### ISSUE TITLE
Add new feature for unique translation table

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#1000]
Currently if you want add translation to your table, you must the follow:

Example with a table named **TestTable**:
- Set **IsTranslated** attribute to true on a column that will be translated.
- Create a table with the name **TestTable_Trl**.
- Add support to **Sychronize Terminology** process for it.
- Add Tab for translation.
- Add A translation view **TestTable_v** and **TestTable_vt** (if apply).

I propose the follow:

- Create Table:
- Name: AD_Translation
- Columns:
  - AD_Translation_ID: Identifier.
  - AD_Language: Language Reference.
  - AD_Table_ID: Table referenced to be translated.
  - AD_Column_ID: Column referenced to be translated.
  - Record_ID: Record.
  - Value: Translation Value.
  - Description: Internal Description for translation.
- Change Lookup reference: Change reference for get translation from **TableName_Trl** to **AD_Translation**.
- Add Support for new table on **Synchronize Terminology** process and deprecate old tables.
- Add Support for new table on **Language Maintenance** process and deprecate old tables.
- Add a Popup option menu for set value for translation on columns flagged as **IsTranslated**.
- Add support on **Report Engine** for get translation from table when a client table is flagged as translated.
- Migrate data from translation tables to new translation table.

**Comment by marcalwestf** [comment]
has this been merged into branch release/3.9.0? I'd like to test it, but can't find it. Nor I can't find the commit in hotfix/3.8.0#002.
Also, instructions to test would be nice to have.

**Comment by yamelsenih** [comment]
Hi @marcalwestf it is a new feature, i add a neww branch for it: [feature/#1000_TranslationForUniqueTable](https://github.com/adempiere/adempiere/compare/feature/%231000_TranslationForUniqueTable)

**Comment by yamelsenih** [comment]
It is under development

**Comment by yamelsenih** [comment]
I will to close it. Reason:
- This will apply with a change of struct for translation.
- The load is very lazy when all translation are over same table
- Is better use a NoSQL DB
