### ISSUE TITLE
The Attribute Set Instance is mandatory,  not working rightly 

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#1002]
Currently Adempiere supports the handling of attribute instances which may be mandatory or not, it is possible to exclude some data models to omit the configuration of the attribute instance validation.

![captura de pantalla 2017-04-24 a la s 14 46 28](https://cloud.githubusercontent.com/assets/786968/25355635/2b4beb04-28ec-11e7-81d7-72ab2f628496.png)

**Comment by e-Evolution** [comment]
Test 1 .- Create a new product with set of attributes, that does not generate instances but the instances is mandatory. the result should fail if an instance attribute not is set.

**Comment by e-Evolution** [comment]
Test 2 .- Create a new product with set of attributes, that does not generate instances but the instances is not mandatory. the result should save of product  if an instance attribute not is set.

**Comment by e-Evolution** [comment]
Test 4.- Create a sales order with mandatory set instance.

**Comment by e-Evolution** [comment]
Test 5.- Create a sales order without mandatory set instance.

**Comment by e-Evolution** [comment]
Test 6.- Create a purchase  order with mandatory set instance.

**Comment by e-Evolution** [comment]
Test 7.- Create a purchase  order without mandatory set instance.

**Comment by e-Evolution** [comment]
Test 8.- Create material receipt with mandatory set instance.

**Comment by e-Evolution** [comment]
Test 9.- Create material receipt without mandatory set instance.

**Comment by e-Evolution** [comment]
Test 9.- Create inventory move with mandatory set instance.

**Comment by e-Evolution** [comment]
Test 11.- Create inventory move without mandatory set instance.

**Comment by e-Evolution** [comment]
Test 12.- Create Physical inventory  with mandatory set instance.

**Comment by e-Evolution** [comment]
Test 13.- Create Physical inventory  without mandatory set instance.

**Comment by e-Evolution** [comment]
Test 14.- Create Manufacturing entry and issue  with mandatory set instance.

**Comment by e-Evolution** [comment]
Test 15.- Create Manufacturing entry and issue  without  mandatory set instance.

**Comment by mckayERP** [comment]
Hi Victor

I have a fix for this posted in another branch.   Suggest it be left for
the next release as it also involves replacing the method of lifo/fifo
tracking which uses ASI values.  It's a bit involved.

Mike

**Comment by e-Evolution** [comment]
Hi @mckayERP , where can found this branches , I am now testing my implementation to solve this user can be we have same approaches , In anyway is good review

Please send a pull request with your propose
