### ISSUE TITLE
i want to create a sequence for Gl_Category like document sequence functionality in Adempiere?

### ISSUE THREAD

**Issue by AbdulfattahHussein3** [adempiere/adempiere#1003]
Adempiere provides a document sequence for all documents , i want to establish a sequence for gl_category and show the sequence in a field in cash journal window

**Comment by yamelsenih** [comment]
Hi @AbdulfattahHussein3 you can create a DocumentNo and C_DocTypeTarget_ID column on C_Cash table, with it change the documentNo is setted from standard document sequence of ADempiere

**Comment by AbdulfattahHussein3** [comment]
Hi Yamel Senih,
Thank You  For  your response ,


​

2017-04-24 23:04 GMT+02:00 Yamel Senih <notifications@github.com>:

**Comment by yamelsenih** [comment]
I will add a changes for use the payment as cash. Is good and easy handle the deposit and prepay from payment as cash instead of **C_Cash**.

When i are ok i will write here for your information
