### ISSUE TITLE
Bad size for processing dialog on ZK Web UI

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#1004]
Currently when a process is running without show help or if you process a document, it show a dialog with ***Processing...Please Wait...*** text with a big size.
![issue63](https://cloud.githubusercontent.com/assets/2333092/25358399/4a6c3c28-290f-11e7-9098-e78557f069ed.png)

**Comment by Raul-mz** [comment]
[#1004 Fixed error with the size for processing dialog on ZK Web](Fixed error with the size for processing dialog on ZK Web)
