### ISSUE TITLE
Complete Preparer Order Not is Funtional in the POS

### ISSUE THREAD

**Issue by erprafaelrodriguez** [adempiere/adempiere#1007]
Regards Team Adempiere!

 I want Complete an Sales Order whit document type Order Standar from the POS and  it's not possible, The Document is remains in Draft...

![complete prepared order](https://cloud.githubusercontent.com/assets/20327157/25403092/cacb4dbc-29c0-11e7-8c74-718356cfabc0.png)

**Comment by adaxa-steven** [comment]
Process the order, go to payment section, select 'Account' in drop-down under "cash".
order Completes.

**Comment by e-Evolution** [comment]
Thank you @erprafaelrodriguez I solve
