### ISSUE TITLE
When a dialog process is called again from parameters save the FieldVO not is update so when process execute not work 

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#1012]
When a dialog process is called again from parameters save the FieldVO not is update so when process execute not work .

My subjection is that the process that not are of report not should load the from history field because can causing problem , i.e. execute same process to same criterial.

Error introducing when save parameter functionality was introducing

**Comment by yamelsenih** [comment]
Previously the process panel was closed, now it keep opened

**Comment by e-Evolution** [comment]
Hi @yamelsenih I see that it make when the process is a report , this new feature come from Adaxa , but your developer remove , I not understand what the reason I included again to parameter print format and output report.

I think that if the process is a report is nice that no close

**Comment by yamelsenih** [comment]
Hi Victor, it is unnecessary. Nou you can press the search button inside report and it show the process parameter.

**Comment by yamelsenih** [comment]
The search button is worked on ZK and swing UI. If you want open the process parameter dialog just go to search button inside report dialog and ready.

Best regards

**Comment by e-Evolution** [comment]
this is ok when you save of parameters , but for example if I am print account balance and nee change the account each time , not is nice

**Comment by yamelsenih** [comment]
I propose keep the parameter value on dialog from search button. I will go to write it.
