### ISSUE TITLE
The Report Financial show the field Under Line Size but this it missing in ADempiere

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#1015]
The Report Financial show the field Under Line Size but this it missing in ADempiere

Should be include the  Under Line Size field ?

![captura de pantalla 2017-05-01 a la s 16 01 05](https://cloud.githubusercontent.com/assets/786968/25598042/69f406de-2e87-11e7-92a6-60e761aea52b.png)

**Comment by adaxa-steven** [comment]
The "Underline Size" is a redundant field from an earlier implementation.  The underlines and overlines now print the full column width. The printed width of the characters were different so telling it to print a specified number of characters just looked untidy. 
Please check that the "Relative Period To" field is set a null not zero by the migration scripts.  I can not see a system to check it.
regards

**Comment by e-Evolution** [comment]
Thank a lot @adaxa-steven , then no is necessary to including.
