### ISSUE TITLE
Changing projects' layout to prepare Gradle migration 

### ISSUE THREAD

**Issue by sramazzina** [adempiere/adempiere#1016]
In preparation to migrating the entire build system to Gradle we need start some preliminary actions to prepare the environment to the new build environment. The first thing to be done is changing the layout of the projects so that it could be aligned to maven standards. The rationale for this change are summarized below.
- The new layout is strongly needed by Gradle to accomplish its build patterns
- The new layout introduces strict separation between type of files by separating them in different directories. We will have separated directories for Java source code, Java unit tests code, resources and Web resources (html files, css, WEB-INF other). Separated directories for java code, java unit tests code and resources will be part of any project. Web resources will only be present in web related projects (look at the following links for further documentation on  [java projects layout](https://docs.gradle.org/3.5/userguide/java_plugin.html#sec:java_project_layout) and [web projects layout](https://docs.gradle.org/3.5/userguide/war_plugin.html#sec:war_project_layout))
According to the results we had from the [prototype I'm developing](https://github.com/sramazzina/adempiere/tree/sandbox/4.0.0%23001) we can proceed by keeping the actual build system based on ant and but changing the directories layout according to the new one. The rationale for this first phase is to rework only the sub-projects we already migrated successfully that are: base, client, JasperReports, org.adempiere.asset, org.eevolution.cashflow. 

We recognize that this preliminary operation has a big impact on the project but it is strongly needed. We've already prepared the updated ant scripts according to the new directories layout for the project above so we suppose this step will not take longer than a few days.  As soon as the prototype will move forward on other remaining projects the idea is to apply the same strategy until every sub-project's layout will be updated.

**Comment by e-Evolution** [comment]
I think is ok for me adopting of maven structure,  this is same other modern projects

maybe we need to change the ADempiere structure to be more based on components for example all model class I and X should be the first component so I think the modularization should be with an approach to business bounded context based in functionality (Sales Management, Purchase Management, Material management, etc)

We can take the github tags as first  business bounded context.

**Comment by trifonnt** [comment]
+1

**Comment by marcalwestf** [comment]
on Sergio's request, I suggested a meeting on Tuesday , May 16th, at 12:00 GMT.
