### ISSUE TITLE
The multiple selection not are work in ZK for select multiples items

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#102]
In old version cloud  select multiples record to include multiples order line.

1.- Create a sales order
2.- Go sales order line , and click in product field
3.- Select multiples product lined and click ok
4.- The multiples line not is created

**Comment by mckayERP** [comment]
Fixed.  See pull request #104.  WSearchEditor was not sending the array of values to the event listener in GridTabDataBinder where the multiple records are generated.

**Comment by mckayERP** [comment]
Fixed with merge #104.
