### ISSUE TITLE
Financial Report support List Source and List Transaction for report source

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#1023]
Currently the Financial Report  report only support list source to report level not by Report Line , so now you can define the List Source or  List Transaction into report source.

![captura de pantalla 2017-05-09 a la s 00 39 38](https://cloud.githubusercontent.com/assets/786968/25840347/5c6bd4be-3450-11e7-87b5-95fa89a260b1.png)

**Comment by trifonnt** [comment]
Hi Victor,

what do you mean by report level not by row?
Maybe a screenshot will better describe what you want to change?

**Comment by adaxa-steven** [comment]
the field "List Transactions" on the Report Line > Report Source is new to me and does not appear in the Adaxa version.
**
![image](https://cloud.githubusercontent.com/assets/15791084/25934290/2e71659e-3660-11e7-932f-8643c68c36c0.png)

**
I remember Armen talking about adding extra functionality as the Report Source but it was my understanding that Armen's work did not make it into 390.

regards
