### ISSUE TITLE
Error: When we specify the number of periods to be considered in the process parameters "ImportBudget", we have no effect and are created according to the number of periods defined in the schema period. At the end of the process, 12 periods are contemplated instead of 2

### ISSUE THREAD

**Issue by sbouissa** [adempiere/adempiere#1024]
![importbudgetperiods](https://cloud.githubusercontent.com/assets/4325868/25751005/f6a7ca5c-3189-11e7-86d7-36dd60bc5cf4.png)

**Comment by adaxa-steven** [comment]
Hi,
I just tested in adaxa.testadempiere.com .. created file with 12 periods. imported file and selected 2 periods. journal batch was created with a journal for each periods. only 2 journals were created.
Maybe something not copied across correctly?

**Comment by sbouissa** [comment]
Hi, I think the problem is on the line 548 of ImportBudget.java becouse de value of "nopPeriods" is 2 and the glPeriods.size() is 12 so always is changing the limit of the first loop

createJournalLine(journal, journalBatch.getDocumentNo(), periodNo);
            if (noPeriods < glPeriods.size()) - ---> Line 548
                noPeriods++
