### ISSUE TITLE
Add Beginning Balance into of Trial Balance 

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#1026]
Current the Trial Balance not show the Beginning Balance.

Account    Beginning Balance    Debit.      Credit.     Balance.

**Comment by adaxa-steven** [comment]
after discussion with Victor ...
In a report like the following .. or any other accounting fact type report it is required in some jurisdictions to show the opening accounted balance, the opening debit balance and the opening credit balance. the trial balance view only shows the the accounted balance. 
![image](https://cloud.githubusercontent.com/assets/15791084/25977290/f34c288e-36fd-11e7-9516-6cc24cad22d1.png)
If the accounted debit and accounted credit is to be made available then we will need a parameter either in the Account Schema or the Report and Process Parameters to control whether the accounted debit and accounted credit opening balance should be displayed or not.
regards

**Comment by adaxa-steven** [comment]
Hi Victor,
re my comment "If the accounted debit and accounted credit is to be made available then we will need a parameter either in the Account Schema or the Report and Process Parameters to control whether the accounted debit and accounted credit opening balance should be displayed or not."

can you please describe the change you made.
thanks
steven

**Comment by e-Evolution** [comment]
Hi Steven !
I tried this approach to add a new function to get off open balance but is complicated because not is possible indicate the period as mandatory, and currently the trial balance you can be defined by date range.

So I used a report financial using relative period to get an opening balance with  detail.

I modify and improve the the report financial : 

#1023 Financial Report support List Source and List Transaction for report source 
#1028 The Financial Report not work for any User dimension (User 1, User2, User3 , User4) 
#1014 The Report Column not should set the Relative Period To as 0.0 to back compatibility 
#976 Error compatibility with Oracle not should PostgreSQL use native code
