### ISSUE TITLE
NPE when try navigate in tabs for new Table and Column Window

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#1027]
NPE when try navigate in tabs for new Table and Column Window:

The system not refresh rightly tabs and other problem is when you try execute an zoom not open the window and  tab where are of information as in swing client.

![captura de pantalla 2017-05-11 a la s 14 46 36](https://cloud.githubusercontent.com/assets/786968/25969024/178edf84-3659-11e7-9c2a-2ad8d8f80769.png)

![captura de pantalla 2017-05-11 a la s 14 53 37](https://cloud.githubusercontent.com/assets/786968/25969180/a62af688-3659-11e7-8349-63efce53b83b.png)

**Comment by dixon22ma** [comment]
Hi @e-Evolution, i added a validation against null and in this way will display the message indicating that you should select the parent tab

![image](https://cloud.githubusercontent.com/assets/2453563/25971101/1dbb7bc8-3669-11e7-92c8-473e6b24deff.png)

**Comment by yamelsenih** [comment]
Hi, it is worked.
