### ISSUE TITLE
The Financial Report not work for any User dimension (User 1, User2, User3 , User4)

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#1028]
The Financial Report not work with user dimension.

Example 

![captura de pantalla 2017-05-13 a la s 11 45 21](https://cloud.githubusercontent.com/assets/786968/26027339/264e9dfa-37d2-11e7-9484-0cee2bbd54f4.png)

![captura de pantalla 2017-05-13 a la s 11 51 14](https://cloud.githubusercontent.com/assets/786968/26027371/8c6638f0-37d2-11e7-93e1-08358a819701.png)

![captura de pantalla 2017-05-13 a la s 11 46 07](https://cloud.githubusercontent.com/assets/786968/26027343/2a106658-37d2-11e7-875c-fa63a02070b3.png)

![captura de pantalla 2017-05-13 a la s 11 46 50](https://cloud.githubusercontent.com/assets/786968/26027346/2dbd8dee-37d2-11e7-9834-78febb33cdae.png)

![captura de pantalla 2017-05-13 a la s 11 47 11](https://cloud.githubusercontent.com/assets/786968/26027349/3130ff56-37d2-11e7-8bdc-6cf66ad22f1c.png)

![captura de pantalla 2017-05-13 a la s 11 47 25](https://cloud.githubusercontent.com/assets/786968/26027352/34a8dc12-37d2-11e7-8b74-b12bf30dcd35.png)

![captura de pantalla 2017-05-13 a la s 11 47 35](https://cloud.githubusercontent.com/assets/786968/26027356/388dfed4-37d2-11e7-9a1f-cc35f57f46dd.png)

**Comment by e-Evolution** [comment]
Currently the the MTreeReport not implement the Tree User 1 , 2 , 3 , 4

**Comment by adaxa-steven** [comment]
this report in adaxa.testadempiere.com
![image](https://cloud.githubusercontent.com/assets/15791084/26031250/bb376f7c-38af-11e7-9b0e-ddf143692d18.png)

with these columns
![image](https://cloud.githubusercontent.com/assets/15791084/26031255/f8a656ca-38af-11e7-9d34-c4bf798a9039.png)
with the column report source defined like this (where User List 1 is being used as Dept/CostCentre
![image](https://cloud.githubusercontent.com/assets/15791084/26031261/1dad75a2-38b0-11e7-9413-55cb115f82cc.png)

creates a report which shows the data for user list1  (Sales is the only not-null that has data)
![image](https://cloud.githubusercontent.com/assets/15791084/26031272/65f18790-38b0-11e7-900a-dafc7f8bb67e.png)

so. it works in the adaxa code .. but the adaxa code does not have userlist3 and userlist4 added ... could that be the reason for the problem?

**Comment by e-Evolution** [comment]
Hi Steven 

This not work because adempiere not create a tree herarchical steucture for each user element 

Into the Tree Window exist a way to validate tree but for user dimensión not is supported 

On the other hand the current elements are mixed with Account elements and this not si good 

If i need create a herachical for each dimension not work 

The solution was implement a tree for each dimension 

MTree_U1, and MTree_U2 , etc , this allows define herarchical structure and get totals by each summary level of same was that account element

Have not a tree for each user dimension causes that strange functionality in Account element tree 

My report use a user 1 with columns that is value segment for a budget Account 

And now pero ok

You can check may be you will integrate in adaxa

**Comment by adaxa-steven** [comment]
in adaxa.testadempiere.com

![image](https://cloud.githubusercontent.com/assets/15791084/26031495/1e6f5a42-38b9-11e7-83fe-e1c57fa642d6.png)

![image](https://cloud.githubusercontent.com/assets/15791084/26031500/3da34162-38b9-11e7-93fd-408ee1c1ab5e.png)

it should not show the account codes in a tree based on an Account Element linked to UserList1 but it still let me populate the tree and then create the report.

regards
