### ISSUE TITLE
The t_rv_reconciliation should be a view and was defined as a table

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#1038]
Currently t_rv_reconciliation have an incorrect name not use of standard names for view that is prefix that is RV vs T_RV the prefix T_ is only to temporary tables and not should be using in views

**Comment by marcalwestf** [comment]
I looked at the sources, and the only place I found _t_rv_reconciliation_, was in file _01800_739_UpdateViewWithNewUserDimension.xml_ . It doesn't appear in any .java file.
There is a definition in db/ddutils for Postgres and Oracle: _T_RV_RECONCILIATION.sql_.

I suppose the name can be changed in _01800_739_UpdateViewWithNewUserDimension.xml_ and _T_RV_RECONCILIATION.sql_ (here also changing the file name) to  _rv_reconciliation_. Additionally, in the AD the table  _t_rv_reconciliation_ should be changed to  _rv_reconciliation_.

![20170518_t_view_02](https://cloud.githubusercontent.com/assets/1789408/26226637/75d28898-3bea-11e7-9540-d2b837b4bb92.png)

What I don't know is if views with names starting with T_ are treated in a special way when referenced to in a Print Format. In our case, the view is referenced by the following print format:
![20170518_t_view_01](https://cloud.githubusercontent.com/assets/1789408/26226670/b0661a60-3bea-11e7-98d0-052ff875482d.png)

If there is no consequences, I'd support changing the name to  _rv_reconciliation_ as explained above.

**Comment by pawlbouden** [comment]
The report engine treats tables/views prefixed with T_ specially, by automatically filtering on the AD_PInstance_ID of the current process.  See MQuery.get().

I believe this behaviour may be useful in this instance.

This may also be why there are other views that break the alleged standard (e.g. t_bomline_costs view from libero).

**Comment by e-Evolution** [comment]
Hi

I tested with right name and it work without some error.

the specific prefix T_ is only for Financial Report not for other view report.

About of t_bomline_cost this is a temporality table not a view

**Comment by pawlbouden** [comment]
Hi Victor,

Did you confirm that your modified version filters to only the current AD_PInstance_ID?

Have you changed the definition of t_bomline_costs recently? Because my database thinks it is view:

adempiere=# \dv t_bomline_costs
               List of relations
  Schema   |      Name       | Type |   Owner   
-----------+-----------------+------+-----------
 adempiere | t_bomline_costs | view | adempiere
(1 row)

adempiere=# select version, releaseno from ad_system;
  version   | releaseno 
------------+-----------
 2017-05-01 | 3.9.0
(1 row)

Regards,

Paul

**Comment by e-Evolution** [comment]
Hi Paul!

Thank a lot , I check and application dictionary is wrong 

![captura de pantalla 2017-05-21 a la s 19 14 18](https://cloud.githubusercontent.com/assets/786968/26288521/d05a30ce-3e59-11e7-8bf5-f067b9cad24a.png)

This should be view and with prefix rv_

**Comment by e-Evolution** [comment]
The other approach was implemented for MQuery class and remove static code

if (table.getColumn("AD_PInstance_ID") != null)
		{
			//	BR [ 236 ]
			query.addRestriction(TableName + ".AD_PInstance_ID=" + AD_PInstance_ID, true);
			isTemporaryTable = true;
		}
