### ISSUE TITLE
Edit english and spanish wikipedia pages

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#1039]
Edit english and spanish wikipedia pages

**Comment by yamelsenih** [comment]
Hi @e-Evolution, it is part of 3.9 release? Can you provide more information about it? What you want to make?

**Comment by marcalwestf** [comment]
what is exactly needed?

**Comment by e-Evolution** [comment]
Update the info in Wikipedia

https://es.wikipedia.org/wiki/ADempiere
https://en.wikipedia.org/wiki/Adempiere
