### ISSUE TITLE
Integrate ADempiere Fleet Management System

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#1042]
https://github.com/adempiere/adempiereFMS

Capabilities to include the management of fleet resources (driver, power, equipment, etc) involved in fulfilling orders and shipments.

- Asset lifecycle management
- Driver hire, education, scheduling, and payroll
- Order capture and Customer Relationship Management
- Fleet planning – consolidation, fleet versus common-carrier trade-offs, multi-leg, multi-mode Driver and equipment assignment, and utilization
- Safety and Maintenance
- Fuel control
- Asset tracking
- Vehicle Licensing/ Regulatory compliance
- Asset inventory management at asset pool locations
- Driver dispatch, mobile communications, tracking
- Costing – fleet, external service providers, special services, accessorials
- Payables – driver pay, independent contractors and external service providers
- Billables – bill customers for service, asset usage
- Cost accruals and revenue recognition

![captura de pantalla 2017-05-19 a la s 12 30 34](https://cloud.githubusercontent.com/assets/786968/26259519/023358ea-3c8f-11e7-8094-9987d43522ce.png)

**Comment by PraponAdempiere** [comment]
Thank you, I just read this issue.
