### ISSUE TITLE
The t_bomline_costs should use RV_ prefix to view

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#1045]
current the standard for create view should use rv_t_bomline_costs or rv_bomline_costs

**Comment by yamelsenih** [comment]
Hi @e-Evolution the T_BOMLine have a Temp table? if it is true then you must use the T_ prefix for it.

Is nice to have a flag for define if it have a temp table.

**Comment by e-Evolution** [comment]
Fix in #1054
