### ISSUE TITLE
Add Sequence and changes in Windows of AD

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#105]
In the application dictionary is good have it:
* Parameter sequence tab in process.
* Tab sequence in window.
* Field, Smart Browse Field and Process Parameter reference in Validation Rule window.

The follow images show the result

![issue39](https://cloud.githubusercontent.com/assets/2333092/11290787/1e72db16-8f0c-11e5-92d7-07d00cbf2cbc.png)
![issue40](https://cloud.githubusercontent.com/assets/2333092/11290794/34ecee22-8f0c-11e5-8a26-e68d90324a3a.png)
![issue41](https://cloud.githubusercontent.com/assets/2333092/11290818/4f8bb240-8f0c-11e5-8d49-892010411711.png)

**Comment by e-Evolution** [comment]
Revert Add Sequence and changes in Windows of AD #105
Script do not work I got an error :
org.adempiere.exceptions.AdempiereException: Step 110, Record 54142 was not found in table Tab (106).
Please before of commit need set that  xml script work adempiere seed fresh

**Comment by e-Evolution** [comment]
Yamel! please check you migration script because I found that some window was move of way incorrect, for example you change the field isinsertrecord into of Validation Rule window.
