### ISSUE TITLE
Process Dialog have not scroll bar in zk

### ISSUE THREAD

**Issue by Raul-mz** [adempiere/adempiere#1051]
It is not possible to see all the parameters of the report.
![image](https://cloud.githubusercontent.com/assets/9552217/26363198/5ab1d632-3fae-11e7-9e3d-f52081d96447.png)

**Comment by Raul-mz** [comment]
Now
![image](https://cloud.githubusercontent.com/assets/9552217/26363916/996562de-3fb0-11e7-8735-79b51f749495.png)

**Comment by e-Evolution** [comment]
Hi @Raul-mz what is the reason of removing the save icon?

**Comment by Raul-mz** [comment]
Hi @e-Evolution, the parameters are saved when you type in the field and the report is generated. The save button is not necessary.

**Comment by yamelsenih** [comment]
Hi @Raul-mz it make a error when is running from a window.
![arbol_26](https://cloud.githubusercontent.com/assets/2333092/26450867/7992be7a-4127-11e7-83cb-32d2fd6dc529.png)

<pre>
===========> zkoss.handleError:1130: >>java.lang.NullPointerException
>>	at org.compiere.model.GridTable.getWhereClause(GridTable.java:2250)
>>	at org.compiere.model.GridTable.dataRefresh(GridTable.java:2771)
>>	at org.compiere.model.GridTab.dataRefresh(GridTab.java:963)
>>	at org.compiere.model.GridTab.dataRefresh(GridTab.java:943)
>>	at org.adempiere.webui.panel.AbstractADWindowPanel.updateUI(AbstractADWindowPanel.java:2389)
>>	at org.adempiere.webui.panel.AbstractADWindowPanel.unlockUI(AbstractADWindowPanel.java:2357)
>>... [24]
===========> zkoss.handleError:1130: >>java.lang.NullPointerException
>>	at org.compiere.model.GridTable.getWhereClause(GridTable.java:2250)
>>	at org.compiere.model.GridTable.dataRefresh(GridTable.java:2771)
>>	at org.compiere.model.GridTab.dataRefresh(GridTab.java:963)
>>	at org.compiere.model.GridTab.dataRefresh(GridTab.java:943)
>>	at org.adempiere.webui.panel.AbstractADWindowPanel.updateUI(AbstractADWindowPanel.java:2389)
>>	at org.adempiere.webui.panel.AbstractADWindowPanel.unlockUI(AbstractADWindowPanel.java:2357)
>>... [24]
</pre>

**Comment by Raul-mz** [comment]
Hi @yamelsenih that error is not entered by the commit. see issue #1059

**Comment by yamelsenih** [comment]
Is really @Raul-mz
