### ISSUE TITLE
The Fact_Acct_Balance not include User3 and User4 Ann should be renamed by RV_Fact_Acct_Balance

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#1052]
The Fact_Acct_Balance not include User3 and User4 Ann should be renamed by RV_Fact_Acct_Balance.

Current this view is very old , so that not following of prefix standard for views, my recommendation is rename from Fact_Acct_Balance to RV_ Fact_Acct_Balance

What do you think?

**Comment by adaxa-steven** [comment]
agree.. I see that it was created in 2003 so must have been named badly back then.
