### ISSUE TITLE
Improvement of Report Engine does not comply with backward compatibility. Print format causes exception

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#1053]
After to integrate ADAXA improves around of report engine , not working rightly 

380 Right side  without improves                                                          390 Left side with improves

![captura_de_pantalla_2017-05-23_a_la_s__18_17_00](https://cloud.githubusercontent.com/assets/786968/26380925/fca823be-3fe6-11e7-9595-f01d07dfcfc3.png)

All the current format design not are show rightly

**Comment by e-Evolution** [comment]
-----------> MOrder.load: NO Data found for C_Order_ID=1037734 [1]
===========> ReportEngine.getDocumentWhat: (1) - SELECT dt.DocSubTypeSO, dt.PrintDocument FROM C_DocType dt, C_Order o WHERE o.C_DocType_ID=dt.C_DocType_ID AND o.C_Order_ID=? [85]
org.postgresql.util.PSQLException: ERROR: no existe la columna dt.printdocument
  Position: 25; State=42703; ErrorCode=0
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2412)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2125)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:297)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:117)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:76)
	at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
	at com.sun.proxy.$Proxy2.executeQuery(Unknown Source)
	at org.compiere.print.ReportEngine.getDocumentWhat(ReportEngine.java:1759)
	at org.compiere.print.ReportEngine.get(ReportEngine.java:1511)
	at org.compiere.print.ReportCtl.startDocumentPrint(ReportCtl.java:333)
	at org.compiere.print.ReportCtl.startDocumentPrint(ReportCtl.java:311)
	at org.compiere.print.ReportCtl.start(ReportCtl.java:138)
	at org.compiere.print.ReportCtl.start(ReportCtl.java:105)
	at org.compiere.apps.ProcessCtl.run(ProcessCtl.java:413)
	at java.lang.Thread.run(Thread.java:748)

**Comment by adaxa-steven** [comment]
Hi Victor, 
please tell us the URL of a test system with the up-to-date code so we can review.
thanks
steven

**Comment by marcalwestf** [comment]
hi,
looking at Adaxa's code, there is a commit named _Control order document processing of related docs. Fixes # 380_. 
User/Date of the commit: _Paul Bowden/2012-01-30 22:16_.

See following image:
![20170524_error_printdocument_03](https://cloud.githubusercontent.com/assets/1789408/26423710/eaa3b8f4-408b-11e7-8a03-f37a4899bbd1.png)


This commit has not been applied in ADempiere 3.9.
The conflict with ADempiere 3.9 manifests itself in class _ReportEngine_, method _getDocumentWhat()_. 

In ADempiere 3.9, the column _printDocument_ from table _C_DocumentType_ is accessed, but there is no definition neither in the model (classes _I_C_DocType_ and _X_C_DocType_) nor in the database (table _C_DocumentType_). The Exception is unavoidable.
![20170524_error_printdocument_02](https://cloud.githubusercontent.com/assets/1789408/26423497/1e7c2c98-408b-11e7-962d-0483b7310fc5.png)

The definition of the Element, Reference, Reference list, Column and Field for _printDocument_ is done in the commit above mentioned. The corresponding xml file is _650_Control_shipment_processing.xml_ .

Problem is, the commit does not address only _printDocument_ , but also other issues like

- Automatically create invoice on document completion
- Automatically create shipment on document completion
- Automatically complete invoice on document completion

Which I do not know if it is functionality worthwhile adopting (not that I would be against it, but I do not know the scope).

The question -which perhaps could be best answered by Steven- is: what is the scope of the commit? Is it worthwhile to take the whole functionality or only a part of the commit?

If we would only need the field _printDocument_ and the selection in _ReportEngine_, could we get the xml file _650_Control_shipment_processing.xml_ shortended in a way it complies with the actual code of _ReportEngine_?

If we can't get an answer or we are not sure about it, I'd suggest to take the code of class _ReportEngine_, method _getDocumentWhat()_ from ADempiere Hotfix#002 before integration with repository _adaxaFinReports_ and replace the actual code with it.

**Comment by adaxa-steven** [comment]
Hi Victor,
I am advised that...
"The commit in question relates to our tracker #396
http://redmine.adaxa.com/issues/396
Description ..Add options to Standard Order document types:
1. Create Shipment, 2. Complete Shipment  3.Create invoice  4. Complete invoice  5. Print document
Add create/complete invoice options to shipment document types too.
They have picked up the code changes for (5) but not applied the provided migration.
Regards"

**Comment by adaxa-steven** [comment]
"Problem is, the commit does not address only printDocument , but also other issues like
1....Automatically create invoice on document completion  [assume standard order, generate a shipment, when shipment completes then it automatically creates the invoice}_
2.......Automatically create shipment on document completion [will automatically create a Shipment when sales order is completed
3......Automatically complete invoice on document completion [controls whether the invoice created in point 1 is completed automatically] 
Which I do not know if it is functionality worthwhile adopting (not that I would be against it, but I do not know the scope).
The question -which perhaps could be best answered by Steven- is: what is the scope of the commit? Is it worthwhile to take the whole functionality or only a part of the commit?


4 flags gets added on Document type as shown in picture below...
![image](https://cloud.githubusercontent.com/assets/15791084/26430323/bd54e61c-412f-11e7-94bf-67d33b5ba974.png)

although you can auto generate a shipment from an order with warehouse order with this you also can control by document type whether the Shipment completes.

the main use is the 'auto generate invoice from Shipment' where we also want control over whether completed or not AND we start with a standard order, manually complete the shipment and auto create the invoice (and with extra functionality then the invoice is emailed to multiple contacts as defined in the BP record) 

In my view it is useful extra functionality.  I think some one create a shipment window which also generated the invoice but I never used it but there could be some crossover.

regards

**Comment by marcalwestf** [comment]
The method _getDocumentWhat()_  in class _ReportEngine_ is used in case of Orders and Shipments for getting the type and ID of the document to be printed.

The explanation of how _printDocument_ is handled in class _ReportEngine_, method _getDocumentWhat()_  goes as follows:

For Orders:
- if _printDocument_ has no value in the Document Type of the Order, the **Order** is taken (this would be the case for all legacy document types as they would have no value).
-  if _printDocument_ has the value of _Invoice_ in the Document Type of the Order, the **Invoice** of the order is looked for.
-  otherwise the **Shipment** of the order is looked for.
-  if there is no Invoice nor Shipment found, the original **Order** is taken.

For Shipments:
- if _printDocument_ has no value in the Document Type of the Shipment, the **Shipment** is taken (this would be the case for all legacy document types as they would have no value).
-  if _printDocument_ has the value of _Order_ in the Document Type of the Shipment, the **Order** of the order is looked for.
-  if _printDocument_ has the value of _Invoice_ in the Document Type of the Shipment, the **Invoice** of the order is looked for.
-  if there is no Order nor Invoice found, the original **Shipment** is taken.

This is a good and sound behavior.
The code in class _ReportEngine_ is as explained before. Only missing are the model and xml file for _printDocument_ .

I will take them from the Adaxa repo and commit them to the ADempiere repo.

**Comment by marcalwestf** [comment]
... concerning the additional functionality of defining the documents that automatically would be completed along a Standard Order , I'd suggest to discuss about it and if the decision is favorable, include them. 
Perhaps there are pros and cons...

**Comment by e-Evolution** [comment]
Hi @marcalwestf , I not understand how would use this behavior.

Current ADempiere use Sub Document Type for Sales Order (Standard Order , Warehouse Order , Invoice Order) to validate this behavior.

Then I think that news flags duplicate the  behavior that is good defined and documented.

About of printDocument what is a Text, a Id , I not can detect how is use ?

The main issue in report engine , is that no is generate as before , we need review that other change cause that relative position and rectangle not work as before.

**Comment by marcalwestf** [comment]
The commit concerns only what I explained before.
It does not implement the printing of other documents with Standard Orders. As I put it, this should be discussed -perhaps in other place.

With this commit the Exception as you describe in the initial post is fixed.
Hope that the problem with the rectangle disappears with it.

**Comment by e-Evolution** [comment]
@marcalwestf  I tested the exception now not is show , but the report is generate with same result , I think that other code was modify.

**Comment by marcalwestf** [comment]
There is a reproducible error in http://188.40.37.194:49269/webui/ now.
This one I am about to describe is slightly different than the one @e-Evolution reported in the first place (see beginning post), but it may coincide.
1.- A Print Format with header and an embedded Print Format
2.- The width of the embedded Print Format is wider than the main Print Format.
The first page is displayed normal:
![20170721_adempiere_23](https://user-images.githubusercontent.com/1789408/28757453-c93ee1c2-7540-11e7-8444-9ec6ab52fbc1.png)
3.- Usually in these cases, the excess columns are displayed in a separate page, with the ordering column first.
4.- The error now is that nowadays additionally the header is displayed as it can be seen in the following Manufacturing Order:
![20170721_adempiere_22](https://user-images.githubusercontent.com/1789408/28757454-d34ad40a-7540-11e7-8ca1-8f3f0983c305.png)

**Comment by JobrianTrinidad** [comment]
Hi @marcalwestf 

We've found the problem.  It looks that the code work as designed.  However, we noticed some problems with the Print Format and fixed it on the same Test Machine.

To fix the report. The following steps must be done.
1. Adjust the Header Margin from 0 to 160 
2. Adjust Y Space for Line 220 from 160 to 10

Please attached images for reference.

![morder-8000_page1](https://user-images.githubusercontent.com/22760273/28761708-b597fcac-7604-11e7-9dc8-3a1cecfa5ed4.png)

![morder-8000_page2](https://user-images.githubusercontent.com/22760273/28761710-bb58aa88-7604-11e7-8e6e-671ddd277421.png)

![printformat_maintab](https://user-images.githubusercontent.com/22760273/28761717-c0d0c630-7604-11e7-993f-4fae64fb1559.png)

![printformat_line220](https://user-images.githubusercontent.com/22760273/28761720-c53a5362-7604-11e7-936f-6ebd048af90c.png)
