### ISSUE TITLE
Suggestion to add, Adempiere Rad Form, into the core Adempiere source code.

### ISSUE THREAD

**Issue by ayazbaloch** [adempiere/adempiere#1058]
@e-Evolution, @mckayERP , @yamelsenih  and @trifonnt 

Dear All core team members,
It is my personal suggestion to add the "Adempiere Rad Form", developed by Matteo, source code into the Adempiere. Link is given below for reference.
https://matteo72.wordpress.com/2013/02/21/adempiere-rad-form/

It is nice feature to add.

**Comment by e-Evolution** [comment]
@ayazbaloch , thank a lot to share this code.

I think that ADempiere Rad, I reviewed the code and would be a good way to improve the current IForm API.

however now we avoid the use the customization form because is complex the maintenance, I think that can bee good to improve wonderfully our current Form API.

What do you think @yamelsenih ?

kind regards
Victor

**Comment by yamelsenih** [comment]
Hi @ayazbaloch is good idea it, i think that is better if we take the good changes on the source code and add it functionality to window of ADempiere for run over a dialog, also can add more listener class for events, currently exists only callouts for fields.

**Comment by yamelsenih** [comment]
Best Regards

**Comment by ayazbaloch** [comment]
Thanks all,
To consider this idea, I have already got permission from the source author, here is our mail correspondence regards this codes for your references.

(
Dear Matteo,

Thanks your kind and prompt response, I will discuss it to the core team members, before my suggestion to the Adempiere team it is required your permission, now you allowed me, I'll give them my suggestion.


Ayaz

Sent from Outlook


From: mat.carminati@tiscali.it <mcarminati996@gmail.com>
Sent: Thursday, May 25, 2017 11:23 PM
To: Mohammad Ayaz
Subject: Re: Incorporating Adempiere RAD Form into Adempiere source.
 
Hi Ayaz,

It doesn't depend on me, If the main committers of Adempiere community are interested in this feature I would be very glad to add it in the core code of Adempiere.

Regards

Matteo

On 25/05/2017 22:18, Mohammad Ayaz wrote:
Dear Mat,

I read your blog, https://matteo72.wordpress.com/, I impressed your work regards on Adempiere RAD Form, but these are not part of Adempiere core source code.


Is it possible to you that you could incorporate these source codes into the above mentioned caption title.


Regards,

Ayaz Baloch

)

**Comment by yamelsenih** [comment]
Thank you @ayazbaloch we will working in it for next versions

**Comment by yamelsenih** [comment]
Hi @ayazbaloch can you make a pull request?

**Comment by ayazbaloch** [comment]
No Dear @yamelsenih , not good in java programming, I love Adempiere framework which reduce 80% programming code.
