### ISSUE TITLE
Process Modal Dialog in zk height is not autosize

### ISSUE THREAD

**Issue by Raul-mz** [adempiere/adempiere#1061]
Not all parameters are visible from the modal dialog in zk
![image](https://cloud.githubusercontent.com/assets/9552217/26585984/d46ec300-451b-11e7-94a5-49e61af5e974.png)

**Comment by Raul-mz** [comment]
Now 
![image](https://cloud.githubusercontent.com/assets/9552217/26586199/7994e2c4-451c-11e7-9e42-d7023bada296.png)

![image](https://cloud.githubusercontent.com/assets/9552217/26586586/a13a9c00-451d-11e7-98e3-e0ef0602e544.png)

**Comment by sramazzina** [comment]
Just cloned a fresh copy of the adempiere repo, checked out branch release-3.9.0 and tried to build but the build fails with the following error

   [javac] /Users/sramazzina/Documents/02.OSS/adempiere/zkwebui/WEB-INF/src/org/adempiere/webui/apps/ProcessModalDialog.java:141: error: cannot find symbol
    [javac] 			processPanel.loadLastRunParameter();
    [javac] 			            ^
    [javac]   symbol:   method loadLastRunParameter()
    [javac]   location: variable processPanel of type ProcessPanel
    [javac] /Users/sramazzina/Documents/02.OSS/adempiere/zkwebui/WEB-INF/src/org/adempiere/webui/apps/ProcessModalDialog.java:243: error: method does not override or implement a method from a supertype
    [javac] 	@Override
    [javac] 	^

**Comment by Raul-mz** [comment]
Hi @sramazzina you can test again.

**Comment by yamelsenih** [comment]
It is worked.
