### ISSUE TITLE
Quality Control

### ISSUE THREAD

**Issue by ElPrience** [adempiere/adempiere#1071]
Hi All , i  want  to  know  how quality management  is working  in  ADempiere ,help  me  if  any one understand  the  business of quality management

**Comment by adaxa-steven** [comment]
Hi EIPrince,
what do you mean by 'quality management'?
Years ago we added the following to Request for a customer:
...'importance/urgency' matrix and SLA response times 
... a satisfaction survey to the Request [available if useful to anyone interested] 
... some extensions to Request Type to store defaults when a new Request of is created.

Also a place for quality testing was added to Product and Production.

Perhaps others know of other 'quality' related items?
regards

**Comment by ElPrience** [comment]
Hi adaxa-stevan
I want   to  know  more  about  quality related to  product  and
 production

Regards

**Comment by adaxa-steven** [comment]
Have a look at the Production Light pdf on the adaxa.com website.

**Comment by ElPrience** [comment]
Ok
Thanks
