### ISSUE TITLE
Commissions:  view rv_commissionrundetail does ot consider SalesReps from table C_CommissionSalesRep

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere#1076]
The view rv_commissionrundetail expects only one Sales Representative defined in table C_Commission. But according to the new commission functionality, the table C_CommissionSalesRep also contains Sales Representatives assigned to a commission. 

The view rv_commissionrundetail  hast to be changed so it considers also the entries from table  C_CommissionSalesRep.

**Comment by yamelsenih** [comment]
Hi @marcalwestf it is solved on previous commit.

Best Regard

**Comment by marcalwestf** [comment]
Commit tested with several Sales Representatives assigned in table C_CommissionSalesRep.
Problem solved.
