### ISSUE TITLE
Commission definition: Sales Representative should not be "NOT NULL"

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere#1077]
Right now, the field _Sales Representative_ in window _Commission_  has a NOT NULL cosntraint, which is incorrect, as there is the table C_CommissionSalesRep which also assigns Sales Representatives for a commission.
This constraint should be eliminated.

**Comment by yamelsenih** [comment]
Hi @marcalwestf i test it and worked, see my test:
- Create new Commission without Sales Rep. (Note that Sales Rep. is hide)
![arbol_63](https://cloud.githubusercontent.com/assets/2333092/26812179/26d18768-4a44-11e7-8d7f-847f14e26e23.png)
- See the Table definition:

<pre>
CREATE TABLE c_commission
(
  c_commission_id numeric(10,0) NOT NULL,
  ad_client_id numeric(10,0) NOT NULL,
  ad_org_id numeric(10,0) NOT NULL,
  isactive character(1) NOT NULL DEFAULT 'Y'::bpchar,
  created timestamp without time zone NOT NULL DEFAULT now(),
  createdby numeric(10,0) NOT NULL,
  updated timestamp without time zone NOT NULL DEFAULT now(),
  updatedby numeric(10,0) NOT NULL,
  name character varying(60) NOT NULL,
  description character varying(255),
  c_bpartner_id numeric(10,0),
  c_currency_id numeric(10,0) NOT NULL,
  frequencytype character(1) NOT NULL,
  docbasistype character(1) NOT NULL,
  listdetails character(1) NOT NULL DEFAULT 'N'::bpchar,
  datelastrun timestamp without time zone,
  createfrom character(1),
  processing character(1),
  c_charge_id numeric(10,0) NOT NULL,
  c_commissiongroup_id numeric(10,0) DEFAULT NULL::numeric,
  istotallypaid character(1) DEFAULT 'N'::bpchar,
  isallowrma character(1) DEFAULT 'N'::bpchar,
  CONSTRAINT c_commission_pkey PRIMARY KEY (c_commission_id),
  CONSTRAINT cbpartner_ccommission FOREIGN KEY (c_bpartner_id)
      REFERENCES c_bpartner (c_bpartner_id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT ccharge_ccommission FOREIGN KEY (c_charge_id)
      REFERENCES c_charge (c_charge_id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT ccurrency_ccommission FOREIGN KEY (c_currency_id)
      REFERENCES c_currency (c_currency_id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT c_commission_createfrom_check CHECK (createfrom = ANY (ARRAY['Y'::bpchar, 'N'::bpchar])),
  CONSTRAINT c_commission_isactive_check CHECK (isactive = ANY (ARRAY['Y'::bpchar, 'N'::bpchar])),
  CONSTRAINT c_commission_isallowrma_check CHECK (isallowrma = ANY (ARRAY['Y'::bpchar, 'N'::bpchar])),
  CONSTRAINT c_commission_istotallypaid_check CHECK (istotallypaid = ANY (ARRAY['Y'::bpchar, 'N'::bpchar])),
  CONSTRAINT c_commission_listdetails_check CHECK (listdetails = ANY (ARRAY['Y'::bpchar, 'N'::bpchar]))
)
</pre>
