### ISSUE TITLE
Commission: percentage definition not only as multiplier, but also as percentage

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere#1080]
In Commission definition, the commission to be calculated can only be set as multiplier.
Thus, 5% has to be set as 0.05, 10% as 0.01, 2.5% as 0.025 etc.

This can confuse users; besides, other percentages are defined as numbers in ADempiere (e.g. taxes).

By creating a flag (for example _isPercentage_) in the commission definition the user can be given the choice to define the commission as 0.05 or 5%.

For backward compatibility, the default value should be 'N'.

**Comment by yamelsenih** [comment]
Hi @marcalwestf i add support to it, please test it and close issue.

Best Regard

**Comment by marcalwestf** [comment]
Tested.
