### ISSUE TITLE
Save commission calculation in Commission Detail

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere#1081]
As of now, when a _CommissionRun_ document is executed with the action _Prepare_, the 
_Commission Detail_ is calculated, as can be seen in the following screenshot:
![20170608_commissions_01](https://user-images.githubusercontent.com/1789408/26932785-d393036c-4c21-11e7-8aa7-308e19ef781b.png)

Here, the _Converted Amount_ is the one who will be considered for calculating the commission.

In the end of the algorithm, the _Commission Detail_ lines are scanned and the commission is calculated. The sum is set in _Commission Amount_:
![20170608_commissions_02](https://user-images.githubusercontent.com/1789408/26932900-3b3cb8aa-4c22-11e7-8af3-8e8a7bc5af3a.png)

Though this is correct, the user doesn't know how this amount came to be. He/she has to go line by line in _Commission Detail_ and calculate the commission, write it down, sum up and compare. This is cumbersome and tedious.

This is the reason for this enhancement: create in _Commission Detail_ the column _CommissionAmt_ and calculate for every _Commission Detail_ line the _CommissionAmt_ . The commision calculated in the tab _Commission Amount_ would be the sum of the _Commission Amounts_ of _Commission Details_.

**Comment by yamelsenih** [comment]
Hi @marcalwestf can you test it change?

Best Regard.

**Comment by marcalwestf** [comment]
Tested. Closing Issue.
