### ISSUE TITLE
Add Adaxa's "Quicksheet" Functionality for massive data input

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere#1088]
Many customers complain that ADempiere doesn't offer a tool for massive entry. 
Though it is possible to reduce the fields displayed in a window and set the order to navigate through them, the windows are a compromise between displaying and editing.

@adaxa-steven has kindly offered Adaxa's _Quicksheet_ functionality, which overcomes this problem, as it is designed just to allow for (as the name says) quick and massive entry.

The Quicksheet can be configured to be used in any window.

Here are snapshots of Adaxa's document explaining the usage of Quicksheet:
![20170608_quickseheet_01](https://user-images.githubusercontent.com/1789408/27011113-5b945c1e-4e72-11e7-9709-b3346545fb7d.png)
![20170608_quickseheet_02](https://user-images.githubusercontent.com/1789408/27011112-5b940692-4e72-11e7-9a66-a220b2d30856.png)

**Comment by marcalwestf** [comment]
Here a link to the documentation provided by @adaxa-steven : [02-HowTo - Quick Entry Set-up.pdf](https://github.com/adempiere/adempiere/files/1066429/02-HowTo.-.Quick.Entry.Set-up.pdf)

**Comment by ayazbaloch** [comment]
Thanks @marcalwestf  for providing document. Nice functionality.

**Comment by yamelsenih** [comment]
Hi, i add a branch for integrate it: https://github.com/adempiere/adempiere/tree/feature/%231088_Quichsheet_Functionality

**Comment by Raul-mz** [comment]
[#1088 Add keyboard events functionality for grid when is multi record](https://github.com/adempiere/adempiere/commit/b5859b168809063f6fdbf07ec6cfdaa795d8712d)

**Comment by marcalwestf** [comment]
For anyone who's interested, the ongoing integration is on branch feature/#1088_Quichsheet_Functionality

**Comment by marcalwestf** [comment]
.. as of now, the development is almost finished; FYI you can download the code from https://github.com/erpcya/adempiere/commits/feature/%231088_Quichsheet_Functionality

The Quicksheet form is the same as the tab grid, which makes the look and feel more real.

Here a snapshot of the Quicksheet form:
![20180512_quicksheet_03](https://user-images.githubusercontent.com/1789408/41081480-3a899434-69e8-11e8-93d5-a0f54bfb934e.png)

**Comment by yamelsenih** [comment]
Continue it in: https://github.com/adempiere/adempiere/pull/1828

**Comment by yamelsenih** [comment]
Error try apply XML
<pre>
===========> MMigrationStep.applySQL: Migration 3921 - QuickEntry - 3.9.1 (D) ; Step: 60; Type: SQL.  Application failed. org.postgresql.util.PSQLException: ERROR: cannot change name of view column "preferredwidth" to "preferredwith"
java.sql.BatchUpdateException: Batch entry 2 CREATE OR REPLACE VIEW adempiere.ad_field_vt AS 
 SELECT trl.ad_language,
    t.ad_window_id,
    f.ad_tab_id,
    f.ad_field_id,
    tbl.ad_table_id,
    f.ad_column_id,
    trl.name,
    trl.description,
    trl.help,
    f.isdisplayed,
    f.displaylogic,
    f.displaylength,
    f.seqno,
    f.sortno,
    f.issameline,
    f.isheading,
    f.isfieldonly,
    f.isreadonly,
    f.isencrypted AS isencryptedfield,
    f.obscuretype,
    c.columnname,
    c.columnsql,
    c.fieldlength,
    c.vformat,
    COALESCE(f.defaultvalue, c.defaultvalue) AS defaultvalue,
    c.iskey,
    c.isparent,
    COALESCE(f.ismandatory, c.ismandatory) AS ismandatory,
    c.isidentifier,
    c.istranslated,
    COALESCE(f.ad_reference_value_id, c.ad_reference_value_id) AS ad_reference_value_id,
    c.callout,
    COALESCE(f.ad_reference_id, c.ad_reference_id) AS ad_reference_id,
    COALESCE(f.ad_val_rule_id, c.ad_val_rule_id) AS ad_val_rule_id,
    c.ad_process_id,
    c.isalwaysupdateable,
    c.readonlylogic,
    c.mandatorylogic,
    c.isupdateable,
    c.isencrypted AS isencryptedcolumn,
    c.isselectioncolumn,
    tbl.tablename,
    c.valuemin,
    c.valuemax,
    fgt.name AS fieldgroup,
    vr.code AS validationcode,
    f.included_tab_id,
    fg.fieldgrouptype,
    fg.iscollapsedbydefault,
    COALESCE(f.infofactoryclass, c.infofactoryclass) AS infofactoryclass,
    c.isautocomplete,
    f.preferredwidth AS preferredwith,
    c.ad_chart_id,
    f.isdisplayedgrid,
    f.seqnogrid,
    f.isembedded,
    COALESCE(f.isallowcopy, c.isallowcopy) AS isallowcopy, 
    f.isquickentry
   FROM ad_field f
     JOIN ad_field_trl trl ON f.ad_field_id = trl.ad_field_id
     JOIN ad_tab t ON f.ad_tab_id = t.ad_tab_id
     LEFT JOIN ad_fieldgroup fg ON f.ad_fieldgroup_id = fg.ad_fieldgroup_id
     LEFT JOIN ad_fieldgroup [47]
===========> MigrationStepApply.process: Migration 3921 - QuickEntry - 3.9.1 (D) ; Step: 60; Type: SQL.  Application failed. org.postgresql.util.PSQLException: ERROR: cannot change name of view column "preferredwidth" to "preferredwith"
java.sql.BatchUpdateException: Batch entry 2 CREATE OR REPLACE VIEW adempiere.ad_field_vt AS 
 SELECT trl.ad_language,
    t.ad_window_id,
    f.ad_tab_id,
    f.ad_field_id,
    tbl.ad_table_id,
    f.ad_column_id,
    trl.name,
    trl.description,
    trl.help,
    f.isdisplayed,
    f.displaylogic,
    f.displaylength,
    f.seqno,
    f.sortno,
    f.issameline,
    f.isheading,
    f.isfieldonly,
    f.isreadonly,
    f.isencrypted AS isencryptedfield,
    f.obscuretype,
    c.columnname,
    c.columnsql,
    c.fieldlength,
    c.vformat,
    COALESCE(f.defaultvalue, c.defaultvalue) AS defaultvalue,
    c.iskey,
    c.isparent,
    COALESCE(f.ismandatory, c.ismandatory) AS ismandatory,
    c.isidentifier,
    c.istranslated,
    COALESCE(f.ad_reference_value_id, c.ad_reference_value_id) AS ad_reference_value_id,
    c.callout,
    COALESCE(f.ad_reference_id, c.ad_reference_id) AS ad_reference_id,
    COALESCE(f.ad_val_rule_id, c.ad_val_rule_id) AS ad_val_rule_id,
    c.ad_process_id,
    c.isalwaysupdateable,
    c.readonlylogic,
    c.mandatorylogic,
    c.isupdateable,
    c.isencrypted AS isencryptedcolumn,
    c.isselectioncolumn,
    tbl.tablename,
    c.valuemin,
    c.valuemax,
    fgt.name AS fieldgroup,
    vr.code AS validationcode,
    f.included_tab_id,
    fg.fieldgrouptype,
    fg.iscollapsedbydefault,
    COALESCE(f.infofactoryclass, c.infofactoryclass) AS infofactoryclass,
    c.isautocomplete,
    f.preferredwidth AS preferredwith,
    c.ad_chart_id,
    f.isdisplayedgrid,
    f.seqnogrid,
    f.isembedded,
    COALESCE(f.isallowcopy, c.isallowcopy) AS isallowcopy, 
    f.isquickentry
   FROM ad_field f
     JOIN ad_field_trl trl ON f.ad_field_id = trl.ad_field_id
     JOIN ad_tab t ON f.ad_tab_id = t.ad_tab_id
     LEFT JOIN ad_fieldgroup fg ON f.ad_fieldgroup_id = fg.ad_fieldgroup_id
     LEFT JOIN ad_fieldgroup [47]
java.sql.BatchUpdateException: Batch entry 2 CREATE OR REPLACE VIEW adempiere.ad_field_vt AS 
 SELECT trl.ad_language,
    t.ad_window_id,
    f.ad_tab_id,
    f.ad_field_id,
    tbl.ad_table_id,
    f.ad_column_id,
    trl.name,
    trl.description,
    trl.help,
    f.isdisplayed,
    f.displaylogic,
    f.displaylength,
    f.seqno,
    f.sortno,
    f.issameline,
    f.isheading,
    f.isfieldonly,
    f.isreadonly,
    f.isencrypted AS isencryptedfield,
    f.obscuretype,
    c.columnname,
    c.columnsql,
    c.fieldlength,
    c.vformat,
    COALESCE(f.defaultvalue, c.defaultvalue) AS defaultvalue,
    c.iskey,
    c.isparent,
    COALESCE(f.ismandatory, c.ismandatory) AS ismandatory,
    c.isidentifier,
    c.istranslated,
    COALESCE(f.ad_reference_value_id, c.ad_reference_value_id) AS ad_reference_value_id,
    c.callout,
    COALESCE(f.ad_reference_id, c.ad_reference_id) AS ad_reference_id,
    COALESCE(f.ad_val_rule_id, c.ad_val_rule_id) AS ad_val_rule_id,
    c.ad_process_id,
    c.isalwaysupdateable,
    c.readonlylogic,
    c.mandatorylogic,
    c.isupdateable,
    c.isencrypted AS isencryptedcolumn,
    c.isselectioncolumn,
    tbl.tablename,
    c.valuemin,
    c.valuemax,
    fgt.name AS fieldgroup,
    vr.code AS validationcode,
    f.included_tab_id,
    fg.fieldgrouptype,
    fg.iscollapsedbydefault,
    COALESCE(f.infofactoryclass, c.infofactoryclass) AS infofactoryclass,
    c.isautocomplete,
    f.preferredwidth AS preferredwith,
    c.ad_chart_id,
    f.isdisplayedgrid,
    f.seqnogrid,
    f.isembedded,
    COALESCE(f.isallowcopy, c.isallowcopy) AS isallowcopy, 
    f.isquickentry
   FROM ad_field f
     JOIN ad_field_trl trl ON f.ad_field_id = trl.ad_field_id
     JOIN ad_tab t ON f.ad_tab_id = t.ad_tab_id
     LEFT JOIN ad_fieldgroup fg ON f.ad_fieldgroup_id = fg.ad_fieldgroup_id
     LEFT JOIN ad_fieldgroup_trl fgt ON f.ad_fieldgroup_id = fgt.ad_fieldgroup_id AND trl.ad_language::text = fgt.ad_language::text
     LEFT JOIN ad_column c ON f.ad_column_id = c.ad_column_id
     JOIN ad_table tbl ON c.ad_table_id = tbl.ad_table_id
     JOIN ad_reference r ON c.ad_reference_id = r.ad_reference_id
     LEFT JOIN ad_val_rule vr ON vr.ad_val_rule_id = COALESCE(f.ad_val_rule_id, c.ad_val_rule_id)
  WHERE f.isactive = 'Y'::bpchar AND c.isactive = 'Y'::bpchar was aborted: ERROR: cannot change name of view column "preferredwidth" to "preferredwith"  Call getNextException to see other errors in the batch.; State=42P16; ErrorCode=0
	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:148)
	at org.postgresql.core.ResultHandlerDelegate.handleError(ResultHandlerDelegate.java:50)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2126)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:469)
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:791)
	at com.mchange.v2.c3p0.impl.NewProxyStatement.executeBatch(NewProxyStatement.java:743)
	at org.compiere.model.MMigrationStep.applySQL(MMigrationStep.java:356)
	at org.compiere.model.MMigrationStep.apply(MMigrationStep.java:227)
	at org.compiere.process.MigrationStepApply.doIt(MigrationStepApply.java:65)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:175)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:128)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.apps.ProcessCtl.startProcess(ProcessCtl.java:623)
	at org.compiere.apps.ProcessCtl.run(ProcessCtl.java:372)
	at java.lang.Thread.run(Thread.java:745)
caused by: org.postgresql.util.PSQLException: ERROR: cannot change name of view column "preferredwidth" to "preferredwith"; State=42P16; ErrorCode=0
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2412)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2125)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:469)
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:791)
	at com.mchange.v2.c3p0.impl.NewProxyStatement.executeBatch(NewProxyStatement.java:743)
	at org.compiere.model.MMigrationStep.applySQL(MMigrationStep.java:356)
	at org.compiere.model.MMigrationStep.apply(MMigrationStep.java:227)
	at org.compiere.process.MigrationStepApply.doIt(MigrationStepApply.java:65)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:175)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:128)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.apps.ProcessCtl.startProcess(ProcessCtl.java:623)
	at org.compiere.apps.ProcessCtl.run(ProcessCtl.java:372)
	at java.lang.Thread.run(Thread.java:745)

-----------> MPInstance.set_Value: ErrorMsg - Value too long - truncated to length=2000 [47]
</pre>

**Comment by e-Evolution** [comment]
I found some problem with this contribution:

1.- The stock view  for DB that are in path 391/db/ddlutils/oracle/views and 391/db/ddlutils/postgresql/views not was updated with new column isquickentry, and for PostgreSQL only made a copy and paste from DDL native structure database, this nos is good practice, all view and query should be based on SQL99 standard.

2.- No DDL or SQL statement should have as a prefix the schema of the database, this is because Adempiere can be installed in a different scheme than the one of adempiere, if this is the case, the script that prefixes a schema will fail.

the XML Script have view with CREATE OR REPLACE VIEW adempiere.ad_field_v AS  , CREATE OR REPLACE VIEW adempiere.ad_field_vt AS 

@yamelsenih @Raul-mz @marcalwestf 
Please can fix?

**Comment by e-Evolution** [comment]
Problem with Quick Sheet when open icon 

![image](https://user-images.githubusercontent.com/786968/50569995-9249ff80-0d3d-11e9-918e-b5e5351f2fc1.png)


Problem when try adding a product from Physical Inventory Line, the system entry infinite cicle until get overload memory 

![image](https://user-images.githubusercontent.com/786968/50570009-1e5c2700-0d3e-11e9-8f42-3445f6ba223e.png)
