### ISSUE TITLE
Current the Print Pay allows print a check in multiples times

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#1089]
Current the Print Pay allows print a check in multiples times, so when the payments of pay selection are generated and printed not should allow printing again.

**Comment by yamelsenih** [comment]
Hi @e-Evolution please test it, note that is added a new relation type for look:
- Payment Request -> Payment Selection
- Payment Selection -> Payments
- Payment Selection -> Payment Batch
- Payment -> Payment Selection
- Payment -> Payment Batch
- Payment Batch -> Payments
- Payment Batch -> Payment Selection

**Comment by yamelsenih** [comment]
It is worked, if exist a bug please reopen it issue
