### ISSUE TITLE
Look & Feel Corrections - Border for the tool box

### ISSUE THREAD

**Issue by eduardolopezuy** [adempiere/adempiere#1093]
#1041 @sajeevsahadev 
regarding a border for the tool box. Also if the tool box is little projected than the data entry screen, it will be easily noticeable for the users to perform some action.
image
![image](https://user-images.githubusercontent.com/13646479/27091532-c42ab71c-5036-11e7-9fa2-6589bd4ab1d7.png)

**Comment by sajeevsahadev** [comment]
Now the tool boxes are in a separate band, its noticeable and aligned with the current theme. 
![image](https://user-images.githubusercontent.com/6624739/27172810-87ededc2-51c7-11e7-90ca-7d4a12980397.png)

**Comment by rcapecce** [comment]
We suppose this issue its all right. It only has a limit line in the upper.

**Comment by marcalwestf** [comment]
... testing this issue, now it is only a tiny mismatch to the left and to the right, as can be seen in the following images:
![20170702_webui_10](https://user-images.githubusercontent.com/1789408/27771693-4148bddc-5f11-11e7-83fc-cef354932bf6.png)
![20170702_webui_11](https://user-images.githubusercontent.com/1789408/27771694-45c86312-5f11-11e7-8cc8-3a32dfcfd98e.png)

**Comment by marcalwestf** [comment]
... more evidently is in this Smart Browser:
![20170702_webui_20](https://user-images.githubusercontent.com/1789408/27771838-156dcdf8-5f14-11e7-8a9a-ecdc21e3edc9.png)

**Comment by eduardolopezuy** [comment]
@marcalwestf 
I think what you say is not linked to the original issue
