### ISSUE TITLE
Look & Feel Corrections - The border box of date fields and the other fields are little different

### ISSUE THREAD

**Issue by eduardolopezuy** [adempiere/adempiere#1094]
#1041 @sajeevsahadev
The border box of date fields and the other fields are little different. The date fields have little bold border and the other field's border is lite. We can keep uniformity over here.
![image](https://user-images.githubusercontent.com/13646479/27091954-19a01178-5038-11e7-931a-0fa579ed057b.png)

**Comment by rcapecce** [comment]
The difference has been fixed
![image](https://user-images.githubusercontent.com/14218144/27292787-d96504f8-54ea-11e7-8d72-c7e0bfc99f60.png)
