### ISSUE TITLE
Look & Feel Corrections - Fonts are too small to read

### ISSUE THREAD

**Issue by eduardolopezuy** [adempiere/adempiere#1095]
#1041 @sajeevsahadev
Our fonts are too small to read.
![image](https://user-images.githubusercontent.com/13646479/27092038-68e7bb82-5038-11e7-8312-35c648e54a7b.png)

**Comment by rcapecce** [comment]
Please check if the change is correct.
![image](https://user-images.githubusercontent.com/14218144/27341939-1bf9321a-55b5-11e7-9ca0-cdf4a1de3d61.png)

If is correct, I will commit the change.

**Comment by rcapecce** [comment]
Correction commited to feature/add-new-zk-ui
