### ISSUE TITLE
Look & Feel Corrections - The active fields and read only fields are less different in its colors

### ISSUE THREAD

**Issue by eduardolopezuy** [adempiere/adempiere#1096]
#1041 @sajeevsahadev
The active fields and read only fields are less different in its colors. For showing the ReadOnly, can it be more light blue or a different color itself(may be Gray).
![image](https://user-images.githubusercontent.com/13646479/27092102-9f4793be-5038-11e7-8802-2cb9b9bb169e.png)

**Comment by rcapecce** [comment]
Now the difference between both are greater.
![image](https://user-images.githubusercontent.com/14218144/27292989-7de5b518-54eb-11e7-90ca-651d00c14d5a.png)

**Comment by marcalwestf** [comment]
...  the problem I see is that if the icons are set to be black &white (i.e. without the color blue), there would be no distinction.
This issue is related to https://github.com/adempiere/adempiere/issues/1119 and all comments there apply here.
