### ISSUE TITLE
Look & Feel Corrections - Our LEFT alignment Tabs need little more space.

### ISSUE THREAD

**Issue by eduardolopezuy** [adempiere/adempiere#1097]
#1041 @sajeevsahadev
Our LEFT alignment Tabs need little more space.
![image](https://user-images.githubusercontent.com/13646479/27092190-ef915512-5038-11e7-8f60-e7a037a9890d.png)

**Comment by sajeevsahadev** [comment]
The Business Partner window is perfect right now.
![image](https://user-images.githubusercontent.com/6624739/27226477-51841b64-52b0-11e7-85c0-ea0c6ef86933.png)

But in Manufacturing Order Window, a small alignment issue. But its not a big one.
![image](https://user-images.githubusercontent.com/6624739/27226535-94e006fc-52b0-11e7-9f76-6c2863cd2e02.png)

**Comment by marcalwestf** [comment]
... now the Manufacturing Order displays the whole text (it is a matter of taste defining such large tab texts)
![20170622_webui_08](https://user-images.githubusercontent.com/1789408/27459082-b6358fd0-5769-11e7-9a56-21c41e7bdcfe.png)

**Comment by marcalwestf** [comment]
...tested several other windows with large tab texts
![20170622_webui_09](https://user-images.githubusercontent.com/1789408/27459128-f1c50152-5769-11e7-9ff0-67b8e0d129bd.png)
