### ISSUE TITLE
Look & Feel Corrections - Change the gradient image to get total flat design

### ISSUE THREAD

**Issue by eduardolopezuy** [adempiere/adempiere#1098]
#1041 @e-Evolution 
Change the gradient image to get total flat design
![image](https://user-images.githubusercontent.com/13646479/27092983-898317f8-503b-11e7-844f-a5c120810d30.png)

**Comment by rcapecce** [comment]
Change the style of the table heads in an embedded tab
Before
![image](https://user-images.githubusercontent.com/14218144/27656468-6b28a918-5c1f-11e7-976f-df40d4788fcb.png)
Now
![image](https://user-images.githubusercontent.com/14218144/27656494-87dd5248-5c1f-11e7-9205-4aec1b3326dc.png)

The menu gradient was solved in #1041 https://github.com/adempiere/adempiere/commit/837375134b480013446d9466b94150118f7de625#diff-40bafda4eab15ec59116ed0ed81e9767
