### ISSUE TITLE
Look & Feel Corrections - Change the gradient imag, some image for components for combo box , box date and top column image

### ISSUE THREAD

**Issue by eduardolopezuy** [adempiere/adempiere#1099]
#1041 @e-Evolution 
![image](https://user-images.githubusercontent.com/13646479/27093061-bfdff7e4-503b-11e7-848d-9844f8837ab3.png)

**Comment by Raul-mz** [comment]
Now:
![image](https://user-images.githubusercontent.com/9552217/27755452-c4fe79f0-5dbd-11e7-965e-d52038a3872e.png)
