### ISSUE TITLE
Look & Feel Corrections - Orange vertical line

### ISSUE THREAD

**Issue by eduardolopezuy** [adempiere/adempiere#1100]
#1041 @e-Evolution 

On the other hand , before existed an orange vertical line that indicate the user that panel master or detail is active , it was change to gray and now no is clear , My suggestion is change to blue vs current gray
![image](https://user-images.githubusercontent.com/13646479/27094817-df7c10be-5041-11e7-815f-59b12bd5a52e.png)

**Comment by rcapecce** [comment]
This issue is already fixed.

![image](https://user-images.githubusercontent.com/14218144/27200091-d27d2598-51ee-11e7-9ddb-1ae0c0be8ed1.png)

![image](https://user-images.githubusercontent.com/14218144/27200107-eb39b164-51ee-11e7-958e-a94a743c8f28.png)
