### ISSUE TITLE
Look & Feel Corrections - Selection menu , change blue with white fonts

### ISSUE THREAD

**Issue by eduardolopezuy** [adempiere/adempiere#1101]
#1041  @e-Evolution 

selection menu , I think that should be change blue with white fonts
![image](https://user-images.githubusercontent.com/13646479/27094933-3c2927f2-5042-11e7-8dfa-6ae1b3f37a01.png)

**Comment by rcapecce** [comment]
This was solved in #1041 https://github.com/adempiere/adempiere/commit/837375134b480013446d9466b94150118f7de625#diff-394134c4dca3fc8159851f5493a5f26e
