### ISSUE TITLE
RUN_DBExport.bat in Windows 10 is not working

### ISSUE THREAD

**Issue by lbetanzo** [adempiere/adempiere#1103]
Yesterday version was workin OK, today a generate a new version with changes and is not workin it just creates a file of 1k  and Setup.bat delays to much and RUN_Adempiere.bat delays to much and send errors

**Comment by lbetanzo** [comment]
I download the last updates and is working ok

**Comment by yamelsenih** [comment]
I will to close it, thank you for your testing
