### ISSUE TITLE
Look & Feel Corrections -Button and history button tool-tips

### ISSUE THREAD

**Issue by eduardolopezuy** [adempiere/adempiere#1104]
#1041 @ayazbaloch 

toggle button and history button tool-tips, see in image.

![image](https://user-images.githubusercontent.com/13646479/27095211-3a6e1d68-5043-11e7-8faa-ef8aa116608a.png)
![image](https://user-images.githubusercontent.com/13646479/27095219-3e1536d6-5043-11e7-88a3-c044c68b17a2.png)

**Comment by rcapecce** [comment]
This issue was fixed in #1041 https://github.com/adempiere/adempiere/commit/837375134b480013446d9466b94150118f7de625
