### ISSUE TITLE
Look & Feel Corrections -Search window - same color for border.

### ISSUE THREAD

**Issue by eduardolopezuy** [adempiere/adempiere#1105]
#1041 @yamelsenih 
Search window is nice to have the same color for border.
![image](https://user-images.githubusercontent.com/13646479/27095303-8da84260-5043-11e7-9769-07382b281c40.png)

**Comment by Raul-mz** [comment]
now
![image](https://user-images.githubusercontent.com/9552217/27648257-f3a2b3e8-5bfb-11e7-9cd9-b3cd38cdc371.png)
