### ISSUE TITLE
Look & Feel Corrections - The tool bar is not homogeneous

### ISSUE THREAD

**Issue by eduardolopezuy** [adempiere/adempiere#1106]
Blue: New, minimalist.
Red: Old, distinct. Is good if the border on icons are the same.
![image](https://user-images.githubusercontent.com/13646479/27095356-bc5a8f64-5043-11e7-8f30-7cbe70b777de.png)

**Comment by e-Evolution** [comment]
Now use all same style icons

![captura de pantalla 2017-07-02 a la s 01 13 08](https://user-images.githubusercontent.com/786968/27767646-aadda22e-5ec3-11e7-893d-33e005c5ff08.png)
