### ISSUE TITLE
Look & Feel Corrections - Lookup element

### ISSUE THREAD

**Issue by eduardolopezuy** [adempiere/adempiere#1107]
#1041 @yamelsenih 
Lookup element: The combo box item color is not the same, is old color.
![image](https://user-images.githubusercontent.com/13646479/27095418-ec946f2e-5043-11e7-9ed7-fba8ed3fbd8d.png)

**Comment by Raul-mz** [comment]
Now
![image](https://user-images.githubusercontent.com/9552217/27652360-6720ecf6-5c09-11e7-9d6e-bfbfb5801baf.png)
