### ISSUE TITLE
Look & Feel Corrections - Process Parameter

### ISSUE THREAD

**Issue by eduardolopezuy** [adempiere/adempiere#1108]
#1041 @yamelsenih 
Process Parameter: The left button don't have the same background that right button
![image](https://user-images.githubusercontent.com/13646479/27095467-1bc325ce-5044-11e7-9bd5-c9ea1763d9ba.png)

**Comment by e-Evolution** [comment]
![captura de pantalla 2017-07-02 a la s 02 14 19](https://user-images.githubusercontent.com/786968/27767940-64686abe-5ecc-11e7-83d7-5927df244792.png)

The image now white color
