### ISSUE TITLE
Look & Feel Corrections - Smart Browse

### ISSUE THREAD

**Issue by eduardolopezuy** [adempiere/adempiere#1109]
#1041 @yamelsenih 
Smart Browse:
The top buttons don't have the same background that action buttons (It is because is disabled?).
The lookup for quantity don't have the same background that amount lookup (It is because is disabled?).
![image](https://user-images.githubusercontent.com/13646479/27095504-46feb3a2-5044-11e7-8b55-49800d31530c.png)

**Comment by rcapecce** [comment]
Both are diferent because they are disabled
