### ISSUE TITLE
Look & Feel Corrections - Table

### ISSUE THREAD

**Issue by eduardolopezuy** [adempiere/adempiere#1110]
#1041 @yamelsenih 
Table: the selected color dis the old.
![image](https://user-images.githubusercontent.com/13646479/27095531-6f621d3e-5044-11e7-9e60-1db38cc901f5.png)

**Comment by rcapecce** [comment]
The old color was updated
![image](https://user-images.githubusercontent.com/14218144/27750319-b1b7dbbc-5dad-11e7-9947-3875aebc7275.png)
