### ISSUE TITLE
Look & Feel Corrections - Main menu

### ISSUE THREAD

**Issue by eduardolopezuy** [adempiere/adempiere#1111]
#1041 @yamelsenih 
Main menu: The icons for window, process, report, form, smart browse and other should be more explicit, it help to user to identify each tool.
![image](https://user-images.githubusercontent.com/13646479/27095580-9a1138bc-5044-11e7-96f5-611e9cfd2d3e.png)

**Comment by rcapecce** [comment]
Correction of Menu Icons applied.

![image](https://user-images.githubusercontent.com/14218144/27344591-3b591532-55bd-11e7-9e96-937251b05e6c.png)

![image](https://user-images.githubusercontent.com/14218144/27344611-4f1f08ec-55bd-11e7-9062-081ac9158ec1.png)
