### ISSUE TITLE
Look & Feel Corrections - Option pane image

### ISSUE THREAD

**Issue by eduardolopezuy** [adempiere/adempiere#1112]
#1041 @yamelsenih 

The option pane image don't have the new images
![image](https://user-images.githubusercontent.com/13646479/27095718-0b2a2ae0-5045-11e7-9f19-4075e535a7b4.png)

**Comment by Raul-mz** [comment]
Now:
![image](https://user-images.githubusercontent.com/9552217/27657887-23ab0cd2-5c1c-11e7-9ef4-002a88c7f5bd.png)
