### ISSUE TITLE
Look & Feel Corrections - When field is only read need other background to identify easily this difference

### ISSUE THREAD

**Issue by eduardolopezuy** [adempiere/adempiere#1115]
#1041 @jdaison 
![image](https://user-images.githubusercontent.com/13646479/27097976-5a049d60-504c-11e7-9794-5fbc1f506bf4.png)

**Comment by Raul-mz** [comment]
Now:
![image](https://user-images.githubusercontent.com/9552217/27748596-03082a5e-5d9e-11e7-866e-6ca04a6aab24.png)
