### ISSUE TITLE
Look & Feel Corrections - Icons dont have same style

### ISSUE THREAD

**Issue by eduardolopezuy** [adempiere/adempiere#1116]
#1041 @jdaison 
![image](https://user-images.githubusercontent.com/13646479/27098039-93dcda5c-504c-11e7-84a0-73dacb3b8671.png)

**Comment by marcalwestf** [comment]
... this issue applies to https://github.com/adempiere/adempiere/issues/1134

**Comment by e-Evolution** [comment]
No have same style 

![captura de pantalla 2017-07-01 a la s 15 11 58](https://user-images.githubusercontent.com/786968/27765147-cab12d36-5e6f-11e7-80f8-4b3b08923189.png)
