### ISSUE TITLE
Look & Feel Corrections - Hyperlinks

### ISSUE THREAD

**Issue by eduardolopezuy** [adempiere/adempiere#1117]
#1041 @jdaison 
![image](https://user-images.githubusercontent.com/13646479/27098080-b0780e66-504c-11e7-85c1-6d9e992d355b.png)

**Comment by marcalwestf** [comment]
... I also liked in the former version the underline, which suggested -as it is- that there is a link to the underlying object.

**Comment by marcalwestf** [comment]
..this is the same as https://github.com/adempiere/adempiere/issues/1123 .
They should referred to and closed at the same time.

**Comment by Raul-mz** [comment]
Now:
![image](https://user-images.githubusercontent.com/9552217/27709560-959e535c-5cea-11e7-81eb-e65fcae5aad4.png)
