### ISSUE TITLE
Look & Feel Corrections - Text is hide

### ISSUE THREAD

**Issue by eduardolopezuy** [adempiere/adempiere#1118]
#1041 @yamelsenih 
![image](https://user-images.githubusercontent.com/13646479/27098188-161d6a68-504d-11e7-827f-07b18c4b1967.png)

**Comment by marcalwestf** [comment]
...now the text is displayed:
![20170622_webui_06](https://user-images.githubusercontent.com/1789408/27458573-ecafbcc8-5766-11e7-932e-d4c0fdffdd46.png)
