### ISSUE TITLE
Look & Feel Corrections - More difference between enabled and disabled fields

### ISSUE THREAD

**Issue by eduardolopezuy** [adempiere/adempiere#1119]
#1041 @yamelsenih 
to have more difference between enabled and disabled fields:

Enabled can be more dark (Label and field).
Disabled can be more light (Label and field).
![image](https://user-images.githubusercontent.com/13646479/27098255-51a1c02a-504d-11e7-90ba-e8273753548b.png)

**Comment by marcalwestf** [comment]
...this is a very important issue. Also a must to be solved before releasing.

**Comment by rcapecce** [comment]
Now is more diferent than the previous version

![image](https://user-images.githubusercontent.com/14218144/27486021-83430bba-5805-11e7-998c-e089722dec60.png)

**Comment by marcalwestf** [comment]
@eduardolopezuy , @rcapecce I haven't seen any commit in the repository that solves this issue.
Could you tell me which commit is involved?
Thanks.

BTW, the solution in the image uploaded by @rcapecce looks well....

**Comment by marcalwestf** [comment]
... besides, as can be seen in the following screenshot, the differentiation is too little to be noticed.
In a Complete Sales Order, Sales Representative is for example is editable. This cannot be easily seen .
![20170622_webui_10](https://user-images.githubusercontent.com/1789408/27492952-4e20d336-5805-11e7-9c2f-3a0e3bccba21.png)

Perhaps a more solid Text (similar to the Label) when a field is editable?
In these cases, all other not editable fields like Client should be also faded, even if they are mandatory....

**Comment by marcalwestf** [comment]
As of now, the difference between fields which cannot be edited, and the ones disabled is minimal.
It has to be **clearly** seen when a field can be edited and when not.
Same applies when it **must** be edited.

**Comment by rcapecce** [comment]
Now the disabled fields are with a soft grey background
![image](https://user-images.githubusercontent.com/14218144/27832530-5a437c60-60a5-11e7-83fd-99726ecbd09f.png)

**Comment by rcapecce** [comment]
@marcalwestf, @e-Evolution y @yamelsenih please check the change to the soft grey background

**Comment by marcalwestf** [comment]
@rcapecce : I tested it on several windows and the disabled fields are now recognized at once.
