### ISSUE TITLE
Look & Feel Corrections - Cannot see the save or undo icons highlighted

### ISSUE THREAD

**Issue by eduardolopezuy** [adempiere/adempiere#1120]
#1041 @marcalwestf 
when a record is edited, I cannot see the save or undo icons highlighted. This is usually a huge help to the users.

**Comment by rcapecce** [comment]
This issue was fixed in other issue.

![image](https://user-images.githubusercontent.com/14218144/27487811-23aff838-580b-11e7-91d7-da9efa3a080d.png)
![image](https://user-images.githubusercontent.com/14218144/27487819-2d4588b8-580b-11e7-8690-ca70389be4db.png)
