### ISSUE TITLE
Look & Feel Corrections - The fields should be painted differently than those which can be edited.

### ISSUE THREAD

**Issue by eduardolopezuy** [adempiere/adempiere#1122]
#1041 @marcalwestf 
the fields (including combo boxes) which cannot be edited should be painted differently than those which can be edited. In the test url all fields are depicted always the same way. I think here Swing is a good example to follow.

**Comment by marcalwestf** [comment]
... closing this issue as it is included in https://github.com/adempiere/adempiere/issues/1146
