### ISSUE TITLE
Look & Feel Corrections -cUnderlining of the label to indicate that it is a link would be helpful.

### ISSUE THREAD

**Issue by eduardolopezuy** [adempiere/adempiere#1123]
#1041 @adaxa-steven 
there is nothing to indicate that you can left-mouse-click on the field name and zoom to the underlying record. Underlining of the label to indicate that it is a link would be helpful.
![image](https://user-images.githubusercontent.com/13646479/27098523-3f4b7e88-504e-11e7-8d8c-3cd59cfc4d67.png)

**Comment by marcalwestf** [comment]
..this is the same as https://github.com/adempiere/adempiere/issues/1117 .
They should referred to and closed at the same time.

**Comment by yamelsenih** [comment]
It is duplicated on #1117
