### ISSUE TITLE
Look & Feel Corrections - the icon for window and report are so similar that user does not understand

### ISSUE THREAD

**Issue by eduardolopezuy** [adempiere/adempiere#1124]
#1041 @adaxa-steven 
![image](https://user-images.githubusercontent.com/13646479/27098683-db0f9e94-504e-11e7-94e3-ea4e672bc25e.png)

**Comment by marcalwestf** [comment]
..now they are different and can be distinguished from each other:
![20170622_webui_07](https://user-images.githubusercontent.com/1789408/27458777-fb73b48e-5767-11e7-91c8-723aa78bf759.png)
