### ISSUE TITLE
Look & Feel Corrections - The 'new record' uses black text on blue background 

### ISSUE THREAD

**Issue by eduardolopezuy** [adempiere/adempiere#1125]
#1041 @adaxa-steven 
the 'new record' uses black text on blue background that is not readable. the bottom of the icon is cut off.
![image](https://user-images.githubusercontent.com/13646479/27098728-0003ad30-504f-11e7-9c78-9e9598904224.png)

**Comment by marcalwestf** [comment]
... issue reproduced and agree that icon is less readable and icon is cut off on different browsers.

**Comment by eduardolopezuy** [comment]
The new button is used too in the tool box.
Please in the code reference the clear button.

**Comment by yamelsenih** [comment]
Hi, it is solved yet, see:
![screenshot_20170703_110828](https://user-images.githubusercontent.com/2333092/27798633-ff6d932c-5fdf-11e7-8d40-2cae3bd1a1cb.png)
