### ISSUE TITLE
Look & Feel Corrections - Some fields are slightly wider than others causing uneven right border

### ISSUE THREAD

**Issue by eduardolopezuy** [adempiere/adempiere#1126]
#1041 @adaxa-steven 
some fields are slightly wider than others causing uneven right border ... could look nicer if lined up.
date fields are one width and number fields a different width ... they could be the same.
![image](https://user-images.githubusercontent.com/13646479/27098797-2f3352c2-504f-11e7-988b-be118deec1c8.png)

**Comment by yamelsenih** [comment]
It is the same that #1099

**Comment by Raul-mz** [comment]
Solve with [#1099](https://github.com/adempiere/adempiere/commit/93dbc34053aff1267a00073962bc87721b8479fe)
