### ISSUE TITLE
Look & Feel Corrections - Can the ' X ' to close the window tab be bigger 

### ISSUE THREAD

**Issue by eduardolopezuy** [adempiere/adempiere#1127]
#1041 @adaxa-steven 
Can the ' X ' to close the window tab be bigger .. easier to find with finger or mouse. (the little "x" beside the words 'sales order')
![image](https://user-images.githubusercontent.com/13646479/27098870-600ad492-504f-11e7-8be1-92abfdc422a8.png)

**Comment by marcalwestf** [comment]
@adaxa-steven could you please deliver the new image and the place where it should be placed?
We then would gladly add it.....

**Comment by adaxa-steven** [comment]
Hi Mario, the image we have would be no use because of it colour. I am not trying to avoid the work but I think it could be created by someone working on the revised UI so that is the correct colour, weight and background colour and size .. or if someone tells me that information we can do it.

**Comment by marcalwestf** [comment]
hi Steven,
I support your request that the icon should be bigger.
Do you have by chance the icon and if the additional changes for it?
Thanks

**Comment by adaxa-steven** [comment]
this is just an Arial upper case "X" in white ... seems ok to me

![image](https://user-images.githubusercontent.com/15791084/27813541-f3b03bfe-60b9-11e7-9239-9ce464200693.png)

**Comment by Raul-mz** [comment]
Now:
![image](https://user-images.githubusercontent.com/9552217/28025482-8c8dee7e-6561-11e7-9460-d2be165f3e90.png)
