### ISSUE TITLE
Look & Feel Corrections -  Flat looking

### ISSUE THREAD

**Issue by eduardolopezuy** [adempiere/adempiere#1129]
#1041 @ishanuda
A. If we can give a flat looking to the tab,
B. if we can give a sharp corner look rather than the rounded corner
C. if the new look check box can be some thin similar to this
D. if the upper tab also can be with the little X rather than the round closing with an appropriate design if possible
E. if these drop down also can be seen like similar to this,
F. In here adding some padding to the beginning and end of the text,

And also if all the dark blue colors in icons and highlighted areas, tabs, buttons, drop down lists etc can be like light blue in D section will give a very beauty look and attractive view

in my opinion it would give the flat looking a great meaning....

and also adding some popup messaging system can notify the user some instant messaging
though it is a programming part. would be helpful to the user.

Any way thank you very much all for the hard work done here and taking the application another step forward.

![image](https://user-images.githubusercontent.com/13646479/27154519-b38fc7da-512b-11e7-84f2-a18dd0d8295c.png)

**Comment by Raul-mz** [comment]
Now:
![image](https://user-images.githubusercontent.com/9552217/27754867-8a5f2464-5dba-11e7-9379-8a49828aa685.png)
