### ISSUE TITLE
Look & Feel Corrections -  "private lock" icon is still the old icon.

### ISSUE THREAD

**Issue by eduardolopezuy** [adempiere/adempiere#1131]
#1041 @cro1y

While I think the colour makes it stand out nicely, I doubt it's intentional that the "private lock" icon is still the old icon.
![image](https://user-images.githubusercontent.com/13646479/27154704-647f53d0-512c-11e7-9a8b-1407db478965.png)

**Comment by rcapecce** [comment]
The icon was changed

![image](https://user-images.githubusercontent.com/14218144/27744396-bffe6406-5d95-11e7-8a90-be346a0f77fe.png)
