### ISSUE TITLE
Look & Feel Corrections - POS The icon with dark lines and blue dark no is nice

### ISSUE THREAD

**Issue by eduardolopezuy** [adempiere/adempiere#1133]
#1041 @e-Evolution 

![image](https://user-images.githubusercontent.com/13646479/27154770-b2a1d420-512c-11e7-8e40-97bfb66a3f0e.png)

**Comment by marcalwestf** [comment]
.. agree. They seem blurred and do not stand out at first glance.

**Comment by yamelsenih** [comment]
It use the same icons that toolbar on standard window

**Comment by e-Evolution** [comment]
The icons images now is write color

![captura de pantalla 2017-07-02 a la s 02 14 59](https://user-images.githubusercontent.com/786968/27767939-4e10a768-5ecc-11e7-873d-a7b90cd896db.png)
