### ISSUE TITLE
Look & Feel Corrections - icons black lines and background black

### ISSUE THREAD

**Issue by eduardolopezuy** [adempiere/adempiere#1134]
#1041 @e-Evolution 

The icons black lines and background black no is nice.
![image](https://user-images.githubusercontent.com/13646479/27154893-1860d432-512d-11e7-9f56-56d7584e96de.png)

**Comment by marcalwestf** [comment]
... and the Icons are of different size. 
In the image above, the zoom icon is bigger than the others.

**Comment by marcalwestf** [comment]
..whereas in the following image, the _Delete record_ icon is bigger
![20170622_webui_03](https://user-images.githubusercontent.com/1789408/27457951-d0106e76-5763-11e7-85f1-dc45db541c0f.png)

**Comment by marcalwestf** [comment]
..the background/foreground issue is also addressed here: https://github.com/adempiere/adempiere/issues/1125 .
