### ISSUE TITLE
Look & Feel Corrections - Icons with background black have not to clarity and sharpness

### ISSUE THREAD

**Issue by eduardolopezuy** [adempiere/adempiere#1135]
#1041 @e-Evolution 

The icons with background black have not to clarity and sharpness, some found some meaning?

I think that will good use black and white as icons bars.
![image](https://user-images.githubusercontent.com/13646479/27154939-3e3bec5a-512d-11e7-9894-6951db342cb0.png)

**Comment by marcalwestf** [comment]
... IMO, I'd say that the icons with blue background color makes the window "bumpy".
Moreover, the combo boxes and dates are different, which contribute to this "uneasiness".

The question would be if the buttons keep the blue background color or if they also become as the others?

**Comment by yamelsenih** [comment]
I think that the background is ok now.

**Comment by e-Evolution** [comment]
Now with icon in write mode the look is good
