### ISSUE TITLE
Change Print Table Format to get rid of ugly Cyan

### ISSUE THREAD

**Issue by adaxa-steven** [adempiere/adempiere#1136]
The ancient Compiere Print Table Format produces reports like...
![image](https://user-images.githubusercontent.com/15791084/27158887-c80905ce-51ac-11e7-9c6d-0300d0a644ff.png)

This to me looks very unprofessional. 
Small changes converts it to...
![image](https://user-images.githubusercontent.com/15791084/27158929-ff91038e-51ac-11e7-88ea-9704db993131.png)

the changes to the Print Table format are...
![image](https://user-images.githubusercontent.com/15791084/27158958-2b67be9e-51ad-11e7-9e50-f9c131db748c.png)

Main changes are .. remove Cyan background and green text, set the 'label wrap' (multi line header) flag to Y,

**Comment by testiranje1234** [comment]
Work and with:

Insert into ad_printformat (AD_PRINTFORMAT_ID,AD_CLIENT_ID,AD_ORG_ID,ISACTIVE,CREATED,CREATEDBY,UPDATED,UPDATEDBY,NAME,DESCRIPTION,ISTABLEBASED,ISFORM,AD_TABLE_ID,AD_PRINTPAPER_ID,AD_PRINTCOLOR_ID,AD_PRINTFONT_ID,ISSTANDARDHEADERFOOTER,HEADERMARGIN,FOOTERMARGIN,CREATECOPY,AD_REPORTVIEW_ID,AD_PRINTTABLEFORMAT_ID,PRINTERNAME,ISDEFAULT,JASPERPROCESS_ID,CLASSNAME,ARGS,ISSUMMARY) values (1000010,11,0,'Y',to_date('15-JUN-17','DD-MON-RR'),101,to_date('15-JUN-17','DD-MON-RR'),101,'GardenWorld -> Project Detail Accounting Report',null,'Y','N',657,100,100,130,'Y',0,0,null,131,null,null,'N',null,null,null,'N');

![print_table_format_2](https://user-images.githubusercontent.com/26572325/27256299-fa676b9a-53b0-11e7-8623-92b4fd1523da.png)

but on my test ADempeire 390 realize from 16062017 I was all re-install, which take my half on hour, from download to re-build from code, re-creating oracle schema and re-setup, work insert, but report dont work, rol and rol again and again.

**Comment by adaxa-steven** [comment]
this was the xml migration file that made the changes in our system...

<?xml version="1.0" encoding="UTF-8"?>

-<Migrations>


-<Migration SeqNo="1820" ReleaseNo="3.9.0" Name="Style Change for default Print Table Format" EntityType="D">


-<Step SeqNo="10" StepType="AD">


-<PO Table="AD_PrintTableFormat" Record_ID="100" Action="U" AD_Table_ID="523">

<Data isOldNull="true" Column="Funct_PrintFont_ID" AD_Column_ID="7624">164</Data>

<Data Column="FunctFG_PrintColor_ID" AD_Column_ID="7628" oldValue="116">100</Data>

<Data Column="HdrTextBG_PrintColor_ID" AD_Column_ID="7632" oldValue="109">115</Data>

<Data Column="HdrLine_PrintColor_ID" AD_Column_ID="7617" oldValue="119">100</Data>

<Data Column="HdrStroke" AD_Column_ID="10783" oldValue="2">1.000000000000</Data>

<Data Column="FunctBG_PrintColor_ID" AD_Column_ID="7626" oldValue="108">115</Data>

<Data Column="LineStroke" AD_Column_ID="10787" oldValue="1">0.500000000000</Data>

<Data Column="HdrTextFG_PrintColor_ID" AD_Column_ID="7621" oldValue="119">100</Data>

<Data Column="IsMultiLineHeader" AD_Column_ID="56358" oldValue="false">true</Data>

</PO>

</Step>


-<Step SeqNo="20" StepType="SQL" Parse="Y" DBType="ALL">

<SQLStatement>UPDATE ad_printformatitem SET AD_PrintFont_ID = NULL where ad_printformatitem_id in ( 50636, 50634, 51026, 50418, 50442, 51070, 1885, 1886, 53126, 53127, 53128, 53131, 53123, 53124, 53125, 1949, 1968, 2009, 2148, 51164, 51336, 51074, 51075, 51097, 51098, 51269, 51270, 50059, 51076, 51337, 51212, 51235, 51247, 50474, 50941, 50477, 1244, 1245, 1708, 1709, 1681, 56534, 56535, 56536, 56537, 56539, 56540, 2325, 2326, 980, 981, 982, 983, 984, 985, 986, 987, 54463, 54491, 54485, 54486, 54487, 54488, 51646, 51647, 51648, 1011031); UPDATE AD_PrintFormatItem SET AD_PrintFont_ID = 133 where AD_PrintFormatItem_ID IN (51589, 51590, 51629, 51631); UPDATE AD_PrintFont SET IsDefault ='Y' WHERE AD_PrintFont_ID=163; UPDATE AD_PrintFont SET IsDefault ='N' WHERE AD_PrintFont_ID=130; UPDATE AD_PrintFormat SET AD_PrintFont_ID = 163 WHERE AD_PrintFormat_ID IN ( 50053, 50095, 50195, 50091, 50051, 50038, 50057, 50131, 50132, 50336, 50023, 50022, 50015, 50014, 50019, 50018, 50016, 50017, 50021, 50020, 50032, 50033, 50031, 154, 155, 50000, 50003, 50004, 162, 50013, 50035, 50006, 50007, 167, 50012, 50028, 50027, 50030, 50024, 50029, 50025, 50008, 161, 163, 164, 50026, 134, 142, 124, 153, 156, 120, 121, 118, 119, 126, 125, 122, 123, 143);</SQLStatement>

</Step>

</Migration>

</Migrations

**Comment by yamelsenih** [comment]
This was changed yet
