### ISSUE TITLE
00143_401_UpdateDemandView.xml in ORACLE is not working

### ISSUE THREAD

**Issue by lbetanzo** [adempiere/adempiere#1137]
it fail in the drop view and I did drop the views but I couldnt create the views with the sql comand. send you error of sintaxis

**Comment by yamelsenih** [comment]
Hi @lbetanzo please can you provide more information about it bug?
Please put here the step number or complete log.
Best Regard.

**Comment by yamelsenih** [comment]
Hi @lbetanzo it bug was fixed.

Please test it

**Comment by yamelsenih** [comment]
Hi @testiranje1234 can you review it?

Best Regard

**Comment by yamelsenih** [comment]
I test it when apply all XML for seed and is ok

**Comment by e-Evolution** [comment]
not work I got : 

20:16:57.951   MMigrationStep.apply: Applying migration step: Migration 143 - Update View Demand  #401 - 3.9.0 (EE03) ; Step: 100; Type: SQL.  [1]
20:16:57.951   MMigrationStep.apply: Applying migration step: Migration 143 - Update View Demand  #401 - 3.9.0 (EE03) ; Step: 100; Type: SQL.  [1]
===========> MMigrationStep.applySQL: Migration 143 - Update View Demand  #401 - 3.9.0 (EE03) ; Step: 100; Type: SQL.  Application failed. 
java.sql.BatchUpdateException: se ha producido un error durante el procesamiento por lotes: ORA-06550: line 2, column 46:
PLS-00103: Encountered the symbol "end-of-file" when expecting one of the following:

   * & = - + ; < / > at in is mod remainder not rem return
   returning <an exponent (**)> <> or != or ~= >= <= <> and or
   like like2 like4 likec between into using || multiset bulk
   member submultiset
 [1]
20:16:57.974   MIssue.create: Migration 143 - Update View Demand  #401 - 3.9.0 (EE03) ; Step: 100; Type: SQL.  Application failed. 
java.sql.BatchUpdateException: se ha producido un error durante el procesamiento por lotes: ORA-06550: line 2, column 46:
PLS-00103: Encountered the symbol "end-of-file" when expecting one of the following:

   * & = - + ; < / > at in is mod remainder not rem return
   returning <an exponent (**)> <> or != or ~= >= <= <> and or
   like like2 like4 likec between into using || multiset bulk
   member submultiset
 [1]
20:16:57.974   MIssue.create: Migration 143 - Update View Demand  #401 - 3.9.0 (EE03) ; Step: 100; Type: SQL.  Application failed. 
java.sql.BatchUpdateException: se ha producido un error durante el procesamiento por lotes: ORA-06550: line 2, column 46:
PLS-00103: Encountered the symbol "end-of-file" when expecting one of the following:

   * & = - + ; < / > at in is mod remainder not rem return
   returning <an exponent (**)> <> or != or ~= >= <= <> and or
   like like2 like4 likec between into using || multiset bulk
   member submultiset
 [1]
20:16:57.982   GridField.loadLookup: (SystemStatus) [1]
20:16:57.982   GridField.loadLookup: (SystemStatus) [1]
===========> MMigrationStep.applySQL: Migration 143 - Update View Demand  #401 - 3.9.0 (EE03) ; Step: 100; Type: SQL.  Application failed. 
java.sql.BatchUpdateException: se ha producido un error durante el procesamiento por lotes: ORA-06550: line 2, column 46:
PLS-00103: Encountered the symbol "end-of-file" when expecting one of the following:

   * & = - + ; < / > at in is mod remainder not rem return
   returning <an exponent (**)> <> or != or ~= >= <= <> and or
   like like2 like4 likec between into using || multiset bulk
   member submultiset
 [1]
-----------> MMigration.apply: Migration 143 - Update View Demand  #401 - 3.9.0 (EE03) ; Step: 100; Type: SQL.  Application failed. 
java.sql.BatchUpdateException: se ha producido un error durante el procesamiento por lotes: ORA-06550: line 2, column 46:
PLS-00103: Encountered the symbol "end-of-file" when expecting one of the following:

   * & = - + ; < / > at in is mod remainder not rem return
   returning <an exponent (**)> <> or != or ~= >= <= <> and or
   like like2 like4 likec between into using || multiset bulk
   member submultiset
 [1]
-----------> MMigration.apply: Migration 143 - Update View Demand  #401 - 3.9.0 (EE03) ; Step: 100; Type: SQL.  Application failed. 
java.sql.BatchUpdateException: se ha producido un error durante el procesamiento por lotes: ORA-06550: line 2, column 46:
PLS-00103: Encountered the symbol "end-of-file" when expecting one of the following:

   * & = - + ; < / > at in is mod remainder not rem return
   returning <an exponent (**)> <> or != or ~= >= <= <> and or
   like like2 like4 likec between into using || multiset bulk
   member submultiset

**Comment by testiranje1234** [comment]
Hi Ibetanzo, if you using oracle database you need replace &lt; with > and
&gt; with <
or simple unzip
00143_401_UpdateDemandView.xml.iso
<https://mail.google.com/mail/u/0/?ui=2&ik=f80d631db9&view=att&th=15cde25abac2ceab&attid=0.1&disp=safe&realattid=f_j4ce34mu0&zw>
into seed and RUN_MigrateXML.sh again, on log files errors will gone.
I m including 00143_401_UpdateDemandView.xml
<https://mail.google.com/mail/u/0/?ui=2&ik=f80d631db9&view=att&th=15cde25abac2ceab&attid=0.1&disp=safe&realattid=f_j4ce34mu0&zw>
into migration folder from source and re-build all code, then re-install all
Adempeire and run migratexml, and all work perfect (need 30-45 minutes)
step by step
test_adempiere_390_.pdf
<https://mail.google.com/mail/u/0/?ui=2&ik=f80d631db9&view=att&th=15cde2871a0290b1&attid=0.2&disp=safe&realattid=f_j4ce9a7h1&zw>



<https://mail.google.com/mail/u/0/?ui=2&ik=f80d631db9&view=att&th=15cde25abac2ceab&attid=0.1&disp=safe&realattid=f_j4ce34mu0&zw>

2017-06-25 3:17 GMT+02:00 e-Evolution <notifications@github.com>:

**Comment by yamelsenih** [comment]
It is worked with the last commit
