### ISSUE TITLE
01360_900_4860_FinReportLines.xml in ORACLE FAIL

### ISSUE THREAD

**Issue by lbetanzo** [adempiere/adempiere#1139]
Application failed java.sql.BatchUpdateExeption table or view does not exist

**Comment by yamelsenih** [comment]
Hi @lbetanzo please can you provide more information about it bug?
Please put here the step number or complete log.
Best Regard.

**Comment by lbetanzo** [comment]
I download last night the last updates and I run the RUN_MigrateXML and is runing ok now but iam goin to open another issue because de 02500_1042_FleetManagementSystem.xml in oracle xe does not finish and you canot login in oracle with RUN_Adempiere.bat so I try to login with postgresql and tomcat and is ok I am trying to check this but if you want to login in my computer you can do it via teamviewer or as yo want i have oracle and postgresql and postgresql in runing perfert

**Comment by yamelsenih** [comment]
Hi @lbetanzo i will to close it, thank you for your testing, 

The 02500_1042_FleetManagementSystem.xml have more than 3000 step, it us very hard for processor and is very slow when the process try make a commit, i test it and is ok but is very slow
