### ISSUE TITLE
01441_907_1880_PrintFormatOnDialog.xml in ORACLE FAIL

### ISSUE THREAD

**Issue by lbetanzo** [adempiere/adempiere#1140]
java.sql.BatchUpdateException: se ha producido un error durante el procesamiento por lotes: ORA-01442: column to be modified to NOT NULL is already NOT NULL

**Comment by yamelsenih** [comment]
Hi @lbetanzo please can you provide more information about it bug?
Please put here the step number.
Best Regard.

**Comment by yamelsenih** [comment]
Hi @lbetanzo please test it, it are resolved

**Comment by yamelsenih** [comment]
Hi @testiranje1234 can you review it?

Best Regard

**Comment by yamelsenih** [comment]
I test it when apply all XML for seed and is ok
