### ISSUE TITLE
New Report for view Open Item To Date

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#1144]
Currently exist a report for view the open items, it is **Menu** -> **Open Items** -> **Open Items**, it is nice and allow view the open item with current date, but if you can see a document that is paid the last month it don't can view in the report.

I will add a report for view the open item to date, with it you can see old open item on a date.
Example:

- Document: **5000**
- Date: **2017-01-01**
- Payment Date: **2017-03-01**

It **Open Irem** report is running now 2017-06-19, it document never is showed.

With **Open Item To Date** report, just set **To Date** parameter to 2017-02-04 by example and the document ishere.

**Comment by marcalwestf** [comment]
Tested in Garden World and other databases 
Running the report with different dates yields -as expected- different results:

1.- Open items as of Mai 15th, 2016
![20170620_openitemstodate_01](https://user-images.githubusercontent.com/1789408/27355559-b200508c-55c8-11e7-87f2-22f2fa7fa8c6.png)


2.- same report as of January 1st , 2017
![20170620_openitemstodate_02](https://user-images.githubusercontent.com/1789408/27355588-d5fe8904-55c8-11e7-8d0e-f027f5b395e2.png)

**Comment by marcalwestf** [comment]
FYI: the Parameters look the same as Open Items, with the difference of the last one, which is the date you want to run it to:
![20170620_openitemstodate_03](https://user-images.githubusercontent.com/1789408/27355857-ab3e7444-55c9-11e7-9f12-077fe1c9407f.png)

**Comment by yamelsenih** [comment]
Thank you @marcalwestf i will to close it
