### ISSUE TITLE
Look and Feel Correction - empty mandatory fields do not stand out

### ISSUE THREAD

**Issue by adaxa-steven** [adempiere/adempiere#1146]
Hi
I added a sales order and failed to fill in the sales rep field but there is no coloured background to draw your eye to the empty mandatory field ... just the error message at the bottom of the screen.  If the field went yellow or pink it would be easier for users to see what the problem is.

![image](https://user-images.githubusercontent.com/15791084/27329791-48103df4-55fa-11e7-90b2-5dc938b10515.png)

and even setting the field as 'mandatory overwrite' does nothing to make it more visible.

**Comment by marcalwestf** [comment]
... I can reproduce this behavior with any window.
This is one of the issues that must be corrected before releasing the WebUI.

**Comment by marcalwestf** [comment]
...ideally it should behave like Swing, where it is very clear which fields are 
1.- mandatory and not yet filled (in the image: Organization, Business Partner, BP location, Sales Rep)
2.- mandatory and already filled (Client, Doc Type, Date...)
3.- not mandatory, editable (Description...)
4.- not editable (currency)

It seems they work also with **background color**.

![20170622_webui_11](https://user-images.githubusercontent.com/1789408/27494122-b1110156-5809-11e7-99be-d4a3322a8bbe.png)

**Comment by Raul-mz** [comment]
Now:
![image](https://user-images.githubusercontent.com/9552217/27708214-291664ee-5ce6-11e7-8a6f-d77ccd616557.png)

**Comment by marcalwestf** [comment]
... something must be missing, because with the latest changes, the records are displayed differently than @Raul-mz reports:
![20170702_webui_15](https://user-images.githubusercontent.com/1789408/27771663-ab712e3e-5f10-11e7-9657-48a5883b0600.png)
![20170702_webui_16](https://user-images.githubusercontent.com/1789408/27771665-b048f7e8-5f10-11e7-8934-f9184a853cd1.png)

**Comment by Raul-mz** [comment]
Hi @marcalwestf,  the labels change color when the save button is pressed and the field is empty.

**Comment by yamelsenih** [comment]
Hi @marcalwestf it issue is solved yet, see: 
- Mandatory as new
![screenshot_20170703_111903](https://user-images.githubusercontent.com/2333092/27799007-8a00ed8a-5fe1-11e7-9f3e-ba07eb57122c.png)
- Mandatory after trying save
![screenshot_20170703_111920](https://user-images.githubusercontent.com/2333092/27799006-89fc0964-5fe1-11e7-83c6-d3c37b577217.png)

For it: 

> not mandatory, editable (Description...)

Is created a issue: #1119

**Comment by marcalwestf** [comment]
I think I know what happens: the images @yamelsenih and @Raul-mz show are **after** the _save_ button has been pressed and the system tells the user which fields he/she should have filled. 
This is undoubtedly a great help.

Would it be possible that this is the behavior **before** pressing the _save_ button?
This way the users would know from the start which are the field they have to fill, before waiting to press the save _button_ to know it.

**Comment by marcalwestf** [comment]
... and once you have tried to save with missing fields, the label remains red...

**Comment by Raul-mz** [comment]
Reopen for test

**Comment by marcalwestf** [comment]
Tested OK: opened several windows and the mandatory fields are easily recognizable:

![20170704_webui_08](https://user-images.githubusercontent.com/1789408/27847074-d964a75a-60f8-11e7-89c8-7c4fb0705dce.png)
