### ISSUE TITLE
Look and Feel correction - cross and tick boxes different size?

### ISSUE THREAD

**Issue by adaxa-steven** [adempiere/adempiere#1147]
I did not see a ticket on this .. please delete if covered elsewhere

![image](https://user-images.githubusercontent.com/15791084/27330032-3591fec8-55fb-11e7-866a-6f35857d5d48.png)

why is the 'cross' box and the 'tick' box different size?

**Comment by marcalwestf** [comment]
I can reproduce this error and agree to make both boxes of same height.

**Comment by rcapecce** [comment]
The Cancel button icon was fixed
