### ISSUE TITLE
Look & Feel Corrections - Change ADempiere logo on reports

### ISSUE THREAD

**Issue by eduardolopezuy** [adempiere/adempiere#1148]
#1041 
Change ADempiere new logo on reports

![adempiere logo on reports](https://user-images.githubusercontent.com/13646479/27356784-33b48c5c-55e6-11e7-8ad1-84c03dce5ac8.jpg)

**Comment by e-Evolution** [comment]
The logo was updated 
![captura de pantalla 2017-07-02 a la s 00 35 42](https://user-images.githubusercontent.com/786968/27767483-6e91ee92-5ebe-11e7-8278-f60f929d349f.png)
