### ISSUE TITLE
Look & feel suggestions

### ISSUE THREAD

**Issue by liosc** [adempiere/adempiere#1157]
Some changes that could improve, in my opinion, the new look&feel.

- Reduce the height of the top banner bringing "user@role.org" in the same line as "Context Preference ..."
- Favourites, recent items and views are underlined. It is not a clean and light way to show them. It could be better without underlining or with a lighter underline.
- If a recent item text goes to new line, the second line starts at the very left (under icon). It could be better to start more on the right, aligned with first line of text.
- The menu combo box on top left could be in a higher position, aligned with "Menu".
- In the search window (for example opening business partner windows) the new record icon has a bad contrast and the image is cut at the bottom

**Comment by eduardolopezuy** [comment]
Hi @liosc 
For a better management of these issues, I will open them one by one.

**Comment by ignaciomorenoc** [comment]
After using Openbravo ERP during 10 Years I want to share one of the strenghts of its powerfull User interface where we can take tips from:

This Video shows speciffically the grid component wich is a simple way to filter-unfilter, arrange, freeze, organize and sumarize information at a glace. I think that many of this features would improve the Adampiere's UI.

https://www.youtube.com/watch?v=sojV31Z1C6Y

Also review the Menu arrangement: Just 3 buttons to seek menu items and create new ones. No more list of links on the left side.

http://wiki.openbravo.com/wiki/User_Interface_Introduction

Hope this can add some improving ideas.

Regards.
