### ISSUE TITLE
Problems with location address: wrong region and not showing region field

### ISSUE THREAD

**Issue by liosc** [adempiere/adempiere#1158]
I changed a business partner address to an italian location indicating the street, city, postal code and country. It seems the address is recorded with default region "OR".
![image](https://user-images.githubusercontent.com/23416398/27431905-6eae720a-574e-11e7-9801-efc3e09c1abf.png)
![image](https://user-images.githubusercontent.com/23416398/27432057-f7450f8e-574e-11e7-87ca-57b15a0a78c0.png)

If I try to show the address in map nothing appears (I think because it tries to locate Milan in Oregon).
![image](https://user-images.githubusercontent.com/23416398/27432172-5b4967b4-574f-11e7-8a4f-e06a584ab185.png)

In "country Region and City" Italy is defined without region. I changed to true the "Has region" flag and I added a region but when I login again as GardenAdmin I can not see the region field in the business partner address.

**Comment by e-Evolution** [comment]
Duplicate with #1150

**Comment by e-Evolution** [comment]
related #886
