### ISSUE TITLE
Look & Feel Corrections -Reduce the height of the top banner 

### ISSUE THREAD

**Issue by eduardolopezuy** [adempiere/adempiere#1159]
#1041 @liosc 
Reduce the height of the top banner bringing "user@role.org" in the same line as "Context Preference ...

**Comment by marcalwestf** [comment]
@eduardolopezuy do you mean this?
![20170622_webui_01](https://user-images.githubusercontent.com/1789408/27456977-375bee88-5760-11e7-8f1f-683c7ceaeb71.png)
If this is the case, it would make sense for me.

**Comment by yamelsenih** [comment]
Hi @liosc i agree with @marcalwestf

**Comment by liosc** [comment]
Hi @yamelsenih, I got the @marcalwestf comment ("it would make sense for me") as referred to the proposal. It would make sense to put everything on the same line so the banner height can be reduced to gain more space for the page contents. Did I get it wrong?

**Comment by e-Evolution** [comment]
I think the size was reduced and is ok if somebody need more top space then can hide using horizontal line.

![captura de pantalla 2017-07-02 a la s 14 59 29](https://user-images.githubusercontent.com/786968/27773070-14f5f508-5f37-11e7-8d16-9fc933929d7d.png)

**Comment by marcalwestf** [comment]
.. the size was reduced and the bar now takes up the size of the ADempiere logo, which seems OK.
