### ISSUE TITLE
Rename of a table creates a new Sequence

### ISSUE THREAD

**Issue by mckayERP** [adempiere/adempiere#116]
The logic around the creation or modification of Sequences could be improved.  If a table name is changed in the Table & Column window, a new sequence is created.  The logic is in the afterSave() function of MTable.  The connection of the sequence to the table is by the table name.  The logic looks for a sequence with the new name and, if none is found, creates it.  For a changed name, a new sequence will always be created.

**Comment by e-Evolution** [comment]
Is some strange that in some moment you change table name and in consequence the change in sequence name is very strange, but in a good improve
