### ISSUE TITLE
Look & Feel Corrections - If a recent item text goes to new line, the second line starts at the very left (under icon).

### ISSUE THREAD

**Issue by eduardolopezuy** [adempiere/adempiere#1161]
#1041 @liosc 
If a recent item text goes to new line, the second line starts at the very left (under icon). It could be better to start more on the right, aligned with first line of text.

**Comment by marcalwestf** [comment]
...well yes.... and it happens also to "Favorites"
Though it is a minimal change.

**Comment by eduardolopezuy** [comment]
Please @liosc give us an attachment

**Comment by liosc** [comment]
How it is:
![image](https://user-images.githubusercontent.com/23416398/27708071-e4700b92-5d17-11e7-818b-5fbb5e985cf2.png)

how could be:
![image](https://user-images.githubusercontent.com/23416398/27708062-de5769c6-5d17-11e7-92b0-d8c16e1701d3.png)
Besides the underlining (there is another open issue), when a row is long enough to go to a second line, the text stays idented as then line above.

To further improve readability, it could be consider an alternate background color for rows (maybe better than the one in this example):
![image](https://user-images.githubusercontent.com/23416398/27708754-24f2df9e-5d1a-11e7-8b86-9c977354ea17.png)

**Comment by yamelsenih** [comment]
Hi, it is not a change necessary, see the current dashboard for favorite:
![screenshot_20170702_155914](https://user-images.githubusercontent.com/2333092/27773072-7a55141c-5f3f-11e7-92a1-d11c4ca96bb7.png)
It image is from older version, the current dashboard follow standard of it

**Comment by e-Evolution** [comment]
Implemented with new images

![captura de pantalla 2017-07-04 a la s 12 36 00](https://user-images.githubusercontent.com/786968/27839234-73983aec-60b5-11e7-85b1-75f39f0c135d.png)

![captura de pantalla 2017-07-04 a la s 12 37 05](https://user-images.githubusercontent.com/786968/27839244-85bd474e-60b5-11e7-979c-3df758491a0f.png)
