### ISSUE TITLE
Look & Feel Corrections -  Menu combo box

### ISSUE THREAD

**Issue by eduardolopezuy** [adempiere/adempiere#1162]
#1041 @liosc 
The menu combo box on top left could be in a higher position, aligned with "Menu".

**Comment by eduardolopezuy** [comment]
Please  @liosc , give us more information with an attachment

**Comment by liosc** [comment]
How it is:
![image](https://user-images.githubusercontent.com/23416398/27707336-497a99e2-5d15-11e7-88c6-739e62b37762.png)

how could be:
![image](https://user-images.githubusercontent.com/23416398/27707356-55a5a0b8-5d15-11e7-9d8c-ecdc64b1eb74.png)

Some space recovered, the search field is aligned with word "Menu". In my opinion it is more linear, clean and there is more space to expand the menu tree. I don't think the word "lookup" is necessary (it is already hard to see).

**Comment by yamelsenih** [comment]
Hi @liosc it was because lookup label are the same color that background, see the pic:
![screenshot_20170702_161200](https://user-images.githubusercontent.com/2333092/27773149-4dee33de-5f41-11e7-81ef-9cfec9beb5be.png)
