### ISSUE TITLE
Look & Feel Corrections - search window

### ISSUE THREAD

**Issue by eduardolopezuy** [adempiere/adempiere#1163]
#1041 @liosc 
In the search window (for example opening business partner windows) the new record icon has a bad contrast and the image is cut at the bottom

**Comment by marcalwestf** [comment]
this issue is also mentioned in https://github.com/adempiere/adempiere/issues/1125 
When https://github.com/adempiere/adempiere/issues/1125 is closed, this issue should be closed, too.
