### ISSUE TITLE
Look & Feel Corrections - No show the search button with new look

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#1166]
![captura de pantalla 2017-06-22 a la s 14 25 27](https://user-images.githubusercontent.com/786968/27452018-b2e00fee-5756-11e7-8702-d578738806b6.png)

**Comment by marcalwestf** [comment]
.. in some Samrt Browsers the Search button is visible:
![20170622_webui_04](https://user-images.githubusercontent.com/1789408/27458163-f10a52bc-5764-11e7-93cb-f44b2098b6ba.png)

**Comment by marcalwestf** [comment]
![20170622_webui_05](https://user-images.githubusercontent.com/1789408/27458373-e25652ec-5765-11e7-9bf8-15fc3f4e0214.png)

Same applies to Smart Browser _Generate Invoice from Order Line_. It seems that it is not a general issue, but only of the Smart Browser _Create Receipt from Purchase_...
In the Smart Browser, the panel containing the parameters seems to be clipped.

**Comment by marcalwestf** [comment]
another Smart Browser which displays the search button:
![20170622_webui_12](https://user-images.githubusercontent.com/1789408/27497360-65c03f9c-5817-11e7-9405-d761d5f3ae22.png)

**Comment by marcalwestf** [comment]
...it is the Smart Browser that opens when being in a _Material Receipt_ window in the _Drafted_ status, the user ticks the button _Create from Order/RMA_.
The Smart Browser is named _Create Receipt from Purchase Order or RMA_.
I get this :
![20170622_webui_13](https://user-images.githubusercontent.com/1789408/27498947-aa8fe49a-581e-11e7-9fdd-073956135981.png)

What I do get is when I select _Order_, the button disappears almost completely:
![20170622_webui_14](https://user-images.githubusercontent.com/1789408/27498997-ff7af42c-581e-11e7-968c-2a6bac8842d8.png)

..but you see on the right hand a scroll bar which can bring back the button.
This is not user-friendly.
![20170622_webui_15](https://user-images.githubusercontent.com/1789408/27499041-3035a670-581f-11e7-9518-60d23a390bbe.png)

**Comment by Raul-mz** [comment]
this is ok?

**Comment by yamelsenih** [comment]
I will close it

**Comment by e-Evolution** [comment]
Nop the top Icon should use new icon to zoom , selected and delete , I saw same

**Comment by yamelsenih** [comment]
Please @e-Evolution tell us a example

**Comment by rcapecce** [comment]
@yamelsenih, I had updated the old icons, that were only used with dark background in the previous commit.

**Comment by rcapecce** [comment]
@yamelsenih, I add these icons in white color in the last commit for the dark backgrounds

**Comment by Raul-mz** [comment]
Now:
![image](https://user-images.githubusercontent.com/9552217/27754955-10b65fa0-5dbb-11e7-9081-bb82eaad3135.png)

**Comment by yamelsenih** [comment]
The /zkwebui/images/toolbar is missing
