### ISSUE TITLE
02500_1042_FleetManagementSystem.xml not finishing in ORACLE XE

### ISSUE THREAD

**Issue by lbetanzo** [adempiere/adempiere#1169]
I download the latest updates last night  to try the oracle migration and it dosent finish I canot login with oracle  with RUN_Adempiere.bat but  I login to the database with navicat and all the steps related with the migration_ID in the status code they have all is A apply so I dont understand

**Comment by yamelsenih** [comment]
Hi @lbetanzo i test it with a seed from beginning and is ok, have you a correct setup for oracle?

Best Regard

**Comment by e-Evolution** [comment]
I can not replicate , I apply script without problem.

![captura de pantalla 2017-06-27 a la s 09 56 25](https://user-images.githubusercontent.com/786968/27594269-f711e4fa-5b1e-11e7-99c7-353d4fc08143.png)
