### ISSUE TITLE
Look and feel style to ADempiere 390 - Change Swing client ADempiere logo

### ISSUE THREAD

**Issue by eduardolopezuy** [adempiere/adempiere#1172]
Change Swing client ADempiere logo.

**Comment by marcalwestf** [comment]
the logo has been changed, but it was agreed that the sequence _AD_ would be in **italics**.
This applies also to WebUI.
Now it looks as follows:
![20170701_webui_02](https://user-images.githubusercontent.com/1789408/27765407-4198b7dc-5e6d-11e7-8f73-22a9c02cb02c.png)
