### ISSUE TITLE
Calculate forecast - Error org.eevolution.model.MPPForecastDefinition cannot be cast to org.eevolution.model.MPPForecastDefinition

### ISSUE THREAD

**Issue by liosc** [adempiere/adempiere#1173]
Error "**org.eevolution.model.MPPForecastDefinition cannot be cast to org.eevolution.model.MPPForecastDefinition**" trying to calculate forecast.

In "Forecast simulation" I filled all the window field and then pushed the "Calculate forecast" button but the above error appeared. I am not sure to have filled all the tables in the right way but the error message is anyway not user/customer friendly.

![image](https://user-images.githubusercontent.com/23416398/27562837-c40da062-5ace-11e7-893f-0f9e8acfeabb.png)

In log there is no error messages, only this warning "(SeqNo) - Default SQL variable parse failed: @SQL=SELECT NVL(MAX(SeqNo),0)+10 AS DefaultValue FROM AD_PrintFormatItem WHERE AD_PrintFormat_ID=@AD_PrintFormat_ID@".

**Comment by e-Evolution** [comment]
Hi @liosc  fixed with with #1183 , please can check again

**Comment by liosc** [comment]
When I push the "Calculate forecast" button I keep seeing the error message.
![image](https://user-images.githubusercontent.com/23416398/27724455-4df4323c-5d72-11e7-9d01-2f5bf95bc2c1.png)

**Comment by e-Evolution** [comment]
I updated with latest night building
