### ISSUE TITLE
Look and feel style to ADempiere 390 - Change icons on Work Flow

### ISSUE THREAD

**Issue by eduardolopezuy** [adempiere/adempiere#1176]
#1041
![work flows 1](https://user-images.githubusercontent.com/13646479/27646525-37f973e4-5bff-11e7-9f22-bd019bcc1a5d.png)

**Comment by marcalwestf** [comment]
... icon has been changed , but it is the window icon.
Here it is;
![20170702_webui_14](https://user-images.githubusercontent.com/1789408/27771556-e418222c-5f0d-11e7-8cf9-036caa27e1a7.png)

Perhaps it should be the new _workflow_ icon?
Here the new _workflow_ icon:
![20170702_webui_13](https://user-images.githubusercontent.com/1789408/27771557-f8dc20f0-5f0d-11e7-975c-2f8649fb6741.png)

**Comment by yamelsenih** [comment]
Hi @marcalwestf please test the menu icon

**Comment by marcalwestf** [comment]
Now the _workflow_ icon in the main menu is OK:

![20170702_webui_22](https://user-images.githubusercontent.com/1789408/27773505-6a3aa53a-5f38-11e7-91ea-7b83b75fca55.png)

**Comment by marcalwestf** [comment]
.... remains only the icons within the workflow

**Comment by marcalwestf** [comment]
...just as an information: in the display, every object has the icon it belongs to: windows, reports, processes:
![20170702_webui_27](https://user-images.githubusercontent.com/1789408/27799917-63b102a8-5fd4-11e7-9fb9-1778a55b42b4.png)

..only the Smart Browsers have a funny icon (a big pink dot):
![20170702_webui_26](https://user-images.githubusercontent.com/1789408/27799958-8b3059c8-5fd4-11e7-994b-182e338c1869.png)

**Comment by yamelsenih** [comment]
Hi @marcalwestf i am working in it issue

**Comment by yamelsenih** [comment]
Hi @marcalwestf it is was already solved, see:
![screenshot_20170703_145536](https://user-images.githubusercontent.com/2333092/27805096-9071d4da-6000-11e7-8d96-d8ff0cca2235.png)

**Comment by marcalwestf** [comment]
tested and I can confirm that all menu objects are displayed with their respective icons.
![20170702_webui_28](https://user-images.githubusercontent.com/1789408/27806995-30fb1b60-5ffb-11e7-8b3e-df172a04937c.png)

Well done @yamelsenih
