### ISSUE TITLE
Look and feel style to ADempiere 390 - Change icons activities

### ISSUE THREAD

**Issue by eduardolopezuy** [adempiere/adempiere#1177]
#1041
![activities](https://user-images.githubusercontent.com/13646479/27652526-7f4a6240-5c12-11e7-8ce9-64f0a7e68d17.jpg)

**Comment by e-Evolution** [comment]
The change was implement with change of images for 16 pixeles 

![captura de pantalla 2017-07-04 a la s 12 39 15](https://user-images.githubusercontent.com/786968/27839306-dfa36e0a-60b5-11e7-88bd-17df0a81bf88.png)
