### ISSUE TITLE
Look & Feel Corrections - Background of the tabs now are differents colors

### ISSUE THREAD

**Issue by eduardolopezuy** [adempiere/adempiere#1178]
#1041 
the background of the tabs now are differents colors (Grey at the upper tabs and skyblue at the back of the side ones. This could be better with the same soft grey.
![ui blue sky](https://user-images.githubusercontent.com/13646479/27655699-9bb7d1d8-5c1c-11e7-97f8-f6642fa61401.png)

**Comment by rcapecce** [comment]
Color Correction Applied
