### ISSUE TITLE
Look & Feel Corrections - Skyblue lines of the limit of the menu and the header

### ISSUE THREAD

**Issue by eduardolopezuy** [adempiere/adempiere#1179]
#1041 
skyblue lines of the limit of the menu and the header could be blue as the background of the header. this could improve the flat desing of the page.
![ui 2](https://user-images.githubusercontent.com/13646479/27655922-79f63e58-5c1d-11e7-875f-f2abfd47781f.jpg)

**Comment by rcapecce** [comment]
The color was fixed
![image](https://user-images.githubusercontent.com/14218144/27843231-e1ff9a5c-60e7-11e7-88e9-583348e23bbb.png)
