### ISSUE TITLE
Look and Feel: correct admin page 

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#1184]
Is necessary update new icons and colors

![captura de pantalla 2017-06-29 a la s 19 23 06](https://user-images.githubusercontent.com/786968/27715961-6dd22dec-5d00-11e7-8491-7cc12b62ba0c.png)

**Comment by rcapecce** [comment]
Corrections applied to the admin page

![image](https://user-images.githubusercontent.com/14218144/27753741-3a02496c-5dbd-11e7-9524-382e14115646.png)

**Comment by eduardolopezuy** [comment]
The blue are diferents.

**Comment by rcapecce** [comment]
The button image was changed

Now:
![image](https://user-images.githubusercontent.com/14218144/27807859-0d39c068-601a-11e7-8302-64504e30bb66.png)
