### ISSUE TITLE
Product Info hides important qty info off the screen on right side

### ISSUE THREAD

**Issue by adaxa-steven** [adempiere/adempiere#1185]
in a sales order line when I open the product info to check qty on hand I can not see it because it has fallen of the right hand side of the page.  I realise it is dislpayed at the bottom but that only lets me see one product at a time. Why not display the qty available close to the left hand side of the form where the users are looking? 

also not that the icons at bottom left are displaying as black text on dark blue backgrond... this is from a build  yesterday.

![image](https://user-images.githubusercontent.com/15791084/27720110-e72cbbe0-5d9a-11e7-9488-1a237440eed7.png)

**Comment by yamelsenih** [comment]
Hi @adaxa-steven 
It was solved
> also not that the icons at bottom left are displaying as black text on dark blue backgrond... this is from > a build yesterday.
![screenshot_20170826_113740](https://user-images.githubusercontent.com/2333092/29742778-1fd845b0-8a53-11e7-97ff-5ca8df466762.png)

For it, i will assign to @Raul-mz for ajust the size of column:
>in a sales order line when I open the product info to check qty on hand I can not see it because it has fallen of the right hand side of the page. I realise it is dislpayed at the bottom but that only lets me see one product at a time. Why not display the qty available close to the left hand side of the form where the users are looking?
