### ISSUE TITLE
Look and Feel Issues... Calendar selected date is black on blue = not readable

### ISSUE THREAD

**Issue by adaxa-steven** [adempiere/adempiere#1188]
![image](https://user-images.githubusercontent.com/15791084/27720863-c35024d2-5d9f-11e7-8b0d-451552467b08.png)

**Comment by Raul-mz** [comment]
Now:
![image](https://user-images.githubusercontent.com/9552217/27807927-3d0f053a-6012-11e7-871c-2806ee494293.png)
