### ISSUE TITLE
Payment Section shows 'Period Closed' in error?

### ISSUE THREAD

**Issue by adaxa-steven** [adempiere/adempiere#1189]
Payment Section shows 'Period Closed' in error?
June 2017 is open
![image](https://user-images.githubusercontent.com/15791084/27721051-2c503462-5da1-11e7-8f2f-64f2aa87e7bb.png)

a Payment selection in June 2017 fails with Period closed error  (cache was reset)
Also, no Target Document Type is selectable
![image](https://user-images.githubusercontent.com/15791084/27721074-5c8501da-5da1-11e7-84f0-a388e38722d2.png)

**Comment by testiranje1234** [comment]
Purchase Requisition is permanently closed with ui  cant open, at the end
of pic.
[image: Убаци слике 1]

2017-06-30 6:36 GMT+02:00 adaxa-steven <notifications@github.com>:

**Comment by adaxa-steven** [comment]
I do not understand what a Purchase Requisition has to do with paying 2 overdue completed vendor invoices that were raised for Charges.   What have I missed?

**Comment by yamelsenih** [comment]
Hi @adaxa-steven the payment selection now is a document with workflow and document type, tou can see the change [here](https://github.com/adempiere/adempiere/issues/297), also the wiki is [here](http://wiki.adempiere.net/Spin_Contribution:_FR:_Payment_Selection_Like_Document), 

I can watch that you don't have a open period for Payment Selection (Document Base Type), see:
![screenshot_20170826_110434](https://user-images.githubusercontent.com/2333092/29742513-9bca18ce-8a4e-11e7-8f71-399f456417af.png)
![screenshot_20170826_110456](https://user-images.githubusercontent.com/2333092/29742514-9bcf4e70-8a4e-11e7-9008-f7e53804b549.png)
![screenshot_20170826_110517](https://user-images.githubusercontent.com/2333092/29742515-9bcffb5e-8a4e-11e7-8292-e47655192760.png)
![screenshot_20170826_110535](https://user-images.githubusercontent.com/2333092/29742516-9bd4749a-8a4e-11e7-8449-c217b328095a.png)

Garden don't have Payment Selection for period control by default.

**Comment by adaxa-steven** [comment]
Hi Yamel
in a standard 390 test system I can see no document base type for Payment Selection, no document type fpr Payment Selection.  These nee to be added.  I could not see what I was supposed to select as the Document Base type.

The Accounting Schema has automatic period control selected with 1000 days in the past and 1000 days in the future so i should not care about the period control records in a particular period (have seen this with other document types also so probably not a Payment selection issues but it did stop me testing)

regards

**Comment by yamelsenih** [comment]
No problem
