### ISSUE TITLE
Look and Feel the icon to delete and multiples delete is same 

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#1190]
In previos version the icons not is same

![i478 pimgpsh_fullsize_distr](https://user-images.githubusercontent.com/786968/27744458-34e658ca-5d85-11e7-8914-08c48a562d58.png)

**Comment by e-Evolution** [comment]
the icons is different no is valid.

**Comment by jdaison** [comment]
This icons are very similar, may be is better use traditional x and trash or change one of thems
https://www.awicons.com/stock-icons/symbol-color/delete-filter/
