### ISSUE TITLE
Look and Feel the Avance search is wrong

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#1192]
Now the combo box have the same color for foreground and background
![screenshot_20170630_200556](https://user-images.githubusercontent.com/2333092/27757482-17dfddbe-5dd0-11e7-80dd-067bf60ebdc0.png)

**Comment by marcalwestf** [comment]
... additional remark: the icons for _New_, _Delete_ and _Save_ are almost invisible and don't have hints displayed when hovered over:
![20170702_webui_12](https://user-images.githubusercontent.com/1789408/27771478-5e8cf4a8-5f0c-11e7-9d06-9167ca9011c2.png)

**Comment by marcalwestf** [comment]
... now the icons are displayed solid:
![20170702_webui_24](https://user-images.githubusercontent.com/1789408/27773666-26088f72-5f3c-11e7-8f14-d8fd1bdb0ca5.png)

... but the name of the selected column is still white on grey and the query value is bot visible

**Comment by marcalwestf** [comment]
...they are displayed if the field is double clicked:
![20170702_webui_25](https://user-images.githubusercontent.com/1789408/27773712-349353be-5f3d-11e7-80d2-a65c13a9e410.png)

**Comment by e-Evolution** [comment]
![captura de pantalla 2017-07-08 a la s 21 51 24](https://user-images.githubusercontent.com/786968/27990786-a343becc-6427-11e7-92e7-f4429e2b09f3.png)
