### ISSUE TITLE
Look & Feel Corrections - Change font and colour

### ISSUE THREAD

**Issue by eduardolopezuy** [adempiere/adempiere#1193]
![ui 5](https://user-images.githubusercontent.com/13646479/27764779-68c67b04-5e78-11e7-9425-4dabfb0dc397.jpg)

**Comment by eduardolopezuy** [comment]
need modification by code to change the explicit font asignated here

**Comment by adaxa-steven** [comment]
the font and colour displayed is selected from the fonts available within adempiere.  investigating adding to the range of fonts so we can choose an 'arial' type font for this display.

**Comment by Raul-mz** [comment]
Suggest it may be so:
![yeb2evmh2g](https://user-images.githubusercontent.com/9552217/28734222-dd6ef964-73ad-11e7-8e03-b02a6b91a310.png)

**Comment by adaxa-steven** [comment]
Hi Eduardo,
that looks much better. what did you do to make sure it uses that font?  does it ignore the font specified in the Document Status Indicator definition but use the fot size and colour settings?
thanks

**Comment by yamelsenih** [comment]
It is worked

**Comment by adaxa-steven** [comment]
[note re the sanserif font issue ... seems that in java it is 'sansserif' and in html it is 'sans-serif' ... after the hyphen problem was fixed in our internal build the selected font was displayed ... may need a fix in 390]
