### ISSUE TITLE
Look and Feel: icons disabled when displaying record as a form

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere#1196]
When a record is displayed as a form, the 4 icons to navigate up and down are not enabled.
This happens with any window.
When displayed as a list, the icons work well.

Steps to reproduce:
1.- open any window in the _grid_ mode: icons are displayed correctly
![20170702_webui_01](https://user-images.githubusercontent.com/1789408/27770880-e12b113c-5f03-11e7-85ac-c50eda31cc38.png)

2.- select the _form_ mode (key _F8_ or icon _Grid toggle_): the icons _Delete_, _Delete selected_,  _Up_, _Down_, _First_ and _Last_ are not available
![20170702_webui_02](https://user-images.githubusercontent.com/1789408/27770885-e4c4d0f8-5f03-11e7-9086-2b6a07e58dcc.png)

3.- select the _grid_ mode (key _F8_ or icon _Grid toggle_): all navigation items,  _Delete_ and _Delete selected_ are disabled
![20170702_webui_04](https://user-images.githubusercontent.com/1789408/27770910-564ff388-5f04-11e7-99b8-db1f3caadac7.png)

4. Select any other record in the grid: the navigation icons are displayed normally again
![20170702_webui_03](https://user-images.githubusercontent.com/1789408/27770912-6ac101fe-5f04-11e7-8ad4-3135b6d63130.png)

**Comment by yamelsenih** [comment]
Hi @marcalwestf i was testing it and the result is ok.

**Comment by marcalwestf** [comment]
not reproducible.
