### ISSUE TITLE
Look and feel: warning icon not displayed

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere#1197]
When a record is being selected for deletion, in the following confirmation dialog the warning icon is not displayed:
![20170702_webui_05](https://user-images.githubusercontent.com/1789408/27771183-e606c73e-5f06-11e7-81f6-91ddc709f864.png)

**Comment by Raul-mz** [comment]
Now: 
![image](https://user-images.githubusercontent.com/9552217/27797682-894d345c-5fdc-11e7-9c01-d73ddc48e9ee.png)
