### ISSUE TITLE
Look and Feel: icon for Attribute set instance inappropriate

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere#1198]
The icon used for Attribute Set Instance (a shopping cart) does not convey the idea of Attribute Sets:
This is how it looks in a window:
![20170702_webui_06](https://user-images.githubusercontent.com/1789408/27771233-eb97899e-5f07-11e7-8ce6-e78979ef5ae9.png)

This is how it looks in the product info:
![20170702_webui_07](https://user-images.githubusercontent.com/1789408/27771234-eba80bc0-5f07-11e7-9caf-e75d3e506d20.png)

**Comment by marcalwestf** [comment]
... now the _Attribute Set Instance_ has a more intuitive icon.
But in the _Product Info_, the icon seems not to have the correct height:
![20170704_webui_05](https://user-images.githubusercontent.com/1789408/27839023-941e8820-60ab-11e7-898f-4c6e331ac066.png)

**Comment by e-Evolution** [comment]
Now show rightly size

![i489 pimgt2_distr](https://user-images.githubusercontent.com/786968/27840919-a1e603ea-60c2-11e7-99b6-bf1c8ed569f5.jpg)

**Comment by e-Evolution** [comment]
![i524 pimgpsh_fullsize_distr](https://user-images.githubusercontent.com/786968/27840929-bc299366-60c2-11e7-9e10-d8c8956d72e1.png)
