### ISSUE TITLE
Look and Feel: in Smart Browsers, quantities in editable fields are not displayed

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere#1200]
In Smart Browsers it is possible to configure fields as editable.
Here, the user should select the field and type in the data.
This is not possible now, as it is not possible to see what's been typed in:
![20170702_webui_21](https://user-images.githubusercontent.com/1789408/27772298-70bae242-5f1c-11e7-8157-b81a40830b52.png)

**Comment by yamelsenih** [comment]
It is the same behavior that #1192

**Comment by e-Evolution** [comment]
![captura de pantalla 2017-07-08 a la s 21 46 56](https://user-images.githubusercontent.com/786968/27990781-77d7fd5c-6427-11e7-8366-1289b7e9fe99.png)
