### ISSUE TITLE
Look and Feel: Harmonize icon for date + time wih other icons

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere#1201]
For displaying date+time fields, a black-and-white icon is used:
![20170702_webui_18](https://user-images.githubusercontent.com/1789408/27772321-e7ada416-5f1c-11e7-9f64-5a8c9a81fdcb.png)

Whereas for other fields like quantities, icons with blue are used:
![20170702_webui_19](https://user-images.githubusercontent.com/1789408/27772325-13135ccc-5f1d-11e7-9d4b-000ce08cc2aa.png)

It would boost user-friendliness if both were of the same type, as they look awkward when displayed together:
![20170702_webui_17](https://user-images.githubusercontent.com/1789408/27772343-5573f874-5f1d-11e7-9631-39ed61b953d5.png)

As a collateral effect, the date+time field would use the light-blue color when disabled, adding to readability.

**Comment by rcapecce** [comment]
The button color was changed, when the field is disabled, the image disappears, this is correct @marcalwestf ?
In other case the correction should be programmatically in Java.

![image](https://user-images.githubusercontent.com/14218144/28026653-1e0c4a84-656d-11e7-9fe4-b6b320085582.png)

**Comment by marcalwestf** [comment]
@rcapecce 
Your question:
> The button color was changed, when the field is disabled, the image disappears, this is correct ?

The behavior should be that -similar to calculator- the icon with light blue is displayed when the field is disabled.

When the field is disabled, it doesn't matter if the icon is displayed or not, but it would be better it is displayed in a light color for legacy reasons; also the users are accustomed to it.

By the way, I haven't seen any change in the behavior after the commit.

**Comment by marcalwestf** [comment]
this is how it looks now when enabled:
![20170711_webui_02](https://user-images.githubusercontent.com/1789408/28072330-df00a2ec-660f-11e7-9084-dc0faf1f771d.png)

... and when disabled:
![20170711_webui_01](https://user-images.githubusercontent.com/1789408/28072342-e70a957e-660f-11e7-9f01-731c9b130ba5.png)
