### ISSUE TITLE
Smart Browser: export doesn't work

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere#1202]
When selecting the export functionality of Smart Browsers by clicking on the _Export_ button, 
![20170702_webui_26](https://user-images.githubusercontent.com/1789408/27774085-25443202-5f47-11e7-9b0c-3f35292a2af8.png)

the export occurs, but the file has no suffix:
![20170702_webui_27](https://user-images.githubusercontent.com/1789408/27774092-5a248152-5f47-11e7-8cae-d93b2a817418.png)

**Comment by e-Evolution** [comment]
Last commit solve issue with report export and browser export to included or not heder
