### ISSUE TITLE
Look and Feel: Mandatory field texts were not red

### ISSUE THREAD

**Issue by eduardolopezuy** [adempiere/adempiere#1203]
![ui 6](https://user-images.githubusercontent.com/13646479/27800798-45ddd5e0-5ff1-11e7-846e-7638dd927235.jpg)
![ui 7](https://user-images.githubusercontent.com/13646479/27800800-486359de-5ff1-11e7-9c2d-8d0ba8210820.jpg)

**Comment by eduardolopezuy** [comment]
#1146

**Comment by marcalwestf** [comment]
Closing this issue because discussed already in https://github.com/adempiere/adempiere/issues/1146
