### ISSUE TITLE
Look & Feel Corrections - Change turquoise to blue

### ISSUE THREAD

**Issue by eduardolopezuy** [adempiere/adempiere#1205]
![ui 9](https://user-images.githubusercontent.com/13646479/27802065-dc8d3eb2-5ff7-11e7-90b8-ea563c280cb5.jpg)

**Comment by adaxa-steven** [comment]
hi Eduard
please see comments on Print Table Format posted here in error
https://github.com/adempiere/adempiere/issues/1207

regards..

**Comment by yamelsenih** [comment]
It is referenced on #1207
