### ISSUE TITLE
Look and Feel Correction - Change HTML colours

### ISSUE THREAD

**Issue by eduardolopezuy** [adempiere/adempiere#1207]
![ui 10](https://user-images.githubusercontent.com/13646479/27810497-7391e89c-6031-11e7-81ef-561f952c45a7.jpg)

**Comment by adaxa-steven** [comment]
HTML report look good
![image](https://user-images.githubusercontent.com/15791084/27815929-8e61256c-60cb-11e7-994c-774a87e1a912.png)

pdf still look awful
![image](https://user-images.githubusercontent.com/15791084/27815947-aee44bf2-60cb-11e7-9ccf-74fced5d32cc.png)

please vote if you think this is better as the default  (remembering that the cyan etc probably being sent to a black and white printer
![image](https://user-images.githubusercontent.com/15791084/27815998-f832b1c2-60cb-11e7-8459-18ddc1bdbc75.png)

the difference is changing the default Print Format Table from
![image](https://user-images.githubusercontent.com/15791084/27816025-226722ca-60cc-11e7-818d-dabb4b856f23.png)

to this
![image](https://user-images.githubusercontent.com/15791084/27816036-38c1a694-60cc-11e7-9de8-094351760747.png)

**Comment by eduardolopezuy** [comment]
Hi Steven, 
I vote different shades of gray.

**Comment by marcalwestf** [comment]
I support @adaxa-steven 's suggestion

**Comment by adaxa-steven** [comment]
the "Summary" button appears in 'wrong' place
![image](https://user-images.githubusercontent.com/15791084/27844716-a85a1cd8-6168-11e7-9e12-7191fc3cb3b6.png)

was previously to the left of the 'modify print format' button and on same level.

**Comment by Raul-mz** [comment]
Now: 
- PDF
![image](https://user-images.githubusercontent.com/9552217/28035102-5cea2186-6581-11e7-9df8-8d39374bb064.png)

- HTML
![image](https://user-images.githubusercontent.com/9552217/28035119-6da165e8-6581-11e7-8175-1482873ed5dc.png)
