### ISSUE TITLE
Look and Feel : some icons need be change to size 16 because the 24 x24 are big to size dialog

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#1214]

**Comment by e-Evolution** [comment]
![captura de pantalla 2017-07-04 a la s 15 37 05](https://user-images.githubusercontent.com/786968/27842324-c675d620-60ce-11e7-919c-213b7e8fc0f3.png)
![captura de pantalla 2017-07-04 a la s 15 23 59](https://user-images.githubusercontent.com/786968/27842330-d21b4d0c-60ce-11e7-8ed7-16d3a3334831.png)

![captura de pantalla 2017-07-04 a la s 15 24 09](https://user-images.githubusercontent.com/786968/27842326-cd0f7ae0-60ce-11e7-85c4-4ecf61fd45e1.png)

**Comment by e-Evolution** [comment]
![captura de pantalla 2017-07-04 a la s 15 39 06](https://user-images.githubusercontent.com/786968/27842350-f3edd9b8-60ce-11e7-9ea0-1f4e37593e85.png)

**Comment by yamelsenih** [comment]
Hi @e-Evolution it is fixed?
