### ISSUE TITLE
Error when push button the attributes in product info 

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#1215]
![captura de pantalla 2017-07-04 a la s 15 21 00](https://user-images.githubusercontent.com/786968/27842104-6c5b10e4-60cc-11e7-867e-688b07b3456b.png)

15:18:32.828 InfoProductPanel.<init>: , Wh=103, PL=101, WHERE= [69]
15:18:32.828 InfoProductPanel.<init>: , Wh=103, PL=101, WHERE= [69]
===========> zkoss.handleError:1130: >>java.lang.NullPointerException
>>	at org.adempiere.webui.editor.WStringEditor.getComponent(WStringEditor.java:110)
>>	at org.adempiere.webui.editor.WStringEditor.setReadWrite(WStringEditor.java:123)
>>	at org.adempiere.webui.editor.WEditor.init(WEditor.java:229)
>>	at org.adempiere.webui.editor.WEditor.<init>(WEditor.java:203)
>>	at org.adempiere.webui.editor.WStringEditor.<init>(WStringEditor.java:102)
>>	at org.adempiere.webui.panel.InfoPAttributePanel.<init>(InfoPAttributePanel.java:117)
>>... [55]
===========> zkoss.handleError:1130: >>java.lang.NullPointerException
>>	at org.adempiere.webui.editor.WStringEditor.getComponent(WStringEditor.java:110)
>>	at org.adempiere.webui.editor.WStringEditor.setReadWrite(WStringEditor.java:123)
>>	at org.adempiere.webui.editor.WEditor.init(WEditor.java:229)
>>	at org.adempiere.webui.editor.WEditor.<init>(WEditor.java:203)
>>	at org.adempiere.webui.editor.WStringEditor.<init>(WStringEditor.java:102)

**Comment by e-Evolution** [comment]
this change cause this error

===========> zkoss.handleError:1130: >>java.lang.NullPointerException
>>	at org.adempiere.webui.editor.WEditor.isMandatoryStyle(WEditor.java:717)
>>	at org.adempiere.webui.editor.WEditor$2.onEvent(WEditor.java:266)
>>	at org.zkoss.zk.ui.impl.EventProcessor.process0(EventProcessor.java:197)
>>	at org.zkoss.zk.ui.impl.EventProcessor.process(EventProcessor.java:141)
>>	at org.zkoss.zk.ui.impl.EventProcessingThreadImpl.process0(EventProcessingThreadImpl.java:519)
>>	at org.zkoss.zk.ui.impl.EventProcessingThreadImpl.run(EventProcessingThreadImpl.java:446)
 [231]

**Comment by marcalwestf** [comment]
With commit https://github.com/adempiere/adempiere/commit/1c6dd598d57178621493c644bc23d8e46de2635c the NPE is not thrown anymore, and the following is displayed in _Product Info_:
![20170704_webui_07](https://user-images.githubusercontent.com/1789408/27846694-73c00040-60f6-11e7-9928-4ea7eb421597.png)
