### ISSUE TITLE
Look and Feel Correction -Enlarge vertical tabs

### ISSUE THREAD

**Issue by eduardolopezuy** [adempiere/adempiere#1216]
![ui 11](https://user-images.githubusercontent.com/13646479/27842214-5a59ed9a-60de-11e7-959d-80092bf3656e.png)

**Comment by eduardolopezuy** [comment]
![ui 12](https://user-images.githubusercontent.com/13646479/27842444-8c0f1afc-60e0-11e7-88d1-7af4e7a9187e.jpg)

**Comment by rcapecce** [comment]
The padding was corrected
Now:
![image](https://user-images.githubusercontent.com/14218144/27842979-5013395c-60e5-11e7-902f-ab4df4f4c8ad.png)

**Comment by liosc** [comment]
I think there is still something wrong with vertical tabs width setting. In business partner, for example, some tab names are truncated. See following image (I am using official test URL http://188.40.37.194:49269).
![image](https://user-images.githubusercontent.com/23416398/28420870-ccb6034c-6d63-11e7-9a38-27f209f313e9.png)

**Comment by eduardolopezuy** [comment]
Hi @liosc ,
What is your display resolution?
1024*768?

**Comment by liosc** [comment]
Hi Eduardo,
my current resolution is 1366x768.

**Comment by rcapecce** [comment]
I fix the css to mark too the disabled tab

Before
![image](https://user-images.githubusercontent.com/14218144/28480469-34000db2-6e37-11e7-8d50-99dd5231f896.png)

After
![image](https://user-images.githubusercontent.com/14218144/28480495-4e37fb9a-6e37-11e7-92f9-8cf83a01554d.png)

Note that when there is no scroll bar, the separation is more notorious
![image](https://user-images.githubusercontent.com/14218144/28480513-644dfcea-6e37-11e7-89e2-eff121eff5c6.png)
