### ISSUE TITLE
When try create an  allocation resource 

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#1217]
Error

![captura de pantalla 2017-07-04 a la s 16 41 47](https://user-images.githubusercontent.com/786968/27843298-c8715748-60d7-11e7-81f9-ff3cc055c171.png)

**Comment by yamelsenih** [comment]
Hi @e-Evolution it is worked, see:
![screenshot_20170707_144004](https://user-images.githubusercontent.com/2333092/27971859-3fc527f6-6322-11e7-9239-fe8cb66a9fb7.png)

**Comment by e-Evolution** [comment]
Can not replicate
