### ISSUE TITLE
Look and Feel: 'cross' and 'tick' images different size? 

### ISSUE THREAD

**Issue by adaxa-steven** [adempiere/adempiere#1220]
should the boxes be the same size?
![image](https://user-images.githubusercontent.com/15791084/27844738-1b39372a-6169-11e7-97ff-b74e876a7847.png)

**Comment by marcalwestf** [comment]
with commit for "flat" buttons looks as follows:
![20170704_webui_09](https://user-images.githubusercontent.com/1789408/27847383-7d7bea82-60fa-11e7-8091-1bc3220a48bd.png)
