### ISSUE TITLE
Look and Feel Correction -Change mark icon

### ISSUE THREAD

**Issue by eduardolopezuy** [adempiere/adempiere#1226]
![ui 16](https://user-images.githubusercontent.com/13646479/27976837-999504d8-633e-11e7-8228-5eadb8ebc0a0.png)

**Comment by rcapecce** [comment]
Now
![image](https://user-images.githubusercontent.com/14218144/28025638-5624b45e-656a-11e7-93f1-1d83885162a3.png)
