### ISSUE TITLE
Barcode Scanner for all material transaction 

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#1236]
This form allows processing the transactions of materials by means of a Barcode Scanner using the Search Key, UPC/EAN, SKU, Partner Product Key

**Comment by e-Evolution** [comment]
Universal Barcode Scanner From

![captura de pantalla 2017-07-09 a la s 15 36 50](https://user-images.githubusercontent.com/786968/27997562-26769f60-64c0-11e7-8be7-41da2e65a329.png)

For Inventory Move transaction.

![captura de pantalla 2017-07-09 a la s 15 29 56](https://user-images.githubusercontent.com/786968/27997563-3d139ab6-64c0-11e7-945e-5b1308148f4d.png)

New button for Material Transaction.

Physical Inventory

![captura de pantalla 2017-07-09 a la s 15 31 32](https://user-images.githubusercontent.com/786968/27997566-573cb06c-64c0-11e7-98c7-097c5a4cc41d.png)

Inventory Move

![captura de pantalla 2017-07-09 a la s 15 31 16](https://user-images.githubusercontent.com/786968/27997571-688cb2fe-64c0-11e7-843f-1202671a2853.png)

Internal Use Inventory 

![captura de pantalla 2017-07-09 a la s 15 28 14](https://user-images.githubusercontent.com/786968/27997573-7969ba86-64c0-11e7-8b61-fad602784377.png)

Material Receipt

![captura de pantalla 2017-07-09 a la s 16 06 19](https://user-images.githubusercontent.com/786968/27997577-b08c5d7a-64c0-11e7-8308-d70f247dbce3.png)

Shipment 

![captura de pantalla 2017-07-09 a la s 16 06 37](https://user-images.githubusercontent.com/786968/27997579-b665b638-64c0-11e7-9aa1-416894dd5a19.png)

**Comment by adaxa-steven** [comment]
Hi Victor,
Perhaps there should be a discussion before this gets added.  There is alternative functionality that was contributed some time ago that covers barcoding for Shipments, MR and Movements. The Shipment version is shown below.
![image](https://user-images.githubusercontent.com/15791084/27998878-2654309e-6559-11e7-83a4-f5cf6f1197e7.png)

candidate shipments
![image](https://user-images.githubusercontent.com/15791084/27998883-3981ee86-6559-11e7-83ae-2e3c7469a916.png)

shipment form that is displayed when you read the shipment document number with the barcode scanner
![image](https://user-images.githubusercontent.com/15791084/27998894-62af4664-6559-11e7-8856-8cb880314b38.png)

you can also display a button so that you can re-scan items to remove them but it has been 'undisplayed' in this version.

**Comment by marcalwestf** [comment]
... well, I think we have indeed two solutions which more or less do the same... 
Unluckily, this case comes up so close to releasing ADempiere 3.9 that there is almost no room to maneuver.

The functionality @e-Evolution committed works with Smart Browser , a proven technique.

Adaxa's functionality with forms. I think Steven sent us (me?) some time ago these screenshots.
I see in Adaxa's solution additional functionality which would be useful to adopt. As usual by Adaxa, they are very practical solutions.

In general, there is a tendency in ADempiere of avoiding when possible forms and using instead Smart Browsers. There reason: Smart Browsers are generated automatically for both Swing and ZK, there is one single code, and there is no need to create every graphical object by hand as it is required by forms. But by definition, Smart Browsers lack of the flexibility of forms. This means, it poses a challenge to implement 1:1 all functionality of a form in a Smart Browser.

This said, I'd suppose the best path would be to leave the "Express Receipt" functionality as it is committed and include the additional functionality of Adaxa ASAP.
(not to mention that next time there should be a better coordination between the collaborators)

**Comment by adaxa-steven** [comment]
Mario
I agree there should be better co-ordination.
Here is a screen shot from a 390 build late last week
![image](https://user-images.githubusercontent.com/15791084/28002646-78bff0fe-657a-11e7-885d-807e521cc09d.png)

I can not see anything about barcode scanning in the window and I have not read any discussion about adding barcode scanning capability so it is hard to see how we could have co-ordinated.

**Comment by e-Evolution** [comment]
Hola Steven!!!

This functionality was added 10 months before, with  Warehouse Management Express Receipt #470. the past Friday the main contributors had a discussion about the enable this functionality.

You can see here when was commited
https://github.com/adempiere/adempiere/tree/develop/org.eevolution.warehouse/src/main/java/ui/zk/org/eevolution/form

https://github.com/adempiere/adempiere/tree/develop/zkwebui/WEB-INF/src/org/eevolution/form

The functionality extremely  simple and useful, without a lot of buttons and options that only causing distraction the user, because your goal and priority is to allows to add fastly product using bar code scanner  any document where can entry a product, if the product has attribute set with a lot or serial defined, then a field is enabled to the scanner the lot and serial if exist a barcode.

**Comment by e-Evolution** [comment]
Hi Steven!

About the functionality that shows,  I think we could evaluate and test if there was a branch based on Adempiere where this was integrated and many of its improvement, will be wonderful if the Adaxa's development team contributed in Adempiere as it did before, so many the great things you do would be easy to integrate and Adaxa would not have to maintain their own fork, this would facilitate the contribution and is the way that others are doing.

Either way, we are very interested in all the improvements you have sent, we will look for the time to evaluate and integrate into the next version of Adempiere.
