### ISSUE TITLE
Match Invoice Documents fail to post

### ISSUE THREAD

**Issue by adaxa-steven** [adempiere/adempiere#1240]
testing here   http://188.40.37.194:49269/webui/index.zul

There are about 20 Invoice Match documents in the Unposted window.
They will not post and say that the Material Receipt is not posted but when you zoom to the Material Receipts it shows they are posted... I did not check them all.

I think this is a 'Must Fix' before release.

**Comment by SusanneCalderon** [comment]
The problem were material receipts without purchase order. For average costing the entries were posted to zero. 
Solution:
When a material receipt is posted but to cost zero then create a dummy factline with amtacctdr and amtacctcr 0. So the purchase costs are covered 100% by Doc_MatchInv.

**Comment by adaxa-steven** [comment]
That cleans up the existing data in GardenWorld but presumably there is still an underlying error or missing functionality to allow it to happen at all.
Is that what this commit did?
https://github.com/adempiere/adempiere/commit/61e541dc0612b22ebedb22c763e248ccafc29167 
thanks
