### ISSUE TITLE
Look and Feel - main screen untidy

### ISSUE THREAD

**Issue by adaxa-steven** [adempiere/adempiere#1242]
The main screen could look much more tidy by some simple changes:
(a) changing dashboard content entries around
(b) fixing up error about what is displayed for Document Status records
![image](https://user-images.githubusercontent.com/15791084/28099337-41214fe0-66ff-11e7-9c14-748525ba576f.png)

**Comment by adaxa-steven** [comment]
also you can just replace these
![image](https://user-images.githubusercontent.com/15791084/28099426-dc0415ba-66ff-11e7-94e2-19fe030fd419.png)

with other Document status indicators that do the same job -see last 4 items.
![image](https://user-images.githubusercontent.com/15791084/28099478-2835fbec-6700-11e7-9eda-291385a8d425.png)
(choose nicer fonts!)
this reduces the number of panels and displays the workflow, request, notices (and My Unprocessed Documents) more prominently and in a place wjhere people are more likely to be looking.

The setup of the is shown in the Document Status window on http://adaxa.testadempiere.com/webui/ so I wont try to document here.

**Comment by adaxa-steven** [comment]
perhaps more like this...
![image](https://user-images.githubusercontent.com/15791084/28100778-8df3c980-6707-11e7-8c43-9a570ca205d9.png)

**Comment by adaxa-steven** [comment]
Hi Mario
I see you marked as 3.9.1 but surely we can do a simple tidy up for 390 .. it is a migration script only .. no code changes

**Comment by adaxa-steven** [comment]
I rearranged on  http://188.40.37.194:49269/webui/index.zul
(1) added Document Tasks at System level and decativated same in GardenWorld client level
[seems that all System owned ones are displayed and then GW client afterwards regardles of the sequence numbers being different.
(2) changed  the column and lines numbers to this
![image](https://user-images.githubusercontent.com/15791084/28101309-1ffe7aa2-670b-11e7-9638-830e27cd458a.png)

result is this
![image](https://user-images.githubusercontent.com/15791084/28101255-a2778e48-670a-11e7-8346-175f8becb7ec.png)

I hope you think it is better.
unfortunately I don't know how to create a migration script.

**Comment by eduardolopezuy** [comment]
Hi Steven, @adaxa-steven 

(choose nicer fonts and names!) on Document tasks,  see #1193

**Comment by adaxa-steven** [comment]
as entered in #1193
the font and colour displayed is selected from the fonts available within adempiere. investigating adding to the range of fonts so we can choose an 'arial' type font for this display.

**Comment by adaxa-steven** [comment]
with extra fonts installed in adempiere

![image](https://user-images.githubusercontent.com/15791084/28155250-30585ad0-67f1-11e7-9ba4-5f05ecdc9554.png)

**Comment by adaxa-steven** [comment]
some further questions on the fonts:
These document status indicators were set with a san serif font selected but the browser ignored that and ended up using a serif font instead.
![image](https://user-images.githubusercontent.com/15791084/28487213-c8b0721a-6ecf-11e7-8266-39bfe4431c30.png)

Liberation sans fonts were added to adempiere print fonts and selected to be used in the document status indicator and on my pc they were used..
![image](https://user-images.githubusercontent.com/15791084/28487237-0f17415c-6ed0-11e7-9ce7-6fce01d64a60.png)

but on another PC they were ignored and the serif font was still displayed.

Is there a way to force the system to use a san serif font in the display instead of the serif font.  The rest of the screen is displayed with arial font or similar so a san serif font is available.  Even if the font selected in the Document Status Indicator is not available to the browser why does it make such a bad choice of an alternative and how can it be fixed?
thanks

**Comment by marcalwestf** [comment]
now, it looks as follows:
![20170721_adempiere_10](https://user-images.githubusercontent.com/1789408/28501746-cf7ebf36-6f9f-11e7-9c26-00374b8a9feb.png)

The configuration:
![20170721_adempiere_11](https://user-images.githubusercontent.com/1789408/28501747-e174f2c8-6f9f-11e7-832a-df3e5bbfef48.png)

**Comment by marcalwestf** [comment]
It would remain to 

1. create entries for _User favorites_, 
2. get rid of _System favorites_ (what about _Cache Reset_??)
3. Move _Activities_ to _Document Status_

**Comment by marcalwestf** [comment]
Item # 2 from last list is not possible because of https://github.com/adempiere/adempiere/issues/1263 .

**Comment by adaxa-steven** [comment]
#1263  has been updated ... it is possible to insert records at least in the current test system instance.
.... so we could now delete the old favorites as long as GW has the new Favorites displaying a selection of windows and report/process.

another point on the fonts question...
If you look at the original entry suggesting taking up the Document Tasks functionality you can see that the first screen shot was using san serif font .. I have no idea how that is controlled. 
https://github.com/adempiere/adempiere/issues/910

recreate entries for User favorites,
get rid of System favorites (what about Cache Reset??)
Move Activities to Document Status
..... I agree it would be good to move the Activities entries to Document Tasks and delete the Activities section. Adding Cache Reset and My Unprocessed Documents would be useful.... what do others think?

**Comment by marcalwestf** [comment]
till yo be done: 
1.- to define panels as _System_ so users can copy for their clients
2.- Create new panels to get rid of the "Views" panel which would be replaced by _Document tasks_

..moving issue to 3.9.1

**Comment by adaxa-steven** [comment]
'sansserif" is not "sans-serif"!
"another point on the fonts question...
If you look at the original entry suggesting taking up the Document Tasks functionality you can see that the first screen shot was using sansserif font .. I have no idea how that is controlled.
#910"
It seems that the problem was that java calls the font "sanserif"  (or 'sansserif?)  and html calls it 
"sans-serif" (with hyphen).  With this change the font choice was then displayed correctly.
