### ISSUE TITLE
The change role throw exception

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#1258]
HTTP Status 500 - Login is invalid, UserName: null and Password:null

type Exception report

message Login is invalid, UserName: null and Password:null

description The server encountered an internal error that prevented it from fulfilling this request.

exception

org.adempiere.webui.exception.ApplicationException: Login is invalid, UserName: null and Password:null
	org.adempiere.webui.panel.RolePanel.<init>(RolePanel.java:105)
	org.adempiere.webui.window.LoginWindow.loginOk(LoginWindow.java:84)
	org.adempiere.webui.window.LoginWindow.changeRole(LoginWindow.java:134)
	org.adempiere.webui.WLogin.changeRole(WLogin.java:190)
	org.adempiere.webui.AdempiereWebUI.onChangeRole(AdempiereWebUI.java:165)
	org.adempiere.webui.AdempiereWebUI.onCreate(AdempiereWebUI.java:134)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:498)
	org.zkoss.zk.ui.impl.EventProcessor.process0(EventProcessor.java:209)
	org.zkoss.zk.ui.impl.EventProcessor.process(EventProcessor.java:141)
	org.zkoss.zk.ui.impl.EventProcessingThreadImpl.process0(EventProcessingThreadImpl.java:519)
	org.zkoss.zk.ui.impl.EventProcessingThreadImpl.run(EventProcessingThreadImpl.java:446)
note The full stack trace of the root cause is available in the Apache Tomcat/7.0.53 logs.

**Comment by sramazzina** [comment]
Victor, can you write more extensive information in your tickets so that anyone who want to reroduce the issue can effecctively do that? Issues written these way doesn't give any chance to anyone to replicate the problem and either try to solve it or try to test it. Grazie :-)

**Comment by marcalwestf** [comment]
Prego, Sergio:
The error concerns to the following: int ZK, there is a "Change role" link in the upper-right corner of the main panel:
![20170721_adempiere_16](https://user-images.githubusercontent.com/1789408/28628483-0182394c-71e2-11e7-8423-f11b9e375683.png)

Which allows you to change role without needing to log in again.
This worked until a couple of weeks ago, but recently the issue reported pops up.
![hpficlcnpjhajhde](https://user-images.githubusercontent.com/1789408/28628669-84aa4904-71e2-11e7-874e-9db97f468878.png)

The task is to find out why this error has sneaked in in the last days and to repair it.

**Comment by marcalwestf** [comment]
In my Eclipse IDE, with the code as of now, I cannot reproduce the error with Tomcat.
Nor I can I reproduce it when doing a local installation of Adempiere with the latest code and installing with JBoss or Tomcat.

It is therefore not a matter of the code.
I would need the very database on http://188.40.37.194:49269 in order to reproduce it.

**Comment by marcalwestf** [comment]
the reported error says that  _user name_ and _password_ are both == _null_.
... in class _org.adempiere.webui.window.LoginWindow_ the responsible for delivering _user name_ and _password_ is the following method: 
```
public void changeRole(Locale locale, Properties ctx) {
	Env.setCtx(ctx);
	getDesktop().getSession().setAttribute(Attributes.PREFERRED_LOCALE, locale);
	Locales.setThreadLocal(locale);
	new Login(Env.getCtx());
	MUser user = MUser.get(ctx, Env.getAD_User_ID(ctx));
	String loginName = user.getLDAPUser() != null ? user.getLDAPUser() : user.getName();
	loginOk(loginName, user.getPassword());
	getDesktop().getSession().setAttribute("Check_AD_User_ID", Env.getAD_User_ID(ctx));

	pnlRole.changeRole(ctx);
}
```

...which calls` loginOK()` and seems OK. 

Perhaps the call 	`	new Login(Env.getCtx());`
could be done with `		new Login(ctx);`
but it seems OK....

I wonder what User is taken which has a  _user name_ and _password_ == null?

**Comment by marcalwestf** [comment]
... it seems the problem comes up when the password is changed.

**Comment by SusanneCalderon** [comment]
The method loginOk(loginName, user.getPassword()) is called with the encrypted password from MUser.
When I change the value to the decrypted password changeRole works.
I would like to knpw how to decrypt the password in order to call loginOK with the decrypted password.

**Comment by sajeevsahadev** [comment]
This issue still exists in 3.9.3
