### ISSUE TITLE
The Synchronize Terminology not work Smart Browser field translation 

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#1262]
The Synchronize Terminology not work Smart Browser field translation

**Comment by sramazzina** [comment]
Hi Victor, could you be more exhaustive in explaining your problem? Today we had a problem with Forecasting Simulation Result window and we opened an new issue #1269 on milestone 3.9.0

**Comment by e-Evolution** [comment]
Hi @sramWhen sincroniza terminology the browser field not are synchronize with system element , so the field are show en English when should be translate with Spanish. 

The reason is that this functionality need be implement as in windows and tabs.

**Comment by yamelsenih** [comment]
Hi @e-Evolution it is worked?
