### ISSUE TITLE
ZK: User Favorites doesn't allow to insert records

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere#1263]
In User Favorites it is not any longer possible to insert windows , reports, etc.

It is only possible to add and delete folders, but not to add elements.

I suppose this was done away with during the Look and Feel changes.

Additionally, the Icon for the folders (and perhaps also for the entries is not visible).

![20170721_adempiere_12](https://user-images.githubusercontent.com/1789408/28501941-78f6a462-6fa4-11e7-817d-6720dae5607c.png)

**Comment by adaxa-steven** [comment]
testing here  http://188.40.37.194:49269/webui/index.zul
add a name for the folder, tick as root, click 'add folder' 
drag items from menu into the folder
![image](https://user-images.githubusercontent.com/15791084/28504895-514f77fa-7061-11e7-94e7-ffde19cd9ba1.png)
seems to be working as designed.
regards

**Comment by marcalwestf** [comment]
@adaxa-steven thanks a lot for the explanation!!!
I was quite puzzled!
