### ISSUE TITLE
ERROR: column "user3_id" does not exist

### ISSUE THREAD

**Issue by sramazzina** [adempiere/adempiere#1266]
Hi all,

after restoring the latest seed from adempiere repository, trying to complete a sales order we unexpectedly get into this error

-----------> MWFActivity.run: MWFNode[186-(DocComplete),Action=DocumentAction=CO] [55]
org.adempiere.exceptions.AdempiereException: org.postgresql.util.PSQLException: ERROR: column "user3_id" does not exist
  Position: 807, SQL=SELECT QtyBatchSize,Planner_ID,CopyFrom,QtyBatchs,Processed,DateConfirm,DateDelivered,DateFinish,DateFinishSchedule,DateOrdered,DatePromised,DateStart,DateStartSchedule,Description,QtyReserved,IsApproved,Lot,M_AttributeSetInstance_ID,OrderType,QtyEntered,AD_OrgTrx_ID,User1_ID,User2_ID,IsPrinted,IsQtyPercentage,IsSOTrx,IsSelected,Line,M_Warehouse_ID,FloatBefored,QtyOrdered,QtyReject,DocAction,DocStatus,FloatAfter,QtyScrap,ScheduleType,SerNo,QtyDelivered,DocumentNo,S_Resource_ID,PP_Order_ID,Posted,PriorityRule,AD_Workflow_ID,PP_Product_BOM_ID,Assay,C_Activity_ID,C_Campaign_ID,C_DocTypeTarget_ID,C_DocType_ID,C_OrderLine_ID,C_Project_ID,C_UOM_ID,M_Product_ID,Yield,ProcessedOn,C_ProjectPhase_ID,C_ProjectTask_ID,M_Shipper_ID,DeliveryRule,DeliveryViaRule,FreightCostRule,M_FreightCategory_ID,TrackingNo,User3_ID,User4_ID,Created,Processing,CreatedBy,AD_Org_ID,AD_Client_ID,Updated,UpdatedBy,IsActive FROM PP_Order WHERE ( C_OrderLine_ID = ?  AND DocStatus IN  (?,?) AND EXISTS (SELECT 1 FROM  PP_Order_BOM  WHERE PP_Order_BOM.PP_Order_ID=PP_Order.PP_Order_ID AND PP_Order_BOM.BOMType =? ))
	at org.compiere.model.ModelValidationEngine.lambda$fireDocValidate$11(ModelValidationEngine.java:528)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)

After further investigation we came to these conclusions:

- this issue seems to be related to issue #665 that is closed.
- looking into the PP_Order table we found out the following fields: user1_id, user2_id and user4_id so the field we need seems to be effectively unavailable
![pp_order-physical](https://user-images.githubusercontent.com/1270945/28519123-b401bb84-706a-11e7-9dce-7c8ff8fedf19.png)
- looking at ADempiere Metadata for PP_Orders's columns the 4 user_id fields are present so it seems the logical and physical levels are not aligned
![pp_order-logical](https://user-images.githubusercontent.com/1270945/28519207-0523b756-706b-11e7-8b76-432b6d5fcf99.png)
- We found a migration file (00430_665_Add_New_User_Account_Dimensions.xml) that contains the statement to create the field in the database.

Therefore, why is that field missing in the current ADempiere_pg.sql seed file?

**Comment by marcalwestf** [comment]
Hi Sergio,
here the screenshot of how you can check if the xml was applied.
![20170721_adempiere_15](https://user-images.githubusercontent.com/1789408/28538274-eb327774-706a-11e7-9725-3993e32918cb.png)

In order for you to see it, you have to log in with the role of  _SystemAdministrator_ and open the window _Migration_:
In this case, the database I am using has _00430_665_Add_New_User_Account_Dimensions.xml_ applied and it can be seen in the database as well as in the Application Dictiionary.
