### ISSUE TITLE
Forecast management - window specification missing in table definition

### ISSUE THREAD

**Issue by liosc** [adempiere/adempiere#1267]
In almost all the table of Forecast module the window field in table definition is empty so it is not available the zoom from the related field. For example from "Forecast simulation" window it is not possible to zoom into "Forecast definition".
We could fix the application dictionary ourselves but we don't know how to make changes permanent.

![image](https://user-images.githubusercontent.com/23416398/28523928-cefde3cc-707e-11e7-9874-42b8619a62f0.png)

**Comment by yamelsenih** [comment]
Resolved here #2588

**Comment by yamelsenih** [comment]
![Current ogv](https://user-images.githubusercontent.com/2333092/58451097-fe0f7900-80df-11e9-8f1e-12535fbca77d.gif)
