### ISSUE TITLE
ERROR: column "ad_menu_id" does not exist

### ISSUE THREAD

**Issue by sramazzina** [adempiere/adempiere#1268]
Every time we open a window we're getting the error detailed below. 

org.postgresql.util.PSQLException: ERROR: column "ad_menu_id" does not exist
  Position: 228; State=42703; ErrorCode=0
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2412)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2125)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:297)

The test was made after installing a brand new ADempiere 390 with database initialized at the latest seed available. Looking at the ADempiere Metatada It seems that table AD_RecentItems is missing of such a file named ad_menu_id.

We tried to add that field by defining it in the ADempiere metadata and synchronizinig the repository but immediately doing this the error above disappeared and a new error detailed below rased up

===========> DB.executeUpdate: INSERT INTO AD_RecentItem (AD_Role_ID,AD_User_ID,AD_RecentItem_ID,AD_Org_ID,Created,CreatedBy,IsActive,UpdatedBy,Updated,AD_Client_ID,AD_Menu_ID) VALUES (102,101,1000001,50001,TO_TIMESTAMP('2017-07-24 14:48:44','YYYY-MM-DD HH24:MI:SS'),101,'Y',101,TO_TIMESTAMP('2017-07-24 14:48:44','YYYY-MM-DD HH24:MI:SS'),11,53427) [POSave_21cde471-24b1-43d8-a62e-081d8dd2ce5c] [42]
org.postgresql.util.PSQLException: ERROR: null value in column "ad_table_id" violates not-null constraint
  Detail: Failing row contains (11, 50001, 1000001, 102, null, null, 101, null, 2017-07-24 14:48:44, 101, Y, null, 2017-07-24 14:48:44, 101, 53427).; State=23502; ErrorCode=0

**Comment by marcalwestf** [comment]
@sramazzina before going into it, I'd like to know if you have the latest seed + code.

Out of the repository, the latest code is not synced with the repository seed. 
In order to get the latest seed, you have to go through a seed generation process which eventually produces the actual seed. In this process, you start from the repo seed and apply all xmls.

I'd like to know if the database you're using has been produced as I describe; otherwise you will produce all kind of errors.

**Comment by yamelsenih** [comment]
Hi @sramazzina the last source code must have a XML applied, please reapply it https://github.com/adempiere/adempiere/blob/e4021f2b8d6bc7aa47c323a6a37df75aa96dad42/migration/380lts-release/02790_884_AddColumnForRecentItems.xml

**Comment by sramazzina** [comment]
@marcalwestf we build the latest code from release/3.9.0 and restored the ADempiere_pg.sql that comes from the repository. I've not applied all the XMLs files because I was convinced that seed was the latest, that was my mistake I'm very sorry. Glad to know this. I will try to apply all the migrations XMLs and then I will let you know. Grazie mille! (Thank you very much)
