### ISSUE TITLE
ZK Open Form return "Process Error"

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#127]
When a process is used for show a form from a window in ZK, the form is launched but also the process dialog.
![issue42](https://cloud.githubusercontent.com/assets/2333092/11400836/b406cc60-9361-11e5-8086-130acd5c420b.png)
![issue43](https://cloud.githubusercontent.com/assets/2333092/11400840/b756082c-9361-11e5-8108-e60586d605ad.png)

**Comment by syvasoft** [comment]
Hi Yamelsenih, 
I have already faced this issue. I don't exactly understand for a use of the custom form with a process. Could you tell me what would be the right output if the custom form specified in the process and what kind of business requirements can be catered using this functionality?

Regards,
Syed.

**Comment by yamelsenih** [comment]
Hi @syvasoft we use it functionality for call a custom form in a window, then when you press the button, the form is launched instead the process.
The next step for it is make form dynamically for the "Create From" like "Create From" in Purchase Order or Statement Account.

We are change it in https://github.com/adempiere/adempiere/issues/114

**Comment by syvasoft** [comment]
@yamelsenih, I have understood the purpose. If the special form is called from a button through a process, it should be a modal dialog, not as a tabbed form just like an AD window. It's really great that you have already mentioned in #114.

**Comment by yamelsenih** [comment]
Yes @syvasoft we also want change the hardcode in "Create From" forms by dynamic forms.
