### ISSUE TITLE
Error while applying migration XMLs

### ISSUE THREAD

**Issue by sramazzina** [adempiere/adempiere#1276]
Just pulled today latest changes from release/3.9.0, recompiled is and installed a new ADempiere instance. Unfortunately while executing RUN_MigrationXML.sh to apply latest database changes I got this exception message that prevented me to complete the migration successfully

===========> MigrationFromXML.process: Loading Migration from XML failed. [1]
org.adempiere.exceptions.AdempiereException: Loading migration from /data/app/Adempiere/migration/380lts-release/02250_928_Remove_Unnecessary_HR_Column.xml failed.
	at org.compiere.process.MigrationFromXML.lambda$loadFile$0(MigrationFromXML.java:168)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.compiere.util.Trx.run(Trx.java:495)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:141)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:107)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:49)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)
caused by: org.adempiere.exceptions.AdempiereException: Process failed during execution Error:  Migration 2250 - Payroll Process have columns unnecessary #928 - 3.8.0 (D) ; Step: 20; Type: AD. Application failed: org.adempiere.exceptions.AdempiereException: Migration 2250 - Payroll Process have columns unnecessary #928 - 3.8.0 (D) ; Step: 20; Type: AD. Step 20, Record 55058 was not found in table Field (107).
	at org.eevolution.service.dsl.ProcessBuilder.execute(ProcessBuilder.java:297)
	at org.compiere.process.MigrationFromXML.applyMigration(MigrationFromXML.java:181)
	at org.compiere.process.MigrationFromXML.lambda$loadFile$0(MigrationFromXML.java:163)

Am I missing something??

**Comment by yamelsenih** [comment]
Hi @sramazzina i an apply all XML just now. I tell you if exists the same error.

**Comment by dixon22ma** [comment]
Hi @sramazzina, @yamelsenih this error is generated in the database of version 390. In the database of version 380 or master this error does not happen.

**Comment by sramazzina** [comment]
Are we saying that the seed has been updated recently to 390?

**Comment by sramazzina** [comment]
No clear to me why @dixon22ma dcided to close this issue. Let me try to restart the description of this issue from the very beginning because maybe there is a point of misunderstanding.

This morning I pulled the latest changes from the adempiere repository, rebuild the ADempiere package on branch release/3.9.0 as usual. After the build completed successfully I started the setup of my just built ADempiere sistem then restored the seed by using RUN_ImportAdempiere as usual. As far as I now this procedure restores the only seed that exists that is ADempiere_pg.jar (I'm on Postgres of course).

After all these setup operations completed successfully I signed in to ADempiere and went to the  Migration screen that showed me that the very last migration applied was the 2240 as you can see in the screenshot below 

![screenshot from 2017-07-31 11-27-38](https://user-images.githubusercontent.com/1270945/28771487-4c3e6492-75e3-11e7-9853-ee136c51c2a3.png)

If I look in the _migration/380lts-release_ folder, the last migration file to be applied is 2980 and the immediateley next to the last applied is the  02250_928_Remove_Unnecessary_HR_Column.xml, the file that is giving the problem subject of this issue. So what am I missing in understanding what's wrong?

As a last step of this installation process, I tried to execute the RUN_MigrationXML and I get the same error. At this point, let me reopen this issue to make more clarity on this.

**Comment by yamelsenih** [comment]
Hi @sramazzina i test it generating a seed from the first XML to last and it is ok

**Comment by sramazzina** [comment]
As verified by the team, the current seed is a bit buggy and the problem is going to be fixed in the following hours during the release process that is currently in progress.
