### ISSUE TITLE
ADempiere-3.9.0 build process creates wrong folder

### ISSUE THREAD

**Issue by trifonnt** [adempiere/adempiere#1286]
ADempiere build script creates wrong folder: 
Adempiere/packagesHumanResourceAndPayroll/

Steps to reproduce:
1) Checkout branch release/3.9.0
$ git clone ..

2) Build from source code
$ cd utils_dev
$ RUN_build2.sh

3) Wrong folder is created
adempiere/Adempiere/packagesHumanResourceAndPayroll/

**Comment by marcalwestf** [comment]
@trifonnt I can reproduce this case: in the Eclipse development workspace , a build creates the folder you mention:
![20170721_adempiere_29](https://user-images.githubusercontent.com/1789408/28830563-5a9dce0e-7694-11e7-9834-9cb9671ecb99.png)

**Comment by trifonnt** [comment]
Victor, thank you for the fix!
Unfortunately I did not had time to research it.
