### ISSUE TITLE
POS: Processing transaction

### ISSUE THREAD

**Issue by ogomezislas** [adempiere/adempiere#1297]
A product is added for sale.
The method of payment is selected: cash

When processing the transaction (ok button) the following message is displayed and the operation is not performed.
<img width="1715" alt="captura de pantalla 2017-08-16 a la s 16 49 23" src="https://user-images.githubusercontent.com/787044/29428689-b84fa9de-8353-11e7-82e8-12d66d52f2c2.png">

The ADempierePOS.jar and ADempierePOSzk.jar files were generated from my Intellij environment (branch develop)

**Comment by e-Evolution** [comment]
@ogomezislas the problem is that deployment not are updated with last version 3.9, so you are using a obsolete binary code with last POS code , the solution update all environment.
