### ISSUE TITLE
Process class generator know List parameter as boolean

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#1303]
When a parameter is List of **Yes or No**, the process class generator know it as boolean instead **String**, it is a bug because a list **Yes or No** can have null value.

**Comment by yamelsenih** [comment]
Now it is as String instead boolean, a String can be Yes, No or null

**Comment by yamelsenih** [comment]
It retfurn a error with list as **No** value
-----------> FinReport.getColumnStatement: No Amount Type in line: MReportLine[1001461 - T - TOTALES, SeqNo=470, AmountType=null, PeriodType=null - LineType=S - SegmentValue - PostingType=A, AmountType=null, PeriodType=null] or column: MReportColumn[1000047 - ORIGEN - null, SeqNo=40, AmountType=B, PeriodType=null, CurrencyType=A/0 - ColumnType=C - Calculation=S - 1000184 - 1000185] [163]-----------> FinReport.getColumnStatement: No Amount Type in line: MReportLine[1001461 - T - TOTALES, SeqNo=470, AmountType=null, PeriodType=null - LineType=S - SegmentValue - PostingType=A, AmountType=null, PeriodType=null] or column: MReportColumn[1000048 - APLICACION - null, SeqNo=50, AmountType=null, PeriodType=null, CurrencyType=A/0 - ColumnType=C - Calculation=S - 1000184 - 1000185] [163]===========> FinReport.process: java.lang.Boolean cannot be cast to java.lang.String [163]java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String	at org.compiere.model.X_PA_Report.getListSources(X_PA_Report.java:270)	at org.compiere.report.FinReport.insertLineSource(FinReport.java:833)	at org.compiere.report.FinReport.insertLineDetail(FinReport.java:782)	at org.compiere.report.FinReport.doIt(FinReport.java:279)	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)	at org.compiere.apps.ProcessCtl.startProcess(ProcessCtl.java:623)	at org.compiere.apps.ProcessCtl.run(ProcessCtl.java:372)	at java.lang.Thread.run(Thread.java:748)

Thank @e-Evolution

**Comment by e-Evolution** [comment]
This change introducing an error for calculate columns values the data are damage.
