### ISSUE TITLE
Missing "Drill" functionality in HTML Report 

### ISSUE THREAD

**Issue by adaxa-steven** [adempiere/adempiere#1305]
the HTML Report has 2 small problems.
(1) the magnifying glass icon displayed in the Record ID column is not visible because of white image on light colour background
(2) there is some code missing. In the adaxa version you do not have to display the Table column for the "drill to document from magnifying glass". This code has been provided but appears not to have been applied.
 
![image](https://user-images.githubusercontent.com/15791084/29500491-62565a3c-8664-11e7-9580-4d2c18f4d198.png)

**Comment by rcapecce** [comment]
Hi @e-Evolution, I make a pull request with the dark find icon.
Remains to do item 2
