### ISSUE TITLE
@PeriodClosed@ message error does not appear in application interface 

### ISSUE THREAD

**Issue by ElPrience** [adempiere/adempiere#1306]
After press complete button in purchase order that is in a closed period 
the document status became invalid but the message error does not appear

**Comment by yamelsenih** [comment]
Hi @ElPrience, can you provide more information about it issue? A screenshot or step by step instructions for emulate this behavior

Best regards

**Comment by ElPrience** [comment]
![error](https://user-images.githubusercontent.com/26410185/29516845-7c02658a-8672-11e7-8610-f83faf14267a.PNG)
this message appears only in log  or console 
i  want to show it like the image

**Comment by yamelsenih** [comment]
I will review it. Thanks you for report it bug.

**Comment by Raul-mz** [comment]
It is already resolved, Now:
![image](https://user-images.githubusercontent.com/9552217/29528169-09f7400e-8669-11e7-8dda-8cdf248997c0.png)

**Comment by yamelsenih** [comment]
Hi @ElPrience can you test it?

**Comment by ElPrience** [comment]
Dear @yamelsenih 
it works good in 3.90
thank u 
but i am using 3.80

**Comment by ElPrience** [comment]
Thank u @Raul-mz

**Comment by yamelsenih** [comment]
@ElPrience ADempiere 3.9 have many functionality and bugfix, is nice migrate to it.

I will to close it.

Best regards
