### ISSUE TITLE
Ax_Case must be deleted on Financial Report

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#1307]
Currently exists a column named **Ax_Case** in **T_Report** table, it don't have functionality in financial report and must be deleted

**Comment by yamelsenih** [comment]
Some problem?

**Comment by e-Evolution** [comment]
@Yamle this functionality come from Pedro Pozo when try integrate in adempiere 

http://smartjsp.com/smartreport/AdvancedFinancialReportingForAdempiereV1.pdf

The idea is that have a way to separate the rows that are balance and the rows that not are of balance , and can be useful for some reports where is necessary to sort this way. my sugestion is not should remove.

**Comment by yamelsenih** [comment]
Hi @e-Evolution it can be added in a view I think

**Comment by adaxa-steven** [comment]
@e-Evolution .. I don't think it came from Predro .. I recognise my own bad naming.
