### ISSUE TITLE
Product costs per warehouse

### ISSUE THREAD

**Issue by AHussein12** [adempiere/adempiere#1310]
i  have a problem  in product costs window,
after completing material receipt in a certain warehouse and product > it works good  and   product cost dimension data is accurate 

![capddture](https://user-images.githubusercontent.com/26410185/29615696-29c67394-880f-11e7-8f28-06cb4d94b0d3.PNG)

the problem happens 
when changing the warehouse >> the product cost dimension data were empty 
![capturesss](https://user-images.githubusercontent.com/26410185/29615670-0ea83034-880f-11e7-8d19-673d49620079.PNG)

**Comment by ElPrience** [comment]
Hi @yamelsenih  you help me here ?

**Comment by trifonnt** [comment]
Hi @ElPrience,

> the problem happens
when changing the warehouse >> the product cost dimension data were empty

How do you change the warehouse?

**Comment by ElPrience** [comment]
Hi @trifonnt  
i change the warehouse in purchase order >

============================================
Test case 
1.create purchase order on a warehouse  x  and product a
2.create material receipt based on purchase order 
3.after completing material receipt i go to product costs window , and found data is  updated 
4.create purchase order on a warehouse  y  and product a
5.create material receipt based on purchase order 
6.after completing material receipt i go to product costs window , and found data is not  updated

**Comment by yamelsenih** [comment]
Hi @ElPrience what is your cost level? if you have a cost level?

**Comment by ElPrience** [comment]
Hi @yamelsenih 
Cost  level is  warehouse

**Comment by yamelsenih** [comment]
If you want keep the same cost for any warehouse then you should change cost level to organization
