### ISSUE TITLE
Tab "Sequence by year" missing in "Document sequence" window

### ISSUE THREAD

**Issue by liosc** [adempiere/adempiere#1311]
In the official ADempiere demo, the tab "Sequence by year" was missing in the definition of the window "Document sequence". I think the tab is necessary when the flag "Restart sequence every year" is active. Am I wrong?
I added the tab in the window definition but I don't know how to make the change permanent.

![image](https://user-images.githubusercontent.com/23416398/29812171-09bf6178-8ca6-11e7-803b-a3408249e183.png)

**Comment by yamelsenih** [comment]
Hi, this is not showed with last version....
![Screenshot_20190528_004932](https://user-images.githubusercontent.com/2333092/58451688-842cbf00-80e2-11e9-8598-336ec5a53b9f.png)
