### ISSUE TITLE
Create excel attachments for mails

### ISSUE THREAD

**Issue by SusanneCalderon** [adempiere/adempiere#1313]
Currently you can generate pdf-attachments. Sometimes it is usefull to create an xls or xlsx attachment from reportengine.
Solution: new method create new method 
```
public File getXLSX (File file) throws Exception
	{
		try
		{
			if (file == null)
				file = File.createTempFile ("ReportEngine", ".xlsx");

			//ordinary temp file - rename it
			if (!(file.getName().contains("_") || file.getName().contains("-"))) {
				file = rename(file);
			}
		}
		catch (IOException e)
		{
			log.log(Level.SEVERE, "", e);
		}
		PrintDataExcelExporter exp = new PrintDataExcelExporter(getPrintData(), getPrintFormat(), true);
		exp.export(file, getPrintFormat().getLanguage(), false);
		return file;
	}	//	getXLSX
```

**Comment by e-Evolution** [comment]
Hi @SusanneCalderon 

I think that not need this new method 

public void createXLSX(File outFile, Language language)
	throws Exception
	{
		PrintDataExcelExporter exp = new PrintDataExcelExporter(getPrintData(), getPrintFormat(), true);
		exp.export(outFile, language);
	}

Use this this method not need add other :


public void createXLSX(File outFile, Language language)
	throws Exception
	{
		PrintDataExcelExporter exp = new PrintDataExcelExporter(getPrintData(), getPrintFormat(), true);
		exp.export(outFile, language);
	}

**Comment by SusanneCalderon** [comment]
Hi Victor,
I want to create an excel attachment in an email, so I need to create the excel file without open excel.
The tempfile must be created an attached to the new email.
The method you mentioned in your comment opens excel.
PrintDataExcelExporter exp = new PrintDataExcelExporter(getPrintData(), getPrintFormat(), **true**);

**Comment by SusanneCalderon** [comment]
Sorry, the line wich creates the xlsx without opening excel  is
exp.export(file, getPrintFormat().getLanguage(), false);
