### ISSUE TITLE
ColumnName UUID is generated as mandatory

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#1325]
When default columns are generated, the UUID column is generated as mandatory and it make a error saving a record. Also the UUID is added by default to field as visible.

![screenshot_20170906_104018](https://user-images.githubusercontent.com/2333092/30117988-d33b6d36-92ef-11e7-9c55-dab975bba96f.png)

**Comment by sbouissa** [comment]
We saw this problem a few days ago: When we create a new table, the program set this column as mandatory , I think the problem could be because this column ends with "ID"

**Comment by yamelsenih** [comment]
Yes @sbouissa i will fix it. Also you can create issues for any error
