### ISSUE TITLE
GitHub strongly suggest to use releases to ship projects

### ISSUE THREAD

**Issue by homebeaver** [adempiere/adempiere#1326]
Hi,
when cloning the repo I got the following mail from github

The page build completed successfully, but returned the following warning for the `master` branch:

It looks like you're using GitHub Pages to distribute binary files. We strongly suggest that you use releases to ship projects on GitHub. Releases are GitHub's way of packaging and providing software to your users. You can think of it as a replacement to using downloads to provide software. We found the following file(s) which may be a good candidate for releases:` jboss/bin/jbosssvc.exe, jboss/bin/jbossweb.x64.exe, jboss/bin/jbosswebw.x64.exe, jboss/bin/native/openssl.exe, launch/Release/Adempiere.exe`, and `utils/windows/AdempiereService.exe`. For more information, see https://help.github.com/articles/about-releases/.

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/troubleshooting-jekyll-builds

**Comment by sramazzina** [comment]
We are planning a restructure of the project directories in the following phase. We will try to address also these things as much as possible. 

In any case, I've just cloned the ADempiere repository but I didn't get such issue. It's not clear to me when and where you're getting this warning message from GitHub.  Can you elaborate a bit more on this? Thanks a lot for your clarification

**Comment by homebeaver** [comment]
Hi @sramazzina , you will get the message when cloning to another github repo.
Not when cloning to a local git repo.

In my case I cloned to https://github.com/klst-de/adempiere

Regards

**Comment by homebeaver** [comment]
Stale Issue
