### ISSUE TITLE
Migration Tools -> The Currently migration tool Not create elements in the Data Base 

### ISSUE THREAD

**Issue by erprafaelrodriguez** [adempiere/adempiere#1329]
Hi Team.

Migrating my database to the version 390, I found that not create the elements mainly in the table "C_BPartner" in the DataBase, I have to synchronized of each element in the table for create in the DataBase.
.
The elements that not create are:
- uuid
- apenquiry
- arenquiry
- customeropeninvoice
- notposted
- gender
- birthday
- bloodgroup
- fhatersname
- placeofbith
- maritalstatus

Regards Team!

**Comment by PraponAdempiere** [comment]
I am migrating version too.  370 -> 380 -> 390, version by version

**Comment by sramazzina** [comment]
We also got some strange behaviors from this tool and we also have something to say. At the very end we decided to migrate from a 370 database to 390 by using MigrationXML and in my opinion works much better. I think we will always follow this approach.

**Comment by e-Evolution** [comment]
Hi @erprafaelrodriguez @PraponAdempiere 

@marcalwestf and me are work and fixed and improve the tools into the develop branch.

in next days we will try replicate and validate this changes, to validad that this columns are removed.

kind regards.

**Comment by erprafaelrodriguez** [comment]
Hello @e-Evolution 
In what I can help I do it with pleasur.

Regards

**Comment by yamelsenih** [comment]
Hi @erprafaelrodriguez can you test it with last version?

**Comment by yamelsenih** [comment]
SeeI: #1337
