### ISSUE TITLE
Add support for Request Standard Type

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#1330]
This new functionality will allow to create standard request types to any entity of the system, which will allow that when an entity is created the system to generate in automatic requests that must be managed

New domain model

R_StandardRequestType
- Value
- Name
- Description
- Help
- AD_Table_ID
- C_DocType_ID
- DocStatus
- EventModelValidator
- Valid from
- Valid To

R_StandardRequest
- SeqNo
- Summary
- R_RequestType_ID
- DueType
- R_Group_ID
- R_Category_ID
- R_Status_ID
- TaskStatus
- Priority
- SalesRep_ID
- AD_Role_ID
- DurationUnit 
- Duration
- Released Standard Request

**Comment by e-Evolution** [comment]
Window 
Name : Request Standard Type
Description : Defines Request Standard Type to create requests automatically
Help : The Standard Request Type allows creating Requests automatically based on a Table, Event model, Document Type, Document Status using the duration to calculate the Date next action, Start Plan, Start Date

![captura de pantalla 2017-09-13 a la s 16 35 23](https://user-images.githubusercontent.com/786968/30401934-9afa722a-98a1-11e7-9791-2c385bcbc8a9.png)

**Comment by e-Evolution** [comment]
Screen of Standard Request fields:

![captura de pantalla 2017-09-13 a la s 16 40 31](https://user-images.githubusercontent.com/786968/30402124-50ee49f8-98a2-11e7-9060-d8421e1ca925.png)

**Comment by e-Evolution** [comment]
New process to generate in batch mode a Request: 

![captura de pantalla 2017-09-13 a la s 17 16 03](https://user-images.githubusercontent.com/786968/30403434-414f0df2-98a7-11e7-872d-bcb279e0094f.png)

**Comment by adaxa-steven** [comment]
Hi Victor,
I am not sure what this is about ... can you explain.
For the record, here are some Request related changes we did that may be worth considering if adding capabilities in this area.
.. added an 'importance vs urgency' structure which set SLA response times (needed a couple of other small tables)
.. added a section on Request where the user could enter feedback to meet some Quality Management requirements to get info from customers about whether issue was handled ok
.. added a lot of the columns that appear in the Request into the Request Type so can store default values for each type of Request and populate on creation.
.. did some mods to Request email processor so if the email had an attachment, the email attachment was added as Request attachment.
regards
Steven

**Comment by e-Evolution** [comment]
Hi @adaxa-steven Steven , thank a lot for your comments.

Is possible see all these changes in an instance of testing, may be Adaxa demo?


The Request Standard Type allows defining the information necessary to create multiples request linked to any document or system entity (Purchase Order, Bussiness Partner).

The main idea is that any entity or document generate a task list or requests that need be following based on document type or document status, or when is an entity for master data any event model (Create, Delete, Update).

I a good example is when having you international purchase process, where is necessary manage multiples request as delivery, transportation, management international and receipt in warehouse multiples task that need be made and each request need a dead line and due date.

Now, this process can be executed manually but is tedious make request one by one, so then the Request Standard Type allows define for each document type and status that request is generated by document automatically.

My next step is to link the standard requests with standard tasks of a project type, so when a project is created the system will generate multiple requests for the task according to the type of standard request that linked,  allowing to manage this task using requests.

kind regards
Victor

**Comment by adaxa-steven** [comment]
Hi Victor
"My next step is to link the standard requests with standard tasks of a project type, so when a project is created the system will generate multiple requests for the task according to the type of standard request that linked, allowing to manage this task using requests."
... that sounds good.  I assume there will be a functional group review to agree to its adoption in core Adempiere before you make the changes?

This discussion reminded me of some other changes that you may think worth adding to Requests.  They happened over time and we would need to pull them out from various places.
.. add a subject line to the Request that can be used in emails generated by the Request
..add capability to include context variables in the email subject line of the Request so it is meaningful to the recipient without having to open it first to see what it is about.
..add 2 URLs to the end of Request emails, one logs you in to zkwebui and opens the Request window at that Request. The second URL opens the mobile phone Client and opens the Request window at that Request. [you still have to enter your login credentials]

regards
steven

**Comment by adaxa-steven** [comment]
Victor, 
pages 80 to 85 of this document  
http://www.adaxa.com/wp-content/uploads/HowToPDF/CaseStudyComplexOpenSourceDistributionSystem.pdf
 talks about the subject line added and the user survey but unfortunately does not show the urgency/importance matrix stuff .. will need to search further.  Will try to get a demo system fired up for you to look.

**Comment by niclopup** [comment]
Hi Víctor,

I think this is a great idea to improve the usage of the requests along the organizations.
I have some coments that perhaps can help.
In case of using this funtionality at a proyect task í believe the  R_StandardRequestType would need another table_id column to combine with because it hasn't a C_DocType_ID. I don't know if i understand ok the funtionality. If not, how it would work with this example?
Another thing would  be to add in R_StandardRequest the columns of "used product" when a request would be invoiced and "user" to let asign the request to someone special when define requests for service proyects. Olso resource could be usefull to plan some request in services proyects.

I hope this ideas could be useful.

Kind regards
Nicolas

**Comment by adaxa-steven** [comment]
Hi Victor,
this was another use-case we built... perhaps worth considering.
.. create PO
.. Create MR to a special location, tick as 'cross-dock'  [https://en.wikipedia.org/wiki/Cross-docking]  for everything on the PO
.. Generate Shipments ex the cross-doc location
.. Generate Inventory Moves automatically to put into long term storage and complete with barcode verification.
.. System finds any inventory that was on the PO and MR that is not accounted for, creates internal use inventory to clear and put in suspense account ... and then generates Request and sends to appropriate product manager so that the differences can be followed up and credits received.

**Comment by sbouissa** [comment]
Hi, Victor
We run the last migrations and we found an error running Adempiere, 
The column AD_Client_ID is missing in the table R_StandardRequestType. 

![error_req](https://user-images.githubusercontent.com/4325868/31627699-84847598-b284-11e7-9c5a-590560bb9aa0.png)

**Comment by e-Evolution** [comment]
Implement project functionality 1d6f889
