### ISSUE TITLE
Migration Tools ->Problem with the migration tool.

### ISSUE THREAD

**Issue by PMillanFurryWolf** [adempiere/adempiere#1337]
Hello team. A few days ago we tried to run the migration tool to update the version from the 3.8.0, to the 3.9.0 LTS. However, when we run it we notice that exist a lot of loss of information that is important for us. these loss of information are reflected in the table called "C_BPartner", in the fields: 

uuid
apenquiry
arenquiry
customeropeninvoice
notposted
gender
birthday
bloodgroup
fhatersname
placeofbith
maritalstatus

Also we tried to make a sincronization through Adempiere but without success.
besides, we notice that we loose some views and functions that we created before.
Do you have a idea of this?

Blessing.

**Comment by gabyrico83** [comment]
Hello! Any news about migration?

**Comment by PraponAon** [comment]
1. These fields may already be in AD_Column.
But not yet created in the table.
Open window Table and Column -> C_BPartner -> Column... press "Synchronize Column button" .

2. Create new data seed with the latest version. and re-migrate.

**Comment by yamelsenih** [comment]
hi, it is a bug? i have AD 391 installed from seed and is worked

**Comment by yamelsenih** [comment]
After migration is good sync all columns

you can check all with it:

<pre>
SELECT t.TableName, c.ColumnName
FROM AD_Table t
INNER JOIN AD_Column c ON(c.AD_Table_ID = t.AD_Table_ID)
WHERE t.IsView = 'N'
AND c.ColumnSQL IS NULL
AND NOT EXISTS(SELECT 1 FROM 
                 information_schema.columns 
                 WHERE upper(table_name) = upper(t.TableName) 
                 AND upper(column_name) = upper(c.ColumnName))
</pre>
