### ISSUE TITLE
Symbol for EUR is not €

### ISSUE THREAD

**Issue by homebeaver** [adempiere/adempiere#1338]
![20170914_211225](https://user-images.githubusercontent.com/3493126/30450965-ac35bb7a-9992-11e7-8f55-360f6aec14d1.png)

**Comment by yamelsenih** [comment]
Hi @trifonnt have you a change for it?

**Comment by trifonnt** [comment]
@yamelsenih I had no time to fix this yet.

**Comment by yamelsenih** [comment]
No problem, I can fix it today

**Comment by yamelsenih** [comment]
Hi @homebeaver it was solved.

Best regard.
