### ISSUE TITLE
Improve transactions in migration process

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#134]
1.- Currently exist duplicate code
2.- Now you can call same process of different way 
3.-The transaction is idle when try load XML filed and apply from process
4.- No exist a good management of transactions , the idea is each step should a transaction and each migration script too.

**Comment by e-Evolution** [comment]
working process ......

**Comment by mckayERP** [comment]
As of 682ab5d44, 1 Dec 2015, the import of xml files from the 370seed is hanging on the first import of file \Adempiere\migration\370lts-380lts\xml\0000_120_Merge_Migration.xml, Step 30.

Its hanging when a column in AD_Migration is synced.  I think, column additions/changes that need to be synced with the database require exclusive locks of the table for ALTER TABLE statements.  So for columns in AD_Migration, these have to be done when the AD_Migration Table has no locks.  For Columns in AD_MigrationStep - when AD_MigrationStep has no locks.  For other tables, the column sync can be done as part of the step apply/rollback.

The function getSteps() in MMigration 

			for ( MMigrationStep step : getSteps(false) )
			{

locks the AD_MigrationStep table.  There is a similar lock in the AD_Migration table but I haven't found the specific line yet.

So a migration can't add and sync columns in the AD_Migration table or AD_MigrationStep table unless there is a way to release the locks on these tables.  For ease of use, we need to find a way to allow changes to these tables as part of the migration loading.

**Comment by mckayERP** [comment]
This seems to fix it:

In MMigration.java, line 236

 //       MMigration mmigration = new Query(ctx, MMigration.Table_Name, where, trxName) // Locks migrationtable
        MMigration mmigration = new Query(ctx, MMigration.Table_Name, where, null)

In MigrationApply.java line 65

            public void run(String trxName) {
 //               MMigration migration = new MMigration(ctx ,migrationId , trxName);  // Locks migration table
                MMigration migration = new MMigration(ctx ,migrationId , null);        // Doesn't lock table 

Not sure yet how to allow changes to the migration record within the main transaction - for example, when updating the "applied" status.

**Comment by e-Evolution** [comment]
Hi Mike I review of code and saw that only execute an query to know if this migration exist 

MMigration migration = new Query(ctx, MMigration.Table_Name, where, trxName)
		.setParameters(name, Integer.parseInt(seqNo), entityType, releaseNo).firstOnly();
		if ( migration != null && migration.getAD_Migration_ID() > 0) {
			return migration;  // already exists (TODO: update?)
		}

I add sole checking that should be != null and Id > 0

so it not lock , because not exist then create a new record 


to create of nodes and steps 


		Node comment = (Element) element.getElementsByTagName("Comments").item(0);
		if ( comment != null )
			migration.setComments(comment.getTextContent());
		
		NodeList children = element.getElementsByTagName("Step");
		for ( int i = 0; i < children.getLength(); i++ )
		{
			Element step = (Element) children.item(i);
			if ( "Step".equals(step.getTagName()))
				MMigrationStep.fromXmlNode(migration, step);
				Trx.get(trxName, false).commit(true);
		}

the transaction that come in method come from MigrationLoader and is execute only to import of XML into DB.

When the xml is complete read and migration record is create the thread of transaction automatically make an commit and close this transaction.

**Comment by e-Evolution** [comment]
About of MigrationApply 

I refactory this , now the migration for each script is execute for an ADempiere process 

https://github.com/adempiere/adempiere/blob/hotfix/3.8.0%23002/base/src/org/compiere/process/MigrationApply.java#L65

So I create an transaction independent of process this way when an script migration is execute and it is successfully then commit this transaction independent of process transaction , this way each migration script is commit in your self transaction.

I think that the issue only happen when you run of process from UI Migration window , because if you use MigrationLoader from shell should can apply the change.

I am execute now all script of 380#002 , and have not problem let me check with previosn version

**Comment by mckayERP** [comment]
Hi Victor,  I've just added a pull request after extensive testing and refactoring of some of the code to align with new process approach you suggested.  I think it is much clearer and cleaner now - thanks.  I can now run the migrations successfully from 370 to 380#002.  When errors are introduced, the process responds in a more consistent fashion.

Mike

**Comment by e-Evolution** [comment]
The process now is working 

00:48:47.593   MMigration.updateStatus: Migration 263 - Express Receipt using barcode - 3.8.0#002 (D)  ---> Applied (A) [1]
00:48:47.593   MMigration.updateStatus: Migration 263 - Express Receipt using barcode - 3.8.0#002 (D)  ---> Applied (A) [1]
00:48:47.594 MigrationApply.addLog: 0 - null - null - Migration 263 - Express Receipt using barcode - 3.8.0#002 (D) Migration successful [1]
00:48:47.594 MigrationApply.addLog: 0 - null - null - Migration 263 - Express Receipt using barcode - 3.8.0#002 (D) Migration successful [1]
00:48:47.644   MigrationFromXML.applyMigration: Process=Apply migration Error=false Summary=OK [1]
00:48:47.644   MigrationFromXML.applyMigration: Process=Apply migration Error=false Summary=OK [1]
00:48:47.669   MigrationLoader.main: Process=Import migration from XML Error=false Summary=Import complete [1]
00:48:47.669   MigrationLoader.main: Process=Import migration from XML Error=false Summary=Import complete [1]
00:48:47.689 SequenceCheck.doIt:  [1]
00:48:47.689 SequenceCheck.doIt:  [1]
00:48:47.723 SequenceCheck.checkTableID: IDRangeEnd = 9999999 [1]
00:48:47.723 SequenceCheck.checkTableID: IDRangeEnd = 9999999 [1]
00:48:47.767 SequenceCheck.checkTableID: IDRangeEnd = 9999999 [1]
00:48:47.767 SequenceCheck.checkTableID: IDRangeEnd = 9999999 [1]
00:48:47.838 SequenceCheck.addLog: 0 - null - null - AD_Browse Sys 50048 -> 50063 [1]
00:48:47.838 SequenceCheck.addLog: 0 - null - null - AD_Browse Sys 50048 -> 50063 [1]
00:48:47.851 SequenceCheck.addLog: 0 - null - null - AD_Browse_Field Sys 54548 -> 55767 [1]
00:48:47.851 SequenceCheck.addLog: 0 - null - null - AD_Browse_Field Sys 54548 -> 55767 [1]
00:48:47.962 SequenceCheck.addLog: 0 - null - null - AD_Form Sys 53040 -> 53063 [1]
00:48:47.962 SequenceCheck.addLog: 0 - null - null - AD_Form Sys 53040 -> 53063 [1]
00:48:48.209 SequenceCheck.addLog: 0 - null - null - AD_PrintFormat Sys 50274 -> 50313 [1]
00:48:48.209 SequenceCheck.addLog: 0 - null - null - AD_PrintFormat Sys 50274 -> 50313 [1]
00:48:48.214 SequenceCheck.addLog: 0 - null - null - AD_PrintFormatItem Sys 57926 -> 58926 [1]
00:48:48.214 SequenceCheck.addLog: 0 - null - null - AD_PrintFormatItem Sys 57926 -> 58926 [1]
00:48:48.254 SequenceCheck.addLog: 0 - null - null - AD_Reference Sys 53689 -> 53844 [1]
00:48:48.254 SequenceCheck.addLog: 0 - null - null - AD_Reference Sys 53689 -> 53844 [1]
00:48:48.308 SequenceCheck.addLog: 0 - null - null - AD_ReportView Sys 53154 -> 53208 [1]
00:48:48.308 SequenceCheck.addLog: 0 - null - null - AD_ReportView Sys 53154 -> 53208 [1]
00:48:48.366 SequenceCheck.addLog: 0 - null - null - AD_Tab Sys 54019 -> 54213 [1]
00:48:48.366 SequenceCheck.addLog: 0 - null - null - AD_Tab Sys 54019 -> 54213 [1]
00:48:48.371 SequenceCheck.addLog: 0 - null - null - AD_Table Sys 53926 -> 54134 [1]
00:48:48.371 SequenceCheck.addLog: 0 - null - null - AD_Table Sys 53926 -> 54134 [1]
00:48:48.483 SequenceCheck.addLog: 0 - null - null - AD_Val_Rule ID  1000000 -> 1000001 [1]
00:48:48.483 SequenceCheck.addLog: 0 - null - null - AD_Val_Rule ID  1000000 -> 1000001 [1]
00:48:48.486 SequenceCheck.addLog: 0 - null - null - AD_View Sys 50040 -> 50056 [1]
00:48:48.486 SequenceCheck.addLog: 0 - null - null - AD_View Sys 50040 -> 50056 [1]
00:48:48.490 SequenceCheck.addLog: 0 - null - null - AD_View_Column Sys 53349 -> 54510 [1]
00:48:48.490 SequenceCheck.addLog: 0 - null - null - AD_View_Column Sys 53349 -> 54510 [1]
00:48:48.495 SequenceCheck.addLog: 0 - null - null - AD_View_Definition Sys 50088 -> 50118 [1]
00:48:48.495 SequenceCheck.addLog: 0 - null - null - AD_View_Definition Sys 50088 -> 50118 [1]
00:48:48.556 SequenceCheck.addLog: 0 - null - null - AD_WF_Node Sys 50193 -> 50231 [1]
00:48:48.556 SequenceCheck.addLog: 0 - null - null - AD_WF_Node Sys 50193 -> 50231 [1]
00:48:48.560 SequenceCheck.addLog: 0 - null - null - AD_WF_NodeNext Sys 50149 -> 50179 [1]
00:48:48.560 SequenceCheck.addLog: 0 - null - null - AD_WF_NodeNext Sys 50149 -> 50179 [1]
00:48:48.586 SequenceCheck.addLog: 0 - null - null - AD_Window Sys 53388 -> 53480 [1]
00:48:48.586 SequenceCheck.addLog: 0 - null - null - AD_Window Sys 53388 -> 53480 [1]
00:48:48.608 SequenceCheck.addLog: 0 - null - null - AD_Workflow Sys 50042 -> 50051 [1]
00:48:48.608 SequenceCheck.addLog: 0 - null - null - AD_Workflow Sys 50042 -> 50051 [1]
00:48:52.206 MSequence.checkClientSequences: AD_Client_ID=0 - created #2 - success=true [1]
00:48:52.206 MSequence.checkClientSequences: AD_Client_ID=0 - created #2 - success=true [1]
00:48:52.248 MSequence.checkClientSequences: AD_Client_ID=11 - created #2 - success=true [1]
00:48:52.248 MSequence.checkClientSequences: AD_Client_ID=11 - created #2 - success=true [1]
00:48:52.290   MigrationLoader.main: Process=Sequence Check Error=false Summary=Sequence Check [1]
00:48:52.290   MigrationLoader.main: Process=Sequence Check Error=false Summary=Sequence Check [1]
00:48:52.355 SynchronizeTerminology.doIt: Adding missing Element Translations [1]
00:48:52.355 SynchronizeTerminology.doIt: Adding missing Element Translations [1]
00:48:52.420 SynchronizeTerminology.doIt:   rows updated: 9 [1]
00:48:52.420 SynchronizeTerminology.doIt:   rows updated: 9 [1]
00:48:52.421 SynchronizeTerminology.doIt: Creating link from Element to Column [1]
00:48:52.421 SynchronizeTerminology.doIt: Creating link from Element to Column [1]
00:48:52.436 SynchronizeTerminology.doIt:   rows updated: 0 [1]
00:48:52.436 SynchronizeTerminology.doIt:   rows updated: 0 [1]
00:48:52.436 SynchronizeTerminology.doIt: Deleting unused Elements [1]
00:48:52.436 SynchronizeTerminology.doIt: Deleting unused Elements [1]
00:48:52.491 SynchronizeTerminology.doIt:   rows deleted: 10 [1]
00:48:52.491 SynchronizeTerminology.doIt:   rows deleted: 10 [1]
00:48:52.520 SynchronizeTerminology.doIt:   rows deleted: 0 [1]
00:48:52.520 SynchronizeTerminology.doIt:   rows deleted: 0 [1]
00:48:52.520 SynchronizeTerminology.doIt: Synchronize Column [1]
00:48:52.520 SynchronizeTerminology.doIt: Synchronize Column [1]
00:48:52.588 SynchronizeTerminology.doIt:   rows updated: 1 [1]
00:48:52.588 SynchronizeTerminology.doIt:   rows updated: 1 [1]
00:48:52.594 SynchronizeTerminology.doIt: Synchronize Field [1]
00:48:52.594 SynchronizeTerminology.doIt: Synchronize Field [1]
00:48:52.785 SynchronizeTerminology.doIt:   rows updated: 104 [1]
00:48:52.785 SynchronizeTerminology.doIt:   rows updated: 104 [1]
00:48:52.796 SynchronizeTerminology.doIt: Synchronize Field Translations [1]
00:48:52.796 SynchronizeTerminology.doIt: Synchronize Field Translations [1]
00:48:53.237 SynchronizeTerminology.doIt:   rows updated: 333 [1]
00:48:53.237 SynchronizeTerminology.doIt:   rows updated: 333 [1]
00:48:53.249 SynchronizeTerminology.doIt: Synchronize PO Field [1]
00:48:53.249 SynchronizeTerminology.doIt: Synchronize PO Field [1]
00:48:53.316 SynchronizeTerminology.doIt:   rows updated: 107 [1]
00:48:53.316 SynchronizeTerminology.doIt:   rows updated: 107 [1]
00:48:53.323 SynchronizeTerminology.doIt: Synchronize PO Field Translations [1]
00:48:53.323 SynchronizeTerminology.doIt: Synchronize PO Field Translations [1]
00:48:53.418 SynchronizeTerminology.doIt:   rows updated: 63 [1]
00:48:53.418 SynchronizeTerminology.doIt:   rows updated: 63 [1]
00:48:53.419 SynchronizeTerminology.doIt: Synchronize Field from Process [1]
00:48:53.419 SynchronizeTerminology.doIt: Synchronize Field from Process [1]
00:48:53.469 SynchronizeTerminology.doIt:   rows updated: 22 [1]
00:48:53.469 SynchronizeTerminology.doIt:   rows updated: 22 [1]
00:48:53.474 SynchronizeTerminology.doIt: Synchronize Field Trl from Process Trl [1]
00:48:53.474 SynchronizeTerminology.doIt: Synchronize Field Trl from Process Trl [1]
00:48:53.557 SynchronizeTerminology.doIt:   rows updated: 22 [1]
00:48:53.557 SynchronizeTerminology.doIt:   rows updated: 22 [1]
00:48:53.557 SynchronizeTerminology.doIt: Synchronize Browse Field [1]
00:48:53.557 SynchronizeTerminology.doIt: Synchronize Browse Field [1]
00:48:53.580 SynchronizeTerminology.doIt:   rows updated: 30 [1]
00:48:53.580 SynchronizeTerminology.doIt:   rows updated: 30 [1]
00:48:53.595 SynchronizeTerminology.doIt: Synchronize Browse Field Translations [1]
00:48:53.595 SynchronizeTerminology.doIt: Synchronize Browse Field Translations [1]
00:48:53.700 SynchronizeTerminology.doIt:   rows updated: 985 [1]
00:48:53.700 SynchronizeTerminology.doIt:   rows updated: 985 [1]
00:48:53.716 SynchronizeTerminology.doIt:   rows updated: 0 [1]
00:48:53.716 SynchronizeTerminology.doIt:   rows updated: 0 [1]
00:48:53.722 SynchronizeTerminology.doIt:   rows updated: 0 [1]
00:48:53.722 SynchronizeTerminology.doIt:   rows updated: 0 [1]
00:48:53.722 SynchronizeTerminology.doIt: Synchronize Process Parameter [1]
00:48:53.722 SynchronizeTerminology.doIt: Synchronize Process Parameter [1]
00:48:53.734 SynchronizeTerminology.doIt:   rows updated: 1 [1]
00:48:53.734 SynchronizeTerminology.doIt:   rows updated: 1 [1]
00:48:53.740 SynchronizeTerminology.doIt: Synchronize Process Parameter Trl [1]
00:48:53.740 SynchronizeTerminology.doIt: Synchronize Process Parameter Trl [1]
00:48:54.337 SynchronizeTerminology.doIt:   rows updated: 86 [1]
00:48:54.337 SynchronizeTerminology.doIt:   rows updated: 86 [1]
00:48:54.342 SynchronizeTerminology.doIt: Synchronize Workflow Node from Window [1]
00:48:54.342 SynchronizeTerminology.doIt: Synchronize Workflow Node from Window [1]
00:48:54.345 SynchronizeTerminology.doIt:   rows updated: 1 [1]
00:48:54.345 SynchronizeTerminology.doIt:   rows updated: 1 [1]
00:48:54.345 SynchronizeTerminology.doIt: Synchronize Workflow Node Trl from Window Trl [1]
00:48:54.345 SynchronizeTerminology.doIt: Synchronize Workflow Node Trl from Window Trl [1]
00:48:54.354 SynchronizeTerminology.doIt:   rows updated: 1 [1]
00:48:54.354 SynchronizeTerminology.doIt:   rows updated: 1 [1]
00:48:54.354 SynchronizeTerminology.doIt: Synchronize Workflow Node from Form [1]
00:48:54.354 SynchronizeTerminology.doIt: Synchronize Workflow Node from Form [1]
00:48:54.357 SynchronizeTerminology.doIt:   rows updated: 0 [1]
00:48:54.357 SynchronizeTerminology.doIt:   rows updated: 0 [1]
00:48:54.357 SynchronizeTerminology.doIt: Synchronize Workflow Node Trl from Form Trl [1]
00:48:54.357 SynchronizeTerminology.doIt: Synchronize Workflow Node Trl from Form Trl [1]
00:48:54.360 SynchronizeTerminology.doIt:   rows updated: 0 [1]
00:48:54.360 SynchronizeTerminology.doIt:   rows updated: 0 [1]
00:48:54.360 SynchronizeTerminology.doIt: Synchronize Workflow Node from Process [1]
00:48:54.360 SynchronizeTerminology.doIt: Synchronize Workflow Node from Process [1]
00:48:54.363 SynchronizeTerminology.doIt:   rows updated: 1 [1]
00:48:54.363 SynchronizeTerminology.doIt:   rows updated: 1 [1]
00:48:54.364 SynchronizeTerminology.doIt: Synchronize Workflow Node Trl from Process Trl [1]
00:48:54.364 SynchronizeTerminology.doIt: Synchronize Workflow Node Trl from Process Trl [1]
00:48:54.368 SynchronizeTerminology.doIt:   rows updated: 1 [1]
00:48:54.368 SynchronizeTerminology.doIt:   rows updated: 1 [1]
00:48:54.368 SynchronizeTerminology.doIt: Synchronize PrintFormatItem Name from Element [1]
00:48:54.368 SynchronizeTerminology.doIt: Synchronize PrintFormatItem Name from Element [1]
00:48:54.431 SynchronizeTerminology.doIt:   rows updated: 6 [1]
00:48:54.431 SynchronizeTerminology.doIt:   rows updated: 6 [1]
00:48:54.437 SynchronizeTerminology.doIt: Synchronize PrintFormatItem PrintName from Element [1]
00:48:54.437 SynchronizeTerminology.doIt: Synchronize PrintFormatItem PrintName from Element [1]
00:48:54.505 SynchronizeTerminology.doIt:   rows updated: 6 [1]
00:48:54.505 SynchronizeTerminology.doIt:   rows updated: 6 [1]
00:48:54.511 SynchronizeTerminology.doIt: Synchronize PrintFormatItem Trl from Element Trl (Multi-Lingual) [1]
00:48:54.511 SynchronizeTerminology.doIt: Synchronize PrintFormatItem Trl from Element Trl (Multi-Lingual) [1]
00:48:54.577 SynchronizeTerminology.doIt:   rows updated: 100 [1]
00:48:54.577 SynchronizeTerminology.doIt:   rows updated: 100 [1]
00:48:54.583 SynchronizeTerminology.doIt: Synchronize PrintFormatItem Trl (Not Multi-Lingual) [1]
00:48:54.583 SynchronizeTerminology.doIt: Synchronize PrintFormatItem Trl (Not Multi-Lingual) [1]
00:48:54.595 SynchronizeTerminology.doIt:   rows updated: 0 [1]
00:48:54.595 SynchronizeTerminology.doIt:   rows updated: 0 [1]
00:48:54.596 SynchronizeTerminology.doIt: Reset PrintFormatItem Trl where not used in base table [1]
00:48:54.596 SynchronizeTerminology.doIt: Reset PrintFormatItem Trl where not used in base table [1]
00:48:54.602 SynchronizeTerminology.doIt:   rows updated: 0 [1]
00:48:54.602 SynchronizeTerminology.doIt:   rows updated: 0 [1]
00:48:54.602 SynchronizeTerminology.doIt: Synchronizing Menu with Window [1]
00:48:54.602 SynchronizeTerminology.doIt: Synchronizing Menu with Window [1]
00:48:54.616 SynchronizeTerminology.doIt:   rows updated: 391 [1]
00:48:54.616 SynchronizeTerminology.doIt:   rows updated: 391 [1]
00:48:54.689 SynchronizeTerminology.doIt:   rows updated: 391 [1]
00:48:54.689 SynchronizeTerminology.doIt:   rows updated: 391 [1]
00:48:54.690 SynchronizeTerminology.doIt: Synchronizing Menu with Processes [1]
00:48:54.690 SynchronizeTerminology.doIt: Synchronizing Menu with Processes [1]
00:48:54.697 SynchronizeTerminology.doIt:   rows updated: 186 [1]
00:48:54.697 SynchronizeTerminology.doIt:   rows updated: 186 [1]
00:48:54.717 SynchronizeTerminology.doIt:   rows updated: 185 [1]
00:48:54.717 SynchronizeTerminology.doIt:   rows updated: 185 [1]
00:48:54.723 SynchronizeTerminology.doIt: Synchronizing Menu with Forms [1]
00:48:54.723 SynchronizeTerminology.doIt: Synchronizing Menu with Forms [1]
00:48:54.726 SynchronizeTerminology.doIt:   rows updated: 33 [1]
00:48:54.726 SynchronizeTerminology.doIt:   rows updated: 33 [1]
00:48:54.762 SynchronizeTerminology.doIt:   rows updated: 33 [1]
00:48:54.762 SynchronizeTerminology.doIt:   rows updated: 33 [1]
00:48:54.762 SynchronizeTerminology.doIt: Synchronizing Menu with Workflows [1]
00:48:54.762 SynchronizeTerminology.doIt: Synchronizing Menu with Workflows [1]
00:48:54.765 SynchronizeTerminology.doIt:   rows updated: 21 [1]
00:48:54.765 SynchronizeTerminology.doIt:   rows updated: 21 [1]
00:48:54.773 SynchronizeTerminology.doIt:   rows updated: 21 [1]
00:48:54.773 SynchronizeTerminology.doIt:   rows updated: 21 [1]
00:48:54.778 SynchronizeTerminology.doIt: Synchronizing Menu with Tasks [1]
00:48:54.778 SynchronizeTerminology.doIt: Synchronizing Menu with Tasks [1]
00:48:54.782 SynchronizeTerminology.doIt:   rows updated: 3 [1]
00:48:54.782 SynchronizeTerminology.doIt:   rows updated: 3 [1]
00:48:54.802 SynchronizeTerminology.doIt:   rows updated: 3 [1]
00:48:54.802 SynchronizeTerminology.doIt:   rows updated: 3 [1]
00:48:54.803 SynchronizeTerminology.doIt: Synchronizing Column with Element [1]
00:48:54.803 SynchronizeTerminology.doIt: Synchronizing Column with Element [1]
00:48:54.850 SynchronizeTerminology.doIt:   rows updated: 0 [1]
00:48:54.850 SynchronizeTerminology.doIt:   rows updated: 0 [1]
00:48:55.032 SynchronizeTerminology.doIt:   rows updated: 412 [1]
00:48:55.032 SynchronizeTerminology.doIt:   rows updated: 412 [1]
00:48:55.044 SynchronizeTerminology.doIt: Synchronizing Table with Element [1]
00:48:55.044 SynchronizeTerminology.doIt: Synchronizing Table with Element [1]
00:48:55.066 SynchronizeTerminology.doIt:   rows updated: 7 [1]
00:48:55.066 SynchronizeTerminology.doIt:   rows updated: 7 [1]
00:48:55.098 SynchronizeTerminology.doIt:   trl rows updated: 8 [1]
00:48:55.098 SynchronizeTerminology.doIt:   trl rows updated: 8 [1]
00:48:55.109 SynchronizeTerminology.doIt:   trl rows updated: 54 [1]
00:48:55.109 SynchronizeTerminology.doIt:   trl rows updated: 54 [1]
00:48:55.210 SynchronizeTerminology.doIt:   trl rows updated: 54 [1]
00:48:55.210 SynchronizeTerminology.doIt:   trl rows updated: 54 [1]
00:48:55.210 SynchronizeTerminology.doIt: Synchronizing Report View with Table [1]
00:48:55.210 SynchronizeTerminology.doIt: Synchronizing Report View with Table [1]
00:48:55.339 SynchronizeTerminology.doIt:   trl rows updated: 105 [1]
00:48:55.339 SynchronizeTerminology.doIt:   trl rows updated: 105 [1]
00:48:55.345 SynchronizeTerminology.doIt: Synchronizing Report View with Table [1]
00:48:55.345 SynchronizeTerminology.doIt: Synchronizing Report View with Table [1]
00:48:55.358 SynchronizeTerminology.doIt:   trl rows updated: 2 [1]
00:48:55.358 SynchronizeTerminology.doIt:   trl rows updated: 2 [1]
00:48:55.362   MigrationLoader.main: Process=Synchronize Terminology Error=false Summary=OK [1]
00:48:55.362   MigrationLoader.main: Process=Synchronize Terminology Error=false Summary=OK [1]
00:48:55.389 RoleAccessUpdate.doIt: AD_Client_ID=0, AD_Role_ID=-1 [1]
00:48:55.389 RoleAccessUpdate.doIt: AD_Client_ID=0, AD_Role_ID=-1 [1]
00:48:55.392 RoleAccessUpdate.addLog: 0 - null - null - Role Template: - [1]
00:48:55.392 RoleAccessUpdate.addLog: 0 - null - null - Role Template: - [1]
00:48:55.497 RoleAccessUpdate.addLog: 0 - null - null - System Administrator: @AD_Window_ID@ #159 -  @AD_Process_ID@ #85 -  @AD_Form_ID@ #11 -  @AD_Browse_ID@ #1 -  @AD_Workflow_ID@ #9 -  @DocAction@ #14 [1]
00:48:55.497 RoleAccessUpdate.addLog: 0 - null - null - System Administrator: @AD_Window_ID@ #159 -  @AD_Process_ID@ #85 -  @AD_Form_ID@ #11 -  @AD_Browse_ID@ #1 -  @AD_Workflow_ID@ #9 -  @DocAction@ #14 [1]
00:48:55.570 RoleAccessUpdate.addLog: 0 - null - null - GardenWorld Admin: @AD_Window_ID@ #390 -  @AD_Process_ID@ #411 -  @AD_Form_ID@ #39 -  @AD_Browse_ID@ #31 -  @AD_Workflow_ID@ #56 -  @DocAction@ #658 [1]
00:48:55.570 RoleAccessUpdate.addLog: 0 - null - null - GardenWorld Admin: @AD_Window_ID@ #390 -  @AD_Process_ID@ #411 -  @AD_Form_ID@ #39 -  @AD_Browse_ID@ #31 -  @AD_Workflow_ID@ #56 -  @DocAction@ #658 [1]
00:48:55.634 RoleAccessUpdate.addLog: 0 - null - null - GardenWorld User: @AD_Window_ID@ #260 -  @AD_Process_ID@ #365 -  @AD_Form_ID@ #32 -  @AD_Browse_ID@ #31 -  @AD_Workflow_ID@ #53 -  @DocAction@ #658 [1]
00:48:55.634 RoleAccessUpdate.addLog: 0 - null - null - GardenWorld User: @AD_Window_ID@ #260 -  @AD_Process_ID@ #365 -  @AD_Form_ID@ #32 -  @AD_Browse_ID@ #31 -  @AD_Workflow_ID@ #53 -  @DocAction@ #658 [1]
00:48:55.634 RoleAccessUpdate.addLog: 0 - null - null - Web Service Execution: - [1]
00:48:55.634 RoleAccessUpdate.addLog: 0 - null - null - Web Service Execution: - [1]
00:48:55.933   MigrationLoader.main: Process=Role Access Update Error=false Summary= [1]
00:48:55.933   MigrationLoader.main: Process=Role Access Update Error=false Summary= [1]
00:48:56.832   CleanUpGW.doIt: Successfully updated Garden World data. [1]
00:48:56.832   CleanUpGW.doIt: Successfully updated Garden World data. [1]
00:48:56.915   MigrationLoader.main: Process=Clean Up Garden World Error=false Summary=Successfully updated Garden World data. [1]
00:48:56.915   MigrationLoader.main: Process=Clean Up Garden World Error=false Summary=Successfully updated Garden World data. [1]

*** 2016-08-03 00:48:56.921 Adempiere Log (CLogConsole) ***
