### ISSUE TITLE
Product Price List Version Input Text box vanish entered value.

### ISSUE THREAD

**Issue by ayazbaloch** [adempiere/adempiere#1341]
@e-Evolution
Open Product window.
Go to any product record then click Price tab.
Click new button to create new Product Price list.
Enter "Price List version" then move to any field, notice that entered value clear from the box.

**Comment by erprafaelrodriguez** [comment]
Hi @ayazbaloch !!

I replicate your exercise and not have problem! 

![github](https://user-images.githubusercontent.com/20327157/30766620-dcf8d592-9fbb-11e7-935a-1a95c2eaedbc.png)

**Comment by ayazbaloch** [comment]
Hi @erprafaelrodriguez and @e-Evolution 
Thanks to response, I re-checked it at my office and home PC and also in Chrome, firefox and IE browser but still it is same.
I checked it from http://demo.testadempiere.com/webui/index.zul
and my local installed Adempiere, but result is same as mentioned.
May be I need some updates from branches.

**Comment by adaxa-steven** [comment]
Hi.
In the product price tab you can only select an existing price list version then enter price values for that product.  It sounds like you may be trying to add a price list version in the product windows?

**Comment by ayazbaloch** [comment]
Thanks @adaxa-steven 
Exactly you are right, it is open text field and user can enter any value to it, My recommendation it should be limit from drop down,where user must select from them.
