### ISSUE TITLE
Adempiere Smart Browser zoom functionality should be override High Volume marked table.

### ISSUE THREAD

**Issue by ayazbaloch** [adempiere/adempiere#1354]
@e-Evolution and @yamelsenih 
High Volume marked table when zoomed from the Smart Browser should not be prompted for parameters. Zoom functionality already carrying a ID.

In my case a window has high volume data, I made Browser and select the record and click zoom in Smart Browser, it opens a desire window with parameters.

**Comment by ayazbaloch** [comment]
Illustration:-
Login as System----->Find "RV_PP_MRP_Supply" into Table and Column window.
Mark it as "High Volume"
![image](https://user-images.githubusercontent.com/10656336/31574873-50c3b108-b0f2-11e7-947b-3c89349b8946.png)

Now login as GardenAdmin
Run Cache Reset process.
Open "MRP Supplies Browse" browser.  Extract all records.

![image](https://user-images.githubusercontent.com/10656336/31574896-356f37aa-b0f3-11e7-8197-e88a3be37c1c.png)

Select any one record then click zoom button. It will as you for parameter value, leave it blank and click OK button.

![image](https://user-images.githubusercontent.com/10656336/31574907-814aff74-b0f3-11e7-92c6-f9761a93f1d9.png)

Now "MRP Supplies View" window showed all records.

![image](https://user-images.githubusercontent.com/10656336/31574918-d0ef057a-b0f3-11e7-8bed-2dcb5d40925b.png)

**Comment by yamelsenih** [comment]
Hi @ayazbaloch le me view it.

**Comment by yamelsenih** [comment]
Hi @ayazbaloch i will fix it

**Comment by yamelsenih** [comment]
Please continue discussion and testing here: https://github.com/adempiere/adempiere/pull/1855

**Comment by ayazbaloch** [comment]
ok, @yamelsenih  let me check and test.

**Comment by ayazbaloch** [comment]
Hi @yamelsenih  I checked it ok for select one record it shows properly without prompting parameters.
But Selecting more than one records it shows 1st record, where you already mentioned in the following lilnk.
https://github.com/adempiere/adempiere/issues/1458
