### ISSUE TITLE
Look & Feel: wrong colour on button

### ISSUE THREAD

**Issue by adaxa-steven** [adempiere/adempiere#1368]
in an html report if you display the record_id field the value displays as a magnifying glass to indicate you can zoom directly to the record.
the colour of the magnifying glass is almost the same as the background colour and it is very small

![image](https://user-images.githubusercontent.com/15791084/31472103-50f1ed7c-af38-11e7-9d19-0ac3d4649eca.png)

**Comment by rcapecce** [comment]
@eduardolopezuy this issue is being solved in incident #1305
