### ISSUE TITLE
missing column in trial balance temporary table

### ISSUE THREAD

**Issue by adaxa-steven** [adempiere/adempiere#1369]
![image](https://user-images.githubusercontent.com/15791084/31472512-e55e4cb0-af3a-11e7-9d5d-adaef1d9dfdc.png)

(SELECT C_Invoice_ID FROM C_AllocationLine WHERE C_AllocationLine_ID=Line_ID AND AD_Table_ID=735)

used in AR and AP trial balance report so you can zoom from a payment allocation GL entry directly to the Payment (column is there) or to the Invoice (column is missing)

**Comment by marcalwestf** [comment]
hi @adaxa-steven do you mean we have to add this column sql in seed?

**Comment by adaxa-steven** [comment]
Mario
it is already there .. I missed it.
![image](https://user-images.githubusercontent.com/15791084/31525775-62c374a4-b00e-11e7-8c1b-0fc4f0e45ea9.png)
