### ISSUE TITLE
attribute for concept, to execute a rule for a identifier payroll

### ISSUE THREAD

**Issue by ogomezislas** [adempiere/adempiere#137]
You need to run a rule for a specific payroll.
In the attribute payroll that calls the rule, payroll run is identified.
The process does not identify settings in the attribute payroll, so you do not run the correct rule.
 
The call to attribute must identify if executed for a specific payroll or take the record without identifying payroll.

**Comment by e-Evolution** [comment]
What is need the setting an attribute by payroll ?, if you can using if clauses set this logic in of rule , so the control should are in rule not in data model.

**Comment by ogomezislas** [comment]
The logic behind the concept is that attributes can be configured to run for a single employee, department, job or payroll.
If the attribute is marked to be seen only for a specific employee, the calculation apply only a employee. 
And this does not happen when configured for a specific payroll.

Example:
The calculation of a concept is different for payroll 1 and payroll 2.
The configuration of the concept, should have two attributes, the first attribute, run the rule for payroll 1, and the second attribute, run the rule for the payroll 2.

Either the question is, what function HR_Payroll_ID in the attributes.
