### ISSUE TITLE
POS window bug - web user interface custom form

### ISSUE THREAD

**Issue by niclopup** [adempiere/adempiere#1374]
There is a problem with POS window.

It shows the following alert:

The selected web user interface custom form 'org.adempiere.pos.WPOS' is not accessible.[SQL: 0, 42703]

![captura de pantalla_2017-10-12_15-12-09](https://user-images.githubusercontent.com/31936815/31514475-1b13729a-af68-11e7-94df-2cda90f6fa72.png)

The sing in was with GardenAdmin in Central Store and the configuratión was this:

![captura de pantalla_2017-10-12_16-05-02](https://user-images.githubusercontent.com/31936815/31514494-290f4824-af68-11e7-8de0-2c794c4ad35e.png)

**Comment by yamelsenih** [comment]
I was solved yet
