### ISSUE TITLE
jasper report in webui of financial report does not work

### ISSUE THREAD

**Issue by jdaison** [adempiere/adempiere#1378]
I have Process with report attached like this: 

![image](https://user-images.githubusercontent.com/6097506/31522416-52c03a4c-af73-11e7-80d7-f3b0a8ba2a22.png)

Then I generate report

![image](https://user-images.githubusercontent.com/6097506/31522476-87d76f48-af73-11e7-9cb3-b63a0c7979b3.png)

In swing works ok but in webui generate this error:

![image](https://user-images.githubusercontent.com/6097506/31522514-bd213ee0-af73-11e7-9b5f-b259705c9684.png)

attach file with all
[log.txt](https://github.com/adempiere/adempiere/files/1380969/log.txt)
 trace log

**Comment by yamelsenih** [comment]
Hi @jdaison for swing UI worked it?

**Comment by jdaison** [comment]
Yes. In swing it works

**Comment by yamelsenih** [comment]
Hi @jdaison i test it and i find the follow:
1. Common logging library is not added to build path.
2. The flag is pirnt preview is false and report is generated as pdf instead show to end user.

See:

<pre>
// You can use JasperPrint to create PDF
// Used For the PH
try {
	File PDF = File.createTempFile("mail", ".pdf");
	JasperExportManager.exportReportToPdfFile(jasperPrint, PDF.getAbsolutePath());
	processInfo.setPDFReport(PDF);
	if (processInfo.isPrintPreview()) {
		log.info("ReportStarter.startProcess run report -" + jasperPrint.getName());
		JRViewerProvider viewerLauncher = getReportViewerProvider();
		//viewerLauncher.openViewer(jasperPrint, pi.getTitle()+" - " + reportPath);
		viewerLauncher.openViewer(jasperPrint, pi.getTitle() + "_" + pi.getRecord_ID() + ".pdf");
	}
} catch (IOException e) {
	log.severe("ReportStarter.startProcess: Can not make PDF File - "+ e.getMessage());
}
// You can use JasperPrint to create PDF
</pre>
The server console is:
<pre>
root@PSI:/tmp# ls                                                                                                                                                                     
+~JF3540452689944952797.tmp                     Test.jrxml                                                                                                                            
+~JF4219729611511869466.tmp                     hsperfdata_root                                                                                                                       
BALANCE_DE_COMPROBACION4663330564758451341.pdf  mail2178496602023817547.pdf                                                                                                           
BALANCE_DE_COMPROBACION4663823323495223152.pdf  mail3486534478451518621.pdf                                                                                                           
BALANCE_GENERAL2540095314134684912.pdf          mail419269729201357959.pdf                                                                                                            
BALANCE_GENERAL5672271805804258449.pdf          mail6709662738849691370.pdf                                                                                                           
BALANCE_GENERAL9112662758341032309.pdf          mail735644781124346707.pdf                                                                                                            
Test.jasper                                     mail765199678758631888.pdf  
</pre>

**Comment by yamelsenih** [comment]
Hi @jdaison i find it:
- The report is launched only if it is flagged as **IsPrintPreview** = true.

Source code have a validation for it

<pre>
if (processInfo.isPrintPreview()) {
	log.info("ReportStarter.startProcess run report -" + jasperPrint.getName());
	JRViewerProvider viewerLauncher = getReportViewerProvider();
	//viewerLauncher.openViewer(jasperPrint, pi.getTitle()+" - " + reportPath);
	viewerLauncher.openViewer(jasperPrint, pi.getTitle() + "_" + pi.getRecord_ID() + ".pdf");
}
</pre>

**Comment by yamelsenih** [comment]
Please confirm it for close

**Comment by iscapnet** [comment]
Hi @yamelsenih , I just tested this fix and it works perfect. Thank You!

![screen-1](https://user-images.githubusercontent.com/10192498/34186552-b5749ff6-e4e9-11e7-94f6-3d9ab2be83a1.jpg)

**Comment by jdaison** [comment]
Hi @yamelsenih , it works ok! 

thanks a lot!
