### ISSUE TITLE
Add new function for date helper

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#1381]
Now exists two functions for handle dates in PostgreSQL and Oracle, they are:

- add_months(timestamp with time zone, numeric);
- adddays(timestamp with time zone, numeric);

I propose add two more functions for add week and years:

- addweeks(timestamp with time zone, numeric);
- addyears(timestamp with time zone, numeric);

It is usefull for handle dates in DB

**Comment by e-Evolution** [comment]
No exist add_months implementation for Oracle as in PostgreSQL

<img width="498" alt="image" src="https://user-images.githubusercontent.com/786968/48920135-c4be2e00-ee5c-11e8-9e7d-b4c433735f76.png">

<img width="1749" alt="image" src="https://user-images.githubusercontent.com/786968/48920141-d0a9f000-ee5c-11e8-8ae1-db2a7a0cab4d.png">

**Comment by yamelsenih** [comment]
Hi @e-Evolution for Oracle is unnecessary this function, already exists, see: https://docs.oracle.com/cd/B19306_01/server.102/b14200/functions004.htm
