### ISSUE TITLE
Factoring

### ISSUE THREAD

**Issue by SusanneCalderon** [adempiere/adempiere#1382]
Model the entire process of factoring in Adempiere. 

Factoring is a credit of a bank or a factoring house to the company hedged by open sales invoices. 
It is a common practise to enhance liquidity.

These sales invoices can be sold or loaned to the factoring house. 
A factoring contract induces costs as commission and interests which are modeled as purchase invoices. 

The payment of a factoring contract by the factoring house is the contract amount - commission - interest -withholding.

The purchase invoices for costs do not induce payments but are subtracted from the entitled payment amount, as described before.

When the contract is reimbursed on time to the factoring house the withholded amount must be paid to the company.

Images:
Workflow 
![factoring](https://user-images.githubusercontent.com/15349639/31675633-77d30c76-b322-11e7-8aa4-0dfabf067c5d.png)
Accounting concept
![factoringaccounting](https://user-images.githubusercontent.com/15349639/31675658-8b8a966c-b322-11e7-829b-edcc8bada7dc.png)

**Comment by yamelsenih** [comment]
Hi @SusanneCalderon have you a pull request for it?
