### ISSUE TITLE
Disable window resizing

### ISSUE THREAD

**Issue by ishanuda** [adempiere/adempiere#139]
I have seen that some of the windows are re sizable where it can be set as fixed disabling the re sizing capability. 
For an example Menu -> System Admin -> General Rules -> Java Version
This kind of window can stay fixed. 

Seems like most of the process windows, can stay as fixed window.

Even when re size it gives an ugly look and feel.

For an example Menu -> System Admin -> General Rules -> Sequence Check 
When re size the buttons overlap the text and feels not good.

**Comment by yamelsenih** [comment]
Hi @ishanuda i test it but i don't see the bug..
You can put a picture?
Thank you.

**Comment by ishanuda** [comment]
Hi @yamelsenih thank you very much for your reply,
I have attached two screen shots here one for java version and other one for Sequence Check.

Can you see that in the java version dialog can be fixed stopping re-sizing process.
Also Sequence Check you can see the buttons overlap with the text.

I have attached the login window to know about the system info for your reference.



![java-version](https://cloud.githubusercontent.com/assets/8893919/14611859/f0956d86-05b1-11e6-9467-3fe40b53da87.jpg)
![sequence-check](https://cloud.githubusercontent.com/assets/8893919/14611860/f0c27768-05b1-11e6-8a6e-bb6d1d02b2e7.jpg)
![adempiere-login](https://cloud.githubusercontent.com/assets/8893919/14611982/8aa82756-05b2-11e6-8235-cb8f54581770.jpg)


Kind request.
Dear @yamelsenih I am customizing and developing the ADempiere for my own subscription management system, and I need some information regarding customization in order to complete my requirement. 

If you can kindly help me to contact you with your personnel e-mail address to get some information it would be a great help and I would be very careful not disturbing you taking your valuable time.

My contact e-mail - ishanuda@gmail.com

thank you very much
Ishanuda

**Comment by ishanuda** [comment]
Hi @yamelsenih thank you very much for your reply,
I have attached two screen shots here one for java version and other one for Sequence Check.

Can you see that in the java version dialog can be fixed stopping re-sizing process.
Also Sequence Check you can see the buttons overlap with the text.

I have attached the login window to know about the system info for your reference.



![java-version](https://cloud.githubusercontent.com/assets/8893919/14611859/f0956d86-05b1-11e6-9467-3fe40b53da87.jpg)
![sequence-check](https://cloud.githubusercontent.com/assets/8893919/14611860/f0c27768-05b1-11e6-8a6e-bb6d1d02b2e7.jpg)
![adempiere-login](https://cloud.githubusercontent.com/assets/8893919/14611982/8aa82756-05b2-11e6-8235-cb8f54581770.jpg)


Kind request.
Dear @yamelsenih I am customizing and developing the ADempiere for my own subscription management system, and I need some information regarding customization in order to complete my requirement. 

If you can kindly help me to contact you with your personnel e-mail address to get some information it would be a great help and I would be very careful not disturbing you taking your valuable time.

My contact e-mail - ishanuda@gmail.com

thank you very much
Ishanuda

**Comment by yamelsenih** [comment]
Hi @ishanuda i working with Linux Debian, but i can test it with a window station.

I wil test it and tell you the result.

**Comment by yamelsenih** [comment]
No test case for SO
