### ISSUE TITLE
Add new parameters to Storage Detail

### ISSUE THREAD

**Issue by beruskajimenez** [adempiere/adempiere#1397]
The following parameters must be added to generate the storage detail report:
**1. - Product Class
2. - Product Brand
3. - Product Group**

![detalle de almacenamiento](https://user-images.githubusercontent.com/32911885/31790379-8a13de20-b515-11e7-9253-a0ab24f0a9f3.png)

**Comment by yamelsenih** [comment]
@Raul-mz please review it

**Comment by yamelsenih** [comment]
A simple result:
![Screenshot_20190823_004120](https://user-images.githubusercontent.com/2333092/63567257-c5483a00-c53e-11e9-9813-bfb811b5167a.png)
