### ISSUE TITLE
Dynamic report export

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#1400]
Currently just exist some file export from report (See pic)
![screenshot_20171019_195559](https://user-images.githubusercontent.com/2333092/31799467-3939eb6e-b508-11e7-9928-b4538736abf0.png)
My proposal is add a abstract class for handle standard export and it can be extended for add more format to default list.

It allows create more custom formats for export from report view.

**Comment by yamelsenih** [comment]
For use and documentation you can see: [http://wiki.adempiere.net/Spin_Contribution:_FR:_Export_Format_From_Report](http://wiki.adempiere.net/Spin_Contribution:_FR:_Export_Format_From_Report)

Best Regard

**Comment by e-Evolution** [comment]
This commit break the back compatibility not exit the method 

public boolean createXML (File file)

public boolean createXML (Writer writer)

a new functionality not should break the back compatibility 

Please fix or revert.

**Comment by yamelsenih** [comment]
Hi Victor, I can add this method, but I was assured that all core functionality is the same. No problem I will add to it

**Comment by e-Evolution** [comment]
yes , not should be remove , you can implement new implement but not should remove.

I saw other methods was removed 

public boolean createDelimitedFile (Writer writer, char delimiter, Language language, boolean printHeader)

private void createCSVvalue (StringBuffer sb, char delimiter, String content)

**Comment by yamelsenih** [comment]
You can try use the new custom format, is more easy

**Comment by yamelsenih** [comment]
**private void createCSVvalue (StringBuffer sb, char delimiter, String content)** a private method is not used for other, it should not add for back compatibility.

**Comment by e-Evolution** [comment]
This change continue break the back compatibility.

the original method was with 2 parameters , some customization launch this error org.compiere.print.ReportEngine.createXLSX(Ljava/io/File;Lorg/compiere/util/Language;)V

Again a new functionality not should change public methods 


/**
	 * Create Excel file
	 * @param outFile output file
	 * @param language
	 * @throws Exception if error
	 */
	public void createXLS(File outFile, Language language)
	throws Exception
	{
		PrintDataExcelExporter exp = new PrintDataExcelExporter(getPrintData(), getPrintFormat());
		exp.export(outFile, language);
	}
	
	public void createXLSX(File outFile, Language language)
	throws Exception
	{
		PrintDataExcelExporter exp = new PrintDataExcelExporter(getPrintData(), getPrintFormat(), true);
		exp.export(outFile, language);
	}

**Comment by yamelsenih** [comment]
Hi @e-Evolution please test it for close

**Comment by yamelsenih** [comment]
When exists two formats with the same extension always is selected first instead real user choice

**Comment by e-Evolution** [comment]
@yamelsenih would you fix the  issue , this change damaged the export Print format Definition.

In commit 23e90f2fd9f5af6d25a8a0fb6c4a74d73f77022b

this code was removed 

//	BR [1019]
			if (m_IsCanLoad) {
				cboType.appendItem("arxml" + " - " + Msg.getMsg(Env.getCtx(), "Adempiere Report Definition"), "arxml");
			}

**Comment by yamelsenih** [comment]
Hi @e-Evolution it already exist here:
https://github.com/adempiere/adempiere/blob/develop/client/src/org/compiere/print/Viewer.java#L1151

**Comment by yamelsenih** [comment]
Hi @e-Evolution please test it. Best regards
