### ISSUE TITLE
Add feature for IsKey property SB

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#1401]
When a Smart Browse is based in a view without primary key and is required a column as Key, is nice to have a way for generate row num automatically.
For now exist a way making a SQL column for SB with a 'Row' AS "Row".

My proposal is that a column distinct of ID or numeric can be a Key column:
DocumentNo, IsActive, any column that is not a numeric or ID

**Comment by e-Evolution** [comment]
This change continue break the back compatibility.

the original method was with 2 parameters , some customization launch this error org.compiere.print.ReportEngine.createXLSX(Ljava/io/File;Lorg/compiere/util/Language;)V

Again a new functionality not should change public methods 


/**
	 * Create Excel file
	 * @param outFile output file
	 * @param language
	 * @throws Exception if error
	 */
	public void createXLS(File outFile, Language language)
	throws Exception
	{
		PrintDataExcelExporter exp = new PrintDataExcelExporter(getPrintData(), getPrintFormat());
		exp.export(outFile, language);
	}
	
	public void createXLSX(File outFile, Language language)
	throws Exception
	{
		PrintDataExcelExporter exp = new PrintDataExcelExporter(getPrintData(), getPrintFormat(), true);
		exp.export(outFile, language);
	}

**Comment by yamelsenih** [comment]
Hi @e-Evolution have some problem it?
