### ISSUE TITLE
Add print formats to transaction detail

### ISSUE THREAD

**Issue by beruskajimenez** [adempiere/adempiere#1405]
The following print formats must be added in the transaction detail report:

**1. Detail of transactions by Warehouse
2. Detail of transactions by Warehouse and Location
3. Detail of transactions by Product Category.
4. Detail of transactions per Document.**

![image](https://user-images.githubusercontent.com/32911885/31837047-9c5e440e-b5d7-11e7-9910-553a77eabd5c.png)

**Comment by yamelsenih** [comment]
@Raul-mz please review it

**Comment by yamelsenih** [comment]
It can be defined by client
