### ISSUE TITLE
Add parameters to generate open items report

### ISSUE THREAD

**Issue by beruskajimenez** [adempiere/adempiere#1409]
Add the following parameters in the Open Items report:

**1. Broker
2. Sales Region**

![image](https://user-images.githubusercontent.com/32911885/31840225-a0995bd2-b5e4-11e7-971b-c0d19f6104b9.png)

**Comment by e-Evolution** [comment]
@beruskajimenez I think that is necessary adding too:

- Campaign
- Channel 
- Payment Term
- Project

kind regards

**Comment by yamelsenih** [comment]
Hi @beruskajimenez please test it for close.

See the pic: 
![screenshot_20171030_001828](https://user-images.githubusercontent.com/2333092/32155189-3589cabe-bd0c-11e7-9c13-13bf8cde6bc8.png)

**Comment by beruskajimenez** [comment]
Hi @e-Evolution  the requested parameters were added to the open items report

See the pic:
![estado de cuenta por documento1](https://user-images.githubusercontent.com/32911885/32188714-f4b6fbd8-bd7e-11e7-8de8-c2b9beb9d25d.png)

**Comment by yamelsenih** [comment]
The current report us broken, it is because Document Type parameter was not in result set  or view
