### ISSUE TITLE
The Column Report Source not is validate if not is defined as a segment value and a element type

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#1410]
The Column Report Source should be validate in any case 

Problem introducing in 682dbf2ba876cdfd7e82b0ad6ae242bbf85654eb

**Comment by adaxa-steven** [comment]
please describe use case and a test system url where it can be seen.

**Comment by e-Evolution** [comment]
Hi Steven , the problem is that I need define a column where only should get values if Report Source for column is for account and Asset.

The column type is defined as Relative Period , then the current code not valid the report source because an element type should defined , it not is rightly so that the financial report should validate report source independent the column type.

kind regards
Victor
