### ISSUE TITLE
Payment Allocation form not invoked from button on Payment window?

### ISSUE THREAD

**Issue by adaxa-steven** [adempiere/adempiere#1411]
Hi
We added a button the Payment window which was displayed when a payment was created, not put to a Charge and not allocated by selecting an invoice.  The Payment Allocation form would be displayed with the BP selected and the Payment shown as selected so the user could just select the matching invoices.

It was my understanding that this would be added to 3.90 but I can find no trace of it.  Have I missed something.  Was the change rejected?

from adaxa.testadempiere.com....
![image](https://user-images.githubusercontent.com/15791084/31845702-72aad0aa-b64f-11e7-9556-42352a15619c.png)

and
![image](https://user-images.githubusercontent.com/15791084/31845709-8a4e79f0-b64f-11e7-8a95-8e96941e3bd8.png)

**Comment by adaxa-steven** [comment]
Hi Victor, I assigned to you rather than leave blank. Pls assign back to me if you dont know about this.

**Comment by yamelsenih** [comment]
Hi @adaxa-steven it is missing in latest version. I would add to ADempiere but i think will use Process button from toolbar instead a new column DB and button.

Best regard.

**Comment by yamelsenih** [comment]
Hi @adaxa-steven i was added it to 3.9.1, see: 
![screenshot_20171111_024949](https://user-images.githubusercontent.com/2333092/32690976-a58a326c-c6d6-11e7-9946-6ac3e22ddc08.png)
![screenshot_20171111_025008](https://user-images.githubusercontent.com/2333092/32690977-a60ea0b0-c6d6-11e7-9627-e9f3e6dc1129.png)
![screenshot_20171111_025029](https://user-images.githubusercontent.com/2333092/32690978-a6636cb2-c6d6-11e7-8a38-5fbfd903cb97.png)
![screenshot_20171111_025043](https://user-images.githubusercontent.com/2333092/32690979-a6ba2e1c-c6d6-11e7-84ea-8728a8b7e875.png)

**Comment by adaxa-steven** [comment]
Much harder to see and use when not a button.
