### ISSUE TITLE
Barcode Scanner Products Not is Functionality whit Attribute Set Instance!!!

### ISSUE THREAD

**Issue by erprafaelrodriguez** [adempiere/adempiere#1415]
Hi Team! 

Testing the new improvement of Barcode Scanner Products in the Window Material Movement I consider not is functional because in the Class org.eevolution.form.VScanBarUI the field LOT is mandatory since the product is hability with M_AttributeSetInstance, but in the window AttributeSetExclude have Exclude the table MovementLine!

<img width="1677" alt="captura de pantalla 2017-10-24 a la s 10 30 28" src="https://user-images.githubusercontent.com/20327157/31955124-111483c6-b8ad-11e7-9276-b2c6496cbe97.png">

<img width="1380" alt="captura de pantalla 2017-10-24 a la s 10 40 23" src="https://user-images.githubusercontent.com/20327157/31955141-21272f52-b8ad-11e7-9b72-22580b206abc.png">

That is to say, if in your M_Atributte functionality you can exclude these movements; M_MovemenLine, M_InventoryLine, C_OrderLine, that in the Barcode has the logic like M_AttributeSetExclude!

Some Comments? 

Regards!!!

**Comment by SusanneCalderon** [comment]
@e-Evolution , I cannot find the class org.eevolution.form.VScanBarUI

**Comment by SusanneCalderon** [comment]
adempiere #1236, I am in branch adempiere develop

**Comment by SusanneCalderon** [comment]
@e-Evolution Hi Victor, to avoid the error message classnotfound when you use the button "Barcode Scan" in swing I suggest an empty class VScanBarUI which only shows the message that this funcionality is available in zk.

**Comment by e-Evolution** [comment]
@SusanneCalderon I implement other approach allow defines if UI component is enable only for WebUI.
