### ISSUE TITLE
Null Pointer Exception at Adempiere start

### ISSUE THREAD

**Issue by mbar49** [adempiere/adempiere#1426]
I imported the products, then deleted the i_product table with the Delete Import function.
At Adempiere restart before menu window I got:

09:54:55.167 DB.isDatabaseOK: DB_Version=2017-08-01 [1]
09:54:55.579 MRole.get: AD_Role_ID=102, AD_User_ID=100, reload=false [1]
09:54:55.850 WFPanel.<init>: RW=false [1]
09:54:59.074 Env.getImageIcon2: GIF/PNG Not found: ShowAllWindow16 [1]
09:54:59.075 Env.getImageIcon2: GIF/PNG Not found: ShowAllWindow24 [1]
09:54:59.180 MTree.<init>: AD_Tree_ID=10, AD_User_ID=100, Editable=false, OnClient=true [1]
-----------> X_I_Product.load: NO Data found for I_Product_ID=1001787 [1]
ADempiere starting: org.compiere.apps.AMenu - java.lang.NullPointerException
java.lang.NullPointerException
	at org.compiere.model.MRecentItem.lambda$getLabel$0(MRecentItem.java:410)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:352)_

**Comment by yamelsenih** [comment]
Hi @mbar49 is possible that the reference to products was deleted and recent item have a broker link, I will fix it.

Thanks you for report it.

**Comment by yamelsenih** [comment]
Hi @mbar49 it was solved yet, i test it easy:

1. Open ADempiere.
2. Create a new Payment Term by example (It generate a ID 1000000).
3. After it i run it query: <pre>DELETE FROM C_PaymentTerm WHERE C_PaymentTerm_ID=1000000;</pre>
4. I Open newsly ADempiere and it throw a NPE.
