### ISSUE TITLE
Migration yields an NPE after catching an Exception

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere#143]
When a migration is applied by executing MMigration.apply() and there the call of stepApply(step) for whatever reason causes an exception, the exception is caught and the method MMigration.apply()  is abandoned. So far so good.

The caller is MigrationApply.run(), which immediately tests the status of the migration object. In the scenario as described, the migration object is null, which leads to an NPE.

The NPE can be avoided by adding to MMigration.apply() a "finally" clause where the migration status is always set:
public void apply() {

```
    try{
        for ( MMigrationStep step : getSteps(false) )
        {
            if (!step.isActive())
                continue;

            if (MMigrationStep.STATUSCODE_Applied.equals(step.getStatusCode())) {
                log.log(Level.CONFIG, step.toString() + " ---> Migration Step already applied - skipping.");
                continue;
            }

            stepApply(step);
        } 
    }
    catch (Exception e)
    {
        if (isFailOnError)    // abort on first error
            throw new AdempiereException(e);

    }
    finally
    {           
        updateStatus();
    }
}
```

This way, a status is always set according to the results of the steps.

Also, in the actual implementation, an NPE would be fired if the status of all steps are applied.

**Comment by yamelsenih** [comment]
This was resolved yet for: #1789 , #1635, #674
