### ISSUE TITLE
Add new Parameters for Invoice Inquiry

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#1432]
The follow reports don't have many options for launch:
- Invoice Transactions (Acct)
- Invoice Transactions (Doc)
- Invoice Detail & Margin
- Daily Invoice
- Weekly Invoice
- Weekly Invoice Prod Cat
- Monthly Invoice
- Monthly Invoice Prod Cat
- Monthly Invoice Vendor
- Monthly Invoice Product
- Quarterly Invoice Customer by Vendor
- Quarterly Invoice Customer by Product
- Quarter Invoice Product

![screenshot_20171030_005655](https://user-images.githubusercontent.com/2333092/32155454-c9cffd3c-bd0d-11e7-8510-293650f98db3.png)
![screenshot_20171030_005712](https://user-images.githubusercontent.com/2333092/32155455-ca041446-bd0d-11e7-82e5-ab50d0171f6b.png)
![screenshot_20171030_005728](https://user-images.githubusercontent.com/2333092/32155457-ca3bbfe0-bd0d-11e7-8467-3ca47d6fa266.png)
![screenshot_20171030_005745](https://user-images.githubusercontent.com/2333092/32155458-ca74ad32-bd0d-11e7-8058-eef2d010b7f4.png)
![screenshot_20171030_001828](https://user-images.githubusercontent.com/2333092/32155459-caa79d32-bd0d-11e7-961f-d10889fcb27b.png)
![screenshot_20171030_005319](https://user-images.githubusercontent.com/2333092/32155443-c7e09798-bd0d-11e7-8d00-45f38ebb352d.png)
![screenshot_20171030_005336](https://user-images.githubusercontent.com/2333092/32155444-c8040d9a-bd0d-11e7-882c-fc486830b50f.png)
![screenshot_20171030_005357](https://user-images.githubusercontent.com/2333092/32155445-c8269bd0-bd0d-11e7-8f5e-681a5a88058e.png)
![screenshot_20171030_005419](https://user-images.githubusercontent.com/2333092/32155446-c849e9aa-bd0d-11e7-8739-ed7dd7726bc6.png)
![screenshot_20171030_005446](https://user-images.githubusercontent.com/2333092/32155448-c86e30da-bd0d-11e7-95a0-d111609582a7.png)
![screenshot_20171030_005508-1](https://user-images.githubusercontent.com/2333092/32155449-c8927f3a-bd0d-11e7-81e1-78a8e6a257af.png)
![screenshot_20171030_005508](https://user-images.githubusercontent.com/2333092/32155450-c903a480-bd0d-11e7-82de-ceb40d375048.png)
![screenshot_20171030_005535](https://user-images.githubusercontent.com/2333092/32155451-c933d286-bd0d-11e7-8914-959c1b6ead2d.png)
![screenshot_20171030_005623](https://user-images.githubusercontent.com/2333092/32155452-c963b5a0-bd0d-11e7-8f6a-149d744823a2.png)
![screenshot_20171030_005639](https://user-images.githubusercontent.com/2333092/32155453-c99bf906-bd0d-11e7-89a0-59ed4fc8bf54.png)

**Comment by yamelsenih** [comment]
Hi @beruskajimenez, you can test it also.

Best regard

**Comment by e-Evolution** [comment]
@yamelsenih now that adding new parameter for product into invoiced , will good adding new product taxonomic fields product class , product group , product classification.

kind regards
Victor

**Comment by yamelsenih** [comment]
Hi Victor, it was done yet, test it.

Now each report allow filter by category, class, group, products, bp, bp group, is sales trx, and other parameters

It change was nice

**Comment by yamelsenih** [comment]
Some images:
![screenshot_20171030_161146](https://user-images.githubusercontent.com/2333092/32193277-2bedcdd0-bd8d-11e7-9792-0454b2dadc4f.png)
![screenshot_20171030_161215](https://user-images.githubusercontent.com/2333092/32193278-2c10fc88-bd8d-11e7-98ae-7afd8bcd05fd.png)
![screenshot_20171030_161042](https://user-images.githubusercontent.com/2333092/32193280-2c2d8038-bd8d-11e7-83f3-5bd9486213e3.png)
![screenshot_20171030_161129](https://user-images.githubusercontent.com/2333092/32193281-2c4dfffc-bd8d-11e7-863b-3046e208a8c6.png)
