### ISSUE TITLE
Document isCopyDocNoOnReversal 2, in order to mark a reversal document with ^ this should be a message 

### ISSUE THREAD

**Issue by SusanneCalderon** [adempiere/adempiere#1438]
```
if(docType.isCopyDocNoOnReversal()) {
				to.setDocumentNo(from.getDocumentNo() + Msg.getMsg(from.getCtx(), "Cancelled"));
```
instead of 
```

if(docType.isCopyDocNoOnReversal()) {
				to.setDocumentNo(from.getDocumentNo() + "^";
```

**Comment by yamelsenih** [comment]
Hi @SusanneCalderon i think that the message can be configured in Document Type instead source code

**Comment by yamelsenih** [comment]
Also can be some like:
<pre>
if(docType.isCopyDocNoOnReversal()) {
				to.setDocumentNo(from.getDocumentNo() + Msg.getMsg(from.getCtx(), "^"));
</pre>

**Comment by e-Evolution** [comment]
@SusanneCalderon @yamelsenih 

I think that is best only use the same document no and adding the internal id, this work good to my users.

Example for Invoice: 

Original:
Document No : 1000441

After of Reverse 

Document No : 1000441+1000020  Original
Document No : 1000441-1000021  Reverse

This way in any report sort by document no got the original and rever together.

What do you think?
Victor

**Comment by SusanneCalderon** [comment]
I cannot explain to the accountants of the ministry this.

**Comment by e-Evolution** [comment]
@SusanneCalderon then si more simple

you can explain + is original and - reverse

Document No : 1000441+ Original
Document No : 1000441- Reverse

I think that this can understand.

**Comment by yamelsenih** [comment]
Hi, the default is with **^**, it will be change by a message.

 I think that is nice to have it:
<pre>
Document No : 1000441+ Original
Document No : 1000441- Reverse
</pre>

And is better if it is configured as a flag in document type like is **IsCopyDocNoOnReversal**, maybe **IsAddedDocNoOnReversal**
