### ISSUE TITLE
Add parameters Order Detail Report

### ISSUE THREAD

**Issue by beruskajimenez** [adempiere/adempiere#1442]
**1. Add a check in the report to identify if it is a sales transaction.**
**2. Add a new parameter to filter by commercial agent**

![detalle de orden](https://user-images.githubusercontent.com/32911885/32277692-a5ce23e0-bee9-11e7-8af3-9d34ec7e0a84.png)

**Comment by yamelsenih** [comment]
Also is nice to add follow parameters:
- Document Status
- Product Category
- Product Class
- Product Classification
- Product Group
- Document Type Target
- Business Partner Group
- Date Promised
- Charge
- Charge Type

**Comment by yamelsenih** [comment]
This is a example for result:
![Screenshot_20190822_215323](https://user-images.githubusercontent.com/2333092/63561257-4693d280-c527-11e9-81cd-a04fa1e7bcd1.png)
