### ISSUE TITLE
Add a Browser User allows selector for user list

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#1447]
New Smart Browser User allows processing user selector and updated massive data

**Comment by e-Evolution** [comment]
![captura de pantalla 2017-11-02 a la s 19 34 46](https://user-images.githubusercontent.com/786968/32358212-b918bd04-c009-11e7-959d-13e2d5eee833.png)

**Comment by yamelsenih** [comment]
Is nice it feature Victor +1
