### ISSUE TITLE
Allow create an instance from extend original core class or tables with character prefix that not have entity Dictionary

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#1448]
Allow create an instance from extend original core class or tables with character prefix that not have entity Dictionary

Currently the system solve C_ProjectMember as MCProjectMember vs MProjectMember , the reason is we use org.eevolution.model package vs org.compiere.model

**Comment by yamelsenih** [comment]
Hi @e-Evolution what is your proposal?
Example:
I have a table named **AM_Meter** with a package **org.eam.model**, it can be created in source code like **org.eam.model.MAMMeter**.
Your proposal is change it for **org.eam.model.MMeter**?
