### ISSUE TITLE
Modal dialog set busy the main window

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#145]
When a search dialog, change log dialog and other dialog is opened in ADempiere, the main screen is set to busy, it action just must make busy the parent frame

**Comment by e-Evolution** [comment]
Hi Yamel!

I review this changes, but found that if you want view multiples info window , for example you open invoice info and next want open info Business Partner not is posible.

In process is very useful you can open multiples info window to view multiple information.

kind regards

**Comment by yamelsenih** [comment]
Hi Victor, the change is done, thank you for the observation.

best regards.
