### ISSUE TITLE
Add additional condition to an Standard Request 

### ISSUE THREAD

**Issue by sbouissa** [adempiere/adempiere#1451]
To solve this necessity, we think in adding a new column in R_RequestStandardType table where we can code differents conditions:

-Condition for the object (PO) that is consider to create the requests (an AND condition to de select of the table object) ---> When the condition start whit "SQL=" 
Example : SQL= M_Product_ID IN (Select p.M_Product_ID from M_Product p where p.M_Product_Group_Id = XXXX) 

-Condition in where we can get values of the object that is being condider to create or not the requests. ---> When the condition start with @SQL=
Example:
@SQL= SELECT a.M_Product_ID FROM M_Product a 
JOIN M_Product_Category b ON a.M_Product_Category_ID = b.M_Product_Category_ID 
WHERE  a.AD_Client_ID = @AD_Client_ID@ AND b.M_Product_Category_ID = 105 AND a.M_Product_ID = @M_Product_ID@ AND a.name IS NOT NULL

-Condition for data of the objet that is beeing consider --> When isn't an @sql or sql
Example: AD_Org_ID = XXXX & AD_Client_ID = XXXX

**Comment by sbouissa** [comment]
![issue1451](https://user-images.githubusercontent.com/4325868/32395051-49cb8462-c0be-11e7-8c0e-c9dd223c648c.png)

**Comment by sbouissa** [comment]
I will add the column "WhereClause" on the table R_RequestStandardType if all of you are agree. If some think another element fit bether please tell me. 
Thankyou

**Comment by e-Evolution** [comment]
Related #1330

**Comment by e-Evolution** [comment]
@sbouissa 

Need review of implementation of where clause , this should work of same way that Alert Rule or Report View, you can use any context variable using @@ so not is necessary to use @SQL=
