### ISSUE TITLE
Add Sales Region to Order and Invoice

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#1455]
Now exist a Sales Region definition for SO management, it is defined on Sales Region window.

For now the sales region is getted from BP contact but sometimes exist a Sales Region Re-Definition, it cause that all history of sales from a Sales Region can be changed.

My proposal is rounded the Sales Region in Sales Order and Invoice, it allow that a change in BP Location don't change sales history.
![screenshot_20171105_232211](https://user-images.githubusercontent.com/2333092/32424096-b9f4e814-c280-11e7-825b-e1de7e62f36d.png)

**Comment by e-Evolution** [comment]
@yamelsenih adding the sales region and sales order is only to have history sales region? , because currently account engine fill this account dimension using the location.

**Comment by yamelsenih** [comment]
Hi @e-Evolution yes, this is only for keep a sales history from invoice document, the current problem is that  if you change sales region on BP Location the sales history is changed
