### ISSUE TITLE
Zoom from Smart Browse just show first record

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#1458]
When a Smart Browse is launched, and it have more than one record if **zoom** button is pressed, the records showed is only one, it is because query restriction only add first record.

**Comment by yamelsenih** [comment]
Ti is fixed in #1457

**Comment by ayazbaloch** [comment]
Dear @yamelsenih could it incorporate, https://github.com/adempiere/adempiere/issues/1354
