### ISSUE TITLE
Add Cash Detail

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#1460]
Is nice to have a report for cash detail, it can be like **Payment Detail** Report.
It allows separe Financial Account information of Financial Cash information

**Comment by e-Evolution** [comment]
@yamelsenih can please add an example this report

**Comment by yamelsenih** [comment]
Is a report like Payment detail but only show information of cash movement or account flagged as cash

**Comment by yamelsenih** [comment]
The financial manager have complex control over financial accounts but is possible that a cash manager want to see balance and other confidential information about bank accounts, then is very important don't show information of bank account for cash manager (It only can see Cash transaction). 
![screenshot_20171112_224647](https://user-images.githubusercontent.com/2333092/32707605-78822704-c7fb-11e7-9bd9-83093b7cc019.png)
![screenshot_20171112_224718](https://user-images.githubusercontent.com/2333092/32707606-78a3817e-c7fb-11e7-9b0d-1c15506cdda5.png)
