### ISSUE TITLE
delete folder of favorites

### ISSUE THREAD

**Issue by wdtz** [adempiere/adempiere#1466]
When entering a folder in user favorites there is no way to delete it, there must be a way to delete it.
![mov1](https://user-images.githubusercontent.com/9578152/32560336-47f1f388-c4a1-11e7-9514-87702ab2d838.png)

**Comment by adaxa-steven** [comment]
![image](https://user-images.githubusercontent.com/15791084/32576130-173cc8ce-c52a-11e7-9d92-f78245e87f33.png)

right-click then delete
![image](https://user-images.githubusercontent.com/15791084/32576165-3acf1ae4-c52a-11e7-964a-95a165f06430.png)

![image](https://user-images.githubusercontent.com/15791084/32576195-4bbed4b6-c52a-11e7-81c6-015a942c3b90.png)

deleted without error.

**Comment by yamelsenih** [comment]
Hi Steven is nice if the dashboard could have a Delete button like is in favourite dashboard instead a pop-up menu

**Comment by adaxa-steven** [comment]
I agree .. but it is not the way we wrote it :-(
