### ISSUE TITLE
NPE editing the name of a folder in favorites

### ISSUE THREAD

**Issue by wdtz** [adempiere/adempiere#1467]
when trying to modify the name of a folder created in favorites and selecting the option "undo" generates an npe.
Here are the instructions to emulate the error:
1. Select the folder you want to rename
![image](https://user-images.githubusercontent.com/9578152/32561324-f288c860-c4a3-11e7-8ca4-a1ac3b541287.png)
2. Make a change in the name
![image](https://user-images.githubusercontent.com/9578152/32561405-1752c330-c4a4-11e7-87b4-c9cac540fd4a.png)
![image](https://user-images.githubusercontent.com/9578152/32561455-2ede5082-c4a4-11e7-907f-e1064a2a5d77.png)

3. Select the "undo" option
![image](https://user-images.githubusercontent.com/9578152/32561487-43bf8d04-c4a4-11e7-974b-1ad11bfbd16b.png)

4. You will see the following error
![image](https://user-images.githubusercontent.com/9578152/32561535-57518336-c4a4-11e7-96b4-2193886cd9d9.png)

**Comment by adaxa-steven** [comment]
![image](https://user-images.githubusercontent.com/15791084/32575992-b27d6178-c529-11e7-85e6-9c486de0908b.png)

double-click and rename then save
![image](https://user-images.githubusercontent.com/15791084/32576031-d6bbebf4-c529-11e7-92b2-c28958c8624b.png)

did not throw an error.  
What could be different?
