### ISSUE TITLE
Add document type for Bank Statement 

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#1470]
All document that generate account entry should have Document Type

**Comment by yamelsenih** [comment]
Hi @e-Evolution please also you should add folow:
DocumentNo

You can mark C_BankStatement Table as IsDocument and missing column will be added

**Comment by yamelsenih** [comment]
Is nice add also a SQL for set default document type for back compatibility

**Comment by yamelsenih** [comment]
I test it and worked for me.
