### ISSUE TITLE
Smart Browser generate invoice from order lines

### ISSUE THREAD

**Issue by beruskajimenez** [adempiere/adempiere#1475]
When an invoice is generated from the Smart Browser Generate Invoice from order lines, it is generated without the lines, however, the grand total if it shows it in the header. It is required to be reviewed this process. Attached is an example.

**Invoice**

![seleccion_034](https://user-images.githubusercontent.com/32911885/32607362-1f850bea-c52f-11e7-98a8-4cf64ee06c96.png)

**Inoice Lines**

![seleccion_035](https://user-images.githubusercontent.com/32911885/32607405-44fc8272-c52f-11e7-95a6-49edaa953b73.png)

**Comment by syvasoft** [comment]
Hi,
There are two lines in Invoice Line tab. Please check second line.

**Comment by beruskajimenez** [comment]
Hello, indeed the lines are in the following record. Thank you.
