### ISSUE TITLE
Impossible export files to excel

### ISSUE THREAD

**Issue by jabo6311** [adempiere/adempiere#1476]
When you need to export any file to excel format, file is not recognized by excel.

![error exp excel](https://user-images.githubusercontent.com/33498993/32616418-b06343fc-c548-11e7-9509-f4ccbe17a7e6.png)

**Comment by yamelsenih** [comment]
Hi @jabo6311 have you a log error from ADempiere? What is the report to export?

**Comment by yamelsenih** [comment]
Hi @jabo6311 i was export it and could view it with LibreOffice.

**Comment by yamelsenih** [comment]
This is a user error
