### ISSUE TITLE
Exclude payments for dunning process

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#1493]
Current now when a dunnig is processed, it add payments/receipt to dunning lines automatically. 

I propose make a flag like **IsIncludePayments** for Include payments to dunning run

**Comment by adaxa-steven** [comment]
If you are making a change here can the SO number be shown on the unallocated payment if it exists.
The payment number allocated by adempiere is meaningless to the customer but the Sales Order number they can check.

**Comment by yamelsenih** [comment]
>If you are making a change here can the SO number be shown on the unallocated payment if it exists.
The payment number allocated by adempiere is meaningless to the customer but the Sales Order number they can check.

It can be added as a new column with reference
![screenshot_20171116_153227](https://user-images.githubusercontent.com/2333092/32911783-8f5bd192-cae3-11e7-84be-34ad11a79a75.png)
Also it can be populated from Invoice reference and payment reference if exists one
