### ISSUE TITLE
Costing Method Average Invoice; the method createCostAdjustment() does not update a new cost in the second transaction of a movementline

### ISSUE THREAD

**Issue by SusanneCalderon** [adempiere/adempiere#1496]
A movementline creates two transactions, the first with movementqty < 0, the second with movementqty > 0. The transactions create the corresponding costdetails, the second costdetail copies the amount from the first costdetail. So when the costdetail is new, the valuation of the first and second transaction is correct.

When a costadjustment is started, for example after inserting a new landed cost invoice, the amount of the second costdetail is not adjusted, so every transaction after the movement with positive movementqty is calculated with the odl value.
Solution:
In case of cost adjustment (costdetail != 0) the field amt should be updated.

Class AverageInvoiceCostingMethod, Line 235
```

if (model instanceof MMovementLine && costDetail!=null){
				costDetail.setAmt(amount);
			}
```

**Comment by e-Evolution** [comment]
@SusanneCalderon 

Have question , if you move a material from a warehouse to other warehouse the source cost should be averaging  with the cost the target warehouse and get a new average cost.

Do you are considering this behaving?

**Comment by yamelsenih** [comment]
Hi, this issue can be closed?
