### ISSUE TITLE
Defining two Standard Request Type associated to the same table, event model validator and different where clause, the requests defined in each one duplicates if the conditions are ok.

### ISSUE THREAD

**Issue by sbouissa** [adempiere/adempiere#1499]
We are trying to create differents requests when a c_projectline is created.
First: we defined a standard request type for the table c_projectline "after insert" (with 13 requests)
Second: we defined a standard request type for the table c_projectline "after insert" and the conddition that the product defined into the c_projectline have to be of 'Example' group.(with1 request)

We create 2 c_projectline (N.1) one with a product associated to the group "Example" and other (N.2) with the product associated to the group "NO"
At the end there are 28 (13+13+1+1) requests associated to the c_projectline (N.1) and 26 (13+13) requests associated to the c_projectline (N.2)

**Comment by SusanneCalderon** [comment]
I merged after some changes so I am cleaning my branch
