### ISSUE TITLE
Running the script "03440_1465_Commission_SQLFunctionLineNetAmt.xml" we had an error.

### ISSUE THREAD

**Issue by sbouissa** [adempiere/adempiere#1500]
The problem is the column "SeqNo" it is define as 3440_1465 and it must be 3440 to run it without problem.

**Comment by elmoyses** [comment]
While updating from 3.90 to 3.91 using ./RUN_MigrateXML.sh the script stops when trying to apply the following xml file:03440_1465_Commission_SQLFunctionLineNetAmt.xmlApplication failed. 

org.postgresql.util.PSQLException: Unterminated dollar quote started at position 195 in SQL -- Function: linenetamtrealorderline(numeric) -- DROP FUNCTION linenetamtrealorderline(numeric); CREATE OR REPLACE FUNCTION linenetamtrealorderline(p_c_orderline_id numeric) RETURNS numeric AS $BODY$ DECLARE v_amt numeric; BEGIN select case when pl.istaxincluded = 'Y' AND t.rate <> 0 then round(ol.linenetamt/(1+(t.rate/100)),cur.stdprecision) else linenetamt end as linenetamtreal into v_amt from c_Orderline ol inner join c_order o on ol.c_order_ID = o.c_order_ID inner join m_pricelist pl on o.m_pricelist_ID = pl.m_pricelist_ID inner join c_Tax t on ol.c_tax_ID = t.c_tax_ID inner join c_currency cur on o.c_currency_ID = cur.c_Currency_ID where ol.c_OrderLine_ID = p_c_orderline_id; RETURN coalesce(v_amt,0); END; . Expected terminating $$
--

**Comment by yamelsenih** [comment]
It was solved yet
