### ISSUE TITLE
Report Valuate Inventory effective date works only for costing level "Warehouse"

### ISSUE THREAD

**Issue by SusanneCalderon** [adempiere/adempiere#1502]
When the costing level _Client_ is selected, the values of beginningbalanceQty and beginningbalance in the table M_Costdetail are overall values(over all warehouses) and do not serve to calculate the qty/valuatedqty of a product at the chosen date for the report in a specific warehouse. 
In case of costing level _Client_ the column m_warehouse_ID only specifies the location of the corresponding transaction. For this costing level it is correct that  the beginninbbalanceQty/beginningbalance are  overall values, a new average cost is calculated on base of total quantities and total inventory value.

To get the correct qty and valuated stock for a warehouse at a specific date, the stock in the warehouse at this date must be calculated from the table m_transaction. This stock must be multiplied with currentcostprice + currentcostprice from the table m_costdetail, found in the lasted entry for the latest transaction before the selected date.

**Comment by yamelsenih** [comment]
Any news?
