### ISSUE TITLE
Accounting account field should show code and account name

### ISSUE THREAD

**Issue by nsarlabos** [adempiere/adempiere#1512]
Currently, when defining an accounting account, the code of the selected accounting combination is being displayed.

The idea is that when defining an accounting combination, take from the account not only the code, but also the name, so it becomes clearer when seen in the fields of accounting account definition.

Suggested solution:

1- Execute the following update:

update C_ValidCombination set combination = coalesce (a.value || '-' || a.name)
from C_ElementValue to
where a.C_ElementValue_ID = C_ValidCombination.Account_ID

2- Implement the MValidCombination class, and in the beforeSave method, set the "Combination" field as the previous point update does.

Attached screenshots are provided as an example.

![image](https://user-images.githubusercontent.com/29130825/33557809-087e9756-d8e7-11e7-92ca-eda83ddf9ea4.png)

![image](https://user-images.githubusercontent.com/29130825/33557823-125ae8c4-d8e7-11e7-991f-74379baf1cd7.png)

**Comment by e-Evolution** [comment]
This issue was solve, if you set the mouse under valid combination the system show the account name vs search value , then I think that not is necessary change the logic
