### ISSUE TITLE
Recurring Phase and Tasks for a Project

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#1531]
There are tasks that need to be repeated after a certain period of time or some recurrence.

So a solution is to repeat the same task for each week or month, but this way is not nice, so now is possible to define a task as recurrent and it will appear automatically.

Benefits of recurring tasks:

- Repetitive tasks are created automatically
- A notice will send to reminded to complete 

To define a task as recurrent activate undefined and frequency type

**Comment by sbouissa** [comment]
We think of a possible solution for this need:

In both tables (C_ProjectTask and  C_ProjectPhase) we could crete two field one to set "is recurrent" and other to set the "recurrence type"
(for example: month, week,year)

Then when RequestModelValidator is executed for Phase or Task we can ask if this is a recurring object, in this case we only consider the "StandardRequestType" asociated with c_phase or c_task (asociated repectively to the projectPhase, projectTask that is being considered) to start the creation of the requests recursively 

Another solution could be to create the fields in the C_Task and C_Phase directly and ask if the c_projectPhase or C_ProjectTask is asociated with a  c_phase or c_task recurrent
