### ISSUE TITLE
Unable to complete Manufacturing Order

### ISSUE THREAD

**Issue by ElPrience** [adempiere/adempiere#1533]
Hi All,

I'm having this problem with my Manufacturing Order. when  tries to complete the Manufacturing Order  it shows 'Terminated' at the window's status bar.

**Comment by e-Evolution** [comment]
What is the Log , reviewing the Log from doble click under ADempiere logo and see the log error.

Other hand , can you set the workflow  message to know the problem?

**Comment by ElPrience** [comment]
Dear e-Evolution,
thank u for  your interest 
it  was a problem in the  manufacturing resource
