### ISSUE TITLE
Deleting problem 

### ISSUE THREAD

**Issue by AHussein12** [adempiere/adempiere#1534]
i have a problem @
after pressing cancel 
it delete the  record !
![capture](https://user-images.githubusercontent.com/26410185/34375905-9750e21a-eaf1-11e7-8c72-027ed180eed5.PNG)

**Comment by ElPrience** [comment]
Dear @e-Evolution  
can you  help me  here ??

**Comment by ElPrience** [comment]
Dear @yamelsenih 
can you  help me  ??

**Comment by yamelsenih** [comment]
Hi @AHussein12 this issue was resolved for 3.9.0 version of ADempiere
