### ISSUE TITLE
Create Payroll Process Report Elements

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#1538]
For generate dynamic reports from payroll movements is necessary create some tables and windows for config, using the standard ADempiere configuration

**Comment by yamelsenih** [comment]
Here is a ER Diagram for proposal
![hr_reporting](https://user-images.githubusercontent.com/2333092/35013124-b5dedb00-fae2-11e7-9782-6d4b6151d656.png)

**Comment by yamelsenih** [comment]
Hey it will be like:
Menu
![screenshot_20180117_112427](https://user-images.githubusercontent.com/2333092/35050393-1accb280-fb79-11e7-85bb-0c5ae844e593.png)
Window
![screenshot_20180117_112447](https://user-images.githubusercontent.com/2333092/35050399-1e51c044-fb79-11e7-8071-3c8ff995da6b.png)

**Comment by dixon22ma** [comment]
Hi, @yamelsenih  when trying to compile, an error is generated by not finding the MHRConcept class located in the org.evolution.model package.
[Error](https://github.com/adempiere/adempiere/commit/0cc395d96ccec4fdad2da69e66e2f6d68d306edd#diff-36380e31fce55c25b926cdf15a4cd30dR22)
![imagen](https://user-images.githubusercontent.com/2453563/35307963-c00e2fba-007b-11e8-9d94-ec7982ff56bb.png)

This error is generated when executing the build.xml file located in the base source folder

**Comment by elmoyses** [comment]
This issue prevent from building the trunk.

**Comment by yamelsenih** [comment]
I am fixing it
