### ISSUE TITLE
Migration file with id of user

### ISSUE THREAD

**Issue by jdaison** [adempiere/adempiere#1543]
The file 00134_PaySelection_Like_Document.xml 

![imagen](https://user-images.githubusercontent.com/6097506/35240871-ce0b18c0-ff82-11e7-89eb-762cf6cc10af.png)

**Comment by yamelsenih** [comment]
Hi @jdaison i will fix it.

Thank you.

**Comment by yamelsenih** [comment]
Hi @jdaison it is solved yet

**Comment by jdaison** [comment]
Thanks!!
