### ISSUE TITLE
Add support to the checkbox "does not save when it's null" of the concept catalog window

### ISSUE THREAD

**Issue by RJPC** [adempiere/adempiere#1545]
Currently, when the concept is of the date type and the check box is checked, the concept is not saved in payroll movements even though the concept returns different from null.

![novedades2](https://user-images.githubusercontent.com/5696550/35295587-5e76e95e-0071-11e8-89ea-728d44d9567f.png)

![image](https://user-images.githubusercontent.com/5696550/35295643-87370ce8-0071-11e8-887a-942e16c3357d.png)

![image](https://user-images.githubusercontent.com/5696550/35295666-9896ffac-0071-11e8-8180-46f77267cfc4.png)

**Comment by RJPC** [comment]
Hi @yamelsenih bug resolved

**Comment by yamelsenih** [comment]
Thanks
