### ISSUE TITLE
Direct Cash Pay from Vendor Invoice with wrong sign when C_Payment

### ISSUE THREAD

**Issue by niclopup** [adempiere/adempiere#1547]
If the Cash Pay is with the C_Payment instead of the C_Cashline, the sign of the payment has to be Possitive because if not the payment would be with the opposite sign. It would add more Open Amount to the Invoice instead of decrease the open balance.

Now when you sleect Cash it add a Negative amount automatically.

Because of this i think that the "Paid" check neither is checked.

i add some screenshots to explain it better.
![captura de pantalla_2018-01-24_10-00-43](https://user-images.githubusercontent.com/31936815/35334115-f6a2aeba-00ef-11e8-910b-af1e0d735167.png)
![captura de pantalla_2018-01-24_10-13-20](https://user-images.githubusercontent.com/31936815/35334119-faff03be-00ef-11e8-96f5-e4d8788b7cda.png)
![captura de pantalla_2018-01-24_10-14-59](https://user-images.githubusercontent.com/31936815/35334121-fe1cad62-00ef-11e8-8735-eef74455c594.png)
![captura de pantalla_2018-01-24_10-19-53](https://user-images.githubusercontent.com/31936815/35334155-26d7cdfe-00f0-11e8-84e5-a3c186c4a85e.png)

**Comment by yamelsenih** [comment]
This was refactored, see related issues:
#2348 
#2347
#2418
