### ISSUE TITLE
MatchInv should have the same dateacct as the material receipt if tperiod is still open

### ISSUE THREAD

**Issue by SusanneCalderon** [adempiere/adempiere#1551]
Actually the datetrx and dateacct of the MMatchInv is not congruent:
1. First complete MInvoice, then complete MInout --> datetrx from MInout 
2. First  complete Minout, then complete MInvoice --> datetrx from MInvoice
3. Deleted MatchInvs are matched in the special Form _Match_ --> Date from Env
This leads to non-congruent movements in Product Asset

Suggestion:  Unify as follows, without consideration of  execution order:
1. Period of material receipt is open  --> datetrx from MInout 
2. Period of material receipt closed, but period of MInvoice open  --> datetrx from MInvoice
3. else datetrx is actual date

**Comment by SusanneCalderon** [comment]
The SysConfig variable  _MatchInv_Use_DateAcct_From_Receipt_ leaves the behaviour as before. 
Setting it to Yes changes to the behaviour described above.
So it is backward compatible.

**Comment by e-Evolution** [comment]
@SusanneCalderon 

Can change your migration script to implement the standard for System Config.

Currently any new parameter for configuration should use upper case so you need change MatchInv_Use_DateAcct_From_Receipt to MATCHINV_USE_DATEACCT_FROM_RECEIPT

here can see how other sysconfig was created.

![captura de pantalla 2018-01-30 a la s 22 58 09](https://user-images.githubusercontent.com/786968/35605839-23c14cd2-0611-11e8-95ca-b330c0cd46af.png)

On the other hand do you need remove the import org.compiere.model.*; and use the detail import as all rest code 

![captura de pantalla 2018-01-30 a la s 23 00 05](https://user-images.githubusercontent.com/786968/35605871-58f864ee-0611-11e8-8fc6-dd9067140d84.png)
