### ISSUE TITLE
Create method to add business days to a date

### ISSUE THREAD

**Issue by RJPC** [adempiere/adempiere#1559]
Currently exist the method TimeUtil.addDays which allows add continous days to a date specific, example:

TimeUtil.addDays('2018/01/01', 10) the result obtained es 2018/01/11

I propose create a method what allows add business days to a date specific, example:

TimeUtil.addBusinessDays('2018/01/01', 10, Calendar.SATURDAY, Calendar.SUNDAY) getting as a result 2018/01/15

**Comment by yamelsenih** [comment]
Hi, i add the follow method:

<pre>public static Timestamp addBusinessDays(Timestamp day, int offset, int... includeDay);</pre>

You can call it here (Add only business day from monday to friday):
<pre>TimeUtil.addBusinessDays(_From, 16, Calendar.MONDAY, Calendar.TUESDAY, Calendar.WEDNESDAY, Calendar.THURSDAY, Calendar.FRIDAY);</pre>
Also can cal it here:
<pre>TimeUtil.addBusinessDays(_From, 16);</pre>
