### ISSUE TITLE
Commission for complete payments: commissions from past months are calculated and displayed

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere#1560]
There is a commission configuration for paying commission only after the whole amount due has been paid.

Description of the error: as of now, if for example for the configuration "Calculate commission only after complete payment" the commission of January is calculated, it includes the commissions for last December and months before, which is obviously an error.

The reason: a condition must be added to include only invoices that have become fully paid within the period the commission is being processed. This is missing in the present version and has to be added to solve the bug.

**Comment by yamelsenih** [comment]
Hi @marcalwestf is very fine if it is solved

**Comment by marcalwestf** [comment]
@e-Evolution the changes in the file _03740_1560_Commission_from_past_months.xml_ addressed in the pull request https://github.com/adempiere/adempiere/pull/1631 are ok.
From my side, it is OK to accept these changes,

I do have a question: what is the exact usage of the branch _hotfix/3.9.0.a_ . What do the letter "a" stands for?
This would include the definition of branches named _hotfix/release[a-z]_.

BTW, the pull request https://github.com/adempiere/adempiere/pull/1597 is complementary to this one, because it concerns the ddutils definition.

**Comment by e-Evolution** [comment]
@marcalwestf Hi Mario.

My intention is create a hotfix branch only with patches for ADempiere previous version.

for instance support all patches included in 3.9.1 that patching 3.9.0, so the propouse is create patch packages for 3.9.0 [Long Term Support](https://en.wikipedia.org/wiki/Long-term_support) with where the suffix is a alphabet letter by pataches pack.

kind regards
