### ISSUE TITLE
Commission for complete payments: allow also for days due originated from invoices

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere#1562]
As of now, the days due for payment Commissions are taken only from the Payment Term.

There are situations where a company also wants to calculate commissions directly from the days specified in the Invoice.

Actually, the due days for payment Commissions were initially taken from Invoice and was changed to be calculated from Payment Term.

The changed suggested here is to include both possibilities: either take the due days from the invoice or from the payment term. This adds to more flexibility.

In order to implement it, a flag "isDaysDueFromPaymentTerm" would have to be added to the commission definition and it would apply for commissions defined as payment.

The code in MCommissionRun.processCommissionLine(), line 611 is as follows:
```
//	Days Due
if (commissionLine.get_ValueAsInt(MCommissionLine.COLUMNNAME_DaysFrom) != 0)
    sql.append(" AND paymenttermduedays(h.C_PaymentTerm_ID, h.DateInvoiced, p.DateTrx) >= ").append(commissionLine.get_ValueAsInt(MCommissionLine.COLUMNNAME_DaysFrom));

if (commissionLine.get_ValueAsInt(MCommissionLine.COLUMNNAME_DaysTo) != 0)
    sql.append("  AND paymenttermduedays(h.C_PaymentTerm_ID, h.DateInvoiced, p.DateTrx) <= ").append(commissionLine.get_ValueAsInt(MCommissionLine.COLUMNNAME_DaysTo));
```

The code would change to:
```
//	Days Due
if (commissionLine.get_ValueAsInt(MCommissionLine.COLUMNNAME_DaysFrom) != 0){
    if (commission.isDaysDueFromPaymentTerm)
        sql.append(" AND paymenttermduedays(h.C_PaymentTerm_ID, h.DateInvoiced, p.DateTrx) >= ").append(commissionLine.get_ValueAsInt(MCommissionLine.COLUMNNAME_DaysFrom));
    else
	sql.append(" AND h.DaysDue >= ").append(commissionLine.get_ValueAsInt(MCommissionLine.COLUMNNAME_DaysFrom));
}				
if (commissionLine.get_ValueAsInt(MCommissionLine.COLUMNNAME_DaysTo) != 0){
    if (commission.isDaysDueFromPaymentTerm)
        sql.append("  AND paymenttermduedays(h.C_PaymentTerm_ID, h.DateInvoiced, p.DateTrx) <= ").append(commissionLine.get_ValueAsInt(MCommissionLine.COLUMNNAME_DaysTo));
    else
        sql.append(" AND h.DaysDue <= ").append(commissionLine.get_ValueAsInt(MCommissionLine.COLUMNNAME_DaysTo));
}
```

**Comment by e-Evolution** [comment]
@marcalwestf 

The new flag IsDaysDueFromPaymentTerm is ok for column of database, but not to show in screen, so please Can define rightly the name and description for IsDaysDueFromPaymentTerm? I think that is better show "Is Days Due From Payment Term"
