### ISSUE TITLE
Class Cast Exception Adempiere FinReport Class

### ISSUE THREAD

**Issue by bilalperyani** [adempiere/adempiere#1563]
When I run process Create Report it gives me the following exception
 "java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String" after debugging I have found the following line of code error prone
 Line # 833 && finReport.getListSources().equals(MReport.LISTSOURCES_No)) {

After further Investigating in X_Pa_Report class 
	public String getListSources () 
	{
		return get_Value(COLUMNNAME_ListSources);//it is returning boolean value however method return type is String 
	}
I have changed the method body like this and than error gone 
public String getListSources () 
	{
		
		
		if ((Boolean)get_Value(COLUMNNAME_ListSources))
			return "Y";
		if (!(Boolean)get_Value(COLUMNNAME_ListSources))
			return "N";
		return (String)get_Value(COLUMNNAME_ListSources);
	}
Same scenario is also happening for List Transaction field .

**Comment by yamelsenih** [comment]
I was resolved yet
