### ISSUE TITLE
Migration Scripts not applied 03660, 03670, 03690, 3.90lts-3.91

### ISSUE THREAD

**Issue by elmoyses** [adempiere/adempiere#1570]
I am unable to create Vendor or Customer Invoices.

When I try to save a new Vendor Invoice I receive the following message:

DBExecuteError - ERROR: column "isallocateimmediate" of relation "c_invoice" does not exist   Position: 42   Location: File: parse_target.c, Routine: checkInsertTargets, Line: 1005  
--

Looking for a solution I found the following commit:

https://github.com/adempiere/adempiere/commit/309f6e9a4cc506179a3cb12de18453cd5bd0b1eb

I have problems applying the scripts listed in my installation:

03660
Application failed: org.adempiere.exceptions.AdempiereException: Migration 3660 - SB_HHRR_CreateInvoice_SmartBrowser - 3.9.1 (D) ; Step: 5320; Type: AD. Step 5320, Record 60618 was not found in table Browse Field (53223).

03670
Application failed: org.adempiere.exceptions.AdempiereException: Migration 3670 - YearEndClosing - 3.9.1 (D) ; Step: 410; Type: AD. Step 410, Record 54254 was not found in table Tree Node MM (452).

03690
Application failed: org.adempiere.exceptions.AdempiereException: Migration 3690 - InvoiceAllocateInmediate - 3.9.1 (D) ; Step: 270; Type: AD. Step 270, Record 86715 was not found in table Column (101).
Application failed: org.adempiere.exceptions.AdempiereException: Migration 3690 - InvoiceAllocateInmediate - 3.9.1 (D) ; Step: 280; Type: AD. Step 280, Record 86588 was not found in table Column (101).

**Comment by yamelsenih** [comment]
Resolved
