### ISSUE TITLE
Migration Script not applied 3640, 3.90lts-3.91

### ISSUE THREAD

**Issue by elmoyses** [adempiere/adempiere#1571]
#1553
https://github.com/adempiere/adempiere/blob/develop/migration/390lts-391/03640_1553_SB_HHRR_CreateInvoice_View.xml

The Migration script 3640 can not be applied to the installation. It shows the following information on step 3530:

Application failed: org.adempiere.exceptions.AdempiereException: SaveError

**Comment by yamelsenih** [comment]
Resolved
