### ISSUE TITLE
Adempiere 3.8 could not add Product Attribute Set Instance

### ISSUE THREAD

**Issue by rizalray** [adempiere/adempiere#1573]
Dear All,

Currently I'am trying to test Adempiere 3.8 for my project. But I found some problem related to Product Attribute. I cannot add a new attribute to the product if the attribut type is text, but it's fine if the type is number.
![attribute set](https://user-images.githubusercontent.com/7224440/36090425-ea4f1946-1012-11e8-8c93-1f35c71f7ea9.png)

is there something I need to change in code?

**Comment by yamelsenih** [comment]
Hi, @rizalray have you 3.9 versión? i will test it for you
