### ISSUE TITLE
The enhancement allows defining the payment document type into the document type for pay selection. 

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#1580]
The enhancement allows defining the payment document type into the document type for pay selection. 

When pay selection is completed the payment will be generated with the payment document type defined in document type of the pay selection.

**Comment by SusanneCalderon** [comment]
@e-Evolution . Hello Victor, comparing I_C_Doctype of your branch with the class in adempiere/develop I see that the column isReversedWithOriginalAcct is omitted. Did you delete this funcionality?

**Comment by e-Evolution** [comment]
@SusanneCalderon thank a lot for your suggestion , this was fixed into e8a9a94

**Comment by SusanneCalderon** [comment]
@e-Evolution Hi Victor, I looked at the changes for this isssue in the pull request 1631 and the methods for the columns revertwithoriginal acct are deleted. I do not know if this will give you troubles with this enhancement in 3.9.1.
are omitted.
![imagen](https://user-images.githubusercontent.com/15349639/38748932-0d4cf0e8-3f0d-11e8-9649-55aec3cf7f12.png)

**Comment by e-Evolution** [comment]
@SusanneCalderon this change was included again into e8a9a94 , I regenerate the model class and fix this problem.
