### ISSUE TITLE
Bugfix error in the getconcept method

### ISSUE THREAD

**Issue by silvianapatricia** [adempiere/adempiere#1581]
the getconcept method does not work in special payroll

![imagen_15](https://user-images.githubusercontent.com/36901843/36756227-cbd7c1a6-1be4-11e8-8594-203af06b3ea3.png)

**Comment by yamelsenih** [comment]
It is because payroll period is mandatory for query in getConceptSum:

<pre>
//check process and payroll
		whereClause.append(" AND EXISTS (SELECT 1 FROM HR_Process p"
							+" INNER JOIN HR_Period pr ON (pr.HR_Period_id=p.HR_Period_ID)"
							+" WHERE HR_Movement.HR_Process_ID = p.HR_Process_ID" 
							+" AND p.DocStatus IN('CO', 'CL')"
							+" AND p.HR_Payroll_ID=?");
</pre>

**Comment by yamelsenih** [comment]
it is bad for **getConceptSum** and **getConceptAvg** methods
