### ISSUE TITLE
Loan Simulator

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#1585]
Is nice to have a form for simulate loan and run a   amortization table from it.

It can be used for any user for a fast vow of loan

**Comment by adaxa-steven** [comment]
Hi Yamel, are you going to support more than one interest rate calc method? 
eg   https://en.wikipedia.org/wiki/Rule_of_78s
Sometimes you still encounter this.
regards
steven

**Comment by yamelsenih** [comment]
Hi @adaxa-steven it is a big feature for Financial Management, tou can see the project in https://github.com/adempiere/adempiere/projects/20
Also already exist a ER-Diagram for emulate financial transaction https://user-images.githubusercontent.com/2333092/36791666-d7124480-1c6e-11e8-9f29-ad6a6ec343f5.png

It feature allows define many financial setting, you can have a Financial Product Category and it can have a behavior distinct that other Financial Product Category.

Best Regards
