### ISSUE TITLE
Generate Loan from Simulator

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#1587]
Is nice to have a process for generate loan from simulation, it allows simulate and test loan, after it you will create loan

**Comment by yamelsenih** [comment]
Here a pic: 
![screenshot_20180326_142447](https://user-images.githubusercontent.com/2333092/37925322-39f0449c-3102-11e8-86a9-b9129a859d53.png)

**Comment by wdtz** [comment]
- When generating the loan from the simulator, it does not establish the currency of the financial product but the default currency

**Comment by yamelsenih** [comment]
> When generating the loan from the simulator, it does not establish the currency of the financial product but the default currency

Resolved
