### ISSUE TITLE
Generate Payment Selection from Loan

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#1589]
When loan is generated, it can generate a Payment Selection for Business Partner with Capital Amount, also it can discount flat commision

**Comment by yamelsenih** [comment]
Here a pic:
![screenshot_20180326_142546](https://user-images.githubusercontent.com/2333092/37925278-237a8470-3102-11e8-8640-7794a3db6532.png)

**Comment by wdtz** [comment]
- when the payment selection is closed it must allow generating another payment selection

- when a payment selection is generated for many loans it does not indicate the number, instead it generates the message indicated in the image 
![paso8](https://user-images.githubusercontent.com/9578152/37941670-e2f54dc4-315e-11e8-94df-f8551849074a.png)

**Comment by yamelsenih** [comment]
>when the payment selection is closed it must allow generating another payment selection

Resolved

>Not supported in the process the bank account for the business partner

Nice to have

>when a payment selection is generated for many loans it does not indicate the number, instead it generates the message indicated in the image

Resolved
