### ISSUE TITLE
RUN_ImportAdempiere.sh is failing when postgresql admin pass is empty

### ISSUE THREAD

**Issue by helal00** [adempiere/adempiere#1591]
RUN_Setup.sh is failing to run RUN_ImportAdempiere.sh on ubuntu/debian when PostgreSQL admin pass is empty. We should exclude empty string check for $ADEMPIERE_DB_SYSTEM in RUN_ImportAdempiere.sh or not allow empty string as admin pass in RUN_Setup.sh.

This issue is keeping many newbies from getting smooth start with adempiere.
I am using ADempiere 3.9.0

**Comment by yamelsenih** [comment]
This was resolved yet
