### ISSUE TITLE
Generate Invoice from Amortization Quote

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#1599]
It Process allows create a invoice from amortization quote, the invoice can have the follow:
- Capital Amount
- Interest Amount
- Dunning Interest Amount

**Comment by yamelsenih** [comment]
Here a pic:
![screenshot_20180326_142640](https://user-images.githubusercontent.com/2333092/37925174-eebfa4b8-3101-11e8-898a-ce53aafe746d.png)

**Comment by wdtz** [comment]
- The Smart Browser does not validate when a loan is not paid

- The parameter (Yes / No) does not work, does not filter

- When generating the invoice in the filter "Destination Document Type" shows types of accounts payable documents, generates the invoice with this type of document even when it is Accounts Receivable.

- It does not generate the invoice respecting the sequence of quotas (Consecutively)

- The currency brings it from the default price list and must be from the loan

- The conversion is not supported

- There is no possibility to generate separate invoices for Interest and Capital

**Comment by yamelsenih** [comment]
>The parameter (Yes / No) does not work, does not filter
ZK Bug

**Comment by yamelsenih** [comment]
>The Smart Browser does not validate when a loan is not paid

Resolved

>The currency brings it from the default price list and must be from the loan

Resolved

>The conversion is not supported

Resolved

>There is no possibility to generate separate invoices for Interest and Capital

Nice to have
