### ISSUE TITLE
Enhancement allows define the accounting by payroll from payroll concept

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#1604]
Currently, you only can define an account combination based on payroll concept, but exist some case that is necessary have an account combination different by payroll.

Solution: adding the column Payroll (HR_Payroll_ID) to defined the account combination for  a specific payroll, if the payroll is empty then the account combination  apply for all payroll

**Comment by yamelsenih** [comment]
Hi @e-Evolution it is a great change, i use it currently for many customers and is good, if you want, i can put a class with it change already supported and tested.

Best regard

**Comment by e-Evolution** [comment]
New Payroll account setting

<img width="1620" alt="captura de pantalla 2018-03-21 a la s 15 34 37" src="https://user-images.githubusercontent.com/786968/37738700-69ccfa18-2d1d-11e8-9cb2-2ac6ca021c09.png">

**Comment by yamelsenih** [comment]
Here is files:
[Payroll.zip](https://github.com/adempiere/adempiere/files/1835547/Payroll.zip)
Also i add a small patch for MHRConcept

<pre>
	/**
     * Get Account configuration
     * @param acctSchemaId
     * @param payrollId
     * @return
     */
    public X_HR_Concept_Acct getConceptAcct(int acctSchemaId, int payrollId) {
    	return new Query(getCtx(), I_HR_Concept_Acct.Table_Name, 
    			"HR_Concept_ID = ? AND C_AcctSchema_ID = ? "
    			+ "AND (HR_Payroll_ID = ? OR HR_Payroll_ID IS NULL)", get_TrxName())
    		.setParameters(getHR_Concept_ID(), acctSchemaId, payrollId)
    		.setOrderBy("COALESCE(HR_Payroll_ID, 0) DESC")
    		.first();
    }
</pre>

It is worked, testing for [ERPYA](http://erpya.com/) and exist in production
