### ISSUE TITLE
java.sql.SQLSyntaxErrorException: ORA-00904: name : invalid identifier

### ISSUE THREAD

**Issue by gheoneaemil** [adempiere/adempiere#1612]
I'm trying to upload an image into an Oracle 11g xe database
everything is good except the blob i guess;
the path variable is a string which refers to the adress of the image(Ex:"C:\\image.png").

try {
					InputStream img = new FileInputStream(new File(path));
					Class.forName("oracle.jdbc.driver.OracleDriver");
					Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "SYSTEM", "password");
					PreparedStatement posted = con.prepareStatement("INSERT INTO users (cname,cda,cne,cyield,cwebsite,cfounder,clogo) VALUES (?,?,?,?,?,?,?)");
					posted.setString(1, textField.getText());
					posted.setString(2, textField_1.getText()); 
					posted.setString(3, textField_3.getText()); 
					posted.setString(4, textField_4.getText());
					posted.setString(5, textField_5.getText());
					posted.setString(6, textField_6.getText());
					posted.setBlob(7,img);
					posted.executeUpdate();
					}catch(Exception exc){System.out.println(exc);}
					finally {
						JOptionPane.showMessageDialog(null,"ok", null, JOptionPane.INFORMATION_MESSAGE);
					}
The error is:
java.sql.SQLSyntaxErrorException: ORA-00904: "CLOGO": invalid identifier

Can anyone help me please?

**Comment by marcalwestf** [comment]
hi @gheoneaemil though I don't use Oracle , it would be for others of interest to know which Adempiere version you are using.

It would be also interesting to know on which table you are working: as far as I know, there is no table "users" in Adempiere. Or perhaps is it your own customization?

**Comment by chenweishi** [comment]
OK

On Mar 28, 2018 8:30 AM, "e-Evolution" <notifications@github.com> wrote:

Closed #1612 <https://github.com/adempiere/adempiere/issues/1612>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/adempiere/adempiere/issues/1612#event-1544507495>, or mute
the thread
