### ISSUE TITLE
Add support to the definition of commissions (by collection)

### ISSUE THREAD

**Issue by RJPC** [adempiere/adempiere#1613]
Validation must be added so that when calculating commissions do not take into account the reverse charges

Images regarding the configuration, reverse charge and calculation of commission

**Configuration**
![comision por cobranza](https://user-images.githubusercontent.com/5696550/37914935-e9fae54a-3107-11e8-9314-38f63cbb389d.png)
![linea de comision por cobranza](https://user-images.githubusercontent.com/5696550/37914951-eee19c20-3107-11e8-9b7d-d6061c5fe335.png)

**Charge reverse**
![Uploading Cobro Reversado.png…]()

**Caculation of commission**
![detalle de comision](https://user-images.githubusercontent.com/5696550/37915027-151d3cb4-3108-11e8-9329-e8e507e88348.png)

Open balances (where you can see that the bill for which you are commissioning has not yet been charged)
![saldos abierto](https://user-images.githubusercontent.com/5696550/37915250-9bfe0204-3108-11e8-8d62-dce606696a32.png)

**Comment by marcalwestf** [comment]
hi @RJPC . Could you please describe with an example the new functionality (or is it a bug correction)?
This way we could figure out better the situation now and the proposed new behavior.
Thanks in advance.

**Comment by RJPC** [comment]
hi @marcalwestf , It is a correction, currently the process generates commission for reverted charges, if the charge is reversed it should not generate commission for this charge since it is a zero charge.

**Comment by yamelsenih** [comment]
It is caused by:
<pre>
h.DocStatus IN ('CL','CO','RE')
</pre>

**Comment by yamelsenih** [comment]
line 683 of MCommissionRun

**Comment by marcalwestf** [comment]
Code reviewed and indeed, the  the documents to be found (Payments and Invoices) must not have the docStatus='RE'.

**Comment by yamelsenih** [comment]
This was added
