### ISSUE TITLE
Option totally paid presents bug (Definition of Commissions)

### ISSUE THREAD

**Issue by RJPC** [adempiere/adempiere#1614]
when the option totally paid is checked and proceed a calculate the commission, the processo present the next message the bug (attached imagen and log bug)

**Definition of Commissions**
![total pagado](https://user-images.githubusercontent.com/5696550/37916147-aa109954-310a-11e8-85e9-8d3db03fad1a.png)

**Menssage the bug**
![bug msj](https://user-images.githubusercontent.com/5696550/37916155-afded63e-310a-11e8-8b77-b1c50c53ad4c.png)

[trace.log](https://github.com/adempiere/adempiere/files/1848435/trace.log)

**Comment by yamelsenih** [comment]
<pre>
org.postgresql.util.PSQLException: ERROR: function maxpaydate(numeric) does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 556
</pre>

**Comment by yamelsenih** [comment]
Resolved
