### ISSUE TITLE
Enhancement New Smart Browser in Pricelist Version to edit and generate  entries in Product Price

### ISSUE THREAD

**Issue by SusanneCalderon** [adempiere/adempiere#1615]
A new SmartBrowser to generate and edit new entries in M_ProductPrice. 
The fields standard price, list price and limit price are editable. 
The smartbrowser is used from a new button in the tab _PriceList_Version_  in the window _PriceList_

**Comment by e-Evolution** [comment]
@SusanneCalderon Can please set here screenshot or gif animate image with the functionality?

**Comment by yamelsenih** [comment]
It already merged yet
