### ISSUE TITLE
Create collect from Invoice list

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#1616]
For now, ADempiere has a process for collect invoice like:

- Create Collect (Payment/Receipt)
- Select a Invoice or go to Pay more invoice ans select more than one.
- Complete Payment/Receipt
Other way is:
- Create Collect (Paymnt/Recipt) without choice a invoice.
- Go to Payment Allocation and select Collect and select Invoices to collect.

I propose add a Smart Browse for view all open invoice and make a payment/receipt from there, it allows create receipt from it SB very easy.

**Comment by wdtz** [comment]
# **Test results**

- The filter bank account and payment rule is not relevant for the search of pending invoices to be canceled. (Attached Imegen)
![paso8](https://user-images.githubusercontent.com/9578152/38432120-fb34ebc4-39b5-11e8-8776-636446f3455e.png)
- The bank account must be editable to select the account in which the payment will be deposited
![paso8](https://user-images.githubusercontent.com/9578152/38433092-231bd2a8-39b9-11e8-98da-a59e634cdb6d.png)
- When selecting invoices with different currencies the system with supports currency conversion
![paso8](https://user-images.githubusercontent.com/9578152/38433531-c5b3563e-39ba-11e8-8847-d3609c01283c.png)
- The process does not include a document number

**Comment by yamelsenih** [comment]
Continue discussione here: https://github.com/adempiere/adempiere/pull/1783
