### ISSUE TITLE
Readonly Logic for tab does not prevent the data from modifying

### ISSUE THREAD

**Issue by syvasoft** [adempiere/adempiere#162]
If the tab is set as read only by Readonly Logic, it does not prevent the data from modifying and the modified data are saved by auto-commit feature when the focus goes to different record or tab.
The same issues are there for both Swing and Web UI.

**Comment by e-Evolution** [comment]
Dear Syvasoft, Would please set here the step to replicate this issue?

**Comment by syvasoft** [comment]
Dear @e-Evolution, 
Login using System/System
In Application Dictionary,
1. Go to Window, Tab & Field, Search for Test window.
2. Switch to Tab tab, set Read only as 1=1 then save it.
3. Reset Cache using Cache Reset Process.
4. Go to System Admin > General Rules > Test window.
5. Due to read-only logic we have set above, New, Clone, Save & Delete toolbar buttons are disabled.
6. Still the fields are editable here. Now modify Name field to "loreum ipsum" then move to next record (make sure you should have at least 2 records already created in this window).
7. Then go back to previous records, there you see your modifications have been saved by auto-commit feature regardless of read-only logic is set as true and it should not have been saved. Hence, it is a bug.

**Comment by dixon22ma** [comment]
Dear @syvasoft, the tabs already check the read-only logic.
