### ISSUE TITLE
TABLE c_allocationhdr COLUMN C_DocType_ID is missing

### ISSUE THREAD

**Issue by klstwh** [adempiere/adempiere#1624]
Used in MAllocationHdr, X_C_AllocationHdr but not in DB, DataDictionary.
Payment with Allocation could not be completed.

**Comment by e-Evolution** [comment]
The XML script that added this column was commit into https://github.com/adempiere/adempiere/issues/1469

I think that you are using last code with a Database not updated , if you use seed for 390 you should use source code for tag 3.9.0

**Comment by klstwh** [comment]
Ok, yes: "... using last code with a Database not updated."
