### ISSUE TITLE
Calculation of Commissions (Support to Credit Notes)

### ISSUE THREAD

**Issue by RJPC** [adempiere/adempiere#1628]
Currently the credit notes are increasing the amount of the commission, the correct thing is that they reduce the amount to be commissioned, Example:

**ADempiere is doing the following:**
Invoices: $ 1000
Credit Notes: $ 200
Commission: ($ 1000 + $ 200) * 4%
Total Commission: $ 48

**The correct is:**
Invoices: $ 1000
Credit Notes: $ 200
Commission: ($ 1000 - $ 200) * 4%
Total Commission: $ 32

**Comment by yamelsenih** [comment]
Resolved yet
