### ISSUE TITLE
Add support for commissions based on deliveries

### ISSUE THREAD

**Issue by RJPC** [adempiere/adempiere#1630]
It is proposed to be supported the commissions based on complete deliveries, example:

**Sales Orders:** 10 x $ 100 = $ 1000
**Delivered:** 7 x $ 100 = $ 700
**Commission calculation:** 700 $ * 4%
**Total Commission:** $ 28

**Comment by yamelsenih** [comment]
Here a pic:
![screenshot_20180328_161258](https://user-images.githubusercontent.com/2333092/38053807-0f527f8c-32a3-11e8-8b82-19053c1915cc.png)

**Comment by RJPC** [comment]
Hi @yamelsenih , You must add support for the returns, currently the returns are increasing the amount to be commission, the must be is to reduce the amount to be commission.
