### ISSUE TITLE
Force parameter in RUN_MigrateXML.sh

### ISSUE THREAD

**Issue by rcapecce** [adempiere/adempiere#1635]
Hello.

Do we have a parametter in this script to indicate that we want to force the migration like in the window?

**Comment by marcalwestf** [comment]
hi @rcapecce the shell script loads and executes the migration files.

**Comment by rcapecce** [comment]
Hi,
Yes @marcalwestf but not in force mode

**Comment by yamelsenih** [comment]
The force parameter is added on pull request #1789 

The discussion will be continue on pull request
