### ISSUE TITLE
Enhancement Process Invoice Complete Pay And Print for Purchase and  Invoices

### ISSUE THREAD

**Issue by SusanneCalderon** [adempiere/adempiere#1636]
For simple purchases invoices it is convenient to use a process that completes, creates the payment and prints the document (i.e. checks) in one process.
This process is implemented in a button in the window purchase Invoices. The parameters are

- payment rule

- bank account (only the bankaccounts with bankaccount documents corresponding to the parameter paymentrule are shown)

- current next(next checkNo), from the corresponding bankaccount document

- is printed

- is direct print

- creditcard number and credit card type.

The process completes the invoice and generates a payment using the process parameters. When _isprinted_ the document print is initiated and the report is shown as jasper or report, depending of the configuration of the printformat and _isdirectprint_
This process can substitute the special form Payment.

**Comment by e-Evolution** [comment]
@SusanneCalderon here , some my suggestions the new process should be only include as process action this way can be call from tools bar and not saturate the screen.

What is the goal to set is printed and is direct print ?

if you want print a check why you need card type ?

Why not use tender type?

kind regards

**Comment by SusanneCalderon** [comment]
Perhaps you can show me what you mean with a process action?

**Comment by SusanneCalderon** [comment]
_Why not use tender type?_
The next parameter is a lookup on c_bankaccountDoc, with the corresponding paymentrule. This way we avoid payments for paymentrules which are not allowed for this bankaccount(i.e. credit card payments en a wrong bankaccount). The process converts the paymentrule to the corresponding tendertype.

**Comment by e-Evolution** [comment]
@SusanneCalderon the process action is of icon that show in each window i.e.

<img width="1527" alt="image" src="https://user-images.githubusercontent.com/786968/38374716-fc7c8200-38b9-11e8-89fb-64de1f7a0df8.png">

this can be added from application dictionary into  a table.

On the other hand , have you a screen shot the process dialog for this improves ?

**Comment by SusanneCalderon** [comment]
@e-Evolution Hello Victor, here are 2 screenshots for tendertype check and credit card
![imagen](https://user-images.githubusercontent.com/15349639/38457100-4b903478-3a49-11e8-81ad-467ee9dfef3f.png)

![imagen](https://user-images.githubusercontent.com/15349639/38457112-64ca8fec-3a49-11e8-8576-6ddc041ddbe8.png)
