### ISSUE TITLE
Operational Calendar: NPE When Creating Periods

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere#1637]
In an _Operational Calendar_ a user wants to create periods by pressing the button _Create Periods_:
![20180403_forecast_01](https://user-images.githubusercontent.com/1789408/38259241-c6701350-3721-11e8-8ed0-f57bd894a76e.png)

**If no year is defined in the period definition, a NPE is thrown**:
![20180403_forecast_03](https://user-images.githubusercontent.com/1789408/38259371-0f7e480a-3722-11e8-9026-6a0631154786.png)

The reason: in method _MPPPeriodDefinition.getYearAsInt()_ the variable year equals NULL, which causes theNPE.
![20180403_forecast_02](https://user-images.githubusercontent.com/1789408/38259585-a337314c-3722-11e8-80af-5e885db85b53.png)

Solutions
1. Catch the NULL in the program.
2. Define the year as obligatory.

BTW, this doesn't happen if the field Year has a valid year, e.g. 2018.

**Comment by yamelsenih** [comment]
Already resolved it

**Comment by yamelsenih** [comment]
Hi @marcalwestf please review the PR and approve it
