### ISSUE TITLE
Delivery Planning of the demands report

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#164]
This report show the Demands planning to delivery that can be use to create on Outbound Order

**Comment by yamelsenih** [comment]
Hi, any update for it?

**Comment by e-Evolution** [comment]
@yamelsenih this functionality was implemented from 3.9.0

![image](https://user-images.githubusercontent.com/786968/58442116-93dde080-80ad-11e9-9219-c7ed5cdda093.png)
