### ISSUE TITLE
Error processing commission calculation (filtering by commission group)

### ISSUE THREAD

**Issue by RJPC** [adempiere/adempiere#1642]
Currently, when trying to process a commission calculation filtered by commission group, the following error occurs:

![commission](https://user-images.githubusercontent.com/5696550/38342842-339f8c04-3870-11e8-9542-96ea0c6239ac.png)

![commission bug](https://user-images.githubusercontent.com/5696550/38342862-559244aa-3870-11e8-86f5-ad91e44a85cc.png)

[trace.log](https://github.com/adempiere/adempiere/files/1878306/trace.log)

**Comment by yamelsenih** [comment]
Fixed yet
