### ISSUE TITLE
Enhancement Add new window for Project Info

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#1646]
This new window is similar to Business Partner Info

<img width="1615" alt="image" src="https://user-images.githubusercontent.com/786968/38443421-337cbca0-39b1-11e8-90a7-c32565778540.png">

So the new window will have all the related information for a Project, any suggestion is welcome.

**Comment by e-Evolution** [comment]
New Project window

<img width="1868" alt="image" src="https://user-images.githubusercontent.com/786968/38584734-d553c36a-3cdc-11e8-9275-e46aa88bef8e.png">

**Comment by adaxa-steven** [comment]
Hi Victor, 
what table is "members"

**Comment by marcalwestf** [comment]
@adaxa-steven Members are users who are involved in the project.

It should be possible to restrict access to the project data only to dedicated users.
