### ISSUE TITLE
Smart Browser Create from Invoice in pay selection does not consider the cash discount

### ISSUE THREAD

**Issue by SusanneCalderon** [adempiere/adempiere#1648]
The payamt in the smartbrowser is the open amount and does not consider a discount like _2% discount if paid in 10 days_
![captura de pantalla 162](https://user-images.githubusercontent.com/15349639/38508360-3d9dba4a-3bdc-11e8-90db-b1e0ab69c5dd.png)

Solution: 
replace the view column payamt _currencyConvert(invoiceOpen(inv.C_Invoice_ID, inv.C_InvoicePaySchedule_ID), inv.C_Currency_ID, @INV_C_Currency_ID@, TO_DATE('@PayDate@','YYYY-MM-DD'), inv.C_ConversionType_ID, inv.AD_Client_ID, inv.AD_Org_ID)_
with 
_currencyConvert(invoiceOpen(inv.C_Invoice_ID, inv.C_InvoicePaySchedule_ID), inv.C_Currency_ID, @INV_C_Currency_ID@, TO_DATE('@PayDate@','YYYY-MM-DD'), inv.C_ConversionType_ID, inv.AD_Client_ID, inv.AD_Org_ID) - 
currencyConvert(paymentTermDiscount(inv.GrandTotal, inv.C_Currency_ID, inv.C_PaymentTerm_ID, inv.DateInvoiced, TO_DATE('@PayDate@','YYYY-MM-DD')), inv.C_Currency_ID, @INV_C_Currency_ID@, TO_DATE('@PayDate@','YYYY-MM-DD'), inv.C_ConversionType_ID, inv.AD_Client_ID, inv.AD_Org_ID)_

**Comment by yamelsenih** [comment]
Please continue discussione here: https://github.com/adempiere/adempiere/pull/1650
