### ISSUE TITLE
OrderPOCreate - Generate PO from Sales Order creates POs from Drafted sales order

### ISSUE THREAD

**Issue by homebeaver** [adempiere/adempiere#1649]
this is a bug. The process has to generate POs only if the DocStatus of the sales order is `Completed` (Status `InProgress` seems for me ok too), but not on `Drafted` as the example shows:

![grafik](https://user-images.githubusercontent.com/3493126/38510644-f14792f2-3c25-11e8-9cc6-01d1b5ae8b89.png)

**Comment by homebeaver** [comment]
the solution for this Bug is simple. Add the following in private method `OrderPOCreate.createPOFromSO`
 
```java
...
if(DocAction.STATUS_InProgress.equals(so.getDocStatus()) || DocAction.STATUS_Completed.equals(so.getDocStatus())) {
	// OK - continue 
} else {
	log.warning("DocStatus is " + so.getDocStatus());
	return 0;
}
...
```
But there are some other shortcomings:

- products which are stocked and onHand should not be purchased
- products with `isPurchased='N'` should not be purchased
- BOM products `isBOM='Y'` should not be purchased

**Comment by yamelsenih** [comment]
Hi @homebeaver have you a pull request for it? i can test for you

Best regard

**Comment by homebeaver** [comment]
Hi @yamelsenih - I'm working on it.

**Comment by yamelsenih** [comment]
Hi @homebeaver y have a change for it, i seem mani commits from your change.

Want you get my change and adde your changes?

Best regard

**Comment by homebeaver** [comment]
thank you very much @yamelsenih  
I'II have no time this year to track the pull request #1866 . Sorry :-(
Mybe you can bring this PR to an end in 3.9.1

regards EUGen

**Comment by yamelsenih** [comment]
Yes @homebeaver i will to review your PR

**Comment by yamelsenih** [comment]
Hi @homebeaver I added a validation for document status here https://github.com/adempiere/adempiere/pull/2201

Best regard
