### ISSUE TITLE
Where are the folders $ ADEMPIERE_ROOT and $ ADEMPIERE_HOME?

### ISSUE THREAD

**Issue by it19862** [adempiere/adempiere#1659]
The instructions say:
  "There is no install script. Just extract the ADempiere archive to a suitable location: (e.g. c:\ or /u01/). For reference, call this directory $ADEMPIERE_ROOT. You should end up with the files in a folder like $ADEMPIERE_ROOT\Adempiere. For reference, call this folder $ADEMPIERE_HOME."

I downloaded ADempiere 3.9.0
https://github.com/adempiere/adempiere/releases

I've placed the files in a folder
"c: \ Program Files \ ADempiere390 \"
![3153](https://user-images.githubusercontent.com/18245828/38767781-7c69012c-3ff0-11e8-818e-d8986419fa59.jpg)

Where are the folders "$ ADEMPIERE_ROOT" and "$ ADEMPIERE_HOME" that are mentioned in the instruction?

**Comment by yamelsenih** [comment]
Hi @it19862 
**$ADEMPIERE_HOME** and **$ADEMPIERE_ROOT** is a path for the main folder of ADempiere, for you **$ADEMPIERE_HOME** should be **C:\Program Files\ADempiere390**
