### ISSUE TITLE
Garden World setup

### ISSUE THREAD

**Issue by mckayERP** [adempiere/adempiere#166]
Garden World should work out of the box with the least confusion for the user.  For example, Garden Admin should have "Show Accounting Tabs" selected as default in preferences, window.  Accounting should be posted with costing functional.

**Comment by mckayERP** [comment]
Running the accounting and cost generation functions after a fresh install, import and migration result in several unposted documents.  Matched invoice 100 can't be posted because the material receipt 1000000 is not posted yet.  But MR 1000000 is posted. The same with matched invoice 101 and material receipt 1000001.

**Comment by mckayERP** [comment]
The reason the MR can't be found is the quantity in the accounting facts for the MR is set to zero.

**Comment by mckayERP** [comment]
The quantity is set to zero since the cost detail has zero quantity.  The default costing is average invoice.  The cost details for the Oak Tree and MR 1000001 show two records, the first with quantity 10 and no cost and the second with quantity zero and costs associated with the invoice.  The generation of facts for the MR looks for cost details with costs using the following code:

		//  *** Purchasing - Receipt
		else if (getDocumentType().equals(DOCTYPE_MatReceipt) && !isSOTrx())
		{
			BigDecimal total = Env.ZERO;
			for (int i = 0; i < p_lines.length; i++)
			{
				int C_Currency_ID = as.getC_Currency_ID();
				//
				DocLine line = p_lines[i];
				BigDecimal costs = null;
				MProduct product = line.getProduct();
				for (MCostDetail cost : line.getCostDetail(as, true))
				{	
						if (!MCostDetail.existsCost(cost))
							continue;  // Will skip cost details with zero cost but non-zero qty.
						...
						...
						dr = fact.createLine(line, assets,
							C_Currency_ID, costs, null);
						dr.addDescription(description);
						//
						if (dr == null)
						{
							p_Error = "DR not created: " + line;
							log.log(Level.WARNING, p_Error);
							return null;
						}
						dr.setM_Locator_ID(line.getM_Locator_ID());
						dr.setLocationFromBPartner(getC_BPartner_Location_ID(), true);   // from Loc
						dr.setLocationFromLocator(line.getM_Locator_ID(), false);   // to Loc
						dr.setM_Product_ID(cost.getM_Product_ID());
						dr.setQty(cost.getQty());  // Can get set to zero  !!

**Comment by e-Evolution** [comment]
Hi MIke

The steps should be

1.- Open of curren period
2.- Execute generare cost from 01/01/2000
3.- Re sent posting 
4.- Next  execute accounting 
5 - print the inventory valuation
6.- print Account balance for inventory so that the total 
report id same that total balance

**Comment by e-Evolution** [comment]
Mike what is settig you are testig?
Method Costig
Cost type 
Cost level
?

**Comment by mckayERP** [comment]
I'm using the defaults in the seed for Garden World which are set to average invoice.
The process is described here: http://wiki.adempiere.net/Garden_World.

So after a fresh install, import and migrateXML, the first thing I do is:

1. In ADempiere GW as GW Admin, run generate cost transactions
2. Run client account processor

Then, I check for unposted documents and found these two match invoices.

As some of the documents won't post without the cost info, I think we should add these steps in the next seed to make it simpler for demos.  I don't think this is a lot of data.

We can reduce the seed size by using 

    RUN_MigrateXML clean

on the current seed to remove all the steps and data that is no longer required.

**Comment by mckayERP** [comment]
Victor, can you have a look at this: [https://github.com/mckayERP/adempiere/commit/a46c8843dbea739dae8dee3a8467889b7cd0e1de](https://github.com/mckayERP/adempiere/commit/a46c8843dbea739dae8dee3a8467889b7cd0e1de)

Its a fix I did on my system that solves this issue.  WDYT?
