### ISSUE TITLE
GitHub build warning : distributing binary files

### ISSUE THREAD

**Issue by homebeaver** [adempiere/adempiere#1660]
Hi, last week I made a fork of https://github.com/adempiere/adempiere to https://github.com/klst-com/adempiere and got this mail from GitHub <support@github.com>

**Subject: Page build warning**

The page build completed successfully, but returned the following warning for the `master` branch:

It looks like you're using GitHub Pages to distribute binary files. We strongly suggest that you use releases to ship projects on GitHub. Releases are GitHub's way of packaging and providing software to your users. You can think of it as a replacement to using downloads to provide software. We found the following file(s) which may be a good candidate for releases: `jboss/bin/jbosssvc.exe, jboss/bin/jbossweb.x64.exe, jboss/bin/jbosswebw.x64.exe, jboss/bin/native/openssl.exe, launch/Release/Adempiere.exe, and utils/windows/AdempiereService.exe`. For more information, see https://help.github.com/articles/about-releases/.

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can contact us by replying to this email.

**Comment by skenypatel** [comment]
I'm getting the same error when I try to post my page on github. Did you find any solution to this yet?

**Comment by homebeaver** [comment]
that's a warning, not an error.
