### ISSUE TITLE
Report Inventory Valuated To Date only works for costing level warehouse

### ISSUE THREAD

**Issue by SusanneCalderon** [adempiere/adempiere#1662]

**Comment by SusanneCalderon** [comment]
The SQL in this process looks for qtys in warehouse in the table m_Costdetail. When you have costinglevel Client, the qtys in m_Costdetail are the overall qtys, not the qty for warehouse. 

_SELECT 1100864,tc.DateAcct,p.AD_Client_ID,
p.AD_Org_ID, tc.C_AcctSchema_ID ,tc.M_CostElement_ID,tc.M_CostType_ID, 
tc.M_Warehouse_ID,p.M_Product_ID,p.M_Product_Category_ID,tc.M_AttributeSetInstance_ID,
p.Group1,p.Group2,  
tc.qty + tc.cumulatedqty AS QtyOnHand, 
CASE WHEN tc.Qty < 0 OR (tc.qty = 0 AND tc.cumulatedqty < 0) THEN ((tc.costAmt + tc.costadjustment) * -1) + tc.CumulatedAmt 
ELSE ((tc.costAmt + tc.costadjustment) * 1) + tc.CumulatedAmt END  AS CostAmt, 
CASE WHEN tc.Qty < 0 OR (tc.qty = 0 AND tc.cumulatedqty < 0) THEN ((tc.costAmtLL + tc.costadjustmentLL) * -1)  + tc.CumulatedAmtLL 
ELSE ((tc.costAmtLL + tc.costadjustmentLL) * 1) + tc.CumulatedAmtLL END AS CostAmtLL 
FROM M_Product p  
INNER JOIN M_CostDetail tc ON (p.M_Product_ID=tc.M_Product_ID) 
WHERE tc.IsReversal='N' AND tc.DateAcct<= TO_DATE('2018-04-18','YYYY-MM-DD') 
AND p.M_Product_ID=1002192  --AND tc.C_AcctSchema_ID=?  
--AND tc.M_CostType_ID =?   AND tc.M_CostElement_ID=?  
AND tc.M_Warehouse_ID=1000020  AND tc.SeqNo = (SELECT MAX(SeqNo) 
										FROM M_CostDetail tc1 WHERE tc1.IsReversal='N' AND tc1.M_Product_ID=tc.M_Product_ID 
										AND tc1.M_Warehouse_ID = tc.M_Warehouse_ID 
										AND tc1.DateAcct<= TO_DATE('2018-04-18','YYYY-MM-DD') 
										AND tc1.C_AcctSchema_ID = tc.C_AcctSchema_ID AND tc1.M_CostType_ID=tc.M_CostType_ID  
										AND tc1.M_CostElement_ID = tc.M_CostElement_ID)_

**Comment by SusanneCalderon** [comment]
Qty on hand of product OV029
![imagen](https://user-images.githubusercontent.com/15349639/38941037-e37da458-42e8-11e8-830d-ec548c6174ac.png)

Result of the report:
![imagen](https://user-images.githubusercontent.com/15349639/38941087-feeb0b90-42e8-11e8-9ac0-843ddc2a5d41.png)

**Comment by SusanneCalderon** [comment]
**Class**: _org.eevolution.process.ValuationEffectiveDate_
**Method**: _doit():_
The table _T_InventoryValue_ is filled with the sql mentioned before. 
It runs through a list of warehouses which consists of all warehouses, or one warehouse selected in the process.

The values of the quantities and costs are taken from the table m_Costdetail, the sql looks for the entry in m_Costdetail for the corresponding product and the corresponding warehouse with the highest sequence number before or equal the selected date. 

**Case costing level Client:**
The cummulated quantity in the costdetail entry found with the parameters warehouse, product and date contains the quantities of all warehouses, which is correct, because the costs are calculated on level client. So you get the overall quantities for all warehouses, and not the quantities of the corresponding warehouse.

**Case costing level Organization**
The cummulated quantity in the costdetail entry found with the parameters warehouse, product and date contains the cummulated quantities of all warehouses of this organization, which is correct, because the costs are calculated on level organization.
So you get the overall quantities for all warehouses of an organization, and not the quantities of the corresponding warehouse.

**Case costing Level Batch/Lot**
The process is not prepared for delivering result on level Batch/Lot.

**Summary**
The report works only for costing level warehouse. 
For all other levels the report deliveres wrong results which are inconsistens thich the accounting.
This is a serious bug.

**Comment by yamelsenih** [comment]
Exists change for it? Can be related to: #2394
