### ISSUE TITLE
Enhancement adds a new action to generate a manufacturing order from a project line.

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#1676]
This new feature allows to generate Manufacturing Order and integrate project functionality with MRP and  CRP

**Comment by marcalwestf** [comment]
hi @e-Evolution  Victor, this seems an interesting enhancement.
I suppose the enhancement you suggest is to create a Manufacturing Order where there is a Product containing a BOM in the Project. This would be in the Project Phase and Project Task.

If this is so, this would be great, as we are about to start committing to the Constrution vertical (https://github.com/SusanneCalderon/adempiereSusanne/tree/feature/ConstructionIndustry).

One step here is to create a BOM for the Project Phase or Project Task which contains a Product with a  default verified BOM. This new BOM would be a copy of the default BOM, only for the Phase or Task and it would be editable.  Here a link to the project, phase and/or task would do the job.

If combined with the enhancement you describe here, we would be a step further. I imagine that the Manufacturing Order to be created would take the BOM created as explained before and use the copied and edited BOM.

**Comment by e-Evolution** [comment]
The BOM and Workflow Manufacturing was adding to Standard Phase and Standard Task , so when a project use a Project Type , the Product , BOM and Workflow Manufacturing are set for a Project Phase or Project Task.

So, you can Create a Manufacturing Order from Phase or Task, this process create a Manufacturing Order link to Project , Phase , Task and a Project Line link to Manufacturing Order. so the relation is completed and bidirectional.
