### ISSUE TITLE
Functional Enhancement: Purchase on Credit

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere#1682]
Many companies which have a good relationtship with their providers, do purchases on credit.

ADempiere does not offer support for purchasing on credit: to model this process, users have to manually create and complete a Purchase Order;  the same with Material Receipt and Purchase Invoice. 

There is in ADempiere "some" help when creating a Material Receipt from a Purchase Order and a Purchase Invoice from a Material Receipt, but as users increasingly expect the system does the most it can, they ask if this can be improved.

The suggestion here is to implement  **Purchases on Credit**.

Similar to a Sales Order, a Purchase Order would be created and completed.
The completion of the Purchase Order would automatically on the one hand create and complete a Material Receipt, on the other hand create and prepare a Purchase Invoice.

Doing so, i.e. having a completed Material Receipt, but a prepared Purchase Invoice in lieu with completing the Purchase Order comes handy while modelling a purchase, as the company often know exactly what it will get (or have gotten), being the price the only possible discrepancy.

When for example Construction companies have credit with their providers, they usually go to the provider, select the materials they need, load them on a truck and deliver them onto a site, subsequently taking the purchase invoice to the back office.

As of now, there is an _On Credit Sales Order_,  which is defined as follows: the DocType _Sales Order_: this DocType has as DocBaseType _Sales Order_ and as SubType _On Credit Order_. 
Additionally, it has DocTypes for invoice and for shipment.
Behind the scenes, ADempiere takes care of completions and processings.

The same would apply to Purchase Orders: the DocType _Purchase Order Credit_ would have as DocBaseType _Purchase Order_ and as SubType _On Credit Order_. 
Additionally, it would have DocTypes for invoice and for shipment as the company would need them.
Analog to sales, ADempiere would take care behind the scenes of completions and processings.

The implementation would require an additional document type and a change in MOrder.completeit(). The latter for not completing a Purchase Invoice.

Image of doucment type:
![20180509_po_01](https://user-images.githubusercontent.com/1789408/39819980-f62fe3b6-5361-11e8-9785-7254e487ac2c.png)

Image of Purchase Order:
![20180509_po_02](https://user-images.githubusercontent.com/1789408/39819981-f6317fc8-5361-11e8-8311-3e5a46cd3841.png)

By clicking on the icon _Where Used_ the related documents (Purchase Invoice and Material Receipt) would be displayed.

**Comments and suggestions welcome**.

**Comment by e-Evolution** [comment]
Hello @marcalwestf  Mario!

The functionality is really feasible, even for Warehouse Order Type, if you want to enable will be convenient to do for all suborder type.

What you have to verify are the processes for PO Match and Invoice Match, on the other hand, the processes of cancellation or reversal of each of the documents, so that they work as they do now, if this works together with the cost implications, I do not see any restriction to implement this functionality.

I understand that you would have to modify the display rules in the document type window so that you can select the order subtypes.

It is not necessary to mention that the changes must be proven intensively guaranteeing not to damage the current operation in the sales orders.

Other approach is create process action into the Purchase Order to generate material receipt or invoice, so the user can call the process action vs complete of document. this functionality can work for any purchase order type.

kind regards

**Comment by adaxa-steven** [comment]
Hi Mario,
sounds like a good improvement.

Can I add for later consideration 
(1) where the goods are paid for by credit card we have the equivalent of a POS Order with payment from a 'credit card bank account'.

(2) and while making changes to Order document types and behaviour ... in a new site we usually import say 2 years sales history using an order type of 'Sales History Order' which is a clone of non-binding offer.  We then set the Deliv qty and Invoiced qty to same as Order qty and close the order... this lets people easily see what was sold in the past but has no accounting effect.   We also do the same with importing Purchases History and in standard adempiere there is no equivalent to the non-binding offer in the purchases context but it would be easy to add if others want to use the same approach to importing purchases history.  For accuracy we create the import of the history from their old system's sales and purchases invoices and then import them as orders.

regards
steven

**Comment by marcalwestf** [comment]
@e-Evolution , @adaxa-steven : thanks Victor and Steven for your comments.
We will discuss and consider them.

Mario

**Comment by marcalwestf** [comment]
Hi ,
I imagine a workflow as follows when the action _Complete_ in _Purchase Order_ is selected:
- Complete the _Purchase Order_
- Create and complete a _Material Receipt_
- Create a _Vendor Invoice_ in _Drafted_ mode

According to this workflow the Vendor Invoice can be modified and eventually completed; this allows for changes in prices between the vendor price list in Adempiere and the actual price from the vendor.

The workflow suits well situations when a company has credit by a material provider. 

Thus, when the company detects a material requirement, checks (or perhaps not!) prices and sends a driver to the provider with a list of items to buy. The driver presents the list, gets the material as well as a printed invoice and he delivers the material at a site which is not the back office where the invoice is typed in.

At the site location (in Adempiere a virtual warehouse) the Purchase Order is created and completed,  based on the materials received. According to the above workflow,  the Material Receipt is created + completed and the Invoice is created as drafted. 

Later at the back office, the purchase manager checks the products and quantities received (in the Purchase Order and Material Receipt documents) and also the prices in the Invoice. In case of price differences, the Purchase Invoice prices are changed manually so they match the actual invoice from the vendor.

Adempiere corrects automatically any price difference betweeen Order and Invoice, so the costs are safely calculated.

The workflow described applies also well for cases when the driver si sent either with money or check to the provider. In such cases, the workflow helps by minimizing the documents to be handled.

**Comment by MarianaGallardo** [comment]
When the purchase order is canceled, reception is not canceled and the invoice is not canceled either. However, the invoice message is shown in the description, but in the document status it remains "in process".

**Comment by marcalwestf** [comment]
good catch @MarianaGallardo .
As I understand, the Voiding action for both Material Receipt and Invoice done "On Credit" have to be developed.
