### ISSUE TITLE
Add support view for Bank Statement Reconciliate

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#1699]
Is nice to have a view for match of payment imported with ADempiere bank movements. It allows compare both movements and reconciliate automatically

**Comment by e-Evolution** [comment]
@yamelsenih , an image say more that 1000 words , would you send  a GIF animate to know how work ?

This a my example that I made for fixed asset addition https://user-images.githubusercontent.com/786968/38830425-df8b7ffe-4181-11e8-9c15-e6aedc241ea2.gif 

her can check some option know generate un gif animation.

https://about.gitlab.com/handbook/product/making-gifs/#all-in-one

**Comment by yamelsenih** [comment]
Yes, i will do, you can see it here: https://github.com/adempiere/adempiere/projects/22
Also it is a preview:
![screenshot_20180606_185900](https://user-images.githubusercontent.com/2333092/41069406-5e9880a4-69b3-11e8-8914-f369c575dd95.png)

**Comment by wdtz** [comment]
Hello @yamelsenih , I think it convenient to make a change, the definition of the following points of interest for functional tests:
Benefit of Change
Previous operation procedure
New operation procedure (Change)

In this way, it will be easier to understand the proposed change, thus giving an opportunity to give an opinion and evaluate its optimal functioning.

The link offered does not provide relevant information for the change, the instructions do not match the change: http://wiki.adempiere.net/Sponsored_Development:_Automatic_Bank_Reconciliation
