### ISSUE TITLE
Add Quicken Interchange Format support

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#1700]
Currently does not exist a Loader Bank Statement for read [QIF format](https://en.wikipedia.org/wiki/Quicken_Interchange_Format), it is a standard format for some banks, is nice to have it for loader import

**Comment by e-Evolution** [comment]
@yamelsenih I agree that support more standard.

So I undestand that it a way to load the import statement document  or directly in bank statement ?

**Comment by yamelsenih** [comment]
Yes, it format is a standard, also exist:
- OFX (Open Financial Exchange): Created by Microsoft, https://en.wikipedia.org/wiki/Open_Financial_Exchange
- QIF (Quicken Interchange Format): https://en.wikipedia.org/wiki/Quicken_Interchange_Format
- MT940: used for swift transaction, https://en.wikipedia.org/wiki/MT940

With it change you can download a bank statement from your bank on format (OFX, QIF and MT940) and it can be upload to ADempiere from Load Bank Stract process

**Comment by yamelsenih** [comment]
Currently ADempiere only support OFX format for it
