### ISSUE TITLE
Enhancement new Fixed Asset Balance report and smart browser.

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#1704]
Current fixed asset have not a report and smart browser Fixed Asset balance

**Comment by e-Evolution** [comment]
New Fixed Asset Balance

<img width="1919" alt="image" src="https://user-images.githubusercontent.com/786968/40562083-2bae629a-6025-11e8-89c2-3af487f0c21c.png">

**Comment by yamelsenih** [comment]
Merged
