### ISSUE TITLE
Info window could not override to Search field.

### ISSUE THREAD

**Issue by ayazbaloch** [adempiere/adempiere#1707]
Dear @yamelsenih  and @e-Evolution,
In Adempiere Info Window could not override to search filed of custom info window.
I noticed in Idempiere and Adaxa Adempiere has same fields for Info Window while Adempiere has not, kindly see Images of Adempiere and Adaxa Adempiere.

Adempiere Image

![image](https://user-images.githubusercontent.com/10656336/40700720-2b62f2ce-63f4-11e8-8ac6-dcfef5579e62.png)

Adaxa Adempiere

![image](https://user-images.githubusercontent.com/10656336/40700983-8773fb3e-63f5-11e8-9949-6e1fb9c79b7c.png)

And in Idempiere see below link for more detail for Custom Info Windows.

http://wiki.idempiere.org/en/Developing_Plug-Ins_-_Custom_Info_Windows

**Comment by e-Evolution** [comment]
Dear @ayazbaloch, the Custom Info Windows was deprecated in ADempiere, we have the Smart Browser that allows build browser with features more power than other plugins.

- Allow reuse the view
- Allow update value directly
- Allow deleting multiples records based on multi-selection
- Allow export record Excel 
- Allow use callout for each cell of grid fields
- Allow define multiples filters and field query display
- Allow zoom for multi-selection based on field key.

kind regards

**Comment by ayazbaloch** [comment]
Dear @e-Evolution,

Could you help me how to assign custom Smart Browser to search field? It is highly appreciated.

**Comment by ayazbaloch** [comment]
Dear @e-Evolution,

Is it possible to assign custom smart Brows to Search field? if yes then how it will be done.
