### ISSUE TITLE
Enhancement Payroll causing lock record when execute prepare Payroll process

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#1708]
When a Payroll process is completed this executing the workflow step fro this document, first prepare it document and continue to complete, when the complete step is executed, the record never is released.

**Comment by yamelsenih** [comment]
Hi @e-Evolution it is a bug introduced with 3.9.0 release

**Comment by e-Evolution** [comment]
@yamelsenih , I am reviewing all code of Payroll and unfortunately there are many poorly defined methods given that a static method must always receive as parameter the context and name of the transaction, so change it as improvement and fix the theme of the methods based on the best practice even if it is a bit painful, I will use this improvement to solve this issue.
