### ISSUE TITLE
Bug fix error to export Jasper Report to Excel

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#1712]
currently, any Jasper Report generated when trying export to Excel get this error:

===========> zkoss.handleError:1130: >>org.adempiere.exceptions.AdempiereException: Failed to render report
>>net.sf.jasperreports.engine.JRException: The cell cannot be added.
>>java.lang.NoSuchMethodError: org.apache.poi.hssf.usermodel.HSSFClientAnchor.setAnchorType(I)V
>>	at net.sf.jasperreports.engine.export.JRXlsExporter.exportImage(JRXlsExporter.java:1540)
>>	at net.sf.jasperreports.engine.export.JRXlsAbstractExporter.exportPage(JRXlsAbstractExporter.java:1059)
>>	at net.sf.jasperreports.engine.export.JRXlsAbstractExporter.exportReportToStream(JRXlsAbstractExporter.java:837)
>>	at net.sf.jasperreports.engine.export.JRXlsAbstractExporter.exportReport(JRXlsAbstractExporter.java:687)
>>	at org.adempiere.webui.window.ZkJRViewer.renderReport(ZkJRViewer.java:191)
>>	at org.adempiere.webui.window.ZkJRViewer.cmd_render(ZkJRViewer.java:295)
>>... [40]

**Comment by e-Evolution** [comment]
The error is caused by incompatibility of library version between jasper report and poi library and was introducing in 5c51177

**Comment by yamelsenih** [comment]
Merged
