### ISSUE TITLE
Create from Order/RMA (Material receipt) Not working

### ISSUE THREAD

**Issue by icdewar** [adempiere/adempiere#1719]
ERROR [STDERR] ===========> zkoss.handleError:1130: >>java.lang.NullPointerException
>>      at org.adempiere.controller.SmallViewController.createVO(SmallViewController.java:451)
>>      at org.adempiere.controller.SmallViewController.createField(SmallViewController.java:379)
>>      at org.eevolution.grid.BrowserSearch.loadData(BrowserSearch.java:115)
>>      at org.adempiere.controller.SmallViewController.init(SmallViewController.java:164)
>>      at org.eevolution.form.WBrowser.statInit(WBrowser.java:205)
>>      at org.eevolution.form.WBrowser.init(WBrowser.java:187)

**Comment by yamelsenih** [comment]
Fixed
