### ISSUE TITLE
How to assign Browse Windows to search field.

### ISSUE THREAD

**Issue by ayazbaloch** [adempiere/adempiere#1720]
Dear All,

How to assign my custom Browse Windows to Search field. While Info Window is deprecated from adempiere.

My last issue is https://github.com/adempiere/adempiere/issues/1707

**Comment by yamelsenih** [comment]
Hi @ayasbaloch it is not possible currently we can add it new functionality

**Comment by e-Evolution** [comment]
Dear @ayazbaloch , you would implement your own view using InfoFactoryClass and be placing this class in the column in the tables that require this behavior.

More detail here
http://wiki.adempiere.net/Info_Class_Factory

**Comment by ayazbaloch** [comment]
Thanks to @yamelsenih and @e-Evolution for your prompt responses.
