### ISSUE TITLE
Deleted recent items causes NPE (only in Swing)

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere#1741]
When for one reason or another, there is an entry in Recent Items (table AD_RecentItem) which points to a non-existing record, an NPE is generated when during the construction of the Recent Items Tree.

Example: in the recent items table there is a Record (ID==1000044) for table M_Product (ID==208).
![20180612_quicksheet_01](https://user-images.githubusercontent.com/1789408/41282388-2db48f04-6df1-11e8-939b-c79d1989b27f.png)

Unluckily, in the M_Product table, there's no record with this ID (1000044)
![20180612_quicksheet_02](https://user-images.githubusercontent.com/1789408/41282411-3c49e30c-6df1-11e8-84d4-5e459c385728.png)

This leads to a NPE:

> ADempiere starting: org.compiere.apps.AMenu - java.lang.NullPointerException
> java.lang.NullPointerException
>         at org.compiere.model.MRecentItem.lambda$getLabel$0(MRecentItem.java:410)
>         at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
>         at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:352)
>         at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
>         at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
>         at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
>         at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
>         at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
>         at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
>         at org.compiere.model.MRecentItem.getLabel(MRecentItem.java:412)
>         at org.compiere.grid.tree.VTreePanel.addToBar(VTreePanel.java:1051)
>         at org.compiere.grid.tree.VTreePanel.initTree(VTreePanel.java:349)
>         at org.compiere.apps.AMenu.<init>(AMenu.java:164)

**The only way to solve it right now is by deleting the Recent item entry, which is first difficult to find out. Moreover, Adempiere doesn't even start!**

The reason: in the class MRecentItem, the instantiation of the MProduct with the ID yields -as expected- a null object:
![20180612_quicksheet_03](https://user-images.githubusercontent.com/1789408/41282766-229afd82-6df2-11e8-9af6-da9e6b596509.png)

The solution:  in the class MRecentItem, catch the null object:
![20180612_quicksheet_04](https://user-images.githubusercontent.com/1789408/41283741-9f2c5f56-6df4-11e8-8bc3-14c0957f27a1.png)

... and also in VTreePanel ()
![20180612_quicksheet_05](https://user-images.githubusercontent.com/1789408/41283638-56274050-6df4-11e8-9320-d35b41230e10.png)

In class DPRecentItems this situation was already solved, thus in ZK this bug doesn't pop up:
![20180612_quicksheet_06](https://user-images.githubusercontent.com/1789408/41283539-1693835e-6df4-11e8-991c-2afbfda7bd8d.png)

**Comment by yamelsenih** [comment]
Hi Mario. I remember that it issue was resolved yet. Let me find the issue

**Comment by marcalwestf** [comment]
ahhh ok thanks.
I was testing the Quick Sheet functionality from the _branch feature/#1088_Quichsheet_Functionality_ of repository _https://github.com/erpcya/adempiere_ .

It was created a couple of months ago, and I supposed that it would have the latest changes, which it has not. It is a direct branch of Adempeiere 3.9.0; the bug fixes since release haven't been applied.

So it is important when a development takes long to merge regularly to avoid these "false negatives".

Thanks again for pointing to it.

**Comment by marcalwestf** [comment]
...looking closer at it, I see that the bug fix in https://github.com/adempiere/adempiere/issues/1426 (https://github.com/adempiere/adempiere/commit/824e0f06560218db67371f339f91b3327cfe1167) concerns only MRecentItem, but not VTreePanel ().

I wonder what happens then in Swing: an empty entry for a non-existent record? I'm afraid so.
I will test it. 
If there is an empty entry for a non-existent record, it will have to be corrected.

In the meanwhile I will let the issu open.

**Comment by marcalwestf** [comment]
tested with the changes from https://github.com/adempiere/adempiere/commit/824e0f06560218db67371f339f91b3327cfe1167 .

The result is as I supposed: an empty entry in the recent items:
![20180612_quicksheet_07](https://user-images.githubusercontent.com/1789408/41313092-327c459a-6e46-11e8-80a8-747fa40bf8c5.png)

Clicking it displays an empty window (at least not an NPE!), but it is nevertheless an error.
It has to be caught In VTreePanel.

**Comment by marcalwestf** [comment]
.... I think that  in the class MRecentItem instead of
![20180612_quicksheet_08](https://user-images.githubusercontent.com/1789408/41313685-d22e32b4-6e47-11e8-92b3-89cf910a9df5.png)

it should be
![20180612_quicksheet_09](https://user-images.githubusercontent.com/1789408/41313721-e9cffb6e-6e47-11e8-91c0-a8389f55acf3.png)

... what do you think?
