### ISSUE TITLE
Error in process creating periods in operational calendar

### ISSUE THREAD

**Issue by wdtz** [adempiere/adempiere#1755]
When executing the process from the period definition (See Image), the names of the period created is: 01/00/2018
![image](https://user-images.githubusercontent.com/9578152/41315427-76683e32-6e5d-11e8-9eaf-9a806c7fae6a.png)

**Ideal operation:** Should take the name of the dates of the period, example (01/01/2018 to 01/31/2018)

**Comment by marcalwestf** [comment]
hi Waditza,
perhaps not an error, but an improvement in notation?

On the other hand, when you define a period from July 1st to July 31st, you think it is for the whole month of July. Thus perhaps the correct name would be in such cases **07/2018**.

But maybe there are so many possibilities and combinations there is no single valid notation....

**Comment by adaxa-steven** [comment]
Notation does vary. We would set as 2018-07 so the period name sorts in excel. In AU the common financial year end is 30 June. One client sets July 2018 as period 2019-01... Ie 1st reporting period of FY 2019.

**Comment by mckayERP** [comment]
Perhaps add a format to the calendar to define the default period name?  In Steven's case it would be hard coded a bit "2019-MM" or more generally "yyyy-MM".

**Comment by yamelsenih** [comment]
Hi, I think that it can be resolved adding format pattern to date by language

**Comment by yamelsenih** [comment]
This process already have format pattern to name of period
