### ISSUE TITLE
Add option to restore the password from the login

### ISSUE THREAD

**Issue by Raul-mz** [adempiere/adempiere#1769]
Currently in adempiere if you forget the password you can not access

**Comment by yamelsenih** [comment]
Is nice to have a token for send to user and verify before authenticate.

1. You can request:
     - User (AD_User.Value)
     - Mail (AD_User.EMail)
2. Validate match with user and email
3. After it can generate a token and sent it to user mail (Can be a url for to ADempiere server)
4. Opening ADempiere:
     - User can get from URL parameter
     - Token also can be add from url parameter
     - Request new password
     - Confirm password.
     - Login
     - Send a mail and notify that user password was changed

**Comment by yamelsenih** [comment]
please continue discussion here: https://github.com/adempiere/adempiere/pull/1850

**Comment by marcalwestf** [comment]
Started testing this pull request
1.- Question: is this enhancement is only available for ZK?
2.- XMLs could be applied without problem. The login displays a new area (**Forgot password?**) that when clicked offers a dialog for entering the user whose password is to be restored:
![20180803_restore_password_01](https://user-images.githubusercontent.com/1789408/43681517-ecdd75e4-9812-11e8-96dc-b23153237b63.png)
![20180803_restore_password_setup_email_05](https://user-images.githubusercontent.com/1789408/43681535-8c990fbc-9813-11e8-8b9f-1f8dbf872b5e.png)

3.- Small Changes to be done: 
a) modify the XML file names to catch up with the latest sequence committed in trunk.
b) Modify accordingly the sequence in the files.
c) Set in XML files field ReleaseNo to "3.9.1"

**Comment by marcalwestf** [comment]
...continuig with the test...
when I write the name of the user (in my case SuperUser) I got an exception:
![20180803_restore_password_setup_email_07](https://user-images.githubusercontent.com/1789408/43681577-683c93b8-9814-11e8-9f22-d98ecfe68a87.png)

though I set up the Client and Email configuration window; I also put for the SuperUser an email.
There is an additional step to be done?

**Comment by marcalwestf** [comment]
this is the error I get from the server:

```
19:25:28,404 ERROR [STDERR] ===========> MSequence.getNextID: No record found - AD_Token [59]
19:25:28,451 ERROR [STDERR] ===========> MSequence.getNextID: No record found - AD_Token [59]
19:25:28,452 ERROR [STDERR] ===========> MToken.saveNew: No NextID (-1) [59]
19:25:28,492 ERROR [STDERR] ===========> MToken.saveNew: No NextID (-1) [59]
19:25:28,501 ERROR [STDERR] -----------> EMail.isValid: SMTP Host is invalidnull [59]
19:25:28,501 ERROR [STDERR] -----------> EMail.isValid: SMTP Host is invalidnull [59]

```


... and in AD_Sequence there is no entry for AD_Token
![20180808_restore_password_setup_email_06](https://user-images.githubusercontent.com/1789408/43873529-196860a4-9b44-11e8-94da-5f8fc31209ed.png)

**Comment by e-Evolution** [comment]
Hi @Raul-mz @yamelsenih I am try request forgot password from Swing , but no can found this option.

What is the procedure for Swing version ?

**Comment by yamelsenih** [comment]
Hi All, i will to describe Step by Step on my site:

 - Import XML
 - Create a new config and test it for client:
![screenshot_20181001_233236](https://user-images.githubusercontent.com/2333092/46328187-634fb080-c5cb-11e8-8410-8a8a0331bfd1.png)
 - Note that exist a Email Template for Reset password now:
![screenshot_20181001_233126](https://user-images.githubusercontent.com/2333092/46328166-3ef3d400-c5cb-11e8-9801-812c71dab3e3.png)
 - Add EMail for my user (SuperUser) 
![screenshot_20181001_234348](https://user-images.githubusercontent.com/2333092/46328205-8d08d780-c5cb-11e8-8d74-cd000f9474d8.png)
 - Run ADempiere Server
 - Go to Login and press **Forgot Password?**
![screenshot_20180930_174343](https://user-images.githubusercontent.com/2333092/46328222-add12d00-c5cb-11e8-894f-d2d807bd2301.png)
 - Put muy user value **SuperUser** 
![screenshot_20181001_233505](https://user-images.githubusercontent.com/2333092/46328260-f25cc880-c5cb-11e8-917b-6cb6a9559cb7.png)
 - Go to my EMail: 
![screenshot_20181001_233533](https://user-images.githubusercontent.com/2333092/46328276-01437b00-c5cc-11e8-8067-e59e806303bd.png)
 - Press Token buton: 
![screenshot_20181001_233546](https://user-images.githubusercontent.com/2333092/46328290-10c2c400-c5cc-11e8-8b17-06dd779a7c78.png)
 - Set my new Password and automatically is loaded **Role Panel** 
![screenshot_20181001_233558](https://user-images.githubusercontent.com/2333092/46328306-289a4800-c5cc-11e8-95f3-37f656587ad3.png)
![screenshot_20181001_233610](https://user-images.githubusercontent.com/2333092/46328317-30f28300-c5cc-11e8-905a-ea3d911a65b0.png)

Note: you can add **Token Definition** and **Token** window to role for view generated token or change **Token Generator** class

![screenshot_20181001_233635](https://user-images.githubusercontent.com/2333092/46328354-731bc480-c5cc-11e8-99de-54b805dcd5be.png)
