### ISSUE TITLE
Auto Location for tree

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#1770]
Is nice to have a automatic location for item of tree when a new item is added, it is very usefull for Element Value and Activity or cost center, example:

I want add a new account 1.1.03 to tree for element value where exist 1.1 folder created

- 1.1
  - 1.1.01
  - 1.1.02

Now the process is:
 - Add account 1.1.03
 - Go to tree and set new location for new element

Proposal:
 - Add account 1.1.03 (Automatically is added into 1.1 folder)

- 1.1
  - 1.1.01
  - 1.1.02
  - <New Item with 1.1.03 value>

**Comment by yamelsenih** [comment]
@carlosaparadam see it

**Comment by e-Evolution** [comment]
@yamelsenih @carlosaparadam have you some update this feature?

**Comment by yamelsenih** [comment]
Yes, already exists a pull request for it. Let me find it

**Comment by carlosaparadam** [comment]
hi @e-Evolution @yamelsenih this is the pull request https://github.com/adempiere/adempiere/pull/2643

**Comment by e-Evolution** [comment]
@carlosaparadam thank you to documented
