### ISSUE TITLE
Cannot complete Planned Manufacturing Order with Movement Date in the future

### ISSUE THREAD

**Issue by homebeaver** [adempiere/adempiere#1782]
in our Accounting schema `Future Days` is defined to 0. This is OK.

I create a new `Planned Manufacturing Order` and set `Movement Date` to `DatePromised` which is in the future. Also this is OK in my opinion.

Now I cannot complete the Document!

![grafik](https://user-images.githubusercontent.com/3493126/41656004-ea8e33c0-748e-11e8-926e-7592babd89bb.png)

You can reproduce it in swing or in a programm:
```java
		MProductionBatch mProductionBatch = new MProductionBatch(getCtx(), 0, get_TrxName());
		
		mProductionBatch.setC_DocType_ID(DOCBASETYPE_MPO_ID); 
		mProductionBatch.setM_Product_ID(mProduct.getM_Product_ID());
		
		mProductionBatch.setMovementDate(this.mOrder.getDatePromised());
...
		mProductionBatch.completeIt();	// <<====== PeriodClosedException
```

**Comment by e-Evolution** [comment]
@homebeaver please , in future use the our convention ion to commits messages:

#Issue Description of Issue URL of issue 

<img width="1263" alt="image" src="https://user-images.githubusercontent.com/786968/44948580-c93af380-ade5-11e8-9fb4-8ec27b14920d.png">
