### ISSUE TITLE
error checking of return msg of groovy ScriptProcess 

### ISSUE THREAD

**Issue by homebeaver** [adempiere/adempiere#1792]
in `ProcessUtil` it checks only for "@Error@" - no further Information can be send to the user. 
Better:

```java
			if (msg!=null && msg.startsWith("@Error@"))
				success = false;
```
will display a summary error msg in red:

![grafik](https://user-images.githubusercontent.com/3493126/42209213-68788a82-7eae-11e8-8ca8-75b8756295df.png)

**Comment by yamelsenih** [comment]
Hi @homebeaver  exists a pull request for it?

please add a pull request for complement it issue

**Comment by homebeaver** [comment]
pull #1822 was merged on 26 Jul 2018 by @yamelsenih 

So I close this issue
