### ISSUE TITLE
Create new menu to Service Management

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#1794]
Currently the functionality of services and resource management is in a sub-menu of business partner, since functionality is added to the management of services a new menu is necessary.

**Comment by e-Evolution** [comment]
<img width="432" alt="captura de pantalla 2018-07-03 a la s 14 05 49" src="https://user-images.githubusercontent.com/786968/42239712-5bc987ca-7eca-11e8-8128-e4b36e45f4e4.png">

**Comment by yamelsenih** [comment]
Hi @e-Evolution  exists a pull request for it?

please add a pull request for complement it issue

**Comment by e-Evolution** [comment]
![image](https://user-images.githubusercontent.com/786968/77593833-86a2a580-6eba-11ea-864a-4574fa5883ce.png)
