### ISSUE TITLE
New Window for Service Type

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#1796]
This window allows you to define the type of service for a service.

<img width="1620" alt="image" src="https://user-images.githubusercontent.com/786968/42250809-31647c68-7ef9-11e8-9ec6-e775c6ffa3bc.png">

<img width="1619" alt="image" src="https://user-images.githubusercontent.com/786968/42251199-777410b8-7efb-11e8-93eb-c79f01c4e4cf.png">

**Comment by yamelsenih** [comment]
Hi @e-Evolution  exists a pull request for it?

please add a pull request for complement it issue
