### ISSUE TITLE
Create Service Price Window

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#1797]
New Window for Service Price Window  allows you to generate service price lists for your Business Partners.

<img width="1634" alt="image" src="https://user-images.githubusercontent.com/786968/42252155-cfb9d06e-7f00-11e8-8041-ba9889b09322.png">

<img width="1622" alt="image" src="https://user-images.githubusercontent.com/786968/42252136-c08f623e-7f00-11e8-8166-98b716b47fec.png">

**Comment by yamelsenih** [comment]
Hi @e-Evolution  exists a pull request for it?

please add a pull request for complement it issue
