### ISSUE TITLE
Bug fix Error when try validate quantity vs  debit or credit signum

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#1801]
Error to import budget  when try validate quantity vs  debit or credit signum, Credit Line must have negative qty and Debit line must have positive qty.

**Comment by adaxa-steven** [comment]
Hi Victor.
I thought we fixed this before. I am assuming you are saying if the amount is a credit and entered as a negative number inthe budget import then a credit qty should also be abnegation number?
