### ISSUE TITLE
Class not repiclated

### ISSUE THREAD

**Issue by andmendescosta** [adempiere/adempiere#181]
I changed the class "ReportStarter.java" but after build gererator the changes they where not replicated from my web application.

I try change the class in adempiere380 and generate a build, and change in my project the adempiere380 below applying an customization.jar generated from a build.

Anyway preserves the imprementation existing in AdempiereOriginal.jar.

**Comment by yamelsenih** [comment]
Hi @andmendescosta you can proveed more details about it?

Best Regards

**Comment by marcalwestf** [comment]
@andmendescosta can you please elaborate the case? Or if you solved it, document how you did it?
We're trying to clean up issues before the release.
Thanks a lot.

**Comment by yamelsenih** [comment]
No test case, I will to close this issue
