### ISSUE TITLE
Error In Transaction Detail Report after enabling cost centers in adempiere

### ISSUE THREAD

**Issue by Mbilalilyas** [adempiere/adempiere#182]
===========> MLookupFactory.getLookup_TableDirEmbed: No Identifier records found: User1_ID [13]
===========> MLookupFactory.getLookup_TableDirEmbed: No Identifier records found: User2_ID [13]

**Comment by yamelsenih** [comment]
Hi @Mbilalilyas this is caused by the bad reference in column of view

**Comment by Mbilalilyas** [comment]
you mean i have to change the reference in the view

**Comment by yamelsenih** [comment]
this change must be created with migration xml

**Comment by Mbilalilyas** [comment]
yes this should also be updated in repository
