### ISSUE TITLE
Add back compatibility for aggregate payroll methods 

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#1833]
Before all aggregate payroll methods return sum or average for all payroll movement.
Now is possible get the payroll movements processed or not processed.

bug introducing #771

**Comment by yamelsenih** [comment]
Hi @e-Evolution a voided payroll process is processed and it can have amounts that add to sum, i think that getSum and getAvg only should get completed and closed process, if you want get values from current payroll you can user getConcept + getConceptSum

It
<pre>
AND EXISTS (SELECT 1 FROM HR_Process p  
			INNER JOIN HR_Period pr ON (pr.HR_Period_id=p.HR_Period_ID)
			WHERE HR_Movement.HR_Process_ID = p.HR_Process_ID
			AND p.HR_Payroll_ID=?)
</pre>

Was a bug resolved, all documents with workflow must be validate with document status instead process flag.

Best regard

**Comment by yamelsenih** [comment]
maybe your have it bug:

<pre>
		//check process and payroll
		whereClause.append(" AND EXISTS (SELECT 1 FROM HR_Process p"
							+" WHERE HR_Movement.HR_Process_ID = p.HR_Process_ID" 
							+" AND " + (includeInProcess? "p.DocStatus IN('CO', 'CL')": "p.DocStatus IN('IP', 'CO', 'CL')")
							+" AND p.HR_Payroll_ID=?");
</pre>

instead it code:
<pre>
		whereClause.append(" AND EXISTS (SELECT 1 FROM HR_Process p"
				+" INNER JOIN HR_Period pr ON (pr.HR_Period_id=p.HR_Period_ID)"
				+" WHERE HR_Movement.HR_Process_ID = p.HR_Process_ID" 
				+" AND " + (includeInProcess? "p.DocStatus IN('CO', 'CL')": "p.DocStatus IN('DR', 'IP', 'CO', 'CL')")
				+" AND p.HR_Payroll_ID=?");
</pre>

**Comment by yamelsenih** [comment]
Hi @e-Evolution here is a little change with fix of it: https://github.com/adempiere/adempiere/pull/1835
