### ISSUE TITLE
HR Attendance: Define E-R Model

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#1834]
Is nice to have a ER model with a scope of changes that will be part of Time & Attendance Record

**Comment by yamelsenih** [comment]
Here a ER diagram for proposal
![time-and-attendance](https://user-images.githubusercontent.com/2333092/43181237-b7b0c1ce-8fa1-11e8-91d3-d77e5bc4f758.png)

**Comment by ayazbaloch** [comment]
Please make provision for bio-matrix data importing.

**Comment by yamelsenih** [comment]
Hi @ayazbaloch have you any information about it? Please give me more info for evaluate

**Comment by yamelsenih** [comment]
Hi @ayazbaloch have you any info?

**Comment by ayazbaloch** [comment]
Dear @yamelsenih, there is no ISO data format for pulling Biometric data. Each vendor has own data format of biometric device, I have a device his sample format is given below. And see log table schema also given in last of given data.

USERID | CHECKTIME | CHECKTYPE | VERIFYCODE | SENSORID | Memoinfo | WorkCode | sn | UserExtFmt
4 | 6/27/16 9:26 AM | i | 1 | 1 |   | 0 | 3485154901201 | 0
4 | 6/27/16   5:26 PM | i | 1 | 1 |   | 0 | 3485154901201 | 0
4 | 6/28/16   8:33 AM | I | 1 | 1 |   | 0 | 3485154901201 | 0
4 | 6/28/16   5:31 PM | O | 1 | 1 |   | 0 | 3485154901201 | 0
4 | 6/30/16   9:23 AM | I | 1 | 1 |   | 0 | 3485154901201 | 0
4 | 6/30/16   4:18 PM | O | 1 | 1 |   | 0 | 3485154901201 | 0
4 | 7/1/16   9:18 AM | i | 1 | 1 |   | 0 | 3485154901201 | 0
4 | 7/1/16   5:33 PM | O | 1 | 1 |   | 0 | 3485154901201 | 0
4 | 7/13/16   8:50 AM | I | 1 | 1 |   | 0 | 3485154901201 | 0
4 | 7/13/16   5:36 PM | O | 1 | 1 |   | 0 | 3485154901201 | 0
4 | 7/14/16   11:52 AM | I | 1 | 1 |   | 0 | 3485154901201 | 0
4 | 7/14/16   5:38 PM | O | 1 | 1 |   | 0 | 3485154901201 | 0


Table:- CheckInOut
Fields        Data Type
-----------------------
USERID            Number
CHECKTIME     Date/Time
CHECKTYPE     Text
VERIFYCODE    Number
SENSORID       Text
Memoinfo       Text
WorkCode       Text
sn                    Text
UserExtFmt     Number


Note: In CHECKTYPE values I---->IN and O--->OUT
Let me work more on it.

**Comment by ayazbaloch** [comment]
See below link, ISO is working on it.
https://www.iso.org/obp/ui/#iso:std:iso-iec:24713:-1:ed-1:v1:en

**Comment by ayazbaloch** [comment]
Hi @yamelsenih , i sent you mail, kindly check it for documentation.

**Comment by yamelsenih** [comment]
Hi @ayazbaloch is nioce your mail, i can see that AD ER-Model can be used.

See the **I_HR_Attendance** is for load all attendance from device.

We are working for improve it.

Thanks for your info, is a geat help for us
