### ISSUE TITLE
Generate Surrogate Keys

### ISSUE THREAD

**Issue by PraponAon** [adempiere/adempiere#1836]
I'm running menu "Generate Surrogate Keys" more than 18 hours, It's not finish.
(Data size 20Mb.)
![image](https://user-images.githubusercontent.com/10692888/43176870-dd3f7ce8-8fef-11e8-9180-d7fc05d0ac07.png)

***************
update with this query , Less than 2 minutes

** 1. create temporary function **

CREATE OR REPLACE FUNCTION xx_add_uuid()
  RETURNS integer AS
$BODY$ 
DECLARE
    r record;
    tbl_name varchar(255);
BEGIN
  FOR r IN 
	SELECT tb.tablename::text,co.column_name 
	FROM pg_catalog.pg_tables tb
	left join (
		select table_name, column_name
		from information_schema.columns 
		WHERE table_schema = 'adempiere' 
		  AND column_name = 'uuid'	
	) co on tb.tablename = co.table_name
	where tb.schemaname='adempiere' and co.column_name is null
	order by tb.tablename 
  LOOP
	tbl_name = r.tablename;
	-- ALTER TABLE tbl_name ADD COLUMN uuid character varying(36) DEFAULT NULL::character varying;
	EXECUTE 'ALTER TABLE '|| tbl_name ||' ADD COLUMN uuid character varying(36) DEFAULT NULL::character varying ';	
  END LOOP;
  RETURN 0;
END;
$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100;

** 2. execute funtion 
select xx_add_uuid();

** 3. test 
SELECT tb.tablename::text,co.column_name 
FROM pg_catalog.pg_tables tb
left join (
   select table_name, column_name
   from information_schema.columns 
   WHERE table_schema = 'adempiere' 
     AND column_name = 'uuid'	
  ) co on tb.tablename = co.table_name
where tb.schemaname='adempiere' and co.column_name is null
order by tb.tablename

**Comment by yamelsenih** [comment]
Hi @PraponAon is nice your proposal, but i think that you also can add a function for create **UUID**, for now the problem is generating **UUID** for all records.

**Comment by PraponAon** [comment]
I found some tables not have uuid column, the result is it can not be signed-on.
so I used it to solve this problem before.
may be not the suitable way.

**Comment by yamelsenih** [comment]
Hi, i will to generate it from Surrogate Key process, but with a little change based on your proposal.

I just will add a new function:
<pre>
generate_uuid_from_db()
</pre>

**Comment by PraponAon** [comment]
👍 thank you very much.

**Comment by yamelsenih** [comment]
Hi @PraponAon i fixed it here https://github.com/adempiere/adempiere/pull/2012 please test it. Note that it can be used for postgreSQL and Oracle.

Best Regard
