### ISSUE TITLE
hotfix002/ Apply migration script "72 - Migration resize SQLStatement " fail

### ISSUE THREAD

**Issue by taherelhossin** [adempiere/adempiere#184]
When applying migration script on clean database i got the following exception and the migration process stopped:

11:37:47.510 MigrationApply.addLog: 0 - null - null - Migration 72 - Migration resize SQLStatement - 3.8.0#002 (D) ; Step: 10; Type: AD. Application failed: org.adempiere.exceptions.DBException: java.sql.SQLException: ORA-22859: invalid modification of columns

The reason of that error is the type of the column which is "CLOB" and oracle didn't allow modification on that data type. I working on finding a solution and will commit is as soon as possible

**Comment by taherelhossin** [comment]
Please label it as a bug if you test it in your machine and get the same issue

**Comment by yamelsenih** [comment]
Hi @taherelhossin the bug is fixed? you can test it? @e-Evolution maked many fixes over Migration process.

Best Regards

**Comment by e-Evolution** [comment]
Currently the migration xml is ok, I can not replicate error
