### ISSUE TITLE
[Hotfix002] Packin Issue

### ISSUE THREAD

**Issue by tiger316** [adempiere/adempiere#185]
Issue:
When Applied packin for GL Journal Line Window after some modification like rearrange the grid columns
i got Adempiere Exception "@AD_Table_ID@ @NotFound@" from MColumn.java
in validLookup method 

Reason:
that's happened because in Gl Journal Line there is a column C_LocFrom_ID 
and when try to use validLookup method it tries to get the reference table by remove "_ID"
and it fails so table return as null 

Solutions:
1st Solution : remove 
if(table == null)
      throw new AdempiereException("@AD_Table_ID@ @NotFound@");
:smile: 

2nd Solution:
Using a ADReferenceNameValueID after failing to get the table by remove "_ID"

you can find ADReferenceNameValueID in XML e.g.
            <element AD_Element_ID="200" IsActive="true" ColumnName="C_LocFrom_ID" Description="Location that inventory was moved from" EntityType="D" Help="The Location From indicates the location that a product was moved from." Name="Location From" PrintName="Location From" FieldLength="22" PO_Description="" PO_Name="" PO_Help="" PO_PrintName="" ADReferenceNameID="Table" ADReferenceNameValueID="C_Location"/>

to apply this  you need to create getter and setter for ADReferenceNameValueID
and to set the value it needs to use index from "m_columns" so we need to add column for it in the SQL query in loadInfo method in POInfo.java
see set_value in PO.java and getColumnIndex in POInfo.java for further information

Which Solution i should go with or there is a 3rd Solution ?

**Comment by yamelsenih** [comment]
Hi @tiger316 this validation is for create a correct reference, i ask: what is the table for reference of "C_LocFrom_ID"?
If is a table with other name then you must configure the reference like table and create your custom reference.

best regards

**Comment by tiger316** [comment]
Hi yamelsenih

The "C_LocFrom_ID" is originally one of the Column of "GL_JournalLine" and "C_LocTo_ID" too
both of them refers to "C_Location" table

there is already a record in "AD_Reference" table for both of them 
again this already exist i didn't add it 

so even if there is a record, the problem will happened because the method didn't call the reference or use it anywhere
so it need to be modified to handle it 
i done some modification to handle this problem like i said in above
see "2nd Solution"

another problem the reference that already exist needs some cleansing 

Regards,

**Comment by yamelsenih** [comment]
Hi @tiger316  it is correct, the problem is by:

* For validate a table, it must be TableDir. Currently the validation include the "Search" reference.

It bug will be resolve.

Thank you @tiger316

**Comment by mckayERP** [comment]
I also have a similar problem.  There is a valid case for multiple ID
columns all pointing to the same table.  The 2nd solution - testing the
reference rather than the existence of the table name would be better.

Mike
