### ISSUE TITLE
Adempiere is not supported Date in Products Attributes.

### ISSUE THREAD

**Issue by ayazbaloch** [adempiere/adempiere#1859]
Dear Adempiere core cummunity members,
In pharmaceutical companies, date of expiry is the most critical attributes for products and products which have lots/batch expiry should be shipped as according to order of expiry date and lot no of the product's batch.

**Comment by adaxa-steven** [comment]
Hi
Is there some reason you can not use guarantee date

![image](https://user-images.githubusercontent.com/15791084/43691992-cd39fa6e-9966-11e8-8bb6-a25f7b033dd8.png)

**Comment by PraponAon** [comment]
@ayazbaloch, Did you choose a guaranteed date?
![image](https://user-images.githubusercontent.com/10692888/43692106-a47c6192-994e-11e8-8499-5801054bbabf.png)

**Comment by ayazbaloch** [comment]
Thanks for @adaxa-steven  and @PraponAon your kind and prompt response for it, let me use it against expiry date.
Could it fulfill the following scenario,
Suppose Product P has some lots# 1,2 and 3. And their expiry 31-Jan-19, 31-Oct-18 and 31-Dec-18 respectively.
Now system should pick Lot#2, Lot#3 and then Lot#1 for shipment/Issue automatically.
Is it possible? Need community help.

**Comment by adaxa-steven** [comment]
as I recall it will pick the oldest batch first ... you can test in gardenworld.

**Comment by ayazbaloch** [comment]
I tested the above mentioned scenario and it is working as per requirement.
Thanks to all participants.
