### ISSUE TITLE
Dicrect Load for Packin is ussupported

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#1861]
When a Packing is imported from Package module on Application Dictionary, it can be used for create XML  migration directly from import.

The bug is the follow:

For PO class exists a flag named isDirectLoad, it allows know when a object is created from import or not, example:

- Without direct load flag:
  - Create Table: It run a method after save for create default columns
- With direct load enabled:
  - Create Table: It not run method for create default columns because all columns will be created for import.

Currently it functionality is unsupported for packin

**Comment by yamelsenih** [comment]
Please continue discussion here: https://github.com/adempiere/adempiere/pull/1862

**Comment by marcalwestf** [comment]
...answer to my last question: it is in the code, set to "false", i.e. the default columns are created automatically,

PO.java
```
:
/** Direct load, e.g. from migration. Do not overwrite assigned ID 
with generated one, or fire triggers */
	private boolean isDirectLoad = false;
:
```
