### ISSUE TITLE
The parameter for the field of Smart Browser does not take the default value defined when this field is marked as a key.

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#1863]
Currently, any field that is marked as a key does not allow to establish a default value in a field for a parameter, window field or smart browser field.

This can be correct in a window since the keys field is usually generated by the internal id of a sequence, but for a parameter of a process or field of a smart browser it is necessary to allow a value to be set by default so that it works in a filter of the call of an Smart Browser

**Comment by yamelsenih** [comment]
Merged
