### ISSUE TITLE
NPE when try validate Model ValidationEngine

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#1867]
When you add a import model validator can not validate because launch NPE

===========> ImportProduct.process: java.lang.NullPointerException [46]
java.lang.NullPointerException
	at org.compiere.model.ModelValidationEngine.fireImportValidate(ModelValidationEngine.java:681)

**Comment by yamelsenih** [comment]
Merged here: https://github.com/adempiere/adempiere/pull/1871
