### ISSUE TITLE
Create Contract Service Entity and Window

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#1876]
The new Contract Service Allows create for multiples contracts with multiples services and periods

This new service contract window allows the recurrence of service billing, service contract management, its integrates, agreements , service types and service levels.

Service Menu
<img width="386" alt="image" src="https://user-images.githubusercontent.com/786968/44185733-db751c00-a0da-11e8-8e20-13f4fc4db96a.png">
Service Contract Window 
<img width="1876" alt="image" src="https://user-images.githubusercontent.com/786968/44185760-137c5f00-a0db-11e8-99ee-3597e6a1923a.png">

<img width="1875" alt="image" src="https://user-images.githubusercontent.com/786968/44185765-1b3c0380-a0db-11e8-8d72-b6ebaad43dbc.png">

Service Contract Members
<img width="1875" alt="image" src="https://user-images.githubusercontent.com/786968/44185898-cc429e00-a0db-11e8-9c8f-8715f1435752.png">

Service Contract Line
<img width="1879" alt="image" src="https://user-images.githubusercontent.com/786968/44185905-e11f3180-a0db-11e8-9340-2080c4fec66f.png">

<img width="1872" alt="image" src="https://user-images.githubusercontent.com/786968/44185915-f300d480-a0db-11e8-9bd4-890936536e0c.png">

Service Contract Tax
<img width="1879" alt="image" src="https://user-images.githubusercontent.com/786968/44185925-0318b400-a0dc-11e8-9e06-7b9c7705d334.png">

**Comment by adaxa-steven** [comment]
Victor, will you be posting a functional explain and screenshots?

**Comment by e-Evolution** [comment]
@adaxa-steven @eduardolopezuy @niclopup 

Please review and send your feedback, any suggestion is welcome.

kind regards
Victor

**Comment by adaxa-steven** [comment]
Thanks Victor, I see the screen shots but I have not understood the business requirement that is being solved.

**Comment by niclopup** [comment]
Great functionallity Victor! 

The only thing to add would be that I didn't find the check of "Approved" in the main window of the Service Contract.

The rest of the definitions and fields i think they are complete to manage a Service Contract! 

@adaxa-steven the idea of this functionallity was to create an entity in ADempiere where you could define all the special definitions that a Service Contract could have, those thar are mostly above all the transactions like sales orderds, requests or invoices but different than a project. We thought this could help by defining it in a different window/table.

In order of this, by having the Service Contract entity, now you can define al the conditions included in a specific contract, which has a beginning date and a end date. That has a price list that define whats services are included in the "Fee", and which ones have an special price. Aso the members thar are related to the contract itself as the type or possition of each one. 

The most important funtionallity is the possibility to set a "Contract Line" that could have a Product, Charge or a Resource Assignment with a "Frequency Definition" to be invoiced. This could help to define differents contracts with customers, making easier the automation of the invoice process of that products, mostly "Services" that are arrenged to be invoiced monthly for example.

By this way, you would never forget what lines or fees to invoice, and when there are some "Extra" services or products would be clearly to invoice them. The next thing to do would be to add an easy way to define all the extra products/services that the customer consume in a period, to identify it and to add to the invoice processor. 

This function will join also with the Expense Management funtionallity to make all the billable lines in a certein moment.

**Comment by adaxa-steven** [comment]
Hi Nicolas
Thanks for the functional description.

If the Service Contract header window is defining all the elements of a service contract and shows the start date and the end date etc, what is the Complete and Posting button on the Service Contract window for?  I would assume that we would be completing and posting multiple documents during the (say) year of the Service Contract which would all be related to that Service Contract.  What have I not understood?

**The following comment is addressed to everyone .. not Nicolas.**
The addition of this functionality is likely a very good addition to Adempiere but it also demonstrates that there now appears to be no process for a review of proposed new functionality by the Adempiere group.  Will this improvement go straight into core Adempiere without further review? Is it being added to some branch for later discussion? What is the process of consideration before adoption?

regards
Steven

**Comment by yamelsenih** [comment]
Hi @e-Evolution  exists a pull request for it?

please add a pull request for complement it issue
