### ISSUE TITLE
Link a Bank with Business Partner

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#1904]
This new functionality allows linking a bank to a business partner, to have the complete data of a bank

<img width="1621" alt="image" src="https://user-images.githubusercontent.com/786968/44240813-bee1ee00-a185-11e8-98ed-691f7a2754d2.png">

<img width="1615" alt="image" src="https://user-images.githubusercontent.com/786968/44240822-ce613700-a185-11e8-918c-c89ae402517b.png">

**Comment by adaxa-steven** [comment]
Hi Victor
If this requires that a Bank and Bank Account need to exist in the Bank window before you can store the Account Name, Bank Routing Number and Account Number before you can add it to the BP>Bank Account window and use in Payment Selection then it will break things.

What is it that you are proposing?
steven

**Comment by e-Evolution** [comment]
@adaxa-steven , The link the a Business Partner to Bank is to setting  all data for a Bank As (Trade name, Business name , Tax ID ,Bank Logo ,  Location and multiples contacts), the BP>Bank Account to kink a bank account to BP :-)

**Comment by adaxa-steven** [comment]
sorry, I dont understand what it is doing.

**Comment by yamelsenih** [comment]
I think that it can be util for link bank charges to real Bank, currently not exist a relation between **C_Bank** Bank and **C_BPartner** business partner of bank.

**Comment by yamelsenih** [comment]
For relation i think that it should be 

**C_BPartner** --------------> **C_Bank** instead of **C_Bank** -----------------------> **C_BPartner**

**Comment by e-Evolution** [comment]
@yamelsenih

Nop , the idea is when you create a bank then a business partner is create in automátic.

**Comment by marcalwestf** [comment]
Hi @all , a question to hopefully clariy things: would this enhancement ensure for example that the Bank "Money Bank" has behind it an actual Business Partner, which could be called "Money Bank" for simplicity?

As of now, the "Money Bank" exists as a Bank, but not as a Business Partner. With the changes suggested, we would have a relation between the bank as Bank and as Business Partner.

Is this explanation right?
