### ISSUE TITLE
Smart Browser "Copy Project Type Tasks into Project"  thwows exception for "GardenWorld Admin" role

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere#1924]
This issue is a follow-up of issue https://github.com/adempiere/adempiere/issues/1923.

For Project _Construction Industry_ (https://github.com/adempiere/adempiere/projects/23) the Smart Browser _Copy Project Type Tasks into Project_ was developed and committed.

The smart browser is opened, tasks are selected and a project, too. Then, the button OK is pressed to execute the underlying process. 

The result is an error message: _Cannot access Process 54093 with role: GardenWorld Admin_.
By adding the process defined in the smart browser to the role GardenWorld Admin and logging in again, the process is executed flawlessly.

I wonder why it wasn't added. 
If it this is reproducible, it should be added to the creation XML.

**Comment by carlosaparadam** [comment]
Hi @marcalwestf , i imported all xml files and run role update process for the garden admin role and i can see all options, please shared me a database with your example for revised
