### ISSUE TITLE
Mismatch Warehouse with  Organization

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere#1930]
In _Project_ window, there are mismatches between _Organization_ and _Warehouse_:
1.- Now it is not possible to select a Warehouse, because it is always _Read-only_ (read-only rule= @M_Warehouse_ID@!0).

2.- If the organization is changed, a warehouse may be saved that does not correspond to the organization if the project. For example, Organization=Fertilizer, Warehouse=Store Central.
This is usually not allowed in ADempiere.

**Suggestion**
It would be desirable that _Organization_ and _Warehouse_ behave as in _Sales Orders_: the Warehouse depends on the Organization selected and once the Warehouse has been selected and saved, it cannot be changed.

This would include to set a dynamic validation (_M_Warehouse Org_) on table C_Project, column _M_Warehouse_ID_,  set Default logic so as to display the default warehouse of the present organization and restrain of changing the warehouse once saved.

**Comment by adaxa-steven** [comment]
+1

**Comment by carlosaparadam** [comment]
hi @marcalwestf it would be set without warehouse by default and filter warehouse by organization?

this could by resolve the problem

**Comment by marcalwestf** [comment]
+1

**Comment by wdtz** [comment]
Result of the Test:
Successful
