### ISSUE TITLE
Deleting projects

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere#1931]
Right now, it is possible to delete Project Tasks and recursively Project Phases.
But, when trying to delete a newly created project (which may not even have phases and/or tasks) an error message pops up: "You cannot delete records from this file for audit reasons".

I wonder which "audit reasons" there may be when a project has just been created.

In my opinion this shouldn't work so. 
Instead, the referential integrity should apply: if the project has been referenced in other documents like Sales Orders, Invoices, Payments, Accounting Facts etc. the deletion has to be refused; otherwise it should be allowed.

If we keep it as it is implemented today, we may end with lots of unused projects which -because of "audit reasons" cannot be deleted. By the way, they can be deleted alright -directly on the database.

Comments welcome, which may eventually lead to getting rid of the constraint and ensure full referential integrity for projects, phases and tasks.

**Comment by adaxa-steven** [comment]
I vote to allow delete.

**Comment by iscapnet** [comment]
Hi, I vote to allow delete as well

**Comment by yamelsenih** [comment]
Hi +1 for it.
I think that it same behavior is present in all documents because when is created constraints automatically is generated as restricted instead Cascade.

**Comment by wdtz** [comment]
Result of the Test:
Successful

**Comment by yamelsenih** [comment]
Resolved
