### ISSUE TITLE
Unhandled exception in Swing client

### ISSUE THREAD

**Issue by AndreyMenshikov** [adempiere/adempiere#194]
Hello!

Sometime, in Swing client the unhadled exception occurs in logoff process.
It occurs when client installed from binary files and when client built from Git.

[exception.txt](https://github.com/adempiere/adempiere/files/108210/exception.txt)
[sysinfo.txt](https://github.com/adempiere/adempiere/files/108211/sysinfo.txt)

Best regards
Andrey Menshikov

**Comment by e-Evolution** [comment]
Hi would set here java trace log please

**Comment by yamelsenih** [comment]
No info, I will to close it
