### ISSUE TITLE
Add CSV as report output type

### ISSUE THREAD

**Issue by adaxa-steven** [adempiere/adempiere#1953]
Adaxa made a change to the report output choice so that you could preselect CSV in addition to excel, html and pdf.

It let large reports of order detail and accounting fact run in half the time of excel reports and reduced the times when no report was produced due to various memory(?)  issues.  

I don't think it affects anything else.  If you think it worth adding we can provide the changes.

Regards 
Steven

**Comment by marcalwestf** [comment]
... getting the classes and XML files from Adaxa to start testing....

**Comment by marcalwestf** [comment]
@adaxa-steven  Steven, could you check if the title corresponds to the code changes?
As I see in the commit, it is added an additional export format "CSV", but it is not set to become the default instead of PDF.

Changes seem otherwise OK, I will add the Reflist translation and test.

**Comment by adaxa-steven** [comment]
"but it is not set to become the default instead of PDF"
I dont think w set it as a selectable default, just another option in the dropdown that you can pre-select before running the report.
