### ISSUE TITLE
When changing the planned amount in the Phase or task, do not recalculate the Task Line

### ISSUE THREAD

**Issue by wdtz** [adempiere/adempiere#1958]
When you change the quantity in the phase or task and execute the process "Create line from product LDM", an error occurs indicating that the bill of materials is already in the project. (Attached Image)
![image](https://user-images.githubusercontent.com/9578152/44872879-adf4aa80-ac64-11e8-8844-1bbb9cff358e.png)

**Comment by carlosaparadam** [comment]
Hi @wdtz, i think so that after update the quantity on the Project Phase/Task, then updates the project line automatically

**Comment by wdtz** [comment]
After the change:

When editing the amounts planned in the task, the amounts updated in the phase and project are not correct.
