### ISSUE TITLE
Bug Behavior  incorrect when complete an allocation and  dates validation is executed

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#1963]
The current logic indicate the that the invoice accounting date or pay accounting date should be after that allocation accounting date.
when the behavior rigth is that allocation accounting date should be after to accounting date or pay accounting date

The behavior was introducing #1348.

**Comment by adaxa-steven** [comment]
I remember we did work on this because if invoice was in month 1, payment wad in month 2 and allocation was in month 3 and each month had different exchange rates then the realised gain/loss was wrong. Is this the problem you are fixing?

**Comment by e-Evolution** [comment]
@adaxa-steven , the problem, in general, is that the allocation accounting date after that payment or invoice accounting date, but in the real world behavior happens is allocation accounting date is after that the payment or invoice.

**Comment by adaxa-steven** [comment]
Victor,
Before you spending time on this, do you you me to get the changes we did in case it fixes your use case.
