### ISSUE TITLE
Create link the Service Contract with Core Entities (C_Order, C_Payment, C_Invoice, S_Request, etc)

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#1976]
The Contract Service and Line need be link with the other ADempiere Entities as Sales Order , Purchase Order , Receipt and Shipment , Invoice and Payment , etc

**Comment by yamelsenih** [comment]
Hi @e-Evolution  exists a pull request for it?

please add a pull request for complement it issue
