### ISSUE TITLE
GridTable dbProcessedS should be tested for null

### ISSUE THREAD

**Issue by mckayERP** [adempiere/adempiere#198]
In GridTable.java, the variable dbProcessedS is used to hold the value of the processed field, if it exists.  If the field is added to a table that already has data, the values of the field can be null or empty and the variable can be set to null.  The test on line 3617 will cause a null pointer exception.

So, instead of
                if (! dbProcessedS.equals("Y"))
use
                if (dbProcessedS == null || dbProcessedS.isEmpty() || ! dbProcessedS.equals("Y"))

**Comment by e-Evolution** [comment]
processed column should be add into a new table always with Default value as 'N' and synchronize with DB, this way avoid the NPE, WDYT?

**Comment by mckayERP** [comment]
Its a good idea.  The current code does not add default values to newly added columns if the table already has data.
