### ISSUE TITLE
M_Element aftersave should use models to update columns, fields etc.

### ISSUE THREAD

**Issue by mckayERP** [adempiere/adempiere#199]
The afterSave function in M_Element should use models to make changes to columns, fields and other database items.  The model changes are captured by the migration scripts where the sql changes are not.  With the current sql updates, the migraiton script only captures the element change.

**Comment by e-Evolution** [comment]
Dear Mike would describe a testing please ?

**Comment by mckayERP** [comment]
Find a columns, like C_BPartner_ID, with columns in multiple tables, fields, parameters etc...

Turn on "Log Migration Scripts".

Change the system element of C_BPartner_ID by changing the name field and save the record.

Turn off "Log Migration Scripts.  Verify that a script has been created and that it includes the change to the System Element.  Note that it does not include the change to columns, fields or parameters.

Verify that the column name has changed in the C_BPartner table and the field in the Business Partner window.

Since the migration script only has the system element change and the migration application sets  isDirectLoad=true, the afterSave functions of the M_Element model are not called.  When the script is applied, only the AD_Element table is changed.
