### ISSUE TITLE
New process for bill collection and payment

### ISSUE THREAD

**Issue by nsarlabos** [adempiere/adempiere#1997]
It requires a process in the window of documents to be collected and paid, to replace the current functionality in the payment rule button.

This process will also allow the collection / payment in a currency different from that of the document, making the conversion of the amount automatically, according to the exchange rate of the type "Company".

The process will assign the corresponding value to the current payment rule field (PaymentRule), which will become a List type.

**Comment by yamelsenih** [comment]
This already exists here: #1616 #1783
