### ISSUE TITLE
WSearchEditor has null pointer exception if not in a tabpanel.

### ISSUE THREAD

**Issue by mckayERP** [adempiere/adempiere#2000]
The WSearchEditor.java code added in #1088 needs a test for null pointer on the tabPanel.

To test in ZK, open Payment Print/Export and click on the Payment Selection field helper button.

From line 701:

	if(this.getADTabPanel() != null && this.getADTabPanel().getListPanel() != null)
		this.getADTabPanel().getListPanel().addKeyListener();
	GridPanel gridQuick = null;
	ADTabPanel tabPanel = (ADTabPanel)getADTabPanel();  // Can be null
	if(tabPanel.getQuickPanel() != null) {  // Null Pointer Exception!
		gridQuick = tabPanel.getQuickPanel();
		gridQuick.addKeyListener();
	}

**Comment by yamelsenih** [comment]
It was resolved yet
