### ISSUE TITLE
Random Error

### ISSUE THREAD

**Issue by wdtz** [adempiere/adempiere#2003]
Error generated randomly when editing quantity in the line of the task. (Attached Image)

![image](https://user-images.githubusercontent.com/9578152/45650761-55634100-ba9d-11e8-8873-feae079cff8c.png)

**Comment by e-Evolution** [comment]
@wdtz , this problem is caused because need be defined , member and member type.

In general now the system adding automatically project management as member.

Testing adding project member 

kind regards
Victor
