### ISSUE TITLE
"Quicksheet" Functionality: missing view definitions in db/ddlutils

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere#2011]
For the development of the **Quicksheet Functionality** (PR: https://github.com/adempiere/adempiere/pull/1828 , issue: https://github.com/adempiere/adempiere/issues/1088) the views _ad_field_v_ and _ad_field_vt_ were modified.

What is missing is the corresponding modification in _db/ddutils_.

At the same time, it is advisable to omit the schema _adempiere_ in the view definition.
In this case the definition should be 

> CREATE OR REPLACE VIEW ad_field_vt AS

instead of

> CREATE OR REPLACE VIEW adempiere.ad_field_vt AS

**Comment by yamelsenih** [comment]
This was resolved yet
