### ISSUE TITLE
Calculation of Incidents from attendance record 

### ISSUE THREAD

**Issue by wdtz** [adempiere/adempiere#2013]
When processing the attendance record ADempiere generates incidents, however the calculation is wrong.

The case emulated in ADempiere was the following:

Incidence of shift configured:

If exist is an attendance record  of type Entrance  from 06:00 to 07:59 is Considered Extra Time in minutes. (Attached Image 01)

An attendance record was created with an entry 07:30 (Image Attached 02)

Expected result:

07:30 to 07:59 = 29 minutes

Result of ADempiere

06:00 to 07:30 = 90 minutes (Attached Image 03)
![image](https://user-images.githubusercontent.com/9578152/45893451-4203ee80-bd99-11e8-9c49-0821c3785d7c.png)

**Comment by yamelsenih** [comment]
It can be used with Anticipated Record flag

Best regards
