### ISSUE TITLE
Add Outbound Order from Sales Order / Distribution

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#2023]
Is Nice to have a form for generate Outbound order from Sales order or Distribution Order, this allows create a fast way for Picking and warehouse material.

See a image:
![screenshot_20180926_171407](https://user-images.githubusercontent.com/2333092/46109824-56842480-c1a7-11e8-95e3-124a24532a54.png)

**Comment by e-Evolution** [comment]
@yamelsenih , but as work the delivery rule , this new functionality ignore the delivery rule, or only work when the delivery rule is force.

Because as I can see this new form , ignore the delivery rule business logic ?

**Comment by yamelsenih** [comment]
Hi @e-Evolution delivery rule is here, this form just allow create a outbound more easy that a Smart Browser and this use all model functionality
