### ISSUE TITLE
Default Amount Field Does Not Work

### ISSUE THREAD

**Issue by wdtz** [adempiere/adempiere#2026]
A bonus turn incident was set up with a predetermined amount of 5000 (Attachment Image 1)
![image](https://user-images.githubusercontent.com/9578152/46113350-0499c980-c1bc-11e8-92fd-780ac2ddbe7c.png)

When processing the incident record, it does not generate the incident with the bonus set by 5000. (Attachment Image 2)

![image](https://user-images.githubusercontent.com/9578152/46113466-7ffb7b00-c1bc-11e8-9d69-d602e64804f0.png)

**Comment by yamelsenih** [comment]
Hi @wdtz please test it
