### ISSUE TITLE
Add Icon Image for any column defined as Button

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#2034]
- Adding a new column for defining the image any column defined as button into a column and field
- Modify the Button and WButtonEditor to enable the icon image

**Comment by yamelsenih** [comment]
Hi @e-Evolution is nice it

**Comment by e-Evolution** [comment]
Copy from now show an icon:

<img width="1298" alt="captura de pantalla 2018-09-28 a la s 21 31 56" src="https://user-images.githubusercontent.com/786968/46240028-ede3a600-c366-11e8-87db-fbe9c97145a4.png">


<img width="1590" alt="captura de pantalla 2018-09-28 a la s 21 37 52" src="https://user-images.githubusercontent.com/786968/46240030-efad6980-c366-11e8-86bf-db9ff1f1a9b1.png">
