### ISSUE TITLE
Final Steps towards Release 3.9.1

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere#2071]
As of now, we can start planning the release 3.9.1.
The idea is to use this issue as a guide to other issues which will consist of atomic steps for the release.

Please mention the steps you suppose are needed for the 3.9.1 release. Later in the thread we'll create an ordered list of the issues.

In due date we will be able to set an exact date, depending on the resources available.

List of tasks (not yet ordered):

- Freeze code and allow only for bug fixing of this release's commits.
- Create seed in Postgres and Oracle
- Perform the post-migration steps in GW in the seed - i.e. role access update, verify document types etc to ensure everything works on initial install. Issue #1999.
- Cleaning the previous migration steps from the last seed before creating the new one. It is getting bloated with migration data. (RUN_MigrateXML clean).
- Install package updates - universal installers, windows only etc...
- Correct XML sequences, including sequence inside the file.
- Edit and make legible issues and pull requests titles. The reason: the published list of bug fixes and enhancements along with the release announcement will be extracted from Github.
- Deploy 3.9.1 versions on both Postgres and Oracle for public testing. Define a period for public testing.
- Document tests done
- Set release date.
- Run scripts for getting bug fixes and enhancements separated by labels.
- Upload installation code.

**Comment by mckayERP** [comment]
Not in order...

- See #1999. Perform the post-migration steps in GW in the seed - i.e. role access update, verify document types etc to ensure everything works on initial install.
- Consider cleaning the previous migration steps from the last seed before creating the new one.  It is getting bloated with migration data.  (RUN_MigrateXML clean).
- Install package updates - universal installers, windows only etc...

**Comment by marcalwestf** [comment]
I will take up the observations, copy them into the initial comment  and -when we have them all- we'll agree on an order.

Ideally, every step should be atomic and be accompanied by an issue which describes it more or less exactly and which is referred to by a pull request.

**Comment by marcalwestf** [comment]
@mckayERP hi Mike, could you elaborate the items you mention please?

> 
> - Consider cleaning the previous migration steps from the last seed before creating the new one. It is getting bloated with migration data. (RUN_MigrateXML clean).
> - Install package updates - universal installers, windows only etc...

What exactly has to be cleaned? I.e., which migration steps have created what data worth being get rid of?
Which packages are to be installed? Do you mean POS, CRM, Assets or something else?

**Comment by e-Evolution** [comment]
@marcalwestf , @mckayERP the step to release are here http://wiki.adempiere.net/Steps_To_Release

I will work this week to execute this step list. the steps with more work and time is to create the seed, in special the Oracle seed, all the new script are testing using PostgreSQL and when generating to Oracle, all inconsistencies are found. so fixes all this problem takes time.

**Comment by marcalwestf** [comment]
this link is quite outdated . Last edition 4 years ago; a lot has changes since then.

Perhaps we could agree on the steps and subsequently update the wiki.

**Comment by mckayERP** [comment]
Cleaning the migration means leaving the header record but deleting all the steps and data.  The feature is already incorporated in the [MigrationLoader.java.](https://github.com/adempiere/adempiere/blob/develop/base/src/org/adempiere/process/MigrationLoader.java) and [MMigration.java](https://github.com/adempiere/adempiere/blob/develop/base/src/org/compiere/model/MMigration.java).  It was commented out n MigrationFromXML.java - this would need to be undone.

Here is the routine:

	/**
	 * Clean the migration of data.  Only the header will be left.
	 * The migration should be applied and have the entity type for Dictionary 'D'.
	 * Steps and Step data will be deleted and the migration marked as "processed".
	 * The goal is to leave a record of the applied migration but reduce the database
	 * size.
	 */
	public void clean() {
		if ( getEntityType().equals("D") && getStatusCode().equals(MMigration.STATUSCODE_Applied) ) {
			log.log(Level.CONFIG, "Cleaning migration: " + this.toString());

			this.setProcessed(true);
			
			for ( int stepId : getStepIds(false) )
			{
				MMigrationStep step = new MMigrationStep(getCtx(), stepId, get_TrxName());
				log.log(Level.CONFIG, "   Deleting step: " + step.toString());
				step.deleteEx(true);
			}
			this.saveEx();
		}
    }

**Comment by mckayERP** [comment]
Packages may not be the right word.  Install packages are the packages used to install the application - perhaps "installers" would be better.  There is a one-click installer for windows and I saw reference to a universal installer for other platforms.  In the past, these were updated after the release.

**Comment by mckayERP** [comment]
For the cleaning, my impression is that roll-backs are not much use once the seed has been created.  It would be difficult to reliably roll-back a single migration from the past without rolling back everything.  The Migration Tool is a better choice it it is necessary to revert to an older version of the database.  So once the seed has been created, there is not much need for the migration steps and data.  The XML files still exist so nothing is lost but the records in the database.

It is important to keep the migration header as that is used to determine if a new XML file has already been loaded.

As stats, the current (as of a few days ago) size of the database seed:

- Last seed jar: adempiere_pg.jar  13MB
- Seed candidate jar: 18MB
- .DMP file last seed: 127MB
- .DMP file candidate: 163MB

**Size of the AD_MigrationData table: 26MB!!**
Size of the AD_MigrationStep table: 1.9MB
Size of the next largest: MColumn: 1.4MB

**Comment by yamelsenih** [comment]
I agree with @mckayERP but i think that Migration can be keeped for one release

**Comment by mckayERP** [comment]
For GardenWorld setup, see #135.  Basically, run the accounting on GardenWorld before generating the next seed so the user doesn't have too.  Ensure the costing works.  GW should work out of the box without the need for any setup.
