### ISSUE TITLE
Synchronize CalloutPayment and CalloutPaymentAllocate

### ISSUE THREAD

**Issue by SusanneCalderon** [adempiere/adempiere#2075]
Now the two callout reacts different when you enter a payment amount different to the open amt.

- CalloutPayment calculates overunderpayment as the difference between open amount and payment amount, when the flag _isOverUnderPAyment_ is set. Otherwise it calculates the difference as writeoffamt.
- CalloutPaymentAllocate calculates a difference always as writeoffamount.

Both callouts should calculate consistent to the flag _isOverUnderPayment_ in the first tab.

**Comment by yamelsenih** [comment]
Hi @SusanneCalderon  exists a pull request for it?

please add a pull request for complement it issue
