### ISSUE TITLE
StackOverFlow Error in WAcctViewer

### ISSUE THREAD

**Issue by SusanneCalderon** [adempiere/adempiere#2095]
![imagen](https://user-images.githubusercontent.com/15349639/47372987-26497c00-d6a8-11e8-9d54-4f502a01c65f.png)

**Explanation:** 
The AcctViewer collects all tables with column _Posted_ in a listbox. The sequence is random.
When in the first table the key column is defined as TableDirect or Search the result is the StackOverFlow Error.
![imagen](https://user-images.githubusercontent.com/15349639/47373238-a374f100-d6a8-11e8-88ef-83dd067a6fe8.png)

**When you change the column definition to ID, the error does not appear.**
![imagen](https://user-images.githubusercontent.com/15349639/47373284-bf789280-d6a8-11e8-9555-4bf7b0440364.png)

**Result of showAccting**
![imagen](https://user-images.githubusercontent.com/15349639/47373357-e8008c80-d6a8-11e8-827f-4d30edc8c6ae.png)

**Comment by yamelsenih** [comment]
I am trying rreproduce this error but I can't reproduce. Can you tell me more infor or a log for review source code?

Best regard
