### ISSUE TITLE
Support for application dictionary changes and configurable automatic syncing with the database

### ISSUE THREAD

**Issue by mckayERP** [adempiere/adempiere#213]
I've had to modify a large chunk of an existing customization and found that ADempiere does not support renaming of columns.  In the database, if you rename a column and sync, you will get the old column with data and a new empty column.  Fixing this is time consuming and involves a lot of work in the database - a tedious task when facing changes to hundreds of columns.

I came up with a solution and applied it to about three hundred columns and about twenty tables.  I found it quite helpful.  With autosyncing, any change made to a table, element or column is immediately applied to the database in a way that no additional work is required.   It works well with the migration scripts which can record and keep track of the changes.

The main indexes and constraints are preserved through the table/column changes.  Special constraints may need to be managed manually.  The deletion of a column is not supported.

As an example, with this feature, I can change the column name of a system element and have the changes synced with the database in all the tables where that element occurs without having to visit each table and manually sync.

If this would be helpful, let me know and I'll make a pull request with the changes.

**Comment by yamelsenih** [comment]
Hi, any update for it?
