### ISSUE TITLE
Error on Smart Browse When needs autorefresh values on process that come from context variables.

### ISSUE THREAD

**Issue by Ganzt90** [adempiere/adempiere#2151]
In the smart Browse process, adding a Dynamic Validation in a parameter that allows to display a selected value of the Query Criteria in the parameter does not refresh automatically to the appropriate value.

![smart browse error](https://user-images.githubusercontent.com/37981079/48949784-8e8db680-ef0f-11e8-805a-5d0642f92139.png)

After refreshing the field

![error](https://user-images.githubusercontent.com/37981079/48950749-9733bc00-ef12-11e8-889f-625a8306c5ff.png)

The required value is properly displayed

![error 2](https://user-images.githubusercontent.com/37981079/48950834-e4179280-ef12-11e8-9c9e-9fb42c5aa879.png)

**Comment by yamelsenih** [comment]
This was resolved yet
