### ISSUE TITLE
Spurious Error When Copying Roles

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere#2165]
Reported by Steven (@adaxa-steven ).

In the copy role process, copying from role a to role: role "A" and role "B" could get interchanged in the code because of the way the parameters are obtained.

Adaxa has provided Code to solve this problem; it will be tested (perhaps adapted) and integrated.
Here's how the change would look like:
![20181203_copyrole](https://user-images.githubusercontent.com/1789408/49413981-65eb9500-f737-11e8-8a78-0d52ecf91acf.png)

**Comment by yamelsenih** [comment]
Hi @marcalwestf i think that @adaxa-steven have a old code, i was changed it a long time before, see this issue: https://github.com/adempiere/adempiere/issues/264

Also here a diff of current ADempiere:

![screenshot_20181203_234243](https://user-images.githubusercontent.com/2333092/49417756-6e52c880-f755-11e8-8875-5777611dfac7.png)


I will to change it class for new approach

**Comment by yamelsenih** [comment]
I will add a change for it reported by  @adaxa-steven:
https://docs.oracle.com/javase/7/docs/api/java/io/File.html#getName()


in this commit:

https://github.com/adempiere/adempiere/commit/9159a75c99578e8122a99f740c58d481b6dc05aa

to replace this bit of code that gets the file name from a path string:

/**
	 * Get name of file
	 * @param fileName
	 * @return
	 */
	private String getFileName(String fileName) {
		if(!Util.isEmpty(fileName)) {
			if(fileName.lastIndexOf("/") != -1) {
				fileName = fileName.substring(fileName.lastIndexOf("/") + 1);
			}
		}
		//	Default
		return fileName;
	}

for OS compatibility as "/" may not be the path separator

Thanks
