### ISSUE TITLE
Add new bank statement report

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#217]
Is necessary an new bank statement report to get information about bank statement

**Comment by yamelsenih** [comment]
Hi We have a report for bank statement and other for balance per bank in a determinates date

**Comment by Mbilalilyas** [comment]
yamelsenih can you please share this report to community

**Comment by e-Evolution** [comment]
Hi @yamelsenih , will great that you can share , I know how I think the contribution or improves save in drawer only help to drawer :-)
