### ISSUE TITLE
Notifier Process

### ISSUE THREAD

**Issue by MarianaGallardo** [adempiere/adempiere#2202]
A notification process is required according to the type of Member that should be informed about the topics that correspond to it. For Member Type "Accounts" for example, it must be defined so that they are aware of all the changes made in the Project.

**Comment by marcalwestf** [comment]
Hi @MarianaGallardo . 
The idea of notifying project members is in principle OK.
Here I kindly have some questions.

1. What do you mean by Type of member?
There is a window Project Member Type, which can be referenced to by Project members, but it has no further information.
2. Which are the "Topics" corresponding to Member types? For once, where do I define a Member Type "Accounts"?
3. How would the notification take place? I suppose email, etc?

Thanks

**Comment by marcalwestf** [comment]
I could imagine that it can be of importance to the user -and as complimentary information- the _Document Tasks_ section.
![20181210_project_15](https://user-images.githubusercontent.com/1789408/49869288-9daca980-fdd5-11e8-8e30-77ba15739fd9.png)

Here, the user could be provided with all documents which requires an action for him. 
Of course it'd have to be defined what, but I could imagine documents like 
- Projects with all phases and tasks completed, but not closed 
- Not finished Projects, but idle than for example 6 months
- Projects without quotations or orders for "n" moths
- Projects with due dates
-  etc.

**Comment by e-Evolution** [comment]
@marcalwestf currently the Project Processor window was adding in https://github.com/adempiere/adempiere/issues/1532, the main idea  is that Project Processor work as Request Processor

OpenUp Solution offered to implement but it seems that it was not possible in 391.

I will finish this functionality in the next version.

**Comment by marcalwestf** [comment]
If I understand you  well @e-Evolution, the Project Processor will affect one or many Project Types and is yet not implemented. I like the idea, though I cannot imagine right now of concrete situations.

@MarianaGallardo  does your improvement aim at implementing it with this Project Processor when it is available?

**Comment by e-Evolution** [comment]
@marcalwestf The project processor is Adempiere's way of generating the emails and notifications in the same way as the request processor does now.

The idea is that a process in the background monitors the phases and tasks, creating notices for the project manager or responsible for a phase or task when it is about to expire or has expired, or validate any status.

Nowadays this can be seen in the practice of request management.

So the idea is that the project processor can be configured by project type and task category to set the monitoring duration

a notice will be sent to project members will be used according to the type of notification.

**Comment by yamelsenih** [comment]
Duplicated with #1532

**Comment by MarianaGallardo** [comment]
The result of the test has been successful.
