### ISSUE TITLE
The migrationsfiles are missing in  Installationfile Adempiere_391LTS.zip 

### ISSUE THREAD

**Issue by SusanneCalderon** [adempiere/adempiere#2207]
I generated Adempiere_391LTS.zip with Ant and the migration archive was not copied.
![imagen](https://user-images.githubusercontent.com/15349639/49840412-e2eebe00-fd78-11e8-99ae-cedd3e64fd37.png)

**Comment by yamelsenih** [comment]
Hi @SusanneCalderon this issue was resolved?
