### ISSUE TITLE
Some nice features selected myself of idempiere.

### ISSUE THREAD

**Issue by ayazbaloch** [adempiere/adempiere#2228]
Dear Adempiere community, I read some selected following features of idempiere.

1- Password Rules (http://wiki.idempiere.org/en/NF1.0_PasswordRules)
2- User Locking (http://wiki.idempiere.org/en/NF1.0_User_Locking)
3- Improved Form Layout (http://wiki.idempiere.org/en/NF1.0_FormLayout)
4- Configurable Grid Layout (http://wiki.idempiere.org/en/NF1.0_SaveGridLayout)
5- Configurable Quick Entry (http://wiki.idempiere.org/en/NF1.0_QuickEntry)
6- Broadcast Message (http://wiki.idempiere.org/en/NF1.0_BroadcastMessage)
7- User Feedback (http://wiki.idempiere.org/en/NF1.0_UserFeedback)
8- Automatic List Refresh (http://wiki.idempiere.org/en/NF1.0_Automatic_List_Refresh)

These are my recommended while community vote for them either are incorporated or not.

**Comment by satpalravi** [comment]
9. Create Line From Requisition in Purchase order Window (http://wiki.idempiere.org/en/Plugin:_Create_from_requisition) - this is important scenario where the supplier is not know for product and requisition is generate inter department. Once requisition clear the approval workflow it should show as due for purchase order.
Example, In few companies where I have implemented other ERPs, the requisition is coming from production floor for project or consumables to purchase, once Requisition is compete, PO can be created using create line from Requisition.

**Comment by marcalwestf** [comment]
hi ,
An explanation about Quick Entry: this is already implemented and ready to be delivered with 3.9.1.

I don't know the solution proposed, but here some highlights of our solution:
- designed for massive entries
- 100% integrated with the grid
- callouts included
- possibility to edit the whole table or to see only new records. This is useful is for example the table has 1000 records.
- works with all references and validations
- has a set of handy shortcuts
- straightforward to use and navigate

**Comment by marcalwestf** [comment]
the other features would be also nice to test.

Here the people interested in getting the feature integrated should do as follows:
- go to the idempiere repository
- find out and isolate the commits concerning the changes
- create a branch in your local ADempiere repository for every new feature
- document in issues what you think is is useful information, questions, changes, etc.
- integrate the commits of the feature in your local branch
- test the feature
- after passing the feature's tests, create a pull request documenting as best as you can your proceedings
- voilá! you're done: the feature will be tested and -if everything goes OK- eventually accepted

**Comment by ayazbaloch** [comment]
Dear @marcalwestf  QuickSheet is for bulk entries which is powerful feature of Adempiere while Quick-Entry is for single record which need to be implemented in Adempiere.

**Comment by adaxa-steven** [comment]
Hi Ayazbaloch
re:  4- Configurable Grid Layout (http://wiki.idempiere.org/en/NF1.0_SaveGridLayout)
this feature is already available to Adempiere..
see adaxa.testadempiere.com.   
[HowTo - Quick Entry Set-up.pdf](https://github.com/adempiere/adempiere/files/2701585/HowTo.-.Quick.Entry.Set-up.pdf)

![image](https://user-images.githubusercontent.com/15791084/50325671-395aba00-053a-11e9-8093-b424aaa73bc1.png)


note that we added an extra control so that a person's role can be flagged to let them create grid preferences for users who have not set their own preferences.. this lets a superuser preconfigure what is seen by a new user to the system.

code is on sourceforge 

Mario,
Quickentry in idempiere allows the the user to add new new fields to the 'right-click-quick-add' a BP (etc)
The Quickentry from Adaxa is different and operates as you have described.
see attached document on it 

regards
Steven

**Comment by ayazbaloch** [comment]
Dear @adaxa-steven  thanks for your valuable comments, could it re: 4 will be come in version 3.9.1 or just is available in Adaxa Adempiere?

**Comment by adaxa-steven** [comment]
re: 4 will be come in version 3.9.1 or just is available in Adaxa Adempiere?
.... i dont know what is in 3.9.1
Mario? Victor? any ideas?

**Comment by yamelsenih** [comment]
>Dear Adempiere community, I read some selected following features of idempiere.

>1- Password Rules (http://wiki.idempiere.org/en/NF1.0_PasswordRules)

ADempiere already has it improved

>2- User Locking (http://wiki.idempiere.org/en/NF1.0_User_Locking)

Nice to hace

>3- Improved Form Layout (http://wiki.idempiere.org/en/NF1.0_FormLayout)

Nice to have

>4- Configurable Grid Layout (http://wiki.idempiere.org/en/NF1.0_SaveGridLayout)

Nice to have

>5- Configurable Quick Entry (http://wiki.idempiere.org/en/NF1.0_QuickEntry)

This already exist for ADempiere

>6- Broadcast Message (http://wiki.idempiere.org/en/NF1.0_BroadcastMessage)

Is nice to have but with a good broker like [Mosquitto](https://mosquitto.org/) or [Emitter](https://emitter.io/) instead

>7- User Feedback (http://wiki.idempiere.org/en/NF1.0_UserFeedback)

Is a good functionality but personally I think that was bad implemented and is nice to have with a abstraction layer for integrate with any Request System like Jira, Github, OSTicket and others 

>8- Automatic List Refresh (http://wiki.idempiere.org/en/NF1.0_Automatic_List_Refresh)

Is nice to have but I think that ZK is a old old old framework and for my is not a priority now

These are my recommended while community vote for them either are incorporated or not.

@ayazbaloch Tanks for this list for choise

**Comment by ayazbaloch** [comment]
Dear @yamelsenih you mean you are working on vueJS for front-end.

**Comment by jdaison** [comment]
this sounds good! +1 for me
