### ISSUE TITLE
Error in DB function paymenttermduedate(numeric,timestamp with time zone)

### ISSUE THREAD

**Issue by mckayERP** [adempiere/adempiere#2256]
With 3.9.1, Postgres 9.4, I'm getting the following error on login to Garden World with GardenAdmin role when displaying the Performance measures.

    ===========> DB.getSQLValueBD: SELECT COALESCE(SUM(currencyBase(invoiceOpen(C_Invoice_ID, C_InvoicePaySchedule_ID),C_Currency_ID, DateAcct, AD_Client_ID, AD_Org_ID)),0)
    FROM C_Invoice_v C_Invoice WHERE IsSOTrx='Y' AND Processed='Y' AND C_Invoice.AD_Client_ID IN(0,11) AND C_Invoice.AD_Org_ID IN(0,11,12,50000,50002,50001,50004,50006,50005,50007) [1]
    org.postgresql.util.PSQLException: ERROR: operator does not exist: timestamp with time zone + numeric
    Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
    Where: PL/pgSQL function paymenttermduedate(numeric,timestamp with time zone) line 41 at assignment; State=42883; ErrorCode=0

Need to use the ADDDAYS database function.

**Comment by e-Evolution** [comment]
The 3.9.1 is compatible with PostgreSQL 11
