### ISSUE TITLE
bug in script PostgreSQL ImportAdempiere.sh

### ISSUE THREAD

**Issue by homebeaver** [adempiere/adempiere#2257]
when performing `RUN_ImportAdempiere.sh` in 3.9.1 with postgres 10 I got

"create database failed with exit code 1"

but the database is created!

**Comment by e-Evolution** [comment]
Hi @homebeaver 

What is the log that cause  code 1?

**Comment by homebeaver** [comment]
After some investigation I found the bug in script PostgreSQL `ImportAdempiere.sh`

It happens when role `adempiere` exists

**Comment by homebeaver** [comment]
a pull request follows
