### ISSUE TITLE
Product Category has unused fields

### ISSUE THREAD

**Issue by mckayERP** [adempiere/adempiere#2264]
I can't find any use for the following fields in the M_Product_Category table:

- isSelfService
- AD_PrintColor_ID

Recommend the associated fields be deleted from the Product Category window.

**Comment by ayazbaloch** [comment]
Dear @mckayERP here is description from compiere doc.
**Select the Self Service check box if Products in this Category will be available in the Web Store.**

**Comment by mckayERP** [comment]
@ayazbaloch Thanks.  I was using the call hierarchy to find where the fields were used but didn't do a text search.  I see the sql for the isSelfService in the webstore code now.

Can't find any reference to the Product Category AD_PrintColor_ID though by call or sql.

**Comment by e-Evolution** [comment]
Hola Mike

The AD_PrintColor_ID thought to define a color in Tree functionality for swing, define a way to print based in AD_PrintColor_ID by ADempiere Report Engine and other case define the color for a POS key.

for product window, I made a small in code and product window and marked this as tree tab and get a tree with colors category that is nice.

![image](https://user-images.githubusercontent.com/786968/51560641-b1bede80-1e4a-11e9-90ae-7b30477adfbb.png)

I think that with little effort work we can implement for all other dimensions.

`
	/**
	 * 	Get fully qualified Name of Action/Color Column
	 *	@return NULL or Action or Color
	 */
	public String getActionColorName()
	{
		//	Yamel Senih [ 9223372036854775807 ]
		String tableName = getSourceTableName();
		if ("AD_Menu".equals(tableName))
			return "t.Action";
		if ("M_Product".equals(tableName))
			return "(SELECT pc.AD_PrintColor_ID FROM M_Product p INNER JOIN M_Product_Category pc ON (p.M_Product_Category_ID = pc.M_Product_Category_ID) WHERE p.M_Product_ID=t.M_Product_ID)";
		return "NULL";
	}	//	getSourceTableName
`

**Comment by mckayERP** [comment]
Excellent!  Thanks.

**Comment by mckayERP** [comment]
Resolved by #2271.
