### ISSUE TITLE
Enlarge length for bank name - use system element BankName which is 120

### ISSUE THREAD

**Issue by homebeaver** [adempiere/adempiere#2266]
`c_bank.name` is limited to 60 chars. This is to short. See similar to c_location and email in #1340

In the 30 largest banks in germany, see [bankenverband.de](https://bankenverband.de/media/publikationen/16112017_Zahlen_und_Fakten_web.pdf) there are three to reach the limit:

```
Landeskreditbank Baden-Württemberg - Förderbank, Karlsruhe
WL Bank AG Westfälische Landschaft Bodenkreditbank, Münster
Bremer Landesbank Kreditanstalt Oldenburg - Girozentrale, Bremen
```

There is a system element `Bank Name` with length 120 - AD_Element_ID=52002 . But is is not used for `c_bank.name`. Why?

**Comment by e-Evolution** [comment]
@homebeaver , I think that is ok , the next standard size is 256.

What do you think?

**Comment by homebeaver** [comment]
For me 120 is enough. I'll provide a migration xml.

**Comment by homebeaver** [comment]
@adaxa-steven  No - `c_bank` holds reference data for banks without bank accounts.
We import this data from the central bank - see [Beiträge here](http://www.adempiere.com/DE/Bank#Beitr.C3.A4ge) - there is an update quarterly a year from the Bundesbank

**Comment by adaxa-steven** [comment]
120 sounds good
