### ISSUE TITLE
problem with constraints over M_AttributeSetInstance_ID

### ISSUE THREAD

**Issue by ChrisHird** [adempiere/adempiere#2285]
Hi
I am trying to convert the entire DB over to IBM i DB2 which requires a number of changes related to the 10 character limit for object names and column Names in native programs (SQL works with existing column names). However when building the source I noticed an error with any constraint etc over the M_AttributeSetInstance_ID column name.
The file M_AttributeInstance has 'CONSTRAINT M_AttributeInstance_Key PRIMARY KEY (M_AttributeSetInstance_ID, M_Attribute_ID)' which causes constraints not to be added over other files as the key pair is not available in the other files. If I remove the M_Attribute_ID I can get the constraints to add but I am not sure of the overall effect of removing the second key value?

Should the other files be changed to include the additional key value or is the second value OK to be removed?

Hope that makes sense.

**Comment by mckayERP** [comment]
Hi Chris, The dual key constraint is valid for that table.  Can you keep the constraint, just not as a primary key?

**Comment by ChrisHird** [comment]
OK I think I have the answer, I need to add another constraint to the M_AttributeInstance table which will be unique and therefore allowed as the target for the foreign key?  Something like :

CONSTRAINT M_AttributeInstance_Unique_Key UNIQUE KEY (M_AttributeSetInstance_ID)

Would that give me any other issues? It mentions the key cannot be NULL except in one record so I am not sure if that is a problem?

**Comment by ChrisHird** [comment]
Fixed the build issue so will close for now. Do you need me to push up a PULL request for that one file (create DB) or should I leave as is (I am not building on the databases you are so not sure of the impact).

Chris...
