### ISSUE TITLE
Calculation of gain or loss for exchange difference in Balance Accounts

### ISSUE THREAD

**Issue by niclopup** [adempiere/adempiere#2300]
There isnt a process to calculate the Gain or Loss because the exchange difference in the Balance Accounts that are in Foreign Currency.

At the and of the period you must update the Amount Accounting Balance to the Source Balance multiply the Currency Rate of the End of the period.

**Comment by adaxa-steven** [comment]
Hi Nicolas,
I have an interest in this topic also.
which accounts are you trying to restate?
regards
steven

**Comment by adaxa-steven** [comment]
I know the bank accounts and bank-in-transit are not translated but I thought  the rest were covered. AR control, Unallocated AR Receipts, Customer Prepayment and equivalent for AP are done.  Are thre others we should manage?

**Comment by niclopup** [comment]
Hi Steven! 

Right now the process only run for those accounts of Asset, Owner's Equity or Liability Type that have on "Y" the check of Foreign Currency Account. Analyzing all the journal lines of the Fact_Acct in a currency different of the Accounting Schema, making a JournalBatch.

The only thing that isn't ready is the report of the results that shows after running the process, like it does the "Invoice Not Realized Gain & Loss Report".

This process I think it should take all the monetary accounts you have on balance. The accounts that we mark the Foreign Currency Account on "Y" are by now only the Bank and Bank-in-Transfer like you said.

Please if you have any comments we are glad to hear them in order to improve the functionallity 

Also i thought you could mark a Long Term Liabilities or a Short Term Obligation for example but it depends with which documents you create them initially (invoice or Payment), but if you say that the AP Payment and AR Receipt Not Allocated are done it shouldn't be necessary. Now, How does they are now done??

**Comment by adaxa-steven** [comment]
Started aging view and extended to include unallocated payments. Then look up the GL account that the invoices and unallocated payments went to. Then find what each was posted as in accounting currency (and prorata for part paid)..  Then convert the open amount in the document currency at the period end exchange rate and compare to the original posted values and get diff.
Unallocated AR payment amounts will be either in Unallocated payment GL account or Customer Prepayments and the view works that out. (see in adaxa.testadempiere.com)

**Comment by niclopup** [comment]
Great! 

I will verify it. 

Regards

**Comment by adaxa-steven** [comment]
I expect it would be possible to call the bank restatement diff by finding the bank statement at end of the month you were reporting and pick up the foreign currency amount from there and convert at period end rate then compare to the posted GL bank account balance and work out the diff but as multiple bank statements could have the same statement date you would have to be very careful to find the right statement. It would also be more complex if you allowed (say) an EUR payment to be created in a Usd bank account and your accounting currency was Canadian dollars.  Up till now I just did the calcs by hand and entered a manual journal.

**Comment by niclopup** [comment]
Exactly.
We apply the same process that the "Invoice Not Realized Gain & Loss Report" use but instead looking at the Fact_Acct.  I think it is the easiest and simpler way to do it.
