### ISSUE TITLE
Forgot Password link on webui login doesn't appear as a link.

### ISSUE THREAD

**Issue by mckayERP** [adempiere/adempiere#2318]
The Forgot Password link on the Webui login dialog does not appear as a link but as a text field.  It works, but it is not intuitive. The cursor does not change to a "finger" but shows as a I-beam indicating text of some sort.

Here are some solutions. Which is better?

As a button:

![image](https://user-images.githubusercontent.com/5507616/52426501-1a08f380-2acc-11e9-9e55-aec100d44b50.png)

Or as a link:

![image](https://user-images.githubusercontent.com/5507616/52428852-d49af500-2ad0-11e9-851a-42ae3bd02549.png)

**Comment by ayazbaloch** [comment]
Both are OK, Let user choice in preference.

**Comment by yamelsenih** [comment]
Hi @mckayERP i think that a underline is standard for hyperlink. however is a nice solution add a button

**Comment by mckayERP** [comment]
Thanks @ayazbaloch. Can you explain how you see the user choosing? As a system configuration or as a theme setting?  The user isn't logged in so a user preference isn't possible.

I'll submit a pull-request for the link but its easy to change to a button if that is preferred.

**Comment by jdaison** [comment]
I prefer a link, I think that is more standard a link

**Comment by ayazbaloch** [comment]
My vote goes to Standard link by default, after login let user choice in preference.
