### ISSUE TITLE
JDK 11 ready 

### ISSUE THREAD

**Issue by zalevan** [adempiere/adempiere#2323]
I successfully compiled and ran adempiere on openjdk 11.0.1. Both the swing client and the tomcat-based server were launched. The number of changes in the code is minimal. How do I transfer these changes?

**Comment by e-Evolution** [comment]
Hi @zalevan , please send the change as an pull request https://help.github.com/articles/about-pull-requests/

Thank a lot

**Comment by marcalwestf** [comment]
@zalevan best would be 
1.- Explain in an issue what you intend to do and all you know by now.
2.- clone Adempiere
3.- create a branch off the latest version (as of now 3.9.1)
4.- do commit your changes + push into this branch
5.- test thoroughly
6.- create a pull request "across forks"
7.- the conversation will be continued in the pull request and (hopefully) eventually merged.

**Comment by zalevan** [comment]
All is done. Closed. Success.
