### ISSUE TITLE
Field Movement Cursor Not Working Properly

### ISSUE THREAD

**Issue by niclopup** [adempiere/adempiere#2329]
When you are in any Text Field, like "Description" or "Reference No." in a Document in Single Record View, you can't move with the arrows in the keyboard. The Strange thing is that if you press Shift or Ctrl it let you move.

![image](https://user-images.githubusercontent.com/31936815/52571090-aa5c7680-2df3-11e9-8022-a8fde41fbea4.png)

![image](https://user-images.githubusercontent.com/31936815/52571159-c95b0880-2df3-11e9-9606-7707cf2f3a99.png)
When you press Crtl+ :arrow_backward: 

This is particulary unconfortable to make fast corrections in any text defined in documents. 

An other strange behavor is that for example for "Proyect" window, the first time you open it let you move perfectly but when you change to Grid Toggle and again to Single Record View it stop working.

In the other hand, in Grid Toggle view, it's not possible to modify any field. to make any change you have to move to Single Record View. 

![image](https://user-images.githubusercontent.com/31936815/52571252-f7d8e380-2df3-11e9-9e3f-40eddfc38a6d.png)

**Comment by rcapecce** [comment]
I'm testing an instance of develop and the arrows works fine but the enter key is not working alone and with the shift key.
I'm testing to the branch erpcya/hotfix/Agency-develop-392-8eb38b43679ab967467611c5021e3f2cf8bf075b an the enter key works fine when I enter to the window in mono row mode, if I change to multi row mode, the enter key breaks thereafter
