### ISSUE TITLE
Adding  library and support to print QR using jasper report

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#2335]

**Comment by jdaison** [comment]
Hi, Victor, I made some reports with these libraries, maybe this can be useful

http://central.maven.org/maven2/com/google/zxing/core/3.3.2/core-3.3.2.jar
http://central.maven.org/maven2/com/google/zxing/javase/3.3.2/javase-3.3.2.jar

The first step is to add libraries to ireport
![image](https://user-images.githubusercontent.com/6097506/52749407-13d8b280-2fb7-11e9-9fec-a4ff806ca684.png)

The second step is to add the image to report then change expression class to java.awt.image then add then nex tens in the image expression field
com.google.zxing.client.j2se.MatrixToImageWriter.toBufferedImage(
     new com.google.zxing.qrcode.QRCodeWriter().encode(
         $P{qrCode},
         com.google.zxing.BarcodeFormat.QR_CODE, 300, 300))

![image](https://user-images.githubusercontent.com/6097506/52749829-65357180-2fb8-11e9-9f7e-4ad05750f978.png)

![image](https://user-images.githubusercontent.com/6097506/52749841-6e264300-2fb8-11e9-8025-f2401504381b.png)

**Comment by e-Evolution** [comment]
Config Jasper Studio 6.6

![image](https://user-images.githubusercontent.com/786968/52751308-9e6be280-2fb4-11e9-9e36-38db8904965b.png)

![image](https://user-images.githubusercontent.com/786968/52751339-b6dbfd00-2fb4-11e9-8249-b2c7b28295cd.png)

![image](https://user-images.githubusercontent.com/786968/52751374-d8d57f80-2fb4-11e9-997d-0cc6534669e5.png)

Result into ADempiere

![image](https://user-images.githubusercontent.com/786968/52751219-58af1a00-2fb4-11e9-83aa-2c02e559bcca.png)

**Comment by e-Evolution** [comment]
@jdaison Hola John !

Jasper Studio 6.6 have native support for QR, so you not need write some code.

kind regards

**Comment by PraponAon** [comment]
Excellent......
ยอดเยี่ยมมากครับ

**Comment by jdaison** [comment]
@e-Evolution great that's so much better!!

**Comment by marcalwestf** [comment]
@e-Evolution  Victor, one question: could this also be included for logging in as with Online Banking, with _two-factor authentication QR codes_? Or it is an additional library needed?

Some clients have asked for it.

**Comment by ppenalo** [comment]
> Hola, @ e-Evolution , hice algunos informes con estas bibliotecas, tal vez esto pueda ser útil
> 
> [http://central.maven.org/maven2/com/google/zxing/core/3.3.2/core-3.3.2.jar ](http://central.maven.org/maven2/com/google/zxing/core/3.3.2/core-3.3.2.jar)
> [http://central.maven.org/maven2/com/google/zxing/javase /3.3.2/javase-3.3.2.jar](http://central.maven.org/maven2/com/google/zxing/javase/3.3.2/javase-3.3.2.jar)
> 
> El primer paso es agregar bibliotecas a ireport
> ![imagen](https://user-images.githubusercontent.com/6097506/52749407-13d8b280-2fb7-11e9-9fec-a4ff806ca684.png)
> 
> El segundo paso es agregar la imagen al informe, luego cambiar el campo de clase de expresión a **java.awt.image y** luego agregar el siguiente texto en el campo de expresión de la image
> ```
> com.google.zxing.client.j2se.MatrixToImageWriter.toBufferedImage(
>      new com.google.zxing.qrcode.QRCodeWriter().encode(
>          $P{qrCode},
>          com.google.zxing.BarcodeFormat.QR_CODE, 300, 300))
> ```
> 
> ![imagen](https://user-images.githubusercontent.com/6097506/52749829-65357180-2fb8-11e9-9f7e-4ad05750f978.png)
> 
> ![imagen](https://user-images.githubusercontent.com/6097506/52749841-6e264300-2fb8-11e9-8025-f2401504381b.png)

**Comment by ppenalo** [comment]
> Hi, @e-Evolution, I made some reports with these libraries, maybe this can be useful
> 
> http://central.maven.org/maven2/com/google/zxing/core/3.3.2/core-3.3.2.jar
> http://central.maven.org/maven2/com/google/zxing/javase/3.3.2/javase-3.3.2.jar
> 
> The first step is to add libraries to ireport
> ![image](https://user-images.githubusercontent.com/6097506/52749407-13d8b280-2fb7-11e9-9fec-a4ff806ca684.png)
> 
> The second step is to add the image to report then change expression class field to **java.awt.image** then add next text in the image expression field
> 
> ```
> com.google.zxing.client.j2se.MatrixToImageWriter.toBufferedImage(
>      new com.google.zxing.qrcode.QRCodeWriter().encode(
>          $P{qrCode},
>          com.google.zxing.BarcodeFormat.QR_CODE, 300, 300))
> ```
> 
> ![image](https://user-images.githubusercontent.com/6097506/52749829-65357180-2fb8-11e9-9f7e-4ad05750f978.png)
> 
> ![image](https://user-images.githubusercontent.com/6097506/52749841-6e264300-2fb8-11e9-8025-f2401504381b.png)

Hi @jdaison jdaison the links worked for me, can you please send me another

**Comment by e-Evolution** [comment]
Hi @GKTechy 

What is the reason for adding other libraries, as I mention here https://github.com/adempiere/adempiere/issues/2335#issuecomment-463418979, they do not require adding anything else since Jasper Report 6.6. and ADempiere 3.9.3 support QRC natively.
