### ISSUE TITLE
Document Status Indicator improvements.

### ISSUE THREAD

**Issue by mckayERP** [adempiere/adempiere#2340]
The code that applied the style and color to the dashboard Document Tasks panel was removed in #1193.  The fields in the Document Status Indicator window can be hidden as they are no longer used.

Also, the Document Tasks are underlined but do not behave as links.  The I-bar cursor shows on hover rather than a finger.

**Comment by marcalwestf** [comment]
Agree with you Mike. Sensible changes which makes the user experience better.
For example, I found it more readable to have a different color for the Quantities.

**Comment by adaxa-steven** [comment]
Hi Mario, Mike, 
we have a task we are are about to work on...
"Convert Document Status Indicators to Server Push model"
this was triggered by UI delays when many Document Status Indicators, each with complex queries are added to the system.
Will advise when the work is completed.

I am surprised that you have chosen to remove the font/size and colour control from the Document Status display. Our users found it helpful and we have now added an icon choice also for each Doc Status Indicator.
![image](https://user-images.githubusercontent.com/15791084/53064843-5c472180-351d-11e9-98d5-970de37463b6.png)

**Comment by sajeevsahadev** [comment]
Me too agree with @marcalwestf and @adaxa-steven. The different color will catch the attention for the users. I think we  should revert those changes. If any one want to change the style, they have an option to change it also.

**Comment by sksanoopz** [comment]
It was good a feature and we checked the same in our local setup. Why it is removed from the repository?  Please revert the same and bring back this feature.

**Comment by mckayERP** [comment]
@adaxa-steven, @sajeevsahadev, @sksanoopz, @marcalwestf 
Hi guys, I like the idea of using the server push for updates.

If you would like the change reverted, it is easy enough to do.  I'll update the pull request to bring it back.

**Comment by yamelsenih** [comment]
Hi @mckayERP can you add here a screenshot of Document Status after change it?

Best regard

**Comment by mckayERP** [comment]
It looks the same.  Haven't fixed the font/color yet.

![webui_dashboard_doctaskexample](https://user-images.githubusercontent.com/5507616/53293080-d71d7000-379b-11e9-953f-11aa72a6459c.PNG)

**Comment by adaxa-steven** [comment]
I was writing about this internally only yesterday and you seem to have part fixed ... by telepathy?
the screen shot is from an adaxa test system not pure adempiere...

![image](https://user-images.githubusercontent.com/15791084/53294884-97aa5e80-3843-11e9-9162-936a65bacb09.png)

**on the first panel** on left if I hover over (say) Sales management the background goes blue and I see a small hand with 1 finger extended ("the hand").

**on the second panel** ...

In Activities the background colour changes as I move over items and I see the 'Hand'

in Info Views the background colour does NOT change when I hover over things but I see the 'Hand' ... and some help text.

**on the third panel,** hovering over a Recent Item I see the 'Hand', some help text ... but the background colour does not change

**on the fourth panel** on right on Doc Status I see the following:

hover over a number or text ... and nothing changes except the cursor changes to a shape like a capital "I" ... so the user does not know it is a link.  .... if I move off the text onto a blank space immediately beside the text description of the Doc Status Indicator .. the cursor changes to an Arrowhead... but both positions work as a hotlink to open the window or form linked in the Doc Status Indicator definition.

I was asked by a non-adempiere person ..."why do we have all these different behaviours.. intentionally to confuse users?"
