### ISSUE TITLE
Webui Combination Dialog needs some attention.

### ISSUE THREAD

**Issue by mckayERP** [adempiere/adempiere#2379]
Its missing icons, a close button and needs to be sized properly.

![image](https://user-images.githubusercontent.com/5507616/53245470-c970c900-367b-11e9-814f-c199402355b5.png)

**Comment by marcalwestf** [comment]
@mckayERP you're very right.
Users get confused and don't see the icons, and click right awat the OK button, forgetting altogether to save.

Later they wonder that the changes supposedly done haven't been done at all!
