### ISSUE TITLE
Is Summary property by default in Print Format

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#238]
Is nice to have a print format that by default is summary or not, when the user select the print format, it is showed by default like is defined in print format.

**Comment by e-Evolution** [comment]
Hi Yamel , Is good idea to add  flag in print format to define is a report is show as summary or not, so +1 to this feature

**Comment by RJPC** [comment]
Hi Yamel, when a print format is created and the summary option this default and the report is generated is not presented as a summary, but when the report has multiple formats and is changed from one format to another if shown as a summary.

**Comment by yamelsenih** [comment]
Hi @RJPC it issue has been resolved, thank you for notify

**Comment by yamelsenih** [comment]
See the new changes: [Spin_Contribution: FR: Default Summary in Print Format](http://wiki.adempiere.net/Spin_Contribution:_FR:_Default_Summary_in_Print_Format)
