### ISSUE TITLE
Project Status: Next Status not Filtered by Project Status Category

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere#2382]
In the _Project Status Category_ window, _Project Status_ tab: when trying to set the _Next Status_, all Project Status defined are displayed, which shouldn't be:
![20190222_status_09](https://user-images.githubusercontent.com/1789408/53282356-1dbb8d80-36fc-11e9-9006-c62bbaf9dc88.png)

This is because there is no validation to filter with by the Project Status defined in the Project Status Category:
![20190222_status_10](https://user-images.githubusercontent.com/1789408/53282361-27dd8c00-36fc-11e9-889f-da5e25f56898.png)

The old validation doesn't apply any more, because the structure around _Project Status_ changed:
![20190222_status_11](https://user-images.githubusercontent.com/1789408/53282403-a9cdb500-36fc-11e9-9f75-104a5c6f3264.png)

So a new validation has to be defined.

**Comment by marcalwestf** [comment]
If we define the validation
```
C_ProjectStatus.C_ProjectStatusCategory_ID=@C_ProjectStatusCategory_ID@
AND C_ProjectStatus.C_ProjectStatus_ID!=@C_ProjectStatus_ID@
```
And set it to the column Next Status:
![20190222_status_12](https://user-images.githubusercontent.com/1789408/53282723-54e06d80-3701-11e9-86e6-ef0ec9960641.png)
(avoiding circular references)

The Next Status works as expected:
![20190222_status_13](https://user-images.githubusercontent.com/1789408/53282749-e8b23980-3701-11e9-9ebb-276c44495d40.png)

**Comment by yamelsenih** [comment]
Hi @marcalwestf is nice this change
