### ISSUE TITLE
Smart Browsers don't have an icon in the menu tree

### ISSUE THREAD

**Issue by mckayERP** [adempiere/adempiere#2389]
In the swing menu tree, smart browser windows appear as default tree items.

Suggest using the same icon as the Doc Action.

Its a two line change in MTreeNode to set the image icon type.  It has no impact on the webui which uses a different approach to set the icons in the menu.

**Comment by yamelsenih** [comment]
Hi @mckayERP can you add support to icon on ZK UI?

Best regard
