### ISSUE TITLE
NPE when select the new print format option

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#239]
When is selected the option ** New Print Format ** or ** Copy Print Format ** in Report view, launch a Null Pointer.

**Comment by e-Evolution** [comment]
Yamel what was here the commit that solve this or not was valid of bug

**Comment by yamelsenih** [comment]
Hi @e-Evolution i forgot set the reference in the commit, the commit is it https://github.com/adempiere/adempiere/commit/7f1292bab8637ca53ec07c837f41b5e2aa8804f1#diff-591149caf2371cb4bea22b6c9ac4785fR1192

Best regard
