### ISSUE TITLE
Calculate tax in incoming invoices

### ISSUE THREAD

**Issue by SusanneCalderon** [adempiere/adempiere#2391]
Hello,
We have a problem with the calculation of the taxes of purchase invoices.
In El Salvador the VAT is 13%, a number which provides a huge numeric problem when then tax is calculated with a lower precision than Adempiere.
So in some cases the calculated VAT diferres from the declared VAT in the incoming invoice.
Adempiere does not allow to modify the tax amount in MInvoiceTax, nonetheless it would be useless as the taxes are recalulated when you prepare or complete.
We worked with a additional invoiceline to correct the difference but it it not optimal as the tax report misses this line in the VAT report.
Solution:

- A process to modify the tax amount in a register of InvoiceTax and recalculate the grandtotal of the invoice.

- Prevent the recalculation in of the taxes when the docstatus in _IP_ and the docaction is _CO_
As it is a very special feature this behaviour can be controlled by SysConfig.

Comments and suggestions very welcome.

**Comment by yamelsenih** [comment]
Hi @SusanneCalderon ADempiere have a field for put tax from product I remember.
![screenshot_20190226_082503](https://user-images.githubusercontent.com/2333092/53412666-58455480-39a0-11e9-98b9-d0a2d0685592.png)
![screenshot_20190226_082522](https://user-images.githubusercontent.com/2333092/53412667-58455480-39a0-11e9-959b-88f7b55a10d0.png)

**Comment by SusanneCalderon** [comment]
@yamelsenih  
thank you.
