### ISSUE TITLE
MHRProcess: execution time of prepare 

### ISSUE THREAD

**Issue by SusanneCalderon** [adempiere/adempiere#2392]
Hello,
The method _Prepare_ in class HRProcess is complicated depending on the complexitiy of a payroll system. So naturally the executing time can be long. 
We recommend to our customers the execution of the payroll in two steps

- Prepare MHRProcess and calculate the MHRMovements. Send a provisional report to the employees.

- Complete MHRProcess
In this case it is convenient not to recalculate MHRProcess, in order to minimize the execution time. 
Solution:
Skip _prepare_ when the docstatus is _IP_ and docaction is _CO_
As a special feature this behavour can be controlled with Sysconfig.

Suggestions and comments very welcome.

**Comment by yamelsenih** [comment]
Hi @SusanneCalderon I don't sure if is good add a Sysconfig parameter.

I think tat can be a flag for payroll definition or inside process like "Recalculate"

**Comment by SusanneCalderon** [comment]
@yamelsenih 
Thank you, will do it.
