### ISSUE TITLE
MOrderline, MInvoiceLine. Numeric problem calculating a discount

### ISSUE THREAD

**Issue by SusanneCalderon** [adempiere/adempiere#2393]
Hello,
We are confronted with the following problem:
We work with a standard precision of 2 digits, for costing the precision is 4 digits.
When a product has a very low price (0.05 for example) the calculated discount of maybe 5% is 0.00 due to rounding to 2 digits. So we cannot calculate a discount for this type of products wich are sold with a low unit price and sold with a discount for large sales quantities. Tipical example is a screw. 
Origin of the problem

- Order of calculation if Adempiere, first calculate the price, then multiply with the quantity

- Round every line to the standard precision

Our solution

- Round the line to the pricelist precision. Then round the order/invoice to standard precision

Comments and suggestions very welcome

**Comment by yamelsenih** [comment]
Hi @SusanneCalderon we are a similar case with low price product, I don't sure if round is also by UON precision.

**Comment by SusanneCalderon** [comment]
Hi @yamelsenih 
Sorry, I did not see you answer.
The method amt in CalloutOrder defines the precision from the currency.		

int StdPrecision = MPriceList.getStandardPrecision(ctx, M_PriceList_ID);

```
public int getStandardPrecision()
	{
		if (m_precision == null)
		{
			MCurrency c = MCurrency.get(getCtx(), getC_Currency_ID());
			m_precision = new Integer (c.getStdPrecision());
		}
		return m_precision.intValue();
	}	//	getStandardPrecision
```

So in calloutOrder the price should be calculated first with a precision higher than the standardprocision and scale to the standard precision after multiplying price x quantity.
