### ISSUE TITLE
Dashboard Panel Recent Items has different look and feel

### ISSUE THREAD

**Issue by mckayERP** [adempiere/adempiere#2443]
There are too many different styles in the dashboard - trees, links, buttons - yet they all do the same thing.  This is confusing to the user.  The main menu and user favorites now look the same.  This issue is to track the updates to the Recent Items.  The goal is to use a flat tree instead of toolbarbuttons to present the items.  Then the look and feel will match the menu and user favorites.

**Comment by adaxa-steven** [comment]
Another UI thing that annoys users:
..if you tick multiple columns as selection columns (say on Payment) the selection panel can not be dragged bigger and its new size 'remembered' and the item you want is always the hidden one.
