### ISSUE TITLE
Smart Browse don't have the standard buttons

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#247]
The Smart Browse buttons does not have the size and location own ADempiere standard buttons

![issue82](https://cloud.githubusercontent.com/assets/2333092/13902975/6fc576ca-ee36-11e5-83f4-64d056c60975.png)
![issue83](https://cloud.githubusercontent.com/assets/2333092/13902976/6fc5e02e-ee36-11e5-96a5-aabe144a5cae.png)

**Comment by e-Evolution** [comment]
Hi Yamel , I am agree that using standard button, I reviewed the change and I think that is more nice that button of Ok and Cancel are centre in bottom of smart browser , so that avoid a displacement unnecessary of mouse to right screen. I will like that continue as before

**Comment by yamelsenih** [comment]
Hi @e-Evolution i was modified it, now are in center.

Thank you for the recommendation.
