### ISSUE TITLE
Add validation for Process Info create Adempiere Exception when client id not is setting 

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#2549]
Currently when a process info is created and a value is not set for the client's id this regrase null which causes NPE

**Comment by SusanneCalderon** [comment]
@e-Evolution , @yamelsenih 
Hello, since this change causes a NPE for the processes called in special forms and trialbalancedrilldown.
The error occurs when you call ProcessInfoUtil.setParameterFromDB (ProcessInfo pi) at line 236
```
if (pi.getAD_Client_ID() == null)
					pi.setAD_Client_ID (rs.getInt(10));
				if (pi.getAD_User_ID() == null)
					pi.setAD_User_ID(rs.getInt(12));
```

**Comment by SusanneCalderon** [comment]
@e-Evolution , @yamelsenih 
Hello, this change causes a NPE for the processes called in special forms and trialbalancedrilldown.
The error occurs when you call ProcessInfoUtil.setParameterFromDB (ProcessInfo pi) at line 236
```
if (pi.getAD_Client_ID() == null)
					pi.setAD_Client_ID (rs.getInt(10));
				if (pi.getAD_User_ID() == null)
					pi.setAD_User_ID(rs.getInt(12));
```
