### ISSUE TITLE
RUN_MigrationXML.bat is not workind send a terminate abnormally

### ISSUE THREAD

**Issue by lbetanzo** [adempiere/adempiere#2562]
[INFO] Initializing c3p0 pool... com.mchange.v2.c3p0.ComboPooledDataSource [ acquireIncrement -> 3, acquireRetryAttempts -> 2, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, dataSourceName -> AdempiereDS, debugUnreturnedConnectionStackTraces -> false, description -> null, driverClass -> org.postgresql.Driver, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, identityToken -> 1bqs5c1a21i6ppe39ybhjc|51cdd8a, idleConnectionTestPeriod -> 1200, initialPoolSize -> 10, jdbcUrl -> jdbc:postgresql://localhost:5432/adempiere?encoding=UNICODE, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 1200, maxIdleTimeExcessConnections -> 1200, maxPoolSize -> 150, maxStatements -> 0, maxStatementsPerConnection -> 0, minPoolSize -> 5, numHelperThreads -> 3, numThreadsAwaitingCheckoutDefaultUser -> 0, preferredTestQuery -> SELECT Version FROM AD_System, properties -> {user=******, password=******}, propertyCycle -> 0, testConnectionOnCheckin -> false, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, usesTraditionalReflectiveProxies -> false ]
19:56:53.631   CLogMgt.setLevel: CONFIG [1]
19:56:53.631   CLogMgt.setLevel: CONFIG [1]
19:56:53.848   GridField.loadLookup: (ReportType) [1]
19:56:53.848   GridField.loadLookup: (ReportType) [1]
19:56:54.477   MWorkflow.getDocValue: #1 [1]
19:56:54.477   MWorkflow.getDocValue: #1 [1]
19:56:54.850 Msg.initMsg: Records=1539 - en_US [1]
19:56:54.850 Msg.initMsg: Records=1539 - en_US [1]
org.adempiere.exceptions.AdempiereException: Process failed during execution Error:  User/Contact * Not found *
        at org.eevolution.service.dsl.ProcessBuilder.execute(ProcessBuilder.java:282)
        at org.adempiere.process.MigrationLoader.main(MigrationLoader.java:80)

*** 2019-05-16 19:56:54.876 Adempiere Log (CLogConsole) ***

terminated abnormally

**Comment by yamelsenih** [comment]
Hi @lbetanzo this issue was solved yet: #2573
