### ISSUE TITLE
Line with centralized id does not have uuid in the seed

### ISSUE THREAD

**Issue by rcapecce** [adempiere/adempiere#2564]
I'm testing a seed database created from the TAG392 source and importing a PackIn but I'm getting a Duplicate Key error in AD_Column.

This happened because this row (AD_Column_ID=92435) havn't a UUID and is in the seed, causing that ADempiere try to create it instead of update it.

In the table AD_Column ther are 71 rows without UUID with centralized ID.

**Comment by yamelsenih** [comment]
Please paste here SQL and result

**Comment by rcapecce** [comment]
Hi @yamelsenih, this is the SQL and result
`SELECT AD_Column_ID FROM AD_Column WHERE UUID IS NULL`

> 91976
> 91977
> 91978
> 91979
> 91980
> 92262
> 91968
> 91969
> 91970
> 91971
> 91972
> 91973
> 91974
> 91975
> 92219
> 92482
> 92486
> 92431
> 92523
> 92427
> 92524
> 92405
> 92406
> 92487
> 92488
> 92470
> 92472
> 92473
> 92474
> 92525
> 92528
> 92403
> 92415
> 92414
> 92416
> 92417
> 92418
> 92419
> 92420
> 92421
> 92422
> 92423
> 92424
> 92425
> 92404
> 92444
> 92471
> 92407
> 92408
> 92409
> 92410
> 92411
> 92412
> 92426
> 92430
> 92429
> 92432
> 92435
> 92433
> 92434
> 92436
> 92437
> 92438
> 92439
> 92440
> 92441
> 92442
> 92443
> 92428
> 92263
> 92413

The procedure that I ran was the following

1. Build an installer with develop
2. Mount the seed database
3. Run the RUN_MigrateXML.sh to update the seed
4. And then run the "Generate Surrogate Keys UUID for al tables" Process.

This process generated the next log, among other records, the 71 AD_Columns_ID
[GenerateSurrogateKeys_20190527.log](https://github.com/adempiere/adempiere/files/3228024/GenerateSurrogateKeys_20190527.log)

Next, I ran the "Export  Surrogate Key To Migration" process to be able to generate the XML file.

Can you check this procedure and validate if it is incorrect. In other case can you explain me the correct way to do this?

**Comment by rcapecce** [comment]
You mean edit the process?
The "Generate Surrogate Key" process actually don't generates already the missing uuid only?

**Comment by yamelsenih** [comment]
Hey, I add two pull request:

#2589 that allows generate UUID missing only
#2590 fix problem with missing UUID
