### ISSUE TITLE
The accounting information screen does not show the accounting entries when a accounting dimension User Element is defined

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#2598]
## Bug report
ADempiere has the functionality to define two dimensions per context User Element 1 and User Element 2, although accounting is currently generated The accounting information screen does not show the accounting entries when an accounting dimension is defined User Element 1 or 2
#### Steps to reproduce

1.- Add the field of M_ProductSpent_ID In the window of invoices vendor in the tab of  invoice line

<img width="1548" alt="image" src="https://user-images.githubusercontent.com/786968/58654015-9b370100-82dc-11e9-98a1-6a4f68aba89f.png">

2.- Add a new accounting dimension User Element 1 linked to the new column created

<img width="1550" alt="image" src="https://user-images.githubusercontent.com/786968/58654433-81e28480-82dd-11e9-9817-ef8a2c0b8bd1.png">

3.- Create an invoice and fill in the new field created within the invoice line and complete the invoice

<img width="1404" alt="image" src="https://user-images.githubusercontent.com/786968/58654389-60819880-82dd-11e9-958d-a0b0de7b72fd.png">

4.- Call the post button to show accounting

<img width="1545" alt="image" src="https://user-images.githubusercontent.com/786968/58654596-dede3a80-82dd-11e9-8d14-e6403952d7fc.png">

#### Expected behavior
The expected behavior is to register the value of the new dimension and show the accounting facts

#### Other relevant information
- Your OS: MacOS
- Java version: 1.8.0
- ADempiere version: 3.9.0
- DB Provider: PG
- DB version: 9.6

**Comment by yamelsenih** [comment]
Test ok
