### ISSUE TITLE
Java GUI swing component should be placed in client folder rather in base folder

### ISSUE THREAD

**Issue by ayazbaloch** [adempiere/adempiere#2618]
Dear @e-Evolution, @yamelsenih and @mckayERP I have noticed swing components classes are resided in base folder rather in client folder. base folder is for model classes.

My suggestion is given below

**base/src/org/compiere/swing ---> client/src/org/compiere/swing**

please let me update ur comments.

**Comment by yamelsenih** [comment]
Hi @ayazbaloch have you a example? print screen or direct url from git repo?

If you have a pull request is better..


Best regard

**Comment by ayazbaloch** [comment]
Dear @yamelsenih  thanks for prompt response, Adempiere has two client gui and web while all web files are resided in zkwebui folder and gui files are resided in client folders but some gui components files are resided in base folder. see below image.

![filemoving](https://user-images.githubusercontent.com/10656336/58982493-02c5e280-87ee-11e9-8077-7bf51d7af17c.png)

**Comment by ayazbaloch** [comment]
Only one file is sharing on both client interface (GUI and web) which is CEditor.java resides in client/src/org/compiere/swing
