### ISSUE TITLE
Serious error when validating the price limit in the sales order or invoice line

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#2620]
## Bug report
Currently for the system validates that it is not possible to sell below the limit price when the "EnforcePriceLimit" flag is activated and the role of the user entering the sales order has not activated the flag to overwrite price limit.

This works only the first time that a line is entered and a price is placed below the limit.

but once the line was captured the salesperson can re-enter the order sales line in other time and change the price below the price limit and the system allow to erroneously entry and save a price below the limit, which is completely incorrect.

#### Steps to reproduce

1. Create a new Sales Order
2. Add a new line for Azalea Bush and modify the price by 6 USD
<img width="1545" alt="image" src="https://user-images.githubusercontent.com/786968/58991348-aa6ef080-87ad-11e9-8af2-57cd61c63eaf.png">

<img width="1549" alt="image" src="https://user-images.githubusercontent.com/786968/58991407-cffbfa00-87ad-11e9-9c10-90c6d06f9231.png">

3. Close the window for this Sales Order
4. Get the previos Sales Order and go the line 
5. Change the price under price limit 6 USD and system allow to save new price

<img width="1549" alt="image" src="https://user-images.githubusercontent.com/786968/58991511-09346a00-87ae-11e9-8004-53f2d2820be7.png">

#### Other relevant information
- Your OS: MacOS
- Java version: JDK 8
- ADempiere version: All
- Browser  safari
- DB Provider: PG
- DB version: ALL

**Comment by yamelsenih** [comment]
Hi @e-Evolution the same problem is with reservation for product, the callouts are not for validate, just can be used as notification :(

**Comment by e-Evolution** [comment]
Hi Yamel @yamelsenih the reservation for a product is different because is made in the background when a sales order is completed, the product prices are validated online or interactively, Why? because is necessary to  check all prices actually, discount, tax, total lines in this moment

**Comment by yamelsenih** [comment]
The problem is that if you have a process for generate order from a
smartbrowser or any process the validation is not applied because level is
controller and not model

**Comment by e-Evolution** [comment]
@yamelsenih yes if need to validated online or interactively, need set in controllers.

And for domain model I think that are implementing is in MProductPricing that is used for calculating prices.

But this I think that is other problem
