### ISSUE TITLE
Option of the text message in the template of the Payroll report

### ISSUE THREAD

**Issue by wdtz** [adempiere/adempiere#2666]
The option of the text message (See Image 01) is considered an improvement in the template of the Payroll report (See Image 02)

Allowing to show in the report the text message by template.

Image 01
![image](https://user-images.githubusercontent.com/9578152/60612111-edfd5000-9d95-11e9-8d5b-d89fb29febd3.png)

Image 02
![image](https://user-images.githubusercontent.com/9578152/60612190-12f1c300-9d96-11e9-87fc-54b11266e73b.png)

**Comment by yamelsenih** [comment]
This is in core
