### ISSUE TITLE
Smart Browse don't have a Sequence Tab for Search Criteria Fields

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#267]
If you can have a **sequence** for search criteria fields distinct that table sequence, it is not supported currently

**Comment by yamelsenih** [comment]
Now you can define the order for query criteria parameters like show the image bellow
![issue93](https://cloud.githubusercontent.com/assets/2333092/14058105/53a6d8e2-f2e8-11e5-9d87-928a22fa866a.png)

**Comment by e-Evolution** [comment]
Yamel , is necessary modify the BrowserField handled to 2pack , this should integrate for 2pack

**Comment by e-Evolution** [comment]
Any change in model need be implement for 2 pack for any component application dictionary

**Comment by yamelsenih** [comment]
Hi @e-Evolution i think that the 2pack is own bad definition, ADempiere have a Aplication Dictionary where is the meta-data of tables and column.
