### ISSUE TITLE
Remove functionality to support isPrePayment and CreditSale

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#2682]
#Bug report 
This commit previos remove important functionality 

631308e7cbb2bf76edf7905ce521252874c70c7b
69b831bad22995205c261793ff69b16e30bdb050

@Raul-mz can please revert or integrate the functionality removed

Previously, the functionality of pre-payments and credit sales from the point of sales was implemented and was removed without reason.

#### Screenshot or Gif
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/786968/61832011-555a6d00-ae35-11e9-8b41-d7983e27fb3e.png">

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/786968/61832022-5f7c6b80-ae35-11e9-99eb-3f1b657fc934.png">

#### Other relevant information
- Your OS: MacOS
- Java version: 1.8
- ADempiere version: 3.9.2
- Browser chrome, safari
- DB Provider: PG
- DB version:  11.2

**Comment by Raul-mz** [comment]
the functionality was removed in the following commit:
https://github.com/adempiere/adempiere/commit/848657ea5b767d7cc4f4a1641a15e3c26b2c249a#diff-d01e79c7de0fbfa80ec1ea5b9e519676R257
