### ISSUE TITLE
Packout doesn't generating translation for workflow

### ISSUE THREAD

**Issue by rcapecce** [adempiere/adempiere#2702]
#  Bug report
When the "2PACK_HANDLE_TRANSLATIONS" system configuration flag is "Y", the packout process generate the translation for window, tab, etc, but no for the AD_WF_Node table, the packout XML has no lines to load the AD_WF_Node_Trl table.

#### Steps to reproduce
1. Set the "2PACK_HANDLE_TRANSLATIONS" system configuration flag to "Y".
2. Create a packout with a row of packout detail with type workflow and select a workflow.
3. Export the packout to filesystem as XML.

#### Screenshot or Gif
![Peek 07-08-2019 12-33](https://user-images.githubusercontent.com/14218144/62636599-35847800-b910-11e9-9896-fd5986b83d10.gif)

#### Expected behavior
The XML should have lines with the translations of the workflow nodes.

**Comment by yamelsenih** [comment]
Fixed here: https://github.com/adempiere/adempiere/pull/2719
