### ISSUE TITLE
Error in where clause for Smart Browser causing by Refactor

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#275]
1.- Create a Smart Browser any View
2.- Define Where clause for Smart Browser
3.- Define Smart Browser Is Execute Query By Default 
4.- Define Concesible by Default

**Comment by e-Evolution** [comment]
introducing 58b26a46c2631423e29280dbd5521eebad2ba481

**Comment by yamelsenih** [comment]
Hi @e-Evolution Thank you, i will look it issue and push the changes

**Comment by e-Evolution** [comment]
at org.eevolution.form.VBrowser$Worker.run(VBrowser.java:682)
','Y',100,1020445,'OpenJDK 64-Bit Server VM 25.66-b17','E','La Pastora|GardenWorld|SYSTEM|','C3U1927B7702P2187I1619L2157M1884',1000000,1000006)<= <INSERT INTO AD_Issue (ReleaseNo,OperatingSystemInfo,DatabaseInfo,DBAddress,Remote_Host,IssueSummary,SourceClassName,Created,SourceMethodName,LoggerName,Name,Remote_Addr,UserName,Updated,UpdatedBy,Processing,Processed,Local_Host,Version,Record_ID,ReleaseTag,ErrorTrace,StackTrace,IsActive,CreatedBy,AD_Issue_ID,JavaInfo,SystemStatus,ProfileInfo,StatisticsInfo,AD_Client_ID,AD_Org_ID) VALUES ('3.8.0LTS','Mac OS X 10.11.4 unknown','9.5.0;PostgreSQL 9.3 JDBC4.1 (build 1102);DS','jdbc:postgresql://192.168.3.245:5432/erp?encoding=unicode','.','org.postgresql.util.PSQLException: ERROR: syntax error at or near "AND"
  Position: 1167 SELECT DISTINCT cctl.AD_Client_ID AS CCTL_AD_Client_ID, cctl.AD_Org_ID AS CCTL_AD_Org_ID, cctl.AD_Reference_ID AS CCTL_AD_Reference_ID, cctl.Created AS CCTL_Created, cctl.CreatedBy AS CCTL_CreatedBy, cctl.Description AS CCTL_Description, ttl.AD_Client_ID AS TTL_AD_Client_ID, ttl.AD_Org_ID AS TTL_AD_Org_ID, ttl.AD_Reference_ID AS TTL_AD_Reference_ID, ttl.Created AS TTL_Created, ttl.CreatedBy AS TTL_CreatedBy, ttl.Description AS TTL_Description, ttl.EntityType AS TTL_EntityType, ttl.Name AS TTL_Name, ttl.Updated AS TTL_Updated, ttl.UpdatedBy AS TTL_UpdatedBy, ttl.ValidFrom AS TTL_ValidFrom, ttl.ValidTo AS TTL_ValidTo, ttl.Value AS TTL_Value, cctl.ValidFrom AS CCTL_ValidFrom, cctl.ValidTo AS CCTL_ValidTo, cctl.Value AS CCTL_Value, ttl.IsActive AS TTL_IsActive, cctl.EntityType AS CCTL_EntityType, cctl.IsActive AS CCTL_IsActive, cctl.Name AS CCTL_Name, cctl.Updated AS CCTL_Updated, cctl.UpdatedBy AS CCTL_UpdatedBy, ttl.AD_Ref_List_ID AS TTL_AD_Ref_List_ID, cctl.AD_Ref_List_ID AS CCTL_AD_Ref_List_ID, 0.0 AS TTL_Amount, '''' AS TTL_ReferenceNo FROM  AD_Ref_List ttl LEFT JOIN AD_Ref_List cctl  ON (cctl.AD_Reference_ID = 149 AND ttl.AD_Ref_List_ID = 400)  WHERE  AND ttl.AD_Client_ID IN(0,1000000) AND ttl.AD_Org_ID IN(1000003,1000025,1000004,1000026,1000005,1000027,1000006,1000028,1000021,1000000,1000022,1000001,1000002,1000024,1000007,1000029,1000008,1000009,1000020,1000014,1000036,1000015,1000037,1000038,1000016,1000017,1000010,1000032,1000011,1000033,1000012,1000034,1000013,1000035,1000018,1000019,0,1000030,1000031) AND (ttl.AD_Ref_List_ID IS NULL OR ttl.AD_Ref_List_ID NOT IN ( SELECT Record_ID FROM AD_Private_Access WHERE AD_Table_ID = 104 AND AD_User_ID <> 100 AND IsActive = ''Y'' ))','org.eevolution.form.VBrowser$Worker',TO_DATE('2016-03-31 17:45:24','YYYY-MM-DD HH24:MI:SS'),'run','org.eevolution.form.VBrowser','?','.','?',TO_DATE('2016-03-31 17:45:24','YYYY-MM-DD HH24:MI:SS'),100,'N','N','Victors-Mac-Book-Pro.local/192.168.3.11','2015-03-01',1,'ADempiere',NULL,'org.postgresql.util.PSQLException: ERROR: syntax error at or near "AND"
  Position: 1167
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2198)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1927)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:561)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:419)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:304)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:76)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at reflect.Method.invoke(Method.java:497)
	at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
	at com.sun.proxy.$Proxy2.executeQuery(Unknown Source)
	at org.eevolution.form.VBrowser$Worker.run(VBrowser.java:682)
','Y',100,1020445,'OpenJDK 64-Bit Server VM 25.66-b17','E','La Pastora|GardenWorld|SYSTEM|','C3U1927B7702P2187I1619L2157M1884',1000000,1000006)> [41]
