### ISSUE TITLE
Bug - Sales Order Object Date errors clogging up log files

### ISSUE THREAD

**Issue by osdevguy** [adempiere/adempiere#2769]
#### Screenshot or Gif

![image](https://user-images.githubusercontent.com/32497646/64495131-1f166700-d296-11e9-8662-8386be13b10b.png)

#### Expected behavior

I expected no error on release 3.92

#### Other relevant information
- Your OS: Windows 10
- Java version:  1.8
- ADempiere version: 3.92
- Browser [e.g. chrome, safari]  - doesn't matter
- Browser Version [e.g. 22]
- DB Provider:  PG
- DB version:   11

**Comment by yamelsenih** [comment]
Hi @osdevguy have you a step by step for reproduce it?
