### ISSUE TITLE
Requesting of a new Manual for v3.8.0

### ISSUE THREAD

**Issue by ishanuda** [adempiere/adempiere#277]
Thought this is not the application related problem, I have gone through the each window field description available on the following link : **http://wiki.adempiere.net/Manual** and also it was very useful. 

But the problem is it is based on ADempiere 3.4.0s menu. 

Now with ADempiere 3.8.0 changes have made and those are not available with such description. or are there. 

If not can you please be kind enough to update the link content with the newly updated features.

**Comment by yamelsenih** [comment]
You can see it here: https://adempiere.github.io/
And here: https://adempiere.gitbook.io/docs/
