### ISSUE TITLE
I don't see Void,Reverse option in all documents like Payment, Invoice, Sale Order in new deployment of Adempiere 3.9.2 for GardenAdmin user

### ISSUE THREAD

**Issue by amirsaifi** [adempiere/adempiere#2796]
Hi Geeks,
I have recently deployed ADempiere 3.9.2. I am experiencing an strange issue. After completion of documents Payment, Sales Order, Invoice etc document action is only showing 'Close' option. I have check the Document Action rights for GardenAdmin and find no issue in it. Any Clue to resolve this issue? Is there any other configuration required in 3.9.2 to make other document action options available in option list after completion of document.

Thanks in advance.
Amir Saifi

**Comment by yamelsenih** [comment]
Hi @amirsaifi I remember this problem and was fixed here: https://github.com/adempiere/adempiere/pull/2563 please confirm it

**Comment by amirsaifi** [comment]
thanx @yamelsenih  its done.
your support is appreciated.
