### ISSUE TITLE
GridController in swing will not set value to null

### ISSUE THREAD

**Issue by mckayERP** [adempiere/adempiere#283]
When responding to a vetoable change, the grid controller test for veto conditions, including user confirmations if required.  If there are none, it sets the value of the field in the grid table model.  However, if the new value is null, it will not set the field value, making it difficult to delete fields that don't set their own values directly.

Fix is to set the field value to null if there is no veto.

**Comment by mckayERP** [comment]
Merged #292

**Comment by e-Evolution** [comment]
The change not work with any mandatory filed and new record

**Comment by mckayERP** [comment]
The issue is with the VMemo field which does not follow the standard approach.  I'll create another issue to address it specifically.  The problem is also that text fields return empty strings instead of null values so when the firevetoablechange function is called after a value has been deleted, the new value will be an empty string.   The test to set the field value to null needs to test for both null and empty strings in the new value and non-null, non-empty strings in the old value.

**Comment by mckayERP** [comment]
I think this issue can be closed.
