### ISSUE TITLE
[Feature Request] Add group for Business Partner

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#2865]
## Feature request
I want to open discution for add more classification for Business Partner Table. Now this table only have a classification **C_BP_Group_ID** (For Accounting and default values on Customer and vendor like proce list and other).

The reason for it is allows generate reports like Invoice Summary, Invoice Line and Margin and other reports for it.
#### Describe the solution you'd like
- Add **C_Channel_ID** on **C_BPartner**: This can be usefull for list all invoices for a channel from BP
- Add a new column named **C_BP_Category_ID** a free field for a new group of bpartner
- Add a new column named **C_BP_Type_ID** a free field for a new group of bpartner
#### Describe alternatives you've considered

None
#### Additional context

Is nice to have more classification for BP.

**Comment by adaxa-steven** [comment]
Agree, it is good to have extra ways to classify a BP.

Also we found this change useful... 
Add 'Parent_BP_ID' to the BPartner table.

We used it in two ways.
(1) Our user sells to many companies who are subsidiaries of parent companies and in accounting fact reports (from Rv_FactAcct) it is easier to get the parent ID from a value stored directly on the BP record than having to navigate a Tree.. Also the Parent BP is a real trading BP also, not just a Summary record.

(2) It was also used when vendor invoices were imported from an external system. Many of the vendors were Franchisees and the payment needed to be made from adempiere to the Parent Company.  In this case we added 'Parent BP' to the 'Franchisee's  BPartner record,  and added 'Franchisee BP' to the vendor invoice record.  When the invoices were imported, the BP to be paid was set to the Parent BP ID and the Franchisee BP on the import was set on the C_Invoice for traceability.

If you are going to change the BP record perhaps you can add both columns?

**Comment by yamelsenih** [comment]
hi @adaxa-steven already exists **BPartner_Parent_ID** and can be used as a tree.

Here a first result:
![Screenshot_20191008_152930](https://user-images.githubusercontent.com/2333092/66427095-4f5e3c00-e9e1-11e9-9183-a5bb35652abf.png)
![Screenshot_20191008_152915](https://user-images.githubusercontent.com/2333092/66427097-4ff6d280-e9e1-11e9-91ea-9924f8eb1ef0.png)

**Comment by yamelsenih** [comment]
Here a image of table with **BPartner_Parent_ID**
![Screenshot_20191008_153626](https://user-images.githubusercontent.com/2333092/66427335-b4199680-e9e1-11e9-946c-d87b3ea83608.png)

**Comment by adaxa-steven** [comment]
oops ,.. I must have just found it and used it :-(
thanks for checking.

**Comment by e-Evolution** [comment]
@yamelsenih I agree but we need to use proper names, in many countries business partners can be people and it is not very well seen to classify or categorize people

I suggest the following:
Account type
market segment
Type of industry
sector.

**Comment by yamelsenih** [comment]
My proposal is:
- Account Type: this already exists on example
- Category
- Classification

The last both are more generic and can be used for Sales and Purchase Trx

**Comment by adaxa-steven** [comment]
These items:
..market segment
..Type of industry
..sector.
seem to be part of the existing NAIC/SIC code construct that is already on the BP record.
Perhaps it would be worthwhile add a table with these codes so people in different jurisdictions could add what they needed. We have done that for customers here. 

US version ... https://www.naics.com/sic-codes-counts-division/
AU/NZ version ... https://siccode.com/page/what-is-an-anzsic-code
I expect there is an equivalent in most jurisdictions.

**Comment by yamelsenih** [comment]
The approach of this issue is categorize a BP with others fields like C_BP_Group_ID instead

This change allows show all report like Invoce Summary and other with more gouping

SAP use terminology like:
- BP Category
- BP Classification
- BP Grouping

**Comment by PraponAon** [comment]
Agree,
When I export data into BI, I have to configure these settings to add dimensions or perspectives for executives.
