### ISSUE TITLE
[Bug Report] Report Parameter Range Date not working (adempiere to jasper)

### ISSUE THREAD

**Issue by dwisatrio** [adempiere/adempiere#2884]
I have done several experiments but still cannot. results after selecting a date, the report is empty. the code that I use in jasper is: `date (co.dateordered) between $ P {date1} and $ P {date2}`.

I've tried setting parameters in adempiere by filling in `$P{date1}` for parameter 1 and `$P{date2}` for parameter 2 in the parameter column

then what should be done to setup at adempiere so that the date that is filled in adempiere can be sent to jasper.

> For more information :
> DB : Postgresql
> Tools : Jaspersoft Studio

thx before for all.

**Comment by dwisatrio** [comment]
Okay, thank you. I will learn from #149

**Comment by dwisatrio** [comment]
The problem is resolved, thank you very much.

Best regards.

**Comment by yamelsenih** [comment]
Very good, you are welcome
