### ISSUE TITLE
Any one working with adempiere faced an issue that, when any window opens  a default value '5567' appears in DocumentNo field. Couldn't understand the cause and the solution!

### ISSUE THREAD

**Issue by laila588** [adempiere/adempiere#2904]
Question
Asking questions about use

#### Other relevant information
- Your OS:
- Java version:
- ADempiere version:
- Browser Version [e.g. 22]
- DB Provider:
- DB version:

**Comment by mckayERP** [comment]
Hi laila,  what version are you using?

Generally, when a new record is created, the fields are set to default values.  There are a number of places to look to see where these are set:

- Check the table/column for the document number default logic.
- Look at any callouts or scripts assigned to the table
- Look for any model validators that may access that table/document
- Check the sequence for any strange settings

**Comment by mckayERP** [comment]
Apparently, the issue was a user preference set on the Document Number field inadvertently.  Deleting the preference fixed the issue.
