### ISSUE TITLE
Implentar Reporte Jasper en Idempiere

### ISSUE THREAD

**Issue by Marcha1** [adempiere/adempiere#2905]
Buenas tardes necesito ayuda para lograr generar un reporte en idempiere con un proceso jasper.

he hecho todo el proceso arme el reporte en jasper estudio 6.10, agregue el Record_Id en la consulta, compilo el reporte lo, hice informe y procesos con el usuario system agregue la clase: org.compiere.report.ReportStarter, adjunte el archivo.jasper agregue el attachment:archivo.jasper, reinicio cache, luego en fomato de impresion agrego el proceso jasper creado, reinicio la cache genera el reporte pero en blanco, no tengo errores en el postgres, he buscado respuestas pero ya no se  que hacer, si me pueden ayudar se los agradezco.

**Comment by marcalwestf** [comment]
@Marcha1 I think you should put your issue to the correct project .
