### ISSUE TITLE
Report viewer re-query

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#295]
Is nice have in the report viewer a button for re-launch the process parameter and change values without exit of report

**Comment by e-Evolution** [comment]
Hi Yamel , I am agree is a good functionality , and only should be add for report , in case of process the system should always finish to avoid execute same process two times that can be a problem some process

**Comment by yamelsenih** [comment]
Wiki of new changes: [Spin Contribution: FR: ReQuery in Print Format](http://wiki.adempiere.net/Spin_Contribution:_FR:_ReQuery_in_Print_Format)
