### ISSUE TITLE
Navigating through tabs 392 y 393

### ISSUE THREAD

**Issue by AlbertoAbudinen** [adempiere/adempiere#2953]
## Bug report
Navigating through tabs, sometimes it causes the records to be changed, for example working with an order when adding lines and returning to the header, ADempiere change the header to another. (Issue in web version and java).

#### Other relevant information
- Your OS: windows 8
- Java version: jdk1.8.0_241
- ADempiere version: 392 y 393
- Browser [e.g. chrome, safari] chrome / Firefox
- Browser Version [e.g. 22]  Chrome Version 79.0.3945.130 (Official Build) (64-bit)
- DB Provider: Postgresql 
- DB version:  multiples 9.3 , 12 , ...

**Comment by rvergara** [comment]
This issue happens if you enter into a window via the search window, when you accept on the search window to create a new register, ADempiere wrongly sets the filter to the defaul record set in the filter window.
The filter should be deactivated for new records

**Comment by e-Evolution** [comment]
Hi @rvergara, I would confirm the behaving, this happens when the filter icon is activated, the rightly behaving is that always when a new record is created any filter should be off.

Now create the patch to solve this issue.

**Comment by rvergara** [comment]
We tested in both test and production customer instances and the patch did work very well. thanks
