### ISSUE TITLE
Create From in all windows must be like Smart Browse

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#296]
The **Create From** form is nice to have like Smart Browse, it is better for handle mantenance.

**Comment by e-Evolution** [comment]
Hi Yamel I am agree we would remove all hard code that exist in info form

**Comment by yamelsenih** [comment]
Here a list of **Create From** to be removed:

1. Create From Invoice (The class **VCreateFromInvoiceUI** will be deprecated).
2. Create From Shipment (The class **VCreateFromShipmentUI** will be deprecated).
3. Create From RMA (The class **VCreateFromRMAUI** will be deprecated).
4. Create From Statement (The class **VCreateFromStatementUI** will be deprecated).

The **VCreateFromFactory** was yet deprecated in issue #114 
The next issue will be for change each **Create From** by **Smart Browse**.
