### ISSUE TITLE
Payment Selection must be like ADempiere Document

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#297]
The **Payment Selection** currently is a standard table and it does not have **Document Action**, it cause many trouble when you try void it or when it is handle in ADempiere

**Comment by e-Evolution** [comment]
Hi Yamel , THE Payment selection is necessary have control of approval process is ok to add all fields that allows to management a ADempiere document standard. So we need add fields.

C_DocType_ID
DocDate or DateTrx
DocAction
DocStatus 
ProcessedOn
Processing is currently 
Processed is currently 
Posted 

if now payselecion will be a document then is necessary create your respective workflow document

About of functionality would be nice add support the multiple currencies and prepayment 

So I think that can add the prepayment flag and the C_Currency_ID when the invoice have a different currency that not is same that bank account.

kind regards
Victor

**Comment by e-Evolution** [comment]
I forgot, if this applies to C_PaymentSelection the same thing should be done to HR_PaymentSelection

**Comment by yamelsenih** [comment]
Hi @e-Evolution i think that the **HR_PaySelection** can be supported in C_PaySelection

**Comment by yamelsenih** [comment]
Wiki of new changes: [Spin Contribution: FR: Payment Selection Like Document](http://wiki.adempiere.net/Spin_Contribution:_FR:_Payment_Selection_Like_Document)

**Comment by e-Evolution** [comment]
The pay selection manual not should be deprecated , a lot of user use this to print check in short , use new window simple selection invoice and pay is a large process.

**Comment by e-Evolution** [comment]
I revert the last commit , @yamelsenih  will add a new smart browser with same functionality  

Is important that the new smart browser emulate the same functionality of payment selection manual

![captura de pantalla 2016-08-17 a las 7 50 42 p m](https://cloud.githubusercontent.com/assets/786968/17758335/09f12a02-64b4-11e6-9c85-022bdabf36df.png)

**Comment by yamelsenih** [comment]
Hi everybody, the change is done.

Best Regards
