### ISSUE TITLE
Instance saved, is not supported for swing UI

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#299]
The new feature for process panel showed in the following image, is not supported in swing GUI
![issue100](https://cloud.githubusercontent.com/assets/2333092/14271029/08e0fa9e-fabe-11e5-842a-c73ad7282ef4.png)

The swing GUI
![issue99](https://cloud.githubusercontent.com/assets/2333092/14271032/15f83f30-fabe-11e5-90a2-540cba10515c.png)

**Comment by e-Evolution** [comment]
Hi Yamel.

Other good idea is add the combo box to select the print format or report view, even would be improve that the parameters panel can are always be accessible and only may be  hide using a collapsed panel , the same way that the filters in the smart browser , this way the viewers under the promoter panel and user only can change a parameter and execute again the report.

kind regards 
Victor

**Comment by Raul-mz** [comment]
Currently has a button to save the parameters
![image](https://cloud.githubusercontent.com/assets/9552217/25352413/f1bed8e8-28f9-11e7-9de5-4a5684750304.png)
Now save the parameters pressing ok button.
![image](https://cloud.githubusercontent.com/assets/9552217/25352456/14f64b8e-28fa-11e7-9754-a538868dd572.png)

**Comment by Raul-mz** [comment]
Now in swing UI 
![image](https://cloud.githubusercontent.com/assets/9552217/25353033/f455628c-28fb-11e7-969f-e7187f2052a3.png)

**Comment by e-Evolution** [comment]
The new process dialog for ZK added the print format 

![captura de pantalla 2017-04-25 a la s 01 17 37](https://cloud.githubusercontent.com/assets/786968/25371198/073ac7d0-2955-11e7-86ab-2bdaccd2b9e2.png)

**Comment by yamelsenih** [comment]
Hi Victor it is other issue

**Comment by yamelsenih** [comment]
Hi Victor it is other issue

**Comment by e-Evolution** [comment]
Hi @Raul-mz  and @yamelsenih , @adaxa-steven  send me an image where they introducing improves for process dialog the improve allow reducing the memory and traffic between server and cliente.

When Steven send me the url to code will be good intruding this way in ADempiere

![img_26042017_082054_0](https://cloud.githubusercontent.com/assets/786968/25410820/a9d148dc-29de-11e7-854a-324f736fbf43.png)
