### ISSUE TITLE
NPE when try create fields for a GridTabVO

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#3045]
## Bug report

When try create fields for a GridTabVO got NPE

#### Steps to reproduce

Log trace :

===========> zkoss.handleError:1130: >>java.lang.NullPointerException
>>      at org.compiere.model.GridTabVO.createFields(GridTabVO.java:230)
>>      at org.compiere.model.GridTabVO.getFields(GridTabVO.java:340)
>>      at org.compiere.model.GridTab.loadFields(GridTab.java:370)
>>      at org.compiere.model.GridTab.loadTab(GridTab.java:313)
>>      at org.compiere.model.GridTab.initTab(GridTab.java:304)
>>      at org.compiere.model.GridWindow.initTab(GridWindow.java:195)
>>... [14327]
-----------> Msg.getMsg: NOT found: QuickEntry [287]
===========> zkoss.handleError:1130: >>java.lang.NullPointerException
>>      at org.compiere.model.GridTabVO.createFields(GridTabVO.java:230)
>>      at org.compiere.model.GridTabVO.getFields(GridTabVO.java:340)
>>      at org.compiere.model.GridTab.loadFields(GridTab.java:370)
>>      at org.compiere.model.GridTab.loadTab(GridTab.java:313)
>>      at org.compiere.model.GridTab.initTab(GridTab.java:304)
>>      at org.compiere.model.GridWindow.initTab(GridWindow.java:195)
>>... [15336]
-----------> Msg.getMsg: NOT found: QuickEntry [14778]
===========> zkoss.handleError:1130: >>java.lang.NullPointerException
>>      at org.compiere.model.GridTabVO.createFields(GridTabVO.java:230)
>>      at org.compiere.model.GridTabVO.getFields(GridTabVO.java:340)
>>      at org.compiere.model.GridTab.loadFields(GridTab.java:370)
>>      at org.compiere.model.GridTab.loadTab(GridTab.java:313)
>>      at org.compiere.model.GridTab.initTab(GridTab.java:304)
>>      at org.compiere.model.GridWindow.initTab(GridWindow.java:195)
>>... [14331]===========> LayoutEngine.addY: Outside of Area: [Ljava.awt.geom.Point2D$Double;@5618c4ed [630]
===========> LayoutEngine.newLine: Outside of Area(2): Point2D.Double[36.0, 771.4375] [630]
-----------> Msg.getMsg: NOT found: QuickEntry [22107]
-----------> Msg.getMsg: NOT found: Load New Report Definition [630]
===========> zkoss.handleError:1130: >>java.lang.NullPointerException
>>      at org.compiere.model.GridTabVO.createFields(GridTabVO.java:230)
>>      at org.compiere.model.GridTabVO.getFields(GridTabVO.java:340)
>>      at org.compiere.model.GridTab.loadFields(GridTab.java:370)
>>      at org.compiere.model.GridTab.loadTab(GridTab.java:313)
>>      at org.compiere.model.GridTab.initTab(GridTab.java:304)
>>      at org.compiere.model.GridWindow.initTab(GridWindow.java:195)
>>... [14327]
-----------> Msg.getMsg: NOT found: QuickEntry [287]
===========> zkoss.handleError:1130: >>java.lang.NullPointerException
>>      at org.compiere.model.GridTabVO.createFields(GridTabVO.java:230)
>>      at org.compiere.model.GridTabVO.getFields(GridTabVO.java:340)
>>      at org.compiere.model.GridTab.loadFields(GridTab.java:370)
>>      at org.compiere.model.GridTab.loadTab(GridTab.java:313)
>>      at org.compiere.model.GridTab.initTab(GridTab.java:304)
>>      at org.compiere.model.GridWindow.initTab(GridWindow.java:195)
>>... [15336]
-----------> Msg.getMsg: NOT found: QuickEntry [14778]
===========> zkoss.handleError:1130: >>java.lang.NullPointerException
>>      at org.compiere.model.GridTabVO.createFields(GridTabVO.java:230)
>>      at org.compiere.model.GridTabVO.getFields(GridTabVO.java:340)
>>      at org.compiere.model.GridTab.loadFields(GridTab.java:370)
>>      at org.compiere.model.GridTab.loadTab(GridTab.java:313)
>>      at org.compiere.model.GridTab.initTab(GridTab.java:304)
>>      at org.compiere.model.GridWindow.initTab(GridWindow.java:195)
>>... [14331]

#### Screenshot or Gif
![image](https://user-images.githubusercontent.com/786968/75918840-10ae9f80-5e22-11ea-8e5d-34f36ee90723.png)

#### Expected behavior
Not should exist this problem , so change funcional programing to validate the NPE

**Comment by marcalwestf** [comment]
@e-Evolution  hi Victor, could you provide a step-by-step description how to reproduce the error?
Thanks !
