### ISSUE TITLE
Required Multi-Selection

### ISSUE THREAD

**Issue by wdtz** [adempiere/adempiere#306]
The option to perform a multi.selection on product information only accepted for orders (buy and sell) or Invoices (purchase and sale), however necessary in other windows, as an example exists:
Requisition
Quote Online
Restriction topic.

And many others will create a more dynamic option for other cases where necessary.

**Comment by yamelsenih** [comment]
Hi @wdtz I think that it can be defined like parameter option in the product information form.

**Comment by yamelsenih** [comment]
Currently is hardcode.

**Comment by yamelsenih** [comment]
I will be resolved on #668
