### ISSUE TITLE
[Bug Report] Schedule Process does not work Default Parameter in Process Parameters 

### ISSUE THREAD

**Issue by Raul-mz** [adempiere/adempiere#3138]
## Bug report

When Schedule Process is configured and default values are added to the Process Parameters, it does not execute them with the added values.

#### Steps to reproduce

1. Open Schedule Process (Create Record)
2. Add Parameters
3. Restart Server
4. Open adempiereMonitor and Execute Schedule Process

#### Screenshot or Gif
![image](https://user-images.githubusercontent.com/9552217/84519942-c8184500-aca0-11ea-8af5-cc707a3fd1e8.png)

![image](https://user-images.githubusercontent.com/9552217/84519876-ae76fd80-aca0-11ea-836b-d9c35caa4953.png)

Result:
![image](https://user-images.githubusercontent.com/9552217/84519782-8d161180-aca0-11ea-83ac-e8cab6d97a2d.png)

#### Expected behavior
It is expected that the process or report will be executed with the values in the parameters indicated in the Schedule Process 

#### Other relevant information
- Your OS: Debian 10
- Java version: open-jdk 8
- ADempiere version: 3.9.3
- Browser: chrome
- Browser Version: 74.0.3729.157 
- DB Provider: Postgresql
- DB version: 11

**Comment by yamelsenih** [comment]
Fixed here: #3162
