### ISSUE TITLE
Error zk (Read Only)

### ISSUE THREAD

**Issue by wdtz** [adempiere/adempiere#316]
When a window is read-only (processed, completed or not updatable) in  type search fields  the button remains active, allowing you to see the information in the records.

Swing should behave like buttons should be read-only.

**Comment by mckayERP** [comment]
Hi Wdtxz,  Thanks for reporting.  Can you explain what you mean?  In the case of completed documents, I think the buttons in search fields should remain active to show the info windows but the fields should be read only.  It this what you are seeing?

M

**Comment by yamelsenih** [comment]
Hi @wdtz @mckayERP i think that it is nice, if the information is disabled then you can't see more information of a search field.
