### ISSUE TITLE
[Bug Report] The workflow engine is not correctly handling transactions when processing documents

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#3170]
#Bug report

The workflow engine is not correctly handling transactions when processing documents

The reason is the incorrect handling of the transaction with which the workflow engine starts is not properly controlled.

When processing a workflow it generates audit logs to process the activities and execution events, these logs must be immediately committed to know the real status of a document and avoid multiple executions of the workflow simultaneously for the same document

#### Steps to reproduce
1.- Add break point any line of method completeIt of MOrder
2.- Start Adempiere debug mode
3.- Create a Sales Order and complete
4.- When stop the execution in break point , interrupt the execution
5.- Run again ADempiere and load same sales order and complete, an error is show Other Process Active
#### Screenshot or Gif

![Peek 2020-07-08 15-22](https://user-images.githubusercontent.com/2333092/86961558-6c21ce80-c12f-11ea-9daa-aeeae3e79df2.gif)

#### Expected behavior
This show that the work flow not can be starting because are running

![image](https://user-images.githubusercontent.com/786968/87018626-21d43800-c197-11ea-8228-238b61e16818.png)

#### Other relevant information
- Your OS: MacOS
- Java version: Java 8
- ADempiere version: 3.9.3
- Browser safari
- DB Provider: PG
- DB version: 12.2

**Comment by yamelsenih** [comment]
Hi @e-Evolution I tested this funcuionality and is OK for me.
Only a last change: please when a workflow is aborted it will should set to false the "Processing" flag. 

Best regards
