### ISSUE TITLE
[Bug Report] The Purchase Order window show the field not should be show

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#3180]
## Bug report
The Purchase Order window show the field not should be show

#### Steps to reproduce
1.- Open a Purchase Order

#### Screenshot or Gif

![image](https://user-images.githubusercontent.com/786968/88318025-c0a47c80-ccdf-11ea-94f5-fd88fd9363e0.png)

#### Expected behavior
This field not should be show

#### Other relevant information
- Your OS: macOS
- Java version: java 8
- ADempiere version: 3.9.3
- Browser [safari]
- DB Provider: pg
- DB version: 12.2

#### Additional context
the bug was introduced with script 04530_2435_BOMDrop.xml in the issue #2435

@mckayERP  Can please fixed this issue ?

**Comment by mckayERP** [comment]
Hi Victor,

I honestly don't know why those fields were included in the XML.  Yes, I will remove them.

Mike
