### ISSUE TITLE
Process parameter panel is showed without parameter

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#323]
In swing, when you press print button in tool bar, if the report of tab don't have parameters,  the process dialog is showed instead hide it

**Comment by e-Evolution** [comment]
'hotfix/3.8.0#002' of github.com:adempiere/adempiere:
  Fixed error with Access Date Level, it must be 4 reference to issue: #326
  Add Process Class Generator for allow generate Process Class from process application dictionary reference to issue: #326
  Change reference for translation in AD_ReportView reference to issue: #237
  Fixed error with process called from window, when it don't have parameters does not show reference to issue: #323
  Change underscore for better convention Reference to issue: #325
  Add helper methods for get parameters in process, something method
