### ISSUE TITLE
Process source code generated automatically

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#326]
Is nice to have a process that generate **automatically** the source code template of process, i think that may be like **ADempiere generate model** but from ADempiere application, then the **System Administrator** can make the following:

- Create ADempiere Process from Application Dictionary.
- Add class name for Process created.
- Press a button **Generate Template Process Class**.
- Set Path of source code.
- Go to source code and just write your custom code.

**Comment by yamelsenih** [comment]
Hi, you can see description and use here: http://wiki.adempiere.net/Spin_Contribution:_FR:_Process_Class_Generated

**Comment by e-Evolution** [comment]
The class generate should be abstract because of you write code in develop class and need add a new parameter not need modify manually 

On the other hand I change the name for variables, now use the parameter name folioing the standard java name and more DSL to natural language.

on the other hand I add the ProcessName and ProcessId to have a goal reference based on application dictionary , all the parameter was move to static and public types.

**Comment by e-Evolution** [comment]
This an example of end result:

```
/******************************************************************************
 * Product: Adempiere ERP & CRM Smart Business Solution                       *
 * Copyright (C) 1999-2007 ComPiere, Inc. All Rights Reserved.                *
 * This program is free software, you can redistribute it and/or modify it    *
 * under the terms version 2 of the GNU General Public License as published   *
 * by the Free Software Foundation. This program is distributed in the hope   *
 * that it will be useful, but WITHOUT ANY WARRANTY, without even the implied *
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.           *
 * See the GNU General Public License for more details.                       *
 * You should have received a copy of the GNU General Public License along    *
 * with this program, if not, write to the Free Software Foundation, Inc.,    *
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA.                     *
 * For the text or an alternative of this public license, you may reach us    *
 * ComPiere, Inc., 2620 Augustine Dr. #245, Santa Clara, CA 95054, USA        *
 * or via info@compiere.org or http://www.compiere.org/license.html           *
 *****************************************************************************/

package org.compiere.process;

import java.sql.Timestamp;


/** Generated Process for (Create Periods )
 *  @author Adempiere (generated) 
 *  @version Release 3.8.0
 */
public abstract class YearCreatePeriodsAbstract extends SvrProcess
{
	/** Process Name 	*/
	public static final String ProcessName = "Create Periods";
	/** Process Id 	*/
	public static final int ProcessId = 100;
 
	/**	Parameter Name for StartDate	*/
	public static final String StartDate = "StartDate";
	/**	Parameter Name for DateFormat	*/
	public static final String DateFormat = "DateFormat";

	/**	Parameter Value for StartDate	*/
	protected Timestamp startDate;
	/**	Parameter Value for DateFormat	*/
	protected String dateFormat;
 

	@Override
	protected void prepare()
	{
		startDate = getParameterAsTimestamp(StartDate);
		dateFormat = getParameterAsString(DateFormat);
	}
}
```

**Comment by trifonnt** [comment]
Java constants SHOULD be with name like:

/** Process Name    */
    public static final String PROCESS_NAME = "Create Periods";

**Comment by yamelsenih** [comment]
Hi @trifonnt I agree with you, for the process name and other constant is better use all in upper case, but for process parameter name is better use like is defined in application dictionary like is defined in X class of model class.

Best regards

**Comment by yamelsenih** [comment]
Is very nice validate parameter on SrvProcess when it is mandatory.

**Comment by yamelsenih** [comment]
Is nice add support to helper method of issue #352

**Comment by yamelsenih** [comment]
Wiki of new changes: [Spin Contribution: FR: Process Class Generated](http://wiki.adempiere.net/Spin_Contribution:_FR:_Process_Class_Generated)
