### ISSUE TITLE
Validate Ordered and Reserved Quantities Inventory

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#3267]
## Feature request
Validate Ordered and Reserved Quantities Inventory
- Clean the Ordered and Reserved quantity from Inventory Storage
- Calculate the Ordered Quantities for Orders (PO, MO, DO) with Status In process and Completed
- Calculate the Reserved Quantities for Orders(SO,MO,DO) with Status In process and Completed

#### Additional context

<img width="1599" alt="image" src="https://user-images.githubusercontent.com/786968/100284738-44dc6a00-2f35-11eb-8aee-a11e2745d73d.png">

**Comment by yamelsenih** [comment]
Hi @e-Evolution I don't know if it is necessary because your shoud must resolve the original problem if a Sales Order not post a reserved quantity correctly then is better resolve it instead create a process for a legacy problem.

**Comment by e-Evolution** [comment]
Hi @yamelsenih Yamel, yes, the original problem was solved here #3266, but the customer that has a problem with ordered and reserved quantities need a way to fix that now is incorrect.

This similar the process validate Business Partners that fixed balance amount.

this improve come to the customer that now are using the manufacturing functionality and distribution management and was found after of Available to Promise #3228

**Comment by yamelsenih** [comment]
Hi @e-Evolution I don't see the PR for this?
Also you should considerate other process that can generate reservation like Production

**Comment by e-Evolution** [comment]
@yamelsenih  Hi Yamel!

I don't know if the production functionality generates reservations. When I reviewed it, it was very simple, it only performed input and output operations for materials, and it did not handle any document status or reservation concept.

If this change, it would be better for someone who knows how this functionality works to implement or improve it.

thi functionality, which I think is incompletely implemented, I do not know if it is worth supporting, the maintainer of this is @marcalwestf Mario and he promised to maintain this functionality when the Adaxa thing was integrated, which by the way I think they do not work 100%, at least in Oracle not work some sql statements

In fact, if you ask me the production orders, it is redundant functionality that is partiality implemented, many of the things that this functionality try to solve is already solved by ADempiere manufacturing, I would vote to deprecate it.

If you still want to use this, I can gladly talk and guide @marcalwestf Mario to implement it.

For now it would be good if the standard and full ADempiere functionality works correctly, so you can do merge and then @marcalwestf Mario completes what is required for production orders if they handle reservations.

kind regards
