### ISSUE TITLE
ClientAccountingProcessor throws NPE with postgres

### ISSUE THREAD

**Issue by mckayERP** [adempiere/adempiere#3275]
The ClientAccountingProcessor is broken on databases that don't use the Oracle DUAL dummy table.

From line 133

			//get current time from db
			Timestamp ts = DB.getSQLValueTS(get_TrxName(), "SELECT getdate() FROM DUAL");
			//go back 2 second to be safe (to avoid posting documents being completed at this precise moment)
			long ms = ts.getTime()- (2 * 1000);

This returns a null timestamp form Postgres causing a NPE on line 136 that stops the process.

Recommend adding the following method to the DB.java to handle database specific details:

	public static Timestamp getCurrentTimeFromDatabase() {
		
		Timestamp ts = new Timestamp(System.currentTimeMillis());
		if (DB.isPostgreSQL())
			ts = DB.getSQLValueTS(null, "SELECT NOW()");
		if (DB.isOracle())
			ts = DB.getSQLValueTS(null, "SELECT getDate() FROM DUAL");
		if (DB.isMariaDB())
			ts = DB.getSQLValueTS(null, "SELECT NOW()");
		if (DB.isMySQL())
			ts = DB.getSQLValueTS(null, "SELECT NOW()");

		return ts;
		
	}

Then modify line 134 in ClientAcctProcessor.java to 

			Timestamp ts = DB.getCurrentTimeFromDatabase();

**Comment by e-Evolution** [comment]
@mckayERP Hi Mike!

I think that had other issue , I adding the testing SQL Statement convert and the multiples testing are working , can review with this commit aec4f46

```
15:54:18.783           DB_PostgreSQL.convertStatement: PostgreSQL =>SELECT CURRENT_TIMESTAMP<= <SELECT getdate() FROM DUAL> [87]
15:54:18.784           Trx.getConnection: Active=true, Connection=com.mchange.v2.c3p0.impl.NewProxyConnection@315fff08 [87]
15:54:18.785         QueryExecutorImpl.execute:   simple execute, handler={0}, maxRows={1}, fetchSize={2}, flags={3} (org.postgresql.jdbc.PgStatement$StatementResultHandler@5478d853, 0, 0, 1) [87]
15:54:18.785         QueryExecutorImpl.sendParse:  FE=> Parse(stmt=null,query="SELECT CURRENT_TIMESTAMP",oids={}) [87]
15:54:18.786         QueryExecutorImpl.sendBind:  FE=> Bind(stmt=null,portal=null) [87]
15:54:18.786         QueryExecutorImpl.sendDescribePortal:  FE=> Describe(portal={0}) (null) [87]
15:54:18.786         QueryExecutorImpl.sendExecute:  FE=> Execute(portal={0},limit={1}) (null, 0) [87]
15:54:18.787         QueryExecutorImpl.sendSync:  FE=> Sync [87]
15:54:18.789         QueryExecutorImpl.processResults:  <=BE ParseComplete [{0}] (null) [87]
15:54:18.790         QueryExecutorImpl.processResults:  <=BE BindComplete [{0}] (unnamed) [87]
15:54:18.790         QueryExecutorImpl.receiveFields:  <=BE RowDescription({0}) (1) [87]
15:54:18.790         QueryExecutorImpl.receiveFields:         {0} (Field(current_timestamp,TIMESTAMPTZ,8,T)) [87]
15:54:18.791         QueryExecutorImpl.processResults:  <=BE DataRow(len={0}) (29) [87]
15:54:18.791         QueryExecutorImpl.receiveCommandStatus:  <=BE CommandStatus({0}) (SELECT 1) [87]
15:54:18.792         QueryExecutorImpl.receiveRFQ:  <=BE ReadyForQuery({0}) (T) [87]
15:54:18.792         PgConnection.getTimestamp:   getTimestamp columnIndex: {0} (1) [87]
15:54:18.793         PgConnection.getString:   getString columnIndex: {0} (1) [87]

```

What version PostgreSQL using ?

**Comment by mckayERP** [comment]
@e-Evolution Hi Victor,

I saw the conversion code, but the call still returns null, as if the conversion is not being called.  I'll trace it and post the results here. It may take a day or two.

Mike

**Comment by mckayERP** [comment]
@e-Evolution Yes, it must have been another problem in my database.  I updated the database and wrote an integration test and have nearly full coverage of the ClientAcctProcessor code.  I can't reproduce the error.

![image](https://user-images.githubusercontent.com/5507616/104796610-a5de2c80-5785-11eb-9b21-434ce08365aa.png)

The code could be refactored using this test.
