### ISSUE TITLE
Travis build failed since commit 3ca4946

### ISSUE THREAD

**Issue by homebeaver** [adempiere/adempiere#3290]
Hi @yamelsenih , @marcalwestf 

![grafik](https://user-images.githubusercontent.com/3493126/103468726-8fcf7580-4d5c-11eb-9fc0-f14941456f57.png)

After this commit all travis builds fails! 

https://travis-ci.com/github/adempiere/adempiere/builds/211653957

![grafik](https://user-images.githubusercontent.com/3493126/103468824-927e9a80-4d5d-11eb-8bf1-df33859bd1d1.png)

Please have a look. Thanks EUGen

**Comment by e-Evolution** [comment]
fixed #3291
