### ISSUE TITLE
Add User 1 and User 2 Dimension for Report Source Type Combination

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#33]
Currently of Report Source Type Combination not support User 1 and User 2 dimension 
http://www.adempiere.com/New_Functionality_Financial_Report_Source_Type_Combination
Jira tracker 
https://adempiere.atlassian.net/browse/ADEMPIERE-431

**Comment by yamelsenih** [comment]
Hi @e-Evolution i think that it dimension must be any column with a **flag** for determinate his behavior, something like **IsGLDimension**, then when the column is a **GL Dimension** it can be apply for **Fact_Acct**.

**Comment by liosc** [comment]
Hi,
this issue has been created more than 2 years ago and it is still open. Did the commits solve the problem? If  tests are required, specify better the business case, please.

**Comment by adaxa-steven** [comment]
It was fixed in the code that 390 Fin Reports changes were based on but I did not check in 390. Will check in next 2 days.

**Comment by yamelsenih** [comment]
Hi, any update for it?

**Comment by adaxa-steven** [comment]
Hi Yamel, if you give me the URL of a running test system I will check it. regards..

**Comment by e-Evolution** [comment]
@yamelsenih 

This was implement for all system from 3.9.0
 for User 1 to User 4

![image](https://user-images.githubusercontent.com/786968/58441982-59277880-80ac-11e9-83c2-b8e04c2eb8c7.png)


![image](https://user-images.githubusercontent.com/786968/58442047-ef5b9e80-80ac-11e9-861d-9ad38f4e95c9.png)

**Comment by e-Evolution** [comment]
![image](https://user-images.githubusercontent.com/786968/58442065-1a45f280-80ad-11e9-83cd-34a6614dde42.png)


Also in column so @yamelsenih you can close

**Comment by yamelsenih** [comment]
Thanks @e-Evolution
