### ISSUE TITLE
Table name not found AD_System

### ISSUE THREAD

**Issue by San-Nabaty** [adempiere/adempiere#3307]
Hi,

i run run_setup.bat, everything fine and no errors, I also run Run_importadempiere.bat script ends with no issues and creates all of the tables into my database in Postgres. 

on the login window, I have a green check for database connectivity, but when trying to login it gives me an error Table name not found AD_System

the table does exist in the database with the name (ad_system)

not sure what the issue is and did try re-installing multiple times but same issue. what else should I check?

![login](https://user-images.githubusercontent.com/40336553/103817734-522e5d80-5078-11eb-952e-52b69cc07f1d.PNG)

**Comment by vdevsoft** [comment]
your  import is not complete, try my method.

DBeaver, pgAdmin-IV
create user adempiere as superuser.
create database demodb , user adempiere owner

cmd prompt
cd C:\Program Files\PostgreSQL\12\bin
psql -d demodb -U adempiere <C:\Adempiere\data\adempiere_pg.dmp

**Comment by San-Nabaty** [comment]
solved by simply changing the db owner to adempiere user
