### ISSUE TITLE
GardenWorldCleanUp not working as expected

### ISSUE THREAD

**Issue by mckayERP** [adempiere/adempiere#3309]
The GardenWorldCleanUp process, which is run at the end of the migration loader and is available in the System menu, if failing.

It is supposed to move the dates in GardenWorld so that they appear to be more recent.  The intent was to ensure the GardenWorld demo data was somewhat up-to-date.

The process is failing as not all the dates were being updated.  New documents were not being updated as the GardenWorldCleanUp code did not account for them.  As a result, the Garden World calendar kept shifting until dates for some documents no longer fall within existing periods.

The code needs to be refactored so it does not depend on particular table models and can discover the documents that need to change.

**Comment by marcalwestf** [comment]
this PR is a prerequisite to accepting https://github.com/adempiere/adempiere/pull/3434
