### ISSUE TITLE
Problem to try create a new company and generate costing detail caused by new cost level called warehouse 

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#332]

**Comment by trifonnt** [comment]
Victor can you please explain why the idea of costing?
It looks like you can have cost per warehouse now?
Is this right?

**Comment by e-Evolution** [comment]
Hi Trifon 

The new Costing level is use to have Costing layer for warehouse, this very usefull when need add landed  or overhead cost for múltiple warehouse that are a diferrent location.
