### ISSUE TITLE
[Bug Report] The Application Dictionary change incorrectly 

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#3334]
## Bug report

The Application Dictionary change incorrectly 

![image](https://user-images.githubusercontent.com/786968/105614590-f827da80-5d8f-11eb-825c-1171fec7d3f2.png)

I think that this bug was introducing in #3295 

#### Steps to reproduce
1.- Create a install with ADempiere 3.9.3
2.- Apply all xml migration script
3.- Login as System

#### Screenshot or Gif

Menu ADempiere 3.9.3
![image](https://user-images.githubusercontent.com/786968/105614720-a7fd4800-5d90-11eb-8f7a-3d9602ca20e1.png)

**Comment by marcalwestf** [comment]
hi @e-Evolution Victor, I did as you required and got the results you mentioned.

I wonder if this an error.
The PR https://github.com/adempiere/adempiere/pull/3295 puts the _Setup Definition_ window exactly under the _Menu/Application Dictionary_ folder.

The question would be if you wish the  _Setup Definition_ window to be moved in the Menu, and if yes, where to.
