### ISSUE TITLE
Build fails since merging PR  3328

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere#3345]
#### Steps to reproduce
1. Do run a _git checkout_ from commit 06b392d145904e7fe132eabce80913fd41fd1802  or from **any** newer commit up to latest commit.
The PR merged was _Merge branch 'feature/#3208_AddJunitJupiter' into develop_  https://github.com/adempiere/adempiere/pull/3328 
2. Do run a build
3. The build halts with an error:
```

BUILD FAILED
/..../adempiere/utils_dev/build.xml:21: The following error occurred while executing this line:
/..../adempiere/base/build.xml:218: junitlauncher doesn't support the "excludeTags" attribute

Total time: 1 minute 32 seconds
```

#### Error Screenshot
![Selection_990](https://user-images.githubusercontent.com/1789408/106016422-112cd600-6085-11eb-8b67-e5f9f1d8561f.png)

#### Expected behavior
An error-free build is expected, like up to commit 951bd5ea4847b16b186ad3e7d004b4c02995b7a4 (Merge branch 'develop' of Github adempiere/adempiere into develop).
See successful build:
![Selection_989](https://user-images.githubusercontent.com/1789408/106016827-7aace480-6085-11eb-971e-35ca836e6265.png)

**Comment by marcalwestf** [comment]
perhaps you could find quickly the error @mckayERP Mike?

**Comment by mckayERP** [comment]
Hi Mario,

It looks like the version of ant you are using may be old.  Can you upgrade
to the latest version? 1.10.9 is the most current I believe and is what is
being used in the travis build.  I'm using 1.10.8 and it works fine.

If you have a database available, you can also run the integration tests by
changing the flag in the test.properties file in utils_dev.  Travis can
only run the unit tests.

Mike

**Comment by marcalwestf** [comment]
@mckayERP  thanks Mike, I will try it and report.

**Comment by marcalwestf** [comment]
hi @mckayERP Mike thanks for the hint!
I had ANT version 1.10.5 (released July 2018). 
I then installed version **1.10.9** (as of Sept-30-2020) and on Eclipse, I selected the new version as the Ant Home directory:
![Selection_992](https://user-images.githubusercontent.com/1789408/106139906-a9819400-6133-11eb-8cf2-95299470fb71.png)

Then, ran Adempiere build and it finishes without error!
