### ISSUE TITLE
Error in Swing creating a Jasper Report

### ISSUE THREAD

**Issue by SusanneCalderon** [adempiere/adempiere#3358]
Calling any jasper report, I have the same problem. It works in Web, but creates an error in Swing.

**Using WebUI:**
![imagen](https://user-images.githubusercontent.com/15349639/107419891-e9565d00-6add-11eb-9c22-dc7df27ccf0d.png)

**Swing**
![imagen](https://user-images.githubusercontent.com/15349639/107420328-64b80e80-6ade-11eb-8a53-669f50cab88b.png)

**Comment by homebeaver** [comment]
Hi @SusanneCalderon, maybe it is similar to "build JasperReports with iText-2.1.7.jar" #3303

regards EUGen

**Comment by e-Evolution** [comment]
@SusanneCalderon the problem was solved here #3527
