### ISSUE TITLE
Complete Standard sales order in ZK 

### ISSUE THREAD

**Issue by eelti** [adempiere/adempiere#3380]
#### Screenshot or Gif
![image](https://user-images.githubusercontent.com/25960538/109713712-8e110b00-7b6f-11eb-82f6-e2184f8183e9.png)

#### Other relevant information
- Your OS: windows 10
- Java version:  OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_282-b08)
- ADempiere version:  3.9.3_2019-12-01 
- Browser edge
- Browser VersionVersion 88.0.705.81 (Version officielle) (64 bits)
- DB Provider: PostGres
- DB version: 12.2

#### Additional context
Works well in java client

**Comment by e-Evolution** [comment]
@eelti Hi Eric, can please send the error log, to get only double-click  the ADempeire icon logo, and send me the trace log

**Comment by eelti** [comment]
[trace.log](https://github.com/adempiere/adempiere/files/6071927/trace.log)

**Comment by eelti** [comment]
Same problems happen in the purchase order screen in Zk

**Comment by eelti** [comment]
I update postgres from 12.2 to 13.2 
Rebuild my docker  with the new pg image and no more problems I guest only my...
