### ISSUE TITLE
Costing Method AverageInvoice, Problem with voided documents

### ISSUE THREAD

**Issue by SusanneCalderon** [adempiere/adempiere#3388]
## Bug report
When a document is voided, the cancellation document copies the Cost Detail register from the original document. This calculation is correct when the original and the cancellation document have the same accounting date. When the date of the annulation document differs from the original it is correct to calculate the new average cost from the last cost detail.

## Solution
Considerate the last Costdetail for the calculation.

**Comment by e-Evolution** [comment]
@SusanneCalderon  I can understand the problem, so I think this should be the behavior:

In case a document is void, if I remember correctly the business logic is called for a reverse correction, so you should apply this logic.

On the other hand, if it is required to do a reversal accrual  with a current date then I think it should work as follows.

1.- If the document to which a reversal accrual is applied generates an inventory receipt, it should calculate a new average

2.- If the document to which a reversal accrual  is applied generates an inventory shipment or out, it should consume the current average layer, so it should not update the average.

Can you  validate that this is what happens with this field especially for an inventory material out?

**Comment by SusanneCalderon** [comment]
@e-Evolution 
Victor, I will test this now

**Comment by e-Evolution** [comment]
Hi @SusanneCalderon Susanne, thank you a lot, let  me review and check

**Comment by SusanneCalderon** [comment]
Hi @e-Evolution 
Imagine the following scenario:

- I generate a shipment on 01.07.2021 with average cost of $100
- I purchase the product on 05.07.2021 with increases the average cost to $110
- I reverse the shipment on 09.07.2021 with the current date
I understand you that the reversal should apply with a cost of $110. So I can increase or decrease the value of my inventory just shipping and reversing

**Comment by SusanneCalderon** [comment]
@e-Evolution 
For the document Inventory the reverse accrual does not apply. The period is tested with the current date, but the reversal document is generated with the original date.

**Comment by SusanneCalderon** [comment]
[Cost_Plumtree.xlsx](https://github.com/adempiere/adempiere/files/6793943/Cost_Plumtree.xlsx)
Here in our approach the plumtree is shipped with a cost of $41.1905 and returns 1 week later with the same cost.

**Comment by SusanneCalderon** [comment]
@e-Evolution 
![imagen](https://user-images.githubusercontent.com/15349639/125136860-d796d700-e0c8-11eb-93a6-49a4bee4e721.png)
Material Move with reverse correct It, the sequences are included after the original document

**Comment by SusanneCalderon** [comment]
@e-Evolution 
The reverse accrual  method in MMovement and MInventory is not consistent. I suggest to exclude reverse accrual for these document types
