### ISSUE TITLE
Smart Browse context is changed from table

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#340]
1. Create a SB with a column like parameters for search, example **C_Currency_ID**.
2. Show column **C_Currency_ID** in table of Smart Browse.
3. Use the **C_Currency_ID** column in a column of table, example:
<pre>
currencyConvert(inv.GrandTotal, inv.C_Currency_ID, **@C_Currency_ID@**, TO_DATE('@PayDate@','YYYY-MM-DD'), inv.C_ConversionType_ID,inv.AD_Client_ID, inv.AD_Org_ID)
</pre>
4. Show Smart Browse and press **Search Button**.
5. The result is ok.
6. Press newly the **Search Button** (It throw the error with SQL).

The error is caused by the table in SB have the same column that the search parameter.

**Comment by e-Evolution** [comment]
Hi @yamelsenih  DefaultValue2 in paramenter not are working , the system show "@pay.DateTrx_To@" vs  "@PAY_DateTrx_To@"

and some DefaultValue show

@SQL= SELECT SUM (o.grandtotal) FROM C_Order o WHERE o.C_POS_ID = @C_POS_ID@ AND o.DateOrdered  BETWEEN TO_DATE('@PAY_DateTrx@','YYYY-MM-DD') AND TO_DATE('@pay.DateTrx_To@','YYYY-MM-DD') AND o.DocStatus IN ('CO','CL')

**Comment by yamelsenih** [comment]
Hi @e-Evolution plesase test it
