### ISSUE TITLE
Role Access Update not working as expected

### ISSUE THREAD

**Issue by mckayERP** [adempiere/adempiere#3427]
Log in as SuperUser or System under System Administrator role  OR GardenAdmin as GardenAdmin role.

Open the Role Access Update process

Set the Client as System
Set the Role to blank.

Run the process

Expected behaviour: all roles in all clients are updated and the process log lists them.

Actual behaviour: only the system administration role is updated.

Cause:  The addition of the process class structure with the abstract process class added some checks on the parameters.  The role id is an int and as a blank/null, it is changed from null to zero.  But zero is a valid role id for the system administration role and the clause ad_role_id=? is added to the where clause, restricting the list of roles to update to the system administration role.

Fix: either test for null or convert a null to -1 to allow all roles to be returned.

**Comment by marcalwestf** [comment]
@mckayERP  I can reproduce the case.
