### ISSUE TITLE
Error generating report

### ISSUE THREAD

**Issue by wdtz** [adempiere/adempiere#345]
To generate the report "Invoice Not Realized Gain & Loss Report" generates the error attached.
[Log.txt](https://github.com/adempiere/adempiere/files/232544/Log.txt)

**Comment by yamelsenih** [comment]
Hi @wdtz i paste the log here
<pre>
===========> DataEngine.loadPrintData: null - ERROR: missing FROM-clause entry for table "t_invoicegl_v"
  Position: 7708
SQL=SELECT A.Value||'-'||A.Name AS AName,T_InvoiceGL_vt.Account_ID AS Account_ID,T_InvoiceGL_vt.DateAcct,T_InvoiceGL_vt.AmtAcctCr,T_InvoiceGL_vt.AmtAcctDr,(SELECT NVL(CAST (Fact_Acct.Fact_Acct_ID AS Text),'') FROM Fact_Acct WHERE T_InvoiceGL_vt.Fact_Acct_ID=Fact_Acct.Fact_Acct_ID) AS BFact_Acct_ID,T_InvoiceGL_vt.Fact_Acct_ID AS Fact_Acct_ID,(SELECT NVL(C_AcctSchema.Name,'') FROM C_AcctSchema WHERE T_InvoiceGL_vt.C_AcctSchema_ID=C_AcctSchema.C_AcctSchema_ID) AS CC_AcctSchema_ID,T_InvoiceGL_vt.C_AcctSchema_ID AS C_AcctSchema_ID,(SELECT NVL(C_Activity.Name,'') FROM C_Activity WHERE T_InvoiceGL_vt.C_Activity_ID=C_Activity.C_Activity_ID) AS DC_Activity_ID,T_InvoiceGL_vt.C_Activity_ID AS C_Activity_ID,E.Name AS EName,T_InvoiceGL_vt.APAR AS APAR,(SELECT NVL(GL_Budget.Name,'') FROM GL_Budget WHERE T_InvoiceGL_vt.GL_Budget_ID=GL_Budget.GL_Budget_ID) AS FGL_Budget_ID,T_InvoiceGL_vt.GL_Budget_ID AS GL_Budget_ID,(SELECT NVL(C_BPartner.Name,'') FROM C_BPartner WHERE T_InvoiceGL_vt.C_BPartner_ID=C_BPartner.C_BPartner_ID) AS GC_BPartner_ID,T_InvoiceGL_vt.C_BPartner_ID AS C_BPartner_ID,(SELECT NVL(C_Campaign.Name,'') FROM C_Campaign WHERE T_InvoiceGL_vt.C_Campaign_ID=C_Campaign.C_Campaign_ID) AS HC_Campaign_ID,T_InvoiceGL_vt.C_Campaign_ID AS C_Campaign_ID,(SELECT NVL(C_Currency.ISO_Code,'') FROM C_Currency WHERE T_InvoiceGL_vt.C_Currency_ID=C_Currency.C_Currency_ID) AS IC_Currency_ID,T_InvoiceGL_vt.C_Currency_ID AS C_Currency_ID,(SELECT NVL(C_ConversionType.Name,'') FROM C_ConversionType WHERE T_InvoiceGL_vt.C_ConversionType_ID=C_ConversionType.C_ConversionType_ID) AS JC_ConversionType_ID,T_InvoiceGL_vt.C_ConversionType_ID AS C_ConversionType_ID,T_InvoiceGL_vt.DateInvoiced,T_InvoiceGL_vt.Description,T_InvoiceGL_vt.DocumentNo,K.Name AS KName,T_InvoiceGL_vt.DocStatus AS DocStatus,(SELECT C_DocType_Trl.Name FROM C_DocType INNER JOIN C_DocType_TRL ON (C_DocType.C_DocType_ID=C_DocType_Trl.C_DocType_ID AND C_DocType_Trl.AD_Language='es_MX') WHERE T_InvoiceGL_vt.C_DocType_ID=C_DocType.C_DocType_ID) AS LC_DocType_ID,T_InvoiceGL_vt.C_DocType_ID AS C_DocType_ID,(SELECT NVL(GL_Category.Name,'') FROM GL_Category WHERE T_InvoiceGL_vt.GL_Category_ID=GL_Category.GL_Category_ID) AS MGL_Category_ID,T_InvoiceGL_vt.GL_Category_ID AS GL_Category_ID,T_InvoiceGL_vt.GrandTotal,(SELECT NVL(C_Invoice.DocumentNo,'')||' - '||NVL(CAST (C_Invoice.DateInvoiced AS Text),'')||' - '||NVL(CAST (C_Invoice.GrandTotal AS Text),'') FROM C_Invoice WHERE T_InvoiceGL_vt.C_Invoice_ID=C_Invoice.C_Invoice_ID) AS NC_Invoice_ID,T_InvoiceGL_vt.C_Invoice_ID AS C_Invoice_ID,O.City AS OCity,T_InvoiceGL_vt.C_LocFrom_ID AS C_LocFrom_ID,P.City AS PCity,T_InvoiceGL_vt.C_LocTo_ID AS C_LocTo_ID,(SELECT NVL(M_Locator.Value,'') FROM M_Locator WHERE T_InvoiceGL_vt.M_Locator_ID=M_Locator.M_Locator_ID) AS QM_Locator_ID,T_InvoiceGL_vt.M_Locator_ID AS M_Locator_ID,T_InvoiceGL_vt.OpenAmt,(SELECT NVL(C_Order.DocumentNo,'')||' - '||NVL(CAST (C_Order.DateOrdered AS Text),'') FROM C_Order WHERE T_InvoiceGL_vt.C_Order_ID=C_Order.C_Order_ID) AS RC_Order_ID,T_InvoiceGL_vt.C_Order_ID AS C_Order_ID,(SELECT NVL(C_BPartner_Location.Name,'') FROM C_BPartner_Location WHERE T_InvoiceGL_vt.C_BPartner_Location_ID=C_BPartner_Location.C_BPartner_Location_ID) AS SC_BPartner_Location_ID,T_InvoiceGL_vt.C_BPartner_Location_ID AS C_BPartner_Location_ID,(SELECT C_PaymentTerm_Trl.Name FROM C_PaymentTerm INNER JOIN C_PaymentTerm_TRL ON (C_PaymentTerm.C_PaymentTerm_ID=C_PaymentTerm_Trl.C_PaymentTerm_ID AND C_PaymentTerm_Trl.AD_Language='es_MX') WHERE T_InvoiceGL_vt.C_PaymentTerm_ID=C_PaymentTerm.C_PaymentTerm_ID) AS TC_PaymentTerm_ID,T_InvoiceGL_vt.C_PaymentTerm_ID AS C_PaymentTerm_ID,(SELECT NVL(C_Period.Name,'') FROM C_Period WHERE T_InvoiceGL_vt.C_Period_ID=C_Period.C_Period_ID) AS UC_Period_ID,T_InvoiceGL_vt.C_Period_ID AS C_Period_ID,V.Name AS VName,T_InvoiceGL_vt.PostingType AS PostingType,T_InvoiceGL_vt.IsTaxIncluded,(SELECT NVL(CAST (AD_PInstance.AD_PInstance_ID AS Text),'')||' - '||NVL((SELECT NVL(AD_Process.Value,'')||' - '||AD_Process_Trl.Name FROM AD_Process INNER JOIN AD_Process_TRL ON (AD_Process.AD_Process_
ID=AD_Process_Trl.AD_Process_ID AND AD_Process_Trl.AD_Language='es_MX') WHERE AD_PInstance.AD_Process_ID=AD_Process.AD_Process_ID),'') FROM AD_PInstance WHERE T_InvoiceGL_vt.AD_PInstance_ID=AD_PInstance.AD_PInstance_ID) AS WAD_PInstance_ID,T_InvoiceGL_vt.AD_PInstance_ID AS AD_PInstance_ID,(SELECT NVL(C_Project.Value,'')||' - '||NVL(C_Project.Name,'') FROM C_Project WHERE T_InvoiceGL_vt.C_Project_ID=C_Project.C_Project_ID) AS XC_Project_ID,T_InvoiceGL_vt.C_Project_ID AS C_Project_ID,T_InvoiceGL_vt.Qty,T_InvoiceGL_vt.AmtRevalCr,T_InvoiceGL_vt.AmtRevalDr,T_InvoiceGL_vt.AmtRevalCrDiff,T_InvoiceGL_vt.AmtRevalDrDiff,Y.Name AS YName,T_InvoiceGL_vt.C_ConversionTypeReval_ID AS C_ConversionTypeReval_ID,T_InvoiceGL_vt.DateReval,(SELECT NVL(C_SalesRegion.Name,'') FROM C_SalesRegion WHERE T_InvoiceGL_vt.C_SalesRegion_ID=C_SalesRegion.C_SalesRegion_ID) AS ZC_SalesRegion_ID,T_InvoiceGL_vt.C_SalesRegion_ID AS C_SalesRegion_ID,AA.Name AS AAName,T_InvoiceGL_vt.SalesRep_ID AS SalesRep_ID,T_InvoiceGL_vt.IsSOTrx,T_InvoiceGL_vt.IsSelfService,T_InvoiceGL_vt.AmtSourceCr,T_InvoiceGL_vt.AmtSourceDr,(SELECT C_Tax_Trl.Name FROM C_Tax INNER JOIN C_Tax_TRL ON (C_Tax.C_Tax_ID=C_Tax_Trl.C_Tax_ID AND C_Tax_Trl.AD_Language='es_MX') WHERE T_InvoiceGL_vt.C_Tax_ID=C_Tax.C_Tax_ID) AS BBC_Tax_ID,T_InvoiceGL_vt.C_Tax_ID AS C_Tax_ID,CC.Value||'-'||CC.Name AS CCName,T_InvoiceGL_vt.AD_OrgTrx_ID AS AD_OrgTrx_ID,(SELECT C_UOM_Trl.Name FROM C_UOM INNER JOIN C_UOM_TRL ON (C_UOM.C_UOM_ID=C_UOM_Trl.C_UOM_ID AND C_UOM_Trl.AD_Language='es_MX') WHERE T_InvoiceGL_vt.C_UOM_ID=C_UOM.C_UOM_ID) AS DDC_UOM_ID,T_InvoiceGL_vt.C_UOM_ID AS C_UOM_ID,(SELECT NVL(AD_User.Name,'') FROM AD_User WHERE T_InvoiceGL_vt.AD_User_ID=AD_User.AD_User_ID) AS EEAD_User_ID,T_InvoiceGL_vt.AD_User_ID AS AD_User_ID,FF.Value||'-'||FF.Name AS FFName,T_InvoiceGL_vt.User1_ID AS User1_ID,GG.Value||'-'||GG.Name AS GGName,T_InvoiceGL_vt.User2_ID AS User2_ID,T_InvoiceGL_vt.AmtAcctBalance,T_InvoiceGL_vt.AmtAcctOpenBalance,T_InvoiceGL_vt.AmtAcctOpenCr,T_InvoiceGL_vt.AmtAcctOpenDr,T_InvoiceGL_vt.IsAllCurrencies,T_InvoiceGL_vt.Percent,HH.Name AS HHName,T_InvoiceGL_vt.C_DocTypeReval_ID AS C_DocTypeReval_ID,T_InvoiceGL_vt.AmtSourceBalance FROM T_InvoiceGL_vt INNER JOIN C_ElementValue A ON (T_InvoiceGL_vt.Account_ID=A.C_ElementValue_ID) LEFT OUTER JOIN  AD_Ref_List XE ON (T_InvoiceGL_vt.APAR=XE.Value AND XE.AD_Reference_ID=332) LEFT OUTER JOIN  AD_Ref_List_Trl E ON (XE.AD_Ref_List_ID=E.AD_Ref_List_ID AND E.AD_Language='es_MX') INNER JOIN  AD_Ref_List XK ON (T_InvoiceGL_vt.DocStatus=XK.Value AND XK.AD_Reference_ID=131) INNER JOIN  AD_Ref_List_Trl K ON (XK.AD_Ref_List_ID=K.AD_Ref_List_ID AND K.AD_Language='es_MX') LEFT OUTER JOIN C_Location O ON (T_InvoiceGL_vt.C_LocFrom_ID=O.C_Location_ID) LEFT OUTER JOIN C_Location P ON (T_InvoiceGL_vt.C_LocTo_ID=P.C_Location_ID) INNER JOIN  AD_Ref_List XV ON (T_InvoiceGL_vt.PostingType=XV.Value AND XV.AD_Reference_ID=125) INNER JOIN  AD_Ref_List_Trl V ON (XV.AD_Ref_List_ID=V.AD_Ref_List_ID AND V.AD_Language='es_MX') INNER JOIN C_ConversionType Y ON (T_InvoiceGL_vt.C_ConversionTypeReval_ID=Y.C_ConversionType_ID) LEFT OUTER JOIN AD_User AA ON (T_InvoiceGL_vt.SalesRep_ID=AA.AD_User_ID) LEFT OUTER JOIN AD_Org CC ON (T_InvoiceGL_vt.AD_OrgTrx_ID=CC.AD_Org_ID) LEFT OUTER JOIN C_ElementValue FF ON (T_InvoiceGL_vt.User1_ID=FF.C_ElementValue_ID) LEFT OUTER JOIN C_ElementValue GG ON (T_InvoiceGL_vt.User2_ID=GG.C_ElementValue_ID) LEFT OUTER JOIN C_DocType HH ON (T_InvoiceGL_vt.C_DocTypeReval_ID=HH.C_DocType_ID) WHERE (T_InvoiceGL_v.AD_PInstance_ID=1000070 AND T_InvoiceGL_vt.C_AcctSchema_ID=101.0 AND T_InvoiceGL_vt.C_ConversionTypeReval_ID=200.0 AND TRUNC(T_InvoiceGL_vt.DateReval, 'DD')=TO_DATE('2016-04-22','YYYY-MM-DD') AND T_InvoiceGL_vt.APAR='A' AND T_InvoiceGL_vt.IsAllCurrencies='N' AND T_InvoiceGL_vt.AD_Language='es_MX') AND T_InvoiceGL_vt.AD_Client_ID IN(0,11) AND T_InvoiceGL_vt.AD_Org_ID IN(50007,0,50004,50005,50006,50000,50001,50002,11,12) AND (A.C_ElementValue_ID IS NULL OR A.C_ElementValue_ID NOT IN ( SELECT Record_ID FROM AD_Private_Access WHERE AD_Table_ID = 188 AND AD_User_ID <> 
100 AND IsActive = 'Y' )) AND (XE.AD_Ref_List_ID IS NULL OR XE.AD_Ref_List_ID NOT IN ( SELECT Record_ID FROM AD_Private_Access WHERE AD_Table_ID = 104 AND AD_User_ID <> 100 AND IsActive = 'Y' )) AND (XK.AD_Ref_List_ID IS NULL OR XK.AD_Ref_List_ID NOT IN ( SELECT Record_ID FROM AD_Private_Access WHERE AD_Table_ID = 104 AND AD_User_ID <> 100 AND IsActive = 'Y' )) AND (O.C_Location_ID IS NULL OR O.C_Location_ID NOT IN ( SELECT Record_ID FROM AD_Private_Access WHERE AD_Table_ID = 162 AND AD_User_ID <> 100 AND IsActive = 'Y' )) AND (P.C_Location_ID IS NULL OR P.C_Location_ID NOT IN ( SELECT Record_ID FROM AD_Private_Access WHERE AD_Table_ID = 162 AND AD_User_ID <> 100 AND IsActive = 'Y' )) AND (XV.AD_Ref_List_ID IS NULL OR XV.AD_Ref_List_ID NOT IN ( SELECT Record_ID FROM AD_Private_Access WHERE AD_Table_ID = 104 AND AD_User_ID <> 100 AND IsActive = 'Y' )) AND (Y.C_ConversionType_ID IS NULL OR Y.C_ConversionType_ID NOT IN ( SELECT Record_ID FROM AD_Private_Access WHERE AD_Table_ID = 637 AND AD_User_ID <> 100 AND IsActive = 'Y' )) AND (AA.AD_User_ID IS NULL OR AA.AD_User_ID NOT IN ( SELECT Record_ID FROM AD_Private_Access WHERE AD_Table_ID = 114 AND AD_User_ID <> 100 AND IsActive = 'Y' )) AND (CC.AD_Org_ID IS NULL OR CC.AD_Org_ID NOT IN ( SELECT Record_ID FROM AD_Private_Access WHERE AD_Table_ID = 155 AND AD_User_ID <> 100 AND IsActive = 'Y' )) AND (FF.C_ElementValue_ID IS NULL OR FF.C_ElementValue_ID NOT IN ( SELECT Record_ID FROM AD_Private_Access WHERE AD_Table_ID = 188 AND AD_User_ID <> 100 AND IsActive = 'Y' )) AND (GG.C_ElementValue_ID IS NULL OR GG.C_ElementValue_ID NOT IN ( SELECT Record_ID FROM AD_Private_Access WHERE AD_Table_ID = 188 AND AD_User_ID <> 100 AND IsActive = 'Y' )) AND (HH.C_DocType_ID IS NULL OR HH.C_DocType_ID NOT IN ( SELECT Record_ID FROM AD_Private_Access WHERE AD_Table_ID = 217 AND AD_User_ID <> 100 AND IsActive = 'Y' ))
</pre>

Best Regards

**Comment by yamelsenih** [comment]
This was resolved here #2440
