### ISSUE TITLE
[Feature Request] Adding support for Java  JDK 11 (LTS)

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#3477]
## Feature request
Adding support for Java  JDK 11 (LTS) 

#### Describe the solution you'd like
1.- Migrate the Ant build using JDK 11 
2.-Review the compatibility with of library 
3.-Change the code for support JDK 11 
4.-Create new build 
5.-Execute intensive testing.

**Comment by marekmosiewicz** [comment]
Hi guys,
   I wanted to solve this issue a few years ago. Now I have no time for this. 
Sincerely,
   Marek Mosiewicz
