### ISSUE TITLE
Build with Unit and Integration Tests Fails

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere#3494]
## Bug report
With present _develop_ version, the build fails if  _Unit_ and _Integration_ tests are enabled
#### Steps to reproduce
1. Set in _utisl_dev/test.properties_ the variables _test.performTests_=true, _test.performUnitTests_=true and _test.performIntegrationTests_=true
2. Run _ANT build_
3. A build error is produced
4. If variable _test.performTests_=false, **the build executes without error**

#### Screenshot or Gif
![Selection_005](https://user-images.githubusercontent.com/1789408/124049405-a259fd00-d9d5-11eb-887e-764e9dd26e0e.png)

#### Expected behavior
It is expected that the build is executed without error.

#### Other relevant information
- Your OS: Linux Kubuntu
- Java version: 11
- ADempiere version: 3.9.3
- IDE: Eclipse

**Comment by mckayERP** [comment]
Hi Mario,

Check that your copy of Adempiere.properties in your user directory is correct and that ADEMPIERE_HOME is set correctly.  See below.

I've update my repo to the current develop head 4489257a...
Built and deployed the project without running any tests.
Ran the setup scripts:

- run_silentsetup.bat
- run_importadempiere.bat
- run_migratexml.bat (overnight)

Built the project again with all tests and recreated the output above.

Debugged and found the tests were being run off of another database.  Tests that checked the message translations were failing but I could see the messages were in the database.
Verified ADEMPIERE_HOME was correct.
Copied ADEMPIERE_HOME\Adempiere.properties to <User_Dir>\Adempiere.properties replacing the file that was there. That was the cause of the problem.

Rebuilt the project and all tests passed.

![image](https://user-images.githubusercontent.com/5507616/124121114-7e80d080-da42-11eb-8805-31181c14396f.png)
