### ISSUE TITLE
Add Account number to Account Tree view

### ISSUE THREAD

**Issue by trifonnt** [adempiere/adempiere#351]
Currently Account Tree view in ADempiere shows only account names.
It is very desired functionality by all users to see both Account number and Account name.

Blow is screen-shot how window "Account Element" looks when this change is applied
 
![account number](https://cloud.githubusercontent.com/assets/518299/14850657/32be1e6a-0c83-11e6-8545-2e3e884bd583.jpg)

**Comment by yamelsenih** [comment]
Hi @trifonnt is very nice if the values showed are from IsIdentifier attribute in AD
