### ISSUE TITLE
Swing: Button Posted freezes the current window

### ISSUE THREAD

**Issue by SusanneCalderon** [adempiere/adempiere#3518]
Reference to Issue #3329 
#### Steps to reproduce

1. In Swing use the button Posted and select Repost 
2. The window is freezed and the aplication is not generated

Reason: Class _AEnv_ in _client/src/compiere/apps_   calls DocumentEngine with TrxName null
In DocumentEngine the method postImmediate requires TrxName without capturing an exception
So the window gets freezed

**Comment by mckayERP** [comment]
Noted.

**Comment by e-Evolution** [comment]
Hi @mckayERP Mike , it is strange because the tests have no problem integrating the refectory #3329.

So @SusanneCalderon , @mckayERP We should deprecate the method? 
I suppose any call to this code has the same problem:

DocumentEngine.postImmediate (Env.getCtx (), AD_Client_ID, AD_Table_ID, Record_ID, force, null); 

On the other hand, @mckayERP you should review the design testing to refactory #3329

kind regards
Victor

**Comment by e-Evolution** [comment]
@SusanneCalderon  You  can check if this happen also in ZK UI please?

**Comment by mckayERP** [comment]
Verified that there is an error when trxName is null;

DocumentEngine.postImmediate has a statement

`requireNonNull(trxName)`

Created a test to validate the error.  Both the Swing AEnv class and the ZK AEnv have a postImmediate method.

The Swing version uses `DocumentEngine.postImmediate()`.  This calls doc.postImmediate().
The ZK version calls `Doc.postImmediate()`. This also calls doc.postImmediate().

Created some tests to verify the behaviour:


    class IT_DocumentPosting extends CommonGWSetup {

    ....
    
    @Nested
    @DisplayName("Given an existing document "
            + "that has no errors")
    class GivenAnExistingDocumentWithNoErrors {
        
        private int invoiceId;
        
        @BeforeEach
        void getExistingDocument() {
            
            int windowNo = 0;
            invoiceId = 103;
            MInvoice existingInvoice = new MInvoice(ctx, invoiceId, null);
            Env.setContext(ctx, windowNo, "IsSOTrx", existingInvoice.isSOTrx());
            Env.setContext(ctx, windowNo, "IsApproved", existingInvoice.isApproved());
            Env.setContext(ctx, windowNo,  "C_Currency_ID", existingInvoice.getC_Currency_ID());
            
        }
        
        @Test
        final void whenRepostedFromSwing_postingShouldSucceed() {
            
            String error = DocumentEngine.postImmediate(ctx, AD_CLIENT_ID, 
                    I_C_Invoice.Table_ID, invoiceId, false, null);
            assertNull(error);
            MInvoice existingInvoice = new MInvoice(ctx, invoiceId, null);
            assertTrue(existingInvoice.isPosted());
            
        }

        @Test
        final void whenRepostedFormZK_postingShouldSucceed() {
            
            MAcctSchema[] ass = MAcctSchema.getClientAcctSchema(ctx, AD_CLIENT_ID);
            String error = Doc.postImmediate(ass, I_C_Invoice.Table_ID, invoiceId, false, null);

            assertNull(error);
            MInvoice existingInvoice = new MInvoice(ctx, invoiceId, null);
            assertTrue(existingInvoice.isPosted());
            
        }

    }

The test when RepostedFromSwing fails.

Removed the `requireNotNull(trxName);` statement from the DocumentEngine.postImmediate method and the test passes.

Built full build with all test - everything passes.

![SwingDocPosting](https://user-images.githubusercontent.com/5507616/125382111-10ea7380-e363-11eb-8d2d-7a99aa14d467.gif)

**Comment by mckayERP** [comment]
Rebuilding to try the ZK inteface next.

**Comment by mckayERP** [comment]
![ZKDocPosting](https://user-images.githubusercontent.com/5507616/125442972-b058d2ad-b47a-4305-9539-33bc39c29ee8.gif)
