### ISSUE TITLE
T_Selection is better send to process like a HashMap instead read from disk

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#352]
1. Use a SB.
2. Process values from SB.

When you process the SB, it save records in **T_Selection** and **T_Selection_Browse** tables, but if the process not call a DB function then is unnecessary it step.

The values can save in a array and set to process parameter.

This same behavior when is calling a process in a form, example: **Generate Invoice (Manual)**.

Is better add helper method for add rows and column values to process info.

**Comment by e-Evolution** [comment]
But for back compatibility, can be that some based install have some store procedure en oracle or postgresql and need that the data are persistence of DB, so si important that work of same way.

So then can enable the HashMap, but we need continue update or create record for  T_Selection and T_Selection_Browser

kid regards

**Comment by yamelsenih** [comment]
Hi @e-Evolution is simple, the process control just must save in DB when the process have a function in DB.

**Comment by e-Evolution** [comment]
I agree , I will review when you commit of code

**Comment by e-Evolution** [comment]
NPE introducing in f946ae6 the problem is 
`//	FR [ 352 ]
        if (isSelection) {
            processInfo.setSelectionKeys(selectedRecordsIds);
        }`
are before to create the processInfo instance
