### ISSUE TITLE
Tree maintenance arrow buttons are disabled

### ISSUE THREAD

**Issue by ishanuda** [adempiere/adempiere#355]
HI,
I have seen that the four arrow buttons in the tree maintenance are disabled as in the attached screen shot.

My system release version is: 3.8.0, with no patches installed

Is this behavior a bug?
Is it disabled by default in the system now?
How to enable these buttons?

![tree-maintenance-buttons-disabled](https://cloud.githubusercontent.com/assets/8893919/14908768/0b0485ae-0df9-11e6-825b-12ce89006820.jpg)

**Comment by sajeevsahadev** [comment]
Can you post the menu tree definition.

**Comment by yamelsenih** [comment]
Hi @ishanuda the buttons is disable when the tree definition have flag **All Nodes** is true.

Best Regard

**Comment by ishanuda** [comment]
Hi, Thank you, as you say when i deselect the flag to all nodes is false, the problem solved.
But I noticed another problem there.

01. I removed an existing node (Ex:- Position) from a menu tree (Ex:- Human Resource & Payroll)
It was successfully removed from the left side menu tree.

02. Again I selected the same menu tree from the left side (Ex:- Human Resource & Payroll). 
selected the removed node (Ex:- Position) from the right side. 
Clicked on the add to tree button.

Menu item added to the left side, but not to the selected menu tree (Ex:- Human Resource & Payroll), 
I added as the last item of the tree.

And I drag it and dropped it inside (Ex:- Human Resource & Payroll) to make it as it was.

Is this behavior normal?.

Thanks

**Comment by yamelsenih** [comment]
Hi @ishanuda currently when you add a node from left yo right it is added at last position and you must move it to correct node.

Is nice to have it change. If have you it change or you want contribute with us, you are welcome...

ADempiere is a big community and we are open to new contributors.

Best regard.
