### ISSUE TITLE
Favorites(System): Drag&Drop doesn't work

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere#3580]
#### Steps to reproduce

1. Login as _GardenAdmin_
2. Open folder _Requisition-to-Invoice_ in menu (or any other folder)
3. Drag and Drop any item to _Favorites_

#### Dragging & dropping doesn't work
![20210729_Favorites](https://user-images.githubusercontent.com/1789408/127542079-b81122a5-c027-46ac-9e95-153ee2d421f5.gif)

#### Deleting works
![20210729_Favorites-delete](https://user-images.githubusercontent.com/1789408/127542576-207b5953-8b4d-42d5-84cb-b4dfa583b901.gif)

#### Expected behavior
The selected item should be added to the _Favorites_.

#### Other relevant information
- OS: Ubuntu 20.04
- Java version: Adopt Open JDK 11.9 
- ADempiere version: latest commit 
- Browser: Firefox

**Comment by vdevsoft** [comment]
Me too, 
Login as GardenAdmin
Drag and Drop any item to Favorites (user)
It appears at SuperUser Favorites (user).

**Comment by marcalwestf** [comment]
When debugging, and setting a breakpoint at the Favourites(System) panel, the drag&drop event is not caught by the panel, so it seems that it has not notified the menu to be informed.

**Comment by vdevsoft** [comment]
Could we add items to table "ad_tree_favorite_node" directly?

**Comment by marcalwestf** [comment]
I suppose so. But as it is an intermediate table, you should be very careful getting and putting the IDs.
This way you might solve one problem (at least better than nothing); the basic problem would remain, though.

Interesting to know your results!

**Comment by bma-robco** [comment]
replaced the following line works for me. 
public DPFavourites()
...
 //favContent.setDroppable(FAVOURITE_DROPPABLE); 
favContent.setDroppable(MenuPanel.MENU_ITEM_DRAGGABLE_TYPE);

**Comment by marcalwestf** [comment]
thank you @bma-robco 

if you wish, you can solve it on a dedicated branch on your clone, create a pull request, set me as a reviewer and I will gladly test it.
This way, the credits go to you and you start contributing with code.
