### ISSUE TITLE
[Bug Report] Error when ADempiere Application Server Admin is shut down causing a possible memory leak

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#3586]
## Bug report
Error when ADempiere application server is shut down causing a possible memory  leak

#### Steps to reproduce
1. Setup ADempiere using Tomcat 9.0
2. Start the Server using utils/RUN_Server2.sh and  await some minutes until start the processors starting 
3. Stop the Server using utils/RUN_Server2Stop.sh and check the log tomcat/logs/catalina.out

#### Screenshot or Gif

-----------> WebappClassLoaderBase.clearReferencesThreads: The web application [admin] appears to have started a thread named [Timer-0] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@11.0.11/java.lang.object.wait(Native Method)
 java.base@11.0.11/java.util.timerthread.mainloop(timer.java:553)
 java.base@11.0.11/java.util.timerthread.run(timer.java:506) [77]
-----------> WebappClassLoaderBase.clearReferencesThreads: The web application [admin] appears to have started a thread named [com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread-#0] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@11.0.11/java.lang.object.wait(Native Method)
 com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:534) [77]
-----------> WebappClassLoaderBase.clearReferencesThreads: The web application [admin] appears to have started a thread named [com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread-#1] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@11.0.11/java.lang.object.wait(Native Method)
 com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:534) [77]
-----------> WebappClassLoaderBase.clearReferencesThreads: The web application [admin] appears to have started a thread named [com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread-#2] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@11.0.11/java.lang.object.wait(Native Method)
 com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:534) [77]
-----------> WebappClassLoaderBase.clearReferencesThreads: The web application [admin] appears to have started a thread named [GardenWorld Accounting Processor] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@11.0.11/java.lang.thread.sleep(Native Method)
 org.compiere.server.AdempiereServer.sleep(AdempiereServer.java:172)
 org.compiere.server.AdempiereServer.run(AdempiereServer.java:302) [77]
-----------> WebappClassLoaderBase.clearReferencesThreads: The web application [admin] appears to have started a thread named [GardenWorld Request Processor] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@11.0.11/java.lang.thread.sleep(Native Method)
 org.compiere.server.AdempiereServer.sleep(AdempiereServer.java:172)
 org.compiere.server.AdempiereServer.run(AdempiereServer.java:302) [77]
-----------> WebappClassLoaderBase.clearReferencesThreads: The web application [admin] appears to have started a thread named [System Workflow Processor] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@11.0.11/java.lang.thread.sleep(Native Method)
 org.compiere.server.AdempiereServer.run(AdempiereServer.java:225) [77]
-----------> WebappClassLoaderBase.clearReferencesThreads: The web application [admin] appears to have started a thread named [System Alert Processor] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@11.0.11/java.lang.thread.sleep(Native Method)
 org.compiere.server.AdempiereServer.run(AdempiereServer.java:225) [77]
-----------> WebappClassLoaderBase.clearReferencesThreads: The web application [admin] appears to have started a thread named [Delete Old Notes] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@11.0.11/java.lang.thread.sleep(Native Method)
 org.compiere.server.AdempiereServer.run(AdempiereServer.java:225)
 org.compiere.server.Scheduler.run(Scheduler.java:413) [77]

#### Expected behavior
The services should be interrupted in order when is shut down the server

#### Other relevant information
- Your OS: MacOS
- Java version: JDK 11
- ADempiere version: 3.9.4 develop brach
- DB Provider: PG 
- DB version: 13

**Comment by marcalwestf** [comment]
Confirmed.
