### ISSUE TITLE
[Bug Report] Error when ADempiere Server Webui is shut down causing a possible memory leak

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#3587]
## Bug report
Error when ADempiere ADempiere Server WebUI is shut down causing a possible memory leak

#### Steps to reproduce
1.- Setup ADempiere using Tomcat 9.0
2.- Start the Server using utils/RUN_Server2.sh and await some minutes until start the processors starting
3.- Stop the Server using utils/RUN_Server2Stop.sh and check the log tomcat/logs/catalina.out

#### Screenshot or Gif

----------> WebappClassLoaderBase.clearReferencesThreads: The web application [webui] appears to have started a thread named [Thread-9] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@11.0.11/java.lang.thread.sleep(Native Method)
 org.zkoss.io.FileWatchdog.run(FileWatchdog.java:128) [77]
===========> WebappClassLoaderBase.checkThreadLocalMapForLeaks: La aplicaci?n web [webui] cre? un ThreadLocal con clave del tipo [org.adempiere.webui.session.ServerContext$1] (valor [org.adempiere.webui.session.ServerContext$1@53ce63f]) y un valor del tipo [org.adempiere.webui.session.ServerContext] (valor [{#AD_Language=en_US, org.compiere.model.DefaultRole=MRole[0,System Administrator,UserLevel=S  ,AD_Client_ID=0,AD_Org_ID=0]}]) pero no pudo quitarlo cuando la aplicaci?n web se par?. Los hilos se van a renovar con el tiempo para intentar evitar in posible fallo de memoria. [77]
===========> WebappClassLoaderBase.checkThreadLocalMapForLeaks: La aplicaci?n web [webui] cre? un ThreadLocal con clave del tipo [org.adempiere.webui.session.ServerContext$1] (valor [org.adempiere.webui.session.ServerContext$1@53ce63f]) y un valor del tipo [org.adempiere.webui.session.ServerContext] (valor [{org.compiere.util.CLogErrorBuffer.logs=[java.util.logging.LogRecord@4d8e5681, java.util.logging.LogRecord@6b8b0f77, java.util.logging.LogRecord@49327a76, java.util.logging.LogRecord@2b5d7071, java.util.logging.LogRecord@14d801c5, java.util.logging.LogRecord@271b449e], org.compiere.util.CLogErrorBuffer.history=[], org.compiere.util.CLogErrorBuffer.errors=[], #AD_Language=en_US, org.compiere.model.DefaultRole=MRole[0,System Administrator,UserLevel=S  ,AD_Client_ID=0,AD_Org_ID=0]}]) pero no pudo quitarlo cuando la aplicaci?n web se par?. Los hilos se van a renovar con el tiempo para intentar evitar in posible fallo de memoria. [77]

#### Expected behavior
When the WebUI server is shut down, the thread of each connection must be interrupted along with its context so as not to create a memory leak.

#### Other relevant information
- Your OS: macOS
- Java version: JDK11
- ADempiere version: 3.9.4 last build the develop branch 
- DB Provider: PG
- DB version: 13

**Comment by marcalwestf** [comment]
Confirming the findings of @e-Evolution .
Get exact the same results on catalina.out.

Documented it on Pull Request https://github.com/adempiere/adempiere/pull/3589#pullrequestreview-721596559.

**Comment by e-Evolution** [comment]
Memory usage by Web UI:

Memory usage when requesting the first connection for a user:

![image](https://user-images.githubusercontent.com/786968/129239317-d20ccea4-cea3-4351-91f2-52849eb60a1c.png)


Memory usage when defining the role and loading the dashboard:

![image](https://user-images.githubusercontent.com/786968/129239356-4d168897-6e67-4f8a-a275-27d0bc7033f9.png)


Memory usage After leaving the user logged in and waiting for a few minutes, the graph maintains an upward trend in memory usage.

For some reason the memory increases if you do any activity on the system.

I have a suspicion that the memory increase is due to improper handling in the use of the context 

After the trend of memory consumption without reason, when exiting the application and logging in again, the memory is recycled, but the consumption pattern continues when entering the application again

![image](https://user-images.githubusercontent.com/786968/129239767-d0a6edc5-c1c8-4e11-842c-d61374feab79.png)
