### ISSUE TITLE
 Toggling between single and multi row causes content to be lost

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere#3606]
#### Steps to reproduce
1. Open any window with text content line Search Value, Name, etc.
2. Display it in grid mode (=multi-row)
3. Edit the text context, without saving
4. Change to single-row display
5. Contents are lost, and also the save button becomes deactivated

#### Screenshot or Gif
![20210831_ChangeText](https://user-images.githubusercontent.com/1789408/131923901-34dc97ba-0003-492d-bcbc-919c0ef58880.gif)

#### Expected behavior
The contents should be also displayed when switching form multi-row to single-row display, similar to what happens when switching from single-row to multi-row.

#### Additional context
Solution explained by @dram  in PR https://github.com/adempiere/adempiere/pull/3592

**Comment by dram** [comment]
I have created a PR for fix this issue: https://github.com/adempiere/adempiere/pull/3608
