### ISSUE TITLE
Question?  Can we set the fields as shown in the picture?

### ISSUE THREAD

**Issue by ishanuda** [adempiere/adempiere#362]
HI,

This is a question to ask from the development team.
Can we configure the fields as shown in the picture?
So that we can give a long description to the field text with an example if needed.

![price-2](https://cloud.githubusercontent.com/assets/8893919/14949250/14dbce74-1066-11e6-9607-2b14f400405b.jpg)

Regards

**Comment by yamelsenih** [comment]
Hi @ishanuda currently the field are displayed filling the window.

What you need?

Best regard

**Comment by ishanuda** [comment]
Did you see the difference in the screen shot, it is custom made, 
not the same as adempiere window,

All the fields titles are on top of the fields.
this can not be set yet in the adempiere right? 
Can you understand what i am telling?

**Comment by yamelsenih** [comment]
Hahahaha, i don't see it detail, i think that it can be configurable 100% and it can be like follow:

1. Labels to **left**.
2. Labels to **Right**.
3. Labels to **Up**.

Is good idea.

**Comment by ishanuda** [comment]
yah you got it, then the UI will have a beautiful look and feel to the end users... :-)
