### ISSUE TITLE
[Feature Request] New functionality to enable the process of a document through workflow 

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#3690]
## Feature request
New functionality to enable the process of a document through workflow 

Currently, when a delivery or invoice is generated manually, they are processed using the document engine through the process this method, the drawback of this approach does not execute the workflow that may have additional authorizations, notifications, or steps configured that are not considered.

#### Describe the solution you'd like
The new functionality enables document processing through the workflow allowing to process of the steps configured within the workflow. 

#### Describe alternatives you've considered
Process documents from the document window using the document action button

**Comment by marcalwestf** [comment]
We have encountered the same issues.
A solution to it would be important.

**Comment by colabware-app** [comment]
Hey @e-Evolution, I’m sure you are struggling to keep up with the number of feature requests here. [With Colabware](https://colabware.co/project/1626013066528x395405457477893570), you can harness the power of crowdfunding to drive innovation and sustain developer livelihood. Please do let us know if you have any questions, and I hope we can assist with your project!
