### ISSUE TITLE
Landed cost accounting  fact is wrong for multiples cost element and calculate cost is wrong when cost amt is null

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#372]

**Comment by vasanth-z** [comment]
please check this done by e-evalution

ᐧ

**Comment by e-Evolution** [comment]
The issue was that call

```
MCostDetail.getByDocLineLandedCost(
						landedCostAllocation,
						as.getC_AcctSchema_ID(),
						costType.get_ID())).orElse(BigDecimal.ZERO)
```

The method execute this query , but in postgresql if any value is null then DB return null despite that some have a value. the bugfix was on constructor of entity now the CostAmt and CostAmtLL are setting as zero from that are created.

On the other hand the Doc_Invoice was optimize code to use lambda expresion and variable name  more DSL

`return new Query (landedCostAllocation.getCtx(), Table_Name, whereClause.toString() , landedCostAllocation.get_TrxName())
		.setParameters(
				landedCostAllocation.getAD_Client_ID(),
				acctSchemaId,
				landedCostAllocation.getM_Product_ID(),
				landedCostAllocation.getM_AttributeSetInstance_ID(),
				costTypeId,
				landedCostAllocation.getM_CostElement_ID(),
				landedCostAllocation.getC_InvoiceLine_ID(),
				landedCostAllocation.getM_InOutLine_ID(),
				landedCostAllocation.getC_LandedCostAllocation_ID())
		.aggregate(COLUMNNAME_CostAmt + " + " +
				COLUMNNAME_CostAdjustment + " + " +
				COLUMNNAME_CostAmtLL + " + " +
				COLUMNNAME_CostAdjustmentLL, Query.AGGREGATE_SUM);`

**Comment by e-Evolution** [comment]
Other important change was add M_CostElement_ID and C_LandedCostAllocation_ID to query the reason is that can exist multiples cost element
