### ISSUE TITLE
Missing entry of vavr-1.0.0-alpha-4.jar in .classpath

### ISSUE THREAD

**Issue by SusanneCalderon** [adempiere/adempiere#3736]
The missing entry in classpath leads to problems in the classes DB and IT_DB.
![imagen](https://user-images.githubusercontent.com/15349639/154181240-85b9191e-4496-40c6-a097-f3ebda150cd3.png)

Solution: Add entry.

**Comment by e-Evolution** [comment]
@SusanneCalderon , thank you Susanne , I fixed [4838d10](https://github.com/e-Evolution/adempiere/commit/4838d105707a57f49d79de7561be443a5b2e9166)

kind regards
Victor
