### ISSUE TITLE
[Feature Request] Add tax functionality to the requisition

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#3737]
## Feature request
Currently adempiere does not allow the handling of taxes in the requisition, in some processes it is necessary to estimate the amount of taxes by line of the requisition

#### Describe the solution you'd like
Implement a similar approach as in the purchase order

#### Describe alternatives you've considered
the only alternative is to use prices with taxes included but it is not possible since it is required to know the detail of the taxes 

![image](https://user-images.githubusercontent.com/786968/154560111-517dd31e-73c0-40c2-91a9-9b3d238ccbc9.png)

![image](https://user-images.githubusercontent.com/786968/154560778-eb1011a0-4bfc-4c57-84fd-be41bbe2982d.png)

![image](https://user-images.githubusercontent.com/786968/154561137-b3158959-a506-43f1-9e9a-c1ef48957a02.png)

**Comment by marcalwestf** [comment]
@e-Evolution  Víctor, could it be an XML file is missing?
I see for example a field _GrandTotal_, but not the XML where it is defined.
Same with new tab.

Thanks!
