### ISSUE TITLE
[Feature Request] Login Remove the Result Set and Adding Integration Test

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#3744]
## Feature request
Currently the login class uses resultset with a try catch that does not guarantee the release of resources

#### Describe the solution you'd like
Replace to use the new runResultSetFunction 

Adding Integration Test and Test Covert

**Comment by SusanneCalderon** [comment]
The new login does not work with various accounting schemas
![imagen](https://user-images.githubusercontent.com/15349639/168177507-02335106-bb1f-43d6-82c2-cc49f346f130.png)

![imagen](https://user-images.githubusercontent.com/15349639/168177777-9d173f0c-107e-451f-9584-293517cb6299.png)

The error occurs in line map

**Comment by SusanneCalderon** [comment]
@e-Evolution , Hello Victor, I think you forgot to define the general ledgers and defaults in your second accounting schema. 
![imagen](https://user-images.githubusercontent.com/15349639/172486519-8ec55d15-29a1-4257-8430-830a6eaa3883.png)
With this constelation you can reproduce the error
![imagen](https://user-images.githubusercontent.com/15349639/172486735-335db0b5-1a29-466e-9972-4bb0616d1fe1.png)
