### ISSUE TITLE
[Feature Request] Send Email Notification with Organization Email

### ISSUE THREAD

**Issue by rcapecce** [adempiere/adempiere#3776]
## Feature request

It is required to have the possibility of sending notifications by mail not only from a single company email, but also from different organizations.

### Describe the solution you'd like

For that, it's proposed to add to the Organization, the configuration of Email and password, just as the configuration is made in the Client.

In the code, it's proposed to determine if it corresponds to send the organization email or the company email, verifying if the record of the AD_Queue table has an organization established, and, in addition, the organization has the mail configuration parameterized.

#### Side: Generate Notification

The notification queue already has a method at the moment of defining the notification to establish by code with which organization to set the AD_Queue (most likely the organization of the PO in question)

#### Implementation Side of Send Mail.

- When the AD_NotificationQueue record is defined, it is already configured to take the AD_Client_ID and AD_Org_ID from the AD_Queue record.

##### EMailSender.sendNotification(MADNotificationQueue notification) Method

- Email Definition
- - The email of the Organization must be obtained if it is defined
- - Otherwise, obtain the email of the company as it has been done until now.
- Parameterization of the mail server
- - Should be changed to use Email class constructor overload, the current constructor uses this overload by not defining the mail server configuration, and then gets the company configuration. It has to be changed to get the one of the organization if it corresponds.

**Comment by rcapecce** [comment]
Hello! This functionality can be tested by running Request Notifications

**Comment by e-Evolution** [comment]
@rcapecce Hi Raul , Do you  adding some animate gif or screen show the new functionality ?

**Comment by rcapecce** [comment]
Hi @e-Evolution ! here you can configure the Organization Email Server to test this functionality
![image](https://user-images.githubusercontent.com/14218144/175091206-ed79cdd1-b4c7-47b8-915b-c4ef2eb9256a.png)

**Comment by e-Evolution** [comment]
@rcapecce Hi Raul , @niclopup Hi Nico!

Reviewing the functionality, I consider that it should be global or for the entire system, that is, ADempiere should first try to use the email configuration of the organization that generated the notification, if there is no email config, then it uses the company configuration.
