### ISSUE TITLE
Close Order does not update Total Lines Amount and total amount

### ISSUE THREAD

**Issue by niclopup** [adempiere/adempiere#3810]
## Bug report

When a Sales Order is Closed and it has a line with Delivered Quantity less than the Ordered Quantity, the line is updated, correcting the Ordered Quantity but it doesn't update the header of the order with the NEW  Total Lines Amount.

<br class="Apple-interchange-newline">

#### Screenshot or Gif

https://user-images.githubusercontent.com/31936815/165549155-89acb05e-3a68-4ea8-93ae-1621f4ab3aa7.mp4

#### Expected behavior
It should update the Total Lines Amount, the Grand Total and the Tax Order

**Comment by nsarlabos** [comment]
It also happens that when using the "Reopen Order" process, the taxes of the order are not recalculated either, looking bad both in the taxes tab and in the header of the order.
