### ISSUE TITLE
Process Dialog Display is bad, not adjusting rightly the components and have not scroll bar

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#386]
This issue appear after of Yamel refactory

**Comment by e-Evolution** [comment]
![1462984949](https://cloud.githubusercontent.com/assets/786968/15188860/7c02f970-176d-11e6-9abc-8b0837ca4692.png)

**Comment by yamelsenih** [comment]
Hi @e-Evolution please test it and tell me.

Best regards.
