### ISSUE TITLE
[Bug Report] 'Change Role' Issue regarding Internal Server Error

### ISSUE THREAD

**Issue by RamiroV13** [adempiere/adempiere#3861]
## Bug report
Issue lies within the option 'Change Role' at main ADempiere screen (after login). When you work a certain time with ADempiere (at least 30 minutes doing multiple stuff like creating new registers, editing and such.) and hit the 'Change Role' option, it appears an internal server error which only happens using ADempiere web version leading to only two posible paths... you either hit the back button from the browser or just close the browser. It's very concerning due to password/user id leaking and becoming visual for any user watching that screen.

#### Screenshot or Gif
![image](https://user-images.githubusercontent.com/89487449/167898540-39a81f89-d86e-4765-bd0f-4233fee703bb.png)
![image](https://user-images.githubusercontent.com/89487449/167898759-99ed5211-5e5c-4f0a-8373-97f77b8a1387.png)

#### Other relevant information
- Your OS: Windows 10
- Java version:
- ADempiere version: 3.9.2
- Browser [e.g. chrome, safari] Chrome
- Browser Version [e.g. 22] 101.0.4951.64
- DB Provider:
- DB version:

**Comment by marcalwestf** [comment]
@RamiroV13 Ramiro, some questions:  
- how many concurrent user are needed to reproduce the error? 
- are you using the latest develop branch? 
- if not, which version of development are you using? 

Thanks

**Comment by RamiroV13** [comment]
test done sucesfully
