### ISSUE TITLE
getSchema method in DB_PostgreSQL.java is better use the adempiere user

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#391]
The method **getSchema()** on DB_PostgreSQL.java class is hardcode the name **adempiere**, if the user want use other name then it can't change the schema.
<pre>
public String getSchema()
{
	return "adempiere";
}
</pre>

Is better use it like DB_Oracle.java
<pre>
public String getSchema()
{
	if (m_userName != null)
		return m_userName.
	log.severe("User Name not set (yet) - call getConnectionURL first");
	return null;
}   //  getSchema
</pre>

**Comment by yamelsenih** [comment]
For MySQL is the same

**Comment by mckayERP** [comment]
Agree with this change.  You should also look at the .bat and .sh scripts to make sure they work as you expect.  RUN_ImportAdemiere sets  the schema to the username in the RUN_Setup dialog.  RUN_DBRestore uses what is in the dmp which could be form another database/schema and doesn't rename it.  This last may require manual config.

Perhaps consider adding the schema as a separate entry in the RUN_Setup instead of the database user name?

**Comment by yamelsenih** [comment]
Hi @mckayERP i test the follow:
- Alter Column.
- I restore one DB with two scheme (adempiere_test from adempiere_test user) and (adempiere from adempiere user).
- I write from adempiere in both scheme and it worked with separate data.

You can test if the setup?

Best regards.

**Comment by e-Evolution** [comment]
Hi Yamel a posible issue is that the PG seed had in your sentence created in adempiere schema (Adempiere_pg.dmp) to default 

--
-- PostgreSQL database dump
--

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;

--
-- Name: adempiere; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA adempiere;

So I think that this change only solve a part of problem.

**Comment by yamelsenih** [comment]
Hi @e-Evolution i think that it should be created from SH instead the dmp. I remember that Compiere when restored DB in oracle make the user and other from SH

**Comment by mckayERP** [comment]
The script run_importadempiere calls the database specific code importadempiere.  For postgres, this includes the following steps to create and rename the schema:

REM Adempiere_pg.dmp always imports to schema "adempiere" owned by user "adempiere"
REM so we need to rename it to %dbSchema% and change ownership to %dbUser%

REM rename schema
IF "%dbSchema%"=="adempiere" GOTO :NORENAME
ECHO rename schema "adempiere" to "%dbSchema%"
SET PGPASSWORD=%dbPwd%
psql -h %dbHost% -p %dbPort% -d %dbName% -U %dbUser% -c "ALTER SCHEMA adempiere RENAME TO %dbSchema%" 1>NUL
SET result=%ERRORLEVEL%
IF %result%==0 GOTO :SCHEMARENAMED
ECHO rename schema failed with exit code %result%
EXIT /B %errorRenameSchema%
:SCHEMARENAMED
SET PGPASSWORD=
:NORENAME

REM change schema ownership
IF "%dbUser%"=="adempiere" GOTO :NOREOWN
ECHO change schema ownership to "%dbUser%"
REM change all objects in %dbName% database owned by adempiere to ownership of %dbUser%
SET PGPASSWORD=%dbPwd%
psql -h %dbHost% -p %dbPort% -d %dbName% -U %dbUser% -c "REASSIGN OWNED BY adempiere TO %dbUser%" 1>NUL
SET result=%ERRORLEVEL%
IF %result%==0 GOTO :REOWNED
ECHO change schema ownership failed with exit code %result%
EXIT /B %errorModifySchema%
:REOWNED
SET PGPASSWORD=
:NOREOWN

REM set searchpath
ECHO set default schema to "%dbSchema%"
SET PGPASSWORD=%dbPwd%
psql -h %dbHost% -p %dbPort% -d %dbName% -U %dbUser% -c "ALTER ROLE %dbUser% SET search_path TO %dbSchema%, pg_catalog" 1>NUL
SET result=%ERRORLEVEL%
IF %result%==0 GOTO :SEARCHPATHSET
ECHO set default schema failed with exit code %result%
EXIT /B %errorModifyUser%
:SEARCHPATHSET
SET PGPASSWORD=

**Comment by e-Evolution** [comment]
Hi @yamelsenih this commit not working , the user name is defined in method

```
  Get Database Connection String
	 *  @param connectionURL Connection URL
	 *  @param userName user name
	 *  @return connection String
	 */
	public String getConnectionURL (String connectionURL, String userName)
	{
		m_userName = userName;
		m_connectionURL = connectionURL;
		return m_connectionURL;
	}	//	getConnectionURL
```

But this never is called , So this approach not work #

**Comment by mckayERP** [comment]
Try 

	/**
	 * 	Get JDBC Schema
	 *	@return schema (dbo)
	 */
	public String getSchema()
	{
		//	vpj-cd e-evolution 03/04/2005
		//	BR [ 391 ]
		if (m_userName == null) {
			CConnection cconn = CConnection.get(Adempiere.getCodeBaseHost());
			m_userName = cconn.getDbUid();
		}
		return m_userName;
	}	//	getSchema

This seems to work as the Uid matches the User Name.

**Comment by yamelsenih** [comment]
I agree with @mckayERP
