### ISSUE TITLE
Translation method does not use PO class

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#392]
The insertTranslations() and updateTranslations() methods into [PO.java](https://github.com/adempiere/adempiere/blob/master/base/src/org/compiere/model/PO.java) class, does not use PO class, it not allow log the records in migration tool for all translations

**Comment by dixon22ma** [comment]
Translation created with System client 


When adding an item of print format, the translation is automatically created by the system. However, this record is created with System company, and it is not possible to make modifications.

[PO.java](https://github.com/adempiere/adempiere/blob/hotfix/3.8.0%23002/base/src/org/compiere/model/PO.java#L3269)

Suggestion Change by:
po.setAD_Client_ID(getAD_Client_ID());

**Comment by yamelsenih** [comment]
Thank @dixon22ma it is changed
