### ISSUE TITLE
Unit of measure system (Imperial/ Metric) can not separate and configure in the UOM window

### ISSUE THREAD

**Issue by ishanuda** [adempiere/adempiere#393]
HI, 

I have seen that the UOM Type is in the ADempiere unit of measure window.
Ex: Angle, Area, Length etc

If we set the UOM Type as Length,
How to set the measurement system as Imperial or Metric

thanks.

**Comment by yamelsenih** [comment]
Hi @ishanuda where is it? Window?

**Comment by ishanuda** [comment]
Hi @yamelsenih,

As you can seen in the Unit of Measure windows attached, 
It has only the type angle, weight etc reference to Metric Ton, Kilogram, 

We can not show whether this units are in Imperial or Metric if we want to show it in a document,
because there is no palace to mention it in the system.

![uom-window-detail](https://cloud.githubusercontent.com/assets/8893919/15424981/32fcb580-1ea3-11e6-9678-a8919a29afef.jpg)
![uom-window-grid](https://cloud.githubusercontent.com/assets/8893919/15424980/32fb3764-1ea3-11e6-822b-e983098114ce.jpg)


By the way, do you have any idea about this issue,
https://github.com/adempiere/adempiere/issues/395

Best regards.

**Comment by sdgathman** [comment]
On 05/20/2016 06:27 AM, Ishan Udayapriya wrote:
>
> Hi @yamelsenih <https://github.com/yamelsenih>,
>
> As you can seen in the Unit of Measure windows attached,
> It has only the type angle, weight etc reference to Metric Ton, Kilogram,
>
> We can not show whether this units are in Imperial or Metric if we
> want to show it in a document,
> because there is no palace to mention it in the system.
>
Imperial ton and Metric ton are two different units.  Selecting one or
the other selects Imperial or Metric.   You probably knew that, so maybe
you problem is that you have a form with a checkbox for
Imperial/Metric.  Where will the form fill get this?  In that case, it
is an attribute of the unit of measure.  You could add a field to UOM
that is Imperial/Metric/NA, or more generally Unit System - as there are
several metric unit systems as well.

On that note, it always irks me that kilograms are usually listed as a
weight . . . (it is a measure of mass - pounds are a measure of weight,
and the two are not generally convertible).

**Comment by mckayERP** [comment]
Conversion varies depending on the planet your on. :)

**Comment by mckayERP** [comment]
Really though, the difference is in the symbols and names.  See the [ISO standards on units of measure](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/codesets/_Y4XF0tp-Ed-ak6NoX_4Aeg_385163498).

Metric ton or tonne (TONE, t, TNE) = 1000kg
Imperial ton (TON) = 2240 lbs.  (This has two variants Long TON in UK (lton_av) and Short TON in US (ston_av) = 2000lbs.  av = avoirdupois or "weight")

A better source is [unitsofmeasure.org](http://unitsofmeasure.org) which lists more complete symbols to distinguish the measures.  [See para 39](http://unitsofmeasure.org/ucum.html#para-39) for the long and short ton definitions.

UOMs are a complex set of data.   I'm not sure you need a field to differentiate or categorize the types as imperial or metric as this would be rather limited considering all the possible types in the specifications.
