### ISSUE TITLE
"BUILD FAILED" Error running Github Action "ADempiere Build" (file: "main.yaml")

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere#3931]
#### Steps to reproduce
1. Create a pull request
2. Wait a while until the action  `ADempiere Build` for this pull request is finished.
3. Go to  `Actions` and click on an executed `ADempiere Build` workflow
4. Click on the `create-seed` job
5. Expand the `Build ADempiere ....` section
6. According to action log file, around line 6872, the installation fails with the message "BUILD FAILED".
7. According to action log, the installation is interrupted and it continues with the next ANT commands (`Run Import Adempiere` etc.)
8.  _Sign Database Build_ and _Setup Client Environment_ are not executed.

#### Screenshot or Gif
![imagen](https://user-images.githubusercontent.com/1789408/176060352-50f1a4f5-2c5d-4e76-9780-eae23c630bc3.png)
![imagen](https://user-images.githubusercontent.com/1789408/176060430-468a990e-4d6e-4f32-a351-a6b2ca1ebce2.png)

#### Expected behavior
The installation should finish the Tomcat installation correctly and execute  _Sign Database Build_ and _Setup Client Environment_.

#### Other relevant information
- Your OS: Github-hosted runner
- Java version: 11
- ADempiere version: 394

#### Error Generation

On _install/build/Adempiere/build.xml_, line 662+664 the contents of the Tomcat server _conf_ directory are copied to the Adempiere installation _/tomcat/conf_ directory (usually 10 files, including _catalina.properties_):
```
<copy todir="${CATALINA_BASE}/conf" failonerror="false">
  <fileset dir="${CATALINA_HOME}/conf" includes="**"/>
</copy>
```
Further down, on _install/build/Adempiere/build.xml_, line 687+688 there is the following code:
`<replaceregexp file="${CATALINA_BASE}/conf/catalina.properties" match="shared.loader=" replace='shared.loader="${catalina.base}/shared/lib","${catalina.base}/shared/lib/*.jar"' byline="true"/>`

`<replaceregexp file="${CATALINA_BASE}/conf/catalina.properties" match="xom-\*.jar" replace='xom-\*.jar,\\\\${line.separator}Adempiere.jar,\\\\${line.separator}adempiereRoot.jar,\\\\${line.separator}AdempiereSLib.jar,\\\\${line.separator}adempiereApps.jar,\\\\${line.separator}javax.mail.jar' byline="true"/>
`

Then according to the action log, the error is thrown: "BUILD FAILED".

```
2022-06-17T22:10:11.6612975Z      [java] [replaceregexp] The following file is missing: '/home/runner/work/adempiere/adempiere/adempiere/Adempiere/tomcat/conf/catalina.properties'
2022-06-17T22:10:11.6615443Z      [java] BUILD FAILED
2022-06-17T22:10:11.6616083Z      [java] /home/runner/work/adempiere/adempiere/adempiere/Adempiere/build.xml:692: Warning: Could not find file /home/runner/work/adempiere/adempiere/adempiere/Adempiere/tomcat/conf/server.xml to copy.
```

#### Error Cause

- It seems that "ubuntu-latest" doesn't install Tomcat by default.
- I suppose that if this is the case, there is no _catalina.properties_ file, and the `<replaceregexp />` ANT command will deliver an error.
- In file _.github/workflows/main.yml_ there is no indication that the Tomcat 9 server will be installed
- On my local machine, I installed Tomcat manually and there is no error, so and I can see a file named _tomcat/conf/catalina.properties_.
- This error was maybe introduced after the server isn't anymore built inside the Adempiere installation.

#### Bug Fix (suggestion)

How to solve this problem? A solution may be adding an action to **main.yaml,** after JDK, e.g.:
```
      # Deploy Tomcat-Server
      - name: Deploy Tomcat ...
        run: >
            echo  "Installing Tomcat version 9" &&
            RUN cd tmp && 
            wget "https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.64/bin/apache-tomcat-9.0.64.tar.gz" && 
            tar -zxvf /tmp/apache-tomcat-9.0.64.tar.gz -C /opt && 
            cd /opt && mv apache-tomcat-9.0.64 tomcat && 
            cd /tmp && rm -rf *
```

This way, there would exist a _/opt/tomcat_ directory, with all directories of the installation, including _conf_ and its 10 files, among them _catalina.properties_.

**Comment by marcalwestf** [comment]
@carlosaparadam , @e-Evolution , @yamelsenih : comments welcome!

**Comment by carlosaparadam** [comment]
Hi @marcalwestf, i think so that proposal solution solving this bug successfully
