### ISSUE TITLE
Why the subscription type is in product level

### ISSUE THREAD

**Issue by ishanuda** [adempiere/adempiere#395]
Hi,

I saw that the subscription type is in the product level.
1. There can be more than one subscription type per product.
2. There can be customers having more than one subscription type for different types of products.

As I can see, assigning a single subscription type in product level will violate assigning of the product to several customers in a subscription, when their having different types of subscription.

What is the purpose of placing the subscription type in product level?

My apology if I am mistaken the business logic here and, an explanation is highly appreciated.

Best regards.

**Comment by yamelsenih** [comment]
I see it but just exists Table and windwow with reference to product, the source code is unsupported mow
