### ISSUE TITLE
Date changes format in records as you change Mono and Grid

### ISSUE THREAD

**Issue by niclopup** [adempiere/adempiere#3973]
## Bug report
in a window with more than 40 records, in the last records the date changes it format showing MM/dd/yyyy when it should be dd/MM/yyyy.

The strange behaivor is that when you change the record form Grid to Mono, the date format changes and you see it ok.

#### Steps to reproduce

![image](https://user-images.githubusercontent.com/31936815/185420113-cb91e7a0-8996-4085-989d-e62696fa40c0.png)

https://user-images.githubusercontent.com/31936815/185419581-484a918e-a935-4215-a3af-a11f7b0d364b.mp4

#### Other relevant information
- Your OS:
- Java version:
- ADempiere version: Develop
- Browser [e.g. chrome, safari] Chrome
- Browser Version [e.g. 22]
- DB Provider:
- DB version:

**Comment by marcalwestf** [comment]
@niclopup Nico, some questions to delimit the issue:
- did you try Swing?
- does it happen wirh any window that has a date?
- does it happen with all dates? 
- is 40 the exact number that produces the error?
- does the pagination play a role?
--what happens if you have say 100 records and you filter to >40?
- if you order the records differently: does the error still happen on the 40th row?

Thanks

**Comment by niclopup** [comment]
@marcalwestf i answer your questions

- did you try Swing?
No

- does it happen wirh any window that has a date? 
Yes. In develop i only try with "Invoice Vendor" importing 40 Invoice AP but in other instance i verify that happens in every window in every date field

- does it happen with all dates? 
Yes

- is 40 the exact number that produces the error? 
No, i couldn find the exact way to reproduce. Normally it doesnt happens in the firs records, you have to scroll down to see the first error.

- does the pagination play a role? 
I don´t think so, the error happens 

- what happens if you have say 100 records and you filter to >40? 
i dont understand. it happens when you have to scroll down in a window, it is not exactly 40 records when it appear

- if you order the records differently: does the error still happen on the 40th row? 
in grid the error persist. it only corrects the format when you change to mono and after to grid but it only corrects the record you are in, not every record.

**Comment by marcalwestf** [comment]
@niclopup  thanks Nico, I will test on a fresh seed with the information you provided.
