### ISSUE TITLE
[Feature Request] Adding URL Map to a location map to Business Partner Location

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#3985]
## Feature request
Adding field with URL Map to a location to Business Partner Location

It is quite useful to use an URL Map to get the exact location of an address.

#### Describe the solution you'd like

This functionality allows you to open the map with the address in embedded format or in a new tab.

This new feature looks for longitude and latitude coordinates in the URL Map to synchronize it with the address data.

![image](https://user-images.githubusercontent.com/786968/190224218-90036873-68cb-4dac-83d7-4b5e21fa91bc.png)

#### Describe alternatives you've considered
Currently, the system does not have an option, but it tries to build the URL dynamically but it may not be exact because it does not use longitude or latitude.

**Comment by marcalwestf** [comment]
hi @e-Evolution  Victor, this is a valuable feature.
I wonder if the button on the Address field that goes to Google Maps -which by the way doesn't work- could be disabled because it is obsolete and causes confusion.

**Comment by e-Evolution** [comment]
@marcalwestf in my case are work to get map image : 

![image](https://user-images.githubusercontent.com/786968/190223064-0f44390e-04c1-42b3-b896-3d48ec47e658.png)

And here is the route between Organization Location and Customer Location : 

![image](https://user-images.githubusercontent.com/786968/190223771-f71a2be0-6f6c-40e7-b3c8-2740039c0400.png)

Why do you say it doesn't work?

**Comment by e-Evolution** [comment]
More intensive testing was done and the problem was found to sync latitude and longitude data when creating a business partner address.

Another problem found is that the address cache is not updated after a change.
