### ISSUE TITLE
Rules do not work in Adempiere 394

### ISSUE THREAD

**Issue by SusanneCalderon** [adempiere/adempiere#3990]
## Bug report
I tested 394 in a database from a running installation which uses rules for callouts and table script validators. The database was updated until xml 9,880. Every rules produced the same error: "Script1.groovy: 1: unable to resolve class org.compiere.model.xxx". 

To confirm this error I tested  a new rule in the newest seed database from github and got the same error.

#### Steps to reproduce
**1. Create a rule**
![image](https://user-images.githubusercontent.com/15349639/193435052-1bd34c9f-38d3-4e94-aad0-ebea117bd70f.png)

**2. Assign this rule to table c_Invoice**

![image](https://user-images.githubusercontent.com/15349639/193435082-b208973b-7f9c-412e-8ab0-143b6dce2590.png)

**3. Stop the Server and start the server**

**4. Generate a new invoice and try to save**

![image](https://user-images.githubusercontent.com/15349639/193435151-c48cfa65-f80d-448c-b2c7-a9f52fb06db1.png)

Complete error message: Error: _javax.script.ScriptException: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed: - Script1.groovy: 1: unable to resolve class org.compiere.model.MInvoice @ line 1, column 1. import_

#### Additional context
The problem only occurs in webUI, in Swing the invoice is saved and the rule is executed.
![image](https://user-images.githubusercontent.com/15349639/193435226-ff396777-b3a8-4272-8804-7b3ef66ddc7d.png)

**Comment by marcalwestf** [comment]
Further findings: one first thought was that possibly there are different groovy versions in Swing and ZK. 
Actually, there is only one groovy version, and the libraries for Swing and ZK are identical.

Here the images that support it:
1.- There is only one place in the repository where the groovy libraries are kept:
![imagen](https://user-images.githubusercontent.com/1789408/194415185-f4e2c90a-716e-417c-99f8-fd3937025129.png)

2.-  in tools/build.xml both libraries groovy-all-2.4.15.jar and groovy-engine.jar are defined for **CSTools.jar**
![imagen](https://user-images.githubusercontent.com/1789408/194413763-074e3d98-6765-4449-8861-ca0579f29d22.png)

3.-  in tools/build.xml both libraries groovy-all-2.4.15.jar and groovy-engine.jar are defined for **CCTools.jar**
![imagen](https://user-images.githubusercontent.com/1789408/194414583-a84a4a26-b386-42b7-a4f7-bc1aee522cd4.png)

4.- In the installation, both **CSTools.jar** and **CCTools.jar** have the same libraries
![imagen](https://user-images.githubusercontent.com/1789408/194414836-3b69e65f-657d-4587-83fa-5385e250071d.png)
![imagen](https://user-images.githubusercontent.com/1789408/194414959-d9fbf457-171c-44d8-846b-35e79d748661.png)

**Comment by marcalwestf** [comment]
@e-Evolution , @yamelsenih  another observation: I wonder if this has something to do with the loss of context?
This idea comes to my mind because there is another situation where context is lost on ZK.

**Comment by marcalwestf** [comment]
@e-Evolution  new observation: when **running with Jetty**, it works!!!

The error reported by @SusanneCalderon  doesn't stem from any refactoring but from the configuration of Tomcat.
I will try to copy The Groovy library on Tomcat and see what happens.

**Comment by marcalwestf** [comment]
@e-Evolution  it is definitely not an error of refactoring, but of tomcat configuration.

I just copied both libraries groovy-all-2.4.15.jar and groovy-engine.jar into $ADEMPIERE_HOME/tomcat/lib and the error did not occur on Tomcat:
![imagen](https://user-images.githubusercontent.com/1789408/194678540-afde4407-aab9-4524-b988-0d0d7ece1dcb.png)

**Comment by e-Evolution** [comment]
@marcalwestf Hi Mario!

The content of these two libraries groovy-all-2.4.15.jar and groovy-engine.jar  should be inside AdempiereSLib.jar, so it's will be easy to solve, we just have to look how the build.xml builds AdempiereSLib.jar so that it is included the all the files of  groovy-all-2.4.15.jar and groovy-engine.jar inside.

The AdempiereSLib.jar  should containt all the .class for all Web Applications (WAR) , AdempiereSLib.jar  is as a global library , it avoid that we need copy each library jar file inside of each web application (WAR)

Please can you modify the build.xml to include all class inside AdempiereSLib.jar?

kind regards
Victor

**Comment by marcalwestf** [comment]
@e-Evolution  I forgot to mention that I looked at AdempiereSLib.jar and the classes seem to be in the package, but they seem not to be recognized;
![imagen](https://user-images.githubusercontent.com/1789408/194710439-ccd6edae-4879-4d21-bc0b-5a510292c40f.png)
