### ISSUE TITLE
Error in jasperreport because JASPER_STARTER_CLASS  in ProcessInfo is not updated

### ISSUE THREAD

**Issue by SusanneCalderon** [adempiere/adempiere#3991]
## Bug report
The static variable JASPER_STARTER_CLASS in the class ProcessInfo has the old path. As the class was moved, this pathe mus be updated to the new path.

## Steps to reproduce:
Try any process with an attached jasperreport, where the field classname is empty.

```

public final class ProcessUtil {

	public static final String JASPER_STARTER_CLASS = "org.compiere.report.ReportStarter";
```

Correct variable:
```

public final class ProcessUtil {

	public static final String JASPER_STARTER_CLASS = "org.compiere.jr.report.ReportStarter";
```

**Comment by marcalwestf** [comment]
this issue was solved by accepting the pull request
