### ISSUE TITLE
Currently is posible add tax amount manually for each line but it always is setting in zero after to save

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#400]

**Comment by e-Evolution** [comment]
Business case:

Some moment is necessary adding the tax amount manually for Sales Order or Purchase Order,  the system should calculate the tax only when amount  is zero or never was entry by the user .

The tax rate need be setting as tax document level and the user entry manually the tax amount 

So the system should created the tax information for each line and calculate total line using the price and tax amount.

**Comment by trifonnt** [comment]
Hi Victor,

In which field in Sales Order, Purchase Order, Sales Order Line or Purchase Order Line user can enter Tax Amount manually?

**Comment by e-Evolution** [comment]
![captura de pantalla 2016-05-20 a las 7 02 39 p m](https://cloud.githubusercontent.com/assets/786968/15444995/791ae086-1ebd-11e6-993a-0078441a2115.png)
 The field is show as Tax Amount in Purchase Order
