### ISSUE TITLE
[Bug Report]  Notification Recipients Window is in incorrect place into the  menu option  

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#4004]
## Bug report
The Notification Recipients Window is in the incorrect place in the  menu option 

#### Steps to reproduce
1.  Import Adempiere database seed for 3.9.3
2. RUN_MigrationXML 
3. Review the menu tree 

#### Screenshot or Gif
![image](https://user-images.githubusercontent.com/786968/198751342-b3956f06-5066-4a2a-93f1-529fac8a81cc.png)

#### Expected behavior
The new window should be in the menu System Admin -> Server -> System Queues 

![image](https://user-images.githubusercontent.com/786968/198751446-c832a34d-a13e-48da-9bcb-55ffcac71c87.png)

#### Other relevant information
- Your OS: macOS
- Java version: 17
- ADempiere version: 3.9.4 nightly build based on develop branch
- DB Provider: PG
- DB version: 15

**Comment by rcapecce** [comment]
In the action https://github.com/adempiere/adempiere/actions/runs/3224295573 the seed has this item in the correct place as you comment.
Can you check if you has applied the migration 09850 and 09860?

https://github.com/adempiere/adempiere/blob/develop/migration/393lts-394lts/09850_3927_New_Notification_Window_per_user.xml and
https://github.com/adempiere/adempiere/blob/develop/migration/393lts-394lts/09860_3927_New_Notification_Window_per_user.xml
