### ISSUE TITLE
GitHub Actions: Artifact "adempiere-postgresql-seed" generated with 0 Bytes

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere#4006]
## Bug report
When creating or pushing a pull request, and a seed is to be made, the artifact generated has the size of zero bytes.

#### Steps to reproduce
- Create a pull request that changes an XML migration file.
- see the size of the artifacts generated
- see the log of _/adempiere/.github/workflows/main.yml_, step _Build Adempiere with database restore..._

#### Screenshot or Gif

1.- Artifact `adempiere-postgresql-seed` generated with 0 bytes size.
![imagen](https://user-images.githubusercontent.com/1789408/199794374-fd6748a3-f075-46bf-8373-321017c83906.png)

2.- Error executing the Github Action `build all` from _/adempiere/.github/workflows/main.yml_
![imagen](https://user-images.githubusercontent.com/1789408/199795502-6542dcd7-baa8-46c1-a717-0f8884f88f46.png)

#### Expected behavior
When creating a pull request that changes a XML migration file, the generated seed should be complete.

#### Other relevant information
- This happens on Github

#### Additional context
The error
```
[exec] pg_dump: error: server version: 15.0 (Debian 15.0-1.pgdg110+1); pg_dump version: 14.5 (Ubuntu 14.5-2.pgdg20.04+2)
     [exec] pg_dump: error: aborting because of server version mismatch
```

seems to hint to Postgres a version mismatch.
The database server is a Debian, with version 15.0, whereas the pg_dump version is on Ubuntu with version 14.5.

**Comment by marcalwestf** [comment]
With the test pull request https://github.aom/adempiere/adempiere/pull/4007 , the seed is generated correctly with Postgres 14.5, as it is now not possible to run GitHub Actions with Postgres 15.0: 

![imagen](https://user-images.githubusercontent.com/1789408/199873207-3d4235b6-bef1-4341-bc6f-22e2e9a1defc.png)

![imagen](https://user-images.githubusercontent.com/1789408/199872882-383173fa-abd2-4ca3-94da-5722da699e5d.png)

![imagen](https://user-images.githubusercontent.com/1789408/199873266-770f5ba3-0b44-44bb-a082-5392d21a05c3.png)

**Comment by yamelsenih** [comment]
Hi, with the last pr was change the PostgreSQL version to 15 but it make a wrong behavior before export because there have distints versions, here the log:
```Shell
export-database:
     [echo] Run Export Database
     [exec] Setting myEnvironment ....
     [exec] Export Reference - /home/runner/work/adempiere/adempiere/adempiere/Adempiere (adempiere)
     [exec] ADempiere PostgreSQL Database Export
     [exec] Saving database reference@adempiere to /home/runner/work/adempiere/adempiere/adempiere/Adempiere/data/Adempiere_pg.dmp
     [exec] pg_dump: error: server version: 15.1 (Debian 15.1-1.pgdg110+1); pg_dump version: 14.6 (Ubuntu 14.6-1.pgdg22.04+1)
     [exec] pg_dump: error: aborting because of server version mismatch
     [exec] adding: Adempiere_pg.dmp(in = 0) (out= 0)(stored 0%)
     [echo] Run Export Database finished
```

A example can be [here](https://github.com/erpcya/adempiere/releases/tag/3.9.4-rc-1.1.0)
![Screenshot from 2022-12-16 11-08-30](https://user-images.githubusercontent.com/2333092/208127919-acf1ebfe-9e18-4807-8ad3-ff9adc313387.png)


You can see the complete log [here](https://github.com/erpcya/adempiere/actions/runs/3713753683/jobs/6296785473#step:6:26320)

**Comment by yamelsenih** [comment]
I am writing a change and testing it [here](https://github.com/erpcya/adempiere/releases/tag/3.9.4-rc-1.1.1)
