### ISSUE TITLE
New the report Demand delivery planning and This report show all information necessary to a delivery schedule based on Outbound Order

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#401]
The demand delivery planning report shows the demands that must be delivered to the promised date
This report show all information necesesary to a delivery schedule based on Outbound Order

**Comment by mckayERP** [comment]
Hi Victor, I'm having issues with the xml migration. I'm getting errors related to duplicate IDs in the translation tables for step 2710, 2750, 2770 etc ...

Is anyone else having this problem?

M

**Comment by e-Evolution** [comment]
The Report is working 

![captura de pantalla 2017-06-29 a la s 20 21 19](https://user-images.githubusercontent.com/786968/27717104-8fd22412-5d08-11e7-9908-3136b83349d4.png)
