### ISSUE TITLE
GitHub Actions: Run Workflow on Postgres 15

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere#4013]
## Feature request
Right now, the workflow `ADempiere Build With ANT` uses a Postgres 14.5 image. 
Being Postgres 15.0 the latest Postgres version and due to the fact that this version has already been tested by some ADempiere contributors, it is coherent to modify the workflow in a way that it runs on Postgres 15.0.

This issue will be implemented after #4012 has been programmed and accepted.

@e-Evolution  Víctor, you found somewhere a way to implement it and had some suggestions.
Can you please put your findings here?

**Comment by yamelsenih** [comment]
Hi @marcalwestf I was wrote a minor change and work for PostgreSQL 14.6
