### ISSUE TITLE
Mail setup is hardcoded

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#402]
The ADempiere mail setup practically does not exists, basically it have just the following:

- Mail Host.
- SMTP Authentication
- Request email
- Request User
- Request User Password

![issue175](https://cloud.githubusercontent.com/assets/2333092/15416762/c33dc8d6-1e18-11e6-9439-c0b02574b523.png)

It is very basic and the source is hardcode:

<pre>
Properties props = System.getProperties();
props.put("mail.store.protocol", "smtp");
props.put("mail.transport.protocol", "smtp");
props.put("mail.host", m_smtpHost);
if (CLogMgt.isLevelFinest())
	props.put("mail.debug", "true");
//
Session session = null;
try
{
	if (m_auth != null)		//	createAuthenticator was called
		props.put("mail.smtp.auth", "true");
	if (m_smtpHost.equalsIgnoreCase("smtp.gmail.com")) {
		// TODO: make it configurable
		// Enable gmail port and ttls - Hardcoded
		props.put("mail.smtp.port", "587");
		props.put("mail.smtp.starttls.enable", "true");
	}

	session = Session.getInstance(props, m_auth);
	session.setDebug(CLogMgt.isLevelFinest());
}
catch (SecurityException se)
{
	log.log(Level.WARNING, "Auth=" + m_auth + " - " + se.toString());
	m_sentMsg = se.toString();
	return se.toString();
}
catch (Exception e)
{
	log.log(Level.SEVERE, "Auth=" + m_auth, e);
	m_sentMsg = e.toString();
	return e.toString();
}
</pre>

**Comment by yamelsenih** [comment]
I proposal the folowing:
* Create a table named **AD_EMailConfig** with the following columns:
 * Name
 * IsSmtpAuthorization
 * SMTPlHost
 * EncryptationType: As list (None, SSL, TLS)
 * Port
* The **AD_EMailConfig** is referenced in **AD_Client** table.
* Optional the **AD_EMailConfig** is referenced in the **AD_User** table (it allow use distint outgoing mail server if you want).

**Comment by mckayERP** [comment]
+1!  Well and long overdue.  Great suggestion.

Mike

**Comment by yamelsenih** [comment]
I put the ERD here
![issue176](https://cloud.githubusercontent.com/assets/2333092/15447221/55c7bfe0-1f04-11e6-8c92-01ef2eea7fec.png)

**Comment by yamelsenih** [comment]
I put the ERD here
![issue176](https://cloud.githubusercontent.com/assets/2333092/15447488/be1a9b36-1f0d-11e6-9884-467295936e18.png)

**Comment by armenrz** [comment]
Hi Yamel,

+1 good improvement.

**Comment by sajeevsahadev** [comment]
"The ADempiere mail setup practically does not exists," @yamelsenih  Actually what is the issue related to this. Now I cannot configure the mails in adempiere. While trying to connecting the smtp.gmail.com, its saying authenticating issues. And interesting thing is, I am getting a mail from google team saying an "	

> **Sign-in attempt prevented. We strongly recommend that you use a secure app, like Gmail, to access your account. All apps made by Google meet these security standards. Using a less secure app, on the other hand, could leave your account vulnerable**

."

**Comment by ansujohn1989** [comment]
Svvxbn

Dhjkkjj

**Comment by yamelsenih** [comment]
Hi @sajeevsahadev the ADempiere setup already exists when you make the setup, also it exists int the client definition like the show the previous images.

My proposal is make a table like you see in the ERD for handle many email configuration.

The error that you said is because GMail update the authentication type to oAuth, i will include it change with EMail configuration.

Best regard.

**Comment by sajeevsahadev** [comment]
Thanks @yamelsenih .You are correct. I could send the mail from smtp.mail.yahoo.com.
The ERD looks good.

**Comment by yamelsenih** [comment]
I just upload the new ERD with **Protocol** column for determinate the **SMTP**, **POP3** and **IMAP** protocols
![issue179](https://cloud.githubusercontent.com/assets/2333092/15701839/66932c9c-27a6-11e6-8cb4-db4109cd17a7.png)

**Comment by yamelsenih** [comment]
For Documentation of it see: [http://wiki.adempiere.net/Spin_Contribution:_FR:_EMail_Config](http://wiki.adempiere.net/Spin_Contribution:_FR:_EMail_Config)
