### ISSUE TITLE
The User don't have a Unique Account Name

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#403]
The user in ADempiere don't have a unique value, also it use the name instead the value for login, my proposal:
- Use the **Value** column like **login user**.
- Add index in **Value** column for make it unique.
- Add a flag for identify the login users of contact users.
- Update the current data for add support.

**Comment by trifonnt** [comment]
> Add index in Value column for make it unique.

Index MUST be on AD_Client_ID + Value or AD_Client_ID + Name

> Add a flag for identify the login users of contact users.

What name would you propose? IsInternalUser

Regards,
Trifon

**Comment by yamelsenih** [comment]
Hi @trifonnt yes you are right.
I propose IsLoginUserlike flag, the you can know the user login currently I know it just like: 
<pre>
WHERE Password IS NOT NULL
</pre>

**Comment by trifonnt** [comment]
> propose IsLoginUserlike flag, the you can know the user login currently I know it just like:
>
>WHERE Password IS NOT NULL

I have Companies which use ADempiere and they allow Customer contacts and Vendor contacts to login into ADempiere via Web Interface and check status of their own documents.
For me it is fine to have both columns:

IsLoginUser and IsInternalUser

Idea of column IsInternalUser is to distinguish company own users.

**Comment by yamelsenih** [comment]
Is good +1

**Comment by yamelsenih** [comment]
The columns to be added: 
- **IsLoginUser**: Identify if a user is for login or is only a contact
- **IsInternalUser**: Is a internal user or a external

**Comment by adaxa-steven** [comment]
another option is to add a virtual column for "Has Role"
(CASE WHEN (SELECT count(*) FROM AD_User_Roles ur WHERE ur.AD_User_ID=AD_User.AD_User_ID AND ur.IsActive='Y') > 0 THEN 'Y' ELSE 'N' END) 

also we add "IsWebstoreUser"?  when two users have same name (etc) only one will be recognised for webstore login... we had to add this after a problem on a customer webstore.

**Comment by yamelsenih** [comment]
Hi @adaxa-steven 

> also we add "IsWebstoreUser"? 

I will add it.

> when two users have same name (etc) only one will be recognised for webstore login... we had to add this after a problem on a customer webstore.

With it change the username is just a personal info, the login user is the **Value** column

**Comment by adaxa-steven** [comment]
"the login user is the Value column" .... except in the standard webstore where the login is on email and as we can not make email unique then we have to identify which of two ad_user records with same email address to use when someone uses that email to login to the webstore.  Code for this will be on SF.

**Comment by yamelsenih** [comment]
> "the login user is the Value column" .... except in the standard webstore where the login is on email and as we can not make email unique then we have to identify which of two ad_user records with same email address to use when someone uses that email to login to the webstore. Code for this will be on SF.

The the webStore can make login with email and it can set on Value column for login.

**Comment by yamelsenih** [comment]
Hi @adaxa-steven i propose it:

- Create **IsWebstoreUser**.
- When **IsWebstoreUser** is flagged then the mail is setted on Value column.
- The search for user is with **IsWebstoreUser** and Value (email)

**Comment by adaxa-steven** [comment]
Not sure if change is required other than webstore login checks if more than one instance of an email address and if so then use the one with the tick.
At the moment if the same user name and password exists in two clients you can rhen choose which client to log into.. Will this still be allowed?

**Comment by yamelsenih** [comment]
I see it and already exist a unique index for email on **AD_User** named **AD_User_EMail**
<pre>
CREATE INDEX AD_User_EMail ON AD_User USING btree (email COLLATE pg_catalog."default");
</pre>

**Comment by yamelsenih** [comment]
I add the chage described previously.
@trifonnt @adaxa-steven please test it and tell me for any observation.

Best Regard

**Comment by yamelsenih** [comment]
The value is not changed when it have a "u" char.
