### ISSUE TITLE
Product Info form in ZK has always the first entry selected

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere#404]
When calling the Product info in ZK, the first entry is always selected.
This is not a big issue if it is called just for information, but it can be a nuisance if it is called within an orderline, invoiceline etc. 

In these cases, the user will have to deselect the first record always before selecting the correct ones.

**Comment by yamelsenih** [comment]
Hi @marcalwestf it issue already create in ADempiere own #306
