### ISSUE TITLE
Wrong Syntax of Delete query in GenerateCostDetail.java

### ISSUE THREAD

**Issue by Mbilalilyas** [adempiere/adempiere#405]
![image](https://cloud.githubusercontent.com/assets/10596601/15462585/249c2a48-20dd-11e6-83bd-89d54fdf635c.png)

on the line 133 of GenerateCostDetail.java the syntax of delete query is wrong which is 
        sqlDelete = new StringBuffer("DELETE M_CostDetail WHERE ");
It should be 
        sqlDelete = new StringBuffer("DELETE from M_CostDetail WHERE ");

**Comment by yamelsenih** [comment]
Hi @Mbilalilyas please test it.

Best Regards

**Comment by e-Evolution** [comment]
Hi apparently Oracle not support DELETE Tabla , in postgresql no is problem but Oracle should be DELETE FROM tabla

kind regards
