### ISSUE TITLE
Add new button to allow create an allocation from payment window

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#406]
The new enhancement is add the allocation button in payment window for any payment with document status complete and allows create an allocation directly of payment allocation window , so the context information (payment , business partner , amount ) can be setting for allocation window and processing a allocation on flight.

**Comment by trifonnt** [comment]
This sounds good to me.
+1

**Comment by yamelsenih** [comment]
This already exists for current version
![Current ogv](https://user-images.githubusercontent.com/2333092/58442854-1f5e6e00-80bc-11e9-83d0-67a38c9ce035.gif)
