### ISSUE TITLE
Enhance visualization of allocation payment window

### ISSUE THREAD

**Issue by jdaison** [adempiere/adempiere#407]
In payment allocation, Date and Automatic Write-Off are located in the top area with filter options: Business partner, organization, currency, multi-currency.

Should be located in bottom area because are parameters.

Make fixed width to parameters with 100%

Change label text Date by Allocation Date

See changes in red ellipse

**Before**
![image](https://cloud.githubusercontent.com/assets/6097506/15518136/f5679584-21c0-11e6-93ca-d174b62733fe.png)

**after**

![image](https://cloud.githubusercontent.com/assets/6097506/15518148/02f0795a-21c1-11e6-904b-397e0f87030c.png)

**Comment by e-Evolution** [comment]
I think that  is nice improve please we need implement in swing too, when you have request poll send me to include

**Comment by yamelsenih** [comment]
Hi @jdaison it is nice to have i agree with it change, also is good if the process button is changed by standard ADempiere buttons like are the SB or process.

**Comment by adaxa-steven** [comment]
Hi, 
If work is being done on this form you may want to add in the following changes that have been contributed
![image](https://cloud.githubusercontent.com/assets/15791084/16970312/75f64af0-4e5e-11e6-8c24-25929213aa86.png)

**Comment by yamelsenih** [comment]
Hi @adaxa-steven  can you make a pull request with it change?

Thank you

**Comment by yamelsenih** [comment]
Hi @jdaison thank you for it observation, @adaxa-steven thank you for your contribution, i make something changes for standard field:

- For **AP/AR** field i change it by a column **APAR** of table **T_InvoiceGL**.
- Add translation for **Org** column.
- Add translation for **AP/AR** column.
- Add swing support.
- Add right align for difference field.
- Add center align for **Multi-Currency** field.

The instance code is here:
<pre>
		//	APAR
		AD_Column_ID = 14082;    //  T_InvoiceGL.APAR
		MLookup lookupAPAR = MLookupFactory.get (Env.getCtx(), getWindowNo(), 0, AD_Column_ID, DisplayType.List);
		aparPick = new VLookup("APAR", true, false, true, lookupAPAR);
		aparPick.setValue(APAR_A);
		aparPick.addVetoableChangeListener(this);
</pre>
See the new changes on the follow images:
For ZK: ![issue34](https://cloud.githubusercontent.com/assets/2333092/19369936/ae01e07a-9176-11e6-92a3-d382c837a461.png)
For Swing: 
![issue35](https://cloud.githubusercontent.com/assets/2333092/19370024/18634eb8-9177-11e6-8ecb-63f620741e3a.png)

**Comment by marcalwestf** [comment]
Tested the form in swing. 
Buttons are ADempiere-like, filters are displayed and work OK, grid displays new columns, description is taken into allocation. 
The rest of the functionality works as hitherto.

**Comment by jdaison** [comment]
@e-Evolution @yamelsenih @adaxa-steven tested, now is better, thanks!
