### ISSUE TITLE
No way to create a multi selection window like in Sales Order -> Order line -> Product selection

### ISSUE THREAD

**Issue by ishanuda** [adempiere/adempiere#408]
Hi, 

Like in the picture there is no way to create a custom multiple record selection window like product selecting in `Sales Order -> Order Line -> Product.`

![multi-select](https://cloud.githubusercontent.com/assets/8893919/15586241/efe43248-23a0-11e6-92fe-aaee8c21d8e7.jpg)

Wish if there is a feature to create this kind of window, would be really helpful.

**Comment by e-Evolution** [comment]
Hi @ishanuda this window is a form programing with code sot that is very complex and have a lot of component. if the selection is to execute an task under a selection then you can use a smart browser link to process in the process you can write the logic that need to proceed the selection record here you can see an example to how implement.

kind regards

**Comment by yamelsenih** [comment]
Hi @ishanuda it issue is duplicated in #306 the tracker for it will be in the #306
