### ISSUE TITLE
System has no proper Subscription Management System

### ISSUE THREAD

**Issue by ishanuda** [adempiere/adempiere#411]
Hi,

I have seen `Subscription Type` and a `Subscription` window in the system.

But it has no capability of creating a subscription for `products`, `multiple products as a bundle by adding particular products` or as a `master bundle by adding bundles which is created using particular products` and create an order and an invoice for the created subscription.

**Comment by mckayERP** [comment]
See https://sourceforge.net/p/adempiere/discussion/611163/thread/1b7a50e6/
http://wiki.adempiere.net/index.php/Metas_Subscription_Module
