### ISSUE TITLE
NPE at MMail.parse(String text) when "text" variable is null

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere#415]
When the text to be parsed contains "funny" characters like 
St├ö├Â┬úÔö£├é├ö├Â┬úÔö£├®├ö├Â┬╝Ôö£ÔòæÔö£├ÂÔö£├éÔ
the method MMail.parse(String text) is called with  "text"==null, and a NPE is generated:

NullPointerException
      at org.compiere.model.MMailText.parse(MMailText.java:154)
      at org.compiere.model.MMailText.getMailText(MMailText.java:111)

The reason: the first line of the code is
if (text.indexOf('@') == -1)
which delivers the NPE immediately.

It shoud be avoided with something like
if (text == null) 
      return "";
if (text.indexOf('@') == -1) 
:
:

**Comment by yamelsenih** [comment]
Hi @marcalwesf is good add a validation for null values in this class

**Comment by marcalwestf** [comment]
can somebody test it to be closed?

**Comment by marcalwestf** [comment]
solved. closing the issue
