### ISSUE TITLE
Not existent column in query DBEngine_Postgresql.sqlMetadata_triggerTables()

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere#418]
When running the Migration tool,  the method DBEngine_Postgresql.sqlMetadata_triggerTables() is called. 
Here a sql is prepared . The sql is a select command, which contains "SELECT ....condition_timing AS TRIG_TYPE..FROM information_schema.triggers ...".
The point is, condition_timing does not exist in the table "information_schema.triggers" , and it yields an error.
The Postgres API changed since PG 9.1 (https://www.postgresql.org/docs/9.5/static/infoschema-triggers.html), and the column is now "action_timing".

**Comment by yamelsenih** [comment]
This was resolved
