### ISSUE TITLE
[Bug Report] Badly formatted end of line in files

### ISSUE THREAD

**Issue by rcapecce** [adempiere/adempiere#4188]
## Bug report

In the ADempiere source, files with line ending CRLF and LF coexist, however, there is a limited list of files that have this line break mixed in, there are some lines whose eol is CFLF while others are LF

#### Steps to reproduce

An example is the MDunningRunLine class.

1. In VisualStudio Code of Github (enter here https://github.dev/adempiere/adempiere/tree/hotfix/3.9.4.001) open the MDunningRunLilne class
2. Check the eol character 
![image](https://github.com/adempiere/adempiere/assets/14218144/e77a274c-16b0-4ffb-80c1-5ebca848013c)
3. Open the same class in IntelliJ (the issue is tested in this ide)
![image](https://github.com/adempiere/adempiere/assets/14218144/8613aff7-a7f6-434b-b912-6f12984c9ef7)
4. So far everything is formated with LF eol
5. Make a change an compare for commit
6. Here IntelliJ show the change in the file but it also show the eol character
![image](https://github.com/adempiere/adempiere/assets/14218144/b882c37f-e9a5-46db-8236-dc868ae00adc)

#### Investigation

Is detected that in the ADempiere source there are 48 java files that have part of their lines with eol CRLF and others with eol LF.

This can be detected with the following command

`git ls-files --eol | grep java | grep mixed`

@e-Evolution you check this eol difference with the command `vim` too

#### Result

This causes an inconsistence, such as GitHub shows a different eol than the one seen from Intellij in the same file.

It also causes that when committing a single change, IntelliJ normalizes the incorrect lines and sends several changes to GitHub to normalize the eols.

#### List of java files with mixed eol

> i/mixed w/mixed attr/                   base/src/org/adempiere/model/ExportModelValidator.java
> i/mixed w/mixed attr/                   base/src/org/adempiere/pipo/AbstractElementHandler.java
> i/mixed w/mixed attr/                   base/src/org/compiere/acct/Doc_Order.java
> i/mixed w/mixed attr/                   base/src/org/compiere/db/DBRes_hu.java
> i/mixed w/mixed attr/                   base/src/org/compiere/model/CalloutInvoice.java
> i/mixed w/mixed attr/                   base/src/org/compiere/model/CalloutOrder.java
> i/mixed w/mixed attr/                   base/src/org/compiere/model/MAcctSchemaGL.java
> i/mixed w/mixed attr/                   base/src/org/compiere/model/MCash.java
> i/mixed w/mixed attr/                   base/src/org/compiere/model/MChat.java
> i/mixed w/mixed attr/                   base/src/org/compiere/model/MChatEntry.java
> i/mixed w/mixed attr/                   base/src/org/compiere/model/MChatType.java
> i/mixed w/mixed attr/                   base/src/org/compiere/model/MContainer.java
> i/mixed w/mixed attr/                   base/src/org/compiere/model/MContainerElement.java
> i/mixed w/mixed attr/                   base/src/org/compiere/model/MDunningLevel.java
> i/mixed w/lf    attr/                   base/src/org/compiere/model/MDunningRunLine.java
> i/mixed w/mixed attr/                   base/src/org/compiere/model/MInterestArea.java
> i/mixed w/mixed attr/                   base/src/org/compiere/model/MNewsItem.java
> i/mixed w/mixed attr/                   base/src/org/compiere/model/MPaymentValidate.java
> i/mixed w/mixed attr/                   base/src/org/compiere/model/MWebProjectDomain.java
> i/mixed w/mixed attr/                   base/src/org/compiere/model/TranslationTable.java
> i/mixed w/mixed attr/                   base/src/org/compiere/process/BankStatementPayment.java
> i/mixed w/mixed attr/                   base/src/org/compiere/process/PaySelectionCreateFrom.java
> i/mixed w/mixed attr/                   base/src/org/compiere/util/AmtInWords_IN.java
> i/mixed w/mixed attr/                   base/src/org/compiere/util/AmtInWords_SR.java
> i/mixed w/mixed attr/                   base/src/org/compiere/util/IniRes_hu.java
> i/mixed w/mixed attr/                   base/src/org/compiere/util/Msg.java
> i/mixed w/mixed attr/                   base/test/src/org/compiere/model/IT_MBPartner.java
> i/mixed w/mixed attr/                   client/src/org/compiere/plaf/PlafRes_hu.java
> i/mixed w/mixed attr/                   client/src/org/spin/apps/form/BankStatementMatchController.java
> i/mixed w/mixed attr/                   serverRoot/src/main/server/org/compiere/ldap/LdapConnectionHandler.java
> i/mixed w/mixed attr/                   serverRoot/src/main/server/org/compiere/ldap/LdapMessage.java
> i/mixed w/mixed attr/                   webCM/src/main/servlet/org/compiere/cm/AdRedirector.java
> i/mixed w/mixed attr/                   webCM/src/main/servlet/org/compiere/cm/Broadcast.java
> i/mixed w/mixed attr/                   webCM/src/main/servlet/org/compiere/cm/Community.java
> i/mixed w/mixed attr/                   webCM/src/main/servlet/org/compiere/cm/Extend.java
> i/mixed w/mixed attr/                   webCM/src/main/servlet/org/compiere/cm/HttpServletCM.java
> i/mixed w/mixed attr/                   webCM/src/main/servlet/org/compiere/cm/MediaBroadcast.java
> i/mixed w/mixed attr/                   webCM/src/main/servlet/org/compiere/cm/RequestServlet.java
> i/mixed w/mixed attr/                   webCM/src/main/servlet/org/compiere/cm/StageBroadcast.java
> i/mixed w/mixed attr/                   webCM/src/main/servlet/org/compiere/cm/XMLBroadcast.java
> i/mixed w/mixed attr/                   webCM/src/main/servlet/org/compiere/cm/cache/CO.java
> i/mixed w/mixed attr/                   webCM/src/main/servlet/org/compiere/cm/cache/Chat.java
> i/mixed w/mixed attr/                   webCM/src/main/servlet/org/compiere/cm/cache/Container.java
> i/mixed w/mixed attr/                   webCM/src/main/servlet/org/compiere/cm/cache/ContainerElement.java
> i/mixed w/mixed attr/                   webCM/src/main/servlet/org/compiere/cm/cache/ContainerTree.java
> i/mixed w/mixed attr/                   webCM/src/main/servlet/org/compiere/cm/cache/Domain.java
> i/mixed w/mixed attr/                   webCM/src/main/servlet/org/compiere/cm/cache/Service.java
> i/mixed w/mixed attr/                   webCM/src/main/servlet/org/compiere/cm/request/Request.java

**Comment by e-Evolution** [comment]
@rcapecce I see that there is no way to avoid this in Intellij

Unfortunately, if you have mixed line breaks in the same file, IntelliJ IDEA might format the file based on the selected settings. In that case, you may need to normalize line breaks in the file before making significant changes to avoid unexpected reformats.

We should normalize the code to one, What do you think @yamelsenih ?

**Comment by yamelsenih** [comment]
Hello, @e-Evolution @rcapecce I wrote a issue with some like this. Maybe can be useful: https://github.com/adempiere/adempiere/issues/2135

Please try it

**Comment by rcapecce** [comment]
Hi @yamelsenih
I understand that in your case (Like your example https://github.com/adempiere/adempiere/commit/ff65981e40cda20780cdb4c327c8666ca2bc39f9) you had it completely in a type of end of line and by IDE configuration it was forced to the default one IDE.
intellij works well with files that are completely encoded with one eol or the other.
The problem discussed here is because in the same file there are 2 line endings and IntelliJ is forcing the default one to be used in this case, that is what I understand.

**Comment by rcapecce** [comment]
When Intellij finds both line endings in the same file, in this case it would use a single eol normalizing the file.

**Comment by yamelsenih** [comment]
Ummm, can you test with other editor?

**Comment by rcapecce** [comment]
@nsarlabos edit this with `vim` and commit in terminal please

**Comment by nsarlabos** [comment]
@rcapecce I made the changes with VIM and was able to generate pull request #4189, it indicates the difference in the only place where it was modified, without presenting line break problems.
