### ISSUE TITLE
error in windows from setup employee

### ISSUE THREAD

**Issue by wdtz** [adempiere/adempiere#419]
![monovista](https://cloud.githubusercontent.com/assets/9578152/15867196/e2fe6256-2cab-11e6-8a12-fd859f17c07e.png)
![multivista](https://cloud.githubusercontent.com/assets/9578152/15867198/e9c72f50-2cab-11e6-8553-bf47f636bdb7.png)

In the windows of employee setup (degree, shift work ...) to change the view to toggle grid does not show records even though there are.(view image)

**Comment by yamelsenih** [comment]
Hi @wdtz it is worked now. Test it
![issue14](https://cloud.githubusercontent.com/assets/2333092/24228177/02d22bd2-0f49-11e7-941b-7878fc63ddd0.png)
![issue15](https://cloud.githubusercontent.com/assets/2333092/24228176/02cd425c-0f49-11e7-88c9-a189b7ff1bb8.png)
