### ISSUE TITLE
[Bug Report] NPE at Run Report

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#4245]
## Bug report
When a report is generated from the ZK and the company does not have an associated logo, it gives an NPE type error.

```Java
============> zkoss.handleError:1130: >>java.lang.NullPointerException
>> at org.compiere.print.layout.LayoutEngine.createStandardHeaderFooter(LayoutEngine.java:958)
>> at org.compiere.print.layout.LayoutEngine.layout(LayoutEngine.java:444)
>> at org.compiere.print.layout.LayoutEngine.<init>(LayoutEngine.java:134)
>> at org.compiere.print.ReportEngine.layout(ReportEngine.java:320)
>> at org.compiere.print.ReportEngine.getLayout(ReportEngine.java:330)
>> at org.compiere.print.ReportEngine.getCtx(ReportEngine.java:367)
```

#### Steps to play
1. Go to the **Company** window
2. in the **Company Information** tab remove the reports logo
3. Reset cache
4. Generate a detail type report

#### Screenshot or Gif
![error_in_ddh](https://github.com/erpcya/adempiere/assets/2333092/736e060d-032f-4b94-a286-cd6e9172e93f)
![Screenshot_20230720_142541](https://github.com/erpcya/adempiere/assets/2333092/0297cb86-584f-4b12-a2ff-9739208c5a42)

#### Expected behavior
If there is no logo in the company, you should simply validate and not show it

#### Other relevant information
-Your OS:
-Java version:
- ADempiere version:
- Browser Version [e.g. 22]
-DB Provider:
-DB version:

**Comment by yamelsenih** [comment]
Already resolved here

**Comment by EdwinBetanc0urt** [comment]
is directly related to https://github.com/adempiere/adempiere/issues/3884
