### ISSUE TITLE
[Bug Report] The Financial Statement Report shows the credits in the beginning balance line incorrectly

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#4296]
## Bug report
The Financial Statement Report shows the credits in the beginning balance line incorrectly

#### Steps to reproduce
1.- Execute the Statement of Accounts Report

![image](https://github.com/adempiere/adempiere/assets/786968/01be15e2-34e4-4cc4-8e65-8beebc2f59df)

2.- The Report will show credit column in negative and balance wrong
3.- if a Account Type is setting , I got the SQL syntaxis error 

#### Expected behavior
The functionality should work as before

#### Other relevant information
- Your OS: macOS
- Java version: 11
- ADempiere version: 3.9.4.001
- DB Provider: PG
- DB version: 16

#### Additional context
The problem was introducing  #2050 by @e-Evolution

**Comment by carlosaparadam** [comment]
Hi @e-Evolution Victor, this pull request only fix an sql error for ambiguous column and move the subqueries that were in the select to the from to improve the query, the error has been introduced here https://github.com/adempiere/adempiere/pull/2050 which is where you start using the **AcctBalance** function that works according to the nature of the account

**Comment by e-Evolution** [comment]
> Hi @e-Evolution Victor, this pull request only fix an sql error for ambiguous column and move the subqueries that were in the select to the from to improve the query, the error has been introduced here #2050 which is where you start using the **AcctBalance** function that works according to the nature of the account

Hi @carlosaparadam Carlos , @SusanneCalderon Susanne , @marcalwestf Mario!

Although the company id was added which is correct and the approach to optimizing the query is appropriate, the problem is that the SQL that calculates the credits and the final balance is incorrect, here you not only changed the query but the logic. on the other hand, when adding this query, the accouttype remained as an ambiguous column.

What we have to improve are our tests and these have to be more exhaustive and not so simple, to cover the majority of cases, here I send the correction https://github.com/adempiere/adempiere/pull/4298

kind regards
Victor

**Comment by e-Evolution** [comment]
Exemple the problem after to merge #2951

![image](https://github.com/adempiere/adempiere/assets/786968/5ee20932-0027-4575-9aa6-54add9dce03c)

Here the credit is negative and balance is incorrect.

**Comment by carlosaparadam** [comment]
Hello @e-Evolution Victor, I understand what you are saying, however, I extend the invitation that you make to us here since the balance logic has been bad since the commits.


```
commit c704d0e16d933367f2e57ecd91d48bc0c74e755a
Author: eEvolution author Victor Perez <victor.perez@e-evolution.com> 2019-03-01 21:17:21
Committer: eEvolution author Victor Perez <victor.perez@e-evolution.com> 2019-03-01 21:17:21
Parent: 1590e7d54fb98459d73e573d9f45e03ce5af2604 (#2049 Error Statement Account when send the account parameters https://github.com/adempiere/adempiere/issues/2049)
Child: f34840c775b1c3bdfd6279ca1606f9d09f809263 (Fix ambiguous column in Financial Statement report query and optimize query for previous balance)

commit 1590e7d54fb98459d73e573d9f45e03ce5af2604
Author: eEvolution author Victor Perez <victor.perez@e-evolution.com> 2018-10-03 16:54:52
Committer: eEvolution author Victor Perez <victor.perez@e-evolution.com> 2018-10-03 16:55:57
Parent: 54c57517c9320495541b6687426b4ae40620bdc8 (adempiere: #1669 StatementOfaccountincludeaccount_ID in the report)
Child: c704d0e16d933367f2e57ecd91d48bc0c74e755a (#2409 Error for balance for Statement Account current show incorrect Account Sign https://github.com/adempiere/adempiere/issues/2409)
```

![Screenshot_20240313_152135](https://github.com/adempiere/adempiere/assets/1847863/538162a2-a657-4db5-9296-95b41c1aba37)
![Screenshot_20240313_154003](https://github.com/adempiere/adempiere/assets/1847863/7f3ff6ca-7bd0-45eb-9d12-591e9972d6f1)

In fact, if you just revert the commit with my changes, the report presents the same problem that you report plus the problem that I reported.

**Comment by carlosaparadam** [comment]
I will review your changes.

Greetings

**Comment by carlosaparadam** [comment]
## I test with an asset account and i see this ok 
![Asset_Parameters](https://github.com/adempiere/adempiere/assets/1847863/b3805923-5a90-4ece-9376-42ce6eeaac15)
![Asset_Report](https://github.com/adempiere/adempiere/assets/1847863/a1e4c626-457d-4e89-9ed5-bf781a26d7b1)

## But with an liability account the credit see in negative
![Liability_Parameters](https://github.com/adempiere/adempiere/assets/1847863/89a47519-3986-44f4-92cb-50fa6db32c31)
![Liability_Report](https://github.com/adempiere/adempiere/assets/1847863/3c58f101-88fb-4654-bc51-2d690cc4d594)

I think so the `AcctBalance` function in Debit and Credit select is unnecessary

**Comment by e-Evolution** [comment]
@carlosaparadam , the problem is here : 

Your code solvente the balance here for balance  : 

![image](https://github.com/adempiere/adempiere/assets/786968/b552112d-1006-4b0a-9602-af2bf256c5da)

But change the logic to credit here 

![image](https://github.com/adempiere/adempiere/assets/786968/078f2ed2-b50b-4c96-8410-8fc056a0ef2c)

If we analyze the balance function, when we pass the credits as the second parameter, the function returns a negative value, which causes the credits to be displayed incorrectly.

Finally I discovered how you have it that when you pass debits and credits the balance is calculated correctly.

  Finally the code that was left was:

```
.append("SUM(AcctBalance(Account_ID, AmtAcctDr, 0)) AmtAcctDr,")
.append("SUM(AcctBalance(fa.Account_ID, AmtAcctCr, 0)) AmtAcctCr,")
.append("SUM(AcctBalance(fa.Account_ID, fa.AmtAcctDr, fa.AmtAcctCr)) Balance, ")
```

**Comment by carlosaparadam** [comment]
Hi @e-Evolution Victor, the credit logic comes from this commit
![image](https://github.com/adempiere/adempiere/assets/1847863/f7348d56-3203-49e6-9d7e-65407462a60a)

**Comment by e-Evolution** [comment]
Hi @carlosaparadam Carlos , @SusanneCalderon Susanne , @marcalwestf Mario.

Reviewing the history in detail @carlosaparadam, you are correct, the error was introduced long before your change. So I apologize for jumping to a conclusion.

Edit the comment to reflect the facts.

When implementing your suggestion it seems to work for all account types Asset, Liability , Capital, Income, Expense.

Send one last change, can you try please?
 
kind regards
Victor

**Comment by carlosaparadam** [comment]
Hi @e-Evolution  Victor, don't worry i am testing with your changes and see this detail.

##  With asset account types don't have problems

### Asset Account January 2021
- **Begin Balance: 0**
- **End Balance: 0**
---
![Asset_202101](https://github.com/adempiere/adempiere/assets/1847863/81806e92-5aa2-4c7b-bf76-1d73dfbc3f11)
### Asset Account July 2021
- **Begin Balance: 0**
- **End Balance: 161.12**
---
![Asset_202107](https://github.com/adempiere/adempiere/assets/1847863/6ac7711c-66bf-43fb-9a1e-1603b077af6d)
### Asset Account January 2022
- **Begin Balance: 161.12**
- **End Balance: 446.95**
---
![Asset_202201](https://github.com/adempiere/adempiere/assets/1847863/b5d4570d-bf45-463c-a1ed-af40e25caf35)

## But with liability account types the end balance don't correspond with the beginning balance of the next period.

### Liability Account January 2021
- **Begin Balance: 0**
- **End Balance: -200**
---
![Liability_202101](https://github.com/adempiere/adempiere/assets/1847863/4d0c0322-06a3-40f4-9d2e-fb9f744b236c)
### Liability Account August 2021
- **Begin Balance: 200**
- **End Balance: -360**
---
![Liability_202108](https://github.com/adempiere/adempiere/assets/1847863/d6360ab4-2925-437c-b2fd-cd71cbed6cb2)
### Liability Account December 2021
- **Begin Balance: 560**
- **End Balance: -3,657.5**
---
![Liability_202112](https://github.com/adempiere/adempiere/assets/1847863/f0b3df3b-b5f2-4067-8601-96eff4cf17a7)

I think so if the `AcctBalance` funcion has been applied to balance query also must be applied to the line query for prevent this incongruity.

Grettings

**Comment by carlosaparadam** [comment]
Another option maybe don't use the `AcctBalance` function as it was here https://github.com/adempiere/adempiere/commit/54c57517c9320495541b6687426b4ae40620bdc8

**Comment by e-Evolution** [comment]
> Another option maybe don't use the `AcctBalance` function as it was here [54c5751](https://github.com/adempiere/adempiere/commit/54c57517c9320495541b6687426b4ae40620bdc8)

In fact, this is how it was originally, accountants in general do not like to see negative signs in the balance sheets, they generally understand that the accounts have a nature. If we are talking about a liability, its nature is creditor and the balance is shown positively.

But in generating it is customary how this works in Venezuela, in Mexico they prefer to see positive values, I suppose that in Europe and the USA they are more practical and do not care

**Comment by e-Evolution** [comment]
@carlosaparadam Carlos here the result : 

![image](https://github.com/adempiere/adempiere/assets/786968/24b4976c-1d0b-4332-98ae-f6338d016772)

![image](https://github.com/adempiere/adempiere/assets/786968/5ec20717-2cdf-43d6-96a8-35542c928669)

![image](https://github.com/adempiere/adempiere/assets/786968/f02ba6f8-38a7-4520-8bc3-a4904a4d8b4f)


![image](https://github.com/adempiere/adempiere/assets/786968/f7a96154-34e9-4473-907a-1f35888ecb56)

[Statement of Accounts.pdf](https://github.com/adempiere/adempiere/files/14620735/Statement.of.Accounts.pdf)

I'm thinking that it may be very useful to calculate the beginning balance by period that would show a useful report when you take them out for all accounts and a calendar year.


What do you think ?

**Comment by carlosaparadam** [comment]
Hi @e-Evolution Victor, i will test again, you say show balance by period?  if so, how would the report work if I only want to see a range of dates? i don't understand your proposal

**Comment by carlosaparadam** [comment]
I had test again and it's ok

### Liability Account January 2021
- **Begin Balance: 0**
- **End Balance: 200**
---
![Liability_202101](https://github.com/adempiere/adempiere/assets/1847863/0a21f528-075c-4f98-aff8-7aa149009397)
### Liability Account August 2021
- **Begin Balance: 200**
- **End Balance: 560**
---
![Liability_202108](https://github.com/adempiere/adempiere/assets/1847863/63bb7f01-40f4-437b-9668-d935888a6860)
### Liability Account December 2021
- **Begin Balance: 560**
- **End Balance: 4,217.50**
---

![Liability_202112](https://github.com/adempiere/adempiere/assets/1847863/f5fa6a6e-645f-4ae4-a38f-4a208f4dd921)

**Comment by e-Evolution** [comment]
> Hi @e-Evolution Victor, i will test again, you say show balance by period? if so, how would the report work if I only want to see a range of dates? i don't understand your proposal

The proposal is get  Beginning Balance by C_Period_ID, so if you take from 01/01/2024 to 12/31/2024

The system would show the Beginning balance with which each period starts from 1 to 12.

January  Beginning Balance
- Movements
February Beginning Balance
- Movements
March Beginning Balance
- Movements
April Beginning Balance
- Movements
etc

But I don't know, it was just an idea.

**Comment by e-Evolution** [comment]
May be that this is Cover by this Report 

![image](https://github.com/adempiere/adempiere/assets/786968/30b2f129-7ca3-4339-a6f4-632456cb067b)

I need validase

**Comment by carlosaparadam** [comment]
Hi @e-Evolution Victor, i review your changes and see this:

- [x] Previous Balance for Asset Accounts **Ok**
- [x] End Balance for Asset Accounts **Ok**
- [x] Previous Balance for Liability Accounts **Ok**
- [x] End Balance for Liability Accounts **Ok**

I think so this report it's Ok with your changes any other functionality could be another report
