### ISSUE TITLE
Report groups in summary do not handle single values well

### ISSUE THREAD

**Issue by mckayERP** [adempiere/adempiere#431]
I have a report - see attached - that has three group levels.  The last group, "Funding Source", has, in this case, only one value and null.   I would expect to see this single value shown for every occurrence of the first two groups but it only shows when the value changes to null.  This makes the report confusing and the sums don't make sense.

![report_error](https://cloud.githubusercontent.com/assets/5507616/16117663/2d8898d6-33a1-11e6-84c9-193b5005eab7.jpg)

**Comment by yamelsenih** [comment]
Hey @mckayERP great catch, I was the same error but never debug it for know cause
I will to test it
