### ISSUE TITLE
The process button in Payment Allocation window is enabled by default.

### ISSUE THREAD

**Issue by mckayERP** [adempiere/adempiere#437]
This allows users to process single invoices or payments which creates a suspense balance.

The button should be disabled by default.

The routine that enables or disables the button is only called when the Charge combobox has a selection.  Otherwise, it is enabled all the time.

**Comment by liosc** [comment]
When the "Payment allocation" window opens the button is enabled but as soon as I select a document it becomes disabled until I balance the amount or I select a charge. But in case I left the amount unbalanced and I selected a charge, the button keeps stay enabled even if I clean the charge selection. Pushing the button It creates a balanced writing (It evidently uses a default account) but I think the behavior should be coherent. If there is an unbalanced selection and no charge is selected the button should be always enabled or always disabled.

**Comment by yamelsenih** [comment]
This already exists
