### ISSUE TITLE
Critical Error when issuing a material to project

### ISSUE THREAD

**Issue by iscapnet** [adempiere/adempiere#443]
A critical error found on Project Management module in Adempiere's recent version 3.8.0, here are the steps to reproduce in Garden World.

1. Log in as User Admin
2. Create a new project "Make a Robot" and set it as Work order
3. Goto project phase tab and enter a planned material of rake-metal on line 10.
4. Add up some inventory of rake-metal in order to have enough QOH
5. Go to issue to project process and select the project "Make a Robot", also a project line for rake-metal product and a locator.

After you hit the Start button the process is interrupted after the following message

-----------> MTransaction.saveFinish: afterSave [74]
java.lang.NullPointerException
	at org.adempiere.engine.CostEngine.createCostDetail(CostEngine.java:238)
	at org.compiere.model.MTransaction.afterSave(MTransaction.java:237)
	at org.compiere.model.PO.saveFinish(PO.java:2239)
	at org.compiere.model.PO.saveNew(PO.java:2812)
	at org.compiere.model.PO.save(PO.java:2123)
	at org.compiere.model.PO.save(PO.java:2312)
	at org.compiere.model.MProjectIssue.process(MProjectIssue.java:170)
	at org.compiere.process.ProjectIssue.issueProjectLine(ProjectIssue.java:291)
	at org.compiere.process.ProjectIssue.doIt(ProjectIssue.java:126)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:147)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:105)

===========> MProjectIssue.process: Transaction not saved [74]

**Comment by e-Evolution** [comment]
Hi Enrique @iscapnet , please test now should be work 

Thank a lot to report.

kind regards

**Comment by iscapnet** [comment]
Hi **Victor**, thanks for looking into this.. I found another bug while testing your fix.. it occurs when the period is closed and ADempiere tries to create the new costing record for the project issue.. this shouldn't throw an error if the period is closed because it interrupts the record creation process and it would be difficult to fix backwards.

> -----------> MCostDetail.save: beforeSave - MCostDetail[0,SeqNo=50,AD_Org_ID=1000001,C_AcctSchema_ID=1000001,M_CostType_ID=1000001,M_CostElement_ID=1000003,M_Transaction_ID=1005965,DateAcct=null,C_ProjectIssue_ID=1000110,Cost =49,Cost Amt=49,Qty=-1,CumulatedQty =2,Qty Onhand =1,Current Qty =0,Cumulated Amt =294,Cumulated Amt LL =0,Current Price =49,Current Proce TL =0] [42]
> java.lang.NullPointerException
> 	at org.compiere.util.DB.prepareStatement(DB.java:732)
> 	at org.compiere.util.DB.getSQLValueTSEx(DB.java:1518)
> 	at org.compiere.model.MCostDetail.setDateAcct(MCostDetail.java:1483)
> 	at org.compiere.model.MCostDetail.beforeSave(MCostDetail.java:1546)
> 	at org.compiere.model.PO.save(PO.java:2062)
> 	at org.compiere.model.PO.saveEx(PO.java:2207)
> 	at org.adempiere.engine.StandardCostingMethod.updateAmountCost(StandardCostingMethod.java:378)
> 	at org.adempiere.engine.StandardCostingMethod.createCostDetail(StandardCostingMethod.java:222)
> 	at org.adempiere.engine.StandardCostingMethod.process(StandardCostingMethod.java:234)
> 	at org.adempiere.engine.CostEngine.createCostDetail(CostEngine.java:432)
> 	at org.adempiere.engine.CostEngine.createCostDetail(CostEngine.java:256)
> 	at org.compiere.model.MTransaction.afterSave(MTransaction.java:237)
> 	at org.compiere.model.PO.saveFinish(PO.java:2239)
> 	at org.compiere.model.PO.saveNew(PO.java:2812)
> 	at org.compiere.model.PO.save(PO.java:2123)
> 	at org.compiere.model.PO.save(PO.java:2312)
> 	at org.compiere.model.MProjectIssue.process(MProjectIssue.java:170)
> 	at org.compiere.process.ProjectIssue.issueMovement(ProjectIssue.java:176)
> 	at org.compiere.process.ProjectIssue.doIt(ProjectIssue.java:120)
> 	at org.compiere.process.SvrProcess.process(SvrProcess.java:147)
> 	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:105)

**Comment by marcalwestf** [comment]
issue tested and changes OK. 
+1 to be closed.
