### ISSUE TITLE
Processes for Smartbrowsers, generated with Adempiere 3.80 do not work anymore

### ISSUE THREAD

**Issue by SusanneCalderon** [adempiere/adempiere#446]
while excecuting the process defined in a smartbrowser I have the following problem:

Before 3.81 the selected rows in a smartbrowser were accessible with a query on table T_Selection.
This does not work in Adempiere 3.81, and there is not explanation how they are accessible in Adempiere 3.81.

Example: 
		String whereClause = "EXISTS (SELECT T_Selection_ID FROM T_Selection WHERE  T_Selection.AD_PInstance_ID=? " +
				" AND T_Selection.T_Selection_ID=c_orderLine.C_OrderLine_ID)";
		m_records = new Query(getCtx(), MOrderLine.Table_Name, whereClause, get_TrxName())
		.setParameters(getAD_PInstance_ID())
		.setOrderBy(orderClause.toString())
		.setClient_ID()
		.list();
This yields an empty list.

**Comment by yamelsenih** [comment]
Hi @SusanneCalderon do you have a example more specific?

The new functionality is more easy, you can use helper method from Parent class of process, for more information you can see it: [http://wiki.adempiere.net/Spin_Contribution:_FR:_Get_Parameter_in_Process](http://wiki.adempiere.net/Spin_Contribution:_FR:_Get_Parameter_in_Process)
