### ISSUE TITLE
Parameter list values not refresh when other users login in web client.

### ISSUE THREAD

**Issue by ayazbaloch** [adempiere/adempiere#46]
@e-Evolution parameter list values not refresh when other users login they see list values of first logined user, it is working properly for GUI client, i think it retrieve from the cache when i delete the cache and login to other user it shown its values accordingly. I am using Adempiere 3.7.

**Comment by ayazbaloch** [comment]
Most of the time, parameter list values are dependent on users/Role, for example in my case user1 just see the list of Region1, Region2 and user2 see the list of Region3 and Region4.
in Adempiere 3.7 MLookupFactory.java I just change the following code

String key = Env.getAD_Client_ID(ctx) + "|" + String.valueOf(AD_Reference_Value_ID);
in line 349
String key = Env.getAD_Client_ID(ctx) + "|" + String.valueOf(AD_Reference_Value_ID)+ "|"+ Env.getAD_User_ID(ctx);

**Comment by Zuhair-Hammadi** [comment]
if lookup contain translated item and you login with different language 
values will not refresh also.

**Comment by ayazbaloch** [comment]
It means cache "key" value should be composite of Client+Reference+User+Language, it is my opinion, now let us see the core team decision what they will decide.

**Comment by liosc** [comment]
Hi,
this issue has been created more than two years ago and it is still open. There are commits. Did they solve the problem? If tests are needed please specify better the business case so anyone could procede.

**Comment by yamelsenih** [comment]
Hi, any update for it?
