### ISSUE TITLE
Update context when you select a row in a SmartBrowser

### ISSUE THREAD

**Issue by SusanneCalderon** [adempiere/adempiere#460]

**Comment by SusanneCalderon** [comment]
When the filter of a Smartbrowser is executed, the values of the last row are colocated in the context. When you select a row the context should be updated.

**Comment by yamelsenih** [comment]
Hi @SusanneCalderon it is caused because when the table is loaded, it set all rows in the context, i change the behavior for that it set the context when the row is selected.

Thank you for find it.

**Comment by yamelsenih** [comment]
Hi @SusanneCalderon can you test the change?
The bug is fixed.
