### ISSUE TITLE
Remove the Posterita code, The code has no maintenance

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#467]
The technical team approval to remove Posterita,  the code has no maintenance.

**Comment by e-Evolution** [comment]
The Posterita POS was deprecated and replace for ADempiere POS

**Comment by yamelsenih** [comment]
The build and classpath has reference to old library revoved.

**Comment by e-Evolution** [comment]
@yamelsenih thank to support eclipse class path

**Comment by yamelsenih** [comment]
You are welcome
