### ISSUE TITLE
Bug with old compatibility

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#468]
Hi @e-Evolution it change don't support the old compatibility
https://github.com/adempiere/adempiere/commit/e84f38449c8234fb3c6bc105e716cd13081c59fa#diff-16351992d2dae50ebdba1962ba634974R47

If the method MBPBankAccount[] getOfBPartner (Properties ctx, int C_BPartner_ID) is used in something clients it throw a error:
<pre>
[javac] Compiling 98 source files to /opt/Development/workspace/CST-STD/build
    [javac] /workspace/CST-STD/base/org/spin/model/CST_STDModelValidator.java:399: error: incompatible types: List<MBPBankAccount> cannot be converted to MBPBankAccount[]
    [javac] 						MBPBankAccount[] bpas = MBPBankAccount.getOfBPartner(
    [javac] 						                                                    ^
</pre>

![selection_157](https://cloud.githubusercontent.com/assets/2333092/17302028/2c991480-57e8-11e6-9d4e-2fafe132e07e.png)

I think that it change must be reverted and mark the method like **@deprecated**

**Comment by e-Evolution** [comment]
The array type not should be use more , this approach not are design to funcional programing , is best approach use List, I added old method only tu support back compatibility

**Comment by yamelsenih** [comment]
yes i agree is better add best practices without broken the old code.

Best regard.

**Comment by dixon22ma** [comment]
Hi @e-Evolution it change don't support the old compatibility
[https://github.com/adempiere/adempiere/commit/e84f38449c8234fb3c6bc105e716cd13081c59fa#diff-603c29b6a3b2146bd21367f782f77e23L128](https://github.com/adempiere/adempiere/commit/e84f38449c8234fb3c6bc105e716cd13081c59fa#diff-603c29b6a3b2146bd21367f782f77e23L128)

If the method [public int exportToFile (List<MPaySelectionCheck> checks, File file, StringBuffer error);](https://github.com/adempiere/adempiere/blob/hotfix/3.8.0%23002/base/src/org/compiere/util/PaymentExport.java#L42)  is used in something clients it throw a error

![errorpaymentexport](https://cloud.githubusercontent.com/assets/2453563/17827413/7e580716-664a-11e6-9679-753360cebffc.png)

**Comment by yamelsenih** [comment]
Hi @e-Evolution, i test it and work. Thank you for it.

Best regards

**Comment by yamelsenih** [comment]
Hi @e-Evolution i add a abstract class instead of interface. please test it.

**Comment by dixon22ma** [comment]
Hi @e-Evolution it change don't support the old compatibility
e84f384#diff-603c29b6a3b2146bd21367f782f77e23L128

If the method public [List<MPaySelectionLine> getPaySelectionLines (boolean reQuery);](https://github.com/adempiere/adempiere/blob/hotfix/3.8.0%23002/base/src/org/compiere/model/MPaySelectionCheck.java#L585) is used in something clients it throw a error

![error](https://cloud.githubusercontent.com/assets/2453563/19454125/df54e142-9485-11e6-8d4a-71ac6bd0c088.png)

**Comment by yamelsenih** [comment]
Always is better add support to old compatibility, if a method is change from array to list then is better create a new method and deprecate the old method.

Best regard.
