### ISSUE TITLE
Use preferred method of converting double to BigDecimal in Matching Invoices

### ISSUE THREAD

**Issue by mckayERP** [adempiere/adempiere#476]
The Match PO-Invoice-Receipt window calculates the quantity to match as a double variable.  This is converted to a BigDecimal using the code new BigDecimal(qty).  This conversion is unpredictable and can lead to strange behaviour.  For example, 

new BigDecimal((double) 24.41) =24.410000000000000142108547152020037174224853515625

This small difference causes problems when trying to post the matched invoice as the reversal entry is found by searching for the invoice with the unpredictable quantity and it is not found, leading the accounting engine to guess that the invoice is not posted yet.

Tested on postgres.adempiere.io.  See Invoice 10000018, MR 10000516, and Match Invoice 10000001.  All the quantities match (0.1 tons of Phosphorous) but the Match Invoice can't be posted.

The java docs recommend to convert double variables to BigDecimals by using the string representation.  This conversion is exact and is performed by the static call BigDecimal.valueOf(double).  The change affects Match.java, VMatch.java and WMatch.java.

**Comment by yamelsenih** [comment]
Hi @mckayERP i think that is better if you use the precision and just BigDecimal instead Double, like the [Allocation class](https://github.com/adempiere/adempiere/blob/master/client/src/org/compiere/apps/form/Allocation.java#L432) it allow handle big numbers.

Best regard

**Comment by yamelsenih** [comment]
Hi, any update for it?

**Comment by carlosaparadam** [comment]
solved on pull request #2931
