### ISSUE TITLE
Bad constraint for table

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#482]
Find the tables in ADempiere i look that exists many tables with bad references or contraints, it tables are:

- HR_ShiftGroup
- C_Country
- HR_JobOpening
- HR_SalaryStructure
- AD_WF_Process

The follow contraint exist in the current DB:
<pre>
ALTER TABLE hr_shiftgroup ADD CONSTRAINT hrshiftgroup_hrshiftgroup FOREIGN KEY (hr_shiftgroup_id) REFERENCES hr_shiftgroup (hr_shiftgroup_id) MATCH SIMPLE ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE c_country ADD CONSTRAINT ccountry_ccountry FOREIGN KEY (c_country_id) REFERENCES c_country (c_country_id) MATCH SIMPLE ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE hr_jobopening ADD CONSTRAINT hrjobopening_hrjobopening FOREIGN KEY (hr_jobopening_id) REFERENCES hr_jobopening (hr_jobopening_id) MATCH SIMPLE ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE hr_salarystructure ADD CONSTRAINT hrsalarystructure_hrsalarystru FOREIGN KEY (hr_salarystructure_id) REFERENCES hr_salarystructure (hr_salarystructure_id) MATCH SIMPLE ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE ad_wf_process ADD CONSTRAINT adwfprocess_adwfprocess FOREIGN KEY (ad_wf_process_id) REFERENCES ad_wf_process (ad_wf_process_id) MATCH SIMPLE ON DELETE NO ACTION ON UPDATE NO ACTION
</pre>

My proposal is drop it constraints, the follow is the action:

<pre>
ALTER TABLE hr_shiftgroup DROP CONSTRAINT IF EXISTS hrshiftgroup_hrshiftgroup;
ALTER TABLE c_country DROP CONSTRAINT IF EXISTS ccountry_ccountry;
ALTER TABLE hr_jobopening DROP CONSTRAINT IF EXISTS hrjobopening_hrjobopening;
ALTER TABLE hr_salarystructure DROP CONSTRAINT IF EXISTS hrsalarystructure_hrsalarystru;
ALTER TABLE ad_wf_process DROP CONSTRAINT IF EXISTS adwfprocess_adwfprocess;
</pre>

**Comment by e-Evolution** [comment]
Hi Yamel of constrain are generate with this [Script](https://sourceforge.net/p/adempiere/svn/HEAD/tree/contributions/stuff/script_to_generate_foreign_keys/generateForeignKeys_pg.sql) from Oracle DB 

So may be this key have an incorrect definition , may be that are defined as parent link when only are primary key field

kinds regards

**Comment by yamelsenih** [comment]
Hi @e-Evolution it is need change, is a bad reference. I will make a xml with it
