### ISSUE TITLE
Integrate ADempiere POS into ADempiere core

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#484]
Integration of ADempiere POS [repository](https://github.com/adempiere/adempierePOS) into ADempiere core

**Comment by e-Evolution** [comment]
Working in process  ....

**Comment by e-Evolution** [comment]
Complete ADempiere binary building .

nstall:
     [echo] =========== Install Adempiere
     [copy] Copying 4 files to /Users/e-Evolution/Documents/Develop/ADempiere/adempiere/adempiere/install
     [copy] Copying /Users/e-Evolution/Documents/Develop/ADempiere/adempiere/install/build/Adempiere_380LTS.zip.MD5 to /Users/e-Evolution/Documents/Develop/ADempiere/adempiere/adempiere/install/Adempiere_380LTS.zip.MD5
     [copy] Copying /Users/e-Evolution/Documents/Develop/ADempiere/adempiere/install/build/Adempiere_380LTS.zip to /Users/e-Evolution/Documents/Develop/ADempiere/adempiere/adempiere/install/Adempiere_380LTS.zip
     [copy] Copying /Users/e-Evolution/Documents/Develop/ADempiere/adempiere/install/build/Adempiere_380LTS.tar.gz to /Users/e-Evolution/Documents/Develop/ADempiere/adempiere/adempiere/install/Adempiere_380LTS.tar.gz
     [copy] Copying /Users/e-Evolution/Documents/Develop/ADempiere/adempiere/install/build/Adempiere_380LTS.tar.gz.MD5 to /Users/e-Evolution/Documents/Develop/ADempiere/adempiere/adempiere/install/Adempiere_380LTS.tar.gz.MD5
   [delete] Deleting 462 files from /Users/e-Evolution/Documents/Develop/ADempiere/adempiere/adempiere/Adempiere/migration
   [delete] Deleted 6 directories from /Users/e-Evolution/Documents/Develop/ADempiere/adempiere/adempiere/Adempiere/migration
   [delete] Deleting 55 files from /Users/e-Evolution/Documents/Develop/ADempiere/adempiere/adempiere/Adempiere/lib
   [delete] Deleted 4 directories from /Users/e-Evolution/Documents/Develop/ADempiere/adempiere/adempiere/Adempiere/lib
   [delete] Deleting 205 files from /Users/e-Evolution/Documents/Develop/ADempiere/adempiere/adempiere/Adempiere/jboss
   [delete] Deleted 40 directories from /Users/e-Evolution/Documents/Develop/ADempiere/adempiere/adempiere/Adempiere/jboss
    [unzip] Expanding: /Users/e-Evolution/Documents/Develop/ADempiere/adempiere/install/build/Adempiere_380LTS.zip into /Users/e-Evolution/Documents/Develop/ADempiere/adempiere/adempiere

complete:

BUILD SUCCESSFUL

**Comment by marcalwestf** [comment]
tested and working. Closing issue.
