### ISSUE TITLE
Bad icon for ZK skin

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#485]
The current ZK skin have a icons for tool bar that is not correct like show the follow image:
![issue2000](https://cloud.githubusercontent.com/assets/2333092/17536474/2c8f8aec-5e63-11e6-9568-46427fcd631c.png)
- The red circle define the **Next Record** action but the icon is standard for forward.
- The yellow circle define the **Last Record** action but the icon is for standard next.

**Comment by jdaison** [comment]
Yamel i think that already icons are correct

**Comment by yamelsenih** [comment]
Hi @jdaison note that the swing button is not the same type of ZK
![issue2002](https://cloud.githubusercontent.com/assets/2333092/17655866/50f67cac-6281-11e6-9a61-3ef8920110a2.png)
