### ISSUE TITLE
Update README file to include 'Getting Started' instructions or redirect to 'Wiki Doc.' page 

### ISSUE THREAD

**Issue by JerJohn15** [adempiere/adempiere#487]
Hello Adempiere community,

I just recently came across this project and noticed there is no 'Getting Started' section within the README file. I wanted to make a recommendation that either one be made (so that users understand what it is, as well as how to install/ configure the application), or if not, at least redirect users to a wiki page by providing  a link to the [wiki](http://www.adempiere.net/web/guest/wiki) page (since all of the documentation appears to be included on the main site).

**Comment by yamelsenih** [comment]
Hi @JerJohn15 thank you for your recommendation we will change the README.md file for add it information.
