### ISSUE TITLE
Unresolved reference after change 

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#488]
![Uploading issue2001.png…]()
After change of integration POS with ADempiere, exists a reference unresolved, it is caused by the change make with @e-Evolution in [https://github.com/adempiere/adempierePOS/commit/57a1412d8457b13734d8b7c51b8dd4f375102796](https://github.com/adempiere/adempierePOS/commit/57a1412d8457b13734d8b7c51b8dd4f375102796)

**Comment by yamelsenih** [comment]
Also exists may references that was yet deleted in tthe commit [https://github.com/adempiere/adempiere/commit/16ba23cd1ae3789ae6b5e4a00e2f88162b031818](https://github.com/adempiere/adempiere/commit/16ba23cd1ae3789ae6b5e4a00e2f88162b031818), the follow is a list show the missing references:
- PosKeyListener
- PosKeyboardFocusManager

It broken the follow class:
- POSDocumentPanel
- POSKeyboard
- POSKeyPanel
- VPOS
- WPOS
- WPOSActionPanel
- WPOSDocumentPanel
- WPOSKeyboard
- WPOSKeyPanel

I think that it chage must be tested before push or make it like a pull request.

**Comment by e-Evolution** [comment]
Yes @yamelsenih the Adempiere POS is in working process , current i am fix the dependenced for intellij and before eclipse 

I finish this tomorrow

**Comment by yamelsenih** [comment]
Yes, i think that if it maybe a dependent error then is better make the push after fixed.

The eclipse dependency is solved in the previous commit.

Best regards
