### ISSUE TITLE
Add IsAllowsCopy method in GridFieldVO and GridField 

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#50]
This method will allow callout business logic can be valid when an copy action is executed from a window

**Comment by yamelsenih** [comment]
Hi @e-Evolution i think that it already exist in ADempiere, you can provide the commit of it?

**Comment by liosc** [comment]
Hi,
@e-Evolution, on Apr 25, 2017 you referenced this issue to the #1002 which is closed. Does this mean that also this issue is solved?
