### ISSUE TITLE
Validate processes within POS

### ISSUE THREAD

**Issue by wdtz** [adempiere/adempiere#502]
Selecting the process within the point of sale "reverse the sales transaction" generates error "java.lang.NullPointerException", this occurs when there is not a sell order selected, there must be a validation for these cases.

![image](https://cloud.githubusercontent.com/assets/9578152/17713738/63441960-63ca-11e6-9a91-a4f41df8c358.png)

<pre>
: Assignment [69]
===========> zkoss.handleError:1130: >>java.lang.NullPointerException
>>  at org.adempiere.pos.service.CPOS.getDocumentNo(Unknown Source)
>>  at org.adempiere.pos.WPOSActionMenu.beforeExecutionCommand(Unknown Source)
>>  at org.adempiere.pos.WPOSActionMenu.onEvent(Unknown Source)
>>  at org.zkoss.zk.ui.impl.EventProcessor.process0(EventProcessor.java:197)
>>  at org.zkoss.zk.ui.impl.EventProcessor.process(EventProcessor.java:141)
>>  at org.zkoss.zk.ui.impl.EventProcessingThreadImpl.process0(EventProcessingThreadImpl.java:519)
>>...
</pre>

**Comment by yamelsenih** [comment]
Hi, any update for it?

**Comment by yamelsenih** [comment]
This was resolved
