### ISSUE TITLE
MRP Reschedule throw error when try execute process 	 

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#507]
org.eevolution.model.MPPMRP cannot be cast to org.eevolution.model.MPPMRP
![captura de pantalla 2016-08-17 a las 2 41 27 a m](https://cloud.githubusercontent.com/assets/786968/17728270/2203958e-6424-11e6-96aa-b77a68ddbd16.png)

**Comment by yamelsenih** [comment]
Hi it is solved:
![arbol_72](https://user-images.githubusercontent.com/2333092/27008780-2617218e-4e4a-11e7-9e2b-0a6c3b45b4a8.png)

**Comment by testiranje1234** [comment]
![scheduling_of_the_demands_2](https://user-images.githubusercontent.com/26572325/27010068-6ddb7f04-4e9c-11e7-86ba-46587a6d6b5c.png)
I was yesterday(10.06.2017) download and instal database and re-build adempeire 390 realize from github, all work, but on low ui-zk- resolution of virtual box look small. but work.

**Comment by testiranje1234** [comment]
did I again download and reinstall adempiere 390 realize on virtualbox, yesterday I m and reinstall all and rebuild all code with netbenas 8 on oracle 11g xe with drop/create/imp/dmp new schema? Or there is simple way how to make same hierarchial on java applet guil swing with zk?
![scheduling of the demands3](https://user-images.githubusercontent.com/26572325/27010169-98926788-4e9e-11e7-8e04-ec41c6302612.png)

**Comment by testiranje1234** [comment]
ok, I found #758 #1085, I m safe 300 mbytes of internet :)
![update_1](https://user-images.githubusercontent.com/26572325/27010408-0d1c6aa4-4ea4-11e7-939f-c24ec6523934.png)
