### ISSUE TITLE
Buttons on VLookup fields in Find window don't work.

### ISSUE THREAD

**Issue by mckayERP** [adempiere/adempiere#508]
When opening a window where a search/find window appears before the window appears, if a VLookup (Search) field is used as a parameter, the button in the field will cause an NPE in the Info.java code as line 350:

`if (frameClass == AWindow.class)
        {
            //  Activated from a window - find the active tab to limit the context
            p_TabNo = ((AWindow) frame).getAPanel().getCurrentTab().getTabNo();
        }
`
The problem is that the call to getCurrentTab() is null as the variable m_curTab in APanel.java has not been initialized by the APanel code.  

Solution is to initialize the m_curTab to the first tab as the APanel is being initialized.

**Comment by yamelsenih** [comment]
Hi @mckayERP i think that is better if is validate the getCurrentTab() with null

**Comment by yamelsenih** [comment]
Hi, it is solved.
