### ISSUE TITLE
Alert period closed

### ISSUE THREAD

**Issue by wdtz** [adempiere/adempiere#510]
No show warning period closed in trying to complete the documents ZK

![image](https://cloud.githubusercontent.com/assets/9578152/17744998/27f56fa4-6478-11e6-9c08-7326945862db.png)

**Comment by yamelsenih** [comment]
Hi @wdtz i test it with last DB and current source code from my computer and it is working, see the follow image:
![issue2007](https://cloud.githubusercontent.com/assets/2333092/17871747/e45cb542-688a-11e6-87b0-5372f2abdf71.png)
