### ISSUE TITLE
Error to Generate invoice process

### ISSUE THREAD

**Issue by wdtz** [adempiere/adempiere#513]
not generate invoice by filling the parameter when entering organization to organization *, the process establishes the organization context in the invoice generated.
![image](https://cloud.githubusercontent.com/assets/9578152/17758369/b7bbb24e-64bc-11e6-8491-27f3d4be302e.png)

**Comment by liosc** [comment]
Hi,
I'm not sure to have understood clearly the problem but If it is a bug concerning the process of generating invoice why It is on 3.9.1 milestone instead of 3.9.0?

**Comment by yamelsenih** [comment]
Hi @wdtz @liosc it issue was solved on #514
