### ISSUE TITLE
Error in  process to Generate invoices from shipments(manual)

### ISSUE THREAD

**Issue by wdtz** [adempiere/adempiere#515]
<pre>
>>org.adempiere.webui.exception.ApplicationException:
 Web UI form not implemented for the swing form 
org.adempiere.apps.form.VInvoiceGenFromShipment >>org.adempiere.webui.exception.ApplicationExceptio...
</pre>
![image](https://cloud.githubusercontent.com/assets/9578152/17758770/225b0a16-64c0-11e6-942d-db4f6cfefd6e.png)

**Comment by yamelsenih** [comment]
Hi @wdtz it will be change to SB like show the issue: #296 .
The issue is duplicated in #434

**Comment by AncyMaryJose** [comment]
I created one custom form. I got the same error. The problem is in
 Class<?> clazz = ADForm.class.getClassLoader().loadClass(zkName);
this line didnot return anything. 
Class not found exception. Can you help???
