### ISSUE TITLE
(POS) keys layouts (missing buttons)

### ISSUE THREAD

**Issue by wdtz** [adempiere/adempiere#519]
- Button to delete in touch?
- How do I write words Dieresis  or Tilde?
  ![image](https://cloud.githubusercontent.com/assets/9578152/17776792/f451b522-652b-11e6-8946-891ab15a4d9d.png)

**Comment by yamelsenih** [comment]
Hi @wdtz is really, i propose the follow:

- Add a Unicode field for special character.
- Verify if exists a library for generate a keys from SO language like physical keyboard.
- Add a option for get keys from SO keyboard library.
