### ISSUE TITLE
(POS) keys layouts (Validate Image)

### ISSUE THREAD

**Issue by wdtz** [adempiere/adempiere#520]
When the keyboard type is numeric and alphabetical in the keys layouts should not show the field to load image or icon
![image](https://cloud.githubusercontent.com/assets/9578152/17777219/b296e43e-652d-11e6-8e23-70a1280c91d0.png)

**Comment by yamelsenih** [comment]
Hi @wdtz the image is a additional attribute, you can have a text with a image also.
