### ISSUE TITLE
(POS) keys layouts (Validate Description)

### ISSUE THREAD

**Issue by wdtz** [adempiere/adempiere#521]
When the keyboard type is numeric and alphabetical in the  keys layouts the text field should be mandatory.

![image](https://cloud.githubusercontent.com/assets/9578152/17777695/7e1b5918-652f-11e6-8cfb-69b453d81366.png)

**Comment by yamelsenih** [comment]
Hi @wdtz it should be not mandatory, currently we are working for add a **key code** in the table for handle the decimal value from unicode, then the **Text** field is not mandatory, see the issue #519

Best Regard
