### ISSUE TITLE
(POS) logic read-only (product field)

### ISSUE THREAD

**Issue by wdtz** [adempiere/adempiere#525]
If select "product" should  block  the field  "layout key" and reverse.
![image](https://cloud.githubusercontent.com/assets/9578152/17780845/d7bf6cec-653a-11e6-9299-770ac0340a92.png)

**Comment by yamelsenih** [comment]
Previous behavior:
![POS_Key_Layout_Bug](https://user-images.githubusercontent.com/2333092/58443778-2e481f00-80c2-11e9-8be7-4bad01f30d57.gif)

**Comment by yamelsenih** [comment]
After change:
![Current ogv](https://user-images.githubusercontent.com/2333092/58444567-d233c980-80c6-11e9-8b4d-c103792507db.gif)
