### ISSUE TITLE
(POS) duplicate key layout

### ISSUE THREAD

**Issue by wdtz** [adempiere/adempiere#526]
It allows product duplicate keys this is meaningless.

**Comment by yamelsenih** [comment]
I think that it is not a bug, a product can be added to many items as pack

Product Name| Quantity
------------ | -------------
Azalea  |  1
Azalea (3 Pack)  |  3

![Current ogv](https://user-images.githubusercontent.com/2333092/58447297-fa74f580-80d1-11e9-999b-b78d120ba819.gif)
