### ISSUE TITLE
(POS) logic read-only (quantity field)

### ISSUE THREAD

**Issue by wdtz** [adempiere/adempiere#527]
If select "layout key" should block the field "quantity".

![image](https://cloud.githubusercontent.com/assets/9578152/17781858/ff212308-653e-11e6-881b-000261b15f4e.png)

**Comment by yamelsenih** [comment]
After change:
![Current ogv](https://user-images.githubusercontent.com/2333092/58447655-1b8a1600-80d3-11e9-9397-473e347e377e.gif)
