### ISSUE TITLE
(POS) Error en distribution of space from line of order

### ISSUE THREAD

**Issue by wdtz** [adempiere/adempiere#529]
When I get over the amount needed to fill the space in the  window non-active scroll and there is no way to see the products that are under.

_**This order has 6 lines and only shows 5 lack of space.**_
![image](https://cloud.githubusercontent.com/assets/9578152/17784883/57bd4d0e-654c-11e6-92a0-fe389d288cb9.png)

**Comment by yamelsenih** [comment]
This is because resolution is very half
