### ISSUE TITLE
(POS) Update fields

### ISSUE THREAD

**Issue by wdtz** [adempiere/adempiere#533]
when opening the window is apparently the values of the first line of the order is established, however, only sets the amounts of the line appears to be selected, what about other values (price and discount)?

![image](https://cloud.githubusercontent.com/assets/9578152/17786787/68b2157e-6554-11e6-85fb-c5659120e6c7.png)

**Comment by e-Evolution** [comment]
@wdtz can please set of labels and milestone and assign a resource to revision or fix this way we have all issues identified ?

**Comment by wdtz** [comment]
hi @e-Evolution I do not have access

**Comment by yamelsenih** [comment]
Hi @e-Evolution I am setting the topic and others
