### ISSUE TITLE
(POS) List Price (Terminal)

### ISSUE THREAD

**Issue by wdtz** [adempiere/adempiere#535]
If it is a POS should validate that only display the lists of sales price

![image](https://cloud.githubusercontent.com/assets/9578152/17788364/4a6b8ada-655b-11e6-8689-8c4a7de41cb9.png)

**Comment by yamelsenih** [comment]
After change:
![Current ogv](https://user-images.githubusercontent.com/2333092/58448197-1af27f00-80d5-11e9-8fc8-2e704509ab01.gif)
