### ISSUE TITLE
(POS) Key Layout in Terminal

### ISSUE THREAD

**Issue by wdtz** [adempiere/adempiere#536]
Must validate the types of keyboards per field respectively , Eg if a keyboard is alfanumerico should appear in the "On Screen Keyboard layout" if numeric in the "On Screen layout Pad Number" field and if product "POS Key Layout"

![image](https://cloud.githubusercontent.com/assets/9578152/17788848/8c6ef712-655d-11e6-8a5f-5494a57515be.png)

**Comment by yamelsenih** [comment]
After change:
![Current ogv](https://user-images.githubusercontent.com/2333092/58448954-8fc6b880-80d7-11e9-89e8-44e85375787b.gif)
