### ISSUE TITLE
(POS)Payment Panel

### ISSUE THREAD

**Issue by wdtz** [adempiere/adempiere#537]
The panel collection uncomfortable to work when more than one type of payment.

**_this case has two forms of payment, check and cash and is not displayed correctly, it becomes somewhat uncomfortable._**

![image](https://cloud.githubusercontent.com/assets/9578152/17789661/2f61c820-6561-11e6-88b2-c761d510b674.png)

**Comment by yamelsenih** [comment]
I think that it should be like is the smart browser search, with a collapsible panel, currently is very complicated and confused

**Comment by yamelsenih** [comment]
Is nice to have, the screen can be many little
