### ISSUE TITLE
(POS) Cash Closure (not working)

### ISSUE THREAD

**Issue by wdtz** [adempiere/adempiere#546]
Shows No Bank Account has an error in the dynamic validation (See attached)
![image](https://cloud.githubusercontent.com/assets/9578152/17870755/baa044de-6886-11e6-9ce5-2ae6d2c2115b.png)

<pre>
GridField.getDefault: (C_BankAccount_ID) - Default SQL variable parse failed: @SQL=SELECT ba.C_BankAccount_ID FROM C_BankAccount ba WHERE EXISTS (SELECT 1 FROM C_POS pos WHERE  pos.C_POS_ID=@pos.C_POS_ID@ AND pos.C_BankAccount_ID=ba.C_BankAccount_ID) [106]
</pre>

**Comment by e-Evolution** [comment]
Hi @wdtz this problem is cause because the 0264_Fixed_SB_Context.xml was executed before of migration script that add this validation , can fix importa and execute again of 0264_Fixed_SB_Context script

**Comment by yamelsenih** [comment]
I agree with Victor, the context values was are changed, just run the XML and test newsly.

Please test it and give us the result.
Best Regards.

**Comment by dixon22ma** [comment]
Hi this error persists execute xml  [0264_Fixed_SB_Context.xml](https://github.com/adempiere/adempiere/blob/hotfix/3.8.0%23002/migration/380lts-release/0264_Fixed_SB_Context.xml)

**Comment by wdtz** [comment]
Hi @e-Evolution sorry,  this solution does not work

**Comment by e-Evolution** [comment]
The migration script create for Yamel no include for display rule , He say me that need fix the xml script to include this context variable, can test change form pos. prefix to POS_

**Comment by yamelsenih** [comment]
Hi @wdtz i change the xml for resolve it issue, now the dynamic validation in the SB is changed in the XML.
