### ISSUE TITLE
(POS) Without identification field

### ISSUE THREAD

**Issue by wdtz** [adempiere/adempiere#548]
In the query window Business Partner is a field unidentified. (See Picture)
![image](https://cloud.githubusercontent.com/assets/9578152/17872639/f694a4aa-688e-11e6-9c89-669a5e14db34.png)

**Comment by Raul-mz** [comment]
After the commit 
![lookup_tabla1](https://cloud.githubusercontent.com/assets/9552217/17893209/d668eb8a-6912-11e6-9861-3087ac05d385.png)

**Comment by Raul-mz** [comment]
[Commit #548 Fixed Error With identification field ](https://github.com/adempiere/adempiere/commit/cf1d73b8a87526126360f052e1a816174a21182b)

**Comment by wdtz** [comment]
Thanks for the solution, revision satisfactory results.
