### ISSUE TITLE
(POS) No shows details on closing cash

### ISSUE THREAD

**Issue by wdtz** [adempiere/adempiere#550]
In the closing cash does not show me the details of payment (Cash, check, etc.)
For optimal closure cash is needthe details.
![image](https://cloud.githubusercontent.com/assets/9578152/17873938/6212c124-6896-11e6-995b-78e0fc07c464.png)

![image](https://cloud.githubusercontent.com/assets/9578152/17874037/1bde686a-6897-11e6-8d6b-9633c450fb9b.png)

**Comment by wdtz** [comment]
sorry I was a cache, reboot and it works.

**Comment by yamelsenih** [comment]
Is nice to have
