### ISSUE TITLE
(POS)Failed to start the search in the sb for closing cash

### ISSUE THREAD

**Issue by wdtz** [adempiere/adempiere#552]
When beginning the search in the smart browser generates a series of errors. (See error)

<pre>
GridField.getDefault: (C_BankAccount_ID) - Default SQL variable parse failed: @SQL=SELECT ba.C_BankAccount_ID FROM C_BankAccount ba WHERE EXISTS (SELECT 1 FROM C_POS pos WHERE  pos.C_POS_ID=@POS_C_POS_ID@ AND pos.C_BankAccount_ID=ba.C_BankAccount_ID) [508]
-----------> GridField.getDefault: (LineTotalAmt) - Default SQL variable parse failed: @SQL= SELECT SUM (o.grandtotal) FROM C_Order o WHERE o.C_POS_ID = @C_POS_ID@ AND o.DateOrdered  BETWEEN TO_DATE('@PAY_DateTrx@','YYYY-MM-DD') AND TO_DATE('@PAY_DateTrx_To@','YYYY-MM-DD') AND o.DocStatus IN ('CO','CL') [106]
-----------> GridField.getDefault: (PaidAmt) - Default SQL variable parse failed: @SQL=SELECT  COALESCE(SUM(p.PayAmt),0) AS PaidAmt  FROM C_Payment p WHERE p.C_POS_ID = @C_POS_ID@ AND p.DateTrx  BETWEEN TO_DATE('@PAY_DateTrx@','YYYY-MM-DD') AND TO_DATE('@PAY_DateTrx_To@','YYYY-MM-DD') AND p.DocStatus IN ('CO','CL') [106]
-----------> GridField.getDefault: (OpenAmt) - Default SQL variable parse failed: @SQL=SELECT SUM(o.Grandtotal - COALESCE((SELECT SUM(p.PayAmt) FROM C_Payment p WHERE p.C_Order_ID = o.C_Order_ID AND p.DocStatus IN ('CO','CL')),0))  FROM C_Order o WHERE o.C_POS_ID = @C_POS_ID@ AND o.DateOrdered  BETWEEN TO_DATE('@PAY_DateTrx@','YYYY-MM-DD') AND TO_DATE('@PAY_DateTrx_To@','YYYY-MM-DD') AND o.DocStatus IN ('CO','CL') AND o.PaymentRule = 'P'  [106]
-----------> GridField.getDefault: (DifferenceAmt) - Default SQL variable parse failed: @SQL=SELECT COALESCE(SUM(COALESCE(o.Grandtotal,0) - (SELECT COALESCE(SUM(p.PayAmt), 0 )  FROM C_Payment p WHERE p.C_Order_ID = o.C_Order_ID AND p.DocStatus IN ('CO','CL'))),0) FROM C_Order o WHERE  o.C_POS_ID = @C_POS_ID@ AND o.DateOrdered  BETWEEN TO_DATE('@PAY_DateTrx@','YYYY-MM-DD') AND TO_DATE('@PAY_DateTrx_To@','YYYY-MM-DD') AND o.DocStatus IN ('CO','CL') AND o.PaymentRule NOT IN('P') [106]

</pre>

**Comment by yamelsenih** [comment]
I was resolved yet after 3.9.1 AD version
