### ISSUE TITLE
Criteria Search on SB don't have a parameter like only information

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#556]
The filter search of Smart Browser don't have a attribute for create a field like only reference for view, example:

I want show a field (Only information) with the bank account balance, but it field is only for view information in the search panel instead filter the query.

**Comment by e-Evolution** [comment]
Hi Yamel then not is a parameter , a way to solve is show as read only and system will create where with same information in this case of open balance need is in query

**Comment by yamelsenih** [comment]
I want add a flag named **IsInfoOnly** for mark it like just information

**Comment by yamelsenih** [comment]
Hi @e-Evolution i can have a search field like read only and use it in the filter, i think that is better if is added a property for determinate if it is not for criteria search

**Comment by e-Evolution** [comment]
in this case , the definition to be criteria search not exist , we would create other concept show in information panel or some similar , the idea is that when a record of smart browser is selected then the info panel is update, any field of information panel should can be updatable from a callout.

I think that would be good the new feature , but now are little the process that need this feature, so I not sure if justifies the work :-), if you think that is justifies then you are welcome
