### ISSUE TITLE
Add support to calculated freight for Sales Order,  Distribution Order and Outbound Orden

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#559]
Currently ADempiere not have implement for calculated freight, now exist a model but not is implement

**Comment by trifonnt** [comment]
hi Victor,

this commit broke the build.
I have fixed it locally and when my local build pass will commit fix.

Regards,
Trifon

**Comment by e-Evolution** [comment]
@trifonnt thank a lot to fix eclipse class path , I no use more Eclipse use IntelliJ, this reason because not can enable to Eclipse.
