### ISSUE TITLE
Add process to generate invoice from payroll process

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#562]
Functionality allows generate a invoice from payroll process

**Comment by e-Evolution** [comment]
Menu option

![1472071450](https://cloud.githubusercontent.com/assets/786968/17947286/b0591c4e-6a11-11e6-97b5-9a5ac221259f.png)

**Comment by e-Evolution** [comment]
Setting Payroll Concept

![captura de pantalla 2016-08-24 a las 4 03 03 p m](https://cloud.githubusercontent.com/assets/786968/17947934/62a014be-6a14-11e6-9a18-cca2438bd508.png)

Attribute to define document type and change 

![captura de pantalla 2016-08-24 a las 4 07 30 p m](https://cloud.githubusercontent.com/assets/786968/17948082/e97bd036-6a14-11e6-92b4-1e81936f680c.png)

**Comment by yamelsenih** [comment]
Hi @e-Evolution it is nice, i think that can be better if you use a Smart Browse for select records
