### ISSUE TITLE
Allow deleting multiple records in grid mode

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere#564]
Right now, the Delete icon (F3) allows for deleting just one record inside a window. 

On the other side, it is possible (with CTL+LEFT CLICK in the grid mode) to select several records of a window. If there are several records selected and the Delete icon is pressed, the first selected record is deleted.

The proposed enhancement would in such cases delete all selected records when in the grid mode.

This is a handy enhancement, because sometimes is cumbersome to delete several records at once. The icon "Delete selected items" (XX)can be confusing when there are many records.
![20160825_delete_several_records](https://cloud.githubusercontent.com/assets/1789408/17980196/5ab55e6a-6abb-11e6-95c1-8e4a6873589d.png)

**Comment by e-Evolution** [comment]
Great @marcalwestf is necessary of ZK implementation, we need have synchronize of swing UI with ZK UI , can please commit also ?

**Comment by marcalwestf** [comment]
still missing implementation in ZK

**Comment by e-Evolution** [comment]
Hi Mario have you some new about ZK implementation ?

**Comment by yamelsenih** [comment]
Hi @marcalwestf it is nice, i thin that is better if when is selected somethimes records and you press the Delete button, the window for delete many records is showed with a records selected by default

**Comment by yamelsenih** [comment]
@marcalwestf i can help you to implent it in ZK with my little suggest

**Comment by marcalwestf** [comment]
thanks, I assign it to you

**Comment by yamelsenih** [comment]
Hi @marcalwestf i add a default multi-selection for delete with default selected row, see the folow image:

- First select the row to be deleted: ![issue26](https://cloud.githubusercontent.com/assets/2333092/19227401/e3fabc58-8e86-11e6-8d9d-3998caa85a6c.png)
- After press delete: ![issue27](https://cloud.githubusercontent.com/assets/2333092/19227424/035b43f6-8e87-11e6-98e7-e04a7a1e42a3.png)
- After comfirm it or unselect a rows before press ok: ![issue28](https://cloud.githubusercontent.com/assets/2333092/19227432/3a8662fc-8e87-11e6-827e-e53899b15207.png)

I hope add support to ZK.

**Comment by marcalwestf** [comment]
hi Yamel,
just tested commit ef6e526379260cabba2bcee5d28513117b50ca13 in Swing. It behaves as you report.
