### ISSUE TITLE
The standard cost for packing component type should be divided between batch quantity to get a right rollup cost

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#567]

**Comment by marcalwestf** [comment]
the project doesn't compile with this commit. The error is "_The method isPacking() is undefined for the type MPPProductBOMLine_".  

The error is on line 220:
						_if (bomline.isPacking()) {_

Apparenntly the class MPPProductBOMLine with the method isPacking() has to be also committed.

![20160828_rollup_bom_error](https://cloud.githubusercontent.com/assets/1789408/18017528/24a86158-6b8f-11e6-8f52-d340c49bfa3b.png)

**Comment by e-Evolution** [comment]
Thank Mario please review now , I send other class
