### ISSUE TITLE
Process Dialog is not MVC

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#571]
The process dialog is used for show information about process to run. When it is called from swing menu is showed like a form, if is called from a window is showed like a dialog, both make a query instead of call the inform ation data from a parent class.

**Comment by e-Evolution** [comment]
Error NPE

![captura de pantalla 2016-10-18 a la s 18 49 30](https://cloud.githubusercontent.com/assets/786968/19500857/a5b4fe4a-9566-11e6-825e-82fcf8035a21.png)

**Comment by e-Evolution** [comment]
18:49:00.349         MIssue.load: 47: AD_Client_ID(class java.lang.Integer) = 1000001 [44]
18:49:00.349         MIssue.load: 48: AD_Org_ID(class java.lang.Integer) = 1000019 [44]
===========> zkoss.handleError:1130: >>java.lang.NullPointerException
18:49:00.349         MIssue.setKeyInfo: (PK) AD_Issue_ID=1002927 [44]
>>	at org.adempiere.controller.SmallViewController.createVO(SmallViewController.java:446)
18:49:00.349         Query.buildSQL: TableName = AD_Table_ScriptValidator... SQL = SELECT AD_Client_ID,AD_Org_ID,AD_Rule_ID,AD_Table_ID,AD_Table_ScriptValidator_ID,Created,CreatedBy,EventModelValidator,IsActive,SeqNo,Updated,UpdatedBy FROM AD_Table_ScriptValidator WHERE (AD_Table_ID=? AND EventModelValidator=?) AND IsActive=? ORDER BY SeqNo [44]
>>	at org.adempiere.controller.SmallViewController.createField(SmallViewController.java:374)
18:49:00.350         Query.createResultSet: Parameter IsActive = Y [44]
>>	at org.eevolution.grid.BrowserSearch.loadData(BrowserSearch.java:115)
18:49:00.351           Trx.commit: **** POSave_e1b73363-110f-4cd7-a9e3-f1150f31300c [44]
>>	at org.adempiere.controller.SmallViewController.init(SmallViewController.java:164)
18:49:00.351           Trx.close: POSave_e1b73363-110f-4cd7-a9e3-f1150f31300c [44]
>>	at org.eevolution.form.WBrowser.statInit(WBrowser.java:205)
>>	at org.eevolution.form.WBrowser.init(WBrowser.java:187)
>>... [44]

**Comment by yamelsenih** [comment]
In test it with Garden World and worked, see the image:
![issue54](https://cloud.githubusercontent.com/assets/2333092/19503626/e9ec0074-9582-11e6-950b-21246df8df6c.png)
![issue55](https://cloud.githubusercontent.com/assets/2333092/19503631/ef72d504-9582-11e6-9c4c-5c651c12b554.png)
![issue56](https://cloud.githubusercontent.com/assets/2333092/19503634/f1e985d0-9582-11e6-8ffb-7a39f7b35615.png)

**Comment by e-Evolution** [comment]
@yamelsenih can please check this issue:

This change not allow execute the jasper report included in print formant jasper report.

When execute the report the dialog process is launch , but the report never is executed.

**Comment by yamelsenih** [comment]
Hi @e-Evolution thank you for notify, i will review it

**Comment by yamelsenih** [comment]
Hi @e-Evolution please add images of it step by step.

**Comment by yamelsenih** [comment]
Hi @e-Evolution it is worked?

**Comment by e-Evolution** [comment]
working in last nightly build
