### ISSUE TITLE
Generating of seed database fails at XML "0303_562_AddProcessToGenerateInvoiceFromPayroll.xml"

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere#573]
How to reproduce it (test on Postgres):
1.- Install ADempiere from newest build (as of now, 651544d796251891568decc85a220e15a0fb0460)
2.- Execute RUN_ImportAdempiere
3.-  Execute RUN_MigrateXML
-> all XML files are executed correctly, until a PSQLException is generated
![20160901_xml_error](https://cloud.githubusercontent.com/assets/1789408/18182938/42c9e1f6-704f-11e6-9c7e-b9195ea1a838.png)

The error occurs at step **360** from file _Migration 303 - #562 Add process to generate invoice from payroll process_.
The SQL error is as follows: _org.postgresql.util.PSQLException: ERROR: insert or update on table "ad_process_para_trl" violates foreign key constraint "adprocpara_adprocparatrl"_

**Comment by marcalwestf** [comment]
though I changed the sequence of the files (by adding a "0" before the file name) the error persists.
It is step 360 which causes the error. If the step is jumped, the whole migration succeeds.

**Comment by e-Evolution** [comment]
@marcalwestf the seed database not should be generate in this moment , it step is make when of release is ready in synchronize with oracle seed 

To generate new seed database is necessary more steps , not only run migration script

of this reason I revert to Adempiere 380 seed

If you want create a new seed for other use you can use https://bintray.com/adempiere/ to upload here and other can testing.
