### ISSUE TITLE
Add support the Tomcat 7 to deploy Server WebUI

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#577]
Current only is possible to deployment a Web server based on JBoss and GlassFish

**Comment by marcalwestf** [comment]
tested and working. 
Now, during installation the desired Application Server has to be selected.
By the way, the Tomcat log under _$ADEMPIER_HOME//tomcat/logs_ displays error messages which could lead to possible memory leaks, which JBoss didn't consider. See the following message as an example:
_===========> WebappClassLoader.clearReferencesThreads: The web application [/] appears to have started a thread named [Delete Old Notes] but has failed to stop it. This is very likely to create a memory leak._

**Comment by mckayERP** [comment]
This commit breaks the windows install.  Changing the AdempiereEnvTemplate.properties ADEMPIERE_DB_PATH variable from postgresql to PostgreSQL breaks the RUN_ImportAdempiere.bat file which compares dbVendor=%ADEMPIERE_DB_PATH% to "postgresql".  The result is an error "Database not supported.".  The RUN_ImportAdempiere.bat file needs to be updated as well to use the new case or modified to test of any case.
