### ISSUE TITLE
Setup ADempiere 390 Release 

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#578]

**Comment by marcalwestf** [comment]
this issue will be closed after closing of these issues:

https://github.com/adempiere/adempiere/issues/579
https://github.com/adempiere/adempiere/issues/945
https://github.com/adempiere/adempiere/issues/946
https://github.com/adempiere/adempiere/issues/947
https://github.com/adempiere/adempiere/issues/951
https://github.com/adempiere/adempiere/issues/1039
https://github.com/adempiere/adempiere/issues/1040
