### ISSUE TITLE
Recursive call getAliasForTableSelection

### ISSUE THREAD

**Issue by SusanneCalderon** [adempiere/adempiere#583]
Class VBrowser line 493   
             _if (getFieldKey() != null && getFieldKey().get_ID() > 0) {
                    MViewDefinition viewDefinition = (MViewDefinition) getFieldKey().getAD_View_Column().getAD_View_Definition();
                    pi.setAliasForTableSelection(viewDefinition.getTableAlias());
                    pi.setTableSelectionId(viewDefinition.getAD_Table_ID());
                }._

The viewdefinition can be based on a view instead of a Table. So the method getInstancesForSelection() in class SVRProcess fails because the method PO.getInstances(Integer tableId, List recordIds, String trxName) fails for tables which are views.

**Comment by e-Evolution** [comment]
The current problem is that of PO not support return incenses based on view that have not a key column in your definition.
 
`
PO.getInstances( getTableSelectionId() , getSelectionKeys(), trxName);
`

So this this code return null record. of solution is define a column key into of view table or force the logic in your process as this:


```
        // Based on MRP
        if ( "demand".equals(getAliasForTableSelection())) {
            getProcessInfo().setTableSelectionId(MPPMRP.Table_ID);
            outBoundOrder = createOutBoundOrder();
            createBasedOnDemand(outBoundOrder, (List<MPPMRP>) getInstancesForSelection(get_TrxName()));
        } 
```

in this case implement of second approach.

see #584
