### ISSUE TITLE
Form frame can clober the window context.

### ISSUE THREAD

**Issue by mckayERP** [adempiere/adempiere#586]
The FormFrame, when opened from a button such as "Create From", sets its window number to the same number as the parent window.  When it adds its context values, it overwrites the window context and, on exit, it wipes the window context.  The window will refresh and recover most of the context but some key elements are lost such as the base document type.  For documents, this means the Document Action combo will fail when the user tries to complete the document after using the Create From dialog.

**Comment by mckayERP** [comment]
Related - the create from windows may draw on the parent window context when they are initialized.  If created with their own window number, the initial values may have to be explicitly set using the parent window context instead.

**Comment by yamelsenih** [comment]
Hi @mckayERP i agree with it, the same behavior was found in smart browser and it was removed

**Comment by yamelsenih** [comment]
Hi @mckayERP it is worked, note that it functionality is deprecated on #296
