### ISSUE TITLE
Webui status bar is located on top

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#588]
The status bar in ZK Web UI is located in the up position like is showed i the follow image
![issue1](https://cloud.githubusercontent.com/assets/2333092/19012073/8da073ee-8778-11e6-8d72-a09ac9e388c0.png)

**Comment by yamelsenih** [comment]
Now it is like the follow image:
![issue2](https://cloud.githubusercontent.com/assets/2333092/19012090/0670d2e6-8779-11e6-8df1-af0cb0cbfdf4.png)

**Comment by e-Evolution** [comment]
Hi Yamel

I think that no is good the status bar in bottom , the rason because user not see when is show this way , It not is use full for UI device as tables or smart phones , other problem is for window a lot of fields that fill more 1 peges not can see the status bar if are in 3 page of browser , pelase no chance of status bar , a lot of user think that set the status bar top was nice , return old approach not is good.

**Comment by yamelsenih** [comment]
Hi Víctor it is confusing, the status bar always is located in the bottom and is a standard for any application, also if you see the swing client it is located in the bottom.

By default and internationally the user always see the bottom for watch the status bar, like example you can see:
- Forms.
- Smart Browser.
It have the status bar in the bottom position, is very complicated that just the window for zk use the status bar in the top.

**Comment by yamelsenih** [comment]
Now the window is like all elements in ADempiere:
![issue3](https://cloud.githubusercontent.com/assets/2333092/19016116/5b24103a-87df-11e6-9b32-eee7ec5c4397.png)
![issue4](https://cloud.githubusercontent.com/assets/2333092/19016117/61fd91c4-87df-11e6-944e-5f25fb47b748.png)
![issue5](https://cloud.githubusercontent.com/assets/2333092/19016123/6f92a34c-87df-11e6-8882-e8ae3ca5e3cd.png)

**Comment by e-Evolution** [comment]
I think that should change and define the same behavior for all , I am agree with this.

on the other hand I think that is best the status bar is in top, this is a way that the user  can see and check easily any warning , information or error.

I reviewed on other solutions and are used this way.

![captura de pantalla 2016-10-01 a la s 13 59 38](https://cloud.githubusercontent.com/assets/786968/19016439/6963016a-87df-11e6-9ddf-fdabab615016.png)


![captura de pantalla 2016-10-01 a la s 14 02 11](https://cloud.githubusercontent.com/assets/786968/19016448/b182c1e2-87df-11e6-8d80-1f3a31691a6b.png)


![captura de pantalla 2016-10-01 a la s 14 03 03](https://cloud.githubusercontent.com/assets/786968/19016453/d53547a4-87df-11e6-8e31-d869bc1b2cbd.png)

![captura de pantalla 2016-10-01 a la s 14 03 55](https://cloud.githubusercontent.com/assets/786968/19016461/f8792cee-87df-11e6-8c2a-b4346fd0f572.png)

![captura de pantalla 2016-10-01 a la s 14 05 07](https://cloud.githubusercontent.com/assets/786968/19016465/208ab982-87e0-11e6-9fc4-cf9c24193964.png)

in any web ui not exist the bottom status bar , this case the status bar or info or alert always are show in top window , I think that it is good design of usability 

What do you think other , how need of mayor end user with your customer ?

**Comment by e-Evolution** [comment]
Other example of from compiere the record id is on top

![captura de pantalla 2016-10-01 a la s 14 23 28](https://cloud.githubusercontent.com/assets/786968/19016640/1b2eed04-87e6-11e6-9bb5-c0da5794e29d.png)

**Comment by yamelsenih** [comment]
So i agree with news changes but i don't agree wtih make a change that just apply for Window and is incomplete, the window is one element of GUI but also exists more elements like:

- Forms.
- Smart Browser.
- Info Windows.

The old change was incomplete, is very bad practice that it changes are on the trunk if they are incomplete.
See the standard image into ADempiere like is currently:
![issue3](https://cloud.githubusercontent.com/assets/2333092/19016116/5b24103a-87df-11e6-9b32-eee7ec5c4397.png)
![issue4](https://cloud.githubusercontent.com/assets/2333092/19016117/61fd91c4-87df-11e6-944e-5f25fb47b748.png)
![issue5](https://cloud.githubusercontent.com/assets/2333092/19016123/6f92a34c-87df-11e6-8882-e8ae3ca5e3cd.png)

Also the user that make login on swing app is confused when try use the ZK.

By definition the tools and uses of GUI must be very similary because:

- The user manual is more simple.
- The learning curve is better.
- The impact when the user use other interface of app is little.

Best Regard

**Comment by marcalwestf** [comment]
hello,
I think both solutions have strengths and weaknesses and reasons to exist. 
I wonder if it is possible to implement both of them, just asking via _ad_sysconfig_ which one the client prefers? 
On the other hand, this would mean to implement both ways thoroughly, this means if the client decides to have the status bar down, then it should be applicable for all objects. Same when status bar is selected to be up.

**Comment by yamelsenih** [comment]
Hi @marcalwestf i agree with you.

**Comment by gvilauy** [comment]
Hi @marcalwestf i agree with you too ....
