### ISSUE TITLE
Infinite loop in InfoBPartner when selecting a Contact or a Location/Address

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere#594]
Steps to reproduce
1.- Open the _Info Business Partner_ form
2.- Select a Business partner which has a contact, for example _Garden User_
3.- In the bottom of the form, the contact is displayed
4.- click the contact
Result: in an infinite loop, the _Info Business Partner_ Form is refreshed, calling _recordSelected(int key)_ again and again.

Same happens when the tab _Location/Address_ is selected instead of the tab _Contact_ and a location is selected.

![20161004_bpinfo](https://cloud.githubusercontent.com/assets/1789408/19089796/0ec5ac60-8a39-11e6-95bf-7146b1602290.png)

**Comment by yamelsenih** [comment]
Hi @marcalwestf please test it.

Best regards.

**Comment by marcalwestf** [comment]
tested and now it works. Closing the issue.
