### ISSUE TITLE
Bugfix error when Standard cost is created 

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#60]
Bugfix error when Standard cost is created

**Comment by liosc** [comment]
Hi e-Evolution,
this issue has been created more than 1,5 years ago. Do you know if it is still significant? It there is the need of test, please specify better the business case.

**Comment by e-Evolution** [comment]
Solved with b95028c3fe20a9e5b468b4b4239be9b2de8ca2d7
