### ISSUE TITLE
Add Standard buttons to Payment Allocation

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#606]
Currently the **Payment Allocation** form have a button for process allocation, it is not a **ADempiere standard button**, also in swing is created AS **JButton** instead of **ConfirmPanel**, see a image:
- For Swing GUI: 
  ![issue35](https://cloud.githubusercontent.com/assets/2333092/19370957/446ffbf4-917d-11e6-8ff4-e676f72a6929.png)
- For ZK GUI: 
  ![issue34](https://cloud.githubusercontent.com/assets/2333092/19370960/4bfe0032-917d-11e6-8864-fe0321f30d39.png)

**Comment by yamelsenih** [comment]
Now itis like show the image:

- For Swing GUI: 
![issue37](https://cloud.githubusercontent.com/assets/2333092/19370984/8c747d62-917d-11e6-9980-bf506d4f04d2.png)
- For ZK GUI: 
![issue36](https://cloud.githubusercontent.com/assets/2333092/19370989/94dee05a-917d-11e6-9c98-9bf97bd1e290.png)

**Comment by marcalwestf** [comment]
tested and works OK.

**Comment by e-Evolution** [comment]
@yamelsenih  bug introducing , now the applied amount not is editable. 

![captura de pantalla 2017-05-23 a la s 18 04 03](https://cloud.githubusercontent.com/assets/786968/26380121/4b97094a-3fe2-11e7-9551-387aa2d1bcd8.png)

**Comment by yamelsenih** [comment]
Hi @e-Evolution, it was test by Mario Calderon. Are you sure of it?

**Comment by e-Evolution** [comment]
Hi @yamelsenih , @marcalwestf you can testing in ADempiere Demo server 
http://188.40.37.194:49269/webui/

I think that when the description was added the columns index is wrong

![captura de pantalla 2017-05-24 a la s 17 21 31](https://cloud.githubusercontent.com/assets/786968/26428110/7f872ec4-40a5-11e7-8ebf-95e748cfeadf.png)

**Comment by yamelsenih** [comment]
Thanks you, I will review it and send to you any results.

Best regards.

**Comment by yamelsenih** [comment]
Hi @e-Evolution i fixed it, please see the changes, test it and tell me. Also i add a **Organization** field for overwrite and add the **Description** to invoice.
See the pic:
![arbol_25](https://cloud.githubusercontent.com/assets/2333092/26432237/45892d30-40c8-11e7-8b87-e555866f9aaf.png)


Best Regard and thank you for notify it.

**Comment by yamelsenih** [comment]
If exist a bad behavior it can be reopen
