### ISSUE TITLE
Some countries is necessary create accounting fact for Tax rate 0% 

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#623]
Fact Account not show tax rate 0%.
 
![captura de pantalla 2016-10-18 a la s 02 02 42](https://cloud.githubusercontent.com/assets/786968/19467460/fe566592-94d6-11e6-9e78-fcf84ee9b73d.png)

**Comment by e-Evolution** [comment]
Fact Account show tax rate 0%.

![captura de pantalla 2016-10-18 a la s 02 04 09](https://cloud.githubusercontent.com/assets/786968/19467510/32a22f48-94d7-11e6-9e96-69733ea5203e.png)

**Comment by jdaison** [comment]
Is best make this with one parameter MSysConfig.getBooleanValue(Name, defaultValue)

**Comment by e-Evolution** [comment]
Hi @jdaison 

I good option if you have not need zero account record is that define the like tax exempt, this way of not exist info into C_InvoiceTax , then the accounting engine not generate some fact
