### ISSUE TITLE
Product Info View, Price History Window: add a tab for the Order Price History

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere#630]
An additional tab displaying the Order Price History in the Product Info View, Price History Window yields valuable information.

Examples in ZK and Swing:
![20161021_orderpricehistory](https://cloud.githubusercontent.com/assets/1789408/19540539/7cc04a78-961d-11e6-9649-d45f2f4c852f.png)

![20161021_orderpricehistory_2](https://cloud.githubusercontent.com/assets/1789408/19540544/827ba55c-961d-11e6-8d83-c77af6a1299c.png)

**Comment by e-Evolution** [comment]
Hi Mario can please create a message OrderPriceHistory, this way can implement multiple language

**Comment by marcalwestf** [comment]
OK.
