### ISSUE TITLE
Records Display

### ISSUE THREAD

**Issue by wdtz** [adempiere/adempiere#644]
It allows users to view logs (orders) of another user.

![image](https://cloud.githubusercontent.com/assets/9578152/19744449/932b890c-9b9b-11e6-8da3-45e6186d0ed2.png)

**Comment by yamelsenih** [comment]
Hi @wdtz i test it with the last version and is ok, see the images:
1. With **GardenAdmin** user on ZK.
![issue72](https://cloud.githubusercontent.com/assets/2333092/20451320/38fe10d6-adce-11e6-955a-d44181041570.png)
2. With **GardenAdmin** user on Swing.
![issue73](https://cloud.githubusercontent.com/assets/2333092/20451331/519c1200-adce-11e6-842e-5cd9ce143289.png)
3. With **GardenUser** user on Swing.
![issue74](https://cloud.githubusercontent.com/assets/2333092/20451334/61e96e14-adce-11e6-8fe1-379000c482d1.png)
