### ISSUE TITLE
Create in Garden World an example Email configuration

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere#651]
As the email configuration has changed, it would be nice if a example of an email configuration would be shown in GardenWorld in table AD_EMailConfig.

**Comment by yamelsenih** [comment]
It make reference to #402

**Comment by yamelsenih** [comment]
For Documentation of it see: [http://wiki.adempiere.net/Spin_Contribution:_FR:_EMail_Config](http://wiki.adempiere.net/Spin_Contribution:_FR:_EMail_Config)
