### ISSUE TITLE
Add constraint of concept

### ISSUE THREAD

**Issue by wdtz** [adempiere/adempiere#653]
the code of the concepts must be unique (constraint) since the code is used to evaluate the groovy now it allows to create more than a concept with the same code.

![image](https://cloud.githubusercontent.com/assets/9578152/19869611/6efb1930-9f83-11e6-810e-75873e17a8c8.png)

**Comment by yamelsenih** [comment]
Hi @wdtz i will working in it, is very bad a concept is created with the same value that other, when it is called on a payroll process it call the first looking..

**Comment by yamelsenih** [comment]
Hi @wdtz it change is done, please test it for close it issue.

Best regards

**Comment by wdtz** [comment]
The tests produced satisfactory results, thanks for the solution
![image](https://cloud.githubusercontent.com/assets/9578152/19907843/72beb914-a078-11e6-9857-49ddc0799138.png)
