### ISSUE TITLE
Production Light: DocAction "Prepare" not possible in Production window

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere#662]
In _Production_ window of _Production Light_, the partial production can be accomplished by changing the _Production Quantity_ and executing the process _DocAction_.

This is right now not Possible because only _Complete_ and _Void_ are possible selections of the _Document Action_ combo box.
![20161102_prd_03](https://cloud.githubusercontent.com/assets/1789408/19908113/6effbafc-a047-11e6-93a4-bee18666c442.png)

**Comment by yamelsenih** [comment]
Hi @marcalwestf i test it and is ok
