### ISSUE TITLE
Add new user account dimensions for User3_ID and User4_ID 

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#665]

**Comment by yamelsenih** [comment]
Hi @e-Evolution  is nice if you add more description for it issue

**Comment by yamelsenih** [comment]
Hi @e-Evolution i test it and find that is created with SQL statement instead ADempiere PO, it is not good. my recomendation is:

- Use ADempiere PO. ![issue70](https://cloud.githubusercontent.com/assets/2333092/20353755/38f45448-abf2-11e6-8d33-2edbd7565e10.png)
- It it is not supported with ADempiere PO then asurance that the step have a rollback statement (**It don't have a rollback statement**, **also can be created from ADempiere PO**). 
![issue71](https://cloud.githubusercontent.com/assets/2333092/20353814/5f066fea-abf2-11e6-807e-9c32f4386171.png)

Please change it, if the step is fail then we don't have a way for make a rollback, is very bad.

**Comment by e-Evolution** [comment]
Hi Yamel!

Unfortunately this functionality was created when the tool to generate XML script at runtime did not exist. So I had 2 options to integrate these changes, to place an sql file or to create an XML with the instructions of the file, I have solved it by creating an XML with SQL statements for this unique occasion, since this functionality was made from 2009 and the Ids of these changes were reserved for some time.

kind regards

**Comment by yamelsenih** [comment]
Is really, i understand.

Thank you.

**Comment by yamelsenih** [comment]
It XML is not correct:

- Don't have rollback statement.
- Use INSERT, UPDATE, DELETE directly on DB instead model class.
See:
<pre>
-- New Dimensions
INSERT INTO AD_Reference (AD_Client_ID,AD_Org_ID,AD_Reference_ID,Created,CreatedBy,Description,EntityType,IsActive,IsOrderByValue,Name,Updated,UpdatedBy,ValidationType) VALUES (0,0,53336,TO_TIMESTAMP('2009-11-28 19:01:00','YYYY-MM-DD HH24:MI:SS'),0,'User3 selection based on Client','D','Y','N','Account_ID - User3',TO_TIMESTAMP('2009-11-28 19:01:00','YYYY-MM-DD HH24:MI:SS'),0,'T')
;

-- Nov 28, 2009 7:01:21 PM CST
-- New Dimensions
INSERT INTO AD_Reference_Trl (AD_Language,AD_Reference_ID, Description,Help,Name, IsTranslated,AD_Client_ID,AD_Org_ID,Created,Createdby,Updated,UpdatedBy) SELECT l.AD_Language,t.AD_Reference_ID, t.Description,t.Help,t.Name, 'N',t.AD_Client_ID,t.AD_Org_ID,t.Created,t.Createdby,t.Updated,t.UpdatedBy FROM AD_Language l, AD_Reference t WHERE l.IsActive='Y' AND l.IsSystemLanguage='Y' AND l.IsBaseLanguage='N' AND t.AD_Reference_ID=53336 AND NOT EXISTS (SELECT * FROM AD_Reference_Trl tt WHERE tt.AD_Language=l.AD_Language AND tt.AD_Reference_ID=t.AD_Reference_ID)
;

-- Nov 28, 2009 7:04:12 PM CST
-- New Dimensions
INSERT INTO AD_Ref_Table (AD_Client_ID,AD_Display,AD_Key,AD_Org_ID,AD_Reference_ID,AD_Table_ID,Created,CreatedBy,EntityType,IsActive,IsValueDisplayed,Updated,UpdatedBy,WhereClause) VALUES (0,1135,1125,0,53336,188,TO_TIMESTAMP('2009-11-28 19:04:12','YYYY-MM-DD HH24:MI:SS'),0,'D','Y','N',TO_TIMESTAMP('2009-11-28 19:04:12','YYYY-MM-DD HH24:MI:SS'),0,'C_ElementValue.IsActive=''Y'' AND C_ElementValue.IsSummary=''N'' 
AND C_ElementValue.C_Element_ID IN (SELECT C_Element_ID FROM C_AcctSchema_Element ase WHERE ase.ElementType=''U3'' AND ase.AD_Client_ID=@AD_Client_ID@)')
;
</pre>

See the image:
![precioproducto41](https://cloud.githubusercontent.com/assets/2333092/23370229/71d14cbe-fcea-11e6-9abc-81e4a58a456e.png)
Is Impossible make a rollback if you try migrate a customer
![precioproducto42](https://cloud.githubusercontent.com/assets/2333092/23370239/798998da-fcea-11e6-8be8-181f521ce693.png)

Is a bad practice.

**Comment by e-Evolution** [comment]
Hi @yamelsenih !
Explain the reason why it is not possible to add a rollback script, this functionality was generated with the old SQL-based script approach.

On the other hand the problem is not the script, if not rather that the combination of AD_Tab_ID and AD_Field (270,56073) was added in some unofficial customization.

To solve the problem you only have to remove your customization for this tab and the script should work without problem.

A good practice is not to modify the core windows of the system to avoid these problems, a good practice is to make copies of any component of the dictionary of applications and here make any change for your client.

**Comment by yamelsenih** [comment]
I see the changes and it can add with XML migration, if is old SQL then is better re-create it instead add it like SQL without rollback on XML

**Comment by yamelsenih** [comment]
Is better re-create the change like XML instead of create a XML without rollback

**Comment by yamelsenih** [comment]
The follow tables and views don't have support for new columns:
- **PP_Order**: ERROR:  column "user3_id" does not exist
- **Fact_Acct_Balance**: ERROR:  column "user3_id" does not exist
- **C_Dunning_Line_v**: ERROR:  column "user3_id" does not exist
- **PP_Order_Header_v**: ERROR:  column "user3_id" does not exist
- **T_InvoiceGL_v**: ERROR:  column "user3_id" does not exist
- **RV_InOutDetails**: ERROR:  column "user3_id" does not exist

It change is unstable, i run it Query and exists differences between Application Dictionary and DB Storage:
<pre>
SELECT 'SELECT User3_ID, User4_ID FROM ' || TableName || ';' FROM AD_Table WHERE EXISTS(SELECT 1 FROM AD_Column WHERE AD_Table_ID = AD_Table.AD_Table_ID AND ColumnName IN('User3_ID', 'User4_ID'));
</pre>
It return the follow Querys:
<pre>
SELECT User3_ID, User4_ID FROM C_InvoiceLine;
SELECT User3_ID, User4_ID FROM RV_Fact_Acct_Period;
SELECT User3_ID, User4_ID FROM I_FAJournal;
SELECT User3_ID, User4_ID FROM Fact_Acct;
SELECT User3_ID, User4_ID FROM M_Inventory;
SELECT User3_ID, User4_ID FROM PP_Order;
SELECT User3_ID, User4_ID FROM M_RequisitionLine;
SELECT User3_ID, User4_ID FROM M_MovementLine;
SELECT User3_ID, User4_ID FROM T_TrialBalance;
SELECT User3_ID, User4_ID FROM I_Budget;
SELECT User3_ID, User4_ID FROM Fact_Acct_Balance;
SELECT User3_ID, User4_ID FROM C_InvoiceBatchLine;
SELECT User3_ID, User4_ID FROM M_InventoryLine;
SELECT User3_ID, User4_ID FROM M_Production;
SELECT User3_ID, User4_ID FROM C_Dunning_Line_v;
SELECT User3_ID, User4_ID FROM C_Invoice;
SELECT User3_ID, User4_ID FROM R_Request;
SELECT User3_ID, User4_ID FROM HR_Movement;
SELECT User3_ID, User4_ID FROM GL_DistributionLine;
SELECT User3_ID, User4_ID FROM PP_Order_Header_v;
SELECT User3_ID, User4_ID FROM M_Requisition;
SELECT User3_ID, User4_ID FROM M_ProductionLine;
SELECT User3_ID, User4_ID FROM T_InvoiceGL_v;
SELECT User3_ID, User4_ID FROM PP_Cost_Collector;
SELECT User3_ID, User4_ID FROM C_ValidCombination;
SELECT User3_ID, User4_ID FROM M_Movement;
SELECT User3_ID, User4_ID FROM RV_InOutDetails;
SELECT User3_ID, User4_ID FROM C_Payment;
SELECT User3_ID, User4_ID FROM I_GLJournal;
SELECT User3_ID, User4_ID FROM DD_Order;
SELECT User3_ID, User4_ID FROM I_SalesHistory;
SELECT User3_ID, User4_ID FROM DD_OrderLine;
SELECT User3_ID, User4_ID FROM C_Cash;
SELECT User3_ID, User4_ID FROM Fact_Acct_Summary;
SELECT User3_ID, User4_ID FROM C_SalesHistory;
SELECT User3_ID, User4_ID FROM M_InOut;
SELECT User3_ID, User4_ID FROM HR_Concept_Acct;
SELECT User3_ID, User4_ID FROM M_InOutLine;
SELECT User3_ID, User4_ID FROM C_Order;
SELECT User3_ID, User4_ID FROM PA_ReportColumn;
SELECT User3_ID, User4_ID FROM RV_Fact_Acct_Day;
SELECT User3_ID, User4_ID FROM RV_Fact_Acct;
SELECT User3_ID, User4_ID FROM GL_Distribution;
SELECT User3_ID, User4_ID FROM PA_ReportSource;
SELECT User3_ID, User4_ID FROM C_OrderLine;
SELECT User3_ID, User4_ID FROM GL_JournalLine;
</pre>

When i run each statement find errors:
<pre>
[WARNING  ] SELECT User3_ID, User4_ID FROM PP_Order
            ERROR:  column "user3_id" does not exist
            LINE 1: SELECT User3_ID, User4_ID FROM PP_Order
                           ^
[WARNING  ] SELECT User3_ID, User4_ID FROM Fact_Acct_Balance
            ERROR:  column "user3_id" does not exist
            LINE 1: SELECT User3_ID, User4_ID FROM Fact_Acct_Balance
                           ^
[WARNING  ] SELECT User3_ID, User4_ID FROM C_Dunning_Line_v
            ERROR:  column "user3_id" does not exist
            LINE 1: SELECT User3_ID, User4_ID FROM C_Dunning_Line_v
                           ^
[WARNING  ] SELECT User3_ID, User4_ID FROM PP_Order_Header_v
            ERROR:  column "user3_id" does not exist
            LINE 1: SELECT User3_ID, User4_ID FROM PP_Order_Header_v
                           ^
[WARNING  ] SELECT User3_ID, User4_ID FROM T_InvoiceGL_v
            ERROR:  column "user3_id" does not exist
            LINE 1: SELECT User3_ID, User4_ID FROM T_InvoiceGL_v
                           ^
[WARNING  ] SELECT User3_ID, User4_ID FROM RV_InOutDetails
            ERROR:  column "user3_id" does not exist
            LINE 1: SELECT User3_ID, User4_ID FROM RV_InOutDetails
                           ^
</pre>
The follow tables and views don't have support for new columns:
- **PP_Order**: ERROR:  column "user3_id" does not exist
- **Fact_Acct_Balance**: ERROR:  column "user3_id" does not exist
- **C_Dunning_Line_v**: ERROR:  column "user3_id" does not exist
- **PP_Order_Header_v**: ERROR:  column "user3_id" does not exist
- **T_InvoiceGL_v**: ERROR:  column "user3_id" does not exist
- **RV_InOutDetails**: ERROR:  column "user3_id" does not exist

It change is unstable, i run it Query and exists differences between Application Dictionary and DB Storage:
<pre>
SELECT 'SELECT User3_ID, User4_ID FROM ' || TableName || ';' FROM AD_Table WHERE EXISTS(SELECT 1 FROM AD_Column WHERE AD_Table_ID = AD_Table.AD_Table_ID AND ColumnName IN('User3_ID', 'User4_ID'));
</pre>
It return the follow Querys:
<pre>
SELECT User3_ID, User4_ID FROM C_InvoiceLine;
SELECT User3_ID, User4_ID FROM RV_Fact_Acct_Period;
SELECT User3_ID, User4_ID FROM I_FAJournal;
SELECT User3_ID, User4_ID FROM Fact_Acct;
SELECT User3_ID, User4_ID FROM M_Inventory;
SELECT User3_ID, User4_ID FROM PP_Order;
SELECT User3_ID, User4_ID FROM M_RequisitionLine;
SELECT User3_ID, User4_ID FROM M_MovementLine;
SELECT User3_ID, User4_ID FROM T_TrialBalance;
SELECT User3_ID, User4_ID FROM I_Budget;
SELECT User3_ID, User4_ID FROM Fact_Acct_Balance;
SELECT User3_ID, User4_ID FROM C_InvoiceBatchLine;
SELECT User3_ID, User4_ID FROM M_InventoryLine;
SELECT User3_ID, User4_ID FROM M_Production;
SELECT User3_ID, User4_ID FROM C_Dunning_Line_v;
SELECT User3_ID, User4_ID FROM C_Invoice;
SELECT User3_ID, User4_ID FROM R_Request;
SELECT User3_ID, User4_ID FROM HR_Movement;
SELECT User3_ID, User4_ID FROM GL_DistributionLine;
SELECT User3_ID, User4_ID FROM PP_Order_Header_v;
SELECT User3_ID, User4_ID FROM M_Requisition;
SELECT User3_ID, User4_ID FROM M_ProductionLine;
SELECT User3_ID, User4_ID FROM T_InvoiceGL_v;
SELECT User3_ID, User4_ID FROM PP_Cost_Collector;
SELECT User3_ID, User4_ID FROM C_ValidCombination;
SELECT User3_ID, User4_ID FROM M_Movement;
SELECT User3_ID, User4_ID FROM RV_InOutDetails;
SELECT User3_ID, User4_ID FROM C_Payment;
SELECT User3_ID, User4_ID FROM I_GLJournal;
SELECT User3_ID, User4_ID FROM DD_Order;
SELECT User3_ID, User4_ID FROM I_SalesHistory;
SELECT User3_ID, User4_ID FROM DD_OrderLine;
SELECT User3_ID, User4_ID FROM C_Cash;
SELECT User3_ID, User4_ID FROM Fact_Acct_Summary;
SELECT User3_ID, User4_ID FROM C_SalesHistory;
SELECT User3_ID, User4_ID FROM M_InOut;
SELECT User3_ID, User4_ID FROM HR_Concept_Acct;
SELECT User3_ID, User4_ID FROM M_InOutLine;
SELECT User3_ID, User4_ID FROM C_Order;
SELECT User3_ID, User4_ID FROM PA_ReportColumn;
SELECT User3_ID, User4_ID FROM RV_Fact_Acct_Day;
SELECT User3_ID, User4_ID FROM RV_Fact_Acct;
SELECT User3_ID, User4_ID FROM GL_Distribution;
SELECT User3_ID, User4_ID FROM PA_ReportSource;
SELECT User3_ID, User4_ID FROM C_OrderLine;
SELECT User3_ID, User4_ID FROM GL_JournalLine;
</pre>

When i run each statement find errors:
<pre>
[WARNING  ] SELECT User3_ID, User4_ID FROM PP_Order
            ERROR:  column "user3_id" does not exist
            LINE 1: SELECT User3_ID, User4_ID FROM PP_Order
                           ^
[WARNING  ] SELECT User3_ID, User4_ID FROM Fact_Acct_Balance
            ERROR:  column "user3_id" does not exist
            LINE 1: SELECT User3_ID, User4_ID FROM Fact_Acct_Balance
                           ^
[WARNING  ] SELECT User3_ID, User4_ID FROM C_Dunning_Line_v
            ERROR:  column "user3_id" does not exist
            LINE 1: SELECT User3_ID, User4_ID FROM C_Dunning_Line_v
                           ^
[WARNING  ] SELECT User3_ID, User4_ID FROM PP_Order_Header_v
            ERROR:  column "user3_id" does not exist
            LINE 1: SELECT User3_ID, User4_ID FROM PP_Order_Header_v
                           ^
[WARNING  ] SELECT User3_ID, User4_ID FROM T_InvoiceGL_v
            ERROR:  column "user3_id" does not exist
            LINE 1: SELECT User3_ID, User4_ID FROM T_InvoiceGL_v
                           ^
[WARNING  ] SELECT User3_ID, User4_ID FROM RV_InOutDetails
            ERROR:  column "user3_id" does not exist
            LINE 1: SELECT User3_ID, User4_ID FROM RV_InOutDetails
                           ^
</pre>

**Comment by e-Evolution** [comment]
related #1054

**Comment by yamelsenih** [comment]
Hi @e-Evolution i restore a seed located on /data/seed for PostgreSQL and it throw a error with  ./00430_665_Add_New_User_Account_Dimensions.xml, it say 
<pre>
 2470, step 140, CREATE OR REPLACE VIEW PP_Order_Header_v
</pre>

**Comment by e-Evolution** [comment]
executing with last migration script and not can replicate of issue.

**Comment by dixon22ma** [comment]
This error persist... 
![image](https://user-images.githubusercontent.com/2453563/28691361-aba492e0-72ea-11e7-8733-0745a3c0f309.png)

Source code of release/3.9.0

**Comment by dixon22ma** [comment]
Hi @ALL, this error is generated in seed of release 390,

To take the database, from the master branch I ran the scripts 390 release and did not generates errors.
