### ISSUE TITLE
Multiselection for lookups

### ISSUE THREAD

**Issue by SusanneCalderon** [adempiere/adempiere#668]
class VLookUp line 1049  // TODO hard-coded - add to AD_Column?
The definition if a LookUp for a column is multiselect should be moved from the code to the application dictionary as a column "ismultiselect" in AD_Field.
Actual code:
if(m_mField != null)
			{
				int AD_Table_ID = MColumn.getTable_ID(Env.getCtx(), m_mField.getAD_Column_ID(), null);
				// TODO hard-coded - add to AD_Column?
				multipleSelection = (MOrderLine.Table_ID ==  AD_Table_ID) || 
									(MInvoiceLine.Table_ID == AD_Table_ID) || 
									(I_PP_Product_BOMLine.Table_ID == AD_Table_ID) || 
									(MProductPrice.Table_ID == AD_Table_ID);
			}

**Comment by yamelsenih** [comment]
Hi @SusanneCalderon it can be supported also in InfoProduct and all info windows
