### ISSUE TITLE
Improve Un posted window now show Amount , Business Partner , Document Type

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#67]
Improve Un posted window now show Amount , Business Partner , Document Type
Adding all documents payroll process , asset addition , asset depreciation , asset disposal , cost collector

**Comment by liosc** [comment]
Hi @e-Evolution,
this issue has been opened more than 1,5 years ago. Is the adding in all the mentioned documents still in progress?

**Comment by e-Evolution** [comment]
implement #739
