### ISSUE TITLE
Solve incorrect accounting with standard cost variance posting 

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#69]
Solve incorrect accounting with standard cost variance posting

**Comment by e-Evolution** [comment]
add account description posting using manufacturing order

**Comment by liosc** [comment]
Hi,
this issues has been opened more than 1,5 years ago. There are commits but I don't see any testing or feedback. Could it be closed? If tests are needed, please specify better the use case.

**Comment by e-Evolution** [comment]
Solved with fc168a1da5f5dd0bd0b8d805a4b066c917faa09d
