### ISSUE TITLE
Adempiere 3.9 seed db OracleXE [not supported error]

### ISSUE THREAD

**Issue by taherelhossin** [adempiere/adempiere#694]
When importing seed db and my db is OracleXE, on Windows.. adempiere say 

_The database vendor OracleXE is not supported.             
The seed file  could not be loaded.                        
Please make sure it exists and you have read permissions._

**Comment by marcalwestf** [comment]
hi , it seems you could overcome the issue.
You can close it now.

**Comment by taherelhossin** [comment]
yes, but it still an issue

**Comment by taherelhossin** [comment]
solved here 
#577 Add support the Tomcat 7 to deploy Server WebUI #577

**Comment by taherelhossin** [comment]
Sorry @marcalwestf , i don't have authority to close the issue
