### ISSUE TITLE
[Bug] Evaluator doesn't complain with algebraic logic standards

### ISSUE THREAD

**Issue by Luchillo** [adempiere/adempiere#697]
So a co-worker and i were making some `read only logic` in a window, then he puts this in there to block the document when it's state is completed and the user is neither him as admin user or the client's company owner:

```java
@DocStatus@ = 'CO' & (@#AD_User_ID@ ! 1000028 | @#AD_User_ID@ ! 100)
```

Off course under the algebraic logic (that's the logic standard in all programming languages, including Java), it shouldn't work, since the user will always be different either from the admin user or the company owner user, thus should block all users.

However it does work, which is weird (i would like to know why didn't just used the Java logic instead of making a new DSL just for logic in window items, but i'm sure you guys got a good reason to do so), the correct way to block for all users that aren't neither admin nor company owner should be this:

```java
@DocStatus@ = 'CO' & !(@#AD_User_ID@ = 1000028 & @#AD_User_ID@ = 100)
```

I would like to know why make a new logic syntax instead of using Java syntax and let Java care about evaluating the logic instead of doing it manually.

Anyway here's the class responsible of evaluating that logic: `org.compiere.util.evaluator`.

**Comment by Luchillo** [comment]
I've been digging up about this and it seems the issue might be that the evaluator doesn't support grouping statements like parenthesis, i still think this is a bug since all logic evaluation should follow the algebraic logic standard.

For the time being @jdaison and i edited the wiki and added a warning about it.

**Comment by e-Evolution** [comment]
Hi Luchillo , if you get of System Help for  Read Logic field you get:

![captura de pantalla 2016-12-26 a la s 14 54 19](https://cloud.githubusercontent.com/assets/786968/21486493/36bed678-cb7b-11e6-8de4-78d2234b398f.png)

So this is of syntax that can use now.

**Comment by Luchillo** [comment]
@e-Evolution So no grouping support EVER for adempiere logic?

**Comment by e-Evolution** [comment]
yes no grouping support only that syntax that show in image.

but I think that not are using of right approach , use the read only logic or display logic for a AD_User_ID not is the righty way.

ADempiere support define the role permission for each CRUD action based on rule.

So you not need setting this complex logic 

![captura de pantalla 2016-12-26 a la s 17 19 00](https://cloud.githubusercontent.com/assets/786968/21487483/758fbb24-cb8f-11e6-8af0-7bc303b0f29a.png)

**Comment by Luchillo** [comment]
@e-Evolution I understand the role permissions, and if it were by me it is the correct solution, however customer insists that it should only be available to the user in question (customers can be irrational some times).

Btw would you rather i speak spanish?
