### ISSUE TITLE
There is a risk that some document was marked as posted by the accounting engine and but there is no accounting fact

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#71]
There is a risk that some document was marked as posted by the accounting engine and but there is no accounting fact, this can cause an incorrect accounting information for financial statement.

The accounting reset process now validate if exist the accounting generated for a document with an accounting open period,  if not then the document is set as un posting to generate accounting

**Comment by mckayERP** [comment]
I've run into a problem with the test for open accounting periods.  When running Resubmit Posting, the reset of the accounting uses a query like the following (this for M_MatchInv):

`UPDATE M_MatchInv 
SET Posted='N' 
WHERE 
	AD_Client_ID=1000000 AND 
	(Posted NOT IN ('Y','N') 
	 OR Posted IS NULL 
	 OR NOT EXISTS (SELECT 1 
					FROM Fact_Acct fa 
					INNER JOIN C_PeriodControl pc ON (fa.C_Period_ID=pc.C_Period_ID) 
					WHERE 
						AD_Table_ID=472 
						AND Record_ID=M_MatchInv.M_MatchInv_ID 
						AND pc.PeriodStatus = 'O'  
						AND pc.DocBaseType = 'MXI' 
						AND fa.C_Period_ID=pc.C_Period_ID)
					)`

The statement OR NOT EXISTS is true for all facts in closed periods so all the accounting in closed periods is reset.  

This is not good.

The logic here needs to be reviewed as to which documents can be reposted.
