### ISSUE TITLE
[Enhancement] Multi column process parameter dialog.

### ISSUE THREAD

**Issue by ayazbaloch** [adempiere/adempiere#715]
@e-Evolution Currently Adempiere supports one column process parameter dialog, such as following image shows.

![image](https://cloud.githubusercontent.com/assets/10656336/21578601/068a6c10-cfdb-11e6-88e4-5845f2b2f0d2.png)

If Adempiere will support multi column process parameter dialog then the above screen will fit like Adempiere window and looks better.

**Comment by ayazbaloch** [comment]
@e-Evolution , Hi team members, there is no response the above mentioned suggestion. Kindly any update regard it.

**Comment by yamelsenih** [comment]
Hi @ayazbaloch it is nice to have. And is possible also. Have you a source or improvement for develop it?

Currently is more easy change the process parameter panel, i wrote some changes for improvement on source code.

Best Regard

**Comment by ayazbaloch** [comment]
Hi @yamelsenih not yet any source I have, are you working on it?
