### ISSUE TITLE
Valid to not is setting when execute import payroll movement 

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#730]

**Comment by yamelsenih** [comment]
Hi @e-Evolution, can you add a description to issue?
Please is nice if each issue have more description

**Comment by yamelsenih** [comment]
Hi @e-Evolution, i test it and it worked, see the step:
- Import Movement Window:
![arbol_59](https://cloud.githubusercontent.com/assets/2333092/26768111/7988cab0-4973-11e7-9f0d-e7772d7d5d07.png)
- Payroll Movement Window
![arbol_58](https://cloud.githubusercontent.com/assets/2333092/26768110/7904b6f8-4973-11e7-9565-eb3f696a34ee.png)
