### ISSUE TITLE
Accounting Fact Reports do not work

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere#739]
When calling the _Accounting Fact_ Reports, the result is an empty report:
![20170126_factacct_daily](https://cloud.githubusercontent.com/assets/1789408/22352766/21cb11c0-e3e3-11e6-88ed-e265cb7a1e50.png)

Besides, there is an error that column _user3_id_ does not exist in the corresponding view. 
The involved views are _rv_fact_acct_, _rv_fact_acct_day_ and _rv_fact_acct_period_.
Looking at their definition in the Application Dictionary, the columns _user3_id_ and _user4_id_ are defined. But this is missing in the database.

**Comment by e-Evolution** [comment]
Thank a lot Mario , I will fix the views

**Comment by e-Evolution** [comment]
Hi @marcalwestf Mario 

I fixed this and other views , please can testing and all are working, close this ticket

**Comment by marcalwestf** [comment]
Working. This is how it looks with the newest changes in reporting :
![20170309_fact_act](https://cloud.githubusercontent.com/assets/1789408/23763913/317eb8a2-04c1-11e7-9096-868583c5c703.png)
 (notice: when clicking on the magnifying glass, the window containing the record is opened)
