### ISSUE TITLE
Bad validation for Employee

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#751]
When a Employee is created:

- New Option.
- Add values.
- Refresh: It make lost the record.

I view the tab validation and it have the follow:
<pre>
EXISTS (SELECT 1 FROM AD_User WHERE AD_User.AD_User_ID=@#AD_User_ID@ AND AD_User.C_BPartner_ID= C_BPartner.C_BPartner_ID)
</pre>
The Employee only is possible view if it have a user like the session user...

It can be controlled from Role access

**Comment by yamelsenih** [comment]
I look a window named **"Employee All"**, it show all employee. Is necessary have two windows? 

I think that if Employee window only show **My Employee** and **Employee All** show all employee then the **Employee** window shoud be changed to **My Employee**.

**Comment by e-Evolution** [comment]
Hola Yamel 

The Employee is used to auto service fill , so that the user can filll all information about of self , the Employe all  is use to edit any data of any employee

May be we can change of name to My Employee information

**Comment by yamelsenih** [comment]
Yes I was thinking it.
I will close it. Issue.
