### ISSUE TITLE
Blood group should be a BP attribute

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#752]
The Blood Group is a attribute of business partner but it is add on employee setup instead of BP. It rounded the value by each employee setup.

![precioproducto9](https://cloud.githubusercontent.com/assets/2333092/22621944/e15f7a98-eb05-11e6-86ea-bbedde59b5e7.png)

**Comment by yamelsenih** [comment]
Also i look the follow fields that should be on **C_BPartner** table instead **HR_Employee** table:

- Birthday.
- FathersName
- BloodGroup

There columns is a attribute of **Business Partner**.

**Comment by e-Evolution** [comment]
Hi Yamel , we would to change and only show when the flag is Employee is set , in some  moment the employee is an extension of business partner , but on the other hand some this field would be defined in user entity , so that this information is more close for human resource functionality

**Comment by yamelsenih** [comment]
Hi Victor, I can be resolved add it changes in C_BPartner table instead Employee table. Also can exists on employee window and not for Business Partner window.

They are not a attribute of HR_Employee, if the problem is the visualization the it can be resolved using the employee window for show the field.

**Comment by yamelsenih** [comment]
It reference to issue: #755

**Comment by e-Evolution** [comment]
Hi Yamel , if you change this column from HR_Employee to C_BPartner then you need implement import logic for this information into I_Partner, So that this I have now in a import process employee data , but if you move then now should be imported from import business partner

**Comment by yamelsenih** [comment]
Ok, i will add it for BP import hahaha thank you

**Comment by e-Evolution** [comment]
Need be impleented setPlaceOfBirth_ID(impBP.getPlaceOfBirth_ID());

**Comment by adaxa-steven** [comment]
If place of birth is country then suggest create a view in the db of c_country where isactive is set to Y for all countries then use this'table' to validate country of birth. It avoids having every country appear when you add an address when your bp addresses will only be from 2 or 3 countries and they are the only ones you really want as active.

**Comment by yamelsenih** [comment]
Hi @adaxa-steven it is a reference to C_Location table, i test it and worked, just is need add support from import business partner
