### ISSUE TITLE
BP reference on Employee 

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#753]
On Employee Dependents just exists a Name for dependent of Employee. Exists many cases where the dependent have other attributes important for payroll like birth date, TaxID / Value.

I propose add a reference of Business Partner on Dependents with the follow attributes:

- Name: **C_BPartnerRelation_ID**
- Mandatory: **No**

**Comment by e-Evolution** [comment]
The problem about this approach is that an employee can have multiples dependents, so the relation no can one to one , currently exist a new window to management of relation called employee relation into human resource , in the other hand I added the c_bpartnerrelation_id in hr_employee and can be link with employee as attribute in multiples payroll concepts

**Comment by yamelsenih** [comment]
I show a example:
Employee Name: Peter
Dependents:

- Peter 1 (Son)
- Peter 2 (Son)
- Peter 3 (Son)

If one of dependents have a BP just need select it on dependent, the relation is other.

**Comment by e-Evolution** [comment]
Can see here

https://github.com/adempiere/adempiere/issues/716

**Comment by yamelsenih** [comment]
I add the reference like optional reference to Business Partner, you can see on the follow image:
![precioproducto15](https://cloud.githubusercontent.com/assets/2333092/22669792/a8499f0c-ec9c-11e6-84af-2c22359a0e11.png)
