### ISSUE TITLE
Constraint failed saving Insurance Detail

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#757]
I try create a Insurance Detail on **Employee** but it throw a error with a mandatory column **HR_Employee_ID**, it column should be optional, the **C_BPartner_ID** is mandatory.
![precioproducto24](https://cloud.githubusercontent.com/assets/2333092/22790163/aa8353e6-eebb-11e6-9d28-6b863ecb9bad.png)

**Comment by e-Evolution** [comment]
Hi Yamel , yes in first version of human resource data all tabs was link by HR_Employee_ID and should be link for C_BPartner_ID because a employee not change this information for each entry or leave of a company. So that we need remove the HR_Employee_ID and replace for C_BParnter_ID
