### ISSUE TITLE
Add Payroll variables for Scripts

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#761]
Currently, the payroll processing have the follow values:

- By Run:
  - **process**: MHRProcess Object
  - **_Process**: HR_Process_ID int
  - **_Period**: HR_Period_ID int
  - **_Payroll**: HR_Payroll_ID int
  - **_Department**: HR_Department_ID int
  - **_From**: StartDate (Payroll) Timestamp
  - **_To**: EndDate (Payroll) Timestamp
- By Employee run:
  - **_DateStart**: StartDate (Employee) Timestamp
  - **_DateEnd**: EndDate (Employee) Timestamp
  - **_Days**: Days between StartDate (Payroll) and EndDate (Payroll) int
  - **_C_BPartner_ID**: C_BPartner_ID int
  - **_HR_Employee_ID**: HR_Employee_ID int
- By Concept run
  - **_HR_Concept_ID**: HR_Concept_ID int
  - **_HR_Concept**: MHRConcept Object
  - **_HR_PayrollConcept_ID**:  HR_PayrollConcept_ID int

I propose the follow variables for help to user to get important values from Ctx:
- By Run:
  - **_HR_Payroll_Value**: Current Payroll Value String 
- By Employee run:
  - **_C_BPartner**: MBPartner Object
  - **_HR_Employee**: MHREmployee Object
  - **_HR_Employee_ValidFrom**: (Employee valid from): <pre>(_DateStart > _From? _DateStart: _From)</pre>
  - **_HR_Employee_ValidTo**: (Employee valid to): <pre>(_DateEnd < _To? _DateEnd: _To)</pre>
  - **_HR_Employee_Payroll_Value**: Payroll value of Employee String

**Comment by e-Evolution** [comment]
Hi @yamelsenih 

Only have a question , I worried to add _C_BPartner because the instance in memory is very big , Do you test that this change not increase the procesing  payroll time?

**Comment by yamelsenih** [comment]
Hi @e-Evolution i test it on a customer with over 400 employees and it worked nice, is better if you have the **_C_BPartner** like a object inside of Script rule engine instead of make a instance for each rule when it is necessary.

By each instance the server make a query to DB and instance a new java object.
