### ISSUE TITLE
Method getAttribute is inconsistent

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#765]
The **getAttribute** method have three distint result:

- **getAttribute**: return a double from **Amount** or **Quantity** the parameters for it is the follow:
<pre>
whereClause.append(" AND AD_Client_ID = ?");
		params.add(getAD_Client_ID());
if(payrollId > 0)
		{
			whereClause.append(" AND (HR_Payroll_ID=? OR HR_Payroll_ID IS NULL)");
			params.add(payrollId);
		}
		if(departmentId > 0)
		{
			whereClause.append(" AND (HR_Department_ID=? OR HR_Department_ID IS NULL)");
			params.add(departmentId);
		}
		if(jobId > 0)
		{
			whereClause.append(" AND (HR_Job_ID=? OR HR_Job_ID IS NULL)");
			params.add(jobId);
		}
		//check concept
		whereClause.append(" AND EXISTS (SELECT 1 FROM HR_Concept c WHERE c.HR_Concept_ID=HR_Attribute.HR_Concept_ID" 
				+ " AND c.Value = ?)");
		params.add(conceptValue);
</pre>
- **getAttributeDate**: get a Timestamp from **ServiceDate**, the parameters for it is the follow:
<pre>
whereClause.append("AD_Client_ID = ?");
		params.add(getAD_Client_ID());
		//check concept
		whereClause.append(" AND EXISTS (SELECT 1 FROM HR_Concept c WHERE c.HR_Concept_ID=HR_Attribute.HR_Concept_ID" 
				+ " AND c.Value = ?)");
		params.add(conceptValue);
</pre>
- **getAttributeString**: get a String from **TextMsg**, the parameters for it is the follow:
<pre>
		//check client
		whereClause.append("AD_Client_ID = ?");
		params.add(getAD_Client_ID());
		//check concept
		whereClause.append(" AND EXISTS (SELECT 1 FROM HR_Concept c WHERE c.HR_Concept_ID=HR_Attribute.HR_Concept_ID" 
				+ " AND c.Value = ?)");
		params.add(conceptValue);
</pre>

All method should have tha same parameters, the good is the **getAttribute**, i will add a generic method for get attributte and use it on **getAttribute**, **getAttributeDate** and **getAttributeString**

**Comment by yamelsenih** [comment]
Also exists other method from it like:

- getAttributeInvoice.
- getAttributeDocType.
- getAttributeBPartner.

**Comment by e-Evolution** [comment]
Hi @yamelsenih 

I think that best name or getAttributePO is getAttributeIntance , this way can cause confusion for PO as (Purchase Order)

**Comment by yamelsenih** [comment]
Hi @e-Evolution yes i will do.

**Comment by e-Evolution** [comment]
Hi @yamelsenih 

I think that we need change the method name from getAttributeBPartner to getAttributeByPartnerId this follow the syntax the other methods 

we would deprecate the old method

**Comment by yamelsenih** [comment]
Hi @e-Evolution i can add a new method with **getAttributeByPartnerId** name and deprecate the old method

**Comment by e-Evolution** [comment]
yes will great, thank a lot
