### ISSUE TITLE
Improve Commission Calculation

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere#766]
As of now, the calculation of sales commissions is quite limited.

In order to be accepted for operational implementation it is missing important issues like the following:
-  commission definition also for a Business Partner Group
- commission based on days elapsed between invoice and (partial) payments done
- commission based on profit margin of product
- commission depending on provider
- Include management of Material Returns and Payment voiding.
- avoiding double calculations during _Commission Calculation_ 
- integration to Human Resources/Payroll
- convert the Commission into an ADempiere document (in order to make it more secure and manageable)
- Simulation of _Commission Runs_
- an explanatory _Commission Detail_ -including the new features

Among perhaps others that may arise.

**Comment by yamelsenih** [comment]
Hi @marcalwestf i added a ER Diagram for the new changes:
The changes have the follow:

![commission](https://cloud.githubusercontent.com/assets/2333092/22975827/6f7b96da-f35e-11e6-955e-cfba3e7fc617.png)

**Comment by adaxa-steven** [comment]
Hi Mario, how do you plan to calc gross margin? We added cost to orderline so the cost which existed at the time the sales rep created the order was recorded as that seemed to be a fair basis for working out margin for commission calcs

**Comment by e-Evolution** [comment]
Hi, Mario!

I think that the commission functionality can improve a lot, so first, we need that the commission definition or rule not should be setting for the employee, this should be for any employee, so the employee not should be mandatory.

![bpnotmandatory](https://cloud.githubusercontent.com/assets/786968/23031509/d3ecaac2-f436-11e6-8609-1948a23e10ee.png)


On the other hand, other new information should be added in the domain model:

Product information
- Product Group
- Product Class
- Product Classification 

Sales Order Information 
- Camping  
- Chanel 
- Project
- Payment Term 

Invoice information 
- Collection Status 
- Dunning Level

 The Commission Run should be executed for all the employees that match with the commission rules, if you have 500 sales representant not is useful have 500 Commission Run, so we should add new tab between commission run and commission amount for each employee have your our calculated.

![commission run add sales rep tab](https://cloud.githubusercontent.com/assets/786968/23031603/39fd50c8-f437-11e6-8dd7-8c37cc9bed66.png)

**Comment by marcalwestf** [comment]
@adaxa-steven this is an interesting approach which I must confess I hadn't considered.
I had in mind just the cost calculation at the time of commission calculation, but thinking about your comment, it seems more "realistic" to take the cost at the time of the order. 

I think this can be implemented.

**Comment by e-Evolution** [comment]
@marcalwestf  in ADempiere can get invoice margin report based on the result the Price List subtract Price Limit , So we would use the same approach to commissions.
