### ISSUE TITLE
¿Server tomcat slow?

### ISSUE THREAD

**Issue by erprafaelrodriguez** [adempiere/adempiere#787]
Hi Team! 

Congratulations for the fantastic project.

I have installed and working Adempiere 3.9.0 in a company whit 80 users concurrents. All is Excellent but whit frequently my server tomcat apparently is locked because is slow... Reviewing my Droplet DB server and Aplications the graphics are noot fired. 

¿Somebody has any experience similary to mine?

**Comment by marcalwestf** [comment]
@erprafaelrodriguez any hints how to reproduce it or what it causes these symptoms?

**Comment by yamelsenih** [comment]
It was not reply
