### ISSUE TITLE
The Calculate Replenish Plan process not support SQL99

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#789]
This new class have multiples SQL sentences that only support for a specific database (PostgreSQL).

ADempiere have a strict support for postgresql and oracle.

So is necessary migrate SQL sentence to support SQL99 and ADempiere functions

https://raw.githubusercontent.com/adempiere/adempiere/hotfix/3.8.0%23002/org.adempiere.production/src/main/java/base/org/adempiere/process/CalculateReplenishPlan.java

**Comment by adaxa-steven** [comment]
Hi Victor, we have a problem here because we abandoned support for Oracle years ago and only ever use Postgres.  Is there an Oracle user out there who is interested to assist with this task?

**Comment by marcalwestf** [comment]
@jdaison can you see if you can detect the places not compliant with SQL99 and put forward a  suggestion?

**Comment by adaxa-steven** [comment]
in the seed db that Mario created I can not run an accounting fact detail report ... it complains about user3 and user4

**Comment by pasiniruffoni** [comment]
I suggest to move to 3.9.1. also

**Comment by marcalwestf** [comment]
Hi, 
@sramazzina said he would take care of testing in Oracle.

Here the instructions I got from Victor and Yamel this regardiing:
Mario install oracle in linux is very simple, please execute next step:

1.- install docker https://docs.docker.com/engine/installation/linux/suse/  (or your OS)
2.- docker pull wnameless/oracle-xe-11g
3.- docker run -d -p 49160:22 -p 49161:1521 wnameless/oracle-xe-11g
see more detail : https://hub.docker.com/r/wnameless/oracle-xe-11g/

See also https://github.com/adempiere/adempiere-docker/tree/master/old/dockerizing-adempiere-oracle

**Comment by sramazzina** [comment]
@marcalwestf, @sramazzina said he will take care about the provision of the docker container with Oracle ;-). In the meanwhile, as @pasiniruffoni correctly said we agreed to move it to 3.9.1.

**Comment by yamelsenih** [comment]
Hi @all i will review it now

**Comment by marcalwestf** [comment]
Tested the code
1.- Java 8-compatible (uses extensively Lambda expressions)
2.- Got rid of Postgres-only notations
3.- Re-arranged Queries

Still to do (please , do take this as a comment, it has nothing to do with this issue)
1.- in window _Replenish Plan Run_ do set the fields _Date start_ and _Finish date_ as mandatory.
Otherwise, error when _Replensih Plan Report_ is executed.
2.- In _Replensih Plan Report_ do add Warehouse as an additional parameter. The process asks for it.
