### ISSUE TITLE
When the improved of Light Production was integrated, the Stocktake functionality not found

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#790]
![Swing and ZK form lost](https://cloud.githubusercontent.com/assets/786968/23369787/205406ae-fcd8-11e6-96dc-e8a5aba7f002.png)

https://github.com/adempiere/adempiere/blob/hotfix/3.8.0%23002/migration/380lts-release/00540_703_Stocktake_Part3.xml#L1036

org.compiere.apps.form.VStocktake

On the other hand I can now now new functionality but not found some new functionality core model 

![captura de pantalla 2017-02-27 a la s 10 33 50](https://cloud.githubusercontent.com/assets/786968/23481756/35c7ae44-fe92-11e6-974e-9c802f9d4cd5.png)

I saw that new columns was added Quantity Count and Pick Qty , but not found any change for MInventoryLine for this new columns

**Comment by JobrianTrinidad** [comment]
Hi Victor,

There are no columns added in the model. But instead, updated directly using an update script. As shown below (located in UpdateQuantityCount.java)

		//	Update Quantity Count
		String sql1 = "UPDATE M_InventoryLine l "
			+ "SET QtyCount=COALESCE(SecondCountQty,FirstCountQty) + PickedQty "
			+ "WHERE M_Inventory_ID=" + p_M_Inventory_ID;
		int no = DB.executeUpdate(sql1, get_TrxName());
		log.info("Update Quantity Count #" + no);

**Comment by e-Evolution** [comment]
@JobrianTrinidad where we can get of UpdateQuantityCount.java source code?

**Comment by marcalwestf** [comment]
I have found this class in the adaxa repo. I will include it in the adempiere demo.

**Comment by JobrianTrinidad** [comment]
@e-Evolution 
It's currently in our repository revision#9247 Stocktake entry form. Thanks to tspc

**Comment by e-Evolution** [comment]
@marcalwestf , It think that this source code not was included in integration , can please add

**Comment by marcalwestf** [comment]
waiting for test

**Comment by marcalwestf** [comment]
After the last commit, this is how it looks in Swing:
![20170303_stocktake](https://cloud.githubusercontent.com/assets/1789408/23572069/3e6af9ce-0032-11e7-96ba-a2fe0be8ae9e.png)

**Comment by marcalwestf** [comment]
this is how it looks in ZK
![20170306_adaxa_01](https://cloud.githubusercontent.com/assets/1789408/23634037/df96d720-028d-11e7-95d3-501f1b28011f.png)

**Comment by yamelsenih** [comment]
It return a error with ZK:

<pre>
===========> zkoss.handleError:1130: >>java.lang.NullPointerException
>>	at org.adempiere.webui.component.GridPanel.onEvent(GridPanel.java:389)
>>	at org.zkoss.zk.ui.impl.EventProcessor.process0(EventProcessor.java:197)
>>	at org.zkoss.zk.ui.impl.EventProcessor.process(EventProcessor.java:141)
>>	at org.zkoss.zk.ui.impl.EventProcessingThreadImpl.process0(EventProcessingThreadImpl.java:519)
>>	at org.zkoss.zk.ui.impl.EventProcessingThreadImpl.sendEvent(EventProcessingThreadImpl.java:123)
>>	at org.zkoss.zk.ui.event.Events.sendEvent(Events.java:293)
>>... [32]
</pre>

**Comment by yamelsenih** [comment]
I fixed a NPE on ZK WebUI.

I test and is OK.

Is nice if the functionality like change values directly on grid can be added to Smart Browse
