### ISSUE TITLE
The XML Script not is compatible with SQL 99 00540_703_Stocktake_Part3.xml

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#791]
The script using CURRENT_TIMESTAMP and TO_TIMESTAMP('2013-09-23 11:54:41','YYYY-MM-DD HH24:MI:SS') that is only support for PostgreSQL 

This script should support the script for Oracle and PostgreSQL, the Migration Step can be set this way 

https://github.com/adempiere/adempiere/blob/hotfix/3.8.0%23002/migration/380lts-release/00540_703_Stocktake_Part3.xml#L1084

![captura de pantalla 2017-03-01 a la s 15 45 22](https://cloud.githubusercontent.com/assets/786968/23482850/2080beb4-fe96-11e6-8dc3-894d67d3e9a8.png)

**Comment by marcalwestf** [comment]
@e-Evolution 
1.- is the CURRENT_TIMESTAMP the only SQL99-incompatible item or are others?
2,- what should be the correct statement?

**Comment by e-Evolution** [comment]
Mario of CURRENT_TIMESTAMP or NOW should replace for get date() function that is part of adempiere.

About of TO_TIMESTAMP('2013-09-23 11:54:41','YYYY-MM-DD HH24:MI:SS') should be use to postgresql 
and should be use to oracle TO_DATE('2011-07-27 15:13:48','YYYY-MM-DD HH24:MI:SS')

You can see the old migration script into of migration project directory

**Comment by SusanneCalderon** [comment]
waiting for test

**Comment by e-Evolution** [comment]
Error in migration:

18:56:26.661   MMigrationStep.apply: Applying migration step: Migration 540 - Stocktake - Part3 - 3.9.0 (D) ; Step: 320; Type: SQL.  [1]
===========> MMigrationStep.applySQL: Migration 540 - Stocktake - Part3 - 3.9.0 (D) ; Step: 320; Type: SQL.  Application failed. org.postgresql.util.PSQLException: ERROR: column "sysdate" does not exist
  Position: 58
java.sql.BatchUpdateException: Batch entry 0 UPDATE AD_TreeNodeMM SET Parent_ID=183, SeqNo=0, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=167 was aborted.  Call getNextException to see the cause. [1]
18:56:26.671   MIssue.create: Migration 540 - Stocktake - Part3 - 3.9.0 (D) ; Step: 320; Type: SQL.  Application failed. org.postgresql.util.PSQLException: ERROR: column "sysdate" does not exist
  Position: 58
java.sql.BatchUpdateException: Batch entry 0 UPDATE AD_TreeNodeMM SET Parent_ID=183, SeqNo=0, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=167 was aborted.  Call getNextException to see the cause. [1]
18:56:26.671   MIssue.create: Migration 540 - Stocktake - Part3 - 3.9.0 (D) ; Step: 320; Type: SQL.  Application failed. org.postgresql.util.PSQLException: ERROR: column "sysdate" does not exist
  Position: 58
java.sql.BatchUpdateException: Batch entry 0 UPDATE AD_TreeNodeMM SET Parent_ID=183, SeqNo=0, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=167 was aborted.  Call getNextException to see the cause. [1]
18:56:26.680   GridField.loadLookup: (SystemStatus) [1]
18:56:26.680   GridField.loadLookup: (SystemStatus) [1]
===========> MMigrationStep.applySQL: Migration 540 - Stocktake - Part3 - 3.9.0 (D) ; Step: 320; Type: SQL.  Application failed. org.postgresql.util.PSQLException: ERROR: column "sysdate" does not exist
  Position: 58
java.sql.BatchUpdateException: Batch entry 0 UPDATE AD_TreeNodeMM SET Parent_ID=183, SeqNo=0, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=167 was aborted.  Call getNextException to see the cause. [1]
-----------> MMigration.apply: Migration 540 - Stocktake - Part3 - 3.9.0 (D) ; Step: 320; Type: SQL.  Application failed. org.postgresql.util.PSQLException: ERROR: column "sysdate" does not exist
  Position: 58
java.sql.BatchUpdateException: Batch entry 0 UPDATE AD_TreeNodeMM SET Parent_ID=183, SeqNo=0, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=167 was aborted.  Call getNextException to see the cause. [1]
-----------> MMigration.apply: Migration 540 - Stocktake - Part3 - 3.9.0 (D) ; Step: 320; Type: SQL.  Application failed. org.postgresql.util.PSQLException: ERROR: column "sysdate" does not exist
  Position: 58
java.sql.BatchUpdateException: Batch entry 0 UPDATE AD_TreeNodeMM SET Parent_ID=183, SeqNo=0, Updated=SysDate WHERE AD_Tree_ID=10 AND Node_ID=167 was aborted.  Call getNextException to see the cause. [1]
18:56:31.838   MMigration.apply: Migration 540 - Stocktake - Part3 - 3.9.0 (D) ; Step: 370; Type: AD.  ---> Migration Step unapplied - skipping. [1]

**Comment by yamelsenih** [comment]
It is applied and is ok in oracle
