### ISSUE TITLE
Script no is compatible 00510_690_Manufacturing_light_fixes.xml only implement function for PostgreSQL

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#792]
Is necessary to implement the new function to oracle database 

https://github.com/adempiere/adempiere/blob/hotfix/3.8.0%23002/migration/380lts-release/00510_690_Manufacturing_light_fixes.xml#L5

**Comment by e-Evolution** [comment]
Any new function added to protect should be include in path ADempiere/adempiere/db/ddlutils/postgresql/functions and ADempiere/adempiere/db/ddlutils/oracle/functions


![captura de pantalla 2017-03-01 a la s 15 52 41](https://cloud.githubusercontent.com/assets/786968/23483103/247141a0-fe97-11e6-86d7-3095f62dc043.png)

**Comment by marcalwestf** [comment]
@SusanneCalderon will see in ddutils the differences from Oracle to Postgres and create an XML with the  new definitions. Then she will also create an entry in dduutils.

**Comment by SusanneCalderon** [comment]
Waiting for testing

**Comment by e-Evolution** [comment]
===========> MMigrationStep.applySQL: Migration 510 - Manufacturing light fixes - 3.9.0 (D) ; Step: 10; Type: SQL.  Application failed. org.postgresql.util.PSQLException: ERROR: unterminated dollar-quoted string at or near "$BODY$
DECLARE
	v_Warehouse_ID			numeric"
  Position: 110
java.sql.BatchUpdateException: Batch entry 0 CREATE OR REPLACE FUNCTION prodqtyordered(p_product_id numeric, p_warehouse_id numeric)
  RETURNS numeric AS
$BODY$
DECLARE
	v_Warehouse_ID			numeric was aborted.  Call getNextException to see the cause. [1]
18:09:26.459   MIssue.create: Migration 510 - Manufacturing light fixes - 3.9.0 (D) ; Step: 10; Type: SQL.  Application failed. org.postgresql.util.PSQLException: ERROR: unterminated dollar-quoted string at or near "$BODY$
DECLARE
	v_Warehouse_ID			numeric"
  Position: 110
java.sql.BatchUpdateException: Batch entry 0 CREATE OR REPLACE FUNCTION prodqtyordered(p_product_id numeric, p_warehouse_id numeric)
  RETURNS numeric AS
$BODY$
DECLARE
	v_Warehouse_ID			numeric was aborted.  Call getNextException to see the cause. [1]
18:09:26.459   MIssue.create: Migration 510 - Manufacturing light fixes - 3.9.0 (D) ; Step: 10; Type: SQL.  Application failed. org.postgresql.util.PSQLException: ERROR: unterminated dollar-quoted string at or near "$BODY$
DECLARE
	v_Warehouse_ID			numeric"
  Position: 110
java.sql.BatchUpdateException: Batch entry 0 CREATE OR REPLACE FUNCTION prodqtyordered(p_product_id numeric, p_warehouse_id numeric)
  RETURNS numeric AS
$BODY$
DECLARE
	v_Warehouse_ID			numeric was aborted.  Call getNextException to see the cause. [1]
18:09:26.459   GridField.loadLookup: (SystemStatus) [1]
18:09:26.459   GridField.loadLookup: (SystemStatus) [1]
===========> MMigrationStep.applySQL: Migration 510 - Manufacturing light fixes - 3.9.0 (D) ; Step: 10; Type: SQL.  Application failed. org.postgresql.util.PSQLException: ERROR: unterminated dollar-quoted string at or near "$BODY$
DECLARE
	v_Warehouse_ID			numeric"
  Position: 110
java.sql.BatchUpdateException: Batch entry 0 CREATE OR REPLACE FUNCTION prodqtyordered(p_product_id numeric, p_warehouse_id numeric)
  RETURNS numeric AS
$BODY$
DECLARE
	v_Warehouse_ID			numeric was aborted.  Call getNextException to see the cause. [1]
-----------> MMigration.apply: Migration 510 - Manufacturing light fixes - 3.9.0 (D) ; Step: 10; Type: SQL.  Application failed. org.postgresql.util.PSQLException: ERROR: unterminated dollar-quoted string at or near "$BODY$
DECLARE
	v_Warehouse_ID			numeric"
  Position: 110
java.sql.BatchUpdateException: Batch entry 0 CREATE OR REPLACE FUNCTION prodqtyordered(p_product_id numeric, p_warehouse_id numeric)
  RETURNS numeric AS
$BODY$
DECLARE
	v_Warehouse_ID			numeric was aborted.  Call getNextException to see the cause. [1]
-----------> MMigration.apply: Migration 510 - Manufacturing light fixes - 3.9.0 (D) ; Step: 10; Type: SQL.  Application failed. org.postgresql.util.PSQLException: ERROR: unterminated dollar-quoted string at or near "$BODY$
DECLARE
	v_Warehouse_ID			numeric"
  Position: 110
java.sql.BatchUpdateException: Batch entry 0 CREATE OR REPLACE FUNCTION prodqtyordered(p_product_id numeric, p_warehouse_id numeric)
  RETURNS numeric AS
$BODY$
DECLARE
	v_Warehouse_ID			numeric was aborted.  Call getNextException to see the cause. [1]
18:09:31.602   MMigration.apply: Migration 510 - Manufacturing light fixes - 3.9.0 (D) ; Step: 1860; Type: AD.  ---> Migration Step unapplied - skipping. [1]

Error when try apply of script

**Comment by yamelsenih** [comment]
Hi i find a error here while compile function

**Comment by yamelsenih** [comment]
i test it and is ok

**Comment by yamelsenih** [comment]
Hi @e-Evolution exist a bug?

**Comment by yamelsenih** [comment]
Hi @e-Evolution i change it and remove schema prefix

**Comment by yamelsenih** [comment]
Please if exist a bug is good add description here
