### ISSUE TITLE
Script not is compatible 00600_4040_#830_MiniMRP_Run_DisplayedGrid only include postgresql support

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#793]
Script XML Line 

https://github.com/adempiere/adempiere/blob/hotfix/3.8.0%23002/migration/380lts-release/00600_4040_%23830_MiniMRP_Run_DisplayedGrid.xml#L213

**Comment by marcalwestf** [comment]
@e-Evolution what is the exact error? 
Is this an issue of SQL99 incompatibility or the constraint has to be in Postgres and in Oracle ?

**Comment by e-Evolution** [comment]
Mario that not exist of implementation for Oracle only support postgresql

ALTER TABLE M_ReplenishPlanLine
  ADD CONSTRAINT M_ReplenishPlan_M_ReplenishPlanLine FOREIGN KEY (M_ReplenishPlan_ID)
      REFERENCES M_ReplenishPlan (M_ReplenishPlan_ID) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

We need of same for oracle, I not sure if is same sentences , here you can see oracle syntax's 
https://www.techonthenet.com/oracle/foreign_keys/foreign_keys.php

**Comment by SusanneCalderon** [comment]
waiting for test

**Comment by yamelsenih** [comment]
It is ok
