### ISSUE TITLE
The  script  00690_5040_#830_Requisition_and_Production_Report_on_MiniMRP.xml create view  internally, but not create in directory views for project

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#794]
Is necessary create the view sql for rv_m_replenishplan_production in stock view to project adempiere/db/ddlutils/oracle/views and adempiere/db/ddlutils/postgresql/views

**Comment by marcalwestf** [comment]
@e-Evolution I will do it.

**Comment by marcalwestf** [comment]
there are actually two views:
rv_m_replenishplan_production
rv_m_replenishplan_requisition

**Comment by marcalwestf** [comment]
rv_m_replenishplan_production and rv_m_replenishplan_requisition are already in  /db/ddlutils/postgresql/views .
They have to be converted to Oracle and stored also in /db/ddlutils/oracle/views

**Comment by marcalwestf** [comment]
they are also defined in  /db/ddlutils/oracle/views !

**Comment by marcalwestf** [comment]
Waiting for test

**Comment by yamelsenih** [comment]
I view it and already exist in oracle
