### ISSUE TITLE
XML Script 00770_5170_rv_minimrp_requisition_update.xml incompatible and not create views directory 

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#795]
Only exist of support for PostgreSQL

https://github.com/adempiere/adempiere/blob/hotfix/3.8.0%23002/migration/380lts-release/00770_5170_rv_minimrp_requisition_update.xml#L55

And the views not was create in projects views directory

**Comment by marcalwestf** [comment]
@e-Evolution I will do it

**Comment by marcalwestf** [comment]
waiting for test

**Comment by yamelsenih** [comment]
It already exist in oracle
