### ISSUE TITLE
The script create a new view 00840_5240_RV_productionline2.xml not found update into project views directory

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#796]
https://github.com/adempiere/adempiere/blob/hotfix/3.8.0%23002/migration/380lts-release/00840_5240_RV_productionline2.xml#L109

**Comment by marcalwestf** [comment]
@e-Evolution I will do it

**Comment by SusanneCalderon** [comment]
waiting for test

**Comment by yamelsenih** [comment]
It already exist on oracle
