### ISSUE TITLE
The Script 00940_5550_MRPRun_Enhancements.xml not update project directory views

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#797]

**Comment by e-Evolution** [comment]
https://github.com/adempiere/adempiere/blob/hotfix/3.8.0%23002/migration/380lts-release/00940_5550_MRPRun_Enhancements.xml#L372

**Comment by marcalwestf** [comment]
@e-Evolution I will do it

**Comment by marcalwestf** [comment]
Relates to https://github.com/adempiere/adempiere/issues/794
Solved with https://github.com/adempiere/adempiere/commit/6bfe9ab27ab9eca36ab8b7d730629d3c0f8ac62e

**Comment by marcalwestf** [comment]
waiting for test

**Comment by yamelsenih** [comment]
I test it and exist for oracle
