### ISSUE TITLE
Script XML 01740_SB_ShipmentCreateFromOrderline.xml is not compatible and not include into directory views 

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#798]
Only support PostgreSQL

https://github.com/adempiere/adempiere/blob/hotfix/3.8.0%23002/migration/380lts-release/01740_SB_ShipmentCreateFromOrderline.xml#L4

**Comment by yamelsenih** [comment]
I test it and the vie already exists in oracle
