### ISSUE TITLE
the View RV_CopyProcess_Para created in 00131_Process_Param_Create.xml not found project directory views

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#800]

**Comment by yamelsenih** [comment]
Hi @e-Evolution it can be generated from Database structure, i thik that just need create a SQLfor generate it and is OK.
I propose:
- Create a SQL for get View and function structure from Seed.
- Run the query and convert it on files by vews or functions.
- Add the files to view directory.
