### ISSUE TITLE
the view RV_InOut_CreateFrom create in 00155_327_CreateFrom_Like_SB.xml not found into project views

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#801]
The original C_Payment_v view not was update into project views

adempiere/db/ddlutils/postgresql/views/C_PAYMENT_V.sql
adempiere/db/ddlutils/oracle/views/C_PAYMENT_V.sql

**Comment by yamelsenih** [comment]
Hi @e-Evolution it can be generated from Database structure, i thik that just need create a SQLfor generate it and is OK.
I propose:
- Create a SQL for get View and function structure from Seed.
- Run the query and convert it on files by vews or functions.
- Add the files to view directory.

**Comment by e-Evolution** [comment]
Hi @yamelsenih , any improve is welcome, the big problem to this approach is that when you get the views from database this are get on native DDL to Database.

We can see here  the original view based in a SQL99 standard:


CREATE OR REPLACE VIEW RV_C_INVOICE_DAY
(AD_CLIENT_ID, AD_ORG_ID, SALESREP_ID, DATEINVOICED, LINENETAMT, 
 LINELISTAMT, LINELIMITAMT, LINEDISCOUNTAMT, LINEDISCOUNT, LINEOVERLIMITAMT, 
 LINEOVERLIMIT, ISSOTRX)
AS 
SELECT AD_Client_ID, AD_Org_ID, SalesRep_ID,
	firstOf(DateInvoiced, 'DD') AS DateInvoiced,	--	DD Day, DY Week, MM Month
	SUM(LineNetAmt) AS LineNetAmt,
	SUM(LineListAmt) AS LineListAmt,
	SUM(LineLimitAmt) AS LineLimitAmt,
	SUM(LineDiscountAmt) AS LineDiscountAmt,
	CASE WHEN SUM(LineListAmt)=0 THEN 0 ELSE
	  ROUND((SUM(LineListAmt)-SUM(LineNetAmt))/SUM(LineListAmt)*100,2) END AS LineDiscount,
	SUM(LineOverLimitAmt) AS LineOverLimitAmt,
	CASE WHEN SUM(LineNetAmt)=0 THEN 0 ELSE
	  100-ROUND((SUM(LineNetAmt)-SUM(LineOverLimitAmt))/SUM(LineNetAmt)*100,2) END AS LineOverLimit,
    IsSOTrx
FROM RV_C_InvoiceLine
GROUP BY AD_Client_ID, AD_Org_ID, SalesRep_ID,
	firstOf(DateInvoiced, 'DD'), IsSOTrx;

But when get directly from PotgreSQL , I got : 

-- View: adempiere.rv_c_invoice_day

-- DROP VIEW adempiere.rv_c_invoice_day;

CREATE OR REPLACE VIEW adempiere.rv_c_invoice_day AS
 SELECT rv_c_invoiceline.ad_client_id,
    rv_c_invoiceline.ad_org_id,
    rv_c_invoiceline.salesrep_id,
    firstof(rv_c_invoiceline.dateinvoiced::timestamp with time zone, 'DD'::character varying) AS dateinvoiced,
    sum(rv_c_invoiceline.linenetamt) AS linenetamt,
    sum(rv_c_invoiceline.linelistamt) AS linelistamt,
    sum(rv_c_invoiceline.linelimitamt) AS linelimitamt,
    sum(rv_c_invoiceline.linediscountamt) AS linediscountamt,
        CASE
            WHEN sum(rv_c_invoiceline.linelistamt) = 0::numeric THEN 0::numeric
            ELSE round((sum(rv_c_invoiceline.linelistamt) - sum(rv_c_invoiceline.linenetamt)) / sum(rv_c_invoiceline.linelistamt) * 100::numeric, 2)
        END AS linediscount,
    sum(rv_c_invoiceline.lineoverlimitamt) AS lineoverlimitamt,
        CASE
            WHEN sum(rv_c_invoiceline.linenetamt) = 0::numeric THEN 0::numeric
            ELSE 100::numeric - round((sum(rv_c_invoiceline.linenetamt) - sum(rv_c_invoiceline.lineoverlimitamt)) / sum(rv_c_invoiceline.linenetamt) * 100::numeric, 2)
        END AS lineoverlimit,
    rv_c_invoiceline.issotrx
   FROM rv_c_invoiceline
  GROUP BY rv_c_invoiceline.ad_client_id, rv_c_invoiceline.ad_org_id, rv_c_invoiceline.salesrep_id, (firstof(rv_c_invoiceline.dateinvoiced::timestamp with time zone, 'DD'::character varying)), rv_c_invoiceline.issotrx;

ALTER TABLE adempiere.rv_c_invoice_day
    OWNER TO adempiere;

we can see the SQL sentence have a lot of different because Postgres transform to native DDL.

Other problem that when you get the views from database this are tied to scheme.

Since the birth of ADempiere, we have had an inventory of all the views for the databases supported by ADempiere, I think we should not change this practice.

this allowed migrated of Oracle to Postgresql easily so that was written in standard SQL99.

The same could be used in the future to support a new database like Maria DB.
