### ISSUE TITLE
User3 and User4 cause errors in rv_factacct

### ISSUE THREAD

**Issue by adaxa-steven** [adempiere/adempiere#805]
in the seed db that Mario created 3 March  I can not run an accounting fact detail report ... it complains about user3 and user4

**Comment by adaxa-steven** [comment]
in the Fin Report Writer Line - Report Line Set > Report Line > Report Source  .... select Combination.
should be able to select User 1 2 3 4,  User Element 1 2   .... but not displayed.

**Comment by e-Evolution** [comment]
Hi @adaxa-steven I think that seed of @marcalwestf not is complete, this issue was solve here

https://github.com/adempiere/adempiere/issues/739

**Comment by e-Evolution** [comment]
@marcalwestf can please check if this issue was solve in #739

**Comment by marcalwestf** [comment]
Also, running the _Trial Balance_ report, the following error message is thrown:
### **===========> DataEngine.loadPrintData: null - ERROR: column t_trialbalance.user4_id does not exist**

In the Application Directory, _t_trialbalance_ is defined as a View (!), whereas in the  database is is defined as a table. 
Also, in the Application Dictionary the column _user4_id_ is defined, but not in the database.

This means, the following has to be done
1.  _t_trialbalance_ has to be defined as a table in the Application Diccionary
2. _user4_id_ has to be defined in the database

**Comment by marcalwestf** [comment]
I found the error: in xml migration file **00430_665_Add_New_User_Account_Dimensions.xml** , there is only the definition for _User3_ID_ in line 8315:
`ALTER TABLE T_TrialBalance ADD COLUMN User3_ID NUMERIC(10) DEFAULT NULL `

The definition for _User4_ID_ is missing: 
**`ALTER TABLE T_TrialBalance ADD COLUMN User4_ID NUMERIC(10) DEFAULT NULL `**

**Comment by e-Evolution** [comment]
was solve when t_trialbalance set as table vs view
