### ISSUE TITLE
Currently migration xml not is generated

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#81]
Currently migration xml not is generated

**Comment by mckayERP** [comment]
Hi Victor, Can you elaborate on this issue?  It seems to be working well for me.

**Comment by e-Evolution** [comment]
Hi Mike the problem is that not generate entry step for transaction definition for example Spanish or other language that not is english

**Comment by liosc** [comment]
Hi @e-Evolution,
this issue is open since more than a year ago. There are commits. Is the problem solved or we need to do some test?

**Comment by e-Evolution** [comment]
solve with #440
