### ISSUE TITLE
The view shw_Orderline_Storage not implement the Adempiere Business Practice 

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#821]
Error introducing here https://github.com/adempiere/adempiere/issues/760

**Comment by e-Evolution** [comment]
The standard prefix to table should be use RV_

![captura de pantalla 2017-03-15 a la s 13 22 12](https://cloud.githubusercontent.com/assets/786968/23966988/e883a07e-0982-11e7-9c12-0889d924d9a4.png)

Not should use other column that not exist as element , if is necessary create new element then need use the standard element names.

![captura de pantalla 2017-03-15 a la s 13 26 19](https://cloud.githubusercontent.com/assets/786968/23967012/039904da-0983-11e7-8a3f-15226f2cb3ec.png)

**Comment by e-Evolution** [comment]
Error introducing in Reference to issue https://github.com/adempiere/adempiere/issues/760
The view should be with prefix in UPPER CASE

![captura de pantalla 2017-03-15 a la s 13 32 57](https://cloud.githubusercontent.com/assets/786968/23967322/0feeb864-0984-11e7-9609-61ddce7493ca.png)

The create new element need use the ADempiere Best Practice.

![captura de pantalla 2017-03-15 a la s 13 33 06](https://cloud.githubusercontent.com/assets/786968/23967324/11b7c5fa-0984-11e7-9021-32762987e0cc.png)

**Comment by yamelsenih** [comment]
I test it and now is **RV_OrderLine_Storage**.
