### ISSUE TITLE
Oracle Migration 600 - ReplenishPlan_DisplayedGrid - 3.9.0 (D) ; Step: 430; Type: SQL.  Application failed. 

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#829]
00:49:27.901   MMigrationStep.apply: Applying migration step: Migration 600 - ReplenishPlan_DisplayedGrid - 3.9.0 (D) ; Step: 430; Type: SQL.  [1]
===========> MMigrationStep.applySQL: Migration 600 - ReplenishPlan_DisplayedGrid - 3.9.0 (D) ; Step: 430; Type: SQL.  Application failed. 
java.sql.BatchUpdateException: se ha producido un error durante el procesamiento por lotes: ORA-00972: identifier is too long
 [1]
00:49:27.908   MIssue.create: Migration 600 - ReplenishPlan_DisplayedGrid - 3.9.0 (D) ; Step: 430; Type: SQL.  Application failed. 
java.sql.BatchUpdateException: se ha producido un error durante el procesamiento por lotes: ORA-00972: identifier is too long
 [1]
00:49:27.908   MIssue.create: Migration 600 - ReplenishPlan_DisplayedGrid - 3.9.0 (D) ; Step: 430; Type: SQL.  Application failed. 
java.sql.BatchUpdateException: se ha producido un error durante el procesamiento por lotes: ORA-00972: identifier is too long
 [1]
00:49:27.916   GridField.loadLookup: (SystemStatus) [1]
00:49:27.916   GridField.loadLookup: (SystemStatus) [1]
===========> MMigrationStep.applySQL: Migration 600 - ReplenishPlan_DisplayedGrid - 3.9.0 (D) ; Step: 430; Type: SQL.  Application failed. 
java.sql.BatchUpdateException: se ha producido un error durante el procesamiento por lotes: ORA-00972: identifier is too long
 [1]
-----------> MMigration.apply: Migration 600 - ReplenishPlan_DisplayedGrid - 3.9.0 (D) ; Step: 430; Type: SQL.  Application failed. 
java.sql.BatchUpdateException: se ha producido un error durante el procesamiento por lotes: ORA-00972: identifier is too long
 [1]
-----------> MMigration.apply: Migration 600 - ReplenishPlan_DisplayedGrid - 3.9.0 (D) ; Step: 430; Type: SQL.  Application failed. 
java.sql.BatchUpdateException: se ha producido un error durante el procesamiento por lotes: ORA-00972: identifier is too long
 [1]
00:49:33.032   MMigrationStep.apply: Applying migration step: Migration 600 - ReplenishPlan_DisplayedGrid - 3.9.0 (D) ; Step: 430; Type: SQL.  [1]
00:49:33.032   MMigrationStep.apply: Applying migration step: Migration 600 - ReplenishPlan_DisplayedGrid - 3.9.0 (D) ; Step: 430; Type: SQL.  [1]
===========> MMigrationStep.applySQL: Migration 600 - ReplenishPlan_DisplayedGrid - 3.9.0 (D) ; Step: 430; Type: SQL.  Application failed. 
java.sql.BatchUpdateException: se ha producido un error durante el procesamiento por lotes: ORA-00972: identifier is too long
 [1]
00:49:33.036   MIssue.create: Migration 600 - ReplenishPlan_DisplayedGrid - 3.9.0 (D) ; Step: 430; Type: SQL.  Application failed. 
java.sql.BatchUpdateException: se ha producido un error durante el procesamiento por lotes: ORA-00972: identifier is too long
 [1]
00:49:33.036   MIssue.create: Migration 600 - ReplenishPlan_DisplayedGrid - 3.9.0 (D) ; Step: 430; Type: SQL.  Application failed. 
java.sql.BatchUpdateException: se ha producido un error durante el procesamiento por lotes: ORA-00972: identifier is too long
 [1]
00:49:33.037   GridField.loadLookup: (SystemStatus) [1]
00:49:33.037   GridField.loadLookup: (SystemStatus) [1]
===========> MMigrationStep.applySQL: Migration 600 - ReplenishPlan_DisplayedGrid - 3.9.0 (D) ; Step: 430; Type: SQL.  Application failed. 
java.sql.BatchUpdateException: se ha producido un error durante el procesamiento por lotes: ORA-00972: identifier is too long
 [1]
-----------> MMigration.apply: Migration 600 - ReplenishPlan_DisplayedGrid - 3.9.0 (D) ; Step: 430; Type: SQL.  Application failed. 
java.sql.BatchUpdateException: se ha producido un error durante el procesamiento por lotes: ORA-00972: identifier is too long
 [1]
-----------> MMigration.apply: Migration 600 - ReplenishPlan_DisplayedGrid - 3.9.0 (D) ; Step: 430; Type: SQL.  Application failed. 
java.sql.BatchUpdateException: se ha producido un error durante el procesamiento por lotes: ORA-00972: identifier is too long
 [1]
00:49:38.078   MMigration.updateStatus: Migration 600 - ReplenishPlan_DisplayedGrid - 3.9.0 (D)  ---> Partially Applied (P) [1]
00:49:38.078   MMigration.updateStatus: Migration 600 - ReplenishPlan_DisplayedGrid - 3.9.0 (D)  ---> Partially Applied (P) [1]
00:49:38.085   MMigration.updateStatus: Migration 600 - ReplenishPlan_DisplayedGrid - 3.9.0 (D)  ---> Partially Applied (P) [1]
00:49:38.085   MMigration.updateStatus: Migration 600 - ReplenishPlan_DisplayedGrid - 3.9.0 (D)  ---> Partially Applied (P) [1]
00:49:38.085 MigrationApply.addLog: 0 - null - null - Migration 600 - ReplenishPlan_DisplayedGrid - 3.9.0 (D) ; Step: 430; Type: SQL.  Application failed. 
java.sql.BatchUpdateException: se ha producido un error durante el procesamiento por lotes: ORA-00972: identifier is too long
 [1]
00:49:38.085 MigrationApply.addLog: 0 - null - null - Migration 600 - ReplenishPlan_DisplayedGrid - 3.9.0 (D) ; Step: 430; Type: SQL.  Application failed. 
java.sql.BatchUpdateException: se ha producido un error durante el procesamiento por lotes: ORA-00972: identifier is too long
 [1]
===========> MigrationApply.process: Migration 600 - ReplenishPlan_DisplayedGrid - 3.9.0 (D) ; Step: 430; Type: SQL.  Application failed. 
java.sql.BatchUpdateException: se ha producido un error durante el procesamiento por lotes: ORA-00972: identifier is too long
 [1]
org.adempiere.exceptions.AdempiereException: Migration 600 - ReplenishPlan_DisplayedGrid - 3.9.0 (D) ; Step: 430; Type: SQL.  Application failed. 
java.sql.BatchUpdateException: se ha producido un error durante el procesamiento por lotes: ORA-00972: identifier is too long

	at org.compiere.model.MMigration.apply(MMigration.java:172)
	at org.compiere.model.MMigration.apply(MMigration.java:170)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)
	at org.eevolution.service.dsl.ProcessBuilder.run(ProcessBuilder.java:208)
	at org.eevolution.service.dsl.ProcessBuilder.access$200(ProcessBuilder.java:53)
	at org.eevolution.service.dsl.ProcessBuilder$1.run(ProcessBuilder.java:281)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.eevolution.service.dsl.ProcessBuilder.execute(ProcessBuilder.java:278)
	at org.compiere.process.MigrationFromXML.applyMigration(MigrationFromXML.java:181)
	at org.compiere.process.MigrationFromXML.lambda$loadFile$0(MigrationFromXML.java:163)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.compiere.util.Trx.run(Trx.java:495)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:141)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:107)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:49)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
caused by: org.adempiere.exceptions.AdempiereException: Migration 600 - ReplenishPlan_DisplayedGrid - 3.9.0 (D) ; Step: 430; Type: SQL.  Application failed.

**Comment by SusanneCalderon** [comment]
Committed ,  waiting for test

**Comment by e-Evolution** [comment]
02:23:58.932   MigrationFromXML.loadFile: Loading file: /Users/e-Evolution/Develop/ADempiere/adempiere/install/build/Adempiere/migration/380lts-release/00600_4040_#830_MiniMRP_Run_DisplayedGrid.xml [1]
02:23:58.935   MigrationFromXML.lambda$loadFile$0: Migration 600 - ReplenishPlan_DisplayedGrid - 3.9.0 (D)  ---> Migration already applied - skipping. [1]
