### ISSUE TITLE
The smart browser title column not translate the context language 

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#845]
@yamelsenih the VBrowserTable and WBrowserTable implementation not translate the column header for language context.

![captura de pantalla 2017-03-18 a la s 01 01 32](https://cloud.githubusercontent.com/assets/786968/24069799/86ad9648-0b76-11e7-810f-069272012c88.png)

**Comment by yamelsenih** [comment]
Hi @e-Evolution it is working now, see:
![issue12](https://cloud.githubusercontent.com/assets/2333092/24174095/445572e2-0e65-11e7-929d-dba90e291721.png)
