### ISSUE TITLE
Add new columns for Concept Attribute

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#854]
Is nice to have some columns for get values from attributes on payroll process, currently the table HR_Atttribute have the follow columns:

- HR_Payroll_ID
- HR_Department_ID
- HR_Job_ID

I propose add the follow columns:

- HR_Contract_ID
- HR_ShiftGroup_ID
- HR_WorkGroup_ID
- HR_Grade_ID
- HR_Degree_ID
- HR_Race_ID
- HR_CareerLevel_ID
- HR_JobEducation_ID
- HR_EmployeeType_ID
- HR_JobType_ID
- HR_SkillType_ID
- C_Activity_ID
- C_Campaign_ID
- C_Project_ID

**Comment by e-Evolution** [comment]
Add AD_OrgTrx_ID too

**Comment by e-Evolution** [comment]
And may be :

HR_Designation_ID 
HR_SalaryRange_ID
HR_SalaryStructure_ID

**Comment by yamelsenih** [comment]
Also is nice to have the EmployStatus
