### ISSUE TITLE
XML 00430_665_Add_New_User_Account_Dimensions.xml has no rollback statements

### ISSUE THREAD

**Issue by SusanneCalderon** [adempiere/adempiere#856]
You cannot rollback this XML, there are no rollback statements defined.
Every step includes up to 20 sqls, they are not ordered by function, for example insert and update.
If you have rearranged some windows in an operative database it is difficult to exclude the updates of the fields, as you can do it if with migration steps type update.

**Comment by e-Evolution** [comment]
@SusanneCalderon , but I executed this script without some problem, what is the error to replicate and fix.

this script is imposible add rollback statements so that was generate with old approach using sql statement.

I test this for postgresql and oracle , and I got successful execution
