### ISSUE TITLE
Add field Record_ID to Print Format "GardenWorld -> Accounting Fact Details"

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere#868]
In ZK, HTML view, this will allow the field to be displayed as a magnifying glass, which when clicking on it, will navigate to the document.

In the  _Print Format_  named _GardenWorld -> Accounting Fact Details_, add the field _Record_ID_ to the end of the _Display Order_ tab:
![20170327_fact_acct_printformat_01](https://cloud.githubusercontent.com/assets/1789408/24382033/07cefe50-1311-11e7-8c1b-efc05a67c059.png)

When calling the report _Account Fact Details_ and selecting the _HTML_ view, a magnifying glass will be displayed for _Record_ID_:
![20170327_fact_acct_printformat_02](https://cloud.githubusercontent.com/assets/1789408/24382084/3f29e0ae-1311-11e7-8541-a347d1d8836d.png)

When clicking on the magnifying glass, the document causing the record will be displayed:
![20170327_fact_acct_printformat_03](https://cloud.githubusercontent.com/assets/1789408/24382131/837c1a88-1311-11e7-8fa3-742a9de04029.png)

**Comment by marcalwestf** [comment]
I don't know if this is possible without creating a whole new Print Format, as there is no print format defined and it is created when calling if for the first time....

**Comment by e-Evolution** [comment]
This functionality was tested, but is very important know that when using Record_ID you need to be included AD_Table_ID , this way the UI can solve by context what window is  open.

**Comment by adaxa-steven** [comment]
If the 'table' is needed then something has been missed. Jo did a change so that you did NOT have to have the table column in the print format. Before the change it was necessary.

**Comment by marcalwestf** [comment]
@adaxa-steven thanks for the expalnation. 
Do you by chance know what the change was?

**Comment by marcalwestf** [comment]
thnaks @adaxa-steven , I got the issue in Adaxa's repo 
But I see there that in the image from Adaxa's repo there is also a referene to Table_ID:
![line_id_link](https://user-images.githubusercontent.com/1789408/27012016-4e1b0d90-4e85-11e7-9528-e1d9296d6d74.png)

**Comment by adaxa-steven** [comment]
fron adaxa.testadempiere.com just now...
no table column in the report...
![image](https://user-images.githubusercontent.com/15791084/27033446-ac8084b8-4fbc-11e7-9d03-71f7b032e0be.png)

still drills through on record number 
![image](https://user-images.githubusercontent.com/15791084/27033476-cf086316-4fbc-11e7-8af6-287333ccd9d1.png)

**Comment by marcalwestf** [comment]
@adaxa-steven  ... good to know that is works. 

Perhaps the reason for the differences could be that in the repository available to us (https://sourceforge.net/p/adempiere/contribution-adaxa/ci/adaxa_1.6/tree/ ) the new changes are missing? 

As I only have access to this repository, I don't know if we have access to the latest sources.

**Comment by marcalwestf** [comment]
.... committed changes provided by Jo Trinidad (Adaxa).
I run the report and now it is not needed to include the Table in order to navigate.
Ad some important reporting classes were concerned, I did also some tests on different reports. No error was produced.
Please do also test as well.

**Comment by e-Evolution** [comment]
With the last commit the functionality are working perfectly , thank a lot @marcalwestf and @adaxa-steven
