### ISSUE TITLE
"Table not found" Exception when trying to change name to Element User1_ID

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere#872]
Error reported by Steven.

When trying to change the name of the  _Element User1_ID_ to another name, a _Table not found_ Exception is thrown.
![20170328_saveelement_01](https://cloud.githubusercontent.com/assets/1789408/24420586/99cefbd0-13b0-11e7-8b39-96f119bc18de.png)

The exception is thrown in _MColumn.validLookup()_, when trying to change the name to _User_1_  in view _RV_OrderLine_Storage_ :
```
public static void validLookup(String p_ColumnName, int p_AD_Reference_ID, int p_AD_Reference_Value_ID) {
 if(p_ColumnName == null||p_ColumnName.trim().length() == 0 || !DisplayType.isLookup(p_AD_Reference_ID)) {
    return;
  } else {
  String m_TableName = p_ColumnName.replace("_ID", "");
  if(p_AD_Reference_ID == DisplayType.TableDir) {
      if(!p_ColumnName.endsWith("_ID"))
          throw new AdempiereException("@Reference@ @of@ @ColumnName@ @NotValid@");
      // Valid Table
      MTable table = MTable.get(Env.getCtx(), m_TableName);
```
**The exception is thrown in the last statement.**

The reason: in _RV_OrderLine_Storage_, for User1_ID the column is defined as _Table Direct_. In this case, Adempiere looks for a table named _User1,_ which does not exist.
![20170328_saveelement_02](https://cloud.githubusercontent.com/assets/1789408/24421502/a93130cc-13b3-11e7-94c1-91efb899d823.png)

Same happens with _User2_ID_.

**Solution: correct _Reference_ and _Reference Key_ for both _User1_ID_ and _User2_ID_.**
![20170328_saveelement_03](https://cloud.githubusercontent.com/assets/1789408/24421679/380d1a9a-13b4-11e7-99fa-459e774495db.png)

This has to be done in the Application Directory, either manually or with a XML script.

**Comment by e-Evolution** [comment]
Mario, I think that you not should change the name of a element, in all case we should change in UI based on name defined in account scheme element

**Comment by marcalwestf** [comment]
Victor that is right, I agree with you that it is recommendable not to do it. 
But if it is technically possible and somebody wants to do it, it should go without problem.

In our case, the problem found was that view _RV_OrderLine_Storage_ has both _User1_ID_ and _User2_ID_ wrongly configured. This is evidently a bug and solved with the commit.

**Comment by yamelsenih** [comment]
Hi @marcalwestf i think that **RV_OrderLine_Storage** has both **User1_ID** and **User2_ID** wrongly configured.

It can be changed.

**Comment by liosc** [comment]
Had it tested by Maurizio. It seems ok.

**Comment by yamelsenih** [comment]
If it is ok then i will close it issue/
