### ISSUE TITLE
Incorrect Entity type for Migration Scripts Column="EntityType">U</Data>

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#874]

**Comment by e-Evolution** [comment]
![captura de pantalla 2017-03-28 a la s 13 16 55](https://cloud.githubusercontent.com/assets/786968/24423026/e0ea8ed2-13b8-11e7-825f-dbefab00626e.png)

**Comment by marcalwestf** [comment]
A merge to repo adaxaFinReports should be done so both have the same changes.

**Comment by marcalwestf** [comment]
@adaxa-steven Steven, I think Victor assigne it to you because it may interest you to get your XML migration files clean, so that all Application Dictionary objects do get the Entity Type=Dictionary.
This may be useful when migrating clients from legacy implementations.
