### ISSUE TITLE
Multiple selection not work in info window i.e. Allocation Payment

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#88]
The multiple selection not work , for example allocation payment before version 380 , but the check and now not work, it was introducing with this changes https://github.com/adempiere/adempiere/commit/83d1957906bf8bd59a4478f341e5eb34f97952ff#diff-c2fc71cd1bdc4c20ca308b02b645020b MiniTable.java class before are work.

**Comment by mckayERP** [comment]
Pull request submitted with the fix.
