### ISSUE TITLE
Allow "Delete Entities" form to be accessible only for role "System Administrator"

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere#880]
Hint by Steven.

The _Delete Entities_ form is configured so that it is accessible from within the GW client.

Better is when _Delete Entities_ is accessible only from the _System Administrator_ login and when you use it you must select which Client you want to delete from.

Delete Entities can kill the whole system .. you can for instance choose to delete from ad_client_id for the gardenworld client ... and in 2 minutes you have no more GardenWorld.

**Comment by e-Evolution** [comment]
@marcalwestf is necessary the implementation for Swing because now only is available for WEB and not is right .

![captura de pantalla 2017-03-28 a la s 15 55 45](https://cloud.githubusercontent.com/assets/786968/24429409/2a342010-13cf-11e7-88b6-b91b0bed4eac.png)

**Comment by adaxa-steven** [comment]
seems to work ok in swing in adaxa.testadempiere.com

![image](https://cloud.githubusercontent.com/assets/15791084/24430061/91d4fa1e-1460-11e7-897b-07e2338a43d3.png)

**Comment by marcalwestf** [comment]
This was committed into Adempiere 3.8 by Suman, when he was Release Manager. 
Here the commit: https://github.com/adempiere/adempiere/commit/e27bc2ec439354539151c46a9217752fcdf7e0bf .
Perhaps he forgot to commit the code for Swing?

**Comment by marcalwestf** [comment]
... at least now it is only possible as System Administrator.
Perhaps we can take it from Adaxa's repo? Here is the commit: https://sourceforge.net/p/adempiere/contribution-adaxa/ci/a1e99f3b305f

**Comment by e-Evolution** [comment]
@marcalwestf if @adaxa-steven have the source code for this then we can included , you need change WDelete to VDelete the form engine got the right class for UI

**Comment by adaxa-steven** [comment]
Will send link in 1 hour

**Comment by yamelsenih** [comment]
Hi, it is nice. I can help you to include on ADempiere with something changes...

**Comment by yamelsenih** [comment]
Hi guys, i am working with it...

**Comment by yamelsenih** [comment]
It is not MVC, will change to MVC for make more easy any migration for other platform

**Comment by yamelsenih** [comment]
The name is many generic, i propose change it for **VDeleteEntity**

**Comment by yamelsenih** [comment]
Hi, i change it to **MVC** and changed the name for support to Swing interface, also change the it for add the rows number, see the image:
![issue26](https://cloud.githubusercontent.com/assets/2333092/24582287/446411c4-16fa-11e7-9627-45384634388f.png)
![issue27](https://cloud.githubusercontent.com/assets/2333092/24582288/4468b18e-16fa-11e7-9c5e-cc0dd463531b.png)
