### ISSUE TITLE
Updating fonts and print paper

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere#882]
Contribution by Jacken Chan / Steven Sackett.

Description

- Set Print Font = San Serif 9 for all report listing
- Set Landscape paper from Letter to A4 for all report listing
- Set Portrait paper from Letter to A4 for all report listing

A better standard for reports.

**Comment by marcalwestf** [comment]
..thanks Steven for the file with the changes...

**Comment by e-Evolution** [comment]
this change was included and are working
