### ISSUE TITLE
Enable Workflow Process Client 

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#883]
The migration script 01140-940_EnableWorkflowProcessClient.xml From adaxaFinReports repository by # 940 (Adaxa)

Steven Can give an explain about this functionality?

**Comment by adaxa-steven** [comment]
it is a sql migration script from Idempiere from a long time ago that we merged in.
Please see here... 
https://idempiere.atlassian.net/browse/IDEMPIERE-73
"Any Workflow Node with Action type "Wait/Sleep" does not wait for entered Wait Time field"

**Comment by marcalwestf** [comment]
XML _01140_883_940_EnableWorkflowProcessClient.xml_ does change the table access level for tables _AD_WorkflowProcessor_ and _AD_WorkflowProcessorLog_ to 6 (_System+Client_).

This way, it is possible to change the fields of the Workflow without having to log in as _System Administrator_.
