### ISSUE TITLE
Recent Items in Dashboard

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#884]
Recent items in dashboard.

> Additional comment by @marcalwestf on June 16th, 2017:
> Original issue : https://github.com/marcalwestf/adaxaFinReports/issues/40 . Here it is explained how to configure recent items.

- A nice funcionality from the Adaxa repo.
- Displays in the dashboard the last entries a user has worked at for a client.
- This is a handy help which avoids having to write down or remember the last items a user was working at.

![01_20170312_recent_items](https://cloud.githubusercontent.com/assets/1789408/23825204/10ba0474-064b-11e7-8912-1faf828fac62.png)

Definitions in window "System Configuration"

- Max number of records to show on recent items dashboard
- Max number of records to save on recent items table per user/client
![03_20170312_recent_items](https://cloud.githubusercontent.com/assets/1789408/23825224/7ad04292-064b-11e7-80d4-2b36c42f8a99.png)
![04_20170312_recent_items](https://cloud.githubusercontent.com/assets/1789408/23825225/7ad0520a-064b-11e7-8087-76b196c3d452.png)

**Comment by adaxa-steven** [comment]
It is useful and it was copied from Idempiere .. please ensure it is appropriately credited.

**Comment by e-Evolution** [comment]
Hi Mario , Steven !

I now can look of new dashboard for User Favorites.

When are testing ask me , how can remove a menu that included before , and not found a way is a feature that is missed ?


![i277 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/786968/25139206/76b16b12-2411-11e7-879e-2dce77e50c90.png)

**Comment by yamelsenih** [comment]
Hi, it is only supported on view for ZK UI, i think that should be own controller. Also is nice know if is better use the AD_ChangeLog for it

**Comment by yamelsenih** [comment]
Hi, what is the XML for it feature? i look a delete here https://github.com/marcalwestf/adaxaFinReports/commit/81f521892b6c45b515b3d15092509ff83c3de13d

**Comment by yamelsenih** [comment]
Hi, i add some changes for it:
- Now exists a custom Max Recent Item to Save and Max Recent Item to Shown on user window:
![ri4](https://user-images.githubusercontent.com/2333092/27256580-a1f9965a-5387-11e7-860a-9bf73ad32d2f.png)
- The event listener is added to swing window
- All option launch from menu is added to recent item (example: If you launch a process it is added to recent item).
- Now any column flagged as identifier is show on record (Before it only showed: **Value**, **DocumentNo**, **Name** or **Description**).
![ri](https://user-images.githubusercontent.com/2333092/27256602-399d046a-5388-11e7-8345-e8f557f4dfed.png)
- Now exist a popup menu for refresh left panel on swing:
![ri1](https://user-images.githubusercontent.com/2333092/27256612-8afd9400-5388-11e7-82f8-03570d8466ca.png)
- If you select **Remove from Bar option** it is supported for Recent item and remove it.
![ri2](https://user-images.githubusercontent.com/2333092/27256616-ac0a025a-5388-11e7-8c5c-c607b378626e.png)
- Also is added default icon for option on popup menu:
![ri3](https://user-images.githubusercontent.com/2333092/27256619-bdcfa24c-5388-11e7-8304-d8b2934a78b8.png)

**Comment by yamelsenih** [comment]
NPE when try add recent item from ather recent item

**Comment by marcalwestf** [comment]
just as an addition: here an image to configure _Recent Items_:
![20170618_recentitems_01](https://user-images.githubusercontent.com/1789408/27261181-cee54876-53fa-11e7-956a-41a2528c8b88.png)

**Comment by marcalwestf** [comment]
@yamelsenih successfully executed _02790_884_AddColumnForRecentItems.xml_ .
The recent items display as you explained. I had first to logout/login + refresh in order to get them.

In interesting point of discussion would be to have them in the upper side of the favorites (as it is now) or in the lower side. I suppose it is a matter of taste. A case of _SystemConfiguration_?

**Comment by yamelsenih** [comment]
Hi @marcarwesf I add it above favorite item because is the more use by default but it can be changed if is added a system config variable.

Is nice you proposal.

**Comment by yamelsenih** [comment]
When i try run ADempiere for apply migration files it return a error:
<pre>
-----------> Msg.getMsg: NOT found: BarRefresh [1]
-----------> MUser.get_Value: Column not found - RecentItemsMaxSaved [1]
ADempiere starting: org.compiere.apps.AMenu - java.lang.IllegalArgumentException: Table Name Not Found - AD_RecentItem
java.lang.IllegalArgumentException: Table Name Not Found - AD_RecentItem
	at org.compiere.model.Query.<init>(Query.java:128)
	at org.compiere.model.MRecentItem.getFromUserAndRole(MRecentItem.java:341)
	at org.compiere.model.MRecentItem.deleteExtraItems(MRecentItem.java:439)
	at org.compiere.model.MRecentItem.deleteExtraItems(MRecentItem.java:462)
	at org.compiere.grid.tree.VTreePanel.initTree(VTreePanel.java:334)
	at org.compiere.apps.AMenu.<init>(AMenu.java:164)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at org.compiere.Adempiere.main(Adempiere.java:612)
</pre>
