### ISSUE TITLE
System config Google Map

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#886]
Can you please elaborate ?

**Comment by adaxa-steven** [comment]
sorry - no idea

**Comment by e-Evolution** [comment]
Hi @adaxa-steven I only have a  #950(Adaxa) 147-AD_SYSTEM-GoogleMap

**Comment by e-Evolution** [comment]
Now is working relation #1150

**Comment by e-Evolution** [comment]
now allow see map location

![captura de pantalla 2017-07-07 a la s 18 23 43](https://user-images.githubusercontent.com/786968/27984036-df74a1a0-6390-11e7-941d-0060f144dcb6.png)

New icons to route and map
![captura de pantalla 2017-07-08 a la s 03 45 13](https://user-images.githubusercontent.com/786968/27984039-e4441012-6390-11e7-8290-4d271ca2b590.png)

Add route icon location component.

![captura de pantalla 2017-07-08 a la s 03 45 04](https://user-images.githubusercontent.com/786968/27984041-e751911c-6390-11e7-8f8a-a638267dd563.png)

New map route , thank a lot Adaxa to contribution.

 
![captura de pantalla 2017-07-08 a la s 03 45 37](https://user-images.githubusercontent.com/786968/27984068-48d201ec-6391-11e7-8d48-74c4f1f27fcf.png)
