### ISSUE TITLE
Barcode Text Print

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#890]
Can you please elaborate ?

**Comment by adaxa-steven** [comment]
pls provide to the change so we can review

**Comment by marcalwestf** [comment]
It implements printing barcodes.

Here the steps how to verify the functionality under http://188.40.37.194:49269/webui/index.zul : 

1.-  Open window _Shipment (customer)_ and select DocumentNo 600003:
![20170711_webui_04](https://user-images.githubusercontent.com/1789408/28099081-6674da42-6677-11e7-86cc-fe8e3395e77c.png)

2.- Click on _Print_ icon. The report is displayed.
ZK:
![20170711_webui_05](https://user-images.githubusercontent.com/1789408/28099120-a13bb2cc-6677-11e7-864b-1b386fb8b404.png)
..and Swing:
![20170711_webui_08](https://user-images.githubusercontent.com/1789408/28099124-acfeafd8-6677-11e7-87a9-2842adbddb66.png)

3.- How to configure it?
Open Print Format of the report. It is Shipment Header; go to Print Format Item _DocumentNo Barcode_ to see how the barcode of the shipment is configured:
![20170711_webui_06](https://user-images.githubusercontent.com/1789408/28099194-020ba422-6678-11e7-8e16-cedbbf712daa.png)

4.- and still in the print format, navigate from print format item _Shipment/Receipt_ to print format _Shipment line_ and there to print format item _UPC_:
![20170711_webui_07](https://user-images.githubusercontent.com/1789408/28099241-6e5cdec0-6678-11e7-90df-05a3b18e9185.png)
