### ISSUE TITLE
Print Format Is Print Parameters

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#891]
If selected, query parameters will be printed at the start of the report.

Can you please elaborate ?

**Comment by e-Evolution** [comment]
contribution from #953(Adaxa)

**Comment by adaxa-steven** [comment]
standard reports always print the report parameters. this tick box lets you choose not to print them
see page 13 and 14 of Adaxa Reporting Changes 2015-09.pdf attached to other tickets.
