### ISSUE TITLE
Print item display logic

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#892]
Can you please elaborate ?

**Comment by e-Evolution** [comment]
Contribution #1590(Adaxa)

**Comment by adaxa-steven** [comment]
in (say) the aging report you will see lots of values that are shown as zero.  this allows you to set display logic to say only display if value not zero.

**Comment by yamelsenih** [comment]
Hi @e-Evolution @adaxa-steven @marcalwestf it is good, i test it and worked.

Is nice to have a DisplayLogic on **AD_PrintFormat** table for hide a row when it don't have a value.
