### ISSUE TITLE
Financial Report Header Print Format

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#893]
Can you please elaborate contribution  #1610(Adaxa)?

**Comment by adaxa-steven** [comment]
see document attached to 899.

**Comment by marcalwestf** [comment]
The Print Format and Print Format Items IDs are in the range > 1000000.
This can clash with the IDs of customers which are migrating from former versions to 3.9.
The Print Format has to be re-created using the centralized IDs.

**Comment by marcalwestf** [comment]
![20170330_pf_01](https://cloud.githubusercontent.com/assets/1789408/24519470/814c845e-1542-11e7-9825-090157d55e29.png)

**Comment by e-Evolution** [comment]
This new functionality is working and was tested
