### ISSUE TITLE
Financial Report Enhanced for header

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#896]
Can you please elaborate 01320-1640_financialreport_changes_for_header.xml #1640(Adaxa)?

**Comment by adaxa-steven** [comment]
see document attached to 899.

**Comment by e-Evolution** [comment]
[Adaxa Reporting Changes 2016-09.pdf](https://github.com/adempiere/adempiere/files/880905/Adaxa.Reporting.Changes.2016-09.pdf)

**Comment by e-Evolution** [comment]
this new functionality was tested and are working
