### ISSUE TITLE
Add User List1 And User List2  Combination

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#897]
Can you please elaborate ? User List1 And User List2 In Combination #3060(Adaxa)

**Comment by e-Evolution** [comment]
Is necessary added User List 3 and User List 4

**Comment by e-Evolution** [comment]
Is necessary Added constraint for Oracle

<Step DBType="Postgres" SeqNo="130" StepType="SQL">
      <SQLStatement>ALTER TABLE t_report DROP CONSTRAINT t_report_pkey;
ALTER TABLE t_report
  ADD CONSTRAINT t_report_pkey PRIMARY KEY(ad_pinstance_id, pa_reportline_id, record_id, fact_acct_id, c_validcombination_id);</SQLStatement>
    </Step>

**Comment by adaxa-steven** [comment]
In Financial Reports in the  Line definition and the Column definition you can specify where the data is to come from (see third tab)  One of the options is Combination. UserList1 and 2 were for some reason not available.

**Comment by yamelsenih** [comment]
Hi @All i think that a constraint for a volatile table is unnecessary. A reference is good on tables that are used on transaction but a temporal table is not good.
