### ISSUE TITLE
Default Period for Financial Report

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#898]
Can you please elaborate  #3090(Adaxa) ? 01340-3090_#1342_Default_Period_for_Financial_Report.xml

**Comment by adaxa-steven** [comment]
see document attached to 899.

this is some sql added to the period paraemeter in the Fin Reports report and process that automtically selects a period for you .. if today is in March 2017 then it will select February 2017

**Comment by e-Evolution** [comment]
[Adaxa Reporting Changes 2016-09.pdf](https://github.com/adempiere/adempiere/files/880905/Adaxa.Reporting.Changes.2016-09.pdf)

**Comment by e-Evolution** [comment]
Script define the default period based on current date
