### ISSUE TITLE
Report source on column

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#899]
Can you please elaborate Report source on column #4600(Adaxa) script 01350-4600_ReportSourceOnColumn.xml?

**Comment by adaxa-steven** [comment]
it is all explained here!
[Adaxa Reporting Changes 2016-09.pdf](https://github.com/adempiere/adempiere/files/880905/Adaxa.Reporting.Changes.2016-09.pdf)

**Comment by marcalwestf** [comment]
Thanks Steven for the detailed description!

**Comment by iscapnet** [comment]
This contribution is Great! I am eager to start using it. It makes reporting so much more user friendly. Thank you!

**Comment by e-Evolution** [comment]
Currently was added but have conflict the posting type from Report source on line , not are work rightly

**Comment by adaxa-steven** [comment]
Please provide information to reproduce this error and an address for a test system to re-test it.  I tested it before and it worked the way it was designed.

**Comment by e-Evolution** [comment]
The must importantes was executing using a single dimension. 

We continue tomorrow with test based on  financial report more complex.

Pending testing using source based on a combination , this testing will finish tomorrow.

working process.....

kind regards
Victor

**Comment by e-Evolution** [comment]
This functionality was testing and working
