### ISSUE TITLE
Show opposite sign

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#903]
Can you please elaborate 01400_5850_Show_opposite_sign.xml #5850(Adaxa)?

**Comment by adaxa-steven** [comment]
allows you to switch signs in a financial report on a variance column.
If the Report Line and the report column are both ticked as 'switch' then the value in the intersection is multiplied by -1
so if actual rev is less than budget revenue you can force a negative value variance (ie bad)

**Comment by e-Evolution** [comment]
I tested  this functionality and are work perfectly
