### ISSUE TITLE
System Config report display Yes - No

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#905]
Can you please elaborate  01430_SysConfig_REPORT_DISPLAY_YES_NO.xml ?

**Comment by adaxa-steven** [comment]
converts  tick and cross icon to Y and N.  reduces report preparation time and report file size
![image](https://cloud.githubusercontent.com/assets/15791084/24486735/4c4344ae-1557-11e7-8279-88b8b9565b3e.png)

**Comment by e-Evolution** [comment]
@adaxa-steven @marcalwestf thank you a lot , I testing and are working.
