### ISSUE TITLE
Print Format on process dialog window

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#907]
Can you please elaborate ? Print Format and Output Type on Process Dialog ?

**Comment by adaxa-steven** [comment]
see here..
https://github.com/marcalwestf/adaxaFinReports/issues/28

**Comment by e-Evolution** [comment]
before you run a report you should be able to select the Print Format and the Output type before you run the report.

add XLSX as one of the available output types

fixed - testing in Jo build.... see bottom of screen shot
![image](https://cloud.githubusercontent.com/assets/15791084/20255902/5874b4ac-aa94-11e6-9f3e-f576ee6119ed.png)

**Comment by e-Evolution** [comment]
Fixed and the swing implementation was included
