### ISSUE TITLE
Business Partner window added Trial Balances

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#909]
Hi Mario
The following functionality was offered for 390 inclusion (the 4 buttons below).  The AR Trial Balance is less obvious than the others.  Trying to understand how it works and what it should do without having an example report is quite confusing.  If the AR Trial Balance (and AP) is taken up we suggest that the print format(s) is also included in the seed database.

On the BP Customer (and vendor) 4 buttons are added that just run existing reports and pass the BP ID across as a parameter when the report runs
![image](https://cloud.githubusercontent.com/assets/15791084/24077923/9831e7f2-0cb1-11e7-8f81-0eaf4c4e7a2a.png)

The interesting ones are the AR Trial Balance (and AP Trial Balance)
![image](https://cloud.githubusercontent.com/assets/15791084/24077958/67df3cf2-0cb2-11e7-9ecc-13656427660d.png)

the text displayed by the Report and Process should be edited!

it lets you run a report and specify the start date to use for the opening balance. It gets the data from the AR Control account for all POSTED transactions as at now commencing on the selected start date (standard Trial Balance behaviour). The default start date is set by sql in the report and process parameters to be the first day of the month from 3 months before today .. but can be overwritten.

The report can look like this (you don't need to display the account column.. just forgot to remove it)
![image](https://cloud.githubusercontent.com/assets/15791084/24077970/af78ecac-0cb2-11e7-83fd-40fd0e2ca265.png)

Note the following .. the GL Category is a useful descriptor of what the transaction is .. so Payment Allocation gets its own GL Category for instance.  Other GL Categories can be added or renamed and then selected into the appropriate Document Type records.
The GL transactions are pulled from the AR Control account of the selected BPartner defined in the BPartner's Accounting record.
The Date column (Date Account2) is created from Date Account with a case statement saying 
'if 'table' is null Dateaccount2 = Dateaccount less one day"  
The report is sorted by this column and it ensures that the opening balance of the GL Trial Balance report sorts as the first row because it will be the earliest date. (only the "Open Balance" row has null in 
the table column)
On the Allocation rows the Payment Column and the Invoice Column is looked up from the Allocation line. (invoice column in report is presently broken).  It is very useful to be able to directly see for each Payment Allocation entry which Payment is involved and which invoice is involved. 

As I recall, all the above just required AD changes but there were a number of migration scripts created before we cleaned out all the bugs ... and it looks like the invoice column still has not been applied in the adaxa.testadempiere.com demo site.

Hi Mario
report version with the 'invoice' virtual column added.
![image](https://cloud.githubusercontent.com/assets/15791084/24086610/d07f152a-0d66-11e7-9b82-fe6d29b69495.png)

![image](https://cloud.githubusercontent.com/assets/15791084/24086619/138ed788-0d67-11e7-8ec0-252e7933b3c3.png)

column sql
(SELECT C_Invoice_ID FROM C_AllocationLine WHERE C_AllocationLine_ID=Line_ID AND AD_Table_ID=735)

hi Steven,
digging into the matter, I notice that for the _Not Posted Invoice_ process in Adaxa's demo site http://adaxa.testadempiere.com/webui/ has not defined any report view nor classname:
![20170319_tr_04](https://cloud.githubusercontent.com/assets/1789408/24087456/df17b81c-0ce4-11e7-932a-4d9bbde34cbb.png)

In the corresponding xml migration file, I can confirm that there's none defined:
![20170319_tr_05](https://cloud.githubusercontent.com/assets/1789408/24087466/05abfcae-0ce5-11e7-9735-e9d1284d7cec.png)

If I run the process by pressing the button and typing in a date:
![20170319_tr_06](https://cloud.githubusercontent.com/assets/1789408/24087499/7f0f134c-0ce5-11e7-88e0-e8d0f3232bef.png)

The result is -as expected- nothing.

I wonder if there is one view to choose or there is a xml missing where the view is created?

its a bug ... needs a filter of AD_Table_ID=318 and IsSoTrx='y'
(and N in the AP version)

With the latest commit, the processes wesre created, including the Print Format for the process _AR Trial balance_
![20170319_tr_10](https://cloud.githubusercontent.com/assets/1789408/24089738/7d8582bc-0cff-11e7-8805-875e521c3566.png)

Pressing the button _AR Enquiry_ from the _Client_ tab in the _Business Partner_ window:
![20170319_tr_08](https://cloud.githubusercontent.com/assets/1789408/24089667/d6fc8a94-0cfe-11e7-8db1-b9c5ec6492f8.png)

... yields the following report
![20170319_tr_09](https://cloud.githubusercontent.com/assets/1789408/24089671/dcfaff3e-0cfe-11e7-9553-dd32b8087d49.png)

I had to allow manually the 5 processes to the "Garden World Admin" role.
Unluckily, this didn't make it into the xml file, so this has to be done manually.
![20170319_tr_07](https://cloud.githubusercontent.com/assets/1789408/24089703/24ee1ba0-0cff-11e7-974f-7e1cb54f2750.png)

I used this description in the Report and Process for the AR and AP Trial Balance...
"Optionally modify the defaulted date range. The report will display any opening balance at the "from" date and all POSTED transactions within the date range in the Business Partners AR Control account defined in the Business Partner > Accounting tab"

**Comment by e-Evolution** [comment]
![captura de pantalla 2017-06-05 a la s 12 07 06](https://cloud.githubusercontent.com/assets/786968/26794516/8e397d6e-49e7-11e7-8415-3ef502d09fbd.png)


AR Trial Balance by Business Partner working

**Comment by e-Evolution** [comment]
The open invoice by Business Partners is working

![captura de pantalla 2017-06-05 a la s 12 15 30](https://cloud.githubusercontent.com/assets/786968/26794846/edf9b1dc-49e8-11e7-86d7-54d96ffb8ea2.png)

**Comment by e-Evolution** [comment]
The unallocated payment working 

![captura de pantalla 2017-06-05 a la s 12 22 40](https://cloud.githubusercontent.com/assets/786968/26795054/c17669a6-49e9-11e7-9469-2475ea65ae41.png)

**Comment by e-Evolution** [comment]
The Unposting invoices is workings 
![captura de pantalla 2017-06-05 a la s 12 27 59](https://cloud.githubusercontent.com/assets/786968/26795228/7948bc6e-49ea-11e7-9f4f-69dd3e8d3af9.png)

**Comment by e-Evolution** [comment]
The same result for AP Vendor

**Comment by adaxa-steven** [comment]
Hi Victor
the Trial Balance should look like the following.
the print format is important so the report is usable.
also, what happened with the script to fix all the fonts and get rid of the cyan colour?

![image](https://cloud.githubusercontent.com/assets/15791084/26810385/bea57aee-4aae-11e7-8c28-7b979931f082.png)
