### ISSUE TITLE
Document Status Indicators Dashboard

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#910]
Document Status in dashboard

- A nice functionality from the Adaxa repo.
- Displays in the dashboard the document/windows which meet certain conditions.
- For example: open orders, open items, unanswered requests, etc.
- This is useful for remembering the activities due for a user, role, organization.
![01_20170311_document_status](https://cloud.githubusercontent.com/assets/1789408/23825339/68526a94-064d-11e7-9b08-504e52fb28cd.png)

Declared in window "Dashboard Content Edit"
![02_20170311_document_status](https://cloud.githubusercontent.com/assets/1789408/23825345/887bc112-064d-11e7-9a7e-a89b1b2ea5e9.png)

Defined in window "Document Status Indicator", including table to be monitored, user/role, fonts, condition, window to be opened, etc.

![03_20170311_document_status](https://cloud.githubusercontent.com/assets/1789408/23825350/94d5a6e4-064d-11e7-8e7f-e707ff13a1d2.png)

One comment: as explained above, I created in Swing by hand the "Document Status Indicator" and run ADempiere.

In Swing I didn't notice that (I ignore how) there was added in the HTML field some code with html, head and body tags, which in Swing were invisible, but lead to some artifacts in the panel.
![20170308_adaxa_dashboard_panels_01](https://cloud.githubusercontent.com/assets/1789408/23919500/abaad490-08bc-11e7-8c33-7b0227e5e143.png)

Once deleted this text either in ZK or the database, the panel was displayed correctly.
Perhaps this record should be created in GW.

**Comment by e-Evolution** [comment]
Now I can see the dashboard for document status , from demo server now show a order pending , but when push doble click in row this only open of window shipment  without some information, if the dash board is ok then should open with the order that show as pending

![captura de pantalla 2017-04-18 a la s 10 43 06](https://cloud.githubusercontent.com/assets/786968/25139840/481a2ada-2413-11e7-877c-86eb6697cd3c.png)

**Comment by testiranje1234** [comment]
Loking good, but theres some problems 
1)
I m trying to solve, with test, I cant save busines parter as new employer, on version adempiere 3,7 3,8 and 3,9 is posible.
2)
This is very specific way, depends on country, I m trying to add previous work and addition for main salary per month in percent (for example for 5 years working in some company, yours month salary will be bigger for (5*0.4% per year) =2% (salary * 1.02).
This view in oracle calculate every day, months and year for every employe.

3) when employer will be retaired, when have 65 years old, for men, for women is complicate algoritam
(from 2017-2024 with 63 years old, 2025-2030 64 years old and 2031... 65 years old - localy principls)

I m trying to extend and modify adempeire 390 with this purposes, and contract for service orders
with BOQ (bill of quantity) until 1 th may, so have more questions could be this end period be extended?
regards


![adaxa_7](https://cloud.githubusercontent.com/assets/26572325/25149398/97370a1e-247e-11e7-9517-8b0e9dd51953.png)
![adaxa_5](https://cloud.githubusercontent.com/assets/26572325/25149399/973bc072-247e-11e7-8d8e-c3ee62aa34fd.png)
![adaxa_4](https://cloud.githubusercontent.com/assets/26572325/25149401/97430f80-247e-11e7-835b-0fde6adeddd6.png)
![adaxa_3](https://cloud.githubusercontent.com/assets/26572325/25149400/973bf588-247e-11e7-90e7-f27ad2298311.png)

**Comment by adaxa-steven** [comment]
re: "Now I can see the dashboard for document status , from demo server now show a order pending , but when push double click in row this only open of window shipment without some information, if the dash board is ok then should open with the order that show as pending"

captura de pantalla 2017-04-18 a la s 10 43 06

It will display whatever your sql asks for ... for us a pending shipment is an already created shipment that has not been completed.  You can display whatever you want and can define in sql.

**Comment by marcalwestf** [comment]
now it looks as follows:
![20170721_adempiere_09](https://user-images.githubusercontent.com/1789408/28500641-f52c2910-6f88-11e7-920c-6e21fa3d8c86.png)
