### ISSUE TITLE
User Favorite Tree Panel 

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#911]
User Favorites

- A nice functionality from the Adaxa repo.
- It displays in the dashboard a tree of the objects the user wants to see (windows, reports, etc.)
- The tree is configurable as the user likes
- The names of the tree nodes are free assignable
- Objects can be added by Drag&Drop and deleted by right-mouse click
- The tree can be collapsed and expanded
- The tree is persistent

![20170313_user_favorites_01](https://cloud.githubusercontent.com/assets/1789408/23879565/8c25617a-0813-11e7-9755-a01e11b5681b.png)

Declared in window "Dashboard Content Edit" (also for activating/deactivating)
![20170313_user_favorites_03](https://cloud.githubusercontent.com/assets/1789408/23879610/c8a2b60c-0813-11e7-8227-8ca891ff27c6.png)

Hi Mario
.... and you can right-mouse-click on the folder name to set a flag to say whether the folder/tree is open or closed at login.
.....and you can double-left-click the mouse to rename the folder 

you can test here pending the official Adempiere test system being available....
http://adaxa.testadempiere.com/webui/

regards

**Comment by e-Evolution** [comment]
Hi Mario , Steven !

I now can look of new dashboard for User Favorites.

When are testing ask me , how can remove a menu that included before , and not found a way is a feature that is missed ?


![i277 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/786968/25139206/76b16b12-2411-11e7-879e-2dce77e50c90.png)

**Comment by yamelsenih** [comment]
Hi @e-Evolution @adaxa-steven, it is supported on Swing GUI? Is a nice feature

**Comment by e-Evolution** [comment]
Hi @yamelsenih , nop unfortunately only wore in swing.

Adaxa deprecated oracle and Swing from your contributions :-(

If we need to swing need implement

**Comment by adaxa-steven** [comment]
We did not implement in swing but nothing has been deprecated  (and we don't implement in Oracle)

**Comment by marcalwestf** [comment]
@e-Evolution you can delete either a folder (including its children) or a leave by right-clicking over the desired item and selecting _Delete_.

**Comment by e-Evolution** [comment]
Hi @marcalwestf Mario I can replicate , thank a lot.
