### ISSUE TITLE
Trial Balance Drillable Report form & menu and Is show retained earning flag

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#913]
The Trial Balance Report is a development by Adaxa.
It allows to display summarized accounting facts in a report and navigate to the actual accounting facts.

It is available from the Adaxa repo in Commit in Adaxa repo: https://sourceforge.net/p/adempiere/contribution-adaxa/ci/5f10d7e8f8f0 .

You call the report and must type in the parameters as you please
![01-20170310_trail_balance_drillable_report_01](https://cloud.githubusercontent.com/assets/1789408/23807074/e7135e66-0589-11e7-9138-bd64562ee7ba.png)

then the report is displayed
![02-20170310_trail_balance_drillable_report_02](https://cloud.githubusercontent.com/assets/1789408/23807086/f9b81912-0589-11e7-80fe-db1a9842054c.png)

you can select none, one or several entries 
![03-20170310_trail_balance_drillable_report_03](https://cloud.githubusercontent.com/assets/1789408/23807292/d3a70156-058a-11e7-9ddb-34ca12453d6c.png)

Notice: the totals are updated!

and if you click right-mouse on a column with values , you get the following
![04-20170310_trail_balance_drillable_report_04](https://cloud.githubusercontent.com/assets/1789408/23807332/e7c66230-058a-11e7-9e26-75b53f7ba9c8.png)

... the only thing missing is the magnifying glass in the last report, so the document which caused the fact_acct is opened.

"the only thing missing is the magnifying glass in the last report, so the document which caused the fact_acct is opened."
..... the Record_ID column is what gets displayed as the magnifying glass in the html report and it zooms immediately to the underlying document

for this to work the standard 'Trial Balance' has to work and presently it throws this error (which may have been fixed since) ... it is that new User3 and User4 stuff that seems to be the cause of the error

integrate from https://github.com/marcalwestf/adaxaFinReports/issues/39

**Comment by e-Evolution** [comment]
22:03:41.938 MChangeLog.fillChangeLog: #66 [17]
22:03:41.984 MRole.get: AD_Role_ID=102, AD_User_ID=100, reload=false [17]
===========> TrialBalance.prepare: Unknown Parameter: isShowRetainedEarnings [45]

The new is Show Retained Earnings not work 

![captura de pantalla 2017-05-21 a la s 22 11 14](https://cloud.githubusercontent.com/assets/786968/26291216/79318d88-3e72-11e7-808d-6c9540a5504f.png)

@marcalwestf  What is the functionality of s Show Retained Earnings?

**Comment by adaxa-steven** [comment]
suggest undisplay it and we will review in 391

**Comment by yamelsenih** [comment]
Hi. You can set it parameter as "Only Parameter" on process parameter and it not will send to report criteria

**Comment by e-Evolution** [comment]
Yamel , I want know what is objetive or goal the  Show Retained Earnings , what is reason that was added, because when review of code, I found not some logic. so I want know because can be that we need integrate some code lines.

I ask to Mario about this and Steven

kind regards

**Comment by adaxa-steven** [comment]
Victor,
it may be incomplete functionality.  it was intended to deal with the situation as follows.
'Balance Sheet accounts' gets all the account starting with 1, 2 and 3. and should get the TOTAL Amount.
The P&L Items should get  the 'Year' value not the 'Total'.
Then we need a row, for which we do not have an account,that can display the sum of all P&L accounts up to the start of the year containing the period you have selected.  If the value is not zero and you do not display it and the user has selected the full account range then the trial balance will not balance to zero.

so ......
+ Balance Sheet accounts TOTAL
+ (P&L for all periods - P&L for this fin year)
= Shareholders funds

= P&L Accounts for this fin year
 now will balance to zero.

as I said the functionality may not be complete so either complete it or hide the retained earnings tick box.

**Comment by marcalwestf** [comment]
Parameter "isShowRetainedEarnings" is set to _inactive_ as there in no functionality implemented.
Leave the issue open for next releases to decide whether to complete implementation.
