### ISSUE TITLE
Statement of Account is hardcode

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#92]
In Process FinStatement of "Statement of Account" report is hardcode the Print format, it find the AD_PrintFormat_ID = 134, when it format is deleted is showed a error:
![issue14](https://cloud.githubusercontent.com/assets/2333092/11157848/29f3f1e0-8a26-11e5-870e-c5e6743060ca.png)
![issue15](https://cloud.githubusercontent.com/assets/2333092/11157849/29f481b4-8a26-11e5-8d90-27676c6d7df7.png)
It is bad, must be like standard report.

The line hardcoded is https://github.com/adempiere/adempiere/blob/develop/base/src/org/compiere/report/FinStatement.java#L276
The other line:
https://github.com/adempiere/adempiere/blob/develop/client/src/org/compiere/print/ReportCtl.java#L149

This issue affect to Statement of Account and Financial Report

**Comment by e-Evolution** [comment]
Hi Yamel ! Why anybody delete if format system base , not should

**Comment by yamelsenih** [comment]
Hi @e-Evolution the hardcode is bad practice, the standard funcionality of print formats in ADempiere is:
* when is run the process/report, the is finded a print format of current client.
* If the print format does not exists then is created from report view setted in Process/Report.
* The base reports are used like template for new reports generated.
* When a report is created like System client, it allow delete from any client.

**Comment by e-Evolution** [comment]
I  saw that hardcode was comments but I cannot see the code that replace of hardcode , How is now call  a financial report ?

**Comment by yamelsenih** [comment]
Hi @e-Evolution the financial report was called the same method that a standard report, the code is duplicated, see the previous code:
<pre>
static public boolean startFinReport (ProcessInfo pi)
 {
 	//  Create Query from Parameters
 	String TableName = pi.getAD_Process_ID() == 202 ? "T_Report" : "T_ReportStatement";
 	MQuery query = MQuery.get (Env.getCtx(), pi.getAD_PInstance_ID(), TableName);
 
 	//	Get PrintFormat
 	MPrintFormat format = (MPrintFormat)pi.getTransientObject();
 	if (format == null)
 		format = (MPrintFormat)pi.getSerializableObject();
 	if (format == null)
 	{
 		s_log.log(Level.SEVERE, "startFinReport - No PrintFormat");
 		return false;
 	}
 	PrintInfo info = new PrintInfo(pi);
 
 	ReportEngine re = new ReportEngine(Env.getCtx(), format, query, pi,info);
 	createOutput(re, pi.isPrintPreview(), null);
 	return true;
 }
</pre>
The standard calling to report is it:
<pre>
static public boolean startStandardReport (ProcessInfo pi)
{
	ReportEngine re = null;
	//
	// Create Report Engine by using attached MPrintFormat (if any)
	Object o = pi.getTransientObject();
	if (o == null)
		o = pi.getSerializableObject();
	if (o != null && o instanceof MPrintFormat) {
		Properties ctx = Env.getCtx();
		MPrintFormat format = (MPrintFormat)o;
		String TableName = MTable.getTableName(ctx, format.getAD_Table_ID());
		MQuery query = MQuery.get (ctx, pi.getAD_PInstance_ID(), TableName);
		PrintInfo info = new PrintInfo(pi);
		re = new ReportEngine(ctx, format, query, info);
		createOutput(re, pi.isPrintPreview(), null);
		return true;
	}
	//
	// Create Report Engine normally
	else {
	re = ReportEngine.get(Env.getCtx(), pi);
		if (re == null)
		{
			pi.setSummary("No ReportEngine");
			return false;
		}
	}
	
	createOutput(re, pi.isPrintPreview(), null);
	return true;
}	//	startStandardReport
</pre>
Best regard

**Comment by yamelsenih** [comment]
Hi @e-Evolution can you test it? for close it issue
