### ISSUE TITLE
Add role window the functionality for is Allow HTML View and is Allow XLS View

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#935]
Can you please elaborate ?

functionality include in pull request https://github.com/adempiere/adempiere/pull/932/files#diff-c2c25284d8602771a5c0faca6c0719a4

**Comment by adaxa-steven** [comment]
As I recall, we found there were circumstances where users did not have access to a particular window but they could zoom to things from within the html report which let them see the data they were not supposed to be viewing .. probably xls prevention added just for extra security ... trying to get confirmation of this now

**Comment by e-Evolution** [comment]
This functionality was testing and improve now the configurable variable is used .
