### ISSUE TITLE
"IsDocument" flag in table for create default columns

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#94]
Whe a new table is created and it is a document that have columns like DocAction, DocStatus and handle workflow, is nice to have a method for create all columns automatically.

**Comment by e-Evolution** [comment]
Hi Yamel , I think that we need xml migration script to define the current document table in application dictionary , please would create to mark this in application dictionary ?

**Comment by e-Evolution** [comment]
Hi Yamel , this commit break of build project , DocumentTemplate.BODY reference not exist

**Comment by yamelsenih** [comment]
Hi @e-Evolution the migration script is in XML from https://github.com/adempiere/adempiere/commit/ca9b2e5049261717ea35eb98780e1d2af132c1fb

**Comment by e-Evolution** [comment]
Hi Yamel I can not found of DocumentTemplate.BODY reference

**Comment by yamelsenih** [comment]
Hi @e-Evolution  this is in https://github.com/adempiere/adempiere/commit/e3e4eadf18b39c572b41903cdf844ed6c9448c4a

**Comment by yamelsenih** [comment]
See the new changes: [Spin Contribution: FR: Table like Document](http://wiki.adempiere.net/Spin_Contribution:_FR:_Table_like_Document)
