### ISSUE TITLE
Generate a GL Distribution for a different Posting Type and misc functional improvements

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#942]
Explicación: Allow overwriting the Posting Type within the distribution line.
With this new feature budget account fact can be generated out of the general ledger account.

Add support for valid from and valid to for GL Distribution 

Distribution name: Create Reservation Budget
Posting type: Actual 
Document Type: AP Invoice 
Selection ---------
Any Account: Yes    Account: Expense 

Distribution Line 10
New field -> Overwrite Posting Type:  Budget 
Overwrite Account: Yes  Account :  Commitment
Distribution Line 20

New field -> Overwrite Posting Type: Budget 
Overwrite Account:Yes  Account:  Reservation 
Change Signal Yes

Before the distribution
Expense       1000               Actual
AP Vendor                1000   Actual

Afte the distribution:
Expense        1000              Actual
AP Vendor                1000   Actual
Commitment  1000             Budget
Reservation              1000   Budget

**Comment by adaxa-steven** [comment]
Victor, are you implementing all the features we had added? I see no mention of fixed dollar amounts or mention of summing to 0% or 100% as being valid. Ability to copy an existing distribution and then edit it?

[GL Distribution changes.pdf](https://github.com/adempiere/adempiere/files/904349/GL.Distribution.changes.pdf)

**Comment by e-Evolution** [comment]
Hi @adaxa-steven Steven I will including  the Adaxa improves and new functionality

**Comment by e-Evolution** [comment]
@adaxa-steven @marcalwestf  thank you a lot , I testing and are working.
