### ISSUE TITLE
Customer RMA can't be deleted if RMA Lines exist

### ISSUE THREAD

**Issue by trifonnt** [adempiere/adempiere#954]
RMA document do not delete RMA lines, that's why ADempiere throws exception when user tries to delete RMA which has RMA Lines.
We must implement RMA.beforeDelete() method and delete all RMA Lines.

**Comment by yamelsenih** [comment]
Hi Trifont, the RMA have workflow, I think that it should be flagged on the table like deleteable flase. Also should have a constraint for delete on Cascade the lines.

Best regards

**Comment by trifonnt** [comment]
>  Also should have a constraint for delete on Cascade the lines.

Exactly, RMA Line has foreign key to RMA, that's why when user tries to delete RMA, database throws exception that RMA can't be deleted, because of the foreign key constraint.
MInOut, MOrder and other document based model classes have beforeDelete() method where they iterate all their lines and delete each line. MRMA class did not had such java method, that's why I have implemented it.

Best regards,
Trifon

**Comment by yamelsenih** [comment]
Is really, good
