### ISSUE TITLE
Invoice Line column LineTotalAmt not updated

### ISSUE THREAD

**Issue by trifonnt** [adempiere/adempiere#965]
Table C_InvoiceLine column LineTotalAmt is not updated in specific cases(when Tax is Document level and Invoice is sales Trx.)

**Comment by trifonnt** [comment]
GIT commit 1ebe44b
https://github.com/adempiere/adempiere/commit/1ebe44bbee3cfe03e2ce71106435336c6e8c750b

**Comment by marcalwestf** [comment]
Just one remark: according to Java naming conventions, only class names should be begin with capital letters. Variables (in this case TaxAmt ) should begin with lower case.
I would leave it as it was: better _taxAmt_ than _TaxAmt_.

**Comment by marcalwestf** [comment]
... one additional question: why must be the condition
`if (tax.isDocumentLevel() && m_IsSOTrx) ` ?

Wouldn't it be better to be just
`if (tax.isDocumentLevel())` ?
This way, it would work for Sales and Purchases.

**Comment by trifonnt** [comment]
Mario, you have very valid questions, but as my time was very limited, I just fixed the bug which was stoping me from working.

Name of the variable and condition should be fixed: +1
