### ISSUE TITLE
Marital Status should be part of Business partner

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#969]
Currently the Marital Status exist on **HR_Employee** and is good for history but it is a attribute of business partner, i propose add it for **C_BPartner** table

**Comment by rachmed** [comment]
hi yamelsenih ,i want to visualize Martital Statis on my adempiere insatallation ,if you can show the steps
to achieve this ,i'm new on adempiere 
thank you

**Comment by testiranje1234** [comment]
Hi yamesdenih, did you replace fields on form with two or three new field?
I notice differenties.
![dif](https://cloud.githubusercontent.com/assets/26572325/25152505/64c235bc-2489-11e7-8511-80d51cd549b2.png)

Should I again need download and reinstall all adempiere 390 from 
https://github.com/adempiere/adempiere/tree/release/3.9.0
 ?
or exist any migration script from 14.04.2017 until now?

**Comment by yamelsenih** [comment]
Hi @rachmed you can appli it https://github.com/adempiere/adempiere/commit/b3595aed75408ac90d320f52ccf14695e962d741
the changes exist on hotfix#002

**Comment by testiranje1234** [comment]
Hi yamesdenih,  on my instalation from 14.04.2017 need do b3595ae ?
Changes exist on hotfix#002
I have virtual machine with centos and idempiere 390 where I can run this
migration/380lts-release/02280_Add_MaritalStatus_BP.xml
?

**Comment by yamelsenih** [comment]
see if exists the migration applied like is showed on pic:
![issue53](https://cloud.githubusercontent.com/assets/2333092/25153235/ebab799c-2459-11e7-972f-5f98a412e61e.png)
The last XML is **2360**

**Comment by rachmed** [comment]
thank you for your response
