### ISSUE TITLE
Some additional accounting dimensions are not being posted

### ISSUE THREAD

**Issue by iscapnet** [adempiere/adempiere#978]
These additional accounting elements aren't show up in our postings:

C_SalesRegion_ID labeled as "Región de Ventas"
UserElement1_ID labeled as "Objetivo"
UserElement2_ID labeled as "Area de Interes"

**Comment by e-Evolution** [comment]
Hi @iscapnet Enrique , this part of a customization not core functionality, this now is supporting via fact account validator.
