### ISSUE TITLE
Error a xml script for oracleXE 2310,2320,2330,2340

### ISSUE THREAD

**Issue by lbetanzo** [adempiere/adempiere#980]
A la hora de darle el comando RUN_MigrateXML.bat hace todo bien hasta llegar al 2310_968_Add_Employee_Detail_Report
esto genera un error en el primer registro y lugo los sigueentes 3 que tienen que ver con empleados tambien fallan.

**Comment by yamelsenih** [comment]
Hi @lbetanzo can you put here a log for see the error?

I test it in Oracle and worked.

Best regard.

**Comment by yamelsenih** [comment]
Hi @lbetanzo i change some columns and replace view for solved it error, plest test it from Hotfix#002 branch.

Best Regard
