### ISSUE TITLE
RUN_Adempiere.bat in oracleXE and Windows 10 is not working dosent connect to database

### ISSUE THREAD

**Issue by lbetanzo** [adempiere/adempiere#986]
The RUN_Adempiere.bat  is not conecting to the database i can import and run migrationXML but when i try to connect with run_adempiere.bat dosent conectthis is in OracleXE in Windows 10

**Comment by testiranje1234** [comment]
On linux centos work perfect, I was folow this steps
1) from sqldeveloper I was creating schema ADEMPIERE390
2) run comand from comand line seting oracle_home and sid as imp steigth to >Adempeire.dmp
3) when dmp is loaded into schema, I was RUN_setup.sh (probably is same on windows)
On one database from one virtual machine, I was creating migration script, but now cant creating new cliens, should migration scripts have some bags, on other virtual machine without migration script I was creating client very well (one as AcountUS.csv other from Acount_RS.csv with eliminate one duplicate 599366 and add one with account 58800 from default account us.
Working, until I found next error

**Comment by yamelsenih** [comment]
Hi @lbetanzo i write a change for it on https://github.com/adempiere/adempiere/commit/e18680f871ccd86f6df5f29a5ef0182cd81b4892
please test and tell us about it

**Comment by yamelsenih** [comment]
I test it and apply all migration XML. It worked.

Please if you have a problem write it here.
