### ISSUE TITLE
Dependency errors, jar not found.

### ISSUE THREAD

**Issue by dixon22ma** [adempiere/adempiere#989]
Hi, In the branch of develop there are errors of dependencies for some jugs not found. View image.

![imagen](https://cloud.githubusercontent.com/assets/2453563/25078834/e0d80892-2304-11e7-82d5-bb8f011e0bf5.png)

**Comment by e-Evolution** [comment]
Hi Dixon , if this issue is the develop not can are into of 3.9.0 milestone

**Comment by dixon22ma** [comment]
Hello Victor, thanks for your advice.
