### ISSUE TITLE
Upgrade RS Accounting

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#991]
It issue is for upgrade the default accouting fact for  Russia, based on file attachment

[AccountingRS.csv.zip](https://github.com/adempiere/adempiere/files/925837/AccountingRS.csv.zip)

**Comment by yamelsenih** [comment]
Thank you to @testiranje1234

**Comment by testiranje1234** [comment]
ok, you r welcome, for us database programers this is big challenge :)
